### PR TITLE
UCX: update NEWS for v1.2.2 and version for Doxygen

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5267/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review as well

**Comment by shamisp** [comment]
Overall I don't have a problem with the content. But I have feeling that we are not very consistent in the way we structure the new. @bbenton - can you take a look here.

Another question - once we merge it and update version to 1.2.2, where do we reflect the fact that it is 1.2.2-rc1, besides the tag ? Do we have to reflect the rc1 somewhere else ?

**Comment by yosefe** [comment]
@shamisp @bbenton how should we reflect rc?

**Comment by shamisp** [comment]
👍

**Pull request merged**
