### PR TITLE
UCP/UCT/GTEST: A couple of fixes in tests

### LINKED ISSUE #1224: failure in test_ucp_tag_xfer.cc
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/624/label=master/consoleFull

9:31:29 [ RUN      ] cmrcx/test_ucp_tag_stats.sync_unexpected/0
19:31:30 /var/lib/jenkins/jobs/gh-ucx-pr__NEW/workspace/label/master/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:741: Failure
19:31:30 Expected: (cnt) > (0ul), actual: 0 vs 0

### PR DESCRIPTION
**Pull request by brminich**
- Fix in UCP unexpected test (wait for unexp msg to arrive before proceed
  with recv). Fixes #1224
- Minor typo corrections in UD test

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2681/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3199/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/728/ for details.

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2686/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2691/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2694/ for details (Mellanox internal link).

**Pull request merged**
