### PR TITLE
UCP/UCS: Warn about unused environment variables at ucp_worker_create()

### LINKED ISSUE #2953: Incorrect warning with ucx master
Seeing this when I set ```UCX_NET_DEVICES```:

```
export UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1
...
[1539371008.388533] [cn828:74988:0]         parser.c:1310 UCX  WARN  unused env variable: UCX_NET_DEVICES (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
```

If I set something that doesn't exist in that variable I get the expected warning so it **is** being used:

```
export UCX_NET_DEVICES=self,mlx5_0:1,mlx5_3:1
...
[1539370849.809991] [cn828:74750:0]    ucp_context.c:588  UCX  WARN  device 'self' is not available
[1539370849.810202] [cn828:74750:0]         parser.c:1310 UCX  WARN  unused env variable: UCX_NET_DEVICES (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2953

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8019/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8017/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8030/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8023/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8034/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8046/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8049/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8054/ for details (Mellanox internal link).

**Pull request merged**
