### PR TITLE
Edits to motivation

### PR DESCRIPTION
**Pull request by manjugv**
Some initial edits for the motivation section.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/380/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/959/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/383/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - can you please re-test it.

**Comment by shamisp** [comment]
@yosefe - can you please check what is the issue ?

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
@shamisp sometimes it fails because /dev/shm gets full

**Comment by shamisp** [comment]
when we are going to fix it ? /dev/shm !

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/965/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/390/ for details (Mellanox internal link).

**Pull request merged**
