### PR TITLE
UCP/EP/INFO: Fix ep info print when there is no wireup lane

### LINKED ISSUE #2406: ucx_info segfault for ep rma feature
```
devendar@hpchead osu-micro-benchmarks-5.3.2 (git::master)$ ucx_info -e -u r
#
# UCP endpoint
#
#               peer: uuid 0x26bea44cec748be8
[hpchead:22974:0:22974] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))

/hpc/local/benchmarks/hpcx_install_2018-03-15/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/wireup/wireup_ep.c: [ ucp_wireup_ep_remote_connected() ]
      ...
      508                                       ucp_wireup_ep_progress, wireup_ep, 0,
      509                                       &wireup_ep->progress_id);
      510     ucp_worker_signal_internal(ucp_ep->worker);
==>   511 }
      512
      513 int ucp_wireup_ep_test(uct_ep_h uct_ep)
      514 {

==== backtrace ====
 0 0x000000000002d6e0 ucp_wireup_ep_remote_connected()  /hpc/local/benchmarks/hpcx_install_2018-03-15/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/wireup/wireup_ep.c:511
 1 0x0000000000011345 ucp_ep_print_info()  /hpc/local/benchmarks/hpcx_install_2018-03-15/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/core/ucp_ep.c:1321
 2 0x00000000004023a3 print_ucp_info()  /hpc/local/benchmarks/hpcx_install_2018-03-15/src/hpcx-gcc-redhat7.4/ucx-master/src/tools/info/proto_info.c:179
 3 0x0000000000401c76 main()  /hpc/local/benchmarks/hpcx_install_2018-03-15/src/hpcx-gcc-redhat7.4/ucx-master/src/tools/info/ucx_info.c:180
 4 0x0000000000021c05 __libc_start_main()  ???:0
 5 0x0000000000401d26 _start()  ???:0
===================
Segmentation fault (core dumped)
devendar@hpchead osu-micro-benchmarks-5.3.2 (git::master)$ which ucx_info
/hpc/local/benchmarks/hpcx_install_2018-03-15/hpcx-gcc-redhat7.4/ucx/bin/ucx_info
devendar@hpchead osu-micro-benchmarks-5.3.2 (git::master)$

```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2406

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6548/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Should it go to 1.3 ? since it is a segfault, I think it should

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6565/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@brminich pls take a look

**Pull request merged**
