### PR TITLE
TEST/UCP/stream: fixed compilation

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed compilation of ucp_stream test

### CODE REVIEW

**Comment by hoopoepg** [comment]
@evgeny-leksikov you are welcome to review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4562/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
@yosefe I merged it because master was broken.
@hoopoepg thanks a lot for quick fix!

**Comment by miked-mellanox** [comment]
i thought github will not let merge if HEAD is more advanced than PR and will require to rebase and CI
somehow it did let and master got broke, right?

**Comment by evgeny-leksikov** [comment]
Yes, there is kind of race - one PR passed testing before another one was merged. Updating of master does not trigger retest

**Pull request merged**
