### PR TITLE
UCP/FLUSH: Use ucp_request_get() macro

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7007/ for details (Mellanox internal link).

**Comment by brminich** [comment]
the bgate fault looks a bit similar to #2328:
01:55:20 [ RUN      ] cm/test_uct_pending.pending_ucs_ok_dc_arbiter_bug/0
01:55:20 [     INFO ] pending queue len: 1024
01:55:30 /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/1/contrib/../test/gtest/uct/test_pending.cc:399: Failure
01:55:30 Value of: n_pending
01:55:30   Actual: 1024
01:55:30 Expected: 0
01:55:30 [  FAILED  ] cm/test_uct_pending.pending_ucs_ok_dc_arbiter_bug/0, where GetParam() = cm/mlx5_0:1 (10197 ms)

Another one is connectivity issue

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by brminich** [comment]
bot:bgate:retest

**Pull request merged**
