### PR TITLE
Variables "c" holding getopt() return need to be int rather than char.

### PR DESCRIPTION
**Pull request by tonycurtis**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/771/ for details.

**Comment by shamisp** [comment]
@miked-mellanox @yosefe - I think Jenkins misbehaves again….

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/203/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe - I don't think it is related to this bug. I saw this error in my testing as well:
```
23:39:31 [ RUN      ] test_ucp_atomic.atomic_add
23:39:32 [jenkins01:21886:0] Caught signal 11 (Segmentation fault)
23:39:32 ==== backtrace ====
23:39:32  2 0x0000000000034684 ucs_handle_error()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../src/ucs/debug/debug.c:631
23:39:32  3 0x00000000000347f4 ucs_error_signal_handler()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../src/ucs/debug/debug.c:606
23:39:32  4 0x0000003d690329a0 killpg()  ??:0
23:39:32  5 0x0000000000449c6d _ZN15test_ucp_atomic12blocking_addIjEEvPN8ucp_test6entityEmPvP8ucp_rkeyRSs()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucp/test_ucp_atomic.cc:13
23:39:32  6 0x000000000044ae25 _ZN16test_ucp_memheap18test_blocking_xferEMS_FvPN8ucp_test6entityEmPvP8ucp_rkeyRSsEm()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucp/test_ucp_memheap.cc:49
23:39:32  7 0x0000000000446bfa test<unsigned int, void (test_ucp_atomic::*)(ucp_test::entity*, long unsigned int, void*, ucp_rkey*, std::string&)>()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucp/test_ucp_atomic.cc:142
23:39:32  8 0x0000000000446bfa ??()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucp/test_ucp_atomic.cc:152
23:39:32  9 0x0000000000003abe _ZN3ucs9test_base13TestBodyProxyEv()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../src/ucs/gtest/test.cc:112
23:39:32 10 0x000000000003506d _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc()  ??:0
23:39:32 11 0x000000000002be91 _ZN7testing4Test3RunEv()  ??:0
23:39:32 12 0x000000000002bf77 _ZN7testing8TestInfo3RunEv()  ??:0
23:39:32 13 0x000000000002c0b7 _ZN7testing8TestCase3RunEv()  ??:0
23:39:32 14 0x000000000002c3ff _ZN7testing8internal12UnitTestImpl11RunAllTestsEv()  ??:0
23:39:32 15 0x0000000000034c1d _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc()  ??:0
23:39:32 16 0x000000000002b4aa _ZN7testing8UnitTest3RunEv()  ??:0
23:39:32 17 0x0000000000002ed4 main()  /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace/contrib/../src/ucs/gtest/main.cc:41
23:39:32 18 0x0000003d6901ed1d __libc_start_main()  ??:0
23:39:32 19 0x000000000040cab9 _start()  ??:0
23:39:32 ===================
```

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/779/ for details.

**Comment by shamisp** [comment]
:+1

**Comment by mellanox-github** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/781/ for details.

**Comment by yosefe** [comment]
bot:retest
ok to test

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/783/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/209/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
