### PR TITLE
UCT/UGNI/ATOMIC: added stub atomic implementation for new API

### PR DESCRIPTION
**Pull request by hoopoepg**
unfortunately I can't test this implementation, that is why it is very straightforward, but allows to test new API by gtest

### CODE REVIEW

**Comment by shamisp** [comment]
Adding @hjelmn @hppritcha @MattBBaker for review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6759/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
new commit to reflect changes from https://github.com/openucx/ucx/pull/2509

**Comment by MattBBaker** [comment]
After the last commit this doesn't build as is. Could you cherry pick in the change in #2509?

**Comment by hoopoepg** [comment]
it failed to cherry-pick this commit. I merged master into this branch

**Comment by shamisp** [comment]
@MattBBaker is it good now ?  @hjelmn  ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6806/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Something looks wrong with atomic_swap32, though it also looks like it's in gtest? I'm going to poke this more.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6808/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by MattBBaker** [comment]
I'm getting this odd crash that I can't explain at all. It looks like gtest itself is failing? I'm posting the backtrace in hopes that it's a known issue or that someone has insights on what is happening.
```
(gdb) bt
#0  0x00002aaaad2c83bf in waitpid () from /lib64/libpthread.so.0
#1  0x00002aaaaaef2908 in ucs_debugger_attach () at debug/debug.c:703
#2  0x00002aaaaaef3e4f in ucs_handle_error (
    error_type=error_type@entry=0x2aaaaaf094ab "address not mapped to object", 
    message=message@entry=0x2aaaaaf09285 "Caught signal %d (%s: %s%s)")
    at debug/debug.c:989
#3  0x00002aaaaaef418a in ucs_debug_handle_error_signal (signo=signo@entry=11, 
    cause=0x2aaaaaf094ab "address not mapped to object", 
    fmt=fmt@entry=0x2aaaaaf0954d " at address %p") at debug/debug.c:933
#4  0x00002aaaaaef43e9 in ucs_error_signal_handler (signo=11, 
    info=0x2aaaaaaef5f0, context=<optimized out>) at debug/debug.c:956
#5  <signal handler called>
---Type <return> to continue, or q <return> to quit---
#6  ucs::test_base::TestBodyProxy (this=0x0) at common/test.cc:297
#7  0x0000000000465574 in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x7a9472 "the test body", method=<optimized out>, 
    object=<optimized out>) at common/gtest-all.cc:3562
#8  testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>
    (object=0xd29f60, method=<optimized out>, 
    location=0x7a9472 "the test body") at common/gtest-all.cc:3598
#9  0x000000000045dc74 in testing::Test::Run (this=this@entry=0xd29f60)
    at common/gtest-all.cc:3635
#10 0x000000000045df0d in Run (this=0xd29f60) at common/gtest-all.cc:3626
#11 testing::TestInfo::Run (this=0xcc3c70) at common/gtest-all.cc:3812
#12 0x000000000045e0e5 in Run (this=<optimized out>)
    at common/gtest-all.cc:3787
#13 testing::TestCase::Run (this=0xcac750) at common/gtest-all.cc:3930
#14 0x000000000045ee5a in Run (this=<optimized out>)
    at common/gtest-all.cc:3916
#15 testing::internal::UnitTestImpl::RunAllTests (this=this@entry=0xaf4ae0)
    at common/gtest-all.cc:5802
#16 0x000000000045f261 in RunAllTests (this=0xaf4ae0)
    at common/gtest-all.cc:5719
#17 HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x7a89c8 "auxiliary test code (environments or event listeners)", 
    method=<optimized out>, object=0xaf4ae0) at common/gtest-all.cc:3562
---Type <return> to continue, or q <return> to quit---
#18 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>
    (
    location=0x7a89c8 "auxiliary test code (environments or event listeners)", 
    method=
    (bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x45f1c0 <testing::internal::UnitTestImpl::RunAllTests()>, 
    object=0xaf4ae0) at common/gtest-all.cc:3598
#19 testing::UnitTest::Run (this=<optimized out>) at common/gtest-all.cc:5413
#20 0x0000000000413a5c in RUN_ALL_TESTS () at common/gtest.h:20059
#21 main (argc=<optimized out>, argv=0x7fffffff6b48) at common/main.cc:85
(gdb) frame 6
#6  ucs::test_base::TestBodyProxy (this=0x0) at common/test.cc:297
297	            m_state = FINISHED;
(gdb) info locals
No locals.
(gdb) list
292	
293	void test_base::TestBodyProxy() {
294	    if (m_state == RUNNING) {
295	        try {
296	            run();
297	            m_state = FINISHED;
298	        } catch (test_skip_exception& e) {
299	            skipped(e);
300	        } catch (test_abort_exception&) {
301	            m_state = ABORTED;
(gdb) 
```

**Comment by hoopoepg** [comment]
could you run gtests under gdb & look backtrace?
it looks like gtest infra is failed

**Comment by MattBBaker** [comment]
I actually still have this up. I'll post more back traces.

**Comment by MattBBaker** [comment]
This was done with no optimizations and full debug info, so I'm guessing this 'optimized out' is never going to be not optimized out. GDB seems to be confused about &Test::TestBody. Also, using gcc version 6.3.0.
```
(gdb) frame 7
---Type <return> to continue, or q <return> to quit---
#7  0x0000000000465574 in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x7a9472 "the test body", method=<optimized out>, 
    object=<optimized out>) at common/gtest-all.cc:3562
3562	  return (object->*method)();
(gdb) info locals
No locals.
(gdb) list
3557	    delete exception_message;
3558	    return static_cast<Result>(0);
3559	  }
3560	#else
3561	  (void)location;
3562	  return (object->*method)();
3563	#endif  // GTEST_HAS_SEH
3564	}
3565	
3566	// Runs the given method and catches and reports C++ and/or SEH-style
(gdb) p object
$1 = <optimized out>
(gdb) frame 8
#8  testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>
    (object=0xd29f60, method=<optimized out>, 
    location=0x7a9472 "the test body") at common/gtest-all.cc:3598
3598	      return HandleSehExceptionsInMethodIfSupported(object, method, location);
(gdb) list
3593	  // the check early, sacrificing the ability to affect Google Test's
3594	  // exception handling in the method where the exception is thrown.
---Type <return> to continue, or q <return> to quit---
3595	  if (internal::GetUnitTestImpl()->catch_exceptions()) {
3596	#if GTEST_HAS_EXCEPTIONS
3597	    try {
3598	      return HandleSehExceptionsInMethodIfSupported(object, method, location);
3599	    } catch (const internal::GoogleTestFailureException&) {  // NOLINT
3600	      // This exception type can only be thrown by a failed Google
3601	      // Test assertion with the intention of letting another testing
3602	      // framework catch it.  Therefore we just re-throw it.
(gdb) p object
$2 = (testing::Test *) 0xd29f60
(gdb) p method
$3 = <optimized out>
(gdb) p location
$4 = 0x7a9472 "the test body"
(gdb) frame 9
#9  0x000000000045dc74 in testing::Test::Run (this=this@entry=0xd29f60)
    at common/gtest-all.cc:3635
3635	        this, &Test::TestBody, "the test body");
(gdb) list
3630	  internal::HandleExceptionsInMethodIfSupported(this, &Test::SetUp, "SetUp()");
3631	  // We will run the test only if SetUp() was successful.
3632	  if (!HasFatalFailure()) {
3633	    impl->os_stack_trace_getter()->UponLeavingGTest();
3634	    internal::HandleExceptionsInMethodIfSupported(
3635	        this, &Test::TestBody, "the test body");
3636	  }
---Type <return> to continue, or q <return> to quit---
3637	
3638	  // However, we want to clean up as much as possible.  Hence we will
3639	  // always call TearDown(), even if SetUp() or the test body has
(gdb) p this
$5 = (testing::Test * const) 0xd29f60
(gdb) p &Test::TestBody
A syntax error in expression, near `TestBody'.
(gdb) p Test::TestBody
A syntax error in expression, near `TestBody'.
```

**Comment by hoopoepg** [comment]
does master branch fail same way?

**Comment by MattBBaker** [comment]
Yes it does. So it looks like this patch is fine and there is a gtest problem.

**Comment by MattBBaker** [comment]
@shamisp I'm stumped as far as the gtest thing goes. I'm fine merging this in as it seems that I'm going to have to put more cycles into that.

**Pull request merged**
