### PR TITLE
Fixed uct hello world crash v1.4

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed missing initialization of EP in uct hello world
- added uct hello world over tcp proto to Jenkins

backport from https://github.com/openucx/ucx/pull/2862

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7676/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bgate failed due to git issues

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7679/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7686/ for details (Mellanox internal link).

**Pull request merged**
