### PR TITLE
GTEST/UCP: Increase lat limit in test_perf envelope

### PR DESCRIPTION
**Pull request by brminich**
Need to increase latency upper threshold. Latency test with the current theshold failed here: 
 
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node,worker=3/5457/consoleFull#-853622487b816df86-9afc-46eb-984f-1a9a125d73bb

### CODE REVIEW

**Comment by brminich** [comment]
bgate failure is a Jenkins problem
```
10:28:15 hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f c66e3464c2ec65ddefa6ce381fc28366c178f1f3" returned status code 128:
10:28:15 stdout: 
10:28:15 stderr: fatal: reference is not a tree: c66e3464c2ec65ddefa6ce381fc28366c178f1f3
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5471/ for details (Mellanox internal link).

**Comment by brminich** [comment]
MLNX lab failure is Jenkins problems on one of the VMs (r-vmb-rhel6-u3-x86-64). All other tests passed. 
@yosefe, do I need to trigger a retest?

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5482/ for details (Mellanox internal link).

**Pull request merged**
