### PR TITLE
IB: Remove dev_id field.

### PR DESCRIPTION
**Pull request by yosefe**
Now we can reduce IB address size since UCP is able to recognize remote features

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1945/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1318/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1947/ for details.

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
