### PR TITLE
UCP/CM: Don't flush interface when destorying UCP worker.

### PR DESCRIPTION
**Pull request by yosefe**
Following #467

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp you probably want to do something in ugni?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1079/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/510/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
autobot build

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1083/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/513/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
@yosefe - if we have outstanding message, the ugni code would report a warning , but does not fail. Do you want me to silent the warning ?

**Comment by yosefe** [comment]
@shamisp yes, during ep/iface destroy

**Comment by shamisp** [comment]
@yosefe ok, will open PR. Should not be an issue.

**Pull request merged**
