### PR TITLE
GTEST/UCP/TAG: Add tag offload test for ROCm

### PR DESCRIPTION
**Pull request by souravzzz**
## What
Added tag offload test for ROCm

### CODE REVIEW

**Comment by souravzzz** [comment]
Thanks for the suggestion @brminich . That's what I initially tried to do but was not sure how to. Can you review the updated PR?

Snipped Output:
```
[----------] 4 tests from rc_dc_gpu/test_ucp_tag_offload_gpu
[ RUN      ] rc_dc_gpu/test_ucp_tag_offload_gpu.sw_rndv_to_gpu_mem/0 <dc_x,rc_x,cuda_copy,rocm_copy>
[     SKIP ] (cuda memory is not supported)
[       OK ] rc_dc_gpu/test_ucp_tag_offload_gpu.sw_rndv_to_gpu_mem/0 (259 ms)
[ RUN      ] rc_dc_gpu/test_ucp_tag_offload_gpu.sw_rndv_to_gpu_mem/1 <dc_x,rc_x,cuda_copy,rocm_copy>
[       OK ] rc_dc_gpu/test_ucp_tag_offload_gpu.sw_rndv_to_gpu_mem/1 (543 ms)
[ RUN      ] rc_dc_gpu/test_ucp_tag_offload_gpu.rx_scatter_to_cqe/0 <dc_x,rc_x,cuda_copy,rocm_copy>
[     SKIP ] (cuda memory is not supported)
[       OK ] rc_dc_gpu/test_ucp_tag_offload_gpu.rx_scatter_to_cqe/0 (252 ms)
[ RUN      ] rc_dc_gpu/test_ucp_tag_offload_gpu.rx_scatter_to_cqe/1 <dc_x,rc_x,cuda_copy,rocm_copy>
[       OK ] rc_dc_gpu/test_ucp_tag_offload_gpu.rx_scatter_to_cqe/1 (260 ms)
[----------] 4 tests from rc_dc_gpu/test_ucp_tag_offload_gpu (1315 ms total)

[----------] 2 tests from rc_dc_gpu/test_ucp_tag_offload_stats_gpu
[ RUN      ] rc_dc_gpu/test_ucp_tag_offload_stats_gpu.block_gpu_no_gpu_direct/0 <dc_x,rc_x,cuda_copy,rocm_copy>
[     SKIP ] (cuda memory is not supported)
[       OK ] rc_dc_gpu/test_ucp_tag_offload_stats_gpu.block_gpu_no_gpu_direct/0 (252 ms)
[ RUN      ] rc_dc_gpu/test_ucp_tag_offload_stats_gpu.block_gpu_no_gpu_direct/1 <dc_x,rc_x,cuda_copy,rocm_copy>
[       OK ] rc_dc_gpu/test_ucp_tag_offload_stats_gpu.block_gpu_no_gpu_direct/1 (260 ms)
[----------] 2 tests from rc_dc_gpu/test_ucp_tag_offload_stats_gpu (512 ms total)
```

**Comment by brminich** [comment]
ok to test

**Comment by brminich** [comment]
👍 

Can you please update the 2nd commit title?
```
Good commit title: 'GTEST/UCP/TAG: Add parameterized tag offload test for GPU buffers'
Bad commit title: 'Revert "GTEST/UCP/TAG: Add tag offload test for ROCm"'
Good commit title: 'GTEST/UCP/TAG: Add tag offload test for ROCm'
##[error]Bad commit title(s), see https://github.com/openucx/ucx/wiki/Guidance-for-contributors#general-guidelines for more info.
```

**Comment by souravzzz** [comment]
Squashed changes

**Comment by brminich** [comment]
`arm-cavium` failure

bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
