### PR TITLE
Typo USC instead of UCS in 'IS_XX_ERROR' macros

### PR DESCRIPTION
**Pull request by abouteiller**

### CODE REVIEW

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
ah, please add your copyright to the header

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2416/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1760/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2421/ for details.

**Comment by yosefe** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1765/ for details (Mellanox internal link).

**Pull request merged**
