### PR TITLE
UCP/WIREUP: Add indirect lookup for AMO lanes.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1902/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1282/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
Unfortunately this surfaces a missing functionality in transport selection which is making sure the selection of both sides is identical. Will have to push few fixes before this can work..

**Comment by shamisp** [comment]
I have to thing more about this. But it seems that the selection has to be identical for all EPs.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1946/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1319/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1948/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1320/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
