### PR TITLE
configury: do not -I/usr/include -L/usr/lib[64] when rdmacm is in /usr

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by miked-mellanox** [comment]
ok to test

**Comment by shamisp** [comment]
@ggouaillardet can we ask you to sign the contributor agreement ?
http://www.openucx.org/wp-content/uploads/2016/01/ucx-individual-contributor-agrement-v1.3.pdf

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4903/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4914/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls take a look as well

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4952/ for details (Mellanox internal link).

**Comment by alinask** [comment]
:+1:

**Comment by alinask** [comment]
@ggouaillardet Does this fix a certain issue you saw?

**Comment by ggouaillardet** [comment]
currently, `-L/usr/lib64` is added into `dependency_libs` of `libucp.la` for example.
Then this is pulled by other packages such as Open MPI.
`-L/usr/lib64 -I/usr/include` is known to cause some issues, for example if you end up with
`-L/usr/lib64 -L/opt/foo/lib`, and there are both `/usr/lib64/libfoo.so` and `/opt/foo/lib/libfoo.so`, then the linker will use `/usr/lib64/libfoo.so` and this is likely not what is expected.

Back to your questions, i did not face a specific issue, but there is a potential one, that is why this should be fixed. fwiw, the same mechanism is used in some other places, so that suggests for a bug in `rdmacm` detection.

i will hand over or post the signed contribution agreement at SC'17, meanwhile, and since this is a trivial script, i am fine someone else committing it and not being credited for that.

**Comment by alinask** [comment]
@ggouaillardet I see, thanks!

**Comment by shamisp** [comment]
@ggouaillardet you can email pdf copy and do hard copy later on. I will send you the email address.

**Comment by ggouaillardet** [comment]
@shamisp i just sent a scan to your gmail address

**Comment by shamisp** [comment]
Awesome.

**Comment by shamisp** [comment]
@yosefe 👍 from me. Any other concerns ?
the contributor agreement was signed. thanks

**Comment by yosefe** [comment]
fine by me. @alinask are we good?

**Comment by alinask** [comment]
:+1:

**Pull request merged**
