### PR TITLE
TEST/UCT: Wait for send resorces for up to 10sec

### LINKED ISSUE #2288: failure on rc/uct_p2p_am_misc.am_max_short_multi/3
```
13:29:58 [ RUN      ] rc/uct_p2p_am_misc.am_max_short_multi/3
13:29:58 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node2/worker/1/contrib/../test/gtest/uct/test_p2p_am.cc:535: Failure
13:29:58 Value of: status
13:29:58   Actual: -2
13:29:58 Expected: UCS_OK
13:29:58 Which is: 0
13:29:58 
[  FAILED  ] rc/uct_p2p_am_misc.am_max_short_multi/3, where GetParam() = rc/mlx5_0:1/loopback (242 ms)
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6201/label=hpc-test-node2,worker=1/consoleFull

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2288

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6249/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6252/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6270/ for details (Mellanox internal link).

**Pull request merged**
