### PR TITLE
UCS/CONFIG: Add support for 'auto' to memunits configuration value.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/895/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1506/ for details.

**Comment by shamisp** [comment]
what is the main motivation ?

**Comment by yosefe** [comment]
allow passing something like UCX_ZCOPY_THRESH=auto - auto calculated from UCT performance info.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
