### PR TITLE
UCP&UCT: add ROCM memory type

### PR DESCRIPTION
**Pull request by yuq**
Prepare for adding UCM rocm and new rocm TL.

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp @bbenton pls approve since it's UCT API change

**Comment by miked-mellanox** [comment]
ok to test

**Comment by shamisp** [comment]
Please add AMD copyright. Otherwise looks good to me.

**Comment by yosefe** [comment]
need to add ROCM to test_md.cc:27:
```
std::string const test_md::mem_types[] = {"host", "cuda", "cuda-managed"};
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8991/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9015/ for details (Mellanox internal link).

**Comment by yuq** [comment]
Hi, how about this commit? I see one test failed but don't know which and how?

**Comment by hoopoepg** [comment]
@yuq we have some issues with testing infrastructure and compilation of ROCM by clang. fixing it right now

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9061/ for details (Mellanox internal link).

**Pull request merged**
