### PR TITLE
RC/VERBS: Avoid passing empty sge to post_send.

### LINKED ISSUE #834: ORNL jenkins failure on rc/uct_p2p_am_test zcopy
```
From the Jenkins test:
[----------] 14 tests from rc/uct_p2p_am_test
[ RUN      ] rc/uct_p2p_am_test.am_short/1
[     INFO ] 8 87 3000x{8..87} nocomp 27
[       OK ] rc/uct_p2p_am_test.am_short/1 (3392 ms)
[ RUN      ] rc/uct_p2p_am_test.am_bcopy/0
[     INFO ] 0 8.0k 256x{0..8.0k} nocomp 90
[       OK ] rc/uct_p2p_am_test.am_bcopy/0 (362 ms)
[ RUN      ] rc/uct_p2p_am_test.am_zcopy/1
[     INFO ] 0 [1465985478.473101] [pod9:4536 :0] rc_verbs_iface.c:47   UCX  ERROR Send completion with error: local length error
```
What other details do you need?

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #834

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2013/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1389/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
