### PR TITLE
Updating the alias for ugni

### PR DESCRIPTION
**Pull request by shamisp**
ugni_smsg is added to the list

Signed-off-by: Pavel Shamis (Pasha) <shamisp@ornl.gov>

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@MattBBaker  please take a look

**Comment by MattBBaker** [comment]
+1

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1330/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/726/ for details (Mellanox internal link).

**Pull request merged**
