### PR TITLE
UCS/SYS: Add uid header file - v.11.x

### PR DESCRIPTION
**Pull request by lappazos**
v1.11.x of #7180

### CODE REVIEW

**Comment by lappazos** [comment]
@yosefe please review

**Comment by yosefe** [comment]
@lappazos please fix the commit title
were there any conflicts?

**Comment by lappazos** [comment]
> @lappazos please fix the commit title
> 
> were there any conflicts?

Only in NEWS. Please take a look at the file.

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by lappazos** [comment]
@yosefe please merge

**Review by yosefe — APPROVED** [review]

**Pull request merged**
