### PR TITLE
UCT/API: Header file cleanup.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1831/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3773/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@bbenton please take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3791/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlnx:retest

**Comment by shamisp** [comment]
bot:mlnx:retest

**Comment by yosefe** [comment]
bot:mlnx:retest

**Comment by yosefe** [comment]
bot:mlnx:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3802/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3816/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3821/ for details (Mellanox internal link).

**Comment by bbenton** [comment]
:+1: for Doc/API

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3824/ for details (Mellanox internal link).

**Pull request merged**
