### PR TITLE
UCX/RCACHE: Fix early rcache invalidation.

### LINKED ISSUE #1934: UCX performance degradation
I noticed that 7c7b531431a62d25e544bfad62f23bd0d5752fb8 introduced significant performance degradation:

osu_bibw

| size | with-vs-without (%) |
| ---- | -------- |
| 1 | -0.36% |
| 2 | -1.80% |
| 4 | -0.18% |
| 8 | 0.12% |
| 16 | 0.10% |
| 32 | -1.35% |
| 64 | 2.40% |
| 128 | 1.84% |
| 256 | 1.32% |
| 512 | 0.78%|
| 1024 | 15.37%|
| 2048 | -40.16%|
| 4096 | -35.44%|
| 8192 | -25.25%|
| 16384 | -16.81%|
| 32768 | -14.46%|
| 65536 | -8.12%|
| 131072 | -5.21%|
| 262144 | -3.55%|
| 524288 | -2.40%|
| 1048576 | -1.82%|
| 2097152 | -1.49%|
| 4194304 | -1.31%|

osu_bw

| size | with-vs-without (%)  |
| ---- | -------- |
| 1 | 0.39% |
| 2 | -0.03% |
| 4 | -0.10% |
| 8 | 0.07% |
| 16 | -0.04% |
| 32 | 0.16% |
| 64 | 1.93% |
| 128 | 1.54% |
| 256 | 0.54% |
| 512 | 1.79% |
| 1024 | 1.36% |
| 2048 | -46.85% |
| 4096 | -32.72% |
| 8192 | -21.42% |
| 16384 | -13.05% |
| 32768 | -15.72% |
| 65536 | -9.61% |
| 131072 | -5.98% |
| 262144 | -4.04% |
| 524288 | -2.65% |
| 1048576 | -1.94% 
| 2097152 | -1.59%
| 4194304 | -1.38%

osu_latency

| size | with-vs-without (%) |
| ---- | -------- |
0 | 0.12%
1 | 0.25%
2 | 0.37%
4 | 0.00%
8 | 0.36%
16 | 0.36%
32 | -0.23%
64 | -0.10%
128 | 0.10%
256 | -0.46%
512 | 0.00%
1024 | 0.28%
2048 | -376.43%
4096 | -272.79%
8192 | -231.64%
16384 | -172.54%
32768 | -312.68%
65536 | -249.60%
131072 | -184.81%
262144 | -134.91%
524288 | -101.90%
1048576 | -82.87%
2097152 | -73.65%
4194304 | -68.23%

osu_mbw_mr

| size | with-vs-without (%)  |
| ---- | -------- |
1 | 0.34%
2 | -0.02%
4 | 0.51%
8 | -0.24%
16 | 0.58%
32 | 0.34%
64 | 2.49%
128 | 2.62%
256 | 0.58%
512 | 0.91%
1024 | 0.29%
2048 | -47.50%
4096 | -33.33%
8192 | -22.03%
16384 | -13.51%
32768 | -15.73%
65536 | -9.60%
131072 | -6.00%
262144 | -3.96%
524288 | -2.65%
1048576 | -2.00%
2097152 | -1.65%
4194304 | -1.46%
osu_multi_lat
0 | -0.25%
1 | -0.12%
2 | -0.25%
4 | -0.12%
8 | -0.12%
16 | 0.12%
32 | 0.46%
64 | -0.70%
128 | -0.39%
256 | 0.45%
512 | 0.36%
1024 | 0.17%
2048 | -370.76%
4096 | -263.78%
8192 | -233.60%
16384 | -171.12%
32768 | -307.81%
65536 | -247.06%
131072 | -184.67%
262144 | -134.85%
524288 | -101.45%
1048576 | -82.60%
2097152 | -73.54%
4194304 | -68.06%

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1934

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4886/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@MattBBaker can you pls post ORNL failure?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4888/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@alex-mikheev pls take a look

**Pull request merged**
