### PR TITLE
NEWS: Backport of news from 1.9.x

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

## What
NEWS: Backport of news from 1.9.x

### CODE REVIEW

**Comment by hoopoepg** [comment]
ok to test

**Comment by shamisp** [comment]
@yosefe seems like errors are unrelated

**Comment by shamisp** [comment]
@tonycurtis ping

**Review by tonycurtis — CHANGES_REQUESTED** [review]
19: APIs should be "routines"
50: recent
60 & 65 could be merged?

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
Thanks @tonycurtis - fixed.

**Comment by shamisp** [comment]
@yosefe something broken with AZP. I will go ahead and merge.

**Comment by shamisp** [comment]
@tonycurtis ping

**Review by tonycurtis — APPROVED** [review]

**Comment by shamisp** [comment]
Failures seems to be unrelated.

**Pull request merged**
