### PR TITLE
BUILD/CONFIG_H: included config.h where is it missing

### PR DESCRIPTION
**Pull request by hoopoepg**
- added inclusion of config.h file where it was missed

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg should we include config.h in all C files, or can it come from internal header files as well?

**Comment by hoopoepg** [comment]
the best practice is include it in C files, because it guarantee valid preprocessing independent from headers inclusion sequence

**Comment by yosefe** [comment]
> the best practice is include it in C files, because it guarantee valid preprocessing independent from headers inclusion sequence

So after this PR, all C files would have it?
Can you pls also add test script for CI?

**Comment by hoopoepg** [comment]
> So after this PR, all C files would have it?
right, all C files in src directory will have config.h

> Can you pls also add test script for CI?
yep, will add new test in separate PR later - looking for the best way to integrate it into jenkins

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 9 of 17 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Apr-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/f04de56130cdc4cb06b4ddc3f0c9e265d0367470/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/a6ca79b445ea8fb20b7f7fb76991bf617f2b48ed/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/577ce5a5b3ed9c2a94510a98a65e31ceb06692b4/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/8c86152545d27b217c3b2334598b17e876d08a5a/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/91df5c82f1000f048123b0b2627fe235d8e40e9e/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/2ea675428b0117cdd9406301866ec9987661c9e9/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/31157fc528fe0178ada0b353ce3f23f09f7590e8/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/57f9b786cafbeab264692d6b8a16bfecd94c92dc/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/1d65a08d357ffa6c1fd901c1f4e160975ed95d64/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/4cfa17a9ff73a7366a86de71306b18e4eb2319b1/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/22cea73de1ef66f52f802002ef3eeb076a6bc505/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/19e18ece25add7346c1b0dde955bbc0dc0dd4a42/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/b241925d844fd21778e9ba7c2e219b487f6c2ab3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/5f340d9c6f1e4f9a4859d2db505ead0a19dd0c72/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/d17d914fbcb2ede323e8b2918a3e55c61f19f834/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/8c0352c95a071191f8a146319c26af74c371bb8b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cdc201ea0bc6c08d3d6dad1906d9c4dc/raw/e84c0a456879dc54e8d6c6ca073168a7bfe9fe64/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
java exception
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 13 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Apr-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/8df3866370f59479723be33c3f78294cec85bf0f/_main) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/59f744fd3da245a9e56b319ca28954bd1aaa33fb/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/7c8556f51ffd906d5dd128ca375704e4e3b63b23/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/ba5548e84ac8a6da941b1f6fb320e44ec33d5c55/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/65d14f2d1b0dac4133c927c39161cc59d9f55d2c/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/9acd0dad3e03941e26a01ae15241e2eed7fbde99/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/ecae8a7d2837eef8aa310c4086077d0ba28fa9d2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/f429b72bc6fd642da0c49b73fd559e293709447a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/d8b32de6a8f78d3117cf70d27f085bf35d2d08f7/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/384390b820bb1f7f281abd38b1ad3f0fe3022e4b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/ae7da13338f94e6df03ccdd448c938c5399a7ecb/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/39edb25c78ce7c9c60dc7aeb9bda31e9c8f037d9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d9f0aecb0055e9f465acfcd25f7f2a42/raw/f7bc9de1633d5e6a9c078d1c45f1e17959c6a4f6/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 13 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Apr-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/f50eb7c3b57a8717e0ba773c31448797edeb6815/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/d735f52693b79dd0efc3cc11348feac96b2f5a62/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/5d98feeaa8da07a82e67d6da334e5a9f7921faad/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/e9a623b1cee0d5202fbd4a04492acc6ac22635c1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/20c7fb9dac871ac84eb7c87617b9992bdbf239ff/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/40849a77d6106294faf4cce25b097eb0cac620f5/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/719391909343342997866f81b817a653146e4936/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/56bd1dbcd9586e24424ddde33545503ebaf8ca01/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/8990ea9029e8b71a34bf46071ac11abcf87616d3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/85ee9857068ba3440680109778f531bac2cf63ee/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/d510a847bb00c3579e9d9d3872f5d664f68d0227/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/bee04443d355f894f2d09d6600021cf5f68bf421/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/96e354219e77b30ea3937f9baf026cb9/raw/461b8c36cf326229bdc5951947dc8bc1280e47dd/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Pull request merged**
