### PR TITLE
UCP/WIREUP/SOCKADDR: rename enum UCP_WIREUP_SOCKADDR_CD_*

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
Rename enum UCP_WIREUP_SOCKADDR_CD_* to UCP_WIREUP_SA_DATA_* according
to ucp_wireup_sockaddr_data_t data type.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12949/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 18 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/dd7a5d4bc6685fffcf2825abf7e95131e1e59fbd/_main) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/aa40be97c96f19a0f2fd1e6bc2d73e9c4377f052/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/76193febe98517cf8c15bc6a2bfe74278feee6d4/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/84bd17e75668988c2bd10f2836b6e4ad346fd534/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/04476fc7bc82e9373a689c8d2d71c1ab1f11fcf9/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/30ae18bdbf853d7a0778422f71e10f9b847c0922/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/0a8b8e5503baf690eb9c35a3867ff9cf524ea514/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/b2c0c3655682038c9ddcf1e2cbee461a22755e53/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/2e74411843d692dc7bf9ba7632c12b0e918458e1/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/39cb90815661a7a6d2584d29a00fb377b4090281/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/12d5bc0572ae11990ac2522e00153b268d66d77d/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/379c9dd2fc49d837168180524cff46189d3fa313/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/634be1d75f42bc23416a80852826b2be36197fc2/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/71fb474d88f57c819322f594b52db9456f225af7/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/86087bd5c4935f4e2cdc4f2fc4a1dbd5ef90d634/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/46ed488d2524618e702de7e594e39643e6beb957/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/1f87fb4b3670a582c1851bc785fb8ad05b6dfef5/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/bfbf24be8333e2def2630cc3ca3892a4/raw/440a0a4d204c02213d608d972f2e4add308fafdf/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12952/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/25bcb68b901520a0276eff94f810fd4df48b3069/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/11ae92cf2f5ea8ffbab7b01227e21e9c9e10fa20/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/d698d2425890a4adf3752bb7d47af68e2941d20b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/5bce650479b8f9a12e15b246eb9d025cd1d0e4ed/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/128c5f13b4d535fe0eb8e7e26deb2522d572789e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/544cdef73a3803dbb6c2b89a7b33e80632c292ef/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/4c373bf2a3c6586ab649695b22721d34650ca325/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/9ee033d7afde84ed9d6889d8c94d3365cf7e4155/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/41d4526cabfd8ce0c77dceb458f8f54a490e46d9/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/ca70483a7fb35281e67c2f0db01037924453855c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/629ea2d7b6807b16c8415941a594d25c303f858f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/e1424015eeb86ba616949c227bfa0ddc9ec53a2a/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/dbe2bef24cf5d6c73b7d550a8c19c593844bc6c6/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/fdcd1c889dee2b86c762e2f64a2c6d80e6597950/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/448ac5a02bcf0a161a1206dc7ae869a105da4e9b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/d6831dbd1af0a9b962acd8c754537143ea1f0d17/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/a3071cc86a91c5481d2d3e652ca9cc5c2707273f/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/95901447fac39ff61d95881cbbf9997df4dc48fb/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/340c0da0e3ed8b46a477ef3ec45f0c4e57a491f7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/2bda200c5ec8199d8f269b8930122f7488963c44/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/31d3edd8d6d6ed40232b04220c125cab12586e20/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/71dbf9e1c6c78faa3d2742cff99943d4e6b7b6b0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/626cd105ea85825c853fe90760df357c4181fcb8/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/68dc16a9f71a4c7549c056a29f68fffa43837196/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/88068f4cf960c264b2d1cf29d7d5c5cf5d77bb53/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/a6b82434844eb6b49a0f19444e95efe30bf3acaa/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/553a6f7193e0c42e873a575a2e06a1335d3e9519/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/3f5d775c92f9116397994349a3b8a36cf1f3132a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c6ce4d5bf57454ca2d21d38fac3eac16/raw/f92e47b6748a10ab8d2ccb534ee10e140695437b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 9 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/2c6726598730de9cb3786b9c55be0c5d1d6506d4/_main) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/4d56e2bb28d785ce47c8ae29f2573b72aa49f2ea/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/47308fb2592ac21876d7506d089d20d2806bf480/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/9b0c3da72117487febb9d316083ff8ee52e77837/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/471e6aca6de45892a9ba39c63039ce4d9c2d311d/hpc-test-althca_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/34076bb40e86ef01377df4eea5e4e69ac2fea7ed/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/f461b5ac88ee6d96e31b781e2fef7b04f2ce0390/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/c1288126b2aaca2219f214c1b66e059232e4463a/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/e3b5f8966641097ec3dbd6d80193d065c46a97d7/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/b7eebb30e58c703bd171bd3f04a89b2168b806b8/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/23f493d282ccd230026f674aeaa30af75178a764/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/c4a5dacab91a5d58f231b8374ecd07b2cfeda2de/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/b8696dccbae59ceb3611b184c9ea73aac978e857/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/4214f9905a7c886374d320296b046e9dd8f3e416/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/f3603b40a20157d3ee91856ca633f37127cba957/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/7476d67781ac8804a6576478cfeaea6fc5c2bf23/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/944b424d2707155bd57866f1a87a2f2f01e66eb7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/346aada4d70aed188360c77db15ee07098f21249/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/45548e5ad3a07a77b6282752b7121e50a9df84cd/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/c8895b41e7ddb6224d935d783395923fe7e80e5d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/a1331ffc5b47a090b2bde901fb3583673f15c2f9/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/ff4594bdc6166dd2d082929176218e1c3d76788e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/73c3d4466ee5a5c58ec5b2f51de620baffc53a51/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/cb1f2ffa4f9e2e1562df48ca02333faa7bd45a0a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/71995c49e9bd4faf223b6250f8ccefa5f94f7108/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/3276429e824603b9b378ae5fb94dc2be5ff21049/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/84bca9ef95dd95bf9b101bc1ae23f00eec430685/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/22253a8d807f5212e8b4861ca351eda16ea3386a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a064e6ee212c5e4fada708c5306c5fb5/raw/5abf2259fec00a20321906fb8330009ccf78d30c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by evgeny-leksikov** [comment]
rnat bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/c3246b705066d201cb0a3c89c250aca6b17c44c2/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/8ba530c79196bf5c35ead426a35fc1cbd2a0e590/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/65178e2f39f4dd48d742073bbaf74583703e39df/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/c688280a9f481913c66a94b68f822c3990bcb713/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/681e8b586cb0746dcbe18bfec8a5e34379c5ba99/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/a3752385037c6886a30c42e5d96ac8777ad8f8dc/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/28d846b06a2a33bfa7dcdb8cadd4f79893fd1635/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/1766130ec715f4eac6d6eec717dd043ec1bac92b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/2ebc6cefa98e106723dc055b9391aea69c00a0ff/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/85922c38ec0e3ccd1a83ca4e9f765d9b112aa887/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/63f8def1cae8778589716e3964b331fbb5dde115/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/665fd1bfef12a02529ceb8c3fdbc4c3dc69d37ff/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/c18d294de1cb24a02a8bc220978297284b2059e2/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/1d1a09057d8206cf5bf88a1c02da94cfe22fe270/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/e3fa7a708d6c8f74736cea23d1f8be8a4bb63474/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/c1a7c65222355f7dc1f0d65b04e3c17098bfb859/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/8de478998aedb638f62743e7e513ab4933a52534/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/6fe4d55348fd4bbf60b7da0b0f672d571f99b863/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/36394514b73f465ec5c77ee2edc87b88d634906e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/335d600c9954e06b90fc057a085a4d4a2131a42d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/1d6ab9e4cb9ccfb30b1466030c85adf70b03c690/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/b5978725adf9c35492826cb111bddf3631bb15d0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/00f7886a46ffdfe627d08db2d41b87df03011496/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/748499225eabebeb748d26774c2990ad2effbea5/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/691298e5cb627269ead1fbaac6da9c6dd524958d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/e2847ba6400a5aeb37ec575a230c5144b5114068/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/453319b29c5a77940d7048ecd4b8376dde3805d2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/500de835a99efa0c9f056629bfe68cc9b0e599a5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7464d051532da2afa805c0b92f6b07b2/raw/495af81d62f488f807f8b2fd6fd613419c517edb/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by evgeny-leksikov** [comment]
@yosefe ok to merge?

**Pull request merged**
