### PR TITLE
DOC: Replacing UCX_OK with UCS_OK in a few places

### PR DESCRIPTION
**Pull request by shamisp**
Simple typo fix

### CODE REVIEW

**Comment by tonycurtis** [comment]
+1

**Comment by shamisp** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11506/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/4599c3bc9352557027e303debc12ddb754d75773/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/f9f17bf2efac98d80ceb067ea5200fd01d72f25f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/61a867133c6bb87f1f9de5743027b087141bbfa1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/5fc9a7a25f084d053efe72f1e5ae30b23cdc7067/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/e12f3c875ba8f7882a45bdbc54e8c1faef1e4e3b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/d9480aa69009f539b2ef42c14a9f378c8e955925/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/8a951b258932acb03bdf998a3e3390d2753dbfde/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/5fc09c25ba0544f95082d79f3c4e0541c3a9e701/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/c28035b2f4126adfab0531fc9d997f7f9946378f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/9e86cd70640bd027c5c5340eefe8b49847ea26b4/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/8358da7f6f8fcfdd05a9235657cda8eeedcb3604/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/69bf845d7dfa6aca772d0361281000a6edc912e2/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/3b06ad55835b7ffe1cc69e1187a77bd745f82271/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/5b2e72f5ceb76197aebc1ed43b84585d47428180/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/36f30adcdfe64fdd05a5eeecea272dec359ba58a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/f6ef1f09397dbc9df242cf8e50fc6870b8e22e2d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/b3c1fc53581576d062c732373fdb060f1f37b701/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/8b88c35040e7995fef9ea8d903cff8d03d5d5e96/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/a709191c6a03ba878561e652a33ae0db81e038ff/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/c7476a149e414289c79e609a029e7ce49017bbe7/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/6ff44cb814b71f0cea8616569ef0b23d10d8f24d/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/608745d58259910ce2bb4b3ff057a7bc1f62956e/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/2dcf39e3a551c8b6b5230e101d29d18e4af42095/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/b4afab039569c030c790244381e0fb8f5951c49a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/1aef8e57ee21b73afb3041c81d6fce745c34f7ac/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/8bfb9f585820b3a0b9a7ca2a348c06b60a233c12/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/fd709f5e5b0cc026cd07aa4d67f39f31e3eb20a9/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/20e581e2fe60d42e93dbe3e0451e6e7f3870d4bf/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/11fd192848e8b9d94a578f5626687ca70960d2e6/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/235cdff5a4a6d5d7ea54854d33a361fa553e11b7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/b025be69c394f1a92f68afaae48bd87594e9b585/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/75829dced6fbe7b8af4148ab9039dfde0621d7ec/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3b9d281232ca482fb0b1850443bf876d/raw/2ee36c792e48e8693774cfeb8680e8fd814e83b5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11507/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/f6243ed668a7a10098f5e16a095e83a3b5161cd4/_main) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/e55212d56edfdb44d75aada94f1083d89f344292/hpc-test-node-new_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/3742243b9b42334619ecc4a2c7144462d0c305e0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/e90d76cee49d41ec9cd9f59666a155ff9c2a923f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/aad860f8c8e1a6dc8cf456e31211e1eed2e5ab0b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/65794ac589e821f7ce95b1cb595e7b21c7493a61/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/bd7cae21305411cd8d67b5a52c6846f373bd0735/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/d31957f9fbc911549413f0bee8fe008c0c685a08/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/597880f17ee49901c83725a5c21e338de1e5dc45/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/8e1ec5d3fc381049873511a739c4d2eedb93d414/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/83cbc1c8c1e9f89a7cd693307ee21b7a24b24716/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/f2555c37f2dbc46cad243d6776c8632b5b27b932/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/4651ac44e49938b7847c91c95ede2149990de6d5/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/542108c8b609ef8d0dbbc6dc5a06682cb115996e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/fcf444a988686a4e5a068d878a538d8524e6b598/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/c069fab9fa38628a68151dabe6b9a3d5a61b8281/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/d2055c12d8959db6982ce8c04085bdeb13fd9da9/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/7b4f73e33e1261b4edc3957defe40d52adb5389e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/64af8909e6c67d1063bdbd467195a1d36adea5d9/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/8fdcf9094889987360f5b03f1fd3ea2d997369f5/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/5c06fd4f7540e7c9f308015bee5e26e73bc351b8/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/8f9919f24e09721cb637040f6d704250a4f69063/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/27b9248529193bfb2f919aeb82437a6899894d74/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/16670780d8af641dfdf977dda0eac3860e1afa09/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/cabe0ecf232d3d1c1261bf9654d377c3cb398893/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/56619b7f0ed43d14dfd30279232e12391deefecd/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/a4db17cfdc98528e6fceabedcd2832e2465cd18f/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/6180fff5f96774a8b7321574aa3d9b013c87a7f6/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/6c1b10198a9eaccf8cf97fe3982410515aa28fa8/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/40bf447afaf3fe8ac5c14254575df26ea2bfced7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/abc5f88cddb4c643fcb28a25d3f1b7e792e1e997/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/5bd5d89c33df850c0c2d547364796d0fe8366dd5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/92e075a9fa7aa8642cba987e08616447/raw/55ca924e4cc3a6de2f88d9d94c5a2a4104a4ec35/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
