### PR TITLE
CONTRIB: Add ptmalloc3 library.

### PR DESCRIPTION
**Pull request by yosefe**
Adding ptmalloc3 from http://www.malloc.de/en/ as a preparation to implement memory hooks.

### CODE REVIEW

**Comment by miked-mellanox** [comment]
does it make sense to expose __end symbol in the ptmalloc3 integration to let ucx provide memheap service?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1167/ for details.

**Comment by yosefe** [comment]
Dont think so. Ucx should not provide membeap service, and even if, __end does not need to be exported to allow it.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/574/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1170/ for details.

**Comment by yosefe** [comment]
@miked-mellanox @shamisp pls review

**Comment by miked-mellanox** [comment]
:+1:

**Comment by yosefe** [comment]
the included ptmalloc3 library license was reviewed and approved by Mellanox legal department.

**Pull request merged**
