### PR TITLE
UCT/DEVX: Fix XRQ tm_list size init

### PR DESCRIPTION
**Pull request by brminich**
## What
Fix `osu_bw` hang with devx + HW TM

### CODE REVIEW

**Comment by yosefe** [comment]
can we have some gtest to repro this?

**Comment by brminich** [comment]
> can we have some gtest to repro this?

ok

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11988/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/e8973167311b14555fa2871a1ba7605102e71166/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/a5f85a3404da325a10d4d53318f209b29d2927ed/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/79a0fc053f72acb1ff73ffa6943523fc42b78ecb/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/234d11be05d901effde6de67f15670e9f286b0c5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/0ded3ba04473488c233931475b8efa8309939a58/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/30b488b6ee0215e8f17b3c24d6f105dbf7560262/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/2f92a75dc79fe347d29f8390efea6ba66749e019/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/fdff8acc6ce8ca5099e53f9ae630b97cf558b155/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/2d751896ffd48ff8e85479a3f7f2635d7369725b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/e74ff2248f8394668bdb6ca9e1c061d570cb4ade/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/06c363410c32799065efc83e1fb22a4914c1cd35/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/d7e0cb0092e3d9c46ef83971a6eae4687444bf4d/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/3a8611876dd52412e13ba9ac5618d9d0a7c4684a/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/29184bfa3c911ebc009b7445208bc878d0d198de/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/75274164d940970a46bef38fa0686a0d1bcdecac/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/96dac1af7b660547b88d888fec8fd1b6ddb447d1/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/7f93f9a830e821661bdccf95c45b9870dfaebf58/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/8cf06890414b220f6df982a8bdd36da5fbdec9f7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/25e329f4baa6947f7fc71a25147c0cd2154cd45e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/2ec4c1f73e1f8fd9549b5543af881d293947bb3e/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/333326ba4796dc412f6a14cbe52446901ffe34e0/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/918f79aa646f62f85681558a5a2d597ae5cf552f/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/13ce19054848b1acc91718a65fcec9f2a40a15ab/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/9d7c66ab378ca6f09f9c317e79d139f02649fad8/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/89300feb63207500aabac7e27ca16e3a1ea898b9/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/a73093f7b3308f9ad494e85ad1d6eb42ed62b69b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/661d39df918a5d7b41fb8a615b2f854c3673bb64/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/d05f6b44f47085a0ccb3758bde4fa6fa30995421/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ca07c709acac4bb156fe41d418945c05/raw/2b320aa92f6bc5434e184e0f5dace5c79de75cc9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
