### PR TITLE
UCM: Remove redundant check of shmat(0) result.

### LINKED ISSUE #612: Redundant if in ucm code
https://github.com/openucx/ucx/blob/master/src/ucm/mmap/install.c#L79

1) the if is redundant
2) add some comments about expected return value (EINVL) and motivation behind the call

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #612

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1492/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/884/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1493/ for details.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
