### PR TITLE
Topic/news update

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1880/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3848/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlnx:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3852/ for details (Mellanox internal link).

**Pull request merged**
