### PR TITLE
UCS/BUILD: Move config/m4/ucs.m4 to src/ucs/configure.m4

### PR DESCRIPTION
**Pull request by yosefe**
# Why
Preparation for using loadable modules in UCX library and adding FUSE support
Possible future uses: XML parser (for topology), hwloc

### CODE REVIEW

**Review by dmitrygx — APPROVED** [review]

**Comment by shamisp** [comment]
loadable UCS ?!

**Review by hoopoepg — APPROVED** [review]

**Comment by hoopoepg** [comment]
as I can see this is just reordering of files in tree

**Comment by shamisp** [comment]
It would be useful to clarify the motivation. thanks

**Comment by yosefe** [comment]
> loadable UCS ?!

support adding ucs loadable modules ("plugins") which use external libraries

**Pull request merged**
