### PR TITLE
CONFIG/RPM: Add source branch and git version to RPM desc

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
+1

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/a19089cc0a3f3a127a02710042b816a2dde3e145/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/488f6d64c3b94328b0e4ddb21340217febca6a06/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/fbf16decaf3cd2ff89f8a40faba2b5289ac550fb/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/db1dadce4880c4573d8cfaba1abca6956f1c0446/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/54ea6f0bd6865aa6cda51a2e5989333b3c865e18/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/dab41804ef7050d0805b5d83f523cac1297b8631/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/b22bcab77b966116bd69a03f386c0111787d8109/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/9638ea5a312941487286867715687b44354b5fed/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/b1b6135541a7fe7251249bd48066b2aa38ac692a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/37152c045e2442e10239980da25439149059090c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/21a10a20a11b13503798ddc7128792266a154ac0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/bcad3140944a3f8db788cc7e0853ff5dc70fe0fe/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/34f0cf6ea607e5980dbf6821aa076f2230b394a4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/ca9306c87b7392b9a5e38e815f8576dd63b4d2a4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/fc5f8eee88a8e47b6f0ea5aa859aaf582a100f6c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/9bf0ac688133425b0a30afb81595b539ade996c4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/aa29d1e266de865a7f42b3c01baa97561435dc5f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/d5963fa9e3396edf89062f193687f56f6e42af52/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/53344422f9af1e1591bbe14331f8437a6fa0e5e2/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/3a61d3b2fd36910030ccba873d18a52c90732d65/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/69af32f4cde928f7997e4bcd438466b79aeea0d7/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/43c7f1791883be7ede9d78ebdee45d8d0ed42cc6/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/e99370c9e826583389045dc62147c90fca97ab4a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/40600bd9386db8509d401f9199f60dd2369d0336/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c2e4975c52779c717b8228b5f2d24e2a/raw/e9e51cd20cc06549522cf93fdbd87ea645cf2e10/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/8e4af30da44434abcd93d46c60c64abf3b6f94e4/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/fe93afbffe58b01975c6e3efee07cd7cf4777971/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/689a1758fcb3516d56f0357149c5563373025ed3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/71e84db4e2d3d486891a82d6574986ac8da0f248/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/69eb98f84a31c89f571de01b95cc1b6a78b0606e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/7aa4b66a676980e455d99a48157aa83d66c05063/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/68296b87a86a4eb1a37c5794c5bf4f782f9093db/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/a9223fd951c30aa33f897a4d7404f1c0c679ae5a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/8e04272819ee777d872d10edc0c0e95e6c12b00a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/5e7d5084a1644e13c9486926812eb6ee212e95fc/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/752461aa5e0a2cbb56b66ed5b3631db7b81d22e5/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/7e0980e100688e418c1acde0db75054be07404c7/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/04f508d9d6f48399797326dafed043abe92f21ed/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/9a8d8f29719359d4a31195c0beb02106db4e2eea/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/df6e626e201e5338c20edfbc646c2d0f85827757/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/e15ece4006f6174cfc442682643cba0dbf9d37c3/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/bacc31205eddbeb8f79644336f07abd21a01693e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/498caf59db1b5e3d2f5ed61a0ef6e72c22168bcd/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/92c206f1b6d8e2bf16bafe1b49a9396a58a02c94/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/4fb0eb89098c7082b290b168cd0da847c9bf476f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/938bef8a4089168a2ced3507a82918b195dd970f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/a9d19965d2e4ddffb03486c008ed261fbb65fa58/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/fd60291673b844c8ecf3e62784b6b6aed159c82e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/e37de4030571028d25c07af94a110be5a3d8e8b8/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c0bf74065cb2b5672c5fddae5909e429/raw/eba8de3381e842957b723c8c6150beab17a0cd9e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/09411d3b1faf4915970024eeb78eaf96fc1a3210/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/1c7898674dc842eaf59daf3ba5c6290335dbb764/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/5ddbbdbabde63946b89259e8549571cd099820e5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/252b486a4af851832668f22ea3bde6d0890d16a5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/7f60cbf6b12df7352ad55020c0def7b7b10cc97f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/11ff86bbd7291d3b7b3a4e0ac2bbda5eee0980a3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/dbbb173765d71a838cc2fd52f020572fa56bf30c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/9ee0f8e8501da5680c48fb2fddd19c678f3d3f01/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/a066535fe6e1b47d34e49ca0e4c06c6b6eea299e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/6a92e3f90c8eec8fa45b74e073c1a065579fe342/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/27dc05aac247808a2ce24dbd545effc0a66eb77f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/884ea157423d020cdfd82796849d7eb70acd64ac/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/7ad20f0ee8677422121ad5e167094716b4ee7478/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/cd3c8edcd65ee0c7502a546588cf276d536b911d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/2ec4477931ddb4499a3be3f69f810c76b577b83c/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/5930d150fae626e9ad86bb6eaaaa3e8e8f852429/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/364e2a18575b28fc14f975ec88acc810f34e94ca/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/0007fb2206c221ad3cd5b20a50d24672e49f48ea/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/448b9aaccae968afb0f1679609c11934b5c63023/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/6cf3db2c6331c6476249cf7d206710a45eb80173/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/bba40599a93fed76ae3d23a125ab195372b8bd4d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/fa90bddeb4adf14ea902ca99779910643037ffab/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/767cc25d3c4f6a82ea5320c421c88ff677c1dea2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/5e3d20f61874769c3b5f2d405dae9ebff509be82/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2b3681923bd18f097268dc9b5f10c8b7/raw/c0aea3d963a8a4623b2b69902610f17bb9810ecf/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
