### PR TITLE
UCT/IB/CM: Fixes in flush flow.

### LINKED ISSUE #1379: failure in cm/uct_flush_test.am_pending_flush_nb/0 on arm
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3106/label=hpc-arm-04,worker=3/console
```
17:45:26 [ RUN      ] cm/uct_flush_test.am_pending_flush_nb/0
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:386: Failure
17:45:37 Value of: flush_req.comp.count == 1
17:45:37   Actual: false
17:45:37 Expected: true
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-04/worker/3/contrib/../test/gtest/uct/test_flush.cc:389: Failure
17:45:37 Value of: reqs.back().comp.count
17:45:37   Actual: 2
17:45:37 Expected: 1
17:45:37 [1489679137.442761] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
17:45:37 [1489679137.442873] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
17:45:37 [1489679137.442925] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
17:45:37 [1489679137.442967] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
17:45:37 [1489679137.442996] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
17:45:37 [1489679137.443037] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
...
17:45:37 [1489679137.456844] [hpc-arm-04:36481:1]       cm_iface.c:209  UCX  ERROR SIDR request error, status: response timeout error
17:45:37 
[  FAILED  ] cm/uct_flush_test.am_pending_flush_nb/0, where GetParam() = cm/mlx5_0:1 (11000 ms)
17:45:37 [----------] 3 tests from cm/uct_flush_test (11343 ms total)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1379

### CODE REVIEW

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1347/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3293/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1352/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3297/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1354/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3299/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1357/ for details.

**Pull request merged**
