### PR TITLE
UGNI: pending_purge compilation fix.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@MattBBaker pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1988/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1363/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
@yosefe Compiles and runs fine. The Jenkins test failed for a reason I hadn't seen before, but is unrelated to this PR.
```
[----------] 14 tests from rc/uct_p2p_am_test
[ RUN      ] rc/uct_p2p_am_test.am_bcopy/0
[     INFO ] 0 8.0k 256x{0..8.0k} nocomp 90 
[       OK ] rc/uct_p2p_am_test.am_bcopy/0 (361 ms)
[ RUN      ] rc/uct_p2p_am_test.am_async/0
[     SKIP ] (unsupported)
[       OK ] rc/uct_p2p_am_test.am_async/0 (65 ms)
[ RUN      ] rc/uct_p2p_am_test.am_short/0
[     INFO ] 8 87 3000x{8..87} nocomp 27 
[       OK ] rc/uct_p2p_am_test.am_short/0 (3429 ms)
[ RUN      ] rc/uct_p2p_am_test.am_short_keep_data/1
[     INFO ] 8 87 3000x{8..87} nocomp 27 
[       OK ] rc/uct_p2p_am_test.am_short_keep_data/1 (3392 ms)
[ RUN      ] rc/uct_p2p_am_test.am_zcopy/1
[     INFO ] 0 [1465815141.162163] [pod9:16282:0] rc_verbs_iface.c:47   UCX  ERROR Send completion with error: local length error
make: *** [test] Terminated
Build step 'Execute shell' marked build as failure
```

**Pull request merged**
