### PR TITLE
UCT/IB: Add ConnectX6-DX device id

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/430ad76747bfeb8571d02d7ae95d2fa82559fb09/_main) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/fd0f0b6c931128557a916d642a305b5ca40f6b28/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/84ac32034fe780c7f140b180d2ab65e8d0d82f93/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/198a3dd4cacf692e156e04cb2adef3dd45b0a94f/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/8e16b153fe2a59b5c7c738eca6ccd49d945df881/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/513179a448271d7277fe367d91904142364c23b7/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/08e5522f440c878955b1c643959ca1a5669d251d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/107d20d237597691b59b2a32092820ba3e0bbc8e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/b5a8634b8f02257de1a9a49eeeec46f3504dafb9/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/c913eeeddf2433322550f0532ee70a60ae59b9b5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/68f88df72a41ba9d1d88ce00526f4cf8995b0968/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/7e8a4c2044462f6dcdf2582b859ece3594adf7a4/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/2f489693dc14425276e8c284e8410c39f95317b5/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/e8d3f4491482d32d309b36c7b6d4185bb2920def/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/b5bd756ccdcd4dbac0f43f5aec7c80aaf7e08ca4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/07f28b3dadecc46758f79a66d410d351b4004c58/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/fa1828e4c41bf0d559dbd437fefd8d452c72a9ed/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/4cf27f29bfdb6ea90175dc4419f00dd1af8208c1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/ebb3aa9459e3d54863aaab14753850251b932315/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/3246c66a4d47e4f358e4d61b02ae1b4fc09e9d40/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/863aeca486077026a3f106950187720523c1123e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/a029f60b1fb6c8ae3079d64424b9eaeed7900a72/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/c2402b59890fd00251e859106ee676e7efec4bdc/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/4ad8a127bf9b45dd5e66de6d44bc87577725c646/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d08463f51ba0cdbac2b109960da07db6/raw/25b006e1f8ff98f5607d2d4f47f6ec04362ea115/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/d74bdc30f950177e0df0672d2208adfa4767f3ea/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/bb97d873fd864afca3750faa1b80126a18906288/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/19b4f4702f31aac79561e21dd53768f4ba5a9979/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/6c9d4262c2353ef690c8ab03f95aa9ff83979988/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/f41e26b498783fd96ae9b8381646ed49220d9d5b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/48294ebf892360c788f4177c7fdba970928e8faa/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/2123c3d6788bf0f76a89b5dc1f0d1d7faeee0b4c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/55fb917e2f55870432f3b808eb47e9bdba001047/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/448294883d6190bd036ebf6cbe6d61ae996b08a6/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/a12adbca642befc4daaa00142828ad136d46f80d/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/6b1973d517e888bc9b98e6627b5a98ce18519ab4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/70b9087b768e64e75d580d0ae6bdc63a0df2f19e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/bef51b225cef0b6b32451482da6e8d645761d8ad/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/b1f513de1637efef22fa207df28e3991e7599cc8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/055ff99542923555acc924e96c100219929379ea/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/bb75deb55f49b55e8b44ebe0590e3db2c428b8ec/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/9a1df86e7e55a11caa19d1c8093a4c69b64aaadf/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/b5d7a367b1730ab4ec40c684597a35cee5d6838d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/ec751260119baf57bcce8840a3b48a1ae7a2ce68/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/f5bf3163b39941b849969041cf16ede493aea351/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/627643fb02acffcd0088822f25771e73e855a452/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/0f6fb7eb1a622fc5277015e883b7af3e34609311/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/7e70d874c4b3e7cdb3146f91133d3c61a45cfda6/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/584bf02599de94ec782246b908f4f0cb4dcfdabf/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/401bb86ca7e2f4dcb2d722abe06c7773/raw/9aaca9607f6a258194e5cca3e5ce92f83af29861/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
@alinask, plz review

**Comment by yosefe** [comment]
pls fix commit title

**Comment by yosefe** [comment]
"UCT/IB: Add ConnectX6-DX device id"

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/2422ecea51ed8c33928537838591735b0aec06df/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/cc255bd5e460f9493ad45377d38f94dc5aea6acb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/9d8d8f8e75ca0726bc797e80128f980c0b6b7a0d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/86c3343f3a1400aeb5f3b1481c83caf0be034fbf/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/36cde5a9167e844d2d3341752a2111d83ece583d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/3e955148f830de14fa090c50d2fbde9e12f989d3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/4bc289e6303fcac5c68aa9148912150eb80c7d50/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/9ede64125398d48f71db6da4251fcddb49ab0976/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/6ca5f7c51a31f49ffe15c9aa5b10d169b1d687c8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/d8b108c7c50472d3da79da65d759119d32c040df/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/25453eea09158230458c3c339b46fc4e65a96ef3/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/5001ad757c657b438799a80e6761e61be4bf43b4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/92d0334f3f47230b2cb1fda29e88b6b43b29bb49/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/98093f586d4cd056e898a27e8842510705bcc6c7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/7ac2161e57f52126285b92ca8a9ed50441277091/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/4c9e20db042ac80ffca61545d6329004e119e19c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/241021f46d87e2eb793e4ca13625e1f6bfae1ce8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/0f8fdbecf6735d92f53309f5e19a2e30ecd8d444/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/550437579debc109efcc2f33f3c74b5ee08ba1e2/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/6a0cf7da282db0aac0cf34945688c46ae6b45204/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/3d08721632b4499f01adaefee84782bb2102609e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/c76bfbe1d8a20e555873e451f2c7976aa25fa440/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/3eca6baf2b027461be6e47319c6a785b0977f971/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/416542e2ad4f25d3dadafc599f460c891aaebe60/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a6835067578de8959a21aa601893ed7e/raw/0a05f85647b72b38147ac060522daa02332e9c12/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/49982e01177fb5a7de57d64a5c5dce0f759cb8e3/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/c7d1c4ebe60b87ee511801df5ab1e5b045afd78b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/5e81183f5f6e2c6a7867ebde89fe4cd4d7060de6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/69685c6abe2b132bb1e3fa7f2eb94d82b84307fa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/55b4cab2be985b2d1fb7400143f49b6c8c086a11/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/f6eeea1b88b0c768df8e79ac225d23cd8ecb7b04/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/8a6e79431538ee8a37c1b99bae60ade34bf04057/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/ee5b9f65a684a2bfd736f8f0772f28d7fb80762f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/289ab074f94c457c06c9a7cefdaf1c25fa0bff63/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/e4ad75b3d142e19591201f8f9b8ce49d4bb3aba4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/462b8c940d44497b00b76dc05af04643eeefe0a9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/4c1e6420e365f21ff8c0358eff2e60e11926a5c4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/dbe2c40171e8f3545655d982cc903b951e690663/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/7fa480bd4da027f7465394c29033e88a676b4ee0/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/3f76ea292469d1cbb30caab63ec784b125f3342e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/5b9c1259c9385b4b9ff9afdeacc3d42a8a73f610/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/997602acf14cbae6986b39e53405ca5ef8a227cc/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/563a891d61e43981d380bdd52db5f60c2803d1c5/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/67e58861b1461e6fe0212fc9fcab670b26d9b2d0/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/c77688dd7b913cce0fd41fab34eb48723b99aa5b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/b30869694b1677c8429d187291b3a475cfc47023/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/d5573438aaba53afa232eea49227f5ffeb5abcc7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/ca8bcfbd1fedec82bbb11bd5c4b955a41c482000/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/533c7ddf385c5c1cd96f64bb1d59b2f95b2bb736/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/192d018643cacb178e33c2a8cedd31dd/raw/b90173c2250ddd879585f644d1e2bcfe2f5111cd/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
