### PR TITLE
TOOLS/PERF: Fix address exhange when size is not same on all endpoints.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1266/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1880/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1884/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1269/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1272/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp  pls review

**Comment by shamisp** [comment]
@yosefe - did u have a chance to check that it work with ORNL's RTE ? @MattBBaker should review / test it as well.

**Comment by yosefe** [comment]
@shamisp Nope, i was hoping ORNL could do thath

**Comment by shamisp** [comment]
@MattBBaker - please check with RTE since you guys care about it. Maybe we can do some automation.

**Comment by MattBBaker** [comment]
The build fails on titan with RTE.

```
Making all in src/tools/perf
make[2]: Entering directory `/lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf'
  CXXLD    libucxperf.la
  CC       perftest.lo
./perftest.c: In function 'ext_rte_group_size':
./perftest.c:863:57: error: 'sock_rte_group_t' has no member named 'self'
     rte_group_t group = (rte_group_t)ctx->sock_rte_group.self;
                                                         ^
./perftest.c: In function 'ext_rte_group_index':
./perftest.c:870:57: error: 'sock_rte_group_t' has no member named 'self'
     rte_group_t group = (rte_group_t)ctx->sock_rte_group.self;
                                                         ^
./perftest.c: In function 'ext_rte_barrier':
./perftest.c:878:57: error: 'sock_rte_group_t' has no member named 'self'
     rte_group_t group = (rte_group_t)ctx->sock_rte_group.self;
                                                         ^
./perftest.c: In function 'ext_rte_post_vec':
./perftest.c:891:57: error: 'sock_rte_group_t' has no member named 'self'
     rte_group_t group = (rte_group_t)ctx->sock_rte_group.self;
                                                         ^
./perftest.c:900:20: error: 'num' undeclared (first use in this function)
     r_vec = calloc(num, sizeof(rte_iovec_t));
                    ^
./perftest.c:900:20: note: each undeclared identifier is reported only once for each function it appears in
./perftest.c: In function 'ext_rte_recv':
./perftest.c:921:57: error: 'sock_rte_group_t' has no member named 'self'
     rte_group_t group = (rte_group_t)ctx->sock_rte_group.self;
                                                         ^
./perftest.c:929:65: error: 'dest' undeclared (first use in this function)
     rc = rte_srs_get_data(session, rte_group_index_to_ec(group, dest),
                                                                 ^
./perftest.c:927:9: error: unused variable 'i' [-Werror=unused-variable]
     int i, rc;
         ^
./perftest.c: In function 'setup_mpi_rte':
./perftest.c:1007:24: error: 'sock_rte_group_t' has no member named 'self'
     ctx->sock_rte_group.self      = group;
                        ^
./perftest.c:1008:24: error: 'sock_rte_group_t' has no member named 'self_size'
     ctx->sock_rte_group.self_size = 0;
                        ^
cc1: all warnings being treated as errors

```

**Comment by yosefe** [comment]
@MattBBaker librte compilation should be fixed now

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1908/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1288/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1291/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1912/ for details.

**Comment by MattBBaker** [comment]
Now it builds, but it doesn't run correctly.
```
[bzf@titan-batch7 bin$]aprun -n 2 -N 1 ./ucx_perftest -d GEMINI:0 -t put_lat -x ugni_rdma
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[nid03788:27617:0]     libperf.c:537  Assertion `size == sizeof(*remote_info) + remote_info->rkey_size + remote_info->uct.dev_addr_len + remote_info->uct.iface_addr_len + remote_info->uct.ep_addr_len' failed
[nid02397:20126:0]     libperf.c:537  Assertion `size == sizeof(*remote_info) + remote_info->rkey_size + remote_info->uct.dev_addr_len + remote_info->uct.iface_addr_len + remote_info->uct.ep_addr_len' failed

/lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c: [ uct_perf_test_setup_endpoints() ]
      ...

/lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c: [ uct_perf_test_setup_endpoints() ]
      ...
      530         perf->uct.peers[i].remote_addr = remote_info->recv_buffer;
      531
      532         ucs_assert_always(size == sizeof(*remote_info) +
==>   533                                   remote_info->rkey_size +
      534                                   remote_info->uct.dev_addr_len +
      535                                   remote_info->uct.iface_addr_len +
      536                                   remote_info->uct.ep_addr_len);

      530         perf->uct.peers[i].remote_addr = remote_info->recv_buffer;
      531
      532         ucs_assert_always(size == sizeof(*remote_info) +
==>   533                                   remote_info->rkey_size +
      534                                   remote_info->uct.dev_addr_len +
      535                                   remote_info->uct.iface_addr_len +
      536                                   remote_info->uct.ep_addr_len);

==== backtrace ====
 0 0x000000000040b09f uct_perf_test_setup_endpoints()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c:533
 1 0x000000000040c41f uct_perf_setup()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c:957
 2 0x000000000040c909 ucx_perf_run()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c:1093
 3 0x0000000000408e4d run_test_recurs()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/./perftest.c:1090
 4 0x0000000000409026 run_test()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/./perftest.c:1119
 5 0x0000000000409141 main()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/./perftest.c:1167
 6 0x000000000001ec36 __libc_start_main()  ??:0
 7 0x0000000000406789 _start()  /usr/src/packages/BUILD/glibc-2.11.3/csu/../sysdeps/x86_64/elf/start.S:113
===================
==== backtrace ====
 0 0x000000000040b09f uct_perf_test_setup_endpoints()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c:533
 1 0x000000000040c41f uct_perf_setup()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c:957
 2 0x000000000040c909 ucx_perf_run()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/libperf.c:1093
 3 0x0000000000408e4d run_test_recurs()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/./perftest.c:1090
 4 0x0000000000409026 run_test()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/./perftest.c:1119
 5 0x0000000000409141 main()  /lustre/atlas2/csc040/scratch/bzf/ucx-work/yose/ucx/src/tools/perf/./perftest.c:1167
 6 0x000000000001ec36 __libc_start_main()  ??:0
 7 0x0000000000406789 _start()  /usr/src/packages/BUILD/glibc-2.11.3/csu/../sysdeps/x86_64/elf/start.S:113
===================
_pmiu_daemon(SIGCHLD): [NID 03788] [c8-1c0s6n0] [Thu May 19 13:42:00 2016] PE RANK 0 exit signal Aborted
_pmiu_daemon(SIGCHLD): [NID 02397] [c6-1c2s1n1] [Thu May 19 13:42:00 2016] PE RANK 1 exit signal Aborted
[NID 03788] 2016-05-19 13:42:00 Apid 11226530: initiated application termination
Application 11226530 exit codes: 134
Application 11226530 resources: utime ~0s, stime ~2s, Rss ~12672, inblocks ~1349481, outblocks ~4735
```

**Comment by yosefe** [comment]
@MattBBaker can you check now?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1297/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1920/ for details.

**Comment by MattBBaker** [comment]
@yosefe Unfortunately it still crashes in the exact same spot.

**Comment by yosefe** [comment]
@MattBBaker can you help with fixing it?

**Comment by MattBBaker** [comment]
@yosefe I'm working on figuring out the black magic to make the debugger work with ucx_perftest.

**Comment by yosefe** [comment]
you can pass UCX_HANDLE_ERRORS=freeze and then attach a debugger

**Comment by yosefe** [comment]
i wonder what is the actualt return value from librte receive and why is it not equal to expected size...

**Comment by MattBBaker** [comment]
Having a look, it seems like the remote_info pointer is total garbage. The size variable says 2048, which seems to be expected. But I'm pretty sure that remote_info->uct.ep_addr_len is not 3003900962910954247.

**Comment by yosefe** [comment]
@MattBBaker does librte require that the sender will have save scatter-gather list layout as the receiver?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1303/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1927/ for details.

**Comment by yosefe** [comment]
@MattBBaker can you check now please?

**Comment by MattBBaker** [comment]
@yosefe Works fine now. :+1:

**Comment by yosefe** [comment]
finally :) @shamisp can we merge?

**Comment by shamisp** [comment]
👍

**Pull request merged**
