### PR TITLE
UCM/TEST: Generate VM_UNMAP event for shmat(REMAP) and mmap(FIXED) - v1.3.x

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7253/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7254/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7256/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7257/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7259/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
currently both UCX and OpenMPI's memhooks are active, since UCX intercepts at the library call level, and OpenMPI intercepts at the syscall level.
We also have option to disable UCX memhooks and use the ones from OpenMPI only

**Pull request merged**
