### PR TITLE
UCS/SYS: Remove extra if (cosmetic change)

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Remove extra `if` statement (cosmetic change)

## Why ?

Just a cosmetic change

## How ?

remove `if (flags & SHM_HUGETLB)`

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/a021eb3b043fbbdb8fe33cf54353a580033910a0/_main) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/829705ebb44958bfbc4ab45f69da4004369c3deb/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/24994ec35effba197d32cfafee82302c4d4bd300/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/f014184a157fd8417ff3cbbbbe0464623d56dfb7/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/279fb5d1e7228555a0631dab6c24bb0056a25a77/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/857a0740fbf73f5dfee365075177fd96c00fc55e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/baae3e79372403ae4e7423645d319405d84fcb69/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/484960f1eabd4a36337b1017f9893625ed4bc309/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/67f474cef389721fd01b3240cb50825e9a1ffd08/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/e1ffd8a1338c2b217d22ab534e790a1f3a6c9c90/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/01e9851017290e1b93d4c45b2ec6d8fc887db8a8/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/7d693bc4a9f9c8336f1143ac4ff6af90f70eeaab/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/7032147d3ec94704b00025e3535d297b0c6ca811/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/f090ba481099374f713a625055f521c191a134ee/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/1ae5e97651eb3d28aa0b9685ca10418a1df231e8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/bb4148c080a00d9099ac7bdf1a31027f6d20b05f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/42c46ca9c9d9c902a31807b598bae7f9f3a77393/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/83f3fb17ee030e8ae509ad0ce2ef73a91392c3ba/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/f1d5e8283e59769912cd62512c4511800d1f061b/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/14410a30ac0582b08b80d7edc9023dda8985a3d3/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/4f8e248740b02a2321baa000eb2b2d19ca73567c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/a4162692f65722b0c1adb8d650bc02e14a0f6e5e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/d6031d9d973e43583c6e8ca27de88ba96bae47d8/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/f5b1678da4319ff366bde6b45fdd7bd77b0a7857/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/21401461b71acdf9a18111706550c30a/raw/43ebf8790ea844115d3acd3657ad3c1006fe378e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/a4265e5fa733c3032e911754ec4cb5f2e29c9eb6/_main) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/64f131ce8c87afca0d82dbb57a59ce4f0af22ffe/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/b2731d7de1679b1cfb295187c5326675f4f20e2e/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/199b2eba232edb602f56603cc4b03f5bd8e6ed92/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/3098a216f81cd99b770979f601a520e20e6d5c97/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/17e7bd502a4aa2cb43c5ab985420f38b1c768c86/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/c5b318313b3c8975cfee87b7d687b5b8e4ac04fd/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/9b913bd1d34f764c467188ad7d29e18ff0f15c1c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/70badc6d9e5827396c972b2e5b3c227e802e0bc9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/50324a18ad88f18a24a6bb28d4898e63601a78c9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/508ed5ba262c24374f332ef1e80231925948275b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/9ca981d85816aec2946c558f1370c8ad5eb9bc9b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/797ba87096524dab1a07fd301562c12c5f8c678d/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/575de6a420e5aef441337e0c310306e2414f22ad/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/b7d348aa9a1aed02f8be4bbd11ffab527281b775/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/a9b7f0791914c4894f4c24a8ce9b5f15542a5c97/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/877b9ce783e05411aa4188289ff85eca70e60263/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/70f6d51ed743a667af7200dc326d6a311c90ea65/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/008b0bbff9082024a66f4460eb60ff0ff6c5a2f9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/32a7aa22a28af151798c36eabf3c99a252167f85/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/9d595d69282b129a934c13cbb86deadc9e2389f6/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/989e5aa65127732e01b89fe1bb4f126557ed350a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/310a2d784826385a3719665819d3c96b818614e9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/4943e8377d65dd0234031044696f866f690463a4/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/56e2d6495e5ac123ed96481de13b545d/raw/e2498c8c9c22300589f3a42f418a9d8c07183288/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/6daa4a0b3948c28aea59cc0ff107e5185136c12e/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/4afe850fc9fa48ad677f0aa3e4f7c19bb7952c69/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/5a056e094146a7e7fd4e4251ab0182bb0ad9acb6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/34aecd52db4c4a44e5a470ec6a4e761eb80fb4e1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/2f77d2717679c2f4dc57f8ab57d9041de0575095/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/eb98f8e26b0424739cd591b0ab48eda55ed2dbb1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/b9c04558ed62ae29452d08d2313e64ced37ee781/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/3dd5f6eb9ba5c85a1f91a23286f4d1f6ecae54a9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/570411fa3c2d729e663aa116c3a98c91db28cc8c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/a9a902a8bd1af7efe980a7269f177eec4a3bf635/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/8b39ca5428825f3fd12a2c89a9ba07313e552421/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/34ab157525be4c8925b78108fb2b95ad81ef8801/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/8b47ce59328cc343b3f35dfd81a5ba33b6807f76/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/892d9b14e92998e190943a25d3ace3a66808abd5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/45ae4866932a519c741ba2c8a618cd8870e63356/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/d5588444e45f81bbb36278413e006a92b77a2bbf/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/3775018c6edffda31317c57743ea7eade4b43595/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/81687b50d33b69eb2fb636c2b3592359d2e0122c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/40b1fe2ded2811153b868e6da66748994dfe6956/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/a92ab1ba1c21b447f97337734e7013e950a81259/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/3bab6967ba9b813535f5433fd4099cfa9fbff3b3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/90b87faca66228f81c68c0483ace8810b956322c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/3c5ae8bd915f9c9dcb498eed93590769ca22e549/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/642cfe0f8bec98baca6ac7db43b23e710a08315f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/293bb9772a2a0d632c14f41bafc9f8ab/raw/2b72c82791b3bbd51c5bcfca9fba3a28e9556e58/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
@hoopoepg, please check

**Pull request merged**
