### PR TITLE
UCT/UD: Fix race condition of arming the interface

### LINKED ISSUE #1861: Hang in udx/test_ucp_wakeup.efd/0
```
18:55:32 [----------] 1 test from udx/test_ucp_wakeup
18:55:32 [ RUN      ] udx/test_ucp_wakeup.efd/0
21:11:54 Build timed out (after 150 minutes). Marking the build as failed.
21:11:54 Build was aborted
```
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4645/label=hpc-test-node2,worker=3/consoleFull#98030106524dff065-0424-4e55-b698-eb134734d522

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1861

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6063/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6085/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6089/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6092/ for details (Mellanox internal link).

**Pull request merged**
