### PR TITLE
Stress test for connect/disconnect

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1209/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1816/ for details.

**Comment by yosefe** [comment]
@alex-mikheev  pls review

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
