### PR TITLE
UCP: reset uuid in address pack for mem type ep

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6299/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy do we need this for v1.3.x?

**Comment by bureddy** [comment]
@yosefe yes, if it is possible

**Comment by bureddy** [comment]
@yosefe  yes

**Pull request merged**
