### PR TITLE
GTEST/UCT/ATOMIC: test for ADD switched to new API

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6870/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@brminich could you look?

**Comment by hoopoepg** [comment]
@brminich removed

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6873/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Pull request merged**
