### PR TITLE
TEST: Fix segfault in ucp tests.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/797/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/222/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe please take a look at the failure

**Comment by yosefe** [comment]
seems we had a problem with one of the build nodes (fedora) - ccache was installed

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/224/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
So, it is not relevant for this change, right ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/225/ for details. (Mellanox internal link)

**Pull request merged**
