### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by zasdfgbnm-nvidia**
https://github.com/openucx/ucx/pull/7016

### CODE REVIEW

**Comment by yosefe** [comment]
@zasdfgbnm-nvidia can you pls change the commit title to `GIT: Update .gitgnore` and force push (to comply with style guide). Thanks!

**Comment by yosefe** [comment]
ok to test

**Comment by yosefe** [comment]
Also, the commit email looks weird:
https://github.com/openucx/ucx/commit/3d3638d3e6456c52ff24edc1f3fe3ecdc2dfef09.patch
```
From 3d3638d3e6456c52ff24edc1f3fe3ecdc2dfef09 Mon Sep 17 00:00:00 2001
From: zasdfgbnm-nvidia <86632425+zasdfgbnm-nvidia@users.noreply.github.com>
Date: Mon, 28 Jun 2021 15:17:36 -0700
Subject: [PATCH] Update .gitignore
```

**Comment by zasdfgbnm-nvidia** [comment]
@yosefe Sorry for the late reply. I have updated the commit email.

**Comment by zasdfgbnm-nvidia** [comment]
commit title is also updated

**Review by yosefe — APPROVED** [review]

**Pull request merged**
