### PR TITLE
UCT: FC test fix

### LINKED ISSUE #782: test rc/test_rc_flow_control.general/0 fails
<pre>
16:03:11 [----------] 8 tests from rc/test_rc_flow_control
16:03:11 [ RUN      ] rc/test_rc_flow_control.general/0
16:03:11 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/uct/test_rc_flow_control.cc:62: Failure
16:03:11 Value of: expected
16:03:11   Actual: 0
16:03:11 Expected: uct_ep_am_short(e->ep(0), 0, 0, __null, 0)
16:03:11 Which is: -2
16:03:12 [  FAILED  ] rc/test_rc_flow_control.general/0, where GetParam() = rc/mlx5_0:1 (1137 ms)
16:03:12 [ RUN      ] rc/test_rc_flow_control.pending_purge/0
16:03:12 [       OK ] rc/test_rc_flow_control.pending_purge/0 (346 ms)
</pre>

http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1911/console

### PR DESCRIPTION
**Pull request by brminich**
fixes #782

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1292/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1914/ for details.

**Comment by yosefe** [comment]
@brminich how does this fix the test?

**Comment by brminich** [comment]
The problem appeared due to the progress() function may be called just once in short_progress_loop function (checked that with additional logging). For this test we have to trigger sending fc grant by the first entity and receive it by the second. So we need a bit more progression. I thought about introducing the function which invokes progress() predefined number of times, but followed the existing approach (like it is done in ud tests).

**Comment by yosefe** [comment]
i'm probably missing something, but you are calling the base implementation exactly the same way, how it makes more progression?

**Comment by brminich** [comment]
I redefined short_progress_loop() to execute 10ms instead of 1

**Comment by yosefe** [comment]
Maybe should define new function then and use it, instead of overriding a virtual function?
See this: http://stackoverflow.com/questions/6464404/virtual-function-default-arguments-behaviour

**Comment by brminich** [comment]
Hmm.  I'm using this in class member functions, but will define new one (as you suggested) to avoid possible confusions/errors

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1293/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1915/ for details.

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
