### PR TITLE
API/UCP: Clarify the documentation for sockaddr in ucp_ep_params_t.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe @shamisp @bbenton Can you please review?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5553/ for details (Mellanox internal link).

**Comment by alinask** [comment]
bot:bgate:retest

**Comment by shamisp** [comment]
The documentation change looks good to me. Can you please clarify why the bit was bumped ?

**Comment by alinask** [comment]
@shamisp I set it to 1 instead of 2, since we usually start flag values with UCS_BIT(0) . The previous value was probably a typo...

**Comment by yosefe** [comment]
@bbenton pls take a look

**Comment by shamisp** [comment]
okay

**Comment by shamisp** [comment]
👍

**Comment by alinask** [comment]
@gmegan Could you please review?

**Comment by bbenton** [comment]
:+1:

**Pull request merged**
