### PR TITLE
SPEC/README: Update the description of UCX in .spec and README files

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
Adding @tonycurtis

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8665/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@tonycurtis thanks! fixed per your comments

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8671/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8674/ for details (Mellanox internal link).

**Comment by tonycurtis** [comment]
+1

**Pull request merged**
