### PR TITLE
UCM/RELOC: add dlopen symbol to reloc patch list  - v1.4.x

### PR DESCRIPTION
**Pull request by bureddy**
porting https://github.com/openucx/ucx/pull/2898 from master

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7801/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@bureddy Is the failure a false alarm ?

**Comment by bureddy** [comment]
@shamisp Its build time out

```
21:43:28 [----------] 1 test from rc_mlx5/uct_p2p_mix_test_indirect_atomic
21:43:28 [ RUN      ] rc_mlx5/uct_p2p_mix_test_indirect_atomic.mix1000_indirect_atomic/1
22:47:09 Build timed out (after 100 minutes). Marking the build as failed.
22:47:10 make: *** [test] Terminated
22:47:10 Build was aborted
```

**Comment by bureddy** [comment]
bot:bgate:retest

**Comment by shamisp** [comment]
👍

**Pull request merged**
