### PR TITLE
TEST: Small test fixes for low CPU availability.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes for some of the recent Jenkins test failures

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2947/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/984/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/985/ for details.

**Comment by yosefe** [comment]
@evgeny-leksikov @brminich pls take a look

**Comment by brminich** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2948/ for details (Mellanox internal link).

**Pull request merged**
