### PR TITLE
README: Add FAQ link

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/285c59aaa83ee741113f420f0c4f0e07a1f2bb2a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/df5de2b7b5b58483d3248734a08c66a6f8666a02/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/d24dac7f0e31053a0b202fe379fb741759e14fe1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/51e445c7b2d1c1c1ef5b79ff8accb59d15687b3b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/69ae7d21c0d8418a1bce09cdc5a2b1cd80baa759/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/266f463c6c204cd8417f3c8c780350a00e62a8b5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/bae593b53d63cf2ffbcdca1e424b30922c22a068/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/521febcd7e83f16effd1195ce710db7e4c46ce95/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/17cce62888801a9aff16f7427cf1eb042c5a4d86/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/d1cce06400883bc1a4a3512f0dbdc0b7ba35f754/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/27853b821eb37e0036b55286ad4ea83a1154fd9a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/1d19f0931210f12285b89c0b9a367828db9dffaa/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/5b7b22eac8d0912639b82d963440233fbd40ca30/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/e199610bb2fd1c5d1c99589f3d07a38bd5620ee6/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/e1c43d60ff3f3bfa77ccc1fb95c58ef41033f296/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/9166cec55ee954220addfb650f898b0f600fe1be/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/8e807d20400e3c0c5bf7a7aa46d6f8d72f1936ba/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/55576217b2104432a038d930a0cfd116eea372ee/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/1e0785b85e3738bfdc28a5f9db8ad39de18038bb/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/8dce63fc774094dc273878efe9535822497d530e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/67326df0d166a329361a2fc9bbcde3d34ff4a109/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/c676c743178a690a19c5764e71d681ecdc471b86/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/0d35258c524127bd68faf5f7daa2f0de31f48ed5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/2f0afa33af6ca2b3f6ccc8e6d988667b77763c76/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9bb4bce4a398082aa48d25fb8cbaf5b8/raw/9b1de9b39e91a3385aaaeab04999690c2df42c7f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
@yosefe now we have two FAQ ? One on wiki and one the new site. I suggest to consolidate documentation before we point to one location or another.

**Comment by yosefe** [comment]
> @yosefe now we have two FAQ ? One on wiki and one the new site. I suggest to consolidate documentation before we point to one location or another.

The one on the wiki would be removed

**Comment by shamisp** [comment]
We are not there yet and I see people contributing to wiki right now. Let’s discuss the transition (there is more then one way to do it) and redirect people once we done. At this stage it is a bit premature. As for now let’s just reference the link from wiki and Once we done we will update readme.

**Comment by shamisp** [comment]
Btw potentially reading docs provides better infrastructure. Or we can use similar template to rapids documentation site.

**Comment by yosefe** [comment]
> We are not there yet and I see people contributing to wiki right now. Let’s discuss the transition (there is more then one way to do it) and redirect people once we done. At this stage it is a bit premature. As for now let’s just reference the link from wiki and Once we done we will update readme.

Ok closing, would link to it from wiki for now

**Pull request closed without merging**
