### PR TITLE
UCP/REQUEST: Expect only UCS_OK or BUSY from uct_ep_pending_add

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/2edaa893855ebf12db95bb254334fe9764ce8202/_main) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/debba4670eb73c4f787f0b4908e01174c5ebdf9c/hpc-test-node-legacy_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/c24398fc8b569f3f23b2d6dc20a561bf3fccbbe4/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/b3d7f4588e92cd720796113adb55acb1fe029edd/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/bd42e0ab474477429c4b2c7871f86a8c7238e529/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/b4d778932dc4ad891cd13fcd57248d832f7dc912/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/b8a5987c6d2e0d5370fe58f609de0ce61c63c356/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/6d3888b13b120df20fe5429288d645a68849d03e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/20853679ff0964f0e5842fb9f3abb5b340d24ac9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/63b615b0d42df06ef3c31fe2d44053ba5ef1480e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/67bb7fff05b476e30ced2bbd3841e2934916c6c8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/ddbcd5a5d600bb2f70c98fe601b9e27b9fd976ba/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/ec29bd3d5ed22c2edbaa789a2d64c2e73c87d789/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/6ef43b8cc4120125815b7de3a0bc018ef3c6da9e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/179b9fec58d122c783a1b6f55bb9255ba5cee7a8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/e6586153a58bb2d16057c21c4180897ba35e5918/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/b6454f76b6bd1f93be8222a6061d76a155776025/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/2266d4c41ee8f9872b3462a1a65474d835bae157/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/f23dfbef7659b6a6abe6e4aa957d6e1bf17f0d01/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/d5c8e8912b74fe8ca451f348d04e10f0ad9cd7e8/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/ee1affe2d299a753b9b0cda666b74cedff060a19/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/02a6aedb4592c17d6525cc52b8a9884ea2c8ace2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/bcdf6f8697e2a7fc0a62a0f769e426bac259f2ee/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/f67af9b695561bb3c756ea3dd0a0b509b869bb2b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/817bcbc98147aab64cf2ab78f1843b05/raw/281872d571e62fdd9932ee4852c7e15f78d6dca1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
issue #4512 and #4068

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/25f412df9976d08e9ffe49b9ad5d98a11fb0e4ef/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/3c22a7825213a9057700b9fe4392a897b9b34982/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/d41e8817f69187b8f5f5de7a1557a3156c3b9943/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/fc73b9f8a7eb286713e6c03311c785d96e794dfa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/1f408f7cad20134c90c15118f3fe83d0affeab57/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/bf28ea8b808a4e11521ae7534c2e409f746df255/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/6c05e93f0a086df2df44386b71a8fbc40bc9599b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/ae05f331eccdf1f788d9d1870e692eaf1e635bbd/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/657284707ff7bbb29e3dea97383dc0518df09802/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/294b546342b2dacaa742a82bc2ef2e95e57b2c31/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/595cb69ebd6ae2c9edb20881752fd1782636e722/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/6fdf97d76a2f669617b384ac7c0750cfc89034fe/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/9981f752081347378a033f81ecd10cc09a71bc01/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/005145dcc2c1a6ba5b30231cce644bcb9af7acba/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/07ff10a434ae490fdf64ba67b6cda7c79280b458/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/86a16c4b810adc6a0e7a6b9af8919629d2bcecbd/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/ce0df63cf2d860ec4a6ab11e9c3ae33aa9c4ac54/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/4bfc4fbf940ff65177abb0412fe230e29fb606e0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/ee7d944d58e3f94ae1aa11b90474bd20a2c2f9a9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/9be1d93d77079c983be5e8082bace07b6355a1cc/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/48d1da809516cb5d2807286398eaca122a9b8a14/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/e20f94b8175fd53a159f6ed9debd2affd5cea76f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/44779dc9e33bb0bfe838a72b47e5bfc76bba6f1e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/e68c4a8a822678d7ad35c0cba1f86fba5959496d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ecf86a0fc202895f214701857c0ce9fa/raw/c677b123e160c8822d3e22a92f7d731249d3470f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
/dev/shm filled on boo31
bot:pipe:retest

**Pull request merged**
