### PR TITLE
UCT/TEST/TOOLS: Support MDs which do not have memory registration.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/581/ for details.

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2521/ for details (Mellanox internal link).

**Comment by brminich** [comment]
:+1:

**Pull request merged**
