### PR TITLE
UCT/UGNI: Remove stdbool.h and change bool types to int

### PR DESCRIPTION
**Pull request by MattBBaker**
As per  #2108, the bools have been pulled out of ugni and replaced with ints.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6224/ for details (Mellanox internal link).

**Comment by brminich** [comment]
failed due to out of memory

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6232/ for details (Mellanox internal link).

**Pull request merged**
