### PR TITLE
IB/MD: fix for PGI build

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/c673c6e8147cc8294a68b60d0338ac0793a93845/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/abaf0de94c96026e4c2dde62f5d4ac17f09f6b10/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/63755ef5cda1651d874ca776abc7e458407c5c32/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/b9291753fe4214ee121e361e8f1a7d231493eb23/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/c5fbd820f2c2606436aea16f9fcc07716004d968/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/993cea63f19d156109f220f43d8478666a279e50/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/0ec978df75ff035847c6d13e396e8f6b220954b5/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/98e58ae687f88e1793e5fb1e5b56b5e147a6c46a/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/e321f49ff3e202da1e77d6e8c8268b2a36387bbb/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/900500e27185b97a63843c6cde28d6ae0b1fca0a/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/7781683846aabca29c3e115bccaa9aa0c5cff1a0/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/004195c7ebcfbb35773b83e1aedf42a4a146b89a/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/331c915148fadfa40bd0e52527af697f5336daac/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/028a82199387727d66400ee6f2076b84fe4f81cf/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/13073087937e05d79e9480ea800bd642a05ba182/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/e1636e3686bd947a07a6197c976e32c3d6373d8e/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/fec533a4e664822d3947c23ca1fa08a851ff1177/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/7c63c94a9b05f4609bf2a4153d98263fdf617fe4/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/c9b8c41f891072e116c3887311904b94223bf704/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/d4ab430f162427a658755560b1acdc2a91a81899/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/7295e17f8966861ecece9bdfbfba582d918af163/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/e2e3c86dce249583e62f8cc82ad3addf45de3586/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/60df38ddc8324ed4e615f00ff6b4ba26757905da/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/3f5755919972d153a547655eec4b0e820057e934/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e2d9e0501ad8663d828cb5ec4e85f0d7/raw/a1be58ed556fc52242c4d3e88a04cd69fb5eb25b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/bd110dfa5459ebef47943e80a83d7bc63b9ba539/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/be25ce75125a4dcbf966c97e22b5a72dfd7aa852/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/0be71ae69468f3fe138cbe470f8ffa5aee762c77/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/53e07a2cbb3ad22e4d49b458044b7424d5b087ed/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/ec8d22a4360f8e499d7712dad0525ff576e01fc2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/54ef77f7cafcc50fd3dc7f814b1cbeb02486d262/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/9fc3422682121841f39b94ebe7c9fa2d26d5d6eb/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/e46d84930ed4b4ee8a53b28fe2b2d58b70d702d5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/6fb6c8d38cc9a974173df7c70c088b89142841ca/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/b49dbd32d3371f596b3042bf08b53eb971a942a7/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/e3af05daf2c7c15792e6e914cabf363be9de52cf/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/8f7048137f9971c83e9f697fdefadc3b0a1bdefc/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/2fd76b1160e09f2f29324eff2a832c45d7611cb8/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/e1f525649666f01d41eb6dac4359d335117f2af4/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/13564a7e93b376b5cfbcef05a9d27190e88ebd3e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/6fd0ca3e476df76685fe76f14f883650868d6e68/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/88575cbc1b90969419e60345036a13b28c0ff73a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/af9dd31749583d6aad6a9790da6b888fe11dd9b7/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/5617ab534b6298b21649c476e15795c046078a75/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/61556048c31e2a093c4c04bb0a084722a1e5babe/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/64578aac590a1fe86c07ca5ee61fb4b27dcc146f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/5a58e8ec5b4e564c3cdea2ee5f38c41335c2e501/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/323d333b1a729d35c7235fef91d32ecbff78e30c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/06e20bd429c6625cb62bcd572d6a782ec4b60cbe/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8b1504364e773603ca1b82c59799bdfe/raw/b23a418fcd264384c8febae9ac656e1fef5bab2a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
"MellanoxLab" is fixed by #4414

**Pull request merged**
