### PR TITLE
test

### PR DESCRIPTION
**Pull request by boehms**
test

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by boehms** [comment]
Sorry guys, this was supposed to go against my fork.

**Comment by shamisp** [comment]
I guess this is @boehms test PR for ORNL's Jenkins setup

**Comment by boehms** [comment]
@shamisp , yes it is. I forked ucx and set up Jenkins to watch my fork for now so I can test the integration with github. Unfortunately I did not pay close attention when I meant to create a pull request against the master in my fork.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1511/ for details.

**Pull request closed without merging**
