### PR TITLE
UCP: documentation typo fix

### PR DESCRIPTION
**Pull request by alex--m**

### CODE REVIEW

**Comment by shamisp** [comment]
Ok to test

**Review by shamisp — APPROVED** [review]

**Comment by shamisp** [comment]
@tonycurtis please take a look.

**Review by tonycurtis — CHANGES_REQUESTED** [review]
"point to point" is usually hyphenated

**Comment by alex--m** [comment]
so, changing to "point-to-point"?

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
@alex--m yes please, if you already make the change please make it hyphenated.

**Comment by shamisp** [comment]
👍

**Pull request merged**
