### PR TITLE
UCT/ROCM: add rocm_cpy TL

### PR DESCRIPTION
**Pull request by yuq**
Corespond to cuda_cpy.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9093/ for details (Mellanox internal link).

**Comment by brminich** [comment]
looks like relevant failure on vulcan-jenkins:
```
04:33:11 /scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/0/contrib/../src/uct/rocm/base/rocm_base.c:18:1: error: missing braces around initializer [-Werror=missing-braces]
04:33:11  } uct_rocm_base_agents = {0};
04:33:11  ^
04:33:11 /scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/0/contrib/../src/uct/rocm/base/rocm_base.c:18:1: error: (near initialization for ‘uct_rocm_base_agents.agents’) [-Werror=missing-braces]
```

**Comment by yuq** [comment]
@brminich Hi, which compiler is it?

**Comment by brminich** [comment]
@yuq,
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9104/ for details (Mellanox internal link).

**Comment by yuq** [comment]
Hi, could anybody tell me what's wrong now?

**Comment by bureddy** [comment]
bot:retest

**Comment by bureddy** [comment]
@yuq  jenkins setup issue on some nodes.  

rocm related error on one node
```
I10:48:13 /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/3/contrib/../src/uct/rocm/base/rocm_base.c:39:35: error: implicit conversion from enumeration type 'enum hsa_amd_agent_info_s' to different enumeration type 'hsa_agent_info_t' [-Werror,-Wenum-conversion]
10:48:13         hsa_agent_get_info(agent, HSA_AMD_AGENT_INFO_BDFID, &bdfid);
10:48:13         ~~~~~~~~~~~~~~~~~~        ^~~~~~~~~~~~~~~~~~~~~~~~
10:48:13 1 error generated.
```

**Comment by yuq** [comment]
@bureddy thanks, what's OS and gcc version is the failed server?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9131/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9133/ for details (Mellanox internal link).

**Comment by yuq** [comment]
Hi, what about this time?

**Comment by yosefe** [comment]
It's on a machine with ROCm driver, but no ROCm GPU:
```
05:46:27 + /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/install/bin/ucx_info -d
05:46:27 [vulcan-jenkins:29934:0:29934] rocm_copy_md.c:103  Could not initialize ROCm support
05:46:27 
05:46:27 /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
05:46:27       ...
05:46:27        33     }
05:46:27        34 
05:46:27        35     ucs_handle_error(message_buf);
05:46:27 ==>    36     abort();
05:46:27        37 }
05:46:27        38 
05:46:27        39 void ucs_fatal_error_format(const char *file, unsigned line,
05:46:27 
05:46:27 ==== backtrace ====
05:46:27  0 0x000000000004d690 ucs_fatal_error_message()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/ucs/debug/assert.c:36
05:46:27  1 0x0000000000050d03 ucs_log_default_handler()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/ucs/debug/log.c:140
05:46:27  2 0x0000000000050e3b ucs_log_dispatch()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/ucs/debug/log.c:193
05:46:27  3 0x0000000000007396 uct_rocm_copy_query_md_resources()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/uct/rocm/copy/rocm_copy_md.c:103
05:46:27  4 0x000000000000a0e4 uct_query_md_resources()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/uct/base/uct_md.c:71
05:46:27  5 0x0000000000404dd4 print_uct_info()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/tools/info/tl_info.c:489
05:46:27  6 0x0000000000401fd1 main()  /scrap/jenkins/workspace/hpc-ucx-pr-3/label/vulcan-jenkins/worker/1/contrib/../src/tools/info/ucx_info.c:184
05:46:27  7 0x0000000000021c05 __libc_start_main()  ???:0
05:46:27  8 0x0000000000402113 _start()  ???:0
05:46:27 ===================
05:46:27 Sending notification to qiang.yu@amd.com
```

**Comment by yosefe** [comment]
@yuq did you get the auto-generated email with error message?

**Comment by yuq** [comment]
@yosefe thanks, I get a bunch of mail, not sure which one is valid.

One of the mail does contain this log but no running command and machine status.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9144/ for details (Mellanox internal link).

**Pull request merged**
