### PR TITLE
UCT/UGNI: Reorganize header files

### PR DESCRIPTION
**Pull request by MattBBaker**
Heavy work in multithreading the UGNI layer has exposed some decencies/bugs in how headers are arranged in UGNI. This refactor makes things much cleaner and easier to do rocket surgery on.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1386/ for details.

**Comment by shamisp** [comment]
I would suggest to use this opportunity and bump up the copyright year

**Comment by shamisp** [comment]
@MattBBaker overall the code looks good.
@yosefe - any comments ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3320/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1387/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1388/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1389/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1394/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3323/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Pull request merged**
