### PR TITLE
JUCX: profile callback functions.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Add callback functions profiliation

## Why ?
To be able to profile jucx hot methods.

### CODE REVIEW

**Comment by yosefe** [comment]
BTW should we add profiling calls to all Java APIs?

**Comment by petro-rudenko** [comment]
The issue is that JNI calls has to be prepended with macros:
```
JNIEXPORT jobject JNICALL
```
Need to check how it'll behave with profiling macros. Or to create separate functions and from JNI functions - call profiled procedures.

**Comment by petro-rudenko** [comment]
Would be something like:
```
JNIEXPORT jobject JNICALL UCS_PROFILE_FUNC ...
```

:)

**Comment by petro-rudenko** [comment]
And most other jni functions is just called to ucp routines, no complicated logic there.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10866/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 17 of 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/40e8a2381f37d691fb3e963d816f3c474e02019d/_main) | :x: FAILURE
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/29d1bea0992660c4e78bb1c27f933a630e2aade4/boo31_W0) | :x: FAILURE
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/c3f062a3263755b8e904ff7ac2149ebc5b7009c7/boo31_W1) | :x: FAILURE
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/b848eaf4873c397224d9e2eaa8b8875905f462eb/boo31_W2) | :x: FAILURE
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/9ed52831f15d671813944cd2aa7b0279cd9d84a5/boo31_W3) | :x: FAILURE
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/c9810f9d5c46428ec69bd3915add359539f28314/hpc-test-node2_W0) | :x: FAILURE
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/b39a51e0b058140bbb6c8349dd6cfebfda01cf2b/hpc-test-node2_W1) | :x: FAILURE
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/162e150cf4cb04aa21066b10b7dc03ef7984b03a/hpc-test-node2_W2) | :x: FAILURE
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/1856b788ffc0584a2c0190a08f8f9ac23b62c30a/hpc-test-node2_W3) | :x: FAILURE
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/ca7c93b705055f48f890a757d7031422a41c2372/hpc-test-node3_W0) | :x: FAILURE
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/c70dba08006fa62c3199ebfd284e9444fd346d10/hpc-test-node3_W1) | :x: FAILURE
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/e71a209d522f63853c12db59285fce1547cef996/hpc-test-node3_W2) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/ab374bbaf6e64a03e44c5ef30d6daf1c4fd2579a/hpc-test-node3_W3) | :x: FAILURE
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/d7573339b73adf8509675668eaa4bfa605740ba0/hpc-test-node_W0) | :x: FAILURE
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/fe81104d20978c8d03dd7f4345f712f9447e30a4/hpc-test-node_W1) | :x: FAILURE
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/c0252181ed743ed9a57981f94b8807c394d513f7/hpc-test-node_W2) | :x: FAILURE
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/a88693fdbfa3741959c469e044d99c9779d58b1f/hpc-test-node_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/5cd2ea2648928278831b2a13871778a1024b903f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/30a294aa2d1150961add22c3bfc6016df8c633a8/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/77d3fdf1715a2f84f96b7bea51a15cd1f9c02db9/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/a78df7c428f635631bb2a123104626e826d88921/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/929600b54e44525765f74d71e7bf1c946689a149/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/10e08ee74fe01ca837bfd58fcaf8a0ab6b74ff54/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/7ea8f8e7b9e51e6041c6bc9e22b5adb3b08c1245/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/9d65a9d62f78ad016f2c1f15ef968996044b7c23/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/ad73457c942c82c2fff8ce7fc48f84236400be16/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/48ee3ddc95b30c8c3b3b35491b99cdc333e15c4c/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/6f3857744c45199b9d1a59270578df5130a1bbbf/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/066a40c4ad85bceceeb4d7713b4c44c3625426c2/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/15d6b79755df1ac8d402d91f177e1bb8bdf22d28/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/f17479dd57395b234cc0ff924796c7380ff962f4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/e9f48ab0e7826932c50a93b2cba7758320841d0c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/11c7e2ea79d474f3466ed399d75bf3d245a63e3e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/cc227a3eba6c196306983259e2cdbd6555bf02e3/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/04c5a06cb90d29591fd1b51a0ad09166f93d6cbf/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/625941b4bb2055536540449ed3db68dceaf73976/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2a43e680f6ad4e83a1d9fc88d2867306/raw/ba61ed22f2d8fbcdc168827118b3cd4ceadbec5b/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
reference is not a tree
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10909/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/45eae48a026e06d9737f565e839df25638ccbdb8/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/a49000298e2f66a73452f0e88bb56b430afeb9a2/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/c61c357a0b7b41feb1b86c6487352f2b31e1749a/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/dca2a4f46658ce2cb666be76a39233a9da433188/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/28876fa5cac453697379244bf4235b6d13290b8c/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/56bb917589497c59755efe6ba964c0629e098350/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/746a6c7a67c999460d86c1eedebd6d81bd0aefa0/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/7e58dc860adc75009a5ebd88b99e164075975023/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/21c1afe33891718029d5076521f0c54bcf80a316/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/881da01266c2aac3213864c2100f87d2903c61c1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/2b1f54f5c8171a1a6dcadba69df3636aa48083e3/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/eb942c62b8bbc353c23cc52c5c839a5dbe84da8a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/e65c4c9c1d39bf650ae161c9db4de398b58099f7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/106b5678c03bd24b5d325665f9cfeea8e52a1c07/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/dc454d9ded1502d8473661544dc90a14f6291bee/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/7a837b857ee2b288ea50754cba1202f1715c131f/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/731eb055516e52a191428dbada407faa8180182f/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/8378a5b18ee16df1713744b0354c2824393dabe7/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/6bfac9f869e7575b55d9cd47f4f31e18a401eff4/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/c64b0e37e05ddc47de3f811881af4dfad933bc52/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/9427d8e6b8d3de1c938761c15594ca0af2392ee9/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/dec5468b356aa50d64a1825894bb183f41bc0f9e/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/5febca0cdb4f3486766b8807a7270c3074a6362a/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/3d92cee204763ca60282bb68c84dfe6838f3fcb5/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/009887a5e81b9e75873e40170a921a1ef6907262/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/f028432d82529a352856d115772e75e79a3438f6/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/83f2c0ab6c33b1f9ca55c3380081a8b9d4e1c370/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/c7e4f975f2db528d8d1d4be4ce59ac50a4a9782b/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/ad4bb45b88d6fbb53e6d5947afaa2884ad19b37b/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/28fe801dc416971c3fb5d46967deea2cfab50a23/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/d14b73bffbd9c787b73077159b197cd80aeb138d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/8789de66beb8b0ac5bed8c0d3ed28af39637e691/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/92769a7e02078c3faf12fa3a43a73171adc19877/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/f750517a4a119070cd3f745fb94919b6b6dc3d83/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/0a98590bd8ac9cdd106a5b8d0df86fd121bd7859/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/9c0fa90ef5f6cc0a6cb42a1d31cdcc83e97809a6/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf802b04fde7dd09a39cf897cb77ecc3/raw/fa39eca10e3f310a3c87893526b920b615f7a203/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
