### PR TITLE
TEST: Fix p2p_am test - wait for active message to arrive.

### LINKED ISSUE #1092: failure in  dc/uct_p2p_am_test.am_sync/0
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2117/label=hpc-test-node/console
```
16:07:10 [ RUN      ] dc/uct_p2p_am_test.am_sync/0
16:07:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-5/label/hpc-test-node/contrib/../test/gtest/uct/test_p2p_am.cc:214: Failure
16:07:11 Value of: m_am_count
16:07:11   Actual: 1
16:07:11 Expected: prev_am_count+1
16:07:11 Which is: 2
16:07:12 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-5/label/hpc-test-node/contrib/../test/gtest/uct/test_p2p_am.cc:214: Failure
16:07:12 Value of: m_am_count
16:07:12   Actual: 3
16:07:12 Expected: prev_am_count+1
16:07:12 Which is: 2
16:07:12 
[  FAILED  ] dc/uct_p2p_am_test.am_sync/0, where GetParam() = dc/mlx5_0:1 (1806 ms)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1092

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3375/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/904/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2869/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Pull request merged**
