### PR TITLE
UCP/API: Remove  UCP AM chunk API

### PR DESCRIPTION
**Pull request by brminich**
## What
Remove UCP AM chunk API

## Why ?
It was not released (and implemented) yet. There are plans to change it, so need to avoid releasing this version of API now.

### CODE REVIEW

**Review by hoopoepg — APPROVED** [review]

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
@shamisp @tonycurtis can you pls take a look?

**Review by tonycurtis — APPROVED** [review]

**Comment by shamisp** [comment]
@yosefe how we can validate that everything that was added is removed. Can we just create revert commit on previous one ?

**Comment by brminich** [comment]
> @yosefe how we can validate that everything that was added is removed. Can we just create revert commit on previous one ?

No, because that commit also added valid clarifications to `ucp_am_data_recv_nbx`

**Comment by shamisp** [comment]
IMHO it would be cleaner revert previous commit and re-submit clarification as a separate PR (less room for a mistake)

**Comment by brminich** [comment]
The changes are not that big. For this PR I applied a reverted commit and then added back what is needed. 
Do you still think it is better to split into 2 PRs?

**Comment by shamisp** [comment]
> The changes are not that big. For this PR I applied a reverted commit and then added back what is needed.
> Do you still think it is better to split into 2 PRs?

1 PR with two separate commits in a PR will do it as well. This way it is easier to track and review. thanks !

**Comment by brminich** [comment]
failures are #6813 and #6824

**Comment by brminich** [comment]
bot:pipe:retest

**Review by shamisp — APPROVED** [review]

**Comment by brminich** [comment]
@yosefe, please re-review

**Review by yosefe — APPROVED** [review]

**Comment by brminich** [comment]
@tonycurtis, can you please re-review?

**Review by tonycurtis — APPROVED** [review]

**Pull request merged**
