### PR TITLE
PERF: Avoid hang when one of the endpoints failed to connect.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by MattBBaker** [comment]
Return of this error:
```
ud_ep.c:733  Assertion `!(uct_ud_ep_is_connected(ep) && (sent_skb->neth->packet_type & UCT_UD_PACKET_FLAG_CTL))' failed: ep(0x17cec60): CREQ resend on endpoint which is already connected
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1235/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1845/ for details.

**Comment by yosefe** [comment]
@shamisp can you please review?

**Comment by shamisp** [comment]
@MattBBaker - can you try it with librte ?

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1242/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1856/ for details.

**Comment by shamisp** [comment]
@MattBBaker did u have a chance to run it with linrte?

**Comment by MattBBaker** [comment]
@shamisp @yosefe Just tested on titan, runs as expected when gtest is built with --with-rte pointed at the one I use for openshmem. Is there anything else needed to run the tests?

**Comment by MattBBaker** [comment]
Got this test stood up and it worked. So :+1:

**Comment by MattBBaker** [comment]
bot:retest

**Comment by MattBBaker** [comment]
Side note, the retest thing now works.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1250/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1862/ for details.

**Comment by yosefe** [comment]
Thanks @MattBBaker !

**Pull request merged**
