### PR TITLE
UCT/API: Multi-packet XRQ for HW TM (API only)

### PR DESCRIPTION
**Pull request by brminich**
## What
Add  UCT API required for implementing Multi-Packet XRQ support

## Why ?
MP XRQ is intended to optimize tag offload flow in the following manner:
- Reduce memory consumption, while enabling higher rendezvous thresholds.  
- Optimize sub-middle messages latency by pipelining sending fragments of the message with its handling on the receiver (for unexpected tag offload flow). Should provide up to 20% benefit for 4KB-64KB messages comparing with the current HW TM flow (making it on pair with SW TM)  

## How ?
With MP XRQ, single message may be delivered in different WQEs and unexpected eager callback will be called for each fragment of the message. Thus it is necessary to introduce some auxiliary data for correct assembling of the message. The PR adds:
1) New flags for unexpected eager callback (to distinguish single and multi fragment messages)
2) Message context, which would help to match different fragments of the same message together

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12323/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/6918d31759144d9b626ebd0363dfa618e11d583a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/982cef70c640f6a1a4718f3a4f51d45e43ca960e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/7c5f24e4de0e34565a13c5b2c1faf331e8b3e7cf/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/960ab07422d1a7968fd76c19d24941f24fe513cb/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/de06979dd794bbb7b2f399385f22b5cea274949a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/3435398220cb8b1f5e9d71c5bdca0c6c663fe5ec/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/838d286489c35c673c05ebf4529381066934b764/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/5a6575509bc84bd7ed8c6b72ef2286ded1d36ddb/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/e661ef52343816be3189cb34978ecfd350fea144/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/6443948a5ccea23834ad7eea5e14384d8abd46b8/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/c15aef58683408805f36fc059f19ae7e44a7adbd/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/739915faf28a29102b9593ebd07deacb5ceb2948/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/7600210499122b4aadf9b4d06c3c2e4a3dd6b345/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/7f2d325a54f0427630c6950cbcd16de549d7b4a9/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/8be0bdc2b117ed5a5c967bbec2a7d5b95fc3e47b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/7492454352d4fc0c64a3a314833aa92af65546de/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/d785a0fc3937976d7af97456106f826a4f53ef9e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/35a45081132cdd91ab4f8b667a3207b7755f5a8f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/6c2198616de2c40cda100adb23851d6d6d0ae4c8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/86031ead6e7fb29efba27e4540a7ce121fcebf80/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/d5e4dd02093764e896f59179a8972b8e1ab69bdc/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/85cb770a3f1f2b599baca4fa0151e9559b5aaf34/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/42159f929dc8a50ff3b5d9d2684da83e1d28dd53/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/40392cadb7214a08bc03256838eca491f63cd326/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/897a47eb6857c30c78e5952d2e83360690437c51/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/2b8deb285adc6b7e3bd301998634b25bf16cf79b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/87c233c66bc2e93a4e783a77f9f519f2dace5984/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/c7c150d4b8c254bb0503bd39aecb755ce96d7f03/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ce7a40d5759ce85bcca06cf4ce6a0555/raw/4ed20adbb9bf70448214bf3dbb803a70e2937caf/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
@shamisp @tonycurtis pls take a look again?

**Comment by tonycurtis** [comment]
+1

**Comment by brminich** [comment]
@shamisp, pls review

**Comment by shamisp** [comment]
If we already add context that can be set at the callback, does it make sense to extend the API to let user set the context at the AM CB setup time ?

**Comment by yosefe** [comment]
@shamisp this context is per message. the API today already allows setting another "persistent" context when CB is setup.

**Comment by shamisp** [comment]
> @shamisp this context is per message. the API today already allows setting another "persistent" context when CB is setup.

@yosefe - Yes, I get this part. It is not very clear what is defined by _"subsequent fragments of the same message."_ Who set the start of the message and the end of the message ? I don't think the concept of "the same message" is well defined. When the context gets reset ? Do I have to re-arm this context on each fragment ? When the context expires ? I'm a bit picky about this because it is not typical construct found in another programing models that this is something that we have to describe really well. 

As for persistent context. It this `@param [in]  arg      Active message argument.` in: https://github.com/openucx/ucx/blob/master/src/uct/api/uct.h#L1764

If this is the case, the definition is obscure at best.

**Comment by yosefe** [comment]
@shamisp the motivation is to let the unexpected callback function process a single incoming message by multiple fragments ("message" is defined on the sender side as single call to uct_ep_tag_eager_short/bcopy/zcopy).
It's theoretically possible that fragments of different messages will be mixed, so we want to define a way for the UCT user to identify fragments which belong to the same message.
The method suggested here is the UCT keeps track of this, so the UCT user would be able to set a user-defined value when the first fragment arrives (for example, a matched UCP request), and then access this value for subsequent fragments.

Given this explanation, how do you think we should phrase it in the documentation?

**Comment by yosefe** [comment]
merging per offline discussion with @shamisp

**Comment by shamisp** [comment]
@yosefe this is a follow up on our offline discussion. 

original text:
```
@param [inout]  context Storage for a per-message user-defined context. For
  *                         example, it can be initialized to a user-defined value
  *                         when the first fragment arrives with the flag
  *                         UCT_CB_PARAM_FLAG_FIRST, and this value will be available
  *                         for all subsequent fragments of the same message.
  *                         No need to initialize the value in case of single
  *                         fragment message (i.e. @a flags contains
  *                         @ref UCT_CB_PARAM_FLAG_FIRST, but does not contain
  *                         @ref UCT_CB_PARAM_FLAG_MORE).
```

New text:

Storage for a per-message user-defined context.  In this context, the message is defined by the sender side as single call to uct_ep_tag_eager_short/bcopy/zcopy. On the transport level the message can be fragmented and delivered to the target over multiple fragments. The fragments will preserve the original order of the message. Each fragment will result in invocation of the above callback. The user can use UCT_CB_PARAM_FLAG_FIRST to identify the first fragment, allocate context object and use the context as token that is set by user and passed to subsequents callbacks of the same message. The user is responsible for allocation and release of the context.

@tonycurtis - need you help here. Does it make sense ? Please feel free to word it better.

**Pull request merged**
