### PR TITLE
UCS/TOPO: Set higher bandwidth for different NUMA nodes on Grace - v1.17.x

### PR DESCRIPTION
**Pull request by tvegas1**
## What
backport #9992

### CODE REVIEW

**Comment by tvegas1** [comment]
workaround in case we want to skip backport:
- `-x UCX_IB_PCI_BW=mlx5_0:1Gbps,mlx5_3:1Gbps,mlx5_7:1Gbps,mlx5_9:1Gbps -x UCX_RNDV_THRESH=1k`

**Comment by yosefe** [comment]
@brminich do we need to port https://github.com/openucx/ucx/pull/9962 to v1.17.x?

**Comment by brminich** [comment]
> @brminich do we need to port #9962 to v1.17.x?

let me check why it is failing on 1.17

**Comment by brminich** [comment]
we also need to analyze a regressions associated with this change

**Pull request closed without merging**
