### PR TITLE
JUCX/WORKER: Support null request in progressRequest()

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Fix null pointer exception in Jucx CI

### CODE REVIEW

**Comment by yosefe** [comment]
@rakhmets can you pls review?

**Review by brminich — APPROVED** [review]

**Comment by rakhmets** [comment]
Is this a new issue? Why do we need to allow the user to pass null object to the method?

**Review by tvegas1 — APPROVED** [review]

**Comment by yosefe** [comment]
> Is this a new issue? Why do we need to allow the user to pass null object to the method?

This issue was introduced by my recent fix of waiting for requests completion in Java unit tests. An alternative way would be to check for null before calling progressRequest method, to handle immediate completion.

**Comment by yosefe** [comment]
> > > Is this a new issue? Why do we need to allow the user to pass null object to the method?
> > 
> > 
> > This issue was introduced by my recent fix of waiting for requests completion in Java unit tests. An alternative way would be to check for null before calling progressRequest method, to handle immediate completion.
> 
> Maybe it is better to fix it in the test than changing the implementation of the API method?

Will add helper function in the test then

**Comment by yosefe** [comment]
The fix is actually not relevant. Jucx always returns a request object and always calls user callback in case of an immediate completion

**Pull request closed without merging**
