### PR TITLE
UCT/UD: fix iface capability flags

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/613/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1190/ for details.

**Comment by shamisp** [comment]
autobot build

**Comment by yosefe** [comment]
this should be enough to switch to wireup over ud.
I'd suggest to also do the following changes:
- Aliases in UCP - replace cm by ud
- Remove BCOPY flag from CM transport so gtest will not use it (and occasionally fail)

**Comment by shamisp** [comment]
:+1:

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1203/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/623/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1215/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/632/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
