### PR TITLE
DOC/CONVENTIONS: Cleanup Conventions and Notations section of the API document

### PR DESCRIPTION
**Pull request by bbenton**
## What
_Describe what this PR is doing._ 
Fix heading for Signal Handler Functions section to display properly
Grammar fix: "an UCX" -> "a UCX"

## Why ?
_Justification for the PR. If there is existing issue/bug please reference. For
bug fixes why and what can be merged in a single item._
Documentation Cleanup

## How ?
_It is optional but for complex PRs please provide information about the design,
architecture, approach, etc._

### CODE REVIEW

**Comment by shamisp** [comment]
ok to test

**Comment by shamisp** [comment]
@bbenton title check failed. See #2 https://github.com/openucx/ucx/wiki/Guidance-for-contributors

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/04c3937d5ca3ae1d9ac6ba1ebf373f5bb7b5b363/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/b061a4fb71c852a1edca777c2702d12167932b4c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/3aa201fb02b6a3d1744272b78b04f6b94e684244/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/94fc0a4969929048691284310005f4bbd756542e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/1d84c1dc95dafec35446f4c445d074c4f9fc74d3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/a11e8413fa1031ac3aec75cc22a0c75783b6ab45/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/c06149a4db86539bb6f6ec233367e2262af1cc4b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/8e8c898fdc7c1832b74dd908b47b29779f61e1b5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/c9e1bef0d277d76951f6ec6465448994395821d2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/a5c3566cf6647d285904078d2706c6d989fa0938/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/5da40c70bb49bb867a28399956d1c1021e516ec6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/ea68b679b77a11ddec0faa407d5fdbc735b816f6/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/5679df3e7e90841249bb1d7185fbc6af6f3a17ae/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/251703db4bfe9ad54ad0482dad1bf2a8325568b7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/64cb585dfac57a3803216111af15819289e30ffc/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/986da5e8f71e12ab3d074fc35b9289f143ecd75d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/dff5c1595766189fa33bb4a08540cbffb9f52790/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/c42e52375308acd93a7bc3e549cdf2ea5e1d8597/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/f4580100c15418794c9084d76b4581f12bf10d5c/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/6094128f02cdc65c41546f1af15107d13abe012e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/d0fef8c8445fceda2c9e0729d901567ece37395b/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/78e1754d53b1ede7eba392e409cb5acc1afc943d/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/041ee1754f12cc13b7de671d9a34c1f2f0bd9434/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/cbdb4073b0d2d9be1c3b233ddbfe891806ffdd19/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7184bdb85f69101a3cc02198a00669b1/raw/a520b62f2226d183db7964708e487d053a9c30ff/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/5a41ef8100b94990ccc402e4b28bbe01bc14bb83/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/d6235bf5b378aba28946ad7d7d7b4c7774249e12/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/71c95c4a6457f1457b1aa31aae3c2cb18021644b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/bc83cd54030ed675b62924d760d8589fc6b87432/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/6859b362acdfa8edb45adc936f91c2195623bfd5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/00df9b2042fb8a1ff24039c11b54c0a8ac292a33/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/4295bce8c829498e175d84f42b6a2edca24acf16/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/5cce31034acada87f5cf1486d04e4c04683cc668/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/70f9b82b242e6837d5b683e6f1e74cc05b801cdf/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/acc14c61530f3305c981c675258c379a6a82356d/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/368dc0eee86ee38d7f65d29b272947ee7ad2e481/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/fb12777e1a9aaec48f494f4177baeba4f6fc5500/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/b47bd84978855ab742854f763960d1c2b114caf9/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/373c4d6479b41ba641b63af9fe888971e3b4bf6b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/5c83e606e37287bc9f289ab60eecd40c426291e7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/ac960f77fa432f37e6588c013e9e9f30630b8f31/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/720aa52d9b7576d20dc467433c64c9ee3d5c5f8a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/9447afe4cf7b664e6271acf87fbccfdac9f206ac/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/60b965c216f72669d55197bfb474dea4f81ec6c2/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/3a0be8526a2c2c4f9feed09fa9856e0a4c87f2c3/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/94898c74b0c7243a575c6e85b5c55fe3381ef9ed/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/0c3c8534afcf1557e7686deea5a1dbd5239c707a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/948e967108a8eec6460cddb69f3c95145944fddc/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/14abae3f399308464e775ce72eaffc954b12d8ec/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9eb04f365957e772136d76df38a9c420/raw/f570ec9de2db1d6bd6b2e277d8458126e64a7de5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
@yosefe ?

**Comment by yosefe** [comment]
@bbenton pls fix commit title

**Comment by yosefe** [comment]
failure is unrelated, since it's just a doc change - merging

**Pull request merged**
