### PR TITLE
TOOLS/PERF: ping pong test BW

### PR DESCRIPTION
**Pull request by eladpe**
Fix pingpong test bandwidth to be twice, as the traffic being sent
and receive.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1590/ for details.

**Comment by eladpe** [comment]
BOT:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3515/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1591/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3516/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
is there a case for separate factors for latency and bw ?

**Comment by yosefe** [comment]
@shamisp for ping-pong test we show unidirectional bandwidth, even though the data goes from both sides. this way we normalize ping-pong and stream tests to same metric

**Pull request merged**
