### PR TITLE
TEST/TIME: Check time accuracy only if performance check is enabled

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by hoopoepg** [comment]
here is failure example:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6053/

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6071/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
why ?

**Comment by yosefe** [comment]
to avoid failures on machines which run many tests in parallel and do not guarantee CPU core isolation

**Comment by shamisp** [comment]
got it

**Comment by shamisp** [comment]
Generally speaking: would be useful to include this sort of info in the commit

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6079/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6083/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6099/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6100/ for details (Mellanox internal link).

**Pull request merged**
