### PR TITLE
UCS/MEMORY: pthread_rwlock_t requires pthread.h.

### PR DESCRIPTION
**Pull request by kostikbel**
Signed-off-by: Konstantin Belousov <konstantinb@mellanox.com>

### CODE REVIEW

**Comment by yosefe** [comment]
VM failure: "Cannot contact r-vmb-ubuntu16-u10-x86-64-jb"
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/ec65be50659659773a5c25a005ea7c96210a9cb3/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/8aeef317168957b3d2e7e0677fb207979e7c9113/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/1fda87d0fe6efaa47bca6f7a1957591aff5c1a2a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/9c2553bc0fb87b40d9c941f2eb427cd48088aff0/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/de38d618c553d5fdd51bcdb4b53f9168d4d4fb59/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/e2536e6c38e84718675dc72bcc873ea37c23471e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/11f91dfccecc100f8fb197bf7de9e0697b91faee/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/e68a23fb18fe3e0189b080924a45a08c30c162f8/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/6996e32e65c28c7d70c6545e1883eac2a30e6f9f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/04747cf04820ace19c02e8ede32a291a9afed6f2/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/f238c502351ec9b1da03500c14a97bb940172324/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/bba8f087630fd07b1a5f641247d56b4808d937e9/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/3e699cb0a6840b5dd7bea89b86dd59e43a86ed76/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/b91ef333348810fb2f78ebabcb2cbb5328caef4c/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/4e92bf8e9faac1c9acb40181aae9f2643ffcd0cc/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/664dad7a3c4fb065b73c4ec9932a4c400e062c01/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/1f415f7f1311da960d61a84da58dd68f0547c046/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/76cb250639abd4004cf02674a1fc9c42900765e0/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/50249e706dcc07d025bf3f825eb37072bae08bca/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/f5a7cb35ae373d91518f3071fbca6a9e5fcef2e9/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/b1cab16ebeadfd20a4cddd1e1a780157fecdb046/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/78c04f452ef68ad2855937f4f8cd005eb5901d5c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/1fe0033bab4544342f583a633186a8a1e2086603/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/53c0ae7892c2999e1e7ff1937a6c6362f696640d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/d62abce1d87682b2af29cf4246a462a1e4320c7c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/524d5be704d595aaafce7ef06dedd1754381c57a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/38a72f94df18f1ea08ca17deb7090e16cfacf725/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/e7a3c5db9260165011a845f9bf4c6c9b9a9995cd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d45ea22e706abc387c1c77df3f515519/raw/3245267d3b22b7ee42f0cfdd01550d7d13968fbc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by jakirkham** [comment]
Stumbled across this recently. Added PR ( https://github.com/openucx/ucx/pull/4533 ) to backport this to `v1.7.x`.

**Pull request merged**
