### PR TITLE
UCP/RNDV: Fix premature completion of rendezvous get request.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1524/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3444/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1525/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3446/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by alinask** [comment]
@yosefe which transport returned ERR_NO_RESOURCE from uct_ep_get_zcopy?

**Comment by yosefe** [comment]
@alinask it was dc_mlx5

**Comment by alinask** [comment]
@yosefe you mean in uct_dc_mlx5_ep_get_zcopy? but it only returns in_progress..
if other return statuses are allowed, maybe we should document it in https://github.com/openucx/ucx/blob/master/src/uct/api/uct.h#L1520 ?

also, can the premature completion happen in other places where uct_ep_get_zcopy is called? (ucp_progress_get () )

**Comment by yosefe** [comment]
@alinask The doxgen is wrong, all UCT communication APIs, from any context, are allowed to return ERR_NO_RESOURCE. Operations which have 'comp' are also allowed to return INPROGRESS.
see https://github.com/openucx/ucx/wiki/UCT-Design#operation-handle-allocation

**Comment by yosefe** [comment]
regarding RMAs - their completion function checks the sent length (e.g ucp_rma_request_zcopy_completion)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3449/ for details (Mellanox internal link).

**Comment by brminich** [comment]
:+1:

**Pull request merged**
