### PR TITLE
Fix typo in contrib/test_jenkins.sh

### PR DESCRIPTION
**Pull request by sashakot**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by shamisp** [comment]
@miked-mellanox please kick in your jenkins

**Comment by yosefe** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1393/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3322/ for details (Mellanox internal link).

**Pull request merged**
