### PR TITLE
DEBUG: Print DC resources when flush failed

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**

### CODE REVIEW

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
@Artemy-Mellanox is this still relevant?

**Comment by Artemy-Mellanox** [comment]
@yosefe reopen?

**Comment by yosefe** [comment]
@Artemy-Mellanox is this PR still relevant, given the fix of hash for DC grant requests?

**Pull request closed without merging**
