### PR TITLE
TEST/WAKEUP: Increase poll timeout to 1000 * time_multiplier().

### LINKED ISSUE #1377: failure in ud/test_uct_wakeup.am/0 with valgrind
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3099/label=hpc-test-node2,worker=2/console
```
14:36:12 [ RUN      ] ud/test_uct_wakeup.am/0
14:36:12 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-4/label/hpc-test-node2/worker/2/contrib/../test/gtest/uct/test_wakeup.cc:101: Failure
14:36:12 Value of: UCS_OK
14:36:12   Actual: 0
14:36:12 Expected: uct_wakeup_efd_arm(wakeup_handle)
14:36:12 Which is: -15
14:36:12 
[  FAILED  ] ud/test_uct_wakeup.am/0, where GetParam() = ud/mlx5_1:1 (455 ms)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fix #1377

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1311/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3255/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shssf pls review

**Comment by shssf** [comment]
:+1:

**Pull request merged**
