### PR TITLE
UCT/DC: Don't consider fc_wnd if flow control is disabled

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@brminich pls take a look

**Comment by evgeny-leksikov** [comment]
Why this check is needed?
https://github.com/openucx/ucx/blob/26aa84a92e70facd3042b921fdd11b9f99b275f3/src/uct/ib/dc/base/dc_ep.c#L307
Seems like this is a hiding of a bug in `UCT_RC_UPDATE_FC_WND` macro or similar:
https://github.com/openucx/ucx/blob/26aa84a92e70facd3042b921fdd11b9f99b275f3/src/uct/ib/rc/base/rc_ep.h#L123
decrement should be under check below

**Comment by brminich** [comment]
It is an optimization. The check below is optimized in release build (no stats)

**Comment by evgeny-leksikov** [comment]
This is the same check that was added in `uct_rc_ep_has_tx_resources`, i don't see real optimization here.

**Comment by brminich** [comment]
- uct_rc_ep_has_tx_resources is not invoked for every AM send, just for pendings
- Check added with `||` which means that the second condition will be evaluated only when the first is false (which is supposed to be very seldom occasion)

**Comment by evgeny-leksikov** [comment]
i think i got it... in new implementation new check will be taken only 1/UINT16_MAX times... OMG, please write a poem in comment for this.

**Comment by evgeny-leksikov** [comment]
BTW, `UCT_RC_UPDATE_FC_WND` can be rewritten with 
`(_fc)->fc_wnd -= (_iface)->config.fc_enabled;`
assuming that `fc_enabled` can be 0 or 1. This is a bit more expensive then just decrement but clearer

**Comment by brminich** [comment]
Just noticed: looks like the same fix needs to be applied for RC:
In `uct_rc_ep_pending_add` and `uct_rc_ep_flush`

**Comment by yosefe** [comment]
isn't it already covered by uct_rc_ep_has_tx_resources()?

**Comment by brminich** [comment]
right, I've mistaken

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6297/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6298/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6300/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6301/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6303/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6305/ for details (Mellanox internal link).

**Pull request merged**
