### PR TITLE
TEST: Fixes signed/unsigned compare in UD test case.

### PR DESCRIPTION
**Pull request by MattBBaker**

### CODE REVIEW

**Comment by MattBBaker** [comment]
@yosefe Can you review?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2374/ for details.

**Comment by yosefe** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1711/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@MattBBaker @yosefe  - copyright was not updated ...

**Comment by MattBBaker** [comment]
@shamisp Oops, I did. I'll check some of the other files and do a copyright update PR, I think I need to fix the year on a lot of ugni.

**Pull request merged**
