### PR TITLE
MM: make sure that the allocated address for the FIFO is aligned.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/823/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/248/ for details. (Mellanox internal link)

**Comment by alinask** [comment]
@yosefe please review

**Comment by yosefe** [comment]
looks good, but we need to coordinate this with XPMEM changes

**Comment by alinask** [comment]
these changes are fifo related, no pd changes here

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
