### PR TITLE
UCP: don't use uninitialized values in the AM rndv calc function.

### PR DESCRIPTION
**Pull request by alinask**
(cherry picked from commit d5e67e179430d5618fed9a7ebd77e4460c221240)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1820/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3760/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by alinask** [comment]
@shamisp Can you please review?

**Comment by shamisp** [comment]
👍

**Pull request merged**
