### PR TITLE
UCT/UD: fixed compilation by gcc8

### PR DESCRIPTION
**Pull request by hoopoepg**
- removed 'packed' attribute from uct_ud_send_skb_inl_t structure

### CODE REVIEW

**Comment by hoopoepg** [comment]
it may increase size, but as I can see this datatype is never used as-is, only .super value is used and .super is still packed

**Comment by yosefe** [comment]
ok, but need to make sure no padding is added, because this structure is sent on the wire

**Comment by hoopoepg** [comment]
I checked - ```uct_ud_send_skb_inl_t``` datatype is never used in UCX directly (it is used as placeholder for ```uct_ud_send_skb_t``` + ```uct_ud_neth_t```), and there is no reason to stay it packed

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6550/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6552/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6554/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
is this #2400 bugfix ?

**Comment by hoopoepg** [comment]
@shamisp right

**Comment by shamisp** [comment]
fixes #2400

**Pull request merged**
