### PR TITLE
UCT/UD/GTEST: Fix a couple of UD tests

### LINKED ISSUE #1087: failure in ud_mlx5/test_ud.crep_drop2/0 with valgrind
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2103/label=hpc-test-node2/consoleFull
```
18:10:25 [ RUN      ] ud_mlx5/test_ud.crep_drop2/0
18:10:27 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:343: Failure
18:10:27 Value of: ep(m_e1, 0)->tx.psn
18:10:27   Actual: 2
18:10:27 Expected: 3
18:10:28 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:344: Failure
18:10:28 Value of: ep(m_e2, 0)->tx.acked_psn
18:10:28   Actual: 0
18:10:28 Expected: 1
18:10:28 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:345: Failure
18:10:28 Value of: ep(m_e2, 0)->tx.psn
18:10:28   Actual: 2
18:10:28 Expected: 3
18:10:28 
[  FAILED  ] ud_mlx5/test_ud.crep_drop2/0, where GetParam() = ud_mlx5/mlx5_1:1 (2429 ms)
```

### PR DESCRIPTION
**Pull request by brminich**
Two tests remained to be sensitive to polling delays (i.e with valgrind). The correction corresponds to the other similar tests -  make sure the expected event occurred in a loop with relatively big timeout. 
crep_drop2 is also updated to check that TX win is really empty,
Fixes #1087

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3074/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/626/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2577/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@alex-mikheev, @yosefe please take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/627/ for details.

**Pull request merged**
