### PR TITLE
UCP/API: Deprecate blocking AMO and RMA operations

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg we decided not to do it for now to avoid compilation warnings in user programs

**Comment by yosefe** [comment]
@shamisp @gmegan pls take a look

**Comment by shamisp** [comment]
I don't think we have to remove the documentation. I would suggest to move it with the rest of declarations. 

@hoopoepg  there are quite a few codes that depend on the API. Let's leave it as it is without compiler attribute. Once we one release before 2.0 we will do it.

**Comment by shamisp** [comment]
@bbenton please take a look if you have time

**Comment by yosefe** [comment]
@shamisp i think we better remove it for easier maintenance, and to discourage new users from using the deprecated API

**Comment by shamisp** [comment]
@yosefe I don't think there is much maintenance around just keeping the documentation around.
As long as it is marked deprecated user will understand that they should not use it.

Also, I would suggest in the blocking API add an example how it can be used to implement blocking semantics, with code examples

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7543/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp fixed

**Comment by shamisp** [comment]
@tonycurtis is this okay with you ?

**Comment by shamisp** [comment]
👍

**Comment by yosefe** [comment]
approved on the UCX dev call

**Pull request merged**
