### PR TITLE
UCT/API: Add memory domain flag - whether remote key is required.

### PR DESCRIPTION
**Pull request by yosefe**
This would allow UCP optimize remote key allocation and exchange

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe - if it is not required, we have to specify in the documentation what user has to pass as a parameter

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2406/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1743/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1847/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2499/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2504/ for details.

**Pull request closed without merging**
