### PR TITLE
DOC: Fixing latex error on OSX

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
@tonycurtis can you please try this on your system. The removed line was making trouble with recent latex.

**Comment by tonycurtis** [comment]
> On Mar 6, 2019, at 5:40 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> @tonycurtis <https://github.com/tonycurtis> can you please try this on your system. The removed line was making trouble with recent latex.
> 

I think I am missing some context - What’s the sequence to build this?
tony

**Comment by shamisp** [comment]
make docs

**Comment by tonycurtis** [comment]
Oops, just a fat-finger issue: make docs running...

**Comment by tonycurtis** [comment]
+1 both in-source-tree and out- after patch

**Comment by shamisp** [comment]
@yosefe please take a look

**Comment by tonycurtis** [comment]
I compared this process on Fedora (29).  Got a runaway argument error relating to a `verbatim`.  Open separate ticket?

**Comment by shamisp** [comment]
Is this related to the line that I removed or unrelated.  If it is
unrelated, please open separate ticket.

**Comment by tonycurtis** [comment]
Looks to be unrelated, patch had no effect: will open new one

**Comment by shamisp** [comment]
Thanks for checking.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9180/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe ?

**Pull request merged**
