### PR TITLE
UCM: Fix getting previous symbol value on ARM.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by MattBBaker** [comment]
From the ORNL buildbot:
```
[----------] 25 tests from ud/test_ud
[ RUN      ] ud/test_ud.connect_iface_2to1/0
[       OK ] ud/test_ud.connect_iface_2to1/0 (54 ms)
[ RUN      ] ud/test_ud.connect_iface_sim2v2/0
[       OK ] ud/test_ud.connect_iface_sim2v2/0 (52 ms)
[ RUN      ] ud/test_ud.duplex_tx/0
[       OK ] ud/test_ud.duplex_tx/0 (142 ms)
[ RUN      ] ud/test_ud.connect_iface_sim/0
[       OK ] ud/test_ud.connect_iface_sim/0 (52 ms)
[ RUN      ] ud/test_ud.ep_destroy_passive/0
[       OK ] ud/test_ud.ep_destroy_passive/0 (62 ms)
[ RUN      ] ud/test_ud.connect_iface_2k/0
[       OK ] ud/test_ud.connect_iface_2k/0 (81 ms)
[ RUN      ] ud/test_ud.flush_ep/0
[       OK ] ud/test_ud.flush_ep/0 (62 ms)
[ RUN      ] ud/test_ud.res_skb_tx/0
[       OK ] ud/test_ud.res_skb_tx/0 (156 ms)
[ RUN      ] ud/test_ud.ep_destroy_creq/0
[       OK ] ud/test_ud.ep_destroy_creq/0 (52 ms)
[ RUN      ] ud/test_ud.ca_md/0
[       OK ] ud/test_ud.ca_md/0 (2724 ms)
[ RUN      ] ud/test_ud.ca_ai/0
/var/lib/jenkins/jobs/ornl_pod9/workspace/contrib/../test/gtest/uct/test_ud.cc:336: Failure
Expected: (rx_ack_count) <= (2), actual: 3 vs 2
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1141/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1746/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1747/ for details.

**Comment by shamisp** [comment]
@MattBBaker @yosefe - I think the failure is unrelated

**Comment by MattBBaker** [comment]
Seems to be unrelated, but wanted to post the log anyways.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1748/ for details.

**Comment by yosefe** [comment]
tested with MPI

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1771/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1163/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1772/ for details.

**Comment by shamisp** [comment]
I still have to try on my box. I will try to do it tonight or tomorrow
morning

On Wed, Apr 6, 2016 at 4:49 AM, Mellanox Build Bot <notifications@github.com

**Comment by shamisp** [comment]
:+1: 
Thanks @yosefe

**Pull request merged**
