### PR TITLE
Doxygen enhancements

### PR DESCRIPTION
**Pull request by yosefe**
- Auto-generate spec version
- Use Markdown for generic text; as preparation for text cleanup

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7143/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7144/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @gmegan pls take a look

**Comment by shamisp** [comment]
How MD gets compiled into TEX?

**Comment by yosefe** [comment]
doxygen can process MD files

**Comment by shamisp** [comment]
I was not aware about this. Are there any specific version requirements for this ?

**Comment by shamisp** [comment]
It seems like 1.8.0 and above support this. As for now we require 1.8.6. I
would like to check it manually and review the output.

**Comment by shamisp** [comment]
General question - what is the goal of the conversion to MD ?

**Comment by yosefe** [comment]
it's more convenient to write/edit whole pages in MD, instead of as a long C/C++ comment block

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7149/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7152/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp is it ok to merge?

**Comment by shamisp** [comment]
Yes

**Pull request merged**
