### PR TITLE
BUILD/NEWS: Bump version to v1.6.1

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by dmitrygx** [comment]
> Test FAILed.
> See [http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/8209](http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/8209/) for details.

@yosefe 
looks like this is something related to the PR:
```
14:53:16 ++ tr ' ' .
14:53:16 + version=1.6.1
14:53:16 + grep -q 1.6.1 ucx.spec.in
14:53:16 + echo 'Current UCX version (1.6.1) is not present in ucx.spec.in changelog'
14:53:16 Current UCX version (1.6.1) is not present in ucx.spec.in changelog
14:53:16 + exit 1
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11372/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 9 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/27118cf1220c9e3715e357b06c1a02d2d92d977b/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/b2c56e01e636b2b47270db1175f4ca52272ca1ee/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/9c1eed4b5f9014f152d6de14bf880854979028d5/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/6957c220124a4aed5bb5b7f4ddc6a041abe891b3/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/45e1c4d249588be290de3e4d30b0473fc731bd20/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/affdd3700a3c162de7c234b526f3b4fd4751cfed/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/8f1dd1a8707aca378f06d759bfcd092dab8af0a1/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/5b1eee7dbfb26261871fe836ec34729985f0f8e3/hpc-test-node-upstream_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/8b10235e18c314ea149837eb40317e328f596cb7/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/2314e4468f7124e0b1317e502c4aa80dfb6ad586/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/b3d92dfe74d7aa96d31fa67bb41377d6da42c0a6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/92e1acd16cc3729233e3a1381324c7233b39068d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/6cb00ffade4fd3f2b97bac02e9e6e9fde18d5c11/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/74a14dd74074a09955124a23ac12a3ffd13a24f9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/11ad4dfdb355f1a515a587ce31212be098feebb3/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/b5ea5c7d26f9c3f217162e0cf6995afb534c825f/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/85a8f08b86d3544c32c329ad31944775f8b7b4cd/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/79ca3a2225a6957e66ff9471d88200cdb966b7cd/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/4a62cce988310f08441a3e8c5718fb15a07998f3/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/25c40ed7a538e59750d72a637148044ae68ca23c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/a769811431b080b8bd9ceb8aa916d373470c09c7/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/a76d0bae3297bf228de12e365ca5e2bf42b8b25f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/5b587dc2b187851139326cc7872d36ef0cfdd117/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/9761b86c332a1f2a9fb4062a58543d47444ed38a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/83cb0a08bd08b55454412ef4efe19255a24075b7/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/dfa9d17f3d821257a9cdc4fd420a4f7e31596101/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/3415b4a4288560618fd99ddab22588f6007a0213/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/64b6fe7b35addeda8d362e0b888fa745904a21ff/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/32a1c4e6f191b9e4d4193560b598e4668b9c8f6a/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/b74da33f37c59055ff53f993d9f9c9d39b7932d1/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/3210854b97a8609ed7d139ddfbf822df792bb2ef/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/303c085512d60f6f2abe521099d228606f25acf2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5b2f317731e9464d568b63919b74e90d/raw/ad90825b40dbd6c346e7ba74ada9e47ddac76b7b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11378/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/cb1ba2aeb7a9df7ba8617b498b3e35dc34b5e396/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/484d50c4afe2e8be5183d08f6d68fd336bc37e8d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/eff875ee251731579210f6e0a1d91a58e6614557/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/bd4297b8ff8c719a797e3e6c7b005db70e48a92a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/06ce96c581ac1fa3aa4e465e99d988f6d3b76201/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/3d0a4b24265262b6ff9de36437ed897de25cd671/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/c4552b894effecec9ed49892a3f865ee164fadef/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/3ec984450c71e9cf4cdf0e1a871a56a4f73264a8/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/4ca807142d4ff303f8880682859909dd50a96e6a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/692721334d30ab7ab483b6f90c5d9f445f31d38c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/5caa4dce615c6866d438e2f8ce32d55c03da4274/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/e16de0da51393c3a068b7e130aa22d544b8146b7/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/e020bba44d505f54ce01c360adfbfafcde7a43bf/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/88fafbfa8b618216e9dff0315d4a278d5558ed2b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/fe358f5aefe231f98ea8f132eebed05e68d6603a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/92dfd5c9f9ea1450a2c14d55b70416d958247870/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/50cfcbd8a8ce76d10d868ca55aa5fc45872f74e4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/44ce6523d940d1efed14bb3ce3f2bdde20708ea8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/6c5686563678e733ecb8257fa46962f01d4b3ce4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/c4845de5bbbdba611dd149ce00fdf4f1e2da97f6/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/a2b7130fdd87a43dd10456fc0498543135e6736f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/75ff0fcc447d688e72f4f63bd84a03407b9aea06/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/01f12b03dd7a5b3c8e539d85ac99e8feaa255ea9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/f1e33bc890f2b1b431b6c96d95c6868dddfd973d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/20ac3e95f5c9727e6310c41690db20c1c0f5b853/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/ae28f9e19f72055dc1c5f866362f2242e82d1563/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/45952a8c4e9e3ec7bcd8414d04b7dc045f90ab04/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/611eb60af67ff0b7f8a545bce29eb34e57d96c31/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/8ee8471e7784663f77b1fbce22c40196c5a99a63/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/1f9f23daaa6e81a71ad480a22aad31dfc0fabd12/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/1b951b7bcaef4a4884e66d415e2c39bf324d5f7c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/4ecbc16fd2dce12543323570219ed395ea17d352/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/508ef802fd2709e5c955d5302e9d2722/raw/5cecc225f4bc4a35c01abaed7cba15e6133ad50e/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by yosefe** [comment]
@shamisp can you pls take a look?

**Pull request merged**
