### PR TITLE
UCP: Rename stub_ep to wireup_ep

### PR DESCRIPTION
**Pull request by yosefe**
"stub" in UCP will now refer only to the ucp endpoint created for sending protocol replies (for example, when getting rendezvous request or sync request), before the full address is received.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4213/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask @evgeny-leksikov @alex-mikheev can u pls review?

**Comment by yosefe** [comment]
@evgeny-leksikov yes
before the fix "stub" was used in 2 places - for uct-emulated-wireup-ep, and for ucp-ep-without-lanes
after this change, 1st one is renamed to be "wireup_ep"

**Comment by evgeny-leksikov** [comment]
@yose i see, thanks!

**Pull request merged**
