### PR TITLE
UCT/SELF: Moved SELF sources into SM. Common atomics are moved in the

### LINKED ISSUE #888: self transport fixes
- check what MPI and shmem spec says about overlapping source/receive buffers for "self"
- if we can, move 'self' under 'shm' and put common put/atomics inside shm/base

### PR DESCRIPTION
**Pull request by shssf**
same way.
- This commit fixes #888

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1542/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2202/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2203/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2204/ for details.

**Comment by yosefe** [comment]
:+1: 
@shamisp pls review as well

**Comment by shamisp** [comment]
👍

**Pull request merged**
