### PR TITLE
UCP: Move wireup fields from ucp_ep to stub_ep.

### PR DESCRIPTION
**Pull request by yosefe**
Following the discussions we had about reducing memory footprint at scale.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1028/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/454/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/455/ for details (Mellanox internal link).

**Pull request merged**
