### PR TITLE
UCT/API: Expose transport flag for possible duplicate active message.

### LINKED ISSUE #619: remove hard-coded check for cm transport in test_p2p_am.cc

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #619

Adds checking for missed async events during progress, which solves SIDR timeout errors with CM transport.

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe To be honest I'm not sure that this a right solution. Is this ibcm "feature" ?

**Comment by yosefe** [comment]
it's because i don't create a persistent ibcm id, instead i destroy and reuse them.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/963/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1570/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1571/ for details.

**Comment by yosefe** [comment]
@MattBBaker  @shamisp is there any similar limitation in ugni_udt? something we can generalize?

**Comment by shamisp** [comment]
@MattBBaker @yosefe I did have odd problem with udt. But I'm was not convinced if this was out of order issue or duplicated. Maybe we can ask LANL folks (@hjelmn)

**Comment by shamisp** [comment]
Adding @hppritcha .

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/964/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1578/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/969/ for details (Mellanox internal link).

**Comment by hppritcha** [comment]
I think this is a reasonable approach for networks that may potentially deliver duplicate messages to an application.  However, wrt gni, i'd be suspicious that just saying you're getting duplicate messages from GNI post datagram protocol is likely masking a bug in the UCT GNI TL.

**Comment by yosefe** [comment]
I'll ask this directly - what is the property of udt (or the UCT implementation of udt) which makes it an "incomplete transport"?

**Comment by MattBBaker** [comment]
@shamisp What was the weird problem you were having with UDT? I've been doing some rocket surgery to UDT to support async callbacks of late so there are a lot of changes coming in the pipes.

@yosefe What do you mean by incomplete? I know that one of the major limitations of UDT is that you can only have a single out standing datagram request at a time, so that makes the transport not preferred.

**Comment by shamisp** [comment]
@MattBBaker - If you try to run perftest over udt it occasionally fails. gtest by default skips it:
https://github.com/openucx/ucx/blob/master/test/gtest/uct/test_uct_perf.cc#L108

You can remove this check and test

**Comment by yosefe** [comment]
@shamisp Is the only problem with performance tests? Maybe we should not do anything for ugni_udt then, but only for ib cm?

**Comment by shamisp** [comment]
@yosefe @MattBBaker My concern that this will break once we scale.

**Comment by yosefe** [comment]
@shamisp I've amended this PR to affect only CM transport.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/984/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1591/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1592/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by MattBBaker** [comment]
I think the right choice would be to have a UCT_IFACE_FLAG_AUX flag to indicate that a transport is meant for wireup auxiliary transports rather than as a run time transport. This seems like it would solve the UDT problem cleanly.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1619/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1007/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @MattBBaker Now the PR fixes only CM and does not affect UDT.

**Comment by shamisp** [comment]
@yosefe please rebase

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1060/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1061/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1062/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp we have some issues with external jenkins. Can we merge this?

**Comment by shamisp** [comment]
@yosefe - please go ahead

**Pull request merged**
