### PR TITLE
rc_mlx5 prefetch optimizations

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
@yosefe I can't seem to be able to change assignees and reviewers

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4599/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4605/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
what is the improvement in performance ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4607/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by artpol84** [comment]
@yosefe, I have couple of updates to this PR that I need to test. Please consider this PR as WIP

**Comment by artpol84** [comment]
Haven't noticed the tag :)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4665/ for details (Mellanox internal link).

**Pull request closed without merging**
