### PR TITLE
CONFIG: Report whether MPI tests are enabled

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
Probably we should add comment somewhere in configure that UCX may use mpirun as a launcher. Some time ago there was a confusion that UCX uses MPI for networking.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9077/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9084/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp it says "MPI tests" in the output

**Pull request merged**
