### PR TITLE
DOCS: Fixing --with-docs-only

### PR DESCRIPTION
**Pull request by shamisp**
* Minor bugfix (mostly useful for OSX users)
* Adding jenkins test case for this build

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3064/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/613/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/614/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2566/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - can u please check why it fails.

**Comment by yosefe** [comment]
@shamisp this is unrelated failure, i've restarted the build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2569/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe can you please review ? if it is all good let's merge

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2573/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2574/ for details (Mellanox internal link).

**Pull request merged**
