### PR TITLE
UCT/API: Expose support for slow-path progress callback on uct_worker.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2371/ for details.

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
@yosefe - these are slow path functions (registration/de-registration). I think it would be preferable to avoid API blot and consolidate registration functions.

**Comment by yosefe** [comment]
what do you mean "consolidate"? they have different parameters/signature

**Comment by shamisp** [comment]
AFAIK one accept void , another some datatype. Should be easy to merge ...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1708/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2376/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1713/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍 Adding @MattBBaker

**Comment by MattBBaker** [comment]
👍 looks good.

**Pull request merged**
