### PR TITLE
UCP/WIREUP: Remove special case for self/shm multi-rail

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/1829a8ba0f93fb4516781ba7d1d0e4290dfc538c/_main) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/cce5e5e92cfbc1cfc0482134e835395099c13c0c/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/ae2a30ed2ff3ac54acf8b76adf09f2fae0e7b300/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/21e78d96611f096976b4baca309c9982b64ce066/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/7b5c7ecbb51706d5f2305b342fdabd9f504ff869/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/e3efcc97b6fb21d3d98df2855c3f7411910cc3a8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/e09a1b4a2d520a0e0a5a476a31778332eacbafd2/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/f291175cc8f2e3fb5c8e8b153c0fa4bbfe675e45/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/c5e09906a5dfd89aba2f1f2dca2f9df7bb032453/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/24793818a244fb1929734e4054413e06a2a33e34/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/58504b948778f618359b65101db44ccea0086172/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/a3eb3f2c68613985cafbad9230c12a4ec58a02b4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/5b2863f19dfe02c5f5f695fb17c7acb5e248bb75/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/afa4484715adc228fd5ea9c1c92a844d0cc7ac9e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/7ec8305bc0badbb005395848b7f0e6958926372b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/7a774362e3df04af96fe863929dad460563c62d8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/075e53671eec1c9ff4f446ff7c1b72bdad31287b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/7a9dbad582999bcf52aece2fef8b6fe1fb2838ac/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/5c4b4d5364611b82e42da1f31ddd85fc93c66cab/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/4f6afbf5b621d31ef2c8fcf7316192347a56e379/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/5886c180b8ffab5d23700e1877d4da299a5b7c21/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/b4fe3e4f58aae1193f7fe3b49618b7d0fdd2ae5c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/7950c69b12171d8852187e436a5e9a4081276fd3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/c07dd6828ded3582eb9087ade438a78aee200171/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fcbf7217abee3dc29a586e44952d9c9/raw/432a6311b72fd9a1559e3b89fd33d1b12b3ef8d7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
```
6:34:07 [ RUN      ] no_ud_ud_x/test_ucp_sockaddr.listen_bidi/8 <dc_x,mm>
16:34:07 [     INFO ] Testing 65.65.65.12:43675
16:34:07 [     INFO ] < rdma_bind_addr(addr=65.65.65.12:43675) failed: Address already in use >
16:34:07 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-ppc-jenkins/worker/1/contrib/../test/gtest/ucp/ucp_test.cc:629: Failure
16:34:07 Value of: status
16:34:07   Actual: -15
16:34:07 Expected: UCS_ERR_UNREACHABLE
16:34:07 Which is: -6
16:34:07 [     INFO ] no active messages transport to 65.65.65.12:43675: Unsupported operation
16:34:07 [     INFO ] rdmacm_ep 0x100370193f0, status Success, flags client: rdma_cm private data pack function failed with error: Destination is unreachable
16:34:07 [     INFO ] ignoring error Destination is unreachable on endpoint 0x3fff865d0000
16:34:07 [     SKIP ] (cannot connect to server)
16:34:07 
[  FAILED  ] no_ud_ud_x/test_ucp_sockaddr.listen_bidi/8, where GetParam() = dc_x,mm (236 ms)
```
on r-vmb-ppc-jenkins

bot:mlx:retest

**Comment by yosefe** [comment]
@evgeny-leksikov is this the error you see with ep-to-iface transports?

**Comment by evgeny-leksikov** [comment]
> @evgeny-leksikov is this the error you see with ep-to-iface transports?

no, this is https://github.com/openucx/ucx/issues/4739

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/5dbadfe60c39e3ac2788e8f02cb13a13b6111f59/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/b9f5cab0aa25fdcdb63efe70bbbb46922f34519d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/d9418f2d2d2266b07b416de308bdf10f5f7d03f4/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/e77df4adc8c571a2e730147d70fff94a86b94306/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/d6b38a04a2cffc776f577dfb6a82963f977d751b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/c2ae420c9510dbc6d3dff4e57fd57345c6086d33/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/310aafbe4a026a1887ddb2c7dc6447e5692b343d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/7361ff7d2f9e9a69c8ad024bc69245b53a006e4e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/695c820571afe6f2e7028dd19dfce4da27fe2155/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/cdf43accb37623995c4d024166bf472936e4b3e3/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/6b75eed3718add29bfdf207680a288601a96f770/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/7f5a0171d4a4398b2a357ae6b57c4076be26e99f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/b8d599bc4b4c69d701f53fd310e7c860b5236758/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/27ffa24499988396ed0db0ce5e38c80f0ba19670/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/7612629607a3570ab4e444d9cc2292fb97c854af/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/8aba2111c80be11a25fccd40a2e797bff59f8d43/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/83345dbd6ca705ed60d80eebf54fff260cd48d5b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/d27dae53f7e73fa17557f3c08475684397edf31c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/cde602ffdc1b128df2bc05615ea6e67dc6664b49/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/82c2ae36d50db803b4927f0be0ddd897e295ff75/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/50c1411c12997b95b10e2b8cb5fe653c70e22870/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/66ddd9a8000af5fe6c809e272788228091ca7d26/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/f9b1988be22acf8b0e33698c7b03fd2d4b7795f9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/10dbb7716a0685fac4d6b09d9061b8a1f7f33d72/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d9b6d0f5f562da8d9e8020efc185be1c/raw/73b7294ed457eb4e87a34a8ab5c452088b428d0f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by bureddy** [comment]
@yosefe we have a behavioral change with this PR when cuda is enabled.
when Cuda is enabled, 
- KNEM is added to rma_bw lanes
-  both IB and{CUDA/RoCM}_IPC lanes are added to rma_bw lanes 

IB is in intra-node rma_be lanes, so with this
  - Intra-node HOST will see better results because using both IB and KNEM
  - memtype IPC protocols seeing poor perf because  it is splitting across IB and {CUDA/RoCM} IPC

**Comment by yosefe** [comment]
@bureddy why is it bad to split?

**Comment by bureddy** [comment]
@yosefe  may be split overhead is too much and BW capacity between the lanes is too big ( NVLINK2- 50 GB ,  IB - 12 GB).

@Akshay-Venkatesh  can you post how much perf difference

**Comment by yosefe** [comment]
in this case most of the data should be passed on cuda-icp. does it publish correct BW?

**Comment by Akshay-Venkatesh** [comment]
@yosefe Here's one sample:

```
$ ucx_perftest dgxA -t tag_bw -m cuda -n 100 -s 1000000
+------------------------------------------------------------------------------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| API:          protocol layer                                                             |
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
| Test:         tag match bandwidth                                                        |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| Data layout:  (automatic)                                                                |
| Send memory:  cuda                                                                       |
| Recv memory:  cuda                                                                       |
| Message size: 1000000                                                                    |
+------------------------------------------------------------------------------------------+
           100     0.000    55.220    55.220   17270.41   17270.41       18109       18109

$ UCX_RNDV_SCHEME=get_zcopy ucx_perftest dgxA -t tag_bw -m cuda -n 100 -s 1000000
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
+------------------------------------------------------------------------------------------+
| API:          protocol layer                                                             |
| Test:         tag match bandwidth                                                        |
| Data layout:  (automatic)                                                                |
| Send memory:  cuda                                                                       |
| Recv memory:  cuda                                                                       |
| Message size: 1000000                                                                    |
+------------------------------------------------------------------------------------------+
           100     0.000   145.998   145.998    6532.11    6532.11        6849        6849

```

If we fix GPU-HCA binding we get better performance though:
```
$ UCX_NET_DEVICES=mlx5_0:1 UCX_RNDV_SCHEME=get_zcopy ucx_perftest dgxA -t tag_bw -m cuda -n 100 -s 1000000 &
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
+------------------------------------------------------------------------------------------+
| API:          protocol layer                                                             |
| Test:         tag match bandwidth                                                        |
| Data layout:  (automatic)                                                                |
| Send memory:  cuda                                                                       |
| Recv memory:  cuda                                                                       |
| Message size: 1000000                                                                    |
+------------------------------------------------------------------------------------------+
           100     0.000    44.940    44.940   21221.28   21221.28       22252       22252
```

The drop in perf can occur because the HCA performance for the given device may not be optimal.

**Comment by yosefe** [comment]
@Akshay-Venkatesh so the problem is that HCA bw does not depend on locality?

**Comment by Akshay-Venkatesh** [comment]
@yosefe 

HCA bw does depend on the GPU selected for the transfer. When GPU memory is used with get_zcopy multi-rail, there is a check needed to see if HCA perf with that GPU is high enough for use. This is part of the topo-revamp work though. 

BTW, cuda_ipc reports 24 GB/s BW but this is static unfortunately.

**Comment by bureddy** [comment]
@Akshay-Venkatesh can you also check with NV2?
@yosefe yes HCA BW for cuda memory is not considered the locality. w/o locality the capability might be < 1 GB.
BTW, is it ok to use IB for intra-node along with KNEM? isn't impact inter-node communications in large all-to-all kind of scenarios?

**Comment by yosefe** [comment]
we consider PPN : HCA BW is divided by PPN (dedicated vs. shared bw reported in iface_query)

**Comment by souravzzz** [comment]
@yosefe Since IPC can work over PCIe as well as NVLINK etc, how should the IPC TLS publish the correct BW numbers?

**Comment by yosefe** [comment]
@souravzzz the UCT transport should detect if it's PCIe or NVlink and publish the correct BW number

**Pull request merged**
