### PR TITLE
UCT/ROCM: move configure to config dir

### PR DESCRIPTION
**Pull request by yuq**
To be shared with UCM ROCM hooks.

### CODE REVIEW

**Comment by miked-mellanox** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8990/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@yuq there is a conflict in configure.ac now..

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9008/ for details (Mellanox internal link).

**Pull request merged**
