### PR TITLE
UCP/RMA: Add profiling to blocking RMA functions.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2768/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/184/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2156/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
well...I would argue that we should rather remove all the blocking functions ...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2774/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/194/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2163/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/200/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2169/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2178/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Yossi,

I have one issue will this approach. From the glance - it is hard to understand what is the function signature and it break stand C tools that I used for code browsing. We should find another way doing this. Otherwise it is going to be huge pain.

**Comment by yosefe** [comment]
@shamisp eclipse has no issue with understanding the signature

**Comment by shamisp** [comment]
1. I have.
2. How this will work with ctags, cscope, etc ?

**Comment by yosefe** [comment]
we already have macros in the code and if some tools can't parse them it's a problem, but the alternative is to complicate the profiling mechanism (require user to define the function twice)

**Comment by shamisp** [comment]
These I high level function that people and developers will want to see.
Can we use some sort of weak symbols for this ? Similar to MPI ?

**Comment by shamisp** [comment]
Also, this will enable 3rd party tools integration like TAU and others.

**Comment by yosefe** [comment]
i will check weak symbols options

**Comment by shamisp** [comment]
What about VIM, Emacs, etc.

**Comment by yosefe** [comment]
@shamisp added a file which fixes ctags

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/345/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2876/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2281/ for details (Mellanox internal link).

**Comment by shssf** [comment]
@shamisp How you can see the weak symbols could help in internal function profiling? In this case, It looks like we have to implement some kind of `P` interface (similar to `PMPI`) because we have to know original function address to call.
Other approach might be in ELF parsing and replacing interested functions by profiling functions. This approach is also looks suspicious.
Currently, I can't propose better solution then this PR. It is looks like the `ctag` issues could be solved by `.ctags` configuration file (implemented).

**Comment by shamisp** [comment]
AFAIK the weak symbols are used to overload MPI interface with PMPI. Good point about ELF.
Maybe we can borrow some scripts from TAU tool. AFAIK they have a set of script that auto-generate profile interface.

**Comment by yosefe** [comment]
@shamisp This is not same as "profiling interface" since it's intended to profile inner code as well.
Weak symbols can not be used for internal functions, only for API functions (consider also inline functions which do not have symbols at all).
The method proposed here handles all cases with minimal code addition.

**Comment by shamisp** [comment]
👍

**Pull request merged**
