### PR TITLE
Port CI fixes from master to v1.11.x branch

### PR DESCRIPTION
**Pull request by dmitrygx**
ported #7359 w/o `buildlib/pr/codestyle.yml` changed into v1.11.x branch

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
@dmitrygx looks like codestyle part also need the fix

**Comment by dmitrygx** [comment]
> @dmitrygx looks like codestyle part also need the fix

@yosefe yes, it is also required. but I thought that it wasn't enabled in v1.11.x since `buildlib/pr/codestyle.yml` doesn't exist.
but it was a part of `buildlib/azure-pipelines-pr.yml` before splitting them to different yaml files as we have on master branch.
applied required fixes in `buildlib/azure-pipelines-pr.yml` file

**Comment by dmitrygx** [comment]
```
##[error]No agent found in pool MLNX which satisfies the specified demands: ucx_sputnik -equals yes, Agent.Version -gtVersion 2.163.1
```
it seems that the problem is related to `ucx_docker -equals yes` changes in yaml files

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe shall I squash commits? or better to keep them separated?

**Comment by yosefe** [comment]
> @yosefe shall I squash commits? or better to keep them separated?

Pls squash, looks like tests are good now

**Comment by dmitrygx** [comment]
> > @yosefe shall I squash commits? or better to keep them separated?
> 
> Pls squash, looks like tests are good now

@yosefe done

**Comment by dmitrygx** [comment]
@yosefe are the failures on gpu/roce nodes known? I guess it should be fixed somehow in master

**Comment by yosefe** [comment]
pls try to port also #7085 and #7508

**Comment by dmitrygx** [comment]
> pls try to port also #7085 and #7508

@yosefe thanks, ported them manually

**Comment by yosefe** [comment]
@dmitrygx i think also need

**Comment by dmitrygx** [comment]
> @dmitrygx i think also need #7346

the PR was prepared on top changes which are not reflected in v1.11.x, so ported manually

**Pull request closed without merging**
