### PR TITLE
UCT: Error handling cap for rc_mlx5

### PR DESCRIPTION
**Pull request by brminich**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1424/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2068/ for details.

**Comment by brminich** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2070/ for details.

**Comment by yosefe** [comment]
@brminich how about this: handle_failure callback would accept `uint32_t qp_num` as 2nd argument (instead of void*), and use this callback in rc_verbs as well, for consistency.

**Comment by brminich** [comment]
I thought we could pass ep pointer as a parameter in UD cases. So in RC case I would pass a pointer to wc as a second parameter, since we also need status for printing an error.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1426/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
in ud case, send completion with error is considered a local failure as well, since the reliability is done in sw and there is only one qp.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2071/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1428/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1430/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2076/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2077/ for details.

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
