### PR TITLE
JUCX: Do not delete reference to listener connHandler (v.1.10.x)

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Port #6273 to v.1.10

## Why ?
A critical bug that doesn't allow to establish multiple client- server connection with connectionHanlders.

### CODE REVIEW

**Comment by yosefe** [comment]
@petro-rudenko can u pls add it to NEWS?

**Review by yosefe — APPROVED** [review]

**Comment by petro-rudenko** [comment]
```
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:724: Failure
Expected: (UCS_INPROGRESS) != (status), actual: 1 vs 1
free not completed EP close request: 0x2c9e3c0
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test_helpers.cc:53: Failure
Failed
Connection timed out - abort testing
[swx-rdmz-ucx-gpu-02:13349:0:13349] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
==== backtrace (tid:  13349) ====
 0 0x000000000005c6e8 ucs_debug_print_backtrace()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../src/ucs/debug/debug.c:656
 1 0x00000000000e2d47 __GI___sched_yield()  :0
 2 0x00000000008d2c9f ucp_test::progress()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:156
 3 0x00000000008d32ab ucp_test_base::entity::close_all_eps()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:746
 4 0x00000000008d340d ucp_test::disconnect()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:197
 5 0x00000000008d340d ucp_test_base::entity::get_num_workers()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:874
 6 0x00000000008d340d ucp_test::disconnect()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:187
 7 0x00000000008d3468 ucp_test::cleanup()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:78
 8 0x00000000005d4b00 ucs::test_base::TearDownProxy()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:315
 9 0x00000000005b7dc9 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3562
10 0x00000000005abfdc testing::Test::Run()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3643
11 0x00000000005ac0e5 testing::TestInfo::Run()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3812
12 0x00000000005ac24f testing::TestCase::Run()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3930
13 0x00000000005b09fd testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5808
14 0x00000000005b0ce0 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5725
15 0x0000000000548658 RUN_ALL_TESTS()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest.h:20059
16 0x0000000000548658 main()  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/main.cc:102
17 0x00000000000223d5 __libc_start_main()  ???:0
18 0x0000000000596361 _start()  ???:0
=================================
[swx-rdmz-ucx-gpu-02:13349:0:13349] Process frozen...
make: *** [test] Terminated
##[error]Bash exited with code '124'
```

**Comment by petro-rudenko** [comment]
bot:pipe:retest

**Comment by petro-rudenko** [comment]
@yosefe let's merge it for 1.10.1

**Review by yosefe — APPROVED** [review]

**Pull request merged**
