### PR TITLE
UCP/WORKER: use ucp_worker_iface_get_attr

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
Refactoring: use `ucp_worker_iface_get_attr` where it's relevant

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12587/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/e99a2e65e18938ddd624860ea97ae71027cc5201/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/5c887b41cce03d1687502d5bf31f0bc1ad4e3c81/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/fe406845e884d9d8d58ca2e0c97e7e48b4e1a093/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/560a403a1d400cee9f02096edf77198adf7353d1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/13326b76e2e7116a33896ea89a2345ff6899fe36/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/2890326943071e4e125fd4808860062cec7c0bc6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/331f18fe86d475773d7ea10c895647213adb9cbe/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/fd3f3300f3af87cbb917169a02445e5c8c26d0b2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/e763295d81518820a4a8bcca1e9c558d9fef4cd0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/2e989634f6da7008f7ba749037b0b6cb8e22523b/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/5f720757b45e2564a40d00ae3b8d3a3a002d1216/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/91b735d991b6ef71413b09daca230e812585c3f1/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/d2ec4833510eee79593518570d7dc8d9b5868a3e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/530d58d84d9a5c3ba431f2b2b47425ab6571dee4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/4e1ee6ec9251738384ab4649e7cc509a1470b8d4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/6037936d5ee7646b101324031604ff06fdd102ee/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/5366bd4b48af793d4e54c3e16e7dbf9e33459c01/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/c9f43d078dbffedaaaf139aff4337ea6137ab19c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/b61b88b21c9eec078dbc3ea0ccebb454542c51b4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/bd1031253bfdd97b33d5cd21d6f88d00c03935e7/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/365682f768b8962de2c7346c94a5855284ae6583/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/ae2dafa2769503a1ded4b84deead7dd523a1bd0d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/77b0abb1fbe88783bece08de40281d31477e1f17/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/ba1dc5d9597428b5f88927d6d2a2dd4ced31c70d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/ee81df5de14660aa7f33149e20b4f30ae809c7ea/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/f21380710faf23cfb607c9be11060e5a8e68a7fc/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/457c3f1823097209db7f1cc5eb5a19f14684a4e9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/d597ced800ace07aa6f026ee68faaf59e40b282f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/27af5e42e37c4788b10affa4c013e16d/raw/913d01a15c88e353670c3435c202a902ffaf1ef5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by alinask** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
