### PR TITLE
SM/MM: make the FIFO element size configurable.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
You can ignore failures in my tests (again thresholds).

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/883/ for details.

**Comment by yosefe** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/305/ for details. (Mellanox internal link)

**Pull request merged**
