### PR TITLE
UCT/UD/DC/MLX5: Add compact address vector optimization.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2528/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1882/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2529/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1883/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev can you take a look?

**Comment by yosefe** [comment]
we have AV compression on hpc-test-node2 (should be added to jenkins, running manually for now) and no-compression on hpc-test-node

**Comment by yosefe** [comment]
@alex-mikheev this PR raised an issue with dcs_quota fairness which i will address in another PR

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2534/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1888/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls take a look

**Comment by alex-mikheev** [comment]
@yosefe any changes besides last two commits ?

**Comment by yosefe** [comment]
no (no force push here)

**Comment by alex-mikheev** [comment]
do we need a conf setting to force disable av compression ?

**Comment by yosefe** [comment]
yep, i will add

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2571/ for details.

**Comment by yosefe** [comment]
@alex-mikheev added a configuration. i extracted it to ud/dc common structure. i plan to add a base class for endpoint (with base_av+grh_av) to that common header as well, in another PR.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1925/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1926/ for details (Mellanox internal link).

**Pull request merged**
