### PR TITLE
ALL: License clarification

### PR DESCRIPTION
**Pull request by shamisp**
Addressing #302

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@yosefe please take a look.

**Comment by shamisp** [comment]
Also adding @jengelh to review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/848/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/274/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@jengelh, does the change address your license concern ?

**Comment by jengelh** [comment]
It does for me. I still has to pass the Linux distributions' reviewers :-)

**Comment by shamisp** [comment]
@jengelh - do you know usernames of Redhat, Suse, and Ubuntu reviewers ? I would like ask them for an opinion.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/857/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/284/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe - can you please check why it fails on Mellanox

**Comment by shamisp** [comment]
@yosefe ?

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/861/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/288/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
:+1:

**Comment by jengelh** [comment]
debian/copyright still contains it. IMHO, that directly should just be nuked anyway, as distributions will always write their own recipes anyhow.

**Comment by shamisp** [comment]
@jengelh ``debian/copyright still contains it. IMHO, that directly should just be nuked anyway,``
I'm not sure how to "read" this comment. Can you please clarify ? Thanks.

**Comment by jengelh** [comment]
```
09:36 ares40:../openucx/ucx > git rev-parse HEAD
c3a0e0a96e0168796132b9408039ea3792f30c76
09:36 ares40:../openucx/ucx > cat debian/copyright 
/*
* Copyright (C) Mellanox Technologies, Ltd. 2001-2013.  ALL RIGHTS RESERVED.
*
* This software product is a proprietary product of Mellanox Technologies, Ltd.
* (the "Company") and all right, title, and interest in and to the software product,
```
1. The file contains an A.R.R. notice which is confusing. Considering the remainder of the source is marked as BSD-3 (LICENSE file), one will wonder what the ARR actually applies to.
2. Speaking of the debian/ directory, it is better to just have it completely removed. "Distribution-specific things belong into the distributions" is the general mantra most software projects have been following, also because distributions often ignore build recipes and use their own (even if debian/).

**Comment by miked-mellanox** [comment]
@jengelh - once distributions will adopt ucx into Community OFED and have own "debian" files - we can consider remove it and use distro-provided.

**Comment by shamisp** [comment]
@miked-mellanox @jengelh , Oh, the debian copyright has to be aligned with our license (BSD3) and distro may replace it with whatever they want.

**Pull request merged**
