### PR TITLE
UCP/UCT/TEST: Rename "rc","ud" transports to "rc_verbs","ud_verbs"

### LINKED ISSUE #4390: Remove UCX_TLS rc alias or rename rc TL to rcv
So, I checked few people outside of Mellanox about their understanding what "rc" in UCX_TLS actually means. As expected, nobody had an idea that rc is an alias that silently enables rc_mlx5. The actual name for rc transport is rc_v and not rc. My suggestion is to remove rc alias and map it back to an actual rc TL.  Alternative is rename rc TL to rcv.

### PR DESCRIPTION
**Pull request by yosefe**
Fix #4390

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/6a0be37d22d2af3dbbd415f5737527600dfb6232/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/504881ab77cb074aaecc18128687ded5c28a82b8/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/683af645cb239b2a285d2024a65af4cf4b948d5b/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/fae74b5f45af88ec2eb5189d210791a756d84432/hpc-test-node-new_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/d7c2baf4f303d3615bbe9d825b3fbb5c00814c7d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/2b7b037e93496f78d1577487099299524d51e315/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/24078d724517eb4fe150cf7510664cc57600bfba/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/1da8fb4876834a6a6dcc0540d35251383690a31a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/2c557d02ed6056ed1fc826863822599f5a6dcf71/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/8781d32827daac73244a8e791846303ad69c6529/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/8183f776bcd0dc35922cbf3a5e85d59a1c01f854/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/53a658df300c2e3c6cb5986a238247dee6927641/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/13e619790f6172c703da481177b38e7d885a42f9/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/d9b60ca274637b2fd51acef10f47dfd8654f72cf/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/402388eda651b3167711d4d0d1f73ecd4e248e98/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/7b8ac39f74386f655c8cb06e9d6635678da26724/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/e20ca2b052e8547ef1b1b16243e8e3059c79ad1f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/603a32f39673bcc16b13ed669cabf628d5ec1419/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/f462e7f022dec9619740c200d87b9ec8aee5490d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/935878f70d393c5fdbb67b988b8817654c6a823b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/1a9f5e6ad9a50e686cf312a69e1391bf241cc350/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/3197d779c4ee573a8563dbf30339850229df33a3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/62077e84376dcafdd4e7af45ca72695c74fa2999/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/4d3fb551ba71848465264a238a217f7c78b07aa1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/319f4e8519d807f18da03229cfb65fcf/raw/219183638080e142f9e43d1ee541383cfe68b7a4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/ba6dc1e6935552d9a0f28d32fd2a172f5cf1d32c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/fa89143af80821bb042e31450a8269fb0585b412/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/e975caa1891d728726ce86b8968310a676590567/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/c26c2fdb2c6d25909955c61cdfa03317222c9b40/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/c85655e5ee013c636c53c02ceb598449a2c5e701/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/1dadf58eb2705b5eb9135659a9bc89229bfd58c3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/ebcfcb68c6bdf0a64755685031d09d20ef861271/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/676f36ee61780d333a50266f5e77d045ac219398/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/a134daa92efe44c2929c43d8252b898d8241b550/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/8a4b04bc5ba3b285688fdb7545be34a13101cda4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/63eba0738fb3841b4537072b52428423500b3454/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/6093f6f4ee9c70ee5cb426430b68fc0d24161947/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/db3603c3b93e4e20cd781938f0513adeefbcd7fd/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/2a766acdc0255ed87ca06c88b1bdb01356cd70c7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/dbf33f55f6bf03e2d238ce878f6920c9050b2aa2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/9b8bc685c705012c05b825daffacd153d45bdd63/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/26d973957652ae4ecb7e23e5b4cf075d0e92cffc/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/9db80ff35ea295b8f76a3851d84b15a2a549af47/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/723ff65ca5997c89aeb812d76edf42acadeaab5c/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/94be63acdee0cec4120f2d91753f91a380df0aa8/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/7f338563ed19c9145132c100ae5f9bedd756e3d3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/12948f30c63b741a3843779a30cfede73b0836d8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/093be0d823cc19226de47429584ec32290eed5fd/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/1a2c30d3c6c0a12c36fe9b29c487a458186fa27b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/794439b2a5222fa746fc84c86f15d64c/raw/558e3712a0388dea0e625bfece0f8d5a57a34086/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@shamisp pls take a look

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/1d4e606e290cccc9ebc8d559a7c0f8454567baa3/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/6cc5c5685e6cb3d782fef52ec797655132eb1f18/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/1d241d4ae4de9fed1d7a64b0a7dc6afe3a42eb78/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/f8f47671e53c0caa1712fb330861a5848bb59f68/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/7609d85c1c6ab45ee2bc0eb8b5af693bd56166fd/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/4807c31abf5e44e283348ebff619c74976c674b4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/0a892528a2d1f7883d3a07b38b9fe8673100c8af/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/b5c0287434c9f755e27782983c8dac2b6327cdfa/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/0759fd7a66f4b16586b4519dcd812e1c2302f8fc/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/8792ce16160d3192b3b1d549aea6267b76285f4b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/7e62b381a685159b76c1805d51c4dfc801a218a2/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/385bac54aabd9bb78f9d51427d24d94baf88b49b/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/ede9c150b50bacc04f78c6f8aaeda9fb682ed316/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/32f2eb89425eced14fec4b4ba2ddc3878b7c8a70/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/7cf33fdb2fdc1c817c97296d339eed4e048486ec/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/d9bb5c4c7a2e1245646da72c24e7140c50cfee4d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/47d327bc52a66fc874f927ebba8da4f9684bfb16/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/c452e77d79ac4b38db789612a1b4224b40680ca1/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/fde7de6d116ddb03f210566e55a57d38aa25ea3a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/99191a252b3ed021081b1b749c793f3e47130ad6/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/305ecf1d3fdd0fb547ea9444b15457cb5eb498f3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/af20c1d5ddf9fefb30123beeb89684b29b1e0252/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/26be0574ebaf4b92d63b1ba5ad43e0e62a9d7b39/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/2692193e1260a4f973cd8ec03d21f31b6c73470d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313230b6c8d14baffad440a84d7e140/raw/302462fe7371e4217cfbec943f8a15ff68dccb79/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
