### PR TITLE
UCP: On-demand progress wih signaled active messages.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4231/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4237/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4242/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4244/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@evgeny-leksikov @alex-mikheev @shamisp pls review

**Comment by evgeny-leksikov** [comment]
@yosefe pls provide more description with roles of new introduced EPs/lanes from this and previous PRs. It becomes hard to understand (at least for me) what is used for. For example, is proxy_ep always signaled? What triggers enabling/disabling of progress? etc

**Comment by yosefe** [comment]
The new PR is meant to allow dynamic progress for transports which support only explicitly-signaled active message events (and not event for any kind of active message), such as shared memory.
[shared memory has such limitation because it's expensive to signal every active message]
The support is done by sending the first active message in ucp_ep's lifetime as signaled. This would generate an event on remote side, call to ucp_worker_iface_check_events_do, and potentially activate the interface (add to progress). This was introduced in #1717.
 In order to achieve that, the active message lane is replaced by a signaling proxy endpoint (ucp_signaling_ep). It implements all of uct_ep's functionality, except that the first message is sent as signaled and then it replaces itself (in ucp_ep->uct_eps[] array) by the underlying rela uct_ep [note: if 1st active message is short, it is sent as bcopy, because am_short does not support flags].
When we select the lanes for a ucp endpoint, it is also checked if signaling proxy may be required, and this is kept in ucp endpoint configuration (key->lanes[].proxy_lane).
If another lane (such as RMA lane) also needs to use the same uct_ep as is used for active messages, then that uct_ep will appear twice. This is needed to avoid extra overhead when both RMAs and active messages are requested by the application, but 1st active message is sent late, or never is sent.
This is how it would look in the ucp endpoint lanes:

before 1st active message is sent:
lane[0]: signaling_proxy_ep->shm_ep_A (config.proxy_lane: 1)
lane[1]: shm_ep_A (config.proxy_lane: none)

after 1st active message is sent:
lane[0]: shm_ep_A (config.proxy_lane: 1)
lane[1]: shm_ep_A (config.proxy_lane: none)

**Comment by evgeny-leksikov** [comment]
@yosefe 
Thank you for explanation!
> [note: if 1st active message is short, it is sent as bcopy, because am_short does not support flags]

do you mean zcopy according to #1717 ? Or this was added to minimize replacements?

Is proxy_ep somehow interacts with wireup_ep? Are there 2 replacements? (wireup -> signalling -> uct)

Why RMA requires extra signalling message? Let me explain in terms of verbs, RDMA WRITE/READ don't require progress on remote side (the same about atomics) but WRITE_WITH_IMM should generate event on event channel, right?
So, if this lane doesn't use AM (even if it was requested), there is no need to enable progress on remote side.

**Comment by yosefe** [comment]
@evgeny-leksikov 
1. no, short is send as bcopy. am_zcopy is also proxied to add the signaled flag
1. proxy_ep is base class for both signaling_ep and wireup_ep, but the last 2 are unrelated. also, signaling_ep is not created for p2p transports. so it's mutually exclusive with wireup_ep
1. that is true, RMA does not require signaling. for that reason, we avoid using same lane for AM and RMA in case a signaling proxy is needed for AM. Before this PR, they could use same lane.

**Comment by evgeny-leksikov** [comment]
@yosefe so, at start we have 2 reserved lanes (wireup and proxy)?

**Comment by yosefe** [comment]
@evgeny-leksikov Yes, in some configurations it is possible that 2 lanes inside ucp_ep->lanes[] will be proxy ("reserved" is not the right terminology). One would be wireup_proxy, and the other one would be signaling_proxy.

**Pull request merged**
