### PR TITLE
UCP/API: Fix spacing in ucp.h

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11772/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/9821ee84d51844d153957d697739efb4c57ea6de/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/2580b431364ad991097adabfdf6831d499b05d85/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/99c0e2f156d6528e323e9c30cbd9de15d830d88b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/a318b7d84f27f37b59fa8cd81060df5d9ebf014a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/c925729669beefb529d1300f04c03827329b2d44/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/9654a4185a3d348d46c58675d2f79d99f1993724/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/408826e854576b8d1ab2ac6507facc74f13bd9e9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/39108e93bb0ccbff18c634b7731885d57671b031/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/2651f2c9410137345e0d644e69502bb68a66beae/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/4c3607422678189cefd5bb44e521fa538dd41cac/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/569ab5bd05e959907e68c49d255981051df183a3/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/4f93fa3f9d578fc2197767bb7c33d30ad6eb41b3/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/56c471f0501cdf225261b6cc331ca0e6bac2d21b/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/839411a82d5a90b33bda587ccec838d394038e7d/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/d04bfc99b92daf8d79adc4e7263d7c285a60d02d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/5c06294d58bb2833d501aa4842b9f3e8d6d1d1ee/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/606417a870dadfb8e3f38da84cdd1f1564d78e45/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/45bb417c0c5e5ee9d62271d59f35e1b0989d5373/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/13b956e563480ffb721bfecccc24f9dfb4d2ae43/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/b0cc88b82b00c4e7ce8dc277b52a05c303e6ac4c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/96bc20d8196c67999b7439d70142879274faf66b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/e7d86de0484fbe2934ed96d0f3bda2a63cc97cda/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/a885b2d47406795a6aca00c54085be05fab725c4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/5abd31b6ecc2a93f3ca0608c44885a3e1743c1c9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/4089e061a3b8990187e6cd104dcb08debf01a326/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/c010564005c4f0368e6ce82e47bb48ab25805ca1/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/79b4c57c4c9dcef3e88d9393f61cfe59acef2036/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/970621cfac0dee1944a4798c753f1a29447889b3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aba6fee9f1812675a28d3ca79ae3dc26/raw/1da934b7e0e1034a62aebf55cdfe36262077962e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
👍 @tonycurtis ?

**Comment by tonycurtis** [comment]
> On Aug 7, 2019, at 8:49 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> 👍 @tonycurtis <https://github.com/tonycurtis> ?
> 

ucp.h:799 struct should have a name?

Tony

**Comment by shamisp** [comment]
@tonycurtis not sure what do you mean ? `brief` followed by name ?

**Comment by tonycurtis** [comment]
> On Aug 7, 2019, at 9:24 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> @tonycurtis <https://github.com/tonycurtis> not sure what do you mean ? brief followed by name ?
> 

There’s an anonymous struct @line 993 that should have a name
Tony

**Comment by yosefe** [comment]
@tonycurtis added struct name

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11799/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/5bdce5a0b620dbd13043eacd5cc9c54ce26d824e/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/c1af2c40cf88fd7b2851a880b366064081389cf0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/749426673c8f3468dce248cffb23ec0a16659be9/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/6bf36c7e997e7f86d93d3e81932ee7d3c4d6c2e6/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/d4725e77e07d0a1c60ff3c5a78e4586f6f359ae3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/88889342b14f45e5195c7b3b538b23bf71d16aed/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/22f921159e19d1d417a0087e2587723446e54551/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/c369d2a49dcccbf3483b21e59a53c4eb72d72bc0/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/efee8d3682f22bf267bd44ab99b983d5f6a017c4/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/cd3e0a66a177b796eae203fbe38fb552b658660a/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/49aa9a6a4e5fdbba3d75731e2f02d23ec83902d0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/3daaeaa137467e3542f46d60979decb2aabd6042/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/d963ba98b4a52f8ebbd1dcb2631425674d98a5ad/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/5af971a12c257dbc15de3c0c7dc5a6f529a327b5/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/4b71f1c3b48a50269be3bb7510a8b13c9b1d3ee4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/46255c035df9d94d08b319c01ed9105328b2200a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/d365cb9ec915905f7c0e6819019a587003dfba55/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/2710bab143696f6fd729122bd00621f6324ae92b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/8fd6f1c5fc5584e2057abef183042daa445a8d20/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/cf85f058aad2a6e521313f6dddfc5774bad9c2cc/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/4f7b1e39f05096dcab6320fe971c86f6fd69a4ae/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/8b1ae9c7636008e0bab53009c2a09b7d595f5b62/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/540d891d5530f2c860ccd6fc72a5fed4e133f786/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/517696d1b0d69824c12b2b4bb8dd850448681ca4/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/3af190fcb91ac7afbb10a4755ca031f4f3a0ec91/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/eccb131d089869767c9f3a4dd6a7757fa2829a21/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/17f5d5b93a4a10cae4271a6ea07682a7b72d28d4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/a333415d861ee6bb893c14dd57d55e21353c0476/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2da743c200d6ad0b6a23cddc93e3cd06/raw/9abbe6083366a0a0ca8c703d241ae2569366111d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
@tonycurtis ?

**Comment by tonycurtis** [comment]
+1

**Pull request merged**
