### PR TITLE
CONTRIB/PR_MERGE: Support dismissed review

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Pushing (or force-pushing) commits would change the state of reviews from APPROVED to DISMISSED

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe what this will do to squashed commits ?

**Comment by yosefe** [comment]
the original goal of the script was to validate squash+force push after approval did not introduce any changes; this PR also considers that force-push (including squash) would dismiss existing approved reviews.

**Comment by shamisp** [comment]
Is it possible to avoid invalidation of approved reviews if `git diff` of
the squashed request didn't change compared to previous diff ?

**Comment by yosefe** [comment]
> Is it possible to avoid invalidation of approved reviews if `git diff` of the squashed request didn't change compared to previous diff ?

Not that i know of.. otherwise would not need this script..

**Comment by yosefe** [comment]
@shamisp is this ok to merge?

**Pull request merged**
