### PR TITLE
UCP/WIREUP: Avoid overriding real transport endpoint.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1928/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1932/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1304/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1933/ for details.

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
Looks ok but for some reason breaks at ORNL. @MattBBaker  ?

**Comment by MattBBaker** [comment]
Failure unrelated.
Not enough memory in /dev/shm. Which is odd, because that directory is clean.

**Comment by yosefe** [comment]
@MattBBaker maybe running processes are still holding open files there, you can check using `lsof`
@shamisp can we merge?

**Comment by shamisp** [comment]
@yosefe sure

**Pull request merged**
