### PR TITLE
JENKINS: Add write permissions before removing old files

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 25 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/c57487e68f63d1519631f5cc0fa63e75fd55ece6/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/5a6cbfb0bc84b09e6ee90d29749890573343e29e/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/00dd3f246ca80c24cf2ad24ab0412dc1010360cd/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/80effd231b574bbe6ae548c6b8064c380362413d/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/6b893e825cf07b714095efa3ef9c86a28b1235d3/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/e441d2b272b20cd9568e6e165bb65251c9ce9a8b/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/e70aadc801e1d9430d723615cf6c9be7f84c7236/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/be2a289b4e3d536655ae7a5d934850e6d4bf7630/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/bf9b532b1cbd8ffe1cfc1806322966e77395ff02/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/be84262d746ad4e0a8a5941c49f0c1a8613ad865/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/934b09becf0feb3e7b5bcfe0f7904fb10bfa4abd/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/a32567a989b800ba8763cab7161b07205ff7e76c/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/6521175125bdef1d1d6f0b49e1646d65350e3202/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/3801fa6b6b26bf2d4805d0c01e9990078fe63753/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/0417b4f01f13eb4b72d4eda26457f33eb96e5826/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/04bbba8d3d7564611c9892117681348fbc28c560/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/e238e91570fa26e2e2a7e0c9612a093993f6d312/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/bcd65ae6d877f790761b5747216ca3bce808ec48/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/d4b30c1afcf2d2a4d066b699803386314a1fa06c/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/d09c743f00089bc3d58c72cb186015336dfd88a4/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/b1abeba57eba80f4d6c4d651d225c5ded57f1562/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/7ed906d9e5756047c4277d2e4c9c9fa8f650b315/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/dc0f7fc383f1c462bb4fa8e893f52959f7c59606/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/970d4438720c7ed438a8a377b4ab55c36f5bfd28/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c29c69dc052fc7ab4374b53a27d11d19/raw/08dd32cc3ec806cac9ac3684b4227af7957bf882/r-vmb-ppc-jenkins_W3) | :x: FAILURE

**Comment by yosefe** [comment]
vm failure OOM
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/8f11489d372377350764ed4aecc66c9af78ee9dc/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/1604a0175f6b73dacd429ab319e01fc3aa10c6b1/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/61bb3accb3c0a37cb742fc516b7acb216043a9e7/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/bc056d67e4eb533cc064bcc612bca815e4efb8ec/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/e2043e554fedc11fad77a3f54f0eff2474e46ed2/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/149575e7713e03e99cccd105a4a5fa0594e2f7d1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/bc1a5c18e063cc49f4a0d85d729b03c95f4c8ac8/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/e2af1c2c3bf7d37c6ef7ab852825e966182e6e57/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/db68bee0bdeb75f8f8301d39b9e9e1d223ba19ca/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/a30953d47e83e900bf09c9e52d82c93816bd41ee/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/8bb28dd290bddb37bd60a5693bfe79d74b00e05d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/2942c94ab7f9f7dc76e1d328e10b26bde4b856a6/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/a2c3dc6e89588ed2aeb09d2aa73048c32464dc7d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/a2161545cddd2107a339ee54c0514f2bfe65ef2b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/e8286812aeb9e7364d5b4c8718777d7090eb6760/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/a4f02a94f01621284693a85999ddf143bd76770d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/6eead24fb7a288ceda1e5dad731ecf0f2d969d64/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/832871bcfc69d97729e3b031e2c6a47055e173b4/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/914b303d1c071ac739a805bcedcd923c7629ef05/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/36145c8ca1e9c3ed799a1967445c67572add3482/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/22c7b8c1f224d3c250b979a70f939a50ce34dfc1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/0d02f4e067f0d0493479bb665f7fa07e449dfe5b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/c993341a628b3fcda5479c461cb38cf258e43323/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/03f9a89e121e8bca2a4cff1af3d2432b3e19980b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/95aeb25fcb937c218f4b5b41de00ef7f/raw/6bf0069e35220671cdc3857ee557b4d786f45511/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@amaslenn can you pls take a look?

**Comment by yosefe** [comment]
> If a user doesn't have permission to delete the folder, changing permissions won't work too.

The problem was that swx-jenkins wah the ownel, but some files in the folder (part of make dist step in autotolles) were created w/o write permissions

**Pull request merged**
