### PR TITLE
SPEC: Remove ucx-static package since it's unusable

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10174/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask @amaslenn @shamisp pls take a look

**Comment by shamisp** [comment]
@yosefe do we have plans to fix this ?

**Comment by yosefe** [comment]
@shamisp it's on TODO list, but no specific plan/schedule for now

**Pull request merged**
