### PR TITLE
TEST/UD: Fix test_ud.ca_md.

### LINKED ISSUE #1451: hang in ud_mlx5/test_ud.ca_md/1
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3396/label=hpc-test-node2,worker=2/console
```
17:00:12 [ RUN      ] ud_mlx5/test_ud.ca_md/1
18:37:22 Build timed out (after 120 minutes). Marking the build as failed.
18:37:22 Build was aborted
18:37:22 TAP Reports Processing: START
18:37:22 Looking for TAP results report in workspace using pattern: **/*.tap
18:37:23 
make: *** [test] Terminated
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1451

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1649/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3567/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1652/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3570/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@MattBBaker can you pls post ORNL failure?

**Comment by MattBBaker** [comment]
compairson between signed and unsigned ints in gtest.
```
  CXX    uct/gtest-test_ud_pending.o
cc1plus: warnings being treated as errors
In file included from /var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/common/test_helpers.h:11,
                 from /var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/common/test.h:10,
                 from /var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/uct/uct_test.h:16,
                 from /var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/uct/test_ud.cc:7:
/var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/common/gtest.h: In function ‘testing::AssertionResult testing::internal::CmpHelperLE(const char*, const char*, const T1&, const T2&) [with T1 = int, T2 = unsigned int]’:
/var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/uct/test_ud.cc:556:   instantiated from here
/var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/common/gtest.h:18993: error: comparison between signed and unsigned integer expressions
make[2]: *** [uct/gtest-test_ud.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1653/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3571/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1662/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3578/ for details (Mellanox internal link).

**Pull request merged**
