### PR TITLE
UCM/RELOC: fix modifying GOT mechanism v1.4.x

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
Cherry-picked from https://github.com/openucx/ucx/pull/2828

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7680/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Why do we have this failure ?

**Comment by evgeny-leksikov** [comment]
Really strange, should not be related
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7688/ for details (Mellanox internal link).

**Pull request merged**
