### PR TITLE
UGNI/API: ugni code base restructuring

### PR DESCRIPTION
**Pull request by shamisp**
* Increasing the limit for TL name to fit ugni_rdma
* Restructuring the common code between ugni/base and ugni/rdma

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe @hppritcha - please review

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/909/ for details.

**Comment by shamisp** [comment]
Adding @MattBBaker, please take a look

**Comment by MattBBaker** [comment]
+1

**Comment by hppritcha** [comment]
looks good, built for me on edison

**Comment by yosefe** [comment]
@shamisp This is changing UCT API (length of TL name)

**Comment by shamisp** [comment]
@yosefe - correct. "ugni_rdma' doesn't fit into array of 8. Any issue with this ?

**Pull request merged**
