### PR TITLE
KNEM: Addressing memory leak in KNEM

### PR DESCRIPTION
**Pull request by shamisp**
See CID 128531

Signed-off-by: Pavel Shamis (Pasha) <shamisp@ornl.gov>

### CODE REVIEW

**Comment by shamisp** [comment]
fixes https://scan8.coverity.com/reports.htm#v27369/p11529/fileInstanceId=7761146&defectInstanceId=2763446&mergedDefectId=128531

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/811/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/238/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
