### PR TITLE
UCT/API: Add direct call for interface progress.

### PR DESCRIPTION
**Pull request by yosefe**
Allows progressing specific UCT interface from the context of slow-path callback function.
Needed in order to implement dynamic progress in UCP: A slow-path callback function is required to process interface event (interrupt) and determine if that interface has actually received an active message and it should be added to the progress list.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4029/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @bbenton pls take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4059/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4071/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4077/ for details (Mellanox internal link).

**Comment by bbenton** [comment]
:+1:

**Pull request merged**
