### PR TITLE
UCP/RNDV-GET: fixed processing of message size, backport for v1.3

### PR DESCRIPTION
**Pull request by hoopoepg**
- added evaluation for min zcopy value

this is backport from https://github.com/openucx/ucx/pull/2278

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6193/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
@hoopoepg can you please add unit test which shows this bug with 100% probability (unlike the random test today)?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6194/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe yes, will try

**Comment by hoopoepg** [comment]
bot:mlx:reetest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6198/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6204/ for details (Mellanox internal link).

**Pull request merged**
