### PR TITLE
JUCX: [minor] add fabric methods.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Add fabric methods to create worker, endpoint, listener.

## Why ?
To make API less verbose and sync with [python api](https://github.com/Akshay-Venkatesh/ucx-py/blob/devel/doc/code-organization.md)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10099/ for details (Mellanox internal link).

**Comment by petro-rudenko** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10100/ for details (Mellanox internal link).

**Comment by petro-rudenko** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10113/ for details (Mellanox internal link).

**Pull request merged**
