### PR TITLE
UCP: Split eager protocol to send and receive.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp this only moves code around, without changes.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1504/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/893/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
