### PR TITLE
CONFIG: Huawei Hi1620 CPU detection

### PR DESCRIPTION
**Pull request by alex--m**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10270/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10755/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/7ed72ef21eac9bf77e86c7c338c8a18f23175b27/_main) | :x: FAILURE
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/6169a04d2a08ceff27690a15c196d187c9b47b95/vulcan-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/21b8f4ba129f2ed9e0ebfedea8baa380f8715c94/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/e5de37efd09e6221586ba22897bc5e9d036a03e6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/64c0f8f8e1c152b6aa674de4963e16f4cdf2954a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/239561fb28322474d1e9387693842536ac947daa/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/b4a6be65cbc03edeb66371af2029f74872e7368b/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/09c71e507c6bf4aeaf13b7900172344f44512b1d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/d6fdffeb28268ab5e23945c7f937982261c62f2d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/4e3e2be86772c76a2a332c70be8ffc4f4b4eed71/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/ceaadd2a96c9c7ee5a8e93f528c4142f0ff43e55/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/ec8861c9f2f9f928274197b49d42e91c246dfe6f/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/0ca7e025659c51b214da930db37e98a88b4963a3/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/be588c16e984e93c422ddb319549ac0c9ff92267/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/fb0b6814140412a1d0266209d91c308cf3d96e43/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/8b9ffd48521721e989fe742f891b612ced22bd26/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/b25a29cdce6616b0fd2625973c50c9015a02743b/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/38b25652fc90091eaee19982ca0402471211be55/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/91c5cc97e723d64bbacc36840068f30e9cf4ae07/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/8320d26af1553b11915af41911adfc252c39149a/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/0c0aa4a47c8a8903e26f04d9e055095064416826/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/c5156e707552507edc011b5d461f2bfc350bac3d/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/3094d249afa99e9bd18db08b65c0c0b6ead20b4f/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/5f64053b361fb2c7524e334d404e180914ae6b53/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/6a57d22a0b56f4bd0b6df4712e79c369f6aff799/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/15ead2205b04c622b5573ad55c04f1128553cf1f/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/8131f7ea6e9c27230ad17c798875047c1d43f664/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/d345672357b7fce9204bfa8b2c8e1a6c65ba0942/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/bc46045a3289f801273472dead925d38a19e6a6c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/e97c366b1ad140791dd389ebeb65ddb132418afa/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/ff4b496d29006f18abffce3b7b4717bedb2e8786/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/9b190513205f34a7c99bb48494c094867647360c/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d55ed71d94eafd7d6ae6cac0d2c0470c/raw/2a1acfd7a925f28636a9d3b8b0976aec39b44eca/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by alex--m** [comment]
For future reference, the build failure is actually a timeout - build/test process is too long:
```
+ucp_contig_contig_cuda_mng_tag_lat/6000-----+----------+----------+-----------+-----------+
            38     0.000 13341.857 13341.857       0.43       0.43          75          75
            75     0.000 13702.973 13520.007       0.42       0.42          73          74
           111     0.000 13902.512 13644.063       0.41       0.42          72          73
           148     0.000 13527.013 13614.800       0.42       0.42          74          73
           186     0.000 13171.067 13524.145       0.43       0.42          76          74
           223     0.000 13702.702 13553.771       0.42       0.42          73          74
           261     0.000 13342.120 13522.956       0.43       0.42          75          74
           299     0.000 13171.027 13478.229       0.43       0.42          76          74
           336     0.000 13770.284 13510.390       0.42       0.42          73          74
Build timed out (after 190 minutes). Marking the build as failed.
Build was aborted
...
```

**Comment by shamisp** [comment]
bot:bgate:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10912/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/d7ebe21d4bf125ea84224a55a925322ac6489ed4/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/de00e88f9381f322d2ae1704497f4d1a17542d1b/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/a354ec010d4099fa90b50875a06092b7115a6788/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/a6b27a4990c5bf36d6a745b2073b46a2877c2ca4/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/e96a7ead1a85c61b26b49dc312a3886cb951d093/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/f2c1aa1c3ae6ea8516aeb1da27b5e0ccbf8c39a4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/9609e5cb4c56a74170f0dc0fa31e7c65927aaf7b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/a64b85155873aff0ec17cd246d42360fda559d24/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/35d366b389839fe1fc820689b84477d7967adda0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/4c93ec11a5f3cdeb3d52423341ad7e811eaf4f17/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/80ad3ffa1c2de091692d5eff204a44fe7db71592/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/4d9d1a18153e4936871e6af2e91b41ba34051485/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/7a8279abd029d0c9f1b26be261657d50d467d314/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/54dbc53bdc463c5ff0bab6aa0f3c4eeb900c8b61/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/c2309d1ba4eed748eed36931023192ed06eb4042/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/5cdec9f96e84ae104af710743634999337e2ad8e/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/b5a31bf8a8f063e29270937876ba452bdfd01f7b/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/f6720d77945933237d8c44bc6bd40957db14bdf5/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/9a75fc1a63227d086e646320257d9c3db05f52da/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/5ab78cdf778de21f089ece0d6816175c8374ed3c/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/c37643fdaa7484164ea4e12eb068e08bd719fb2a/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/96ff6ab4059421d915aa76e5377f8b67e043e78d/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/2e0c554b99fb6c171a953e9314bb93ea98f563fb/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/fbd456dc4aed5c2d1daeea7732ca0ab1a57f67ed/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/f5f4504414abfbfe7948deb6da2a286e592a2cee/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/18583b2afe8b890cbf3c80aede045fea5507cd3e/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/5032fe8fb69ab470a346c03a5aeb16b16428cc1e/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/27ca58e704d4255a7c0f2ac216dd4e5c95d25823/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/e1240bbfc62f071998fd3a6638fef1fa5027a045/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/8c539fa309bdc0b379cea4baab52210f66310c68/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/2f55b1f249e0c96f7bc1017e009f3d7687fd2f21/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/1196191d19a5525b990454ef3950eb45ca2bb636/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/84f3871d87b62c7e79778d72000a65ae3de9b920/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/e2abce12d9af335a19e2a6ea220bd590dca5e56e/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/f48dfe90427d08a9f8c99ab6e1f34d4a3ebfed72/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/e7570f1554dea5d5e5c900cf8a461d5478685e4d/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1937b1a18774ef9be199991680df8db/raw/e7d5fb49c245ee3f6f2b4cd347a1911effa1b022/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
ok to test

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10922/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/8bc165394ec1895b227a59a05c29c54b06d19061/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/a806a34b47bacd4ffd096dc86830ea6438300b15/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/d119223a4935341ab7c9ec70fa4b54daba15cb46/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/215ad065500c6de9951bf0dd364c5a2dbe55d15e/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/e747d42d840d16014ae156466e7f0ad8c055d956/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/935b1b629d8ac3e9bf9805866f85f7e6b9676a38/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/ffaf4dbe0b4bad8ca4c6fa67e57ed40cddba6f83/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/759301defcf5788ac93d8290108db19f019a0bc5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/7b936e2b6abc01fb036fcf6469083d0aa6eb653f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/6c0613e3c0c6eae416b6415e7c84e220702094d4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/ae4bb72664ee76e1dec61a5be2d77c4f78338f9a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/7aae1c02b223f53a80369eae96f681496257ef0e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/2795c797ac78f8842291e8a5ee149aab4273c942/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/3e412b54b13b4e32acf47dbae4bbe24739ecabca/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/dcb29b9c1781c25b84f49b6f612ff458d0a0e948/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/d0a8b7c89d166bc79a8d59518dec5b0a9f6d10ca/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/1029c6d0a83c685115987dae227cf1e6379d18aa/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/fc97e9577de6c57efc3b6796014a0b36cc1ab538/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/5fefba51ad8ad1115bf5398010fc6105809dd401/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/af4847162105381a21ffd321d5965730769d4c5f/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/6e959dc256b6011727185a9c11011c3bda5eaeb5/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/918d0d7e3f23a66e113292fed16351cea4f9376e/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/d001bec73eca8b78795d0eaac786f08e888b014a/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/8bfc4ff2ab676c4fe21786b0991dfe40ca6445d5/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/d6d08232dae921fd789cc6c7328ff698f5996f1c/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/7e810b7bb21ea7974f6acf488331c8d8dd6de21e/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/83862ecc8f035ff58796ef0c97f55e7f77f9372b/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/d2ca2b844c7c04c46f4e8dc663b526c58ea35de1/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/06b816b684ab44b83645d8c278dd47c439f706cd/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/2cdef1486cd920c5aed743f0610a28930f607a23/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/dafa225fcf21cdb9799da6a3f0ef32ba8449f25e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/b3c72c4509c389f7f3b03520b138952c30c712a8/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/5a6d583c69246fedaf46fea0b7379f9c0991aedb/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/306d8880a8816720ea5cfaf824ea399c9bd623b8/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/5e3349264da0711bd875b54c2d0b3734e69d2d01/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/fa1f8f19f1b01dac4a07da2f48f630b7b46981b7/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/df2382fd9dd387425a4d5f4055f7c35f/raw/8a7baf54ee4c82324fba81d7ac2d3ab1f2c0060e/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
