### PR TITLE
GTEST/UCS: Enable sockaddr testing with an IPv6 address - v1.7.x

### PR DESCRIPTION
**Pull request by alinask**
## What
Enable gtest to test IPv6 interfaces with the sockaddr testing.

## Why ?
To test IPv6 interfaces as well.

## How ?
Porting of https://github.com/openucx/ucx/pull/4326

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 19-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/80a658e2e916806bcf486b44a208883408fd7408/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/a8336b2a25c17402cfbbdab1499d119b1699811c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/6ed9874a29324de29f9a90515a9ae0e4cc1359ee/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/0858824f72344f301bdf862e942c1fb35cf17418/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/64647299ba4c7f7b5bd93d0be534245d3eb2bf51/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/313b05109033cf61f77e8d61f9a370ba79a9e3e1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/9fe85f75101136bb2a862881edbcd3e8c8d29b21/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/3bd8e03fa4913737dfc1019ab20cbb5065c8f937/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/653daf0eddc9ae8e5c1fd573a4b37d2125d375a0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/2a6bfe4c9e610b79cd84784628ead57dee516d19/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/50c60d7e724964f26e7215799a284b99585dc487/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/09e4b5e705909dc7245374f18ba630d563d32b29/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/0c62b870cec3c66bb9f6bb464a40a5e3e65bc003/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/d0a57cb10a5c6d03f1503d9516a6d3e699a50147/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/e0e63141ec4b16c8a72e7b239171cf82b95ff2f5/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/15a64bab26c36f7a9cab2a12dc5d31849029e71c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/8e217ddcf53372b0233bf0a2fb3da6bc6cc7a7ed/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/2084d3e19e4a54077ade91d691febc08d9b6aaee/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/b5875e6277deeec9567eac7ca50d007819491803/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/9cedca2fbea8b291f41a27d0ad71a35583ef4396/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/6f3ca78e9fa111f133efd39ae4c832e64d812ec5/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/667fc595c9418801d213ea0df330eb96e8f8b55b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/bf8af66cc64c18d903139c5cdee1d99f76e3ae5b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/bec790518f7d07e220ef56614006c87063a8a01d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/30ed85fe77ab76ccc81c6d39e0ca23f2/raw/34ca25b8564acc6f488915656dd2c018434888a9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
```
[2019-11-13T07:37:51.254Z] [ RUN      ] shm/test_ucp_sockaddr.err_handle/0
[2019-11-13T07:37:51.254Z] [     INFO ] < failed to connect to fe80::f652:14ff:fe01:b892:256 >
[2019-11-13T07:38:01.197Z] /scrap/jenkins/workspace/ucx-2/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:513: Failure
[2019-11-13T07:38:01.197Z] Value of: m_err_handler_count
[2019-11-13T07:38:01.197Z]   Actual: 0
[2019-11-13T07:38:01.197Z] Expected: 1
```

**Comment by alinask** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/497dd61535d720f240e4347d24568f120a2010c3/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/5f3886f014cb09fbdb109b4326dcf068e134b93f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/a2c99ac2d6cf22e2a00cdea997418d5241b4aab1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/e37c70e9d5145b4895da7458f924b1bf14ac62eb/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/74012132eb8c70b544369ce1d1c277d99f6abdcf/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/d91944967fb2ab1442910235deb82ce4611a1ea9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/55a22dd29b38b5bead64d20e00a0c74a1c3118f0/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/7c13efbeca51916f9df9e8cf5b144f1b96cc537c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/f1222d23243c6f7710e6f2333fbf6b94db15d25a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/7055943ab1a4c1790aa9aeccf075f0d4b1de96af/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/9d914aafd16416b1174228fea20ad6cde60cdf3b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/c87c7f2831b428348c3cacd53b10b8e27883783c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/9ca1f85a8b927e6af0dc68894aed2061573640be/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/08f53a2a0be062e4a736bb8d09c81fe0fd11fcc1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/7f6de769299a5af90617e540f9b36f2394b0c1a8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/cb951e49e1ffa782867bf730abd235830974b14f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/3a56f1403f651a9c704cc9e0330f70e62f556a10/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/83b63fa4391d03498931bf129e4b455c403a3272/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/14892fa08da1bafc8519b1a2ae7540d697658dd7/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/25b89ec57ef97e470fadf0ac06d0f83d90c29c8d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/75571cf091b257608db22f2fceabfd008a3b0e77/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/d80e8685e74f60538a13fd1937f831f35b7e37af/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/c3064ab54c91c6ea77acd6e32eecd30a3bc08fbe/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/94d86f1d59c22a3e396fc9cd2f0162a60d24167e/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26b855e55168d6c148e64bfab288896c/raw/afc30542ba0b6f98905d02febca570b45d51e283/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
