### PR TITLE
UCS/INFO: Print cache size in ucx_info.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/811/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1423/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1424/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/812/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1426/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by MattBBaker** [comment]
autobot build

**Comment by MattBBaker** [comment]
This looks like a system issue with buildbot rather than anything wrong with this pr.

**Comment by shamisp** [comment]
If one bright day we will decide to support other than linux systems (like bsd), this is going to be portability nightmare

**Comment by yosefe** [comment]
hm. maybe use hwloc?

**Comment by shamisp** [comment]
If you can extract the same info using hwloc (I think you can), I would prefer to use hwloc.
BTW, hwloc supports "embedding" into the library, so you don't have to depend on 3rd party installation.

**Comment by miked-mellanox** [comment]
IMO - for now we can open a ticket for hwloc or alike tools for the future releases.

**Comment by shamisp** [comment]
We can, but my concern that we are getting deeper-and-deeper into Linux specific features. We should stop and look back. It might be much easier to use hwloc instead of developing the same features from scratch

**Comment by miked-mellanox** [comment]
yep, but currently the resource discovery is very minor feature in the non-critical flow (print some node stat). I would not invest time into hwloc just for that, but after we have bigger use-case of non-linux use-case/end-user.

**Comment by shamisp** [comment]
But he already implement ~ 200 lines of code, probably instead of few lines of hwloc code...

**Comment by yosefe** [comment]
@shamisp @miked-mellanox i am splitting this PR to memcpy bandwidth and cache sizes. Assuming there is no controversy about the first part, we can explore using hwloc for the second part. Also, I think we will need to use hwloc at some point for other things as well.

**Comment by shamisp** [comment]
@yosefe :+1: on the split.

Anyways we use affinity in a few places, so we need this library

**Pull request closed without merging**
