### PR TITLE
Test fixes and enhancements

### PR DESCRIPTION
**Pull request by shamisp**
HAVE_MPI checks just for the mpirun and not mpicc.
While typically distro provides both binaries, typically
these are distributed with two different packages.

In this case we have to use already existing MPICC

Signed-off-by: Pavel Shamis (Pasha) pasharesearch@gmail.com

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2715/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/123/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2075/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2719/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/127/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2080/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2721/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2081/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/128/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2722/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2082/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/129/ for details.

**Comment by shamisp** [comment]
Yeah. Apparently I missed it somewhere .

**Comment by shamisp** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/138/ for details.

**Comment by shamisp** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2742/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2122/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/151/ for details.

**Comment by shamisp** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2750/ for details.

**Comment by shamisp** [comment]
@yosefe - something is not right on mellanox machine.
It finds MPICC but whatever mpicc is there it cant build MPI.

thanks 
```
22:14:27 make[1]: Entering directory `/scrap/jenkins/jobs/gh-ucx-pr/workspace/build-test/test/mpi'
22:14:27   CC       test_memhooks_lib.lo
22:14:27   CC       test_memhooks.o
22:14:27   CC       shmem_pingpong.o
22:14:27 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/mpi/test_memhooks.c:7:17: fatal error: mpi.h: No such file or directory
22:14:27  #include <mpi.h>
22:14:27                  ^
22:14:27 compilation terminated.
22:14:27 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/mpi/shmem_pingpong.c:12:19: fatal error: shmem.h: No such file or directory
22:14:27  #include <shmem.h>
22:14:27                    ^
22:14:27 compilation terminated.
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2136/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/166/ for details.

**Comment by miked-mellanox** [comment]
seems CC != mpicc in the make command line

**Comment by shamisp** [comment]
it uses MPICC, while MPICC is defined as

  AC_PATH_PROGS(MPICC,mpicc mpiicc,"",$mpi_path)


I will enabled make verbose mode.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2755/ for details.

**Comment by miked-mellanox** [comment]
yep, it was gcc and not mpicc

**Comment by shamisp** [comment]
automake generates some weird compilation commands even for empty files..

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2757/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2141/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2758/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/171/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2143/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/173/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2145/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/174/ for details.

**Comment by shamisp** [comment]
@yosefe - thanks. missed this one.

**Comment by yosefe** [comment]
@shamisp i have suggestion for better fix - define HAVE_MPI in config.h based on MPICC instead of MPIRUN, to avoid changes in perftest.c

**Comment by shamisp** [comment]
I was thinking about the same. MPIRUN is actually used only in one place.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/177/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2148/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2761/ for details.

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2762/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/178/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2149/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2763/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/179/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2150/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/181/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2766/ for details.

**Comment by shamisp** [comment]
@yosefe the rename confused hell out of me :)

**Comment by yosefe** [comment]
@shamisp sorry - i used this PR to add few more fixes to solve all those random failures in tests

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2153/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp can we merge?

**Comment by shamisp** [comment]
Yeah - thanks for help

**Pull request merged**
