### PR TITLE
 GTEST/UCT/RC: desc release tests for MP XRQ

### PR DESCRIPTION
**Pull request by brminich**
## What
- More tests for MP XRQ
- Some minor fixes

## Why ?
Release of UCT descriptor involves quite complicated flow in UCT, need to properly test it

### CODE REVIEW

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12553/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@dmitrygx, @hoopoepg, can you please review?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12556/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/c5779f4a4233c4d02937b66f8e1b60caf59c07e0/_main) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/8de161d2ff6f314ed52bff0467415ef1cf0d1375/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/ebb416b6f1e9a0beb2ba24cb54bc3f991a4f3074/hpc-test-node-legacy_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/37236639490cb1761d469dc4e9ae0d8fe713a45d/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/4c3a6410075b74acaca38e3ab5f62aa9bfb37e9b/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/37501b6c9d5491283089f665d55d8e62384c53cd/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/db80d1062f717b41918df6f952fc049cb5f65279/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/5681ed46b838578016d40c200693aeccb43be18f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/efd5e893a7d6a189345379c3e8027b5f8f30a149/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/7f19511c5a38e06d337a033a5083185a40181086/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/72a715e6f294a15eabef004c09685edc7c2c2775/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/2b5c50ca43018ddbbdd20a9b759ab2ca14b1aa1a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/8d34c82d7146e8ae23c4ad006ae9a0d4a2f47ae5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/7d58cbf380235a22346aaffa65d1520cadc2d00b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/d544236636e1afbc25fbcc34b75db562a6a487c1/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/030fc6595d551411429b3e9f26fc8fde37700163/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/68103851530e928f754fe8113d599ef26efc63df/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/ef9c0e355f576ceafcdd163882ab1edfde1782c5/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/79e3dc4319b680be24ffbdeeab3bc2eca1b7a8e4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/b5b4cedd6fa042e771b87072beb0bfbb831cc5d6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/5e4afa340a93ec6c1735a97d608ac9221f0529d6/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/4f4f9aa05af3e2d71f2d365ea5871350621b36ba/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/2977ea63bd4b4a9233f19519207c9a4e0e822fe8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/040e8a0203ada0156f3b2a7b62e0736a9081f6d5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/f95e0d5e3e86a534df83563cb1ea97e8009c036a/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/5aa8ddcf82962d2bc55a308fa3d92398827a4f4d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/f77443a4347e7276a90eba5ab2d8bc6352380761/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/13d3b8679c7885acc22b87ad405d0af5187f4d1f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9366ccd020c26a4a78d0208a112ae4a7/raw/200dbd22cafb8b00942f3f6e9b3e0389791a39f4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS

**Pull request merged**
