### PR TITLE
UCP/SM: Make knem work with Rendezvous.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
Related to https://github.com/openucx/ucx/issues/493

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/571/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3030/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2514/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Do we have the same pending issue in CMA and XPMEM ?

**Comment by alinask** [comment]
With CMA, yes, because it doesn't have the pending flag. XPMEM uses mm's iface attributes which have pending but dont have get_zcopy, which is a requirement for rndv.

**Comment by shamisp** [comment]
In this case, can you please fix CMA as well ? It is much more pervasive than KNEM and the fix should look identical.

XPMEM - XPMEM conceptually supports zcopy. So, this is something that got overlooked. Can you please open a bug.

Is there any particular reason why we only have get rndv and and not put ?

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3048/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2531/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
valgrind showed leak:
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3048/valgrindResult/pid=31714,0x4/

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2537/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@shamisp I opened the bug you requested - https://github.com/openucx/ucx/issues/1213 .
We will add 'put' later on.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3052/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/604/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2548/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe please review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3059/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/612/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3060/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3063/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2564/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2565/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@shamisp Can you please review?

**Comment by shamisp** [comment]
@alinask Can you please the same issue for CMA ?

**Comment by alinask** [comment]
@shamisp sure. i'll do it in a separate PR.

**Comment by shamisp** [comment]
No problem. 👍

**Pull request merged**
