### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by hppritcha**
@shamisp 

add LANL attribution to license file

Signed-off-by: Howard Pritchard <howardp@lanl.gov

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1615/ for details.

**Comment by shamisp** [comment]
The failure is unrelated.

**Pull request merged**
