### PR TITLE
UCT/BASE: Add return status to uct_worker_tl_data_get()

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg pls take a look

**Comment by hoopoepg** [comment]
failed due to https://github.com/openucx/ucx/issues/1963

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6513/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by hoopoepg** [comment]
@yosefe ok to commit?
I will cherry-pick this commit into https://github.com/openucx/ucx/pull/2378

**Pull request merged**
