### PR TITLE
Port recent bugfixes to v1.6.x and update NEWS to v1.6-rc4

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10809/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/2d29e700433269a48cf2d252d6d8ea4475d75b5c/_main) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/c27deab8bb137143d7521d506f1dc72885a1efb9/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/8a44648543e59889b5bbf27a8c07799d638bbe59/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/e47df4bf54ba59b27d5ad3ce5217853fe4379096/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/bcc62a1977e8d0ccae587e41b5cc544f4a3a3710/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/3e18d7ce459a634f3c90fc416c708bbe1561a1c4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/727829ce8b7b228cd80516eb95ed26e019e06741/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/a4cc7c3b693ec17a4d2c0eaf2fbb663e00d5e1c8/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/fc50b9a4d4c304b265c67275fa25ad6d329e319c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/00a072375d8d4a87084e91002f6932ec200f7b79/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/63de0586d6f3066655316e755ab394af9bf5be56/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/7da98fb2a02ee310d0b06eee2711e8889e5162c6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/db18e3af79cf09de13ad6aa087b0ee5593247e1b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/bab0f6704fbaeaafc80390cedfa231e44890de72/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/1497f1c021c204b24fcb950d14ce7f8d6148f0a7/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/2e622b144763d83b8ea0b21a097dd26ddfa903bd/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/cdfa863e48aff1ddc573ad1d623e5b74a8f6a386/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/4883d2f65b7104655c21f304cfd930d327b73ca3/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/6514367416c598901a1217d720e80c9515a1d12a/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/9bd186ae1e09afc7b6aefb8beb0e247a246fd32f/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/dde1187b2b12c030e39dd980718afa5ed4b7fe04/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/8554611e654fefbd8e76805343e00484c6004e22/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/6d830d8a310afffc2abe41efddd69b182d1cb27f/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/5533f37638a2060a3e61554fb55ff0848d247d38/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/06b7423b5b922c68a45db0ea33e6b16b2eb1c3ef/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/1a5268d26a5963fd710df7753508d3bad73c05fa/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/7d9b92300e848182e08e9cd56c2fd85b719249b9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/6aa6651029e825c591ae152fe20092027c5836a6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/a3cca53990c302803d30fbe86f6820d9f6f15bbe/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/e6b0cbf8ce309ab189ebdde4744c6318a8b734dc/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/94e7bf244f619ac7bbf515920a6881771c67d40b/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/cb4ab5a134726bd1a265284edf57978f7a6d1a48/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4079fc424b5eb870c7424915c813d979/raw/bd985a9201b1022e39bdc837035517e343720b8c/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10816/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/8eb9429bc4ebd5b4842cfcd838917e020d7c2571/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/078f6f3059d54dabbf30636e4cd2c3d479e0db02/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/515b678adcc28feb6bd9b563af848f64fd6a040c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/75cbbcb11520e66413442f51022798b5db5ef219/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/64161bfd14588b28b9d8aa7784708778085ae968/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/2aba1a8e32c67b679a1a696b2eac14b3f94c8bb9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/adfad163a0505becbe0ec0fee0b4f7e9331aaaa6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/1a40b190415ac9a30b7d930f575a62de7ca11a61/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/0b589cabc6845c6382b8727be9d565e780648885/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/c3226a0a8bc540876dd37fe0a103f59c499dc89b/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/e6496b026a8d1d9e99065b96d0c00fffbd0bf6ba/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/59bf8944540e4ab73580bdc0936a2d831b42d455/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/76203e6cac116554bf2803a3a54277a18e2524a8/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/c4369cdcc9d0338c5fd480cff9d9bca4c7191770/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/46415da2d394d558e4f71cab4942c167ffe5b740/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/69eac24ad9927346fd017b6bdd33eeda50411d41/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/c7acd80fd326ead87e1ff888492db06ad2e72ece/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/b370e34a24ec0af8b6f3c694d237d53ce67e24f2/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/c1c658de5a7c642cf741981de46567c128e859a3/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/626363bb583cad5e70cba3e3b2a26691bf1e59ec/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/ad51f7ee53dd0ec41eb4c7c0a32d1fa289a19e83/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/fd8fe5523d06c47e4401edff977c833f8ed65987/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/fffff6f6381b06156f80dc6eb0ac29bba68aec89/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/8697fa2e31568a1408afdf2a9f99d0f06d65a7c1/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/8d272a33be64a44f1e1c516b44c19dce8e2b4a30/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/eb4ce18f8d00a182133093d6447169203c4421e7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/074b7ef313d79a8e4051d81ff77f9171b00761d1/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/bb33892ddcc2d44c2148582cef9124dababd350f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/7ef1c6857081526c1798216a840f0e91e0eaeeb8/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/82524eaa42900852f30689ac2fe6bcc24b4cffd8/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/aa23b13f0206dc9c934442e8e53af66d4221e361/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/0879efa58536779c09e726ff90ab3e43641271fe/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc0e784b383c25409b2c7776b52139cd/raw/3c0380a066364017d8dfc6ce3a2ad54231a8ed2c/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@brminich @hoopoepg can you pls take a look?

**Pull request merged**
