### PR TITLE
ROCM: Refine ROCM

### PR DESCRIPTION
**Pull request by yuq**
The original CMA TL used by ROCM is slow for GPU memory to GPU memory (D2D 2~3GB/s), because:
1. need a temp system buffer, so the data path is D->H->D
2. do copy in kernel space, no async support

Now we reference the UCX CUDA TL implementation to have three TL:
1. rocm_ipc: as cuda_ipc for inter process zcopy
2. rocm_cpy: as cuda_cpy for intra process short/zcopy
3. rocm_gdr: as gdr_copy for fast read speed from GPU device memory

ROCM TLs need GPU support LargeBar feature which will export all GPU memory to be accessible by CPU and other devices in the same PCIE root complex.

Currently we need "UCX_RNDV_SCHEME=get_zcopy" to support inter node as described in:
https://github.com/openucx/ucx/issues/3241

### CODE REVIEW

**Comment by yosefe** [comment]
@yuq why is this PR changing many files which are not related to ROCm, such as CUDA for example?

**Comment by yuq** [comment]
@yosefe that's the GDR part, rocm also want to use GDR, so move it to a common place to be shared with rocm.

**Comment by yosefe** [comment]
@yuq is gdrcopy module also used by ROCm? i thought it works only for Cuda devices
In any case, need to split this PR to smaller PRs which are <500 lines to make it possible to review..

**Comment by yuq** [comment]
@yosefe yes, rocm will use GDR copy functions to accelerate GPU memory read, but won't use buffer pin/map functions.

In this PR there're three commits. I can break the second commit to smaller ones, i.e. add one TL per commit. But can't be sure <500 loc because some TL is big. Do you want one commit per PR? I think it's better to make one PR contain related multi commit, you can review commit by commit.

**Comment by yosefe** [comment]
@yuq single PR with multi commit takes long to review when there are many comments that need to fix and many different issues to address, especially with new feature.
let's have something like the following split on PRs:
- UCT api changes (e.g adding memory type)
- UCM changes (rocm hooks?)
- infrastructure changes
- adding new UCT transprot(s) - one PR or more per transport
- tests changes

regarding gdrcopy - currently it's tightly coupled with cuda, since AFAIR from @bureddy we expected to use it with CUDA only. Would be better to discuss this issue in a separate PR.

**Comment by yuq** [comment]
OK, I'll submit multi PRs as your request.

**Comment by yosefe** [comment]
@yuq thanks! need to submit PRs which don't depend on others, and can build and pass tests over when based on master branch.
PRs which are unrelated code could be submitted in parallel (for example, UCM changes and UCT API changes)

**Comment by yuq** [comment]
@yosefe It's a little tricky. Because TL PR depends on UCM and UCT API PR, I can't submit TL PR until UCM and UCT PR gets merged, right? Can I submit all PRs at once (based on current master) and you have to apply in sequence?

**Comment by yosefe** [comment]
@yuq let's submit dependent PRs (e.g UCT) only after their dependencies are merged to master.
This is because review comments on a PR can affect other PR that depend on it, so no point to review them before the previous are merged.

**Comment by yuq** [comment]
@yosefe Hi, I've done commit separation and submit three PRs in parallel (no dependency between them) to accelerate the process. You can find all the commits here if needed:
https://github.com/yuq/ucx/commits/yuq-upstream

**Comment by yosefe** [comment]
@yuq thanks, this looks good. I've sent you invite to ucx developers so Jenkins would run tests.
Can you pls create a Wiki page for users, of how to run MPI+ROCm?

**Comment by yuq** [comment]
@yosefe OK, thanks. I'll create the WIKI page tomorrow.

**Comment by shamisp** [comment]
Do we have CI infrastructure in place to test this ?

**Comment by yuq** [comment]
Hi, I've written a WIKI for the refined ROCM usage:
https://github.com/openucx/ucx/wiki/Build-and-run-ROCM-UCX-OpenMPI-(to-be-upstreamed)

**Comment by miked-mellanox** [comment]
> Hi, I've written a WIKI for the refined ROCM usage:
> https://github.com/openucx/ucx/wiki/Build-and-run-ROCM-UCX-OpenMPI-(to-be-upstreamed)

Thanks @yuq ! can you please add info on the following as well:
* info about rocm_cpy,rocm_gdr,rocm_ipc and when each of items applicable
* tunable parameters for rocm modules
* troubleshoot section (debug level? flags?)
* how to check if it is actually running/activated in a job?
* device selection?
* limitations if any

**Comment by yuq** [comment]
> * info about rocm_cpy,rocm_gdr,rocm_ipc and when each of items applicable
These three TLs have their equivalent in cuda. I just reference your cuda implementation. My knowledge can't allow me to describe in depth, so just in my understanding:
- rocm_ipc: for intra node cross process zcopy, support ROCM/HOST memory
- rocm_cpy: for intra process short and zcopy, support ROCM/HOST memory
- rocm_gdr: for intra process short, support ROCM/HOST memory

> * tunable parameters for rocm modules
no parameters for now.

> * troubleshoot section (debug level? flags?)
> * how to check if it is actually running/activated in a job?
Actually I don't know how except add some printf in the copy function :)

> * device selection?
Must be LargeBar feature enabled AMD card, like MI server card:
https://www.amd.com/en/graphics/servers-radeon-instinct-mi
I'll add a section for this.

> * limitations if any

**Comment by yosefe** [comment]
@yuq can we close this PR, since it's now being replaced by small PRs?

**Comment by yuq** [comment]
@yosefe OK.

**Pull request closed without merging**
