### PR TITLE
BUILD: Add configure flag for SSE 4.2

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1274/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1889/ for details.

**Comment by yosefe** [comment]
@shamisp

**Comment by shamisp** [comment]
👍

**Pull request merged**
