### PR TITLE
UCP/CORE: Back-porting KA fixes to v1.11.x

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Back-porting KA fixes to v1.11.x.

## Why ?

To fix doing KA several times for the same EP.

## How ?

Cherry-picked 3 PRs

### CODE REVIEW

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

**Comment by yosefe** [comment]
> @yosefe could you review pls?

are you sure we need it for v1.11?

**Comment by dmitrygx** [comment]
> are you sure we need it for v1.11?

just to make sure that we are doing KA for each EP only once per round, but actually not sure if it will be a problem for anyone

**Comment by dmitrygx** [comment]
@yosefe ok to close?

**Pull request closed without merging**
