### PR TITLE
UCP/WIREUP: Fix mem type rma_bw lane selection when ucp wakeup feature

### PR DESCRIPTION
**Pull request by bureddy**
requested

## What
skip ucp wakeup feature check for internal mem type endpoint rma bw lane selection

## Why ?
Fixes issue in using mem type pipeline schemes in SparkUCX

### CODE REVIEW

**Comment by bureddy** [comment]
@petro-rudenko can you check with this PR?

**Comment by yosefe** [comment]
@bureddy what if the user does epoll_wait() and not calling progress? could pipeline protocol be stuck?

**Comment by petro-rudenko** [comment]
Seems like working.  Will test more and will let you know if issues will occur

**Comment by bureddy** [comment]
> @bureddy what if the user does epoll_wait() and not calling progress? could pipeline protocol be stuck?

yes. it could stuck.  we added event wakeup in cuda_ipc but not to cuda_copy UCT.  will add it.
@Akshay-Venkatesh Let's add  CUDA event callback scheme to cuda_copy UCT, similar to cuda_ipc UCT.  reuse the code

**Comment by yosefe** [comment]
@bureddy can we close this PR, per #5283?

**Comment by bureddy** [comment]
yes, closing it on behalf of  #5283

**Pull request closed without merging**
