### PR TITLE
Logging style

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp @alex-mikheev @alinask

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1652/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1040/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
:+1: 
Maybe you want to dump styling documentation somewhere on wiki

**Pull request merged**
