### PR TITLE
CONFIGURE: Fixes several places where CFLAGS was being rewritten.

### PR DESCRIPTION
**Pull request by MattBBaker**
Made the autoconf files more robust.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4087/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Looks good to me. @yosefe  ? @boehms ?

**Comment by MattBBaker** [comment]
Should also mention this fixes #1666

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4088/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4098/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
The last test failure in the Mellanox jenkins looks like it was an NFS failure rather than anything UCX related. Are we good?

**Comment by MattBBaker** [comment]
@shamisp This PR has a patch equivilant to #1690. If I chuck it than it will start failing tests. How do we want to handle this?

**Comment by shamisp** [comment]
I would prefer to merge your patch.

**Comment by yosefe** [comment]
bot:bgate:retest

**Pull request merged**
