### PR TITLE
NEWS: RC2 news update

### PR DESCRIPTION
**Pull request by shamisp**
## What
RC preparation.

https://github.com/openucx/ucx/issues/5354

### CODE REVIEW

**Comment by yosefe** [comment]
ok to test

**Comment by brminich** [comment]
`arm-cavium` failure

bot:pipe:retest

**Comment by shamisp** [comment]
@brminich - I cannot access the log of failed machine. Is this something serious or just noise ?

**Comment by brminich** [comment]
@shamisp, seems we a have a problem with one of our arm test machines.
I rebooted it in the morning, but it did not help.

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
