### PR TITLE
Fixes est_num_ppn setting from params

### PR DESCRIPTION
**Pull request by vspetrov**
## What
est_num_ppn fix - don't overwrite the params.est_num_ppn setting in the next step to 1

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12265/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/6eb8b6fa0ba42977de0025ee1933ba7bd4c194ac/_main) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/72398151e26bd5ccf4c1128745d150fcfc6e16e4/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/09832ca859e50080b79adff6d199960107a3890e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/ead2eb8002e3174c23e31c9ffad68921696affc2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/d34fc034a569f33bf46aefc56c2b2f37e32f361d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/87a45ed6424be30f08d819a228d7608bb470ecd3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/33502bd622abd7f3c116f0f26579594826da45b6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/a58456d93b0145eeb473b5899487de47e0e869c2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/30151b89305d402cc581fbc982fcbe946ec44970/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/3089976c5e9ae496c43733e7651faf9aaf11a9d1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/b5d5705a826cdb45c2003be62ee03e1318a75e7d/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/02ba56ad5fa7f7994a3331ff022c9a96f1cf5236/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/c668e7d85ff7706096209d6998939c3de627c0f7/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/2acf06636c4e3b52b4617fd84469b40e093ea300/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/81dc452f52cc801705988d12bdcc9f8f484b9b8e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/5dc868c15a019c7ebb8fc0d14f3787cd2df03b31/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/5d518fd2db9d1e9a8a9636633e05228f0ddfa3f8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/58c566d17da337f782d37f7880346293879554f3/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/64c4abc30ef2c6830dd867fef2a6cf799d2661a3/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/c7ba1716487da523da6111e4567a11e90ad7f699/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/05291b6c0fcc905c0890e7f20367a6ec5ae28b12/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/abfa568e28d02996f77335bd63305a4f2d3932bc/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/2833697ef577cd640df4dae6d8ee1136299aef5e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/c4f55f63f4885ce9bf597272ded04fa87a12ff00/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/63728fb0f476e1aca0751ea76ea3eba1e0c45a88/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/fca0f8974fe5dff57a19ad5f6580389344375c60/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/cf3e605f48be0eb8a304a9d23daa09c98475ae5f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/ffeaab4e9dfbe1574ebb8a3226b2602401ff7cb3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/53cd7cbc43cdb04b482bf31fd2ae048d/raw/0165799f3cdae2c4a09eeee99e389af336b8ab90/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by dmitrygx** [comment]
> Test FAILed.
> See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12265/ for details (Mellanox internal link).

related to #3107

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12269/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/626ecaefec01c6f2ba6c6caa9261ecdcc8bae3f8/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/fea4fc846f86e751bf21625b9ae12276b97392a2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/d8c1d841d6d3d4b09dcf5413e0f0f8a4abb88b32/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/1891d0b2e7390cf22e4461b8805f5f1a0be2e081/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/a0119f6194efd52eef80b05676dbbd7dcfa9fb67/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/16f66446f0d62e551e1442bf1b6625d1489fb41f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/91491aa52cc945f69e162d8010c9996b66b84672/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/21cd5d5d35733243f547cb8cc3846341fcc0607d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/03bc9a1b8b5c218caf67d5a49416231873a2660a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/670d5acae18985d1f137b811913f5cde7188cf6c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/6cb010c00055feeb2a1042a748118d31c9f6554e/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/3613c9a2d36bf3bd990cc13e9438129c2d4a7580/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/6b62e900e14d92180f73ff28bd0adee933a33297/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/5832fb88cdb73461bc9594b349d23a4ac6a7307b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/586722cb57e5ffdfe07d0f60ef00d0e80b11554f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/843959c5ba861f5ebec842a71fb59ca15ba85abb/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/7ca5eceff6c1c815f10f67ddcc46d69db36858c5/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/bb40f5a987bff47b35da9d9cda008dd8c55da82c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/69218deb41173e07fa4c66fe9d0f7c3e0d9ba0d4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/334f9d5d499efef285f1679b7123270464eaa2b3/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/8ada5e25a6840368bbb7c170ab529ede30c357f8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/3ec4f1f4c42333f09d394f839037d7dcfe4fb721/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/236769880c60d5a19ff7d00556005f1caf94edae/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/b3b7cace392e1c36591bd4dcbdbad4c1e51b0ad8/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/2faae4c53a46e9d7799619337ea6a8a0b08a18d1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/2d9fd6383aa019b2592c71a2607c16f0b1f88d1e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/e162f0bf18bc620a27bfdd30fc45d232646b4731/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/f64045347d9f43cf90b43e00184a902a664202cf/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/176ff97aa4f970decfe5e34c0d209de4/raw/c61357c4d1f336e100f6c4a09c78aef2ad37d74b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
