### PR TITLE
BUILD: Bump shared library version - v1.3.x

### PR DESCRIPTION
**Pull request by yosefe**
see https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp @bbenton pls take a look

**Comment by yosefe** [comment]
adding @amaslenn

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6146/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Are we still backward compatible ? did you test it ?

**Comment by yosefe** [comment]
the meaning of this change is we are NOT backward compatible

**Comment by shamisp** [comment]
Well, we agreed that change in 1.X still preserve API (and ABI) backward compatibility. Or we should make it backward compatible, or go to 2.X.

**Comment by yosefe** [comment]
the API change is minor, and ABI should not break. If you think that justifies 2.x, let's do it.

**Comment by shamisp** [comment]
I don't understand. How the ABI backward compatible if the API is not
backward compatible ?
I think 2.x is a not right way forward. I would rather suggest to fix
backward compatibility issues in 1.3.x release if any.

**Comment by yosefe** [comment]
@evgeny-leksikov the compiler is not allowed to use arbitrary padding, it must adhere to the platform ABI which defines the padding. otherwise libraries from different compilers would not have worked.

**Comment by evgeny-leksikov** [comment]
AFAIK default behaviour of compiler is to make alignment by sizeof type. We broke structure to separate fields. Alignment of error handler CB can be different.

**Comment by shamisp** [comment]
Pain. Can we revert it ?

**Comment by evgeny-leksikov** [comment]
it's not easy... stream api uses new field (user data). So, more or less working way to revert it is duplicating of user data pointer in error handler type + new param field.
In addition, I do not think if anyone uses error handling with 1.2.x because it was just introduced and a lot of bugs were fixed in 1.3.x but we don't have any report from outside.

**Comment by shamisp** [comment]
@evgeny-leksikov there are many issues with this. First we break versioning policy that we defined by ourself. Seconds, there are projects out there that we don't know what are they using. 

Duplication is nut such horrible solution.

**Comment by evgeny-leksikov** [comment]
@shamisp @yosefe then may be better go to 2.X?

**Comment by shamisp** [comment]
Not nice either...

**Comment by evgeny-leksikov** [comment]
https://github.com/openucx/ucx/pull/2281 fixes compatibility issue above

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6236/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp updated SO version according to API compatibility

**Comment by shamisp** [comment]
👍

**Pull request merged**
