### PR TITLE
UCT/RC: Check iface types(TM or not)

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@MattBBaker can you pls post ORLN failure?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4133/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4136/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Looks like the latest one is working. Previous failing was,
```
  CC     ib/rc/verbs/libuct_la-rc_verbs_common.lo
cc1: warnings being treated as errors
<https://pod9.ccs.ornl.gov/job/UCX/ws/contrib/../src/uct/ib/rc/verbs/rc_verbs_iface.c>: In function ‘uct_rc_verbs_iface_get_address’:
<https://pod9.ccs.ornl.gov/job/UCX/ws/contrib/../src/uct/ib/rc/verbs/rc_verbs_iface.c>:675: error: unused variable ‘iface’
<https://pod9.ccs.ornl.gov/job/UCX/ws/contrib/../src/uct/ib/rc/verbs/rc_verbs_iface.c>: In function ‘uct_rc_verbs_iface_is_reachable’:
<https://pod9.ccs.ornl.gov/job/UCX/ws/contrib/../src/uct/ib/rc/verbs/rc_verbs_iface.c>:686: error: unused variable ‘iface’
make[2]: *** [ib/rc/verbs/libuct_la-rc_verbs_iface.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4139/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4144/ for details (Mellanox internal link).

**Pull request merged**
