### PR TITLE
UCT/IB: reduce max bcopy to 4k to match ib mtu

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5789/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
looks like it causes `rc/test_ucp_wireup.send_disconnect_onesided/1` to fail

**Comment by alex-mikheev** [comment]
@brminich it seems that tag matching does not like max_bcopy=4k. Any ideas why ? 10x

**Comment by brminich** [comment]
yes, with HW TM max eager thresh is limited by the segment size. So, now it uses RNDV starting from 4K, I guess

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5810/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5813/ for details (Mellanox internal link).

**Comment by alex-mikheev** [comment]
@yosefe not yet I want to check mpi first

**Pull request closed without merging**
