### PR TITLE
cherry-pick ROCm build improvements into 1.4.x

### PR DESCRIPTION
**Pull request by jeffdaily**
## What
Cherry-pick ROCm build improvements from master into 1.4.x.

## Why ?
Requested by @shamisp.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by brminich** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7573/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Not clear why it is X. There is no failures in jenkins

**Pull request merged**
