### PR TITLE
UCS/DEBUG: Update backtrace exclusion filter

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12393/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/5676d84709c0ca2ec474b905b5610c193d399c49/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/3be0f10d51afa5de7003b953a125e876290cc230/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/ca5dd69f943b894b75eb2160d144e90be746534e/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/acc7fedbcf26d0aa58636aa097e9509ec60dae73/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/5e2affde6ef5c4edf338e0d43d87dd9078b1b5ad/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/58a6074cb877bbcd5b6cbcc7dd4559072ecf2318/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/aed83def28a4778de714ad6bcafa638581587665/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/68bc3a04a12bc4d04235d79008e58309e4649d7f/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/b2c424ef4c2c8a74c26647ae6a879e4516dab934/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/87a5eb7292aaf609d721dcd11e024272cd22090b/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/13d955010577efddd717d92fea73141cae3a9ad4/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/9727797e9df457c6f0668e71d9c2d0be48d8bfe2/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/52facb81c920ac0ee578222e8a62db7d1332b978/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/4e210f9680035ea7286b6dcf964d5678b71ecae6/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/d802fe6ef30ab2dc3e27e53a877ef492e2ed385f/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/ef30edf144d2875e7bd040339d733b9d2846e962/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/92fe0c4b102204ee5b69ffbf2546832e38c4c00b/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/f135ea0c85e2f90986af1f2899d51c9caba23fff/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/0f016e3ec126c3ad17209799b9576633418c16e6/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/9e696217238465fea74988491617aedddcb8f269/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/5a9366b4f82bc3c2bbc52ea39390d56d6c6098af/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/0d94676fda37ac1f7c7b426ce68b86e4c6feeb72/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/1c99f65d4adf7eb20ead5b4f164cf7e5363690a7/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/81358698329f63eff39a5a6b5fb1bd53f194dd24/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/50db7d81bb38e7cec0973294eaa0943330e0fea6/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/a91b9cc0d9cd959e697a5b6af527e2e28e565c71/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/882235db66bc07d76d9b3c345670683711245b42/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/370d94819bec9064ad252ae40bb15a5c6a05ad60/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c6db2151ce124f97fd7d16a4b998ceb9/raw/08079541ac5da8b32e34463435c9803b2fd7d3ff/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12394/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/278eaf3642b4059920252beea099a3e22411bd87/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/0be9bd2178fa11a3e13804ba5a77bd244e318228/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/244748a08c37cb334920ab82cb039b5ebff6a661/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/ec1f6375355d402d878e5abe71683bb1fcfe4d00/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/ab5cb7678b1fba300288d2a40da32dc9dc82ffc5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/69794fc6176b2b76a4a16373ae8599060427a5ca/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/ed5bb57aa669acac43c829a09ec50e5da507013d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/31a9b7efd629599456eb75b5945903d4a005f32f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/e071d9056cbc62d9f8d532db998043aec040494c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/1c1c11f758b8dd993a58d728ba812e8f34bd0e6a/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/47804696048873b48b426d4f6c41cd88aeb91dee/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/1b8d784cdc3d0be8250a4fc796329451c4e987fc/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/e4aee12fdc8a1c6867e08ae68b6403aebe5b5325/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/6586a223a292ddfac0ba7cc293dcd1d09c728041/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/5fb9ed55d1a344da37ec71e3da8168825063670f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/c70afe735c793e0999cb6b4a99ca43be6309a816/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/46bcdce0af4b117a774776f3e8604e2c4f7cedad/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/4eae3a486d9d59cf79c5358d8d188eb83457acf1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/5fd2a35096f6425d053f07e8631bc7af5296f345/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/eb852b185b666c87166d0a041b8b4e5e041c6aa8/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/594ad2b179a072ec521377a8965d8a5cb2c45525/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/d619f4e8219d4e10b5d960b51351b51212f4098e/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/6469dbff8804d857bd7b0ae81812b8867991abee/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/33514b655c2e2a167c9d1bb002e27a0da0f764db/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/b031e7bd02d29b424d2aa3486b5e3ad2cb8f73b5/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/08fce247081472f53d82a8c47931e6c486ca8fa4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/52d4e290ca73d34087d0b0fa5ee1d2d918edabec/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/9aa6d3cbd9ac1a1f489b71d1d08b0aa9cddad60c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88fc820af390875475d780d1532073ff/raw/e8e7fd06a0c7db4f0b2b5393f586b8929e876eb2/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@brminich @dmitrygx @hoopoepg can you pls take a look?

**Pull request merged**
