### PR TITLE
UCT/RC/DC: Fix RC and DC config inheritance

### PR DESCRIPTION
**Pull request by brminich**
## What
Align RC/DC config with iface inheritance

### CODE REVIEW

**Comment by brminich** [comment]
arm node failure

bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10965/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/45cd0e26619343e30d5e562d3587d83208c9abc7/_main) | :x: FAILURE
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/c96d7316eb3eb628fc0efddcd742b0b09df2c192/boo31_W0) | :x: FAILURE
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/6867f5522022893538104aa73f6de4d0372b10e2/boo31_W1) | :x: FAILURE
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/b31af993d6207b5d73f1bdee28f14082a20e9e16/boo31_W2) | :x: FAILURE
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/07bba2c7b353c90c6fb657617ff3dea9a2d264cb/boo31_W3) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/fb44d0d9a63baa132366e3c67e60b932753c8f1e/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/9f5c97a29b900757e810e2e5727b0edc70bfa4a7/hpc-test-node3_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/243c2f9856e86658396d5decc7fd2c5b022daff4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/d77fbb9a6c1475242b6a656b9706fb2289c2b375/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/3b498f99a11908965f57b56d4a93d469c2024d44/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/22e1474d97c4f7f102d72e659edfbffd4f5022c5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/46ba2f9de9b48833f0f956459965f7ac88b6e018/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/c42359558f90313dfffeca93bbcb884e37054caa/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/18a19fe5318f4cd13874f49ff448355d30e71a53/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/29904142134a36a8de0adb407a2ee56df5215792/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/ae1d2ee8acecf0b4523b6a3c23b664bcab227bd7/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/12bb604e54b2bdebf4b6975e5af99ed39b107368/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/0d34aeb97e33e71d27293e383707ef3b9ec7d13e/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/984403752c6bacad0e4c505d73badd790f9f87e6/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/44c58da9198622a2cfc06b6b998a49d4bf51ac9f/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/a659fb394f502daafbd05df3f8cca65ed9e9a620/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/cead99858998a9b78ed416af45fdab3d519b9d27/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/09535e409eb8068fa382a4092b67deccaefdf1cc/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/c36e0bb1b889b9af0b6c66b3bd13f2ed1498796f/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/26f347624c07ab186d4ca6e63f83cb347f3e18dd/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/2bf4052f9611fcd4649185d0d9adabd5822fc1e0/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/4e814449ee8fef2c30b9aa0b2a98da51941fa6ae/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/acde22ac1acee2160edd134a311a67e9564e64d5/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/af6b6824764769812148ca0f5d38133f2491b19d/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/91a591c27c1524ace12c5407492923ab92d1fa7c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/c38af5fa6bc608017f058f0dece6b0e1f420080d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/64ed71166f0f2418c840353c601fa7069771126a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/4f59e18d99ba99fd84877abfa19ac3fff889e274/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/c3eb2b53fea64fc0fa9b57616a964a57097dc97d/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/bb7026d842758fd678824c1d7aa9d7805f045fc8/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/ecf950c82d15f7ff96f224496e0fc86cfb599d66/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/39077896405fdbdb03b18f96f5533ed8/raw/89d744c9c23682aadb73f6e3c75c666513858ee5/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
OOM and JTMO

bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10973/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/0601125bbd46d87e07e702db59dc65ea2891dc0b/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/b3a8d1510d62e39df1da4c72f0b009e152699f86/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/5e5033123c2dfdd4c287edbbf8a1ecc563b37fb1/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/3f4ffd42ede405050492689301acb20d9f314c7d/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/091be782ecbd0fc896ba5eb5a0589b0cf3d05a2c/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/958722bd9104e20c2c1f9ae361b78ebac156f5e0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/2e2ddc02649f0e965bb6b4f44b49cafc163f56fa/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/860a55acb240634141ff97c848e28f4a9170663a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/06c8d701db8fa9f849b292daa95b9c83b51b5046/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/1a8e59cd9271e7c1448545715078bd81d6657970/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/daf1112d896f6cce6970223b6dedf6c8705ea307/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/aac2211570a63529fd0f2f44b5410dc3e60653d9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/6037ebe6b9d9f335021a207868f003692995bff4/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/95a0e555f87572eddcdad247b2d492e63e2bfdbd/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/f79a53b53ba1b51f8c2a237699736fe24ba7acd8/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/6fe363f3e5fa60e236d778e66d30e13c4460b258/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/fb045a9166d318c41468087e0f864f08df3d4de1/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/9a6d1c8fbea56fe7c5c6255a4618873e0d6746ed/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/5e7f6b00ebce3d3303889b8d4d85b508379bbcb6/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/466037c3d6e3f965b246760dc5ef3f6c594758c8/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/830132139f3e4a350c0a377afa62fa9b4abb0e45/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/b4d5e83298c2e474a06fea8cbbaeddea4fbde6f6/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/3ecc6c77cde70f678400f220cae4971ffaf3368e/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/9dd7781d0ea24f093b5e1e089c90f4fe0a0b31b3/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/3d8d16574dd82edafb742e112d8d79213605f094/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/778b50750d4e78310b99d00593d193f1915689fc/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/81d528515bfb00e8b7d515e38d15cb0c110162d4/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/846150a64fd420398126246b06d97d1e3c8decd1/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/17a84e7d31311b3fb9e8866a778281ce58250e18/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/484436d14e6d11326e29a1b2065f7fed1e6fe747/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/f503e50f67f4a37bcfd598dcc9892aa6027216b6/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/4217d2e7ac2fdd7599d5ff5ab75e05e6e53ddda5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/3eb8c801c81612b1c9a828ab85a1c1cd5ecd2ca1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/c1fef3273c8d9e74b37ba0178d33077c0e17092b/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/d71e634299872adc9e108271703a8c76e1c372f9/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/fc895ee529d6f66384aa02b966b93afe00d5ba33/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ec9ff37a66da8bf30b1988791fdf8394/raw/bff694eaa3abc57a1d94b87e98a52eb718e169c6/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
@hoopoepg, @dmitrygladkov, can u please review?

**Comment by brminich** [comment]
bot:bgate:retest

**Comment by brminich** [comment]
@yosefe, plz review

**Pull request merged**
