### PR TITLE
UCP/PROTOV2: Add exclude map to ucp_proto_common_init_params_t

### PR DESCRIPTION
**Pull request by brminich**
## What
Add exclude lane map to `ucp_proto_common_init_params_t`, so that `ucp_proto_common_find_lanes` will use it instead of just `0` (which is now passed in most of the places)

## Why ?
Will be used by 2-stage pipeline protocol, it will search for a lane with rkey_ptr capabilities, but not a real rkey_ptr lane (need to exclude it from the search)

ref #8668

### CODE REVIEW

**Comment by yosefe** [comment]
Maybe add it to proto_common params ?

**Review by yosefe — COMMENTED** [review]
pls update commit and PR title

**Comment by brminich** [comment]
> pls update commit and PR title

done

**Comment by brminich** [comment]
> > pls update commit and PR title
> 
> done

also will amend the commit title shortly

**Comment by brminich** [comment]
@yosefe, pls review

**Review by yosefe — APPROVED** [review]

**Pull request merged**
