### PR TITLE
UCT/ROCM/IPC: remove unused CMA code

### PR DESCRIPTION
**Pull request by yuq**
UCX won't pass host memory to rocm_ipc, so remove
the CMA code in IPC which was used to support host
memory.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9399/ for details (Mellanox internal link).

**Comment by yuq** [comment]
Hi, seems there's some log IO issue in the test machine?
```
 0 0x00000000000e985d __write_nocancel()  :0
 1 0x0000000000075fb3 _IO_new_file_write()  :0
 2 0x000000000007674f _IO_new_file_xsputn()  :0
 3 0x000000000004c4cd buffered_vfprintf()  vfprintf.c:0
 4 0x000000000004736e _IO_vfprintf_internal()  :0
 5 0x0000000000526517 testing::internal::ColoredPrintf()  /usr/include/bits/stdio.h:38
 6 0x000000000052c01c testing::internal::PrettyUnitTestResultPrinter::OnTestEnd()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest-all.cc:4281
 7 0x0000000000523415 testing::internal::TestEventRepeater::OnTestEnd()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest-all.cc:4470
 8 0x00000000005387b1 testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest-all.cc:3823
 9 0x000000000053889f testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest-all.cc:3930
10 0x000000000053d237 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest-all.cc:5802
11 0x000000000053d53b testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest-all.cc:5719
12 0x00000000004e5f33 main()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/2/contrib/../test/gtest/common/gtest.h:20059
13 0x0000000000021c05 __libc_start_main()  ???:0
14 0x0000000000522dfe _start()  ???:0
```

**Comment by shamisp** [comment]
bot: retest

**Comment by shamisp** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9466/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9471/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9495/ for details (Mellanox internal link).

**Pull request merged**
