### PR TITLE
UCP: fix api prototype to make gcc happy

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe pls take a look

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1362/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/753/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
:+1:

**Comment by shamisp** [comment]
:+1

**Pull request merged**
