### PR TITLE
UCT/IB/RC: Minor code fix.

### PR DESCRIPTION
**Pull request by rakhmets**
## What
Replaced manual static array size calculation by macro.

### CODE REVIEW

**Review by brminich — APPROVED** [review]

**Review by yosefe — APPROVED** [review]

**Review by dmitrygx — APPROVED** [review]

**Comment by brminich** [comment]
issue is #6225 

bot:pipe:retest

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
@evgeny-leksikov were you looking at the problem like below? It fails 2d time in a row here
```
[2021-01-28T20:22:55.278Z] [ RUN      ] all/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/2 <all/stream>

[2021-01-28T20:22:55.564Z] [     INFO ] Testing 65.65.65.15:0

[2021-01-28T20:22:55.564Z] [     INFO ] server listening on 65.65.65.15:44442

[2021-01-28T20:24:03.633Z] /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:724: Failure

[2021-01-28T20:24:03.633Z] Expected: (UCS_INPROGRESS) != (status), actual: 1 vs 1

[2021-01-28T20:24:03.633Z] free not completed EP close request: 0x1003f9cef80

[2021-01-28T20:25:00.086Z] [1611865495.581437] [r-vmb-ppc-jenkins:17794:0]       ucp_test.cc:226  UCX  ERROR request 0x1003f9cee00 did not complete on time

[2021-01-28T20:39:07.153Z] /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/test_helpers.cc:54: Failure

[2021-01-28T20:39:07.153Z] Failed

[2021-01-28T20:39:07.153Z] Connection timed out - abort testing

[2021-01-28T20:39:07.153Z] [r-vmb-ppc-jenkins:17794:0:17794] Caught signal 6 (Aborted: tkill(2) or tgkill(2))

[2021-01-28T20:39:07.153Z] 

[2021-01-28T20:39:07.153Z] /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc: [ ucp_test::progress() ]

[2021-01-28T20:39:07.153Z]       ...

[2021-01-28T20:39:07.153Z]       152          iter != entities().end(); ++iter)

[2021-01-28T20:39:07.153Z]       153     {

[2021-01-28T20:39:07.153Z]       154         count += (*iter)->progress(worker_index);

[2021-01-28T20:39:07.153Z] ==>   155         sched_yield();

[2021-01-28T20:39:07.153Z]       156     }

[2021-01-28T20:39:07.153Z]       157     return count;

[2021-01-28T20:39:07.153Z]       158 }

[2021-01-28T20:39:07.153Z] 

[2021-01-28T20:39:07.153Z] ==== backtrace (tid:  17794) ====

[2021-01-28T20:39:07.153Z]  0 0x000000000005fd28 ucs_debug_print_backtrace()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucs/debug/debug.c:656

[2021-01-28T20:39:07.153Z]  1 0x00000000106484d0 ucp_test::progress()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:155

[2021-01-28T20:39:07.153Z]  2 0x0000000010648fac ucp_test_base::entity::close_all_eps()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:746

[2021-01-28T20:39:07.153Z]  3 0x0000000010649140 ucp_test::disconnect()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:197

[2021-01-28T20:39:07.153Z]  4 0x0000000010649140 ucp_test_base::entity::get_num_workers()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:874

[2021-01-28T20:39:07.153Z]  5 0x0000000010649140 ucp_test::disconnect()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:187

[2021-01-28T20:39:07.153Z]  6 0x00000000106491f0 ucp_test::cleanup()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:78

[2021-01-28T20:39:07.153Z]  7 0x0000000010225170 ucs::test_base::TearDownProxy()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/test.cc:316

[2021-01-28T20:39:07.153Z]  8 0x000000001040b980 ucp_test::TearDown()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.h:190

[2021-01-28T20:39:07.153Z]  9 0x000000001020085c HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3562

[2021-01-28T20:39:07.153Z] 10 0x000000001020085c testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3598

[2021-01-28T20:39:07.153Z] 11 0x00000000101ef984 testing::Test::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3643

[2021-01-28T20:39:07.153Z] 12 0x00000000101efb4c testing::TestInfo::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3812

[2021-01-28T20:39:07.153Z] 13 0x00000000101efd98 testing::TestCase::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3930

[2021-01-28T20:39:07.153Z] 14 0x00000000101f5d98 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:5808

[2021-01-28T20:39:07.153Z] 15 0x00000000101f61e4 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:5725

[2021-01-28T20:39:07.153Z] 16 0x00000000101f61e4 HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3562

[2021-01-28T20:39:07.153Z] 17 0x00000000101f61e4 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3598

[2021-01-28T20:39:07.153Z] 18 0x00000000101f61e4 testing::UnitTest::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:5422

[2021-01-28T20:39:07.153Z] 19 0x0000000010170668 RUN_ALL_TESTS()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest.h:20059

[2021-01-28T20:39:07.153Z] 20 0x0000000010170668 main()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/main.cc:102

[2021-01-28T20:39:07.153Z] 21 0x0000000000025100 generic_start_main.isra.0()  libc-start.c:0

[2021-01-28T20:39:07.153Z] 22 0x00000000000252f4 __libc_start_main()  ???:0

[2021-01-28T20:39:07.153Z] =================================

[2021-01-28T20:39:07.153Z] Sending notification to rakhmetshin@nvidia.com

[2021-01-28T20:39:07.153Z] [r-vmb-ppc-jenkins:17794:0:17794] Process frozen...
```

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by evgeny-leksikov** [comment]
> @evgeny-leksikov were you looking at the problem like below? It fails 2d time in a row here

https://github.com/openucx/ucx/issues/5337

**Pull request merged**
