### PR TITLE
AZP/PERF: Get PerfX codebase by tag

### PR DESCRIPTION
**Pull request by Alexey-Rivkin**
## What
Get PerfX codebase by tag instead of the latest master.

## Why ?
Improve stability by shielding possible breaking changes in PerfX.

## How ?
Current change management procedure:
1.	UCX uses PerfX with a tag v1.0.0.
2.	A change is needed in PerfX.
3.	Someone creates a branch in PerfX and develops it, PR is created.
4.	UCX branch is created to use new Perf. If a change is complex, we verify it and cont. development of PerfX as needed.
5.	Merge PerfX and create a new tag v1.0.1.
6.	Update UCX branch to use v1.0.1.

### CODE REVIEW

**Review by amaslenn — APPROVED** [review]

**Comment by Alexey-Rivkin** [comment]
Unable to verify till [HPCINFRA-1518](https://jirasw.nvidia.com/browse/HPCINFRA-1518) (internal link) is resolved.

**Review by dpressle — APPROVED** [review]

**Review by amaslenn — APPROVED** [review]

**Comment by Alexey-Rivkin** [comment]
[Working build](https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=76149)

**Review by yosefe — APPROVED** [review]

**Pull request merged**
