### PR TITLE
DOCS: Improve docker docs

### PR DESCRIPTION
**Pull request by gleon99**
## What
Mention explicitly the requirements for using RDMA.

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
why unlimited ? is this docker requirement ?

**Comment by yosefe** [comment]
it's needed to use RDMA (not specific for docker, but can be overlooked when using docker)

**Comment by shamisp** [comment]
Is not unlimited is a bit brutal ? I would describe that RDMA requires XXX of locked resources. For simplicity they can set to unlimited but they should check with their IT. What MOFED  documentation recommends ?

**Comment by yosefe** [comment]
> Is not unlimited is a bit brutal ? I would describe that RDMA requires XXX of locked resources. For simplicity they can set to unlimited but they should check with their IT. What MOFED documentation recommends ?

It really depends on how many resources are created - how many memory buffers are pinned, etc. It also depends how much memory the application allocates and passes down to UCX.
Maybe we can say "limit -l should be set to a value large enough to accommodate for transport resources and send/receive buffers. It's recommended to set it to at least 128MB, and increase the application working set is large."
This is what rdma-core has:
https://github.com/linux-rdma/rdma-core/blob/master/Documentation/libibverbs.md#using-libibverbs

**Comment by shamisp** [comment]
@yosefe +1  - let's follow verbs documentation.

**Comment by changchengx** [comment]
@gleon99 Should we also need install ofed package in the docker image? If so, what's the minimized ofed packages to be installed?

**Comment by gleon99** [comment]
`ulimit` explanation - fixed.

I'm not sure regarding the ofed package - maybe we only need to mention there things which are specific to running *in docker* (ofed is needed anyway)?

**Comment by changchengx** [comment]
@gleon99 
In docker container, ucx will use rdmacm or verbs library and so on. It'll use the library installed in the docker image. It should also need to install OFED package. It's better that we could confirm the minimized required package to be installed.

**Review by yosefe — APPROVED** [review]

**Comment by gleon99** [comment]
@yosefe please look

**Review by yosefe — APPROVED** [review]

**Pull request merged**
