### PR TITLE
UCP/WIREUP: Fix initialization of wireup message request.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5565/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
@brminich i worte it in the commit message: Otherwise, error handling code may try to release memory registrations which don't exist.
This can happen in case of fabric error during wireup protocol, so ucp_ep_err_pending_purge() calls ucp_request_send_state_ff(), which checks ` if (req->send.state.uct_comp.func)`, which may be "garbage" if not initialized, and then `req->send.state.uct_comp.func(&req->send.state.uct_comp, status);` segfaults

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5574/ for details (Mellanox internal link).

**Comment by brminich** [comment]
sorry, missed that

**Pull request merged**
