### PR TITLE
CONFIG: Fixing bug in valgring config

### PR DESCRIPTION
**Pull request by shamisp**
Fixing #357

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@yosefe take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/810/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/237/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe @alex-mikheev can you please take a look why mlnx testing is unhappy

**Comment by yosefe** [comment]
i guess need to set with_valgrind to /usr
```
01:16:53 checking for yes/include/valgrind/memcheck.h... no
01:16:53 configure: error: Valgrind memcheck support requested, but <valgrind/memcheck.h> not found, install valgrind-devel rpm.
```

**Comment by shamisp** [comment]
Will fix it on monday

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/822/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/247/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe , please review

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
