### PR TITLE
UCP/WIREUP: Backport wire up message size fix for v1.2

### PR DESCRIPTION
**Pull request by MattBBaker**
Exact same change as in #1556 for v1.2

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1801/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3741/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3745/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Pull request merged**
