### PR TITLE
A missing space make compilation fail when uct.h is included from C++

### PR DESCRIPTION
**Pull request by abouteiller**
Just a typo.

### CODE REVIEW

**Comment by yosefe** [comment]
Hmm... log.h should not be included from APi anyway..

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1937/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1310/ for details (Mellanox internal link).

**Comment by abouteiller** [comment]
You'll get the error from here, when using gcc 6.1. 

```
 CC       perftest.lo                                                                                                                                                                                 [5005/19974]
In file included from /home/bouteill/ucx/debug.build/../src/ucs/async/async.h:17:0,
                 from ../../../../src/tools/perf/libperf_int.h:15,
                 from ../../../../src/tools/perf/uct_tests.cc:7:
../../../../src/tools/perf/uct_tests.cc: In member function ‘ucs_status_t uct_perf_test_runner<CMD, TYPE, DATA, ONESIDED>::run_stream_req_uni(bool, bool, bool)’:
/home/bouteill/ucx/debug.build/../src/ucs/debug/log.h:43:59: error: unable to find string literal operator ‘operator""_fmt’ with ‘const char [24]’, ‘long unsigned int’ arguments
             __ucs_abort(__FILE__, __LINE__, __FUNCTION__, "Assertion `%s' failed: "_fmt, \
                                                           ^
/home/bouteill/ucx/debug.build/../src/ucs/debug/log.h:52:49: note: in expansion of macro ‘ucs_assertv_always’
 #define ucs_assertv(_expression, _fmt, ...)     ucs_assertv_always(_expression, _fmt, ## __VA_ARGS__)
                                                 ^~~~~~~~~~~~~~~~~~
../../../../src/tools/perf/uct_tests.cc:314:21: note: in expansion of macro ‘ucs_assertv’
                     ucs_assertv(UCS_CIRCULAR_COMPARE8(send_sn - 1, >=, *recv_sn),
                     ^~~~~~~~~~~
```

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
