### PR TITLE
TEST/UCT: Extend MM tests

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12878/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/9e3fd6fe732e895b7c5e3b9c29749010e42dcd4b/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/b11258a4168779d0779392fe477da1b780d4ccb0/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/a0ebd069919ecd49c21a7189f9093f2d87f9f1f3/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/484755c006cdb9f652aaa71871f00fc294e3216e/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/593eabfd809f7fe3600121e7d6e14820cf469d8a/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/856696a5e7a0c72c0df797c78d49829d8318e2f1/hpc-test-node-new_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/3a5a663ecd6810af92dae84b52daee0f8e56cf41/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/cf3d6cf1e6584e6fda16db9cce3c28b874b2eee6/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/059256ea075278dc7360eb3597b403e37d1361fd/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/e46c4e2c0d5c53fcd3e38c7b1f09f52be08f2fa3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/8eb74a399dbcc48f9d8cf7e9588c7a0d305a6519/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/07862fcab02a68efb3f60914766c34e356255c8b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/88c2abdc18b3d030f7c970a0f632ce17e8c39b50/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/e511fb893a4766f626c9ea814cbfda2c2ed58930/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/2e11383365879e8d2a41044c4e6407958b94a3ec/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/141f036c13b3d3a93f6cf7ca9375a9697f3247ea/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/40f7fd48e83a6c96ce007d73c4afe07653cb4a44/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/005e0c85d73763bac6a5523ce7921ac445416a84/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/359808e48365d24546ca125b07b5f55d2113e3c9/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/e71560d44fe1bf2d41a809ad3b0cf6a6d97f5dbe/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/6e1c1e707c3a8a2dd1194318cb9dc6a9c9d01932/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/bb3dcc7731c3b07401d907c22150e47994b36563/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/4ff3ba2740f8e3ea02c9e796f21687e24476ee03/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/08327886d421b56d90f5be029120d481b05cffab/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/5781da0d351bf5acd71a7fa0de22e7ada28c529b/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/5b7f9bb19674ae1430954c2720e82d73a4c9ebef/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/a5443b20c0c9d740f70c3d2e2ca794a702b1b137/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/9c8b878356fe8cd384cfe51f9ffe04b7e15df199/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/2e97c317e98e3b19bdb1b8ced4b11459/raw/c2c84c441bb724bf229f0bbbe230dcd2bbd38f4e/hpc-test-node-new_W1) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12886/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/ef2d0e5d9c3ce801a53523b755f4421677dcf33f/_main) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/04e52be236441c545e1cdb8eccb87a180da5b879/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/4851dee1dd362b484a096c6f566aec6475933abf/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/9619ff2bf984a1e774a24c6dff232bb784fa247a/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/f670177672cd5f0933d02e552884a6420a98f7fa/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/7b314f1f1b2dcad5d668df0459b70b644b59f888/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/c05b29294fecd42cb694291c29da4a83b2a1b549/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/bc84978e8f1de802a3395eb4ca273d236b8de057/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/005acbd51c050a2fe7ae45509ba99729334115d5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/e17a316ce0b12560030e23e9ddb89b1e934022c1/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/8c7b9838b02287ccef08d324bd8cc0fb3fe3ca36/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/52c0e79e38e08dad55659a1634bf895cf5df8df4/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/23cc9da474e504f1d68898ee62ce94ea79f6c51d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/bc61c423826c55f728d145ffc1dbcdffc5c39674/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/fb521d2ef58c04fe88fccf798e2885cdbe7c0eb6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/ca3c9f40677a3128d2f5465598aa5550358b11b2/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/ca7390acc04cc7a963f59cbebf832bd69575d67c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/6afd70f6b3f23977fa955a09cf18e4d49f56cb49/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/1d66d10a4318525f0deddf06ab6ea154001df886/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/b19a31c3a37afe2e0104515c534c754a0530c1bd/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/d776e5e79d8fa61e32a50104e79f91006fb97dd0/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/2ba99f9849eac60c32b4039ce351d259215c7053/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/d7462c30db5e5a46460ec02342935605c7c1e7de/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/77a5cda2672dcefdbc60ff26bb7358580ea23ac4/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/82cb89174db92b39eaca5b3cd8cea39d5e3198d8/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/96bccd34a0be740b0b5d36f67a9e9f2e5b24f818/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/b3e454e15ec89c84f8833d52de3c77e62de9bfca/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/55678e2e9be7806f5fd27699ac773aa1a219dfd9/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c9933449e41ed996146dd8dc6ac2a496/raw/0fa38b9612b70afffb9ad63e17d1eca7033827dc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12907/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/121ed066b4c3679dd17bbdabeb1fadccd5b55d49/_main) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/5f5e33845233dee12cce0a85b15f86a3921c0650/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/14a990a8846f7ffa60b188c927fcd8c381b3dd24/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/41e1defa0764e6ecb0a0197e9c9f290b551b6154/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/bbfc6084757a90ffbec368124a6101490da91806/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/d996a4dc7ad3908e67b3817273a71cc037497ff4/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/cdf0cf688c49f0960e890c4637bff190d0ecc68c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/d07f97743292aa28847660dd6f175fa5cefbce9c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/25b1a1a35ed27fb47c56647fdfd5765495db39cf/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/a8a58e6fe13518d57b54cb3c4315a3bd0cf7d00a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/4ca2f732079a6c9a444324cfbac34fbfdf6545da/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/defbbe74f99a38184e5e8f092c9524090bb9f186/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/d84d27564034e0d495dfbd5b0696ac48a588a3ba/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/517794ac787079638d946bc72d34bba8e865f7e1/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/4418137e10aae583399025c145d790693ec000e0/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/e9de73a6a87e248a9950481a39dabc2a1e3a37ac/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/18fab58a4e69813cd41e2d3076afe7bf24244801/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/e98a2d6cd1fcc091f3ea350d5ddcdffd57126ce0/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/6a1898ce0699f25c97f7e0c838d4aaae76e05651/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/b4f08a006f2bec1b1b19f737b0c2522bc3afb500/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/4883d6b9bfdccad8474f6c5d31d23edf71558964/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/b90b1a0e6cd4308ef77f4581fafed73eed29580c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/285c41fe67b6dce7ab62b19496a662ff35cfd28d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/e8a5bf87b69fa5e18caab160d5340f593394dac7/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/67862fc207f981357398dfea9a3e20c7e454e2fe/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/9eb3b2f055a3c81a96ab38e112f005ad48a02ce4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/768dcc24df720e55f3af96e01f089b430779dab3/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/24ea73bb4db57935d2fb06fa4be3774be3edb2e1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0199eb03068833696d5b5ff3ca088683/raw/af40a1d01c17e53456dbe66cc4b35960b14c196b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
hpc-test-node2 failure
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12920/ for details (Mellanox internal link).

**Pull request merged**
