### PR TITLE
DOC: Updating UCX architecture figure

### PR DESCRIPTION
**Pull request by shamisp**
Fixing #799

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
@shssf please take a look.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1365/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3306/ for details (Mellanox internal link).

**Comment by shssf** [comment]
:+1:

**Pull request merged**
