### PR TITLE
DNM - Ucx memory consumption

### PR DESCRIPTION
**Pull request by eladpe**
this PR replacing  PR 1525

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3898/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3899/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3900/ for details (Mellanox internal link).

**Comment by eladpe** [comment]
BOT:ornl:retest

**Comment by eladpe** [comment]
@MattBBaker ORNL is failing me on remark line. Can you tell why is that? Thanks

**Comment by eladpe** [comment]
BOT:ornl:retest

**Comment by MattBBaker** [comment]
@eladpe This one was internal badness.

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3901/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3903/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3910/ for details (Mellanox internal link).

**Pull request closed without merging**
