### PR TITLE
TEST/EXAMPLES: Makefile fixes

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe why remove pedantic ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9232/ for details (Mellanox internal link).

**Comment by brminich** [comment]
OOM and #3318 

bot:mlx:retest

**Comment by yosefe** [comment]
@shamisp i've added -pedantic, not removed it...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9237/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
> @shamisp i've added -pedantic, not removed it...

Ah sorry, tried to review from my iPhone.

**Pull request merged**
