### PR TITLE
UCP/AM: Use UCX memcpy for AM eager

### PR DESCRIPTION
**Pull request by brminich**
## What
Use internal UCX memcpy for AM eager flow 

## Why ?
Performance + profiling of memory copies

### CODE REVIEW

**Comment by brminich** [comment]
issue is #5844

**Review by dmitrygx — APPROVED** [review]

**Comment by brminich** [comment]
@hoopoepg, @dmitrygx, please review

**Review by dmitrygx — APPROVED** [review]

**Review by hoopoepg — APPROVED** [review]
does it improve performance?

**Comment by brminich** [comment]
> does it improve performance?

On the message sizes I checked on x86 the impact is minimal (~noise). Maybe need to check others. But anyway this is the func, which is supposed to be used internally..

**Review by yosefe — APPROVED** [review]

**Pull request merged**
