### PR TITLE
UCP/COMPILE: armclang fix v1.3

### LINKED ISSUE #2176: Clang5 + UD is still broken...
We are missing clang5 in regression...

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixes for armclang5 build
- added test armclang5 build

backport from https://github.com/openucx/ucx/pull/2274

Fixes #2176

### CODE REVIEW

**Comment by yosefe** [comment]
adding @shamisp

**Comment by shamisp** [comment]
```
17:31:49   CXX      ucp/gtest-test_ucp_tag_probe.o
17:31:49 In file included from /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/common/test_helpers.h:11:0,
17:31:49                  from /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/common/test.h:10,
17:31:49                  from /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/ucp/ucp_test.h:17,
17:31:49                  from /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/ucp/test_ucp_tag.h:11,
17:31:49                  from /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/ucp/test_ucp_tag_offload.cc:7:
17:31:49 /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/common/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int]’:
17:31:49 /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/common/gtest.h:18898:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int; bool lhs_is_null_literal = false]’
17:31:49 /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/ucp/test_ucp_tag_offload.cc:200:5:   required from here
17:31:49 /scrap/jenkins/workspace/gh-ucx-pr-2/label/ARM_test_node/worker/0/contrib/../test/gtest/common/gtest.h:18862:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
17:31:49    if (expected == actual) {
17:31:49        ~~~~~~~~~^~~~~~~~~
17:31:51   CXX      ucp/gtest-test_ucp_tag_xfer.o
17:31:51   CXX      ucp/gtest-test_ucp_tag.o
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6210/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6214/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6217/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6218/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe tests are ok

**Comment by shamisp** [comment]
👍

**Pull request merged**
