### PR TITLE
BUILD: Set default prefix to /usr/local, allow rpmbuild to override it.

### LINKED ISSUE #1651: MLNX OFED should not install UCX into /opt/ucx blindly
On some platform `/opt` is a shared folder mounted over NFS, and concurrent installations on multiple machines of OFED will fail as `/opt/ucx` is not empty.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1651

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3981/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3984/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3985/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @miked-mellanox pls review again - i had to cleanup rpm spec and deb files to fix rpm build on ubuntu and sles11

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
@byronyi FYI

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3994/ for details (Mellanox internal link).

**Pull request merged**
