### PR TITLE
UCS/PROFILE: Add cast from pthread_t to uintmax_t, to avoid warning.

### PR DESCRIPTION
**Pull request by kostikbel**
Signed-off-by: Konstantin Belousov <konstantinb@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12116/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/b2025ddb9e3f208456f7a343f1280cef4a86ad65/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/41957dc012173f2abb6d7a98e0f3b15cfd8d66e7/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/0d58edff7f3ed5632a18a5c13559cf379763e5e5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/8f0f7dec1d0b7fcb8aea9756890eff2dc7243146/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/4999e2e74d64d994c64018fdcd83919f085f18ae/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/be32a5ece473e4cd32567ae0306748e08bc89a23/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/57b09ba16c3b34de77837a5e921f299a2e349bfc/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/195c7367faeb691cab373cd03fe57bf2e9130079/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/5f911286d013e6b75d3dd838334152ff05476282/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/56a795ef3cf4d2b96d69d351f11b500a37693d9e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/2e646f7c947d7049a76bbdbadfface12058d61ed/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/b508a768f27098c1096144e00748c8db7679a226/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/89334d6fb8a1ab870e5e42983fac0512a3071803/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/a4b51af5a896bf32043720ec9d3850161389a97a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/df7ec88ca6d9a13ad302dfafdb469e6b480f545b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/b5f05094b9303d0ab2dba41238334c491fb44546/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/5b6da0a0f60101bc25a0f14c3dd81be522d3033a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/0260cb80f365129e03ec25dd7d42120923792998/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/40973773d4153f6b067d22a70da8f992365fa81e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/676552608459bc7c3778919bc863d95b0ed7f6fb/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/6319c398c3d26b1359bb186f3db3ba2d88261ff9/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/7af22b68eb9bc855e4bef1637fc590369addbc99/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/9c4b62c0eceb30b34778c04a4adf0b5b4de34191/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/5fba7ca984500d6d1a451f0c2c405c3bfcbb26ef/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/807707522c6ed916371cd5d0df7183631f8f5602/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/fa7bcdaa320ef8d526f770f3e28cf0285488b23b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/4d9f3b893a970db168e6e00a5891d48209d3d311/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/1f9ccece333c47b36a8783ab4b886fc0969d039f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3753a59c2077f71083721a72417de139/raw/ac97278c79f1aaf558066067374b6e287207877a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12156/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 8 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/07332c023c6e4762e8b01b56d4a0b74d4ecb95ff/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/20a247e003482767e8345a5477a353be83b66fee/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/4da7ab1fef13d254abe252f7f5f17bc863950dee/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/003573fb8726d58817f92d2bfcfe2c30a20a0c6e/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/f20b9479601b53b0b89dd8a9daebe38705db605f/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/bd227b7b2fe75fd1441ad54f1c7c9de6cc3a36fc/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/13c3baa03f3f64f8ff9ec38723090e8fc7df3590/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/7d8129a441d19a7c47de867e7ae9868f0348ab27/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/b5f4a7950b47bea3a75d9f77a4d3300f899b74e9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/fec34b05e42211b46e059b2ee4a614fba450ca0a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/693424d520fcc4c8a62916b07305c7d837f11c79/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/e75bd3150d1d57b40e4e1811e9969e2c896a3aa3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/bce18c82b14dba354f878f43f1e44c6258f0f4d9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/533627b11b47b945a83dac979b57e00a26cb427d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/f14bf4126209c3b5f7be7f6bab720e1f6e6c3bef/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/425e2b3b2de4d973d8aa6e1942068e47875bfbff/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/32be77980f12df5a6f4147b8e6fc0217bf49d14d/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/0beb582d34cc9b341feb84c45c37a9db9a9073a0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/313ee969ae7cb3435fb16b8e2a4f4c252c599cfe/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/acfee0b95b8e85661557ac09698bf7603e629ee9/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/5073a97226c960b2fe0e09d042e2b3adcba19532/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/0e02688f40462982e7ce78eaa82c6a6d7e7b38b3/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/ea95f2e77460c94c3fc5ea3cc278fe5c2413c700/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/c4b750614a97c6c2cd08d8de24c7cb379c63c63c/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/fd7d4fee2b351ac17cb7c4636f0b2811a30c3f51/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/cbe8ca8adee7beb77cabdb6154c0cf908ca54e7f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/35b62fdce4ebdd2b591eaf9bc33bf3449253effa/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/055d791c57eb0b58c543e5a289fe837c4480d2f8/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/79bf677628d80c327afba044a293ff95/raw/d81126496fead0993276723ede22ea6ab4fefd3b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12176/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/0358ac60598c37d9b34e7e0d7e698a69ab5f821a/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/284b0b338e33bba6bf5ec8dded5fc80d741a4d4c/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/febf5bb16154bbd856fb608a7b328c2671ec03d9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/913a2c69687972de4dea6d761e281b25c42ddf7c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/7602f861a4d5bfd7c56b0b659d7f153d72b58b04/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/48a52226f465dfc0a0fd07c7e649d903b2da02ba/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/d6811da5b379d56a819e7c3e6810f5e4fb001929/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/0a68c19130b1939d2a47c5e9ada8156d4f50d3f6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/c7609676cf15a3726d40bb7e09c9f84181cfc125/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/9a3866053e556b7900408dd9e05ef80de6359b17/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/c208bae1808bc015d16dcfe1b569b3d3afe43aad/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/20098ee7150c9d48693a20349ca80f5ddc476def/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/9e34f62a84d8bae549dfea6e8deed050bb1c7076/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/864302ede363822213db8b16da053e3fd14d6958/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/96ba476bd70b10cfe77ee413041605ca95fa4a22/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/27b70acf15cea0eb2bffd613966595d3a52ad843/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/2ba2cdbce8089476b0fdfa31fe520d8b70093d67/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/833ba6b3c941ec6548c75140ec7ec60617786879/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/c299615c9f605cb2424576771849cd10b1dd7f18/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/40e3a31a2257db83f924e1beab5004d1fced90e9/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/b5b5f943c01b5fc025300fb66f762d4f296922eb/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/ea055047ee598c22a6afd4890019f8408e84dfdb/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/a49625ac6f58f18df1aa77fa9f55225ecfcf225a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/eaad3b64753e95450e7233a1208b9c30657be0b5/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/bb399cb561c5b3248739a553b6ad5c6a1ed04ee0/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/e11974051cd078dc86bd5272499f72e9842566fd/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/e4103fadfef1599836e3202a2ea7b7127f158893/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/1d6b3090013901a0035949cd948ef824217f7db3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6a4f31fd131469054ad16c4bfc315837/raw/926c9a929f10a52694c89c7dc2d93b4022cbf9d3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12213/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/0f36a5e9b69f6ec1e386d80c2755eddbfbaf95d1/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/a5d3672135b0ad62ef8205cfe816a7465a15415e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/520c2058217a50708f89a8fd9f29468a225e73ab/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/722910207732f6e9c4db181b3386e4320869b03b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/65468beddefed94e9744c0281ef07a4358f212bd/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/f20fb648faac801bcf49ab050c11bfef1ea68707/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/b49609afd56da7b7993a9cfbcef77ecdbb5f1e0c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/53816c715d5d1273f99c128d67adff358c70a0da/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/b929113fe36b341514b187bb597cda7dd91ebaa3/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/7343287d38dc7cb4f852f769f9cf3e826fd8f604/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/c79b75697d101b3c2aa2865a8a5762539a19752e/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/b8313d8b202cf14e8df9549b7230eedd3356ad24/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/d96dad5c8b6bbbf0d86e2d989620007ad15e802d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/1b16b0af24f0b01e5461d786fb4e25339bb69aba/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/d67973021a0d904fe05cb40f503f95289f9d4a10/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/9960635a72aef99c866010d4f0baeaa09edcd921/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/8160e5a7abe3581fb9b8aad494b8f3611ec7df43/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/6119a4fedf7b7d6fd2d5830853c1a8c1c791215f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/477d82d64d9ddb42ce0cd789614286eec63c5a23/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/2be92eb212d05a33def27b3a1fc5d50347e7f469/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/9918e87336f9e17a4b261e4b1c2a80d6e6a4c756/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/7dac39fc62fb1d080007849e0fbc5827c5b008fe/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/d16e72d30540fc0ff770a1d06baa9c82db0bd8de/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/0e84f75d10d86ddfc09a4a2f36827a82942c586c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/3d22a1c667e7bf5a3e9b7c20aede572aad0af8de/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/062be1c1948c2bbf411bea26954fa05d1e01aa0b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/da039288ccfdcbf33281c8cb2bfdd4d36f4807b9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/8dcb80564232da4329ff4cc539b60c8a19cc9a72/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4164b8388a76be42309646c240cc4406/raw/b8ad779dc3cb92b03bf21a7b94948eb49ae40ae3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
