### PR TITLE
UCP/PGI: fixes for PGI compiler

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed wireup, amo, rma components

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12559/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/fa477cad52549584779f814a7e3767efb365211f/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/2fd817d704cc4b5a11650cab5adf2a36d382b2a4/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/de7568975bbff320cf3fcc4abe4ef2cc64382da0/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/ff5a267c801c971b60b685458f73751e5d4f747c/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/182e7d21aa313eee05f0766913c34d9ae8518731/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/72d55a5178e2d4f69f47c6f38eced474df695daf/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/3bd3daac8f34e97144d286737307e4f4ba5cefbf/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/d5de2d2f890a679eaeddeceb7f1e2184adf4a0e0/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/5c531e8e3529ee62f9051f59d0aa34ebf511eaa6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/65f034f924878fffd202faa10bfb3ed657997c51/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/1c12f19106491be4c1f77544c953b21772a25e1d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/df3fdd9134bc6a2b7d62fa60a18b701e1a1ea5b7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/79bfa8a3d1188bfa2b04a13026c1e0d5432654fb/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/85db8c48a5af567bbcd1bc4400c4b566e9645a3e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/93c0b5351dd19eefc23e6b687262bbcf1f80abb2/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/a54dbddeca784af0ab8cff6c9591947c03582494/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/16411b339c0428841611c7feb938ee19983b8439/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/aa7d32f25d1dc248dfabc3781749dfc06ab443b4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/ef9f693fe176e018ca9975830a8f001e4ce7e24e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/168fbb8600b350a5c86069e54dbf6ecef125f4b5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/ecb0052346d973729cadab1916180f1cb0116aaa/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/66245651b3b8a9cbe4e02365e5529e346a10359e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/43304d5122042221da3157191a4c6b58b813f2ed/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/a10fae88e22f0b4c16a23903d1e175d2a69b33cb/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/1d475705089a76ae1941a8960ffc4722033339bb/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/971047f8b68de15f87de9c6c8022c1c18223b8ec/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/2f30331c002b1fdf8a7b8079b89eb3421ee31308/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/792de0f884ff99500c44330e0b3625722b188653/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f0d1d0fa795146d27edee20e176ca53/raw/84f9f600defd8648542c9de7c812efc8c0f82a6e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
bot:bgate:retest
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12579/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:pipe:retest

**Comment by hoopoepg** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
