### PR TITLE
NEWS: Updating news file with known issues

### PR DESCRIPTION
**Pull request by shamisp**
NEWS update

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7867/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe @bureddy - is the description okay ?

**Comment by yosefe** [comment]
bot:bate:retest

**Comment by yosefe** [comment]
bot:bgate:retest

**Pull request merged**
