### PR TITLE
UCP/EP: Fix missing initialization of rndv_send_nbr thresholds

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6558/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Looks like should go to 1.3 as well ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6564/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6571/ for details (Mellanox internal link).

**Pull request merged**
