### PR TITLE
UCT/CUDA: Fix cuda iface address and reachability

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6543/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6546/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
```
00:57:35 [1521327455.090024] [vulcan-jenkins:18086:0]         select.c:312  UCX  ERROR no copy across memory types transport to vulcan-jenkins:18086: self/self - Destination is unreachable, tcp/eth0 - no put short, tcp/ib0 - no put short, rc/mlx5_0:1 - Destination is unreachable, rc_mlx5/mlx5_0:1 - Destination is unreachable, dc/mlx5_0:1 - Destination is unreachable, dc_mlx5/mlx5_0:1 - Destination i
00:57:35 Failed to ucp_worker_create
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6547/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6567/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Pull request merged**
