### PR TITLE
UCT: Disable the cm transport if the ib_ucm.ko module is not loaded.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe Can you please review?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9512/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9522/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls pick to v1.6.x

**Pull request merged**
