### PR TITLE
NEWS: news update before v1.6.0 rc1

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe I want to tag this today.

**Comment by shamisp** [comment]
okay to test

**Comment by shamisp** [comment]
News backport from master. TXT changes only.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10453/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10454/ for details (Mellanox internal link).

**Pull request merged**
