### PR TITLE
Add basic MT support to UCP level.

### PR DESCRIPTION
**Pull request by xinzhao3**
Revert field mask name UCP_CONTEXT_ATTR_REQUEST_SIZE to UCP_ATTR_REQUEST_SIZE.

### CODE REVIEW

**Comment by alinask** [comment]
@xinzhao3 was the MT support in ucp tested at scale?

**Comment by xinzhao3** [comment]
@alinask No. Currently I just tested it with 2 to 4 processes.

**Comment by xinzhao3** [comment]
@miked-mellanox @yosefe I reverted the name of field mask. Could you review again?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2899/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/380/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2312/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
@xinzhao3 - is it compilable with ompi master after the change?

**Comment by xinzhao3** [comment]
@miked-mellanox Yes.

**Comment by shamisp** [comment]
@yosefe - did you reset the header or something ? the change is much more aggressive than simple revert.

**Pull request merged**
