### PR TITLE
FIX: fix license in several files

### PR DESCRIPTION
**Pull request by amaslenn**
(cherry picked from commit e38c6918015c8dc7cdeb342481e014056f04ea3d)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4901/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - is this unrelated failure ?

**Comment by yosefe** [comment]
@amaslenn , next time, the branch you create on your forked repo should be named "topic/fix-license"
see https://github.com/openucx/ucx/wiki/Guidance-for-contributors#git-workflow-to-submit-a-feature-or-bug-fix point no. 3

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4904/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp should be fixed by https://www.google.com/patents/US20160072906

**Pull request merged**
