### PR TITLE
PERFTEST: Fix hang in atomic add test.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/729/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/166/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
