### PR TITLE
IB: Register atfork() handler only once, and also check it in configure.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #702

### CODE REVIEW

**Comment by abouteiller** [comment]
+1

**Comment by shamisp** [comment]
+1

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1108/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1711/ for details.

**Pull request merged**
