### PR TITLE
UCT/DC: Work-around bogus array-bounds warning on gcc 5.1

### LINKED ISSUE #1302: Compilation fails on fedora-release-23 PPC64LE
[10.7.65.195]
```
  CC       ib/dc/base/libuct_la-dc_iface.lo
  CC       ib/dc/base/libuct_la-dc_ep.lo
  CC       ib/dc/verbs/libuct_la-dc_verbs.lo
In file included from ib/dc/verbs/dc_verbs.h:10:0,
                 from ib/dc/verbs/dc_verbs.c:7:
ib/dc/verbs/dc_verbs.c: In function 'uct_dc_verbs_iface_progress':
/var/tmp/OFED_topdir/BUILD/ucx-1.0.2385/src/uct/ib/dc/base/dc_iface.h:120:27: error: array subscript is above array bounds [-Werror=array-bounds]
         if (iface->tx.dcis[i].txqp.qp->qp_num == qp_num) {
                           ^
cc1: all warnings being treated as errors
Makefile:1363: recipe for target 'ib/dc/verbs/libuct_la-dc_verbs.lo' failed
make[2]: *** [ib/dc/verbs/libuct_la-dc_verbs.lo] Error 1
make[2]: Leaving directory '/var/tmp/OFED_topdir/BUILD/ucx-1.0.2385/src/uct'
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1302

### CODE REVIEW

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3363/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/896/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2859/ for details (Mellanox internal link).

**Pull request merged**
