### PR TITLE
CONFIGURE: Update SO version from 0:0:0 to 1:0:1 - v1.5.x

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe we are still backward compatible. So we really have to mark that interfaces were removed ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8666/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
Do we have any other changes pending, besides main readme update ?

**Pull request merged**
