### PR TITLE
UCP: Fix atomic caps in unified worker address

### LINKED ISSUE #4160: [mtt] SHMEM/UNIFIED on CX6: Fatal: endpoint reconfiguration not supported yet
Configuration
```
OMPI: 4.0.2rc1
MOFED: MLNX_OFED_LINUX-4.6-1.0.1.1
Module: hpcx-gcc (2019-09-03)
Test module: none
Nodes: jazz x3 (ppn=28(x3), nodelist=jazz[05,08,24])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtl_scrap/users/mtt/scratch/shmem/20190903_150831_60396_916_jazz05.swx.labs.mlnx/html/test_stdout_6jLVgJ.txt

Doesn't reproduce with unified_mode disabled (`-x UCX_UNIFIED_MODE=n`).
Doesn't reproduce on CX5 (`mlx5_2`).

Cmd:
`oshrun -np 15 --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll_hcoll_enable 0 -mca coll ^hcoll -x HCOLL_POLL
ING_LEVEL=1 -x HCOLL_ENABLE_MCAST_ALL=0 -x HCOLL_BCOL=basesmuma,ucx_p2p -x HCOLL_SBGP=basesmsocket,p2p -mca spml ucx -mca pml ucx -x UCX_TLS=rc_x,self,sm -x U
CX_NET_DEVICES=mlx5_0:1,mlx5_4:1 -x UCX_UNIFIED_MODE=y --map-by slot -x SHMEM_SYMMETRIC_HEAP_SIZE=128M /hpc/mtl_scrap/users/mtt/scratch/shmem/20190903_150831_
60396_916_jazz05.swx.labs.mlnx/installs/V4Ff/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=analysis:tc1`

Output:
```sh
[jazz24:190231:0:190231]      wireup.c:923  Fatal: endpoint reconfiguration not supported yet
[1567668379.516967] [jazz24:190231:0]         wireup.c:796  UCX  ERROR old: am_lane 4 wireup_lane 3 reachable_mds 0x1b3
[1567668379.517001] [jazz24:190231:0]         wireup.c:802  UCX  ERROR old: lane[0]:  4:rc_mlx5/mlx5_4:1 md[4]      -> md[5]/ib       rma#2
[1567668379.517005] [jazz24:190231:0]         wireup.c:802  UCX  ERROR old: lane[1]:  0:posix/memory md[0]          -> md[0]/posix    rma#0
[1567668379.517008] [jazz24:190231:0]         wireup.c:802  UCX  ERROR old: lane[2]:  1:sysv/memory md[1]           -> md[1]/sysv     rma#1
[1567668379.517012] [jazz24:190231:0]         wireup.c:802  UCX  ERROR old: lane[3]:  4:rc_mlx5/mlx5_4:1 md[4]      -> md[4]/ib       amo#0 wireup
[1567668379.517015] [jazz24:190231:0]         wireup.c:802  UCX  ERROR old: lane[4]: proxy to lane[1]              -> md[0]/posix    am am_bw#0
[1567668379.517018] [jazz24:190231:0]         wireup.c:796  UCX  ERROR new: am_lane 3 wireup_lane 0 reachable_mds 0x1b3
[1567668379.517021] [jazz24:190231:0]         wireup.c:802  UCX  ERROR new: lane[0]:  4:rc_mlx5/mlx5_4:1 md[4]      -> md[5]/ib       rma#2 wireup
[1567668379.517024] [jazz24:190231:0]         wireup.c:802  UCX  ERROR new: lane[1]:  0:posix/memory md[0]          -> md[0]/posix    rma#0
[1567668379.517027] [jazz24:190231:0]         wireup.c:802  UCX  ERROR new: lane[2]:  1:sysv/memory md[1]           -> md[1]/sysv     rma#1
[1567668379.517029] [jazz24:190231:0]         wireup.c:802  UCX  ERROR new: lane[3]: proxy to lane[1]              -> md[0]/posix    am am_bw#0
==== backtrace (tid: 190231) ====
 0 0x0000000000052488 ucs_fatal_error_message()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c:33
 1 0x0000000000052616 ucs_fatal_error_format()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c:49
 2 0x000000000006e10e ucp_wireup_init_lanes()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/wireup/wireup.c:923
 3 0x000000000006e338 ucp_wireup_init_lanes_by_request()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/wireup/wireup.c:277
 4 0x000000000006fb8e ucp_wireup_msg_handler()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/wireup/wireup.c:593
 5 0x0000000000065285 uct_iface_invoke_am()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/base/uct_iface.h:628
 6 0x000000000006d768 uct_ud_mlx5_iface_poll_rx()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/accel/ud_mlx5.c:420
 7 0x000000000004a7e3 ucs_callbackq_slow_proxy()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.c:393
 8 0x0000000000029e5a ucs_callbackq_dispatch()  /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:211
 9 0x0000000000003413 spml_ucx_default_progress()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/mca/spml/ucx/spml_ucx_component.c:151
10 0x0000000000036bdc opal_progress()  /build-result/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:231
11 0x00000000000338bd ompi_request_wait_completion()  /build-result/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/request.h:415
12 0x000000000003563d ompi_comm_nextcid()  /build-result/src/hpcx-gcc-redhat7.4/ompi/ompi/communicator/comm_cid.c:293
13 0x0000000000030a74 ompi_comm_create_group()  /build-result/src/hpcx-gcc-redhat7.4/ompi/ompi/communicator/comm.c:1209
14 0x0000000000001e56 mca_scoll_mpi_comm_query()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/mca/scoll/mpi/scoll_mpi_module.c:160
15 0x00000000000c9ceb query_1_0_0()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/mca/scoll/base/scoll_base_select.c:394
16 0x00000000000c8c21 mca_scoll_enable()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/mca/scoll/base/scoll_base_frame.c:80
17 0x00000000000381bf _shmem_init()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/runtime/oshmem_shmem_init.c:368
18 0x000000000003afc2 _shmem_init()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/shmem/c/profile/pshmem_init.c:77
19 0x000000000003afc2 pstart_pes()  /build-result/src/hpcx-gcc-redhat7.4/ompi/oshmem/shmem/c/profile/pshmem_init.c:57
20 0x0000000000406dd9 __do_exec()  /hpc/mtl_scrap/users/mtt/scratch/shmem/20190903_150831_60396_916_jazz05.swx.labs.mlnx/installs/V4Ff/tests/verifier/tests-me
llanox.git/verifier/osh_exec.c:188
21 0x0000000000406dd9 proc_mode_exec()  /hpc/mtl_scrap/users/mtt/scratch/shmem/20190903_150831_60396_916_jazz05.swx.labs.mlnx/installs/V4Ff/tests/verifier/tes
ts-mellanox.git/verifier/osh_exec.c:128
22 0x000000000040577e main()  /hpc/mtl_scrap/users/mtt/scratch/shmem/20190903_150831_60396_916_jazz05.swx.labs.mlnx/installs/V4Ff/tests/verifier/tests-mellano
x.git/verifier/osh_main.c:138
23 0x0000000000021c05 __libc_start_main()  ???:0
24 0x0000000000405991 _start()  ???:0
=================================
[jazz24:190231:0:190231] Process frozen...
```

### PR DESCRIPTION
**Pull request by brminich**
## What
Fix packing/unpacking worker address in unified mode. 

## Why ?
Processes may chose different devices for atomics depending on NUMA locality. When unpacking address in unified mode need to know whether the remote resource can be used for atomics on the peer (i.e. it is a part of `worker->atomic_tls` bitmap).

Fixes #4160

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12259/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/b8bd6326bf2397e5d3f4de2486dda50037f4b042/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/b3d62a8da9543e2294541af808149a777356415b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/d2310d5ecf25ef81a244041bc26099b70e78dc8f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/caa49edb1fb999b3456a1f40f4b87edd175c55ba/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/b58095861984fc3b804ee386f2042b9b37c90424/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/6ce3f5267882278a301b5d148f2ca0adb08f9a17/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/17278a56c657e0d5e5defda89c4354f5596c92b6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/0dff45877056c55c60d4723cb068c9be095f2185/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/bce4604c6486453397c485b85d26e7f204b36997/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/6b85a23e4bc384f0c61d75f7a61bcf6b4cc10533/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/a193c6571dea63e110bab766443f088009b1b855/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/24dce7eb41ec752c031d2b4cb0ff670562b4842e/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/48597c7b0ac761d650a4125cc79639a94ce11b30/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/95bdd7a1889693324e5ddc477df8d4e1283587db/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/5e0bbe03aeb3e483065998624d14600ac5dc2817/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/d62290ef29dfcc24fd76b03b5a8115c7ea54bb0a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/f385be9c83f10ef980746c8a1b1d99d865ecef0e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/274c08c3ed8093c50c4a275203a4a331fd19aed3/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/437f0ee7f8a8f54b7f7935c0c490263fd6cf114b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/83a9b048dc825f752cb1133d64fb2eb7629ec8ee/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/a70f8fbea5c8f006a60cacde70649c14b98c8d27/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/9ef2739cf744966eb19baba4f42d6ffb57e0ff7d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/feaca883d550f3e1ef13259bcc0c131e0d4abaa8/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/b6ae9c3b47a31983e5c19c255ff33676fb78c153/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/1230472c683eed9ee67da0c3eb1456e22e21cce4/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/b624bfd5c341ffc11df74e37e2b5ab162c755b1f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/510501f40cbceb14e624c35d64fd8bafce4515ca/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/7fb38b73c161cb7f079b1bfd2f8753619304366c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d161847a48565f9bfad93e1293accfc0/raw/fbf0abb3d6442287159fdae88b6f896e60524d8f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
@yosefe, plz check

**Pull request merged**
