### PR TITLE
UCP: fix the sending function selection.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/949/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1556/ for details.

**Comment by alinask** [comment]
@yosefe please review

**Comment by yosefe** [comment]
:+1:

**Comment by shamisp** [comment]
@yosefe we require two reviews from different org for UCP level code.

**Pull request merged**
