### PR TITLE
UCS/ARCH: Fix reading ppc timebase from /proc/cpuinfo.

### LINKED ISSUE #1588: fix reading cpuinfo timebase for ppc
on clx-ppc-07:
```
cat proc/cpuinfo
timebase        : 512000000
platform        : PowerNV
model           : 8335-GTA
machine         : PowerNV 8335-GTA
firmware        : OPAL v3
```
ucs_get_cpuinfo_clock_freq() returns the value multiplied by 1e6, so the effective freq returned is:
512000000000000

On x86_64, where we see "2400 Mhz" or something similar in /proc/cpuinfo, it makes sense to multiply by 1e6…

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1588

### CODE REVIEW

**Comment by yosefe** [comment]
ok to test

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3892/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3893/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
You need to add test for the new API. Proc is a not reliable way of reading frequency.  Linux does not require to report freq. I would suggest to rollback the patch.

**Comment by yosefe** [comment]
it's done in case glibc does not support reading timebase.
We already have test for it (the one which tests `ucs_get_time()`) but didn't actually run it on older system so far.

**Pull request merged**
