### PR TITLE
EXPERIMENT/UCP/MEMIC/MEMREG: added flag to allocate memory on DM

### PR DESCRIPTION
**Pull request by hoopoepg**
NOTE: will work only single dc_x ot rc_x transport (because it failed to
        register on 2+ tl's) and ALLOC prio md:*,xxxxx

tested on
UCX_ALLOC_PRIO=md:*,md:sysv,md:posix,huge,thp,mmap,heap
UCX_TLS=dc_x

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7124/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7125/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7136/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7199/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
closing as it was for testing purposes only

**Pull request closed without merging**
