### PR TITLE
UCT/IB/CUDA: Penalizing HCAs farther away from GPU

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
Refer https://github.com/openucx/ucx/pull/3062
@yosefe @bureddy @brminich @shamisp

### CODE REVIEW

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8515/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe can you please comment on the failure

**Comment by bureddy** [comment]
@shamisp its valgrind error on upstream testing. seems not related to this PR.  other PRs also have same error

**Comment by yosefe** [comment]
@Artemy-Mellanox do we need to pick some fixes/suppressions to v1.5.x branch?

**Pull request merged**
