### PR TITLE
UGNI/UDT: Adding support for UGNI datagram

### PR DESCRIPTION
**Pull request by shamisp**
* Adding basic support for datagram
* Cleanup of UGNI infrastracture
* UCT level bugfixes (some of these really bloody!)

TODO:
- Pending queue support (have to talk with Yossi)
- Out of order messages (rare but happens)

### CODE REVIEW

**Comment by shamisp** [comment]
@hppritcha - please review (also we should chat about some of the open issues)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/978/ for details.

**Comment by shamisp** [comment]
@miked-mellanox , jenkins does not do well…
```
01:03:37 configure: error: --with-mpi was requested but MPI was not found in the PATH in /hpc/local/bin/:/hpc/local/bin/:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
01:03:37 Build step 'Execute shell' marked build as failure
```

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/401/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
adding @MattBBaker - please review.

**Comment by miked-mellanox** [comment]
yep, seems some nfs problem at night, module file failed to load but jenkins continued execution.
module load does not exit 1 on error :(

``` shell
01:03:29 + module load hpcx-gcc
01:03:29 ++ /usr/bin/modulecmd bash load hpcx-gcc
01:03:29 ModuleCmd_Load.c(204):ERROR:105: Unable to locate a modulefile for 'hpcx-gcc'
01:03:29 + eval
```

anyway, now looks ok

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/979/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/402/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Code looks fine. +1

**Comment by shamisp** [comment]
Thanks @MattBBaker . One more review to go.

**Comment by hppritcha** [comment]
this looks okay.  I'd not recommend the GNI post data route for a general, high performance  AM protocol however.

**Comment by shamisp** [comment]
@hppritcha it will be used only for smsg wireup (very similar to ibcm code in ib)

**Pull request merged**
