### PR TITLE
CONFIGURE: Add support for --enable-devel-headers

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10161/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp can you pls take a look?

**Comment by shamisp** [comment]
@yosefe I don't think the header files belong to the PR. These two are not connected to the define. It can go with a separate PRs in UCP and UCT levels, together with makefile changes.

**Comment by yosefe** [comment]
@shamisp right, they were added by mistake

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10281/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp fixed

**Pull request merged**
