### PR TITLE
UGNI: Fixing NULL callback failure

### PR DESCRIPTION
**Pull request by shamisp**
Fixing the failures identified by gtest.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@MattBBaker @yosefe please take a look. @MattBBaker I hope it does not cause disaster in your tree.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/167/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/730/ for details.

**Comment by MattBBaker** [comment]
Looks good.
+1

**Comment by shamisp** [comment]
The mellanox failure can't be related to our code since it does not build ugni device.

**Comment by yosefe** [comment]
@shamisp 2 comments:
1. CodeStyle - `if` statement should be surrounded by brackets
2. Maybe should put that 'if' in an inline function like `uct_ugni_invoke_callback(fma)`

**Pull request merged**
