### PR TITLE
UCT/API:  Add API for GET SHORT.

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6569/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6572/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
why ?

**Comment by bureddy** [comment]
used  put_short for mem type(CUDA)  staging protocols at receiver side to transfer data from bounce buffer to target GPU buffer (https://github.com/openucx/ucx/blob/master/src/ucp/dt/dt.c#L97).  similarly, wanted to add new protocols which require staging at sender side to transfer from source GPU buffer to bounce buffer using get_short.

**Comment by shamisp** [comment]
Got it. Next time please document your changes as part of PR and commit message. @gmegan can you second the API change. thanks

**Comment by shamisp** [comment]
👍

**Comment by gmegan** [comment]
+1

**Pull request merged**
