### PR TITLE
UCT/DOC: Fix documentation of uct_worker_create() - async cannot be NULL

### LINKED ISSUE #2382: uct_iface_open crash
I am seeing a crash:

```
2  0x000000000fe9c921 in uct_worker_progress_add_safe (worker=0x788aeb0, cb=0xfea4830 <uct_ugni_progress>, 
    arg=0x7886fe0, prog=0x7887488) at base/uct_worker.c:59

(gdb) f 2
#2  0x000000000fe9c921 in uct_worker_progress_add_safe (worker=0x788aeb0, cb=0xfea4830 <uct_ugni_progress>, 
    arg=0x7886fe0, prog=0x7887488) at base/uct_worker.c:59
59	    UCS_ASYNC_BLOCK(worker->async);
(gdb) p worker
$1 = (uct_priv_worker_t *) 0x788aeb0
(gdb) p worker->async
$2 = (ucs_async_context_t *) 0x0
```

The worker was created with a NULL async context which is fine according to the documentation:

```c
/**
 * @ingroup UCT_CONTEXT
 * @brief Create a worker object.
 *
 *  The worker represents a progress engine. Multiple progress engines can be
 * created in an application, for example to be used by multiple threads.
 *  Transports can allocate separate communication resources for every worker,
 * so that every worker can be progressed independently of others.
 *
 * @param [in]  async         Context for async event handlers.
  *                            Can be NULL, which means that event handlers will
 *                             not have particular context.
 * @param [in]  thread_mode   Thread access mode to the worker and all interfaces
 *                             and endpoints associated with it.
 * @param [out] worker_p      Filled with a pointer to the worker object.
 */
ucs_status_t uct_worker_create(ucs_async_context_t *async,
                               ucs_thread_mode_t thread_mode,
                               uct_worker_h *worker_p);
```

Is this crash expected or a bug?

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2382

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp @gmegan @bbenton pls take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6492/ for details (Mellanox internal link).

**Comment by hjelmn** [comment]
It might be worth pointing the user @ the ```ucs_async_context_create()``` function in the documentation.

**Comment by hjelmn** [comment]
Nope, at least  not in the ugni path. I just get a SEGV.

**Comment by shamisp** [comment]
Well, documentation update is good but IMHO this is something that we have to check and return an error.

**Comment by shamisp** [comment]
IMHO this is something that should be handled in in the common code.

**Comment by hjelmn** [comment]
@shamisp I agree.

**Comment by yosefe** [comment]
@shamisp @hjelmn added check

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6516/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls take a look

**Comment by shamisp** [comment]
👍

**Pull request merged**
