### PR TITLE
TEST/PENDING: Fix fairness test to retry adding to pending.

### LINKED ISSUE #875: Failure in ud fairness test
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node/1478/consoleFull
```
01:11:56 [ RUN      ] ud/test_uct_pending.pending_fairness/1
01:11:56 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_pending.cc:295: Failure
01:11:56 Error: Device is busy
01:11:56 [1467929516.410185] [hpc-test-node:4260 :5]          ud_ep.c:974  UCX  WARN  ep=0x31e5400 cancelling user pending request 0x2ed48d8
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #875

### CODE REVIEW

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by alex-mikheev** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1491/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2141/ for details.

**Comment by yosefe** [comment]
the failure is unrelated - in the flush test

**Pull request merged**
