### PR TITLE
TEST/EXAMPLES: Add uct_hello_world command example in usage.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
## What

As I proposed #3823, add `Example` part in `uct_hello_world` command usage

## Why ?

This example may help for beginners.

### CODE REVIEW

**Comment by dmitrygladkov** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10998/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/4a8f9e9cb8646cc1462faee443e04550c7740870/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/825ee36c74723ca1ca73a907c407b84663bc5254/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/c59316f630c83dc938d0f4c96d07eef5e3140e1b/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/2ce8318ac5b1f97a39bb3a0179ceac58d6b6f4d1/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/dcce69189c44f4cf1d1ad848aca0da47e85540fb/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/f70e8ed0165844a074e3fb29085ab0a477ee99c5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/fc85cc7a77e93703f0d89d2236a7499627147622/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/2b31489d70eca461fc09223f509d06fd7c98bb03/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/2cf35b0fae8afaeb709d5b0d8dbbc3c3659894f6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/1b11a7bf9afa5c117fe5ad0d8f3ff66aa671b5a6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/86306661eb8de37ccb0d086d109945597813489d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/51fb74acf71b47227448e15e492a665a64725b8f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/0c88c28f9a3a68c77fd918cf0707c19e01db1607/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/4df4832d0e344b90e06477a6660fc631fea8c33e/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/2e88ab31f0b8e80d79d6695fd36cbfce1fb16891/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/439a8d7fc09e0c5198ab87bef364234f4642c0ed/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/a649ca82687c4c1ba06f607ed6f888ce27361f5b/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/d648d21c4c0ea8f40418763e3dafeeff0c101110/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/8e8fad3c836b1d22ceef924be3547fd0a6054bee/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/be1a42f7e743f99e987d087e7f00e9f379da9be4/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/d0056cf2a54ce7bbb4d71a78c2ef38b32aecbd69/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/2d027a81a76bcb255a3b51397b6d7e9d4efcc608/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/06929a601565d8c6814ab1cb28ebbaea29cbb3b6/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/053dcfe08408da4476bc7d03eb2db52fef1d73d7/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/6dbc88915b07bd5ee7a0ccc77ef001ebe9be0427/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/7b0added252946b8685608019856f97fb4ee4cfb/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/65fbc8ce26e658b914a6f7b3ff894d12b8092824/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/27e5b6fa32f2c98a20ab8d4c444701fd001f00d5/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/1ef7308d5add21a5c78e6a15da6e95a6de07134d/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/7e94435dc0b24954e3a79964650273a7f0479805/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/701af792656eb6c315bacefef5a27f4b8b9433b0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/627047ec2a61adf4426bb88de2bd1325d6b1909e/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/e1809d3d4763709c31a6310703a10b789801d0ad/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/a3481e47f17ede3f8e9efadeb282d5d3c5c69113/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/7fc661739e01e355749be71bded41604befd9547/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/3bba3de6800902e1f52d2ffa54d0d9f1bf7b344e/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36f30420e033a94a76a0f7d289cf27fc/raw/8bbbe93165a87eb189d278ca4a69f84f93557501/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
