### PR TITLE
UCP/RNDV: fix for hang on osu collective tests with multi-rail

### PR DESCRIPTION
**Pull request by hoopoepg**
- added lock on lane when called from pending

fixes https://github.com/openucx/ucx/issues/2301

### CODE REVIEW

**Comment by hoopoepg** [comment]
would be great to add this commit to v1.3 branch

**Comment by yosefe** [comment]
@hoopoepg how does it fix the problem?

**Comment by hoopoepg** [comment]
it locks for pending lane.
I tried to apply same logic as in b/z-copy - it failed on assert in UCT or arbiter

**Comment by yosefe** [comment]
seems like a workaround, need to find the root cause

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6259/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@hoopoepg can we close this one?

**Comment by hoopoepg** [comment]
I was going to update it by port from v1.3
Do you think new PR is more preferable?

**Comment by yosefe** [comment]
it's ok either way

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6268/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6271/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe squashed

**Pull request merged**
