### PR TITLE
UCP/RNDV/MLANE: disable mlane on self/shared AM TL - v1.4

### PR DESCRIPTION
**Pull request by hoopoepg**
picked up from https://github.com/openucx/ucx/pull/2669, commit 9cc678efc172e900fc4a7f037a7da642438d3850

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7164/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7165/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7166/ for details (Mellanox internal link).

**Pull request merged**
