### PR TITLE
UCT/TCP: Fix possible memory leak

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Move check for thread mode above to avoid possible memory leaks

## Why ?

Fix memory leaks for iface resources

## How ?

Move at the beginning of the function

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11710/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/50e3e073a3a250f1022024e9afea3aa041ca8ba8/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/317f43e8b5420760bb4bb9b92bbc4c00b54d483f/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/ed62bbb93ea5b73fca5b016a082c2960f207102f/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/684dcb950c16f5b7ca69e4f799461f64fee7efc5/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/a034257c7872969eb0b113f919a956365dfced26/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/e3bae2cea92fae2ad1afb5772a5eb67e9eb87984/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/90475d8ac5f9d90fb181a860805a5facd493d4ed/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/86f62276642f931910aa7cc08c20c1b5bfb6c995/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/45571c38f76d959725c69b2b693be3bfacb6aacc/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/67c8ddb977a6e69a40b95a1507bc43b6b2762554/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/de8e1e37597dd31ff573c04c4401e28896716a69/hpc-test-node-legacy_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/0d87363fa7c751371cc2d9f705dc65cb7ef84637/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/be0b47b6f5f07b07456d35a61663cb6052b6189e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/c185ba441484894345c3f127675dbbaa2b4fa0b4/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/6d6fd67722da04eaefcb4c20ad6ddb873ccc1f55/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/d2df459f941aa284a3db183fa003e2f5fb8d6c95/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/e1543463d6e564b1fed2ef97c1e498112de72c85/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/953be6c0b230573eb0d71ad47a52fee2e72c74e6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/daf6e7dde801b11f4dfc6b3475383fde51b91898/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/e8724f116248532b3be3feebabd1163845d7ec7d/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/411e2de07b4fca42cef0b29dc849e57180551107/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/033d4d779f790bda2685aea6d5058645ad72f4df/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/242b44c87e95761503f5b6c76c58d9ba041de33f/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/68b947941db4c5938d03429efd97edcb8eb84168/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/ea80e156eac03312cc499d7051ea27047d5e4dad/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/740d6de376d20108bbef5ea5223868df19b7c038/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/a396325e14bf8b7b6b01c855b2bfd9e03ebedd5d/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/76c83c87a2343dbffa5fbd2ff2ab9d62491c595e/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e17e43ca561d89d53d8f89cd263aaeb1/raw/1f2dcbc5a0220f375bbb6a2ba6da964e4d6bbaac/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11713/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/043d27f85469df7f8ec4c8ad2a0aee76b3aa8bdf/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/f48f35142741b2b0b59f17bc822ab75e06a1e7bb/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/b9d67c150a038f364280488a555e3c8e805c81c6/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/4ca8762c529e9b949f38205f3ef992df2147863d/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/4eb21092dd01a23233c71cd0d8a1c646b50845ed/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/631d8e46e91066683933b8d67bb2cd041b7e82c0/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/388c690a605c64488904f197886dd2a11fae80f0/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/e9d7f05f509985b31892b37b18b0182c7b2203e9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/efd73c4b623cb5e03a661996a1a5d741aa9cc288/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/a42176504844f4ed151311241d0d69873948e7c6/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/79e7b40f139b45b0d0ee789225af550823644798/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/148bb1f99dd5d14fc374dde270e0d19f688922a8/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/79fe6dba734ec738f4e20417a8f93aae74140c3a/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/eef8bc26cbb6ffe3da66d5c5b428d0cd875718e2/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/393d31126dc70847ba8502da18ccf3987db70017/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/3aa91173633e006de7aaed81437bd3d9ae28de18/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/2c94670ad6a49bf57883a5e761cdc13d697eef16/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/c5ac4fb6d1c59844cc10b4fcc37644e86142f404/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/5e14962d786bc863de72c5dede5b19b52dc30c31/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/1a10fd16dcc2fe82ebf20a63d4071ac4593e8579/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/a77e70f60b07370b61c85fb8f6a5a4d2515102ce/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/8ba19b47823ad9b46c2b01f25296965be36a4a15/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/5b866ca3b11470666c6e8ea138e3941e7e896965/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/7c7cc8b0ee8c8194a75c1184a4f17c73751732a0/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/334463b5a19bc649bfa88e14da01d4812aadaab2/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/1235896898aa30b8bc754d155d223be8f69e9a8e/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/c94f93e46c59b111ea5c115ab6d4248a69426731/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/0e22fa12f996186c413623357e9818d4b63e204d/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ccf9e1efc0f1a422c7724182a965dfa2/raw/ea41611b6f0f589845b09e59bd47619a2a3e4231/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11715/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/a85683d248a0fc912cd25671523caa405c6e50b9/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/3d0a53f12df8b192d9803b68e4939af8cdca24c4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/146f6c5488f513ab396f8f384f04afd03b362e9c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/8b6929bd3672fe11d30bd2882461164b84e3bc36/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/f798c0fef8b7f8f7022827c1b93c93b25a25b79f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/c42ef95e65a418494eac7052dde1e8123f134f3c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/22256b53e929a68fa861128146ebbffb66d527a2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/e0ae9a1c496163d9a3374f724777b2641af6455c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/edc660571922c81f84e5dda5d6a94dbb0e8af87b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/fe6a5bea299828983da0fbcd620427d47ca99119/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/4b2fd96b0f69e5bdea791d29b7b5c24d5954fe7d/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/8781b7786b8fe1fd132bc6dcca66084ee9284065/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/4639fcd8f3251a17da7cf7fc26b7259ad48e7a2d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/282d305b8f30cae0e3316565cbdf7c77bcced604/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/0425ba173893e25030346a9925d97c1dc1d5eb3a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/fc45d6375c049a628cff4bfd7b93c776670c7945/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/b856061c5b6686810d8a2d693d0bbf2c6f474315/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/3a60a0aafedc8b4e298ccac0177e823e118e3965/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/12b7d5eaeb3a58983d55643690091bc615d6c2b4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/6fd101c3be77a279868b829299f0c8bdeb5e1b53/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/6b7c7205b40a1883cee45a314644df70a49d2c5d/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/3036e188c64b774dd126c8de6c8ca37c9965a875/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/1853bfeea2547b577fa3f78b0aa4f7110a1c1f67/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/433a448b926be0f04a13c27cde9159b9a13654da/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/7ee8b53a0b2d4589ec102560258e61d6638d3338/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/6ff8ec64bb0b008b2b5b05f87fec897f037c5ba2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/a42c2406e2a681b149e4ed5abfbbe31e318dd2bf/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/312202df90134ac4e1d2334f32a8ff4fa3cc0b06/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/356713a1a9142c0a5110e24d511a4a55/raw/bf194a74eabd37c2131a1a9cc8985e1251842ec7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:bgate:retest

**Comment by dmitrygx** [comment]
> is there a real leak here? because UCS_CLASS_INIT() macro already makes sure parent destructors are called if init function fails

I didn't know about this fact
If it so, should we ensure that all fields are set to their initial value before any allocs/inits/etc done in the code to avoid freeing/closing/etc those fields?
e.g.:
```
INIT_FUNC() {
    self->fd = -1;

    self->mem = malloc(sizeof(*self->mem));
    if (self->mem == NULL) {
        return UCS_ERR_NO_MEMORY;
    }
}

CLEANUP_FUNC() {
    if (self->fd != -1) {
        close(self->fd);
    }
}
```

> why not just change 'return' to 'goto err_cleanup_tx_mpool'?

I think it's better to have it above, since no other inits/allocs/etc are needed to check it

**Comment by yosefe** [comment]
@dmitrygx it calls **parent** destructors, not the one of the failed ini

**Comment by dmitrygx** [comment]
> it calls **parent** destructors, not the one of the failed init

@yosefe yes, I know this fact
so, `tx_mpool` and `rx_mpool` are leaked if we just return error w/o calling mpool cleanup functions

**Comment by dmitrygx** [comment]
> merging this since i now see we check invalid params before calling parent ctor

@yosefe thank you!

**Pull request merged**
