### PR TITLE
UCP/CORE: Set EP_FAILED in cleanup_lanes + don't allocate local req ID for memtype EP

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Set `EP_FAILED` in cleanup_lanes + don't allocate local req ID for memtype EP

## Why ?

Local request ID is not needed for memory type EP.
`EP_FAILED` has to be set to keep EP reference counter updated and to pass assertion in EP destroy.

## How ?

Don't set local req ID for EP if MEMTYPE flag was specified.
Set EP_FAILED flag for `cleanup_lanes()` as we do for `discard_lanes()`.

### CODE REVIEW

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?
failure is unrelated, will restart it

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
failure seems related to destroy ep:
```
Connection timed out - abort testing
[sputnik4:14484:0:14484] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
==== backtrace (tid:  14484) ====
 0 0x00000000000e2d47 __GI___sched_yield()  :0
 1 0x00000000008fa864 ucp_test::progress()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:156
 2 0x00000000008fa864 ucp_test_base::entity::close_all_eps()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:746
 3 0x00000000008fad0d ucp_test::disconnect()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:197
 4 0x00000000008fad0d ucp_test_base::entity::get_num_workers()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:874
 5 0x00000000008fad0d ucp_test::disconnect()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:187
 6 0x00000000008fad68 ucp_test::cleanup()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:78
 7 0x00000000005e0e90 ucs::test_base::TearDownProxy()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:333
 8 0x00000000005c4c69 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3562
 9 0x00000000005b8e7c testing::Test::Run()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3643
10 0x00000000005b8f85 testing::TestInfo::Run()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3812
11 0x00000000005b90ef testing::TestCase::Run()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3930
12 0x00000000005bd89d testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5808
13 0x00000000005bdb80 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5725
14 0x00000000005525dd RUN_ALL_TESTS()  /scrap/azure/agent-01/AZ
```

**Comment by dmitrygx** [comment]
> failure seems related to destroy ep:

unfortunately, it also hangs on master

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@brminich @yosefe that was a sporadic issue - probably configuration issue, I didn't manage to reproduce the problem on `sputnik4` with `taskset -c 0,1` and >=50k repetitions.
can we merge the PR?

**Pull request merged**
