### PR TITLE
UCT/ROCM: add rocm_ipc TL

### PR DESCRIPTION
**Pull request by yuq**
Corespond to cuda_ipc.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9169/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9178/ for details (Mellanox internal link).

**Comment by yuq** [comment]
@yosefe thanks, you can merge it now.

**Comment by yosefe** [comment]
done. i'll do the same for all PRs which are ROCm-only code.

**Pull request merged**
