### PR TITLE
UCS/LOG: Rename get_thread_num() to ucs_log_get_thread_num().

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1977/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1352/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask can you pls review?

**Comment by alinask** [comment]
:+1:

**Pull request merged**
