### PR TITLE
AZP: run tests on HWI

### PR DESCRIPTION
**Pull request by amaslenn**
## What
Run "hwi" testing in AZP

## Why ?
Migrate from Jenkins to Azure.

### CODE REVIEW

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
@Artemy-Mellanox there are some failures https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/5559/logs/120, are we surely setting cqe_size=64 for all cases on this platform?

**Comment by amaslenn** [comment]
@yosefe could you please take a look?
```sh
[     INFO ] memory_type:host 33 [swx-rdmz-ucx-arm-hwi:13994:0:13994]       rc_ep.h:403  Assertion `!(op->flags & UCT_RC_IFACE_SEND_OP_FLAG_ZCOPY)' failed
==== backtrace (tid:  13994) ====
=================================
```

**Comment by yosefe** [comment]
retesting after merged #5279

**Comment by yosefe** [comment]
retesting after merging #5282

**Pull request merged**
