### PR TITLE
BUILD: Enable CPU optimizations by default.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1351/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1976/ for details.

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
Do we have some special option : --distro-build ?

**Comment by yosefe** [comment]
No, do we need anything except --disable-optimizations?
We can also add contrib/configure-dist script

**Comment by shamisp** [comment]
What does it disable ? We need a easy way for distros to disable HW platform specific optimizations.

**Comment by yosefe** [comment]
it disables all platform specific optimizations (currently, it avoids passing any special sse/avx flags)

**Comment by shamisp** [comment]
ok
👍

**Pull request merged**
