### PR TITLE
Fixes for races in async infra

### LINKED ISSUE #1229: segfault in thread/test_async_timer_mt.multithread/0
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/655/label=master/console
```
12:47:43 [----------] 1 test from thread/test_async_timer_mt
12:47:43 [ RUN      ] thread/test_async_timer_mt.multithread/0
12:47:43 [jenkins03:7099 :10] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
12:47:43 make: *** [test] Segmentation fault
12:47:43 make: Leaving directory `/scrap/jenkins/jobs/gh-ucx-pr__NEW/workspace-5/label/master/build-test/test/gtest'
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1229 and recent failures in jenkins perftest
@shssf

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3099/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2613/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/659/ for details.

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/667/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3119/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3127/ for details.

**Pull request merged**
