### PR TITLE
Improve IB error reporting

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8187/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@evgeny-leksikov @brminich pls take a look

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8198/ for details (Mellanox internal link).

**Pull request merged**
