### PR TITLE
UCP/MEMTYPE: Fix zcopy setting with non host memory

### PR DESCRIPTION
**Pull request by bureddy**
- regression from recent ucp_tag_send_nbr changes

### CODE REVIEW

**Comment by yosefe** [comment]
@bureddy do we have unit test (gtest) which should have caught this?

**Comment by bureddy** [comment]
@yosefe we do not have ucp gtest for mem type yet. will look into it.
For now, I will add perftest with cuda buffers in separate PR. this would have catch this error

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5984/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy pls also make sure the perftest actually runs in jenkins. could be either from gtest (test_ucp_perf/test_uct_perf) or as part of the separate perftest run.

**Pull request merged**
