### PR TITLE
UCT/ROCM : Fix a build issue

### PR DESCRIPTION
**Pull request by khamidouche**
Just a small changes to fix a build issue with latest ROCM releases

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by miked-mellanox** [comment]
Ok to test

**Comment by evgeny-leksikov** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5032/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5033/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5040/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Pull request merged**
