### PR TITLE
IB/DC/TEST: Fix compilation with gcc 7.1

### LINKED ISSUE #1638: git master HEAD: compile error with gcc 7.1.0
```
make[2]: Entering directory '/home/tc/src/ucx/master/build/src/uct'
  CC       ib/base/libuct_la-ib_md.lo
../../../source/src/uct/ib/base/ib_md.c: In function ‘uct_ib_query_md_resources’:
../../../source/src/uct/ib/base/ib_md.c:960:44: error: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size 13 [-Werror=format-truncation=]
     snprintf(md_name, UCT_MD_NAME_MAX, "%s/%s", UCT_IB_MD_PREFIX, device->name);
                                            ^~
../../../source/src/uct/ib/base/ib_md.c:960:5: note: ‘snprintf’ output between 4 and 67 bytes into a destination of size 16
     snprintf(md_name, UCT_MD_NAME_MAX, "%s/%s", UCT_IB_MD_PREFIX, device->name);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../source/src/uct/ib/base/ib_md.c: In function ‘uct_ib_md_open’:
../../../source/src/uct/ib/base/ib_md.c:960:44: error: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size 13 [-Werror=format-truncation=]
     snprintf(md_name, UCT_MD_NAME_MAX, "%s/%s", UCT_IB_MD_PREFIX, device->name);
                                            ^~
../../../source/src/uct/ib/base/ib_md.c:960:5: note: ‘snprintf’ output between 4 and 67 bytes into a destination of size 16
     snprintf(md_name, UCT_MD_NAME_MAX, "%s/%s", UCT_IB_MD_PREFIX, device->name);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1638

### CODE REVIEW

**Comment by shamisp** [comment]
@tonycurtis please take a look

**Comment by tonycurtis** [comment]
snprintf/strncat change looks good to me

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3969/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3978/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3980/ for details (Mellanox internal link).

**Pull request merged**
