### PR TITLE
GTEST: Increase range for perf atomic add rate

### PR DESCRIPTION
**Pull request by brminich**
## What
Increase upper bound for atomic add rate in ucp_perf_envelope test.

## Why ?
The test may fail during high/low load on the server, like [here](http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7829/label=hpc-test-node3,worker=0/consoleFull#212814535244550c5d-247a-4f9d-bad5-5b93d2b6e2ac)
```
15:38:33 [     INFO ]            atomic add rate : 0.427 Mpps
15:38:40 [     INFO ]            atomic add rate : 0.440 Mpps (attempt 1)
15:38:46 [     INFO ]            atomic add rate : 0.338 Mpps (attempt 2)
15:38:51 [     INFO ]            atomic add rate : 0.414 Mpps (attempt 3)
15:38:57 [     INFO ]            atomic add rate : 0.392 Mpps (attempt 4)
15:39:04 [     INFO ]            atomic add rate : 0.418 Mpps (attempt 5)
15:39:10 [     INFO ]            atomic add rate : 0.420 Mpps (attempt 6)
15:39:16 [     INFO ]            atomic add rate : 0.382 Mpps (attempt 7)
15:39:22 [     INFO ]            atomic add rate : 0.445 Mpps (attempt 8)
15:39:28 [     INFO ]            atomic add rate : 0.476 Mpps (attempt 9)
15:39:35 [     INFO ]            atomic add rate : 0.425 Mpps (attempt 10)
15:39:37 /scrap/jenkins/workspace/hpc-ucx-pr-5/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/test_perf.cc:304: Failure
15:39:37 Failed
15:39:37 Invalid atomic add rate performance, expected: 0.5..100
```

### CODE REVIEW

**Comment by hoopoepg** [comment]
the really strange test... I seen errors out-of-range, but lower of min value...

**Comment by brminich** [comment]
Typically we change threshold when we see that it's too restrictive (have a particular failure).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7831/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@brminich could you reduce minimal value from 0.5 to 0.125? it seems in emulation mode it may fail too

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by brminich** [comment]
@hoopoepg, done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7837/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7840/ for details (Mellanox internal link).

**Pull request merged**
