### PR TITLE
UCT/MEM: Don't print error message if madvise(HUGEPAGE) fails.

### LINKED ISSUE #2084: madvise failure on gtest
There are failures that happen when running gtest with --gtest_filter=\*ucp\*. 
This seems to reproduce only when compiling UCX with --enable-debug (and configure-debug).
After a while, many tests start failing with the same error. For example:
```
[ RUN      ] dc/test_ucp_tag_cancel.cancel_exp/0
[1513499907.466875] [vegas07:32639:0]        uct_mem.c:155  UCX  ERROR madvise failure status (-1) address(0x5000000) len(2097152): Invalid argument
[1513499907.498387] [vegas07:32639:0]        uct_mem.c:155  UCX  ERROR madvise failure status (-1) address(0x5000000) len(2097152): Invalid argument
common/test.cc:238: Failure
Failed
Got 2 errors during the test
[  FAILED  ] dc/test_ucp_tag_cancel.cancel_exp/0, where GetParam() = \dc (206 ms)
```

Many of the following tests will fail with the same error.
Running each test separately doesn't reproduce the failure.
Master branch (96a17136020f5a9801c7fbb5f53c86500ea44ea1)

Full list of failed tests:
```
[  FAILED  ] 75 tests, listed below:
[  FAILED  ] dc/test_ucp_tag_cancel.cancel_exp/0, where GetParam() = \dc
[  FAILED  ] shm/test_ucp_tag_cancel.cancel_exp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] dc/test_ucp_tag_match.send_recv_unexp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_unexp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_unexp_rqfree/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_unexp_rqfree/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_exp_medium/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_exp_medium/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send2_nb_recv_exp_medium/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send2_nb_recv_exp_medium/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send2_nb_recv_medium_wildcard/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send2_nb_recv_medium_wildcard/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_nb_partial_exp_medium/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_nb_partial_exp_medium/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_nb_recv_unexp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_nb_recv_unexp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_cb_release/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_cb_release/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_truncated/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_truncated/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_nb_exp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_recv_nb_exp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_nb_multiple_recv_unexp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.send_nb_multiple_recv_unexp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.sync_send_unexp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.sync_send_unexp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.sync_send_unexp_rndv/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.sync_send_unexp_rndv/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_req_exp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_req_exp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_rts_unexp/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_rts_unexp/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_truncated/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_truncated/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_req_exp_auto_thresh/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_match.rndv_req_exp_auto_thresh/1, where GetParam() = \dc
[  FAILED  ] shm/test_ucp_tag_match.send_recv_unexp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_unexp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_unexp_rqfree/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_unexp_rqfree/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_exp_medium/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_exp_medium/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send2_nb_recv_exp_medium/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send2_nb_recv_exp_medium/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send2_nb_recv_medium_wildcard/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send2_nb_recv_medium_wildcard/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_nb_partial_exp_medium/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_nb_partial_exp_medium/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_nb_recv_unexp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_nb_recv_unexp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_cb_release/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_cb_release/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_truncated/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_truncated/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_nb_exp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_recv_nb_exp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_nb_multiple_recv_unexp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.send_nb_multiple_recv_unexp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.sync_send_unexp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.sync_send_unexp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.sync_send_unexp_rndv/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.sync_send_unexp_rndv/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_req_exp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_req_exp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_rts_unexp/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_rts_unexp/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_truncated/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_truncated/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_req_exp_auto_thresh/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] shm/test_ucp_tag_match.rndv_req_exp_auto_thresh/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib
[  FAILED  ] dc/test_ucp_tag_mt.send_recv/0, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_mt.send_recv/1, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_mt.send_recv/2, where GetParam() = \dc
[  FAILED  ] dc/test_ucp_tag_mt.send_recv/3, where GetParam() = \dc
[  FAILED  ] shm/test_ucp_tag_mt.send_recv/0, where GetParam() = \mm,\knem,\cma,\xpmem,ib
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2084

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5568/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5572/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls take a look

**Comment by alinask** [comment]
@yosefe wasn't it already falling back to the next allocation method? the change in this pr is that it wont print an error in case of a failure right?

**Comment by yosefe** [comment]
it was falling back if mmap() failed but not if madvise failed. after this pr, there will be an error only if **all** allocation methods have failed (which is unlikely)

**Comment by alinask** [comment]
but there is a 'break' at the end of every case. what am i missing here?

**Comment by hoopoepg** [comment]
it breaks switch/case statement, but outer loop is continued to enumerate allocation methods

**Comment by hoopoepg** [comment]
> it was falling back if mmap() failed but not if madvise failed. after this pr, there will be an error only if all allocation methods have failed (which is unlikely)

as I can see it will switch to next enumerated method (mmap, heap, etc what is set in configuration)... original code made the same thing (except error reporting instead of trace), isn't it?

**Comment by yosefe** [comment]
@hoopoepg right, actually this PR is only changing the error message to debug

**Comment by alinask** [comment]
@yosefe this is exactly what i meant in my first comment. what did you mean by "it was falling back if mmap() failed but not if madvise failed" then?

**Comment by yosefe** [comment]
@alinask @hoopoepg my comment https://github.com/openucx/ucx/pull/2096#issuecomment-353288436 is wrong

**Pull request merged**
