### PR TITLE
TOOLS/PROFILE: Support custom pager

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12806/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 17 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/f24d125142ce65e9807c45deb3e8c3095d21f83b/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/8c639cb96782dd2d06586be38d119ddc8b1455e8/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/bf395af877bc3a30170665f24e96f20be729f6d4/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/237a8a424c324bf7c1bb1923ba81de0b27206959/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/707af485435d593943b7dd32bc1de8bb1f6ee69f/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/9be243d8e978288be3db53aaa54de346069976d1/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/01402f14ddf6d3a2f2db9f12dcb410041214ada4/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/ed15e644b944e9f406c4778d3dce5f16050e48a0/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/e8a304774cacf3f9381f153ccc2546cfa8b7eb98/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/562cdd39bf1e7d15caf1c129ed95252ba03f1aa6/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/4912aad09d229e3ff5acdc63d0f3efdfdaa917ad/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/bbc016012d405eab550a6b265ca55aea9dc3e272/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/fd56b25cf8f484df227240e1b72a0ec877d91be2/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/ffbfb943d4fde671c4ce137f46450cfebd720af4/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/e9de36154e5450747a9148bc6ca04e7624ed5c8c/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/507c0b9160ba8f03ad9313c8560478575d2a9a4e/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/e60bdd77d8d11c71954514941b9fc0bfe3ceb057/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/b324c2bc581dc963b7205d44a6c3cb14348adc88/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/0707d3974d12efc9f28b1bfe01aa2d2242702e9b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/b232336a2f8ec2abe54fed66f5b39be205b51ef8/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/8dd0aa36c74f04191f3a310ca770bf9392124a27/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/650a58bb9f01c170d47cab658724aed1bd085e67/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/6521185deb96c7d304152afa86272d8ca2b72a17/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/48527d81edc9a4c4a02c74eb94880cf71bb9cca5/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/11e55fc589abd04304bfa2073b421e8fd0edc334/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/56b54c67dfaca4926d02539a7ff379397585909e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/ed3b8e11cf910bc85fce690147a910654c66b1bd/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/5841b28238a0c895089cc8b7264a34380cdfd862/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7581b38e2e3cedec64349a99e4c5593f/raw/aac8d68b36bb2bc3f5b81011cf7237dfcc386174/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12824/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 9 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/cf00d303fa1a3c19090f2c966290942421b0aaf3/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/373480a0426146776804ac0a20764c8f7bdd5bbd/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/3db320e67dd31cc5ab7be3e7edc8d44c0502ee9b/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/3a793ae747adeeca39d40e9bc2333a8393946873/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/8d30b180d4f93ffcfb839cb8b960eaf97b472e65/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/f4a3c414f500c6cf44cdb941f0bd24af57ac886b/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/2206f93b2c8e19ac670bbdaa9b7f0d3df2145bce/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/6547acf11eab920f43003fbd5039ea6307df8bcd/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/0b098145bce6e817eced0429642e1f05a890860d/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/2c044c57d1a14cff0cafd00094725e509aa5c616/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/44c9cddb704458c75c09d92a6837c4f2ddfa8391/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/638ce51de52d39bd35fc5af4dd7a6277676f3be4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/59681f78a9cc64b7e283c23d0fa6f0e49287ea35/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/0cd8645679e4c5f846d9df94529ac694496d5f3a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/a4ace07a3bf39692b515e3ff7239e2a98c59078c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/e074bf9ab24eea0b9039bddd1f7b8c10e7e25133/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/681fea0af5c42ab56b569421835ff66a464b265b/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/627ad4deb9c4e1f467bd2fb4b3a80a597a930ef6/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/6279a59521704cd85eaf8443af23b7eef4d4d101/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/ff506921b8f8961885f58d2d9372e0fbbcb42adf/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/c58ee22ffc01304cd63d2f7ebe69353e29505e39/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/74629b110a80b712ce32f9b0b173388a091ddf81/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/f09c8615457473ab7d2cc257494dda63ce5f3c60/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/ed14b7c3a1731561364db39e62f9bf294e58d458/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/b22277c064d46947b39fbee1f87830b9d4fa07d0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/6d7d4406b292ecc9845cc45d958de46a50853ab0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/25bb07cfc904e3f87caafd67f421e3a18ba09a2e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/de76af011d463a685172b5564bbbbda8a57f37df/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cb84d14e9ffc02cd1d84e3e53eba9f6f/raw/20e6cbb7551a6a46ce2cb1adb6982a10f58c0ba5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12834/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/33e0f8bb14193d316f42afc2f3c7c0bee58a85c4/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/ecb60b322978c37f16f1d352f4a16fc64f9e6b98/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/e2f049777d940c12d2ffbae8dcc281ec4df33184/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/d1da911b0d1759d9bf5f0c9045ec48bc7b88f85e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/1ad06410da211a570ab79c89dc07e717fda9af90/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/6397811cd195ca45657b6295046d89d9426d6b25/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/4dd86127dd19843fa9b13361525c34f4c0db8dab/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/77ce3e33e66841006f5adbc1151a0a961029b200/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/df3364e398bbaa073843a8572b6ac320e02e6fa2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/0ea50049be2b50fe19407c20985c1153f13dee27/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/59f777b2131e6b904f47f5e98ad50d085ce7cd84/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/9608b4f605c1fb27bc989d495f1659991757d2ec/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/a5275007b4d0c2c6648eb554ea0b33094fd66748/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/a054b7b6ac729274cc3c0410672c52c34db2250b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/7dcf2009baa64f792aca1fb3baa25566b30eeb63/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/394145b27a3d5ea2243523375c15b0e3d33f212c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/3fe028817afeb7514adb568135f9ebf306d57d7a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/a941444554cc6b5474e4dbcd8b42fe51aca9cdbd/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/4a0fc52d6aff39bbac5a5a5f46409f99a6e94a3b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/71567c1f3d5a6b8ec4bcad8f06d9f7f92a6b9e5f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/60d632d80e926482cb15502dfd5f32df5e9da761/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/92df01429ef2b3bd847a5db5a73c06bc3383801f/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/7aa069880c9c1990d6d69d61f56d058370b5c9ae/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/3af5733b46402a235f25aadeb09f04199a7a50b0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/8c21b7630adab526b0f7a1d0aec84cb5077e7e58/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/0c8fc8e149a70fbdd66d3e380193b04811a87ce9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/a65975e4c542b6edc7c3f67a9686f575facad6d4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/aca094ff475d57fb07b268ff427517c7752897ee/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4650aad9a9d4878b45cdb0e765277813/raw/97c28880c354d0d7645848ed60d2e4f3e5935b5d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
