### PR TITLE
IB/DC/TEST: Fix compilation with gcc 7.1

### PR DESCRIPTION
**Pull request by alinask**
(cherry picked from commit 71dfa34ef7b9ac7abeb7a282b9aec9a7c780c3ee)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4323/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe please review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4325/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4328/ for details (Mellanox internal link).

**Comment by alinask** [comment]
The failure in jenkins is https://github.com/openucx/ucx/issues/1770

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4335/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4350/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4354/ for details (Mellanox internal link).

**Pull request merged**
