### PR TITLE
DOCS: Add basic read-the-docs support

### PR DESCRIPTION
**Pull request by yosefe**
## What
Add Read-the-docs support to UCX.
See https://openucx.readthedocs.io/en/topic-read-the-docs/index.html for look&feel

## Why ?
Improving UCX documentation for users as discussed in UCX f2f meeting

### CODE REVIEW

**Comment by shamisp** [comment]
Yossi, is the way to preview/render the api changes before the merge ? What
is the workflow for somebody to upstream and demonstrate API change. This
is generic question, not just in context of this particular PR.

**Comment by yosefe** [comment]
@shamisp we can ask it explicitly from RTD (after this PR is merged), see : https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by shamisp** [comment]
Nice!

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/4b9534840c70ae97ef863fa74990a3d32e5e7410/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/64682a53234ec9690f504a895fe466c638cdddc6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/b58f3e6c59039f4d8c83872d2ae921fcfe08f241/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/f703ab688f45b0de618464646028b1fe01938d50/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/89f421d26035aaccb0c046ac3db32281f5215b8a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/fa9a35d2e62e85460458a62330a0413d145d2fdb/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/bc06b28e4f120bd73f9b0230e3ef383df81c1967/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/1fe4183fece45634e001c7553275255fbcb6ad13/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/a09875e3dd7bee04f9ffc0ef8ef5bc4f2cc55a5f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/4a22c71a8fba14764a7b1ffac275e4cede50156e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/2e61d08b1d18f6180dc13d8f5929125873876531/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/91d5325aaecda2afa92850311fbe63f08912dad5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/569691549f1081187a46e3f16f1c1b5d1516d3cd/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/09828a26a7f633383d99e89e853406e4a09dba2c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/31e20e87d09568fe0067b8f51341e981b35e3cb4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/7f1ad972efd2725c2507dba7b7ce17627317ea04/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/74a748460d2d4590222d9535bea7770677827230/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/c72880442ef437b3fa2ba6f7b41eda0494b3c815/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/a98f76cdeed60f9b109475f563b82f7c083540c1/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/b2c78daa815b1de36be99bbc39592de554bdc6a0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/3c439c75283883b35083f54420f526991fb9e45c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/ec683f4a04f4314317f69f581585c67a382ae22b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/a591f01a0361ce86d34e0d4b1bf4f5c3734fab90/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/338bb8346f3fa293fdf24dd3311ca965f20963dd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc1a9ce9f56306b8d8f2b01f12183e6c/raw/b5cc876a43865168ad1fd84d404016e24a0b31c1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
+1

**Pull request merged**
