### PR TITLE
GTEST: A workaround for the GCC issue in FC35 - 1.12.x

### LINKED ISSUE #7705: Gtest build failure on Fedora 35 with inbox gcc
### Describe the bug
Gtest build failure on Fedora 35 with inbox gcc
```
 CXX      ucp/gtest-test_ucp_stream.o
../../../test/gtest/uct/uct_test.cc: In member function ‘bool uct_test::async_event_ctx::wait_for_event(uct_test::entity&, double)’:
../../../test/gtest/uct/uct_test.cc:1514:26: error: ‘int poll(pollfd*, nfds_t, int)’ writing 8 bytes into a region of size 4 overflows the destination [-Werror=stringop-overflow=]
 1514 |     int ret        = poll(&wakeup_fd, 1, timeout_ms);
      |                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/poll.h:1,
                 from ../../../test/gtest/uct/uct_test.h:15,
                 from ../../../test/gtest/uct/uct_test.cc:7:
/usr/include/sys/poll.h:38:9: note: destination object ‘pollfd::fd’ of size 4
   38 |     int fd;                     /* File descriptor to poll.  */
      |         ^~
/usr/include/sys/poll.h:38:9: note: destination object ‘pollfd::fd’ of size 4
/usr/include/sys/poll.h:54:12: note: in a call to function ‘int poll(pollfd*, nfds_t, int)’ declared with attribute ‘access (write_only, 1, 2)’
   54 | extern int poll (struct pollfd *__fds, nfds_t __nfds, int __timeout)
      |            ^~~~
  CXX      ucp/gtest-test_ucp_peer_failure.o

```

### Steps to Reproduce
- ``../configure --enable-gtest --enable-examples --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --with-xpmem=/home/pavsha01/work/xpmem-install/ --prefix=/home/xxx/xxx/ucx-install/ --with-ugni PKG_CONFIG_PATH=:/home/xxx/xxx/ucx/build/../contrib/cray-ugni-mock PKG_CONFIG_TOP_BUILD_DIR=/home/xxx/xxx/ucx/build/..``

- Reproducible on master and v1.12.x branch

### Setup and versions
- Fedora release 35 (Thirty Five) , aarch64
- No rdma-core drivers/hardware
- gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

### PR DESCRIPTION
**Pull request by shamisp**
Fixes #7705

### CODE REVIEW

**Comment by shamisp** [comment]
ok to test

**Review by yosefe — APPROVED** [review]

**Review by yosefe — CHANGES_REQUESTED** [review]
fd leak - need to fix; tests fail

**Comment by shamisp** [comment]
@yosefe I don't think the failure is related.

**Review by yosefe — APPROVED** [review]
pls squash

**Review by brminich — APPROVED** [review]

**Pull request merged**
