### PR TITLE
UCS: padded warning fix

### PR DESCRIPTION
**Pull request by brminich**
- Based on Rafi PR 902
- Check for compilation of ucp_hello_world added to jenkins

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2219/ for details.

**Comment by brminich** [comment]
The fail could be related to #903. (but it's nonblocking_put_nbi_flush_**ep** which fails, not a worker though)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1555/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2220/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1556/ for details (Mellanox internal link).

**Comment by brminich** [comment]
Now the problem looks like #856

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2221/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2228/ for details.

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
