### PR TITLE
UCT/IFACE: added message size on invalid AM ID error

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12405/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/3f1eab08884db76234e3ca2068c703b5540f653c/_main) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/620468d561e8a9895e53ce029d2f5e5b7816b42d/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/09860282ea5bb2e940d337401ec9cee3dde2ad5e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/2fdfc9934f025c2159c8f0e18278217584fd0679/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/a6d2067c3a34cbeccd87d0f51d5e5025fe8c6bc1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/18ce3bf8ce2e0910754d75581073cd067680062a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/04526335fda062c6c03f052701516b9f6161a7eb/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/2dc0b7c5487d99f679ba902bb0f46ebae7d45a0e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/cef402f81938c6482031a61725145de4f917cac3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/d389f27adc99cf75141f8f03aa25f5d05cda0bcb/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/ebe0ba5da0d4d41e435313f7cd5722c263e010c5/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/ffbfee0a60d00838043255819ed8e01c3603f9ab/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/a6119fe91b070a3976199a93e55797d3894a9471/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/a492b7bc88cc337ccc6dd892daad2047460650f7/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/9983bfd4f0cd37b7622c89eea40cbe981cf022fa/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/d433404a6d31128ead8111d70a9d827e0bce82cf/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/b200139abfc4c8298f301ad0c581dae45d2581cd/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/7d70b2b323ed5186646f9fe0450a000872c74416/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/425ae5c59f5f7ca0ceaf57d9fe919b222c0af5ea/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/959052aa4c1dd8e10be7e1b82a69396eb24eec9b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/d125879845096e6193f1eca4a059e5a43adbbd01/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/a5bc00fa2bff7cb3f2ce8b15110bad993d8a7d5b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/590e415adbf6c55f2a389e530c8772b972d93a6b/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/93b3824848be53718dd1d723da434d6a01db0d0a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/8b7b25afab3016fc61cf897b463c42e49e64cd58/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/bd09ba31251ddb13659d821966753fa5b8455ce5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/f22535896dab7a702450e64a8205b05d553eef53/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/eee0e84bb171a79a087de9e4a62413f015d9a401/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3debe22451ce7f9926417baeee15f5a5/raw/31156178aeb5269a2c091c2f794d8d0568beaef1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12413/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/2adfc36a38fb9066ada95d15c947342d7171f8c0/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/f2b03d3de2181e855e6abbab569a553902cdd862/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/b1fe4c4e8acd63f81fc4c4afca022c3a2bfe1a35/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/9a62e2b7ba6a39c8a779e527731a0b8c1803422d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/b637df8b54e0a5d27d2db63ef3012f2643c4ddfe/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/286f333a22bb89796873b2ea5527176d4295e548/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/f18bdb2b1cde73b9ce6f6e8698770b8c2e505b84/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/5a0f21cd80026d4ccf2ffc0201959db6591e0bb9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/00de4db5557f966f8cfa62f47fef552482da54b4/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/655fb778c80a931aa8b743fb0e87c4131a9c7b54/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/babbe32b8484aac1b0ef25baefcd7be22ee9ed0f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/01294e790a434b01c00d50d92700b5b124c5d5af/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/0b977f1a9fc545a019b6493f2fee716d0f063af1/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/4208444a0a265d901c0875cca5674b30e25063b0/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/e384e4c09a1b063c3360fe57799e79585b3a682e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/4f7a9d9a05b319872d808676b83f6ea78fac96d9/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/9cb4ebaf76053da6128bf08d191759071acf40b4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/488a5bc733f55b78e8e0c519cd98bca3610def4f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/505d9d9181db5be79294774096374d8e4a27eb8d/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/bceb01ee1af1e3477d3837523f907afa171a2dcf/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/a726cccf22854cc92b7c3c6849c79a26b98c33e8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/ceaf31191597cf5c1d8a7b4771548a11d89d7df8/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/95cd3030e974359e5a7a119c25af2efc4651f1e4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/21007aa196e4deaaee8b199c860838c2fdff58d6/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/8aa698673b20f16ab42972c5e59fca16360e5d6d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/f9ac863ca8e1df4aa4244696ca1e95fea4766c9a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/8c9cd304416654e0dd8c70cff18fa5d4f22dbbc8/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/02ba5e134c453530ef3270f9185401ce38b4bcbb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/19be56f9c8e0099e71b8115aed82b010/raw/a1fa0e9212f6d6b211148ba968ac7376348d7164/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Pull request merged**
