### PR TITLE
UCT: Rename uct/tl to uct/base.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1231/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/644/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1232/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/645/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe why ?

**Comment by yosefe** [comment]
i want to adhere to file naming conventions throughout the project ('base'), and every file is dedicated to a specific object. also 'context' is from the time we had uct_context, which we don't have any more.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
:+1:

**Comment by shamisp** [comment]
autobot build

**Comment by yosefe** [comment]
@shamisp is there something wrong with buildbot?

**Pull request merged**
