### PR TITLE
UCP: disable amo lane for mem type endpoint

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by bureddy** [comment]
fixes https://github.com/openucx/ucx/issues/2266

**Comment by shamisp** [comment]
why ?

**Comment by bureddy** [comment]
mem_type (local) endpoint  which is used for staging (move data between mem type domain(cuda) to host  memory) do not need/support atomics

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6173/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy pls pick to v1.3.x branch

**Pull request merged**
