### PR TITLE
UCP/CORE: Reduce log level of no devices avaialble.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4826/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
#1918 , retesting

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4828/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4829/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4830/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls take a look

**Comment by yosefe** [comment]
note: need to make sure there is warning when UCX_xx_DEVICES or UCX_xx_TLS specifies non-existing resource

**Comment by alinask** [comment]
@yosefe why is this done?

**Comment by yosefe** [comment]
The cuda changes make UCP always print the warning "no accelerator devices are available"

**Comment by alinask** [comment]
:+1:

**Comment by shamisp** [comment]
hmmm. I would suggest to print the warning if used explicitly requested the TL.

**Comment by yosefe** [comment]
@shamisp yes, that is why i have move this to WIP (see my comment above)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5042/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5047/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls take a look

**Comment by alinask** [comment]
@yosefe what of 'all' was requested but there aren't any devices available?

**Comment by yosefe** [comment]
@alinask there would not be an error if no devices of specific type are present. Otherwise we would see warnings if no GPUs are present, or if no network devices are present but the user is running on single machine.
There would be a warning only if no devices are present *at all* or that a remote destination cannot be reached using the existing devices.

**Comment by alinask** [comment]
@yosefe yes, this is what I thought we should avoid - not having any indication of missing devices when there is a failure. Because "destination cannot be reached" does not indicate that the reason is lack of devices, which is a relatively common error case.
You don't think we should notify the user if this happens?

**Comment by yosefe** [comment]
but in some cases it's a normal situation to not have any devices of a specific type, and i don't see a way to distinguish between the two..

**Pull request merged**
