### PR TITLE
Fix some English/spelling in ucp.h

### PR DESCRIPTION
**Pull request by tonycurtis**
* responsible to -> for
* accesses -> ed
* reacheble -> reachable

## What
Fixes some English and spelling in ucp.h

## Why ?
To correct spelling

## How ?
N/A

### CODE REVIEW

**Comment by shamisp** [comment]
@bbenton please review and approve 
@tonycurtis thanks a lot for helping with documentation

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8605/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by bbenton** [comment]
👍

**Comment by shamisp** [comment]
@yosefe since there are some spacing changes, we need your 👌

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8606/ for details (Mellanox internal link).

**Pull request merged**
