### PR TITLE
rpm: use manually created tarball from GH release

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4373/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
why manual ?

**Comment by amaslenn** [comment]
@shamisp GH simply compresses the content into `.tar.gz`, while for rpm we use a tarball created by `make dist`.

**Comment by alinask** [comment]
@shamisp Do you have additional comments?

**Comment by shamisp** [comment]
Looks good to me!

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4416/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4440/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4451/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
unrelated failure

**Pull request merged**
