### PR TITLE
GTEST: disabled new_delete test on valgrind

### PR DESCRIPTION
**Pull request by hoopoepg**
fixes https://github.com/openucx/ucx/issues/3734

### CODE REVIEW

**Comment by brminich** [comment]
maybe disable all hooks tests with valgrind, as you suggested?

**Comment by hoopoepg** [comment]
good idea

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10742/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/09bfda68882728274c3b0fe38de9d54eb3e12c3c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/cb8fd2b27c8ffc21e48fdfc50e59f01e19fe1275/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/1f03688d6c7dc1eaf47fff85c3a5be91e6ca670f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/a2b1f147518f760ad1bae7d2010d056fbdca4020/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/41058e560f85f558cdeb321b75024536209847fb/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/107e5da2b3f34bc3b2813f92e102a26f280f7fbd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/5a20899e4336c0aba8c4154403a9f552badc7a6b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/9ad316ac3deba41a57adfa557857e46fdb1e7974/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/7d5c807ebdac79c7f6deed92707cc2a1d0b31f34/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/a1acb2a9b30e1fcd1193550d13ebe6d147d3b03b/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/da2c406bf810d6a9b73961132b2b93f542587838/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/5eb467e561d0f55b48058545fed05310ae3905e1/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/1e0ad48f700ae8313eb910e8a34ca08f6877bbb8/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/8070eb6b0941f75f2786a956af56bf44592a920c/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/0179cb7046be3b860cdc12c507585712ae3a131c/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/5b286617160d2a4f39e2e862898f36c2d1fa51ea/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/981eee655892b681b4263b41dae1736c87c99cb0/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/f7fbe0a8965d6135f3af98f7740994e849bb8ad7/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/e5f5114ba0e966ab2aa8f01bb2cc2105a5508039/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/2d0f62dbed81526a480fe2b48137b64159d54993/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/f0c46a430835a9e36ded01891818c92fb8584e27/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/c5bb499730ac7a9cb57e8cf327d04bd66740e565/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/401ad488da50b1ed52302c9e86cf8d8cf71e8cb5/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/ddd44ae3135ad40777b5bd442db0fdd4610e324e/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/90ace9bbd251bb60f385517b8364ae3678c6d9a9/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/11f72b3d4e1ed88d0220715ef7fa6f13c727ace8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/a42eb4a40aaf033f615f97170693b2a083ef38eb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/41e755137ef3d484c173ed5894f85573dd4527b0/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/ec20a4162c83b2704ed81ca230e76df2fb6cefb4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/d98c39f6a2cc2881182dbd33efa8004b1c8eb25d/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/3c1db54737248a380d2e68843a69bd24d7d501e6/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/9e0c44c8ae0fc4e1a62ad59e0ad7f23c541445fa/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aefa201cc4949801f2e1be111b42f12d/raw/7cf21135eb696c2652a733ecb5cacb6e1174ea5d/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by hoopoepg** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
