### PR TITLE
UCP/TAG/OFFLOAD: Add assertion for the return value of posting tag

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11415/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/b2262892b7041018664326cb10583f0e06bdb4d1/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/b2d64ff10528f90cf621dd57623577a8a033d2bc/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/dff5619e76e7aa94b7b9186921fd0f427c883467/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/a3cde04779b68cd55894636aad9359bb5f47eff8/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/9e0b426b3fbd5947635bf03a2cafdbc3efd3a33e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/7e507133958ceb2090c3b3ce38b054e228a607ac/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/bbb66a168124d1f4c7bff7b0d71704d534d37ffd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/31e9123119fa939fa551564b722c5afe6de9c8aa/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/dc3d66f0f048ab093976ef5f1689fe798fa458d6/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/be4d3a378f9e6f5f3bfacfa1e8c8a73dc64b71e4/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/94c458a1af26ac7b1d350829de3efc18f2cef70f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/345605c1f77389675a7e5d0db5ce7b5d3fa72c61/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/f6fdb67aab56ea353d73d707c9596463adba79c3/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/7f282bf3b218e673529ba628d78086fb607b9b38/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/c13c2b7403c020f280d56c2f5de30b774917df2d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/565a9934953c63b8ba9192346d1833e81926ae64/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/b35cd8a8ec23c13a77bede3e46c6c981c31e0aaa/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/a6c4bb435c5e2940341923aafcb685ee3b9e5a1c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/f95ac7a7d1e53088e8dde199bc7e25d36d95d5d9/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/1d8b75eb4a2285c03f7c72200751ddcadcacb2d2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/d387d2bc120cf01657c82efcbd598ff2a5712c0e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/db9932e986a9fe79877b387079b67100f618e629/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/d648b269c2b0c37e904ae615190ce3beefdf6b2f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/261462520188e19b5c2b9149a868b5ef83ab8976/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/749926d8ba1b2dbd0fefcdd0abc601bec2a5fcde/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/ed4c37aad2aef745b8e73178ca4121f4440b67d3/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/dd911a10ed8b0f4130a23f7ed82f186391b7f415/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/bbb8b953b1922641a29d493ed5fd7ebf0531ba42/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/9438718f06f5ca259dd72e79079cce213544a07b/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/0e44d912da685004e4ab5c1893c94d86b0849e88/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/674fc74afc93bd3d39f92b0ea0f0c0cb313e1d04/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/7659716c7285d9e8e3402caa88596d75255b1379/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32925389b057e9fa7da078502236a283/raw/7a7ae6b3da2a2637e45dd8ea5771b2beeb09e5bd/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
issue is #3929 

bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11423/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/a5dce4e5b5f5c7e6f7b8330d501ff0ed156773fb/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/3d2d23fdcf712d798fadac7c37fe7f7ca94f287c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/36b4be7c3f5242a565891b525fc852285990d891/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/6720e117d7d236f9f59b5a720fcd235478cca7a1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/b7344075ed19c93dbbb535a2e10d76c4928107e6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/e91387da5dc6621990fa2ed38703056867a7728f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/31358a8ca0fd9394a46a8ef54d14366f5a484513/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/9f91017a1c41bbcac163a4e96dc28758bc2d07e0/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/ffbb5ddb17a5f67a5179dfd555bee8eddf3357da/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/4adafe9307fce573f99271275ca52258cf8e41bb/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/abf28d203df95cfbfeb1b7ea831cca9bd38f52ed/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/cae25e296e55e20d2c012b6df121118ba7ae21ea/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/051a5886f1f3e8cd42d9a28b9870f5ceec80a48d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/42c00bc749bef895844a127d431bc00e01edb8d4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/18b204b716d42688f7a4d09835e95cf0f980acc2/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/dd1dcc42f8ba48e7eaa96d7a9b87bdb6b9ab91db/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/994dad7ff9ccc1884ba73530d643b27f5ff53b5c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/c0d81dc047cd39edf080e418bc3927b1344c9095/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/421fbdc900ae495831ff1a04efd7e52ec6f44049/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/a40139fbff4bc30a6c816f8f0a423e18475d7a17/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/8086bdf67d9d9638761b13b47765429af4cd2edb/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/37f4ddb89df2736f8239524508a12f56deb343ea/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/b46887ce618e9535bc566b4497d54bade0ad52c2/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/a4b362fb38c7ddef3253b52d4821e8002a481be1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/257d8067043edd9e8245d82c782e95cb2a3dc254/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/71b306fd6ca2d7c99059ec0baeb308549778c3e4/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/c626e9e073a127d4cf91145cab130ae847f3307d/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/db8f27d51b3a8cc8e3486b427da0e9ad351f20bc/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/40fb088ea6caa64e9df469d98ae7fb9de26fbb56/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/6e2fd8d79c0434d15267e7a9041daed8a8ff5d55/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/59382434e0c264239a38ea77b6f94a0661db0c1c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/575251b59f2e5a99bd363e087cd912840303c158/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/49e43e8fe46c7661baa513206627ef11/raw/4c0e59aa839e332312ace30548df3a0caf56b169/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
