### PR TITLE
UCP/API/DOC: Fix typo in UCP Worker description

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix typo in UCP Worker description

## Why ?

better documentation

## How ?

`implement` -> `implemented` in the following files:
- `bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java `
- `src/ucp/api/ucp_def.h`

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/660387aee048c2161528b8795501ba970fc10353/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/1fcfd1e9e2f485aeb73a7b99f8c30986d4c31bb5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/865ec5533a667100a370930b252b0b1b7b393ed8/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/78fef171a8c10bb8b6e0abac8155894d639f391f/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/9e44a24860b43d9507f189b86898af70b062dcff/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/f9210018e32d056c35055a9691c3abb7cbd32f6d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/e731257a1a1763eac95bd29c9322e3eaad476080/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/cf1dc9297f1e64576443817ea26aaaaf629fb6c6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/0d0c7e8c785b0b90c7ab74a41022b97487d7620f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/b7d00a506a428843d671394c6226582a102edc15/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/a5e02b86255dc91f4e11a49516633f439b94c212/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/b13bd869c78c73e84a47a65fe0a6decd7f144698/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/0da6df95d324330bb4aae1cb51232b7b97cbb174/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/b3c10cf2602e1ed4528a966ae962618f32b8c540/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/0edb5db9d9ab3e23f9f719b99d882f3981e6752e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/f3223eef48423b9387a5db34c927d5f006d8a208/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/9f823c71930ebd7d188f349bd6ad191560d96d34/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/bf5168c00b9fd270436c56af78e8df86afef7352/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/556a2709c865ae9cbb575e3493439a44902e303a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/64a5dfa0c86a281d48faa7e5e6368257622bcc0a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/aefec6643080daf5efbfcee40bc315d0035eb696/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/469684b2dab4e43b57c4240707752a0bf6db7a4f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/dec60f170a817177b36faa790dde8ed98b237ff0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/9d82607262a2f33961a1201a16f2bc596b3b3877/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e9e9d2816feb01c3c36bbc2691d35399/raw/5d96378e9606ad930a4d36b2406fa32553cc82c7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
@tonycurtis

**Comment by dmitrygx** [comment]
@tonycurtis @shamisp done.
could you check, please?

**Comment by tonycurtis** [comment]
+1

**Comment by shamisp** [comment]
Looks good

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/10d7e7bc320796be88f6f95f7ee9023be3f0217a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/732d992f41e0513a27786cce0bf7ddd43260256c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/185c4d337612080a61f5706c9a40e1ab6d14b9be/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/c79323249cdd429f8d0fc0673eb85d344aacdab3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/0f9683b42a96732911357bb35096e41057a4d973/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/f17b0a0d90d2b337973cb91ac58c97e9af802fb3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/aafef73690f8ec29db7769a79e065c6317ea53c3/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/82ed658d8759d24bab07a0f203c9abfdcd65f001/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/031273282fae37804d68ecb19a4651ffebf678e0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/33862ebffe9ad45afded9441e71d745c423340e3/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/ac282e472f4a09f71618b9750a064ea9e6511124/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/e5cdea87b96c201d49a6d3b469168c60450aa06d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/15628e92bf9cf08df15499dbf5604783f02f18ed/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/8fd944e5963fcf7ff54e1511279bfb37c4a9308b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/a2a39c2fd8eba032418f5527304cbfaded11eee6/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/ee9c8ae5d3275c8ec14df94a4dc0dbcb10fe331d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/bdd798176cdbd65337f843313e4c0887e8ef9a1f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/3e20d4929c381afe0f1844718630b61eb7c3531c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/6cc2fe6002ddfafd1d9fcd069107af9f60f2b0d5/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/fcaa6bcf4af86e171a6176d07c59512a622f15eb/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/0042b7b16463c4bab58fd285a1a5eee445e9cece/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/9de71102633faa547ea5f8d26001983157e07d78/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/37ecb20f0a0d5e9778b3eb77c8220cc36818c5df/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/7514389c0553eb8a6c082539e294b442eed28d37/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cdb5c8c9f926c603a13ecc8a931359b4/raw/742a811d054d17d70ea1d4a369a7d54c8162022a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
