### PR TITLE
configury:  add pkg.m4 file to ucx configury

### PR DESCRIPTION
**Pull request by hppritcha**
Oftentimes pkg-config is not installed on a system,
and almost certainly not for cases where uses have
to locally build their own autotools owing to archaic
linux distros used by vendor.

Adding the pkg.m4 to ucx configury is a way to
make the lives of those folks better.

@shamisp 

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/866/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/867/ for details.

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by shamisp** [comment]
It is functional, but we are waiting for LANL representatives to sign the contributor agreement. We can not accept code without signed agreement :disappointed:

**Comment by miked-mellanox** [comment]
replaced by #536

**Pull request closed without merging**
