### PR TITLE
UCT/IB/MLX5: Fix SRQ cleanup flow.

### LINKED ISSUE #1389: Timeout in  rc_mlx5/test_uct_ep.disconnect_after_send/0
53:53 [----------] 1 test from rc_mlx5/test_uct_ep
10:53:53 [ RUN      ] rc_mlx5/test_uct_ep.disconnect_after_send/0
14:08:36 Build timed out (after 200 minutes). Marking the build as failed.
14:08:36 Build was aborted

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1389

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1299/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3242/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3245/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Pull request merged**
