### PR TITLE
UGNI: Cleaning the callback flow

### PR DESCRIPTION
**Pull request by shamisp**
Following Yossi's suggesting to replace "if" with
inline cb.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@yosefe @MattBBaker , please take a look.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/742/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/179/ for details. (Mellanox internal link)

**Comment by MattBBaker** [comment]
+1

**Pull request merged**
