### PR TITLE
TEST: added test for CQ moderation period - DO NOT MERGE, WIP

### PR DESCRIPTION
**Pull request by hoopoepg**
- added test for CQ moderation feature
- for now period of events are tested

this PR depends from https://github.com/openucx/ucx/pull/1838, will be updated to reflect changes from parent PR

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4603/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4604/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4611/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
this PR is added to https://github.com/openucx/ucx/pull/1838

**Comment by yosefe** [comment]
superseded by #1838

**Pull request closed without merging**
