### PR TITLE
UCT/UGNI: Update UGNI tl to use new error handling signature.

### PR DESCRIPTION
**Pull request by MattBBaker**
Now that the UCT version is merged in, update for UGNI so that it will compile.

### CODE REVIEW

**Comment by MattBBaker** [comment]
@shamisp Can you review?

**Comment by shamisp** [comment]
it looks good to me 👍 
let's wait for testing results

**Comment by abouteiller** [comment]
👍

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1232/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1841/ for details.

**Pull request merged**
