### PR TITLE
UCT/DC: Add explicit quota to dcs_quota policy.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2543/ for details.

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1896/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls take a look

**Comment by yosefe** [comment]
@MattBBaker can you please post ORNL failure?

**Comment by MattBBaker** [comment]
Our friend /dev/shm

```
[     INFO ] 0 3.9g [1475682365.444036] [pod9:11912:0]       mm_posix.c:88   UCX  ERROR Not enough memory to write total of 4208440835 bytes. Please check that /dev/shm or the directory you specified has more available memory.
[1475682365.956684] [pod9:11912:0]        uct_mem.c:89   UCX  ERROR failed to allocate 4208440835 bytes using md posix: Out of memory
/var/lib/jenkins/jobs/UCX/workspace@2/contrib/../test/gtest/uct/uct_test.cc:241: Failure
Error: Out of memory

[  FAILED  ] mm/uct_p2p_rma_test.put_short/0, where GetParam() = mm/posix (13112 ms)
```

**Comment by yosefe** [comment]
can yoy enlarge the size in /etc/fstab?

**Comment by MattBBaker** [comment]
I personally cannot, I'll see if I can poke an admin to do it.

**Comment by yosefe** [comment]
bot:ornl:retest

**Pull request merged**
