### PR TITLE
UCT/UGNI: Localize CHECK_PARAM_IOV to finalize UCT zcopy support.

### PR DESCRIPTION
**Pull request by shssf**
Related Issue #951

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2673/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/74/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2029/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@MattBBaker - this PR is awaiting your blessing :)

**Comment by shamisp** [comment]
👍  from my side

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2032/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
So, making the macro UGNI specific? Looks good. 👍

**Pull request merged**
