### PR TITLE
UCP/RC: Don't flush UCT endpoint before destroying it from UCP.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1048/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/478/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
autobot build

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
