### PR TITLE
UCS/PROFILE: Fixes in profiling infra.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2855/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/307/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2254/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @brminich pls review

**Comment by brminich** [comment]
:+1:

**Pull request merged**
