### PR TITLE
NEWS: Backport #2843 from master v1.4.x

### PR DESCRIPTION
**Pull request by shamisp**
News and authors files update before RC1

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7784/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7795/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Errors are unrelated. @yosefe can you please cleanup your CI ?

**Comment by yosefe** [comment]
bot:bgate:retest

**Pull request merged**
