### PR TITLE
Fix failure in gtest because global configuration is not restored

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox this should fix the test failure for #538

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/651/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1238/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1242/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/654/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
failure is unrelated (on fedora22 build machine only)

**Comment by miked-mellanox** [comment]
:+1:

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
