### PR TITLE
UCP/API/DOC: Fix ucp_get_[nb|nbi] documentation

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix documantation for `ucp_get_nb` and `ucp_get_nbi`

## Why ?

Wrong description for parameters in Doxygen

## How ?

Fix the description according to the real meaning

### CODE REVIEW

**Comment by dmitrygx** [comment]
Thanks to @Sergei-Lebedev for finding this!

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/e966bcc00c6dcc3c1e22fb97c3b784d6ffef9686/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/11261ae4950665caa499d3b69c34fa223ba1161e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/7f10dd7281234facfef9058664dc671c52cdb573/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/3c2e751f0e0769bf8dccd0900dfe9b56c9687743/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/f28adedc1d535d09c49cb424ecb583148f730020/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/407d26a3bbe1fc15d962238b71055c6208790a43/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/c6257dbf20d99bbdc47423afbb1c0d1bd0151584/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/cf5421f134bc098c605a451c5ea2b4d200ada3be/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/944f31a9d22d71213e25ebb62fe436da3a6ed11c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/6a97d5814fac3ead7058e7473ea26a0717865f18/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/aba1dc4fc07fc8efe49731eb5302c43acee5cca7/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/524a1ab9a8b4a06a97714fdfa54c9a28d8594646/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/4061bd042234ba17ca687e0c2ae8b6a25dc8638b/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/8047f494f8f0002bf3e57cb978ee17c88580ac57/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/bf66a79d021da9c5b31ca6a54306f976842fb5fc/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/9d0f2f32158c6f52e922e369320f5f1c01f05b6c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/5c6ba7e015bcabb6744b4a5190b24a7d21b7883e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/4d9d630c0e7205ec887b32a259ea802600cdbba2/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/6f3d42736b293928c5d5ec6c1e5fe372ee59abbb/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/80c20c083a273dbb7dcf264d116c9b7c0a174fb3/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/58b7754c24f6647b4bfbebb595cbe895fc466aaf/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/6a211929a0be576ec293fee459fd7a206b05147a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/9605b5a6c4d018812b825422485a81dada1d2a6a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/88f1beacf0d319315bde57f820468546e4c6c7fd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c1b664d83cd84b440574990afa918dc0/raw/7482317057779b78ecad0e3d237dc681dddba714/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@brminich @yosefe @shamisp @tonycurtis could you review pls?

**Comment by shamisp** [comment]
+1

**Comment by shamisp** [comment]
Trivial documentation change, I will go ahead and merge it.

**Comment by tonycurtis** [comment]
+1

**Pull request merged**
