### PR TITLE
UCS/UCM: Memory type allocation cache

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6163/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6176/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6179/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
this patch is well above 500 code line limit...

**Comment by bureddy** [comment]
will split it. thanks

**Pull request closed without merging**
