### PR TITLE
TEST/UD: Fix ca_md test - make sure there are enough TX resources.

### LINKED ISSUE #1212: failure in ud_mlx5/test_ud.ca_md/0
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2540/label=hpc-test-node/consoleFull
```
21:50:11 [ RUN      ] ud_mlx5/test_ud.ca_md/0
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:11 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_ud.cc:506: Failure
21:50:11 Value of: status
21:50:11   Actual: -2
21:50:11 Expected: UCS_OK
21:50:11 Which is: 0
21:50:11 Error: No resources are available to initiate the operation
21:50:14 
[  FAILED  ] ud_mlx5/test_ud.ca_md/0, where GetParam() = ud_mlx5/mlx5_0:1 (2941 ms)
21:50:14 [ RUN      ] ud_mlx5/test_ud.ca_resend/0
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1212

### CODE REVIEW

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/609/ for details.

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2555/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/610/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2557/ for details (Mellanox internal link).

**Pull request merged**
