### PR TITLE
JENKINS: Fixes to make Jenkins run on ARM machine.

### PR DESCRIPTION
**Pull request by yosefe**
- disable valgrind
- fix IB device enumeration

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1046/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3001/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls take a look

**Comment by shamisp** [comment]
@yosefe - thanks. Can you please forward me valgraind failures so I can pass it to our team ?

**Comment by yosefe** [comment]
@shamisp it just hangs forever - no output.

**Comment by shamisp** [comment]
Can you please provide a command line example that we can use for the
reproducer.

**Comment by yosefe** [comment]
`valgind ls`

**Comment by shamisp** [comment]
och ...

**Comment by shamisp** [comment]
--version ?

**Comment by yosefe** [comment]
```
$ valgrind --version
valgrind-3.11.0
$ uname -a
Linux hpc-arm-04.mtr.labs.mlnx 4.5.0-15.el7.aarch64 #1 SMP Wed Oct 12 14:00:10 EDT 2016 aarch64 aarch64 aarch64 GNU/Linux
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

**Pull request merged**
