### PR TITLE
UCT/UD_MLX5: fixes bug in available wqe counting

### PR DESCRIPTION
**Pull request by alex-mikheev**
in ud_mlx5 available tx wqe count may be negative. 
@yosefe

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/884/ for details.

**Comment by shamisp** [comment]
ignore the failure

**Comment by yosefe** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/306/ for details. (Mellanox internal link)

**Pull request merged**
