### PR TITLE
UCM/CONFIG: Fixing mmap symbols override.

### LINKED ISSUE #582: Add an option disabling UCM library
We need to add configure option allowing disable of the UCM malloc hooks interception in compile time.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #582

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/802/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/803/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1417/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1418/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/804/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp it should fix your issue

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
@yosefe Let me try this patch...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1420/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/807/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - we shell chat

**Comment by MattBBaker** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/809/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1422/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/810/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe , Huh...the 1d8e8cb6c957b9abe8850936d838197960f644b9 fixed it.
Do we understand why ? The static init was setting the pointer to the original functions ...

**Comment by shamisp** [comment]
Another issue - I think we have to disable all the malloc hook test for this case, right ? By default it is enabled...

**Comment by yosefe** [comment]
you can always disable malloc hooks by setting `UCX_MEM_EVENTS=no`.
the compile-time setting controls only whether dynamic symbols will be overridden by ucm library during load time.

**Comment by shamisp** [comment]
I think, if it disabled by user during compile time, we have to set the UCX_MEM_EVENTS=no by default.

**Comment by yosefe** [comment]
You disabled only symbols override in compile time. Memory events can work without this as well.

**Comment by shamisp** [comment]
@yosefe , probably I'm missing something. I don't understand how it can work if we explicitly disable this...

**Comment by yosefe** [comment]
because what is being disabled is not the whole memory hooks mechanism, is just one of the methods (and there are alternatives)

**Comment by shamisp** [comment]
I think we should have a method (compile time) to disable the mechanism entirely. Just like we have one in OMPI.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
