### PR TITLE
UCT/DOC: document uct_ep_disconnect return codes

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
Document `uct_ep_disconnect` return codes

## Why ?
To make clearer specially handled errors

### CODE REVIEW

**Comment by shamisp** [comment]
@tonycurtis @bbenton - please take a look. Overall, looks good to me.

**Comment by tonycurtis** [comment]
Is completed -> has completed

 
* (@ref uct_ep_client_connect_cb_t or      
 * @ref uct_ep_server_connect_cb_t correspondingly
 * was not invoked).

“Correspondingly” doesn’t seem to refer to anything?  Maybe just put “either” at the front.

Tony

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/b663e160ddb2cd8a0ae4cf0b311d1a9c770895a9/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/e5ed2aed6e047fa2e2a7b8d85cdacf92325622f9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/28088cc41921ddeb292986ac54d3454ded417dfd/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/e4293dbe91d52d93e8ae310be070f7081e19e6be/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/a6c84d4d6b6cf1bd8f6e951396e1bf7962cedbf8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/67caad3642e61fa7500ddccce5aec55005d7c148/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/c331f4d474dd6d9b86c0c0c69960df4d466dac52/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/064cdd7fbd7675af0b6b1a0ab4997427c48f2c2d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/324435adfe2dbc0dfdd3499201a5b6b1f76d27e8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/783e807aa583e01c6ad69ff3cdda649ecc65cd59/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/7cd72765464bad438f8f5329df223cb0886224ea/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/099824591b850434e6a5f0525cd24732e0cb62bc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/160253f780595b5b93d9f7ef918de09b8b073def/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/cac831fe7a7fd6a748faa25dec3f8236f236dc10/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/c546ee712dbfb49eaa1fe9e96c921a92b5819f81/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/2c8c127d7dc639cfc5d0b09d88be7d7fb0ee5472/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/a34eb628c76a6a6f13a045da641fb963e60df6d5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/04b3de8839d7036a7b358130b1a733a59e089ca0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/7c753e60ac0467bf132fdbadbc294ab8dd1de3ea/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/db49da45e3cf2b3ffeb3508642ef77b909b46963/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/0ac71eda85a0826e27b239758927a7be882ae2a9/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/80bc89feae05e53ea656440704a1d21dee0cb83e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/f98f41d84816aaf22f79015143983a30b7ac6a80/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/00724453b48e4010065d9074124874618fa85e89/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83bdc1f525131f21a5f272b21ecbfd6f/raw/f9cb5662847f080b4f0b175cb064e480fe4ed2f1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/6d31fc5c647f70f36ed7b4812b12c2b8ac2f886c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/1aeacb94c7b9ae311ba275f862f54780cac50b44/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/3900c5f8d8a9eb24a5bb4962dae3c24cb2698a60/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/43a635e51387c41aa7bba28bd8ac7b03aa17ac11/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/508fe23e22a37e2b03a7cd4c27ef5d39c9192f98/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/16ef9f5a9660f660944830d1b9bbf8107bd08a58/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/57e9b67f2bb286832c6e725c30cfe061d1dd7bf8/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/8f24e50df7b19c850795e3b922c8007daab33e8d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/bc99f9f563acee460fe7cc88d03bec2b456597a9/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/bacba3b4e6c4ba509e1aacf08911da3c781b24ac/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/e55db50252a0fda2c2b57feba949e660f93be07d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/6d0709a0a6e0a68c3de759f5e67a65cf46a97e1b/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/6fa2accbcea11f017434d979ceff731a7f3a78cf/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/1dd1b21ec7752f1532201d6caeae588a77ef717a/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/e0142f271784bb0194252d5522a84d3a64463d45/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/744b19f7a725a6c90e90015e1154e25345e13543/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/383bd584d6e47cb5894be8218d1711b54b3252fc/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/6cd222cc2c3267f5b8f8e61ddf5c3f8ce18284aa/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/a6ae6f36eacc30b19e6d08e6c901b038a71c5973/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/ba983a3e38e7bc70633ef2d6edab73ad63261aee/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/40eaa17cd673b817fc642a85d6791955935c3eef/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/cd3d215cdb411f7d877326cb15a7980aa09b1851/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/27049e1a4ace2a64ea65bbdd34e5969c84c7ffd9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/4bddb133249be1b0555cb92e35b093309b3cee1c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f8a6c053f72badcb922c0c4b03dfc772/raw/9b0987c9bad53b793105ae589b4d75a31eddeee6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by alinask** [comment]
@evgeny-leksikov is the concept of locally and remotely connected ep clear to a user..?
i'm not sure we use this terminology in the api. maybe add an explanation of what it means?

**Comment by evgeny-leksikov** [comment]
> @evgeny-leksikov is the concept of locally and remotely connected ep clear to a user..?
> i'm not sure we use this terminology in the api. maybe add an explanation of what it means?

There are mentions of remote peer/side in the func description, also I tried to explain it referring to corresponding callbacks, do you think need to add something else?

**Comment by alinask** [comment]
> > @evgeny-leksikov is the concept of locally and remotely connected ep clear to a user..?
> > i'm not sure we use this terminology in the api. maybe add an explanation of what it means?
> 
> There are mentions of remote peer/side in the func description, also I tried to explain it referring to corresponding callbacks, do you think need to add something else?

There are mentions of remote peer but not of a remote connected ep. IMHO it would be better to explain.
Also, should we mention that UCS_ERR_NOT_CONNECTED and UCS_INPROGRESS are returned on repeating calls to this function?

**Comment by evgeny-leksikov** [comment]
> There are mentions of remote peer but not of a remote connected ep. IMHO it would be better to explain.

@yosefe WDTY? IMO it's clear from whole the description

> Also, should we mention that UCS_ERR_NOT_CONNECTED and UCS_INPROGRESS are returned on repeating calls to this function?

I don't think so because such calls don't have side effect except notification to user.

**Comment by shamisp** [comment]
@alinask made valid point. Probably you can state that ```the disconnect request was initiated, but the remote peer didn't respond on the request and callback registered under XXX has not been invoked to process the request```

**Comment by shamisp** [comment]
I'm sure @tonycurtis can come up with more compelling clarification :)

**Comment by tonycurtis** [comment]
> On Dec 17, 2019, at 9:40 AM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> @alinask <https://github.com/alinask> made valid point. Probably you can state that the disconnect request was initiated, but the remote peer didn't respond on the request and callback registered under XXX has not been invoked to process the request
> 

So, how about:

The disconnect request has been initiated, but the remote peer has not (yet?) responded to this request, and consequently the registered callback has not been invoked to handle/process the request.

?


Also a query whether the @ref should be to the type names?

Tony

**Comment by evgeny-leksikov** [comment]
@tonycurtis thank you! 

> Also a query whether the @ref should be to the type names?

I think this is pretty useful because goxygen generates valid link to the type thich is documented how to use it in correct way.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/ec64b626de73b4b496fc9affe8392402b54eb63f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/8bd71e6c52d426059f1116230207be2392deda5e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/3feee43b1f05e62b2ae7bc088fa2feb78c51d2ae/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/97a16578254e0d3fb122621af2e36ffd00e0f91a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/2ca1a656d452036e72e660ae79bdade595b6f7f6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/5323f8840ae3cb79a8e0c48ca41a0f5641d1bcfb/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/335aaf56aa3a92dcb911050eef40176437d8cee4/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/24371d8334aab268958f057a10ccd0caec0840c5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/d350eb77b553adc5ccad35b6e5390e16c0adf73b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/13796a977e7cbd3bacde4d1b678a186c433f813e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/d70694d7c743260aae83dff0aa64d99d68595fa6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/e4297c3088f2d1b3f2fe1be8fc75169a0ecdc02a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/0765299c2b2c418b2e908e1a71f56b9702fb15fe/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/f0a6dd83329636939d9e718b74b8b7fe440304c5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/abbcd057f1a159a6df62a54257472ed97d397029/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/a8a31cddfbd5d4a2cce8342bd932fb25bedf734a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/50d5730a4576cfc76fc24327677296f38c0b9adf/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/b5798dcdd04eacef3c51dfa5dcb4726644005a43/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/17123a4a620b986c1743fa36d0124cbb8abc1f20/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/0633988922bb32125d188e71d63f65d2cc5e6f57/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/0b55c15e8af552106fab34a99077d7a735be6560/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/282516246d4be3ba0cbf661e172cc5045cb5fb54/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/fdc26ddcc866ae2952cd0005c2b6921aae332a16/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/344ea73192357d93e7072b5ce34adf438e469e97/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3f092e81d2d5bb3b774208704d41089f/raw/531fd66c8a153b146a41893272a7d228153d421c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by alinask** [comment]
@tonycurtis Can you please review?

**Comment by shamisp** [comment]
@tonycurtis ?

**Comment by shamisp** [comment]
I'm 👍

**Comment by tonycurtis** [comment]
Looks ok (have been traveling, mostly incommunicado)

tony

**Pull request merged**
