### PR TITLE
UD/VERBS: Fix passing common config params to ud.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1533/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3454/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1534/ for details.

**Comment by MattBBaker** [comment]
This failure seems relevant and excessively interesting.
```
[----------] 1 test from ud/test_err_handling_destroy_ep_cb
[ RUN      ] ud/test_err_handling_destroy_ep_cb.desproy_ep_cb/0
<https://pod9.ccs.ornl.gov/job/UCX/ws/contrib/../test/gtest/common/test.cc>:66: Failure
Failed
Invalid UCS configuration for TIMEOUT : 1s, error message: No such element(-12)
[pod9:25257:0]       test.cc:124  Assertion `m_state == FINISHED || m_state == SKIPPED || m_state == ABORTED' failed: state=1
[pod9:25257:0] Process frozen...
make: *** [test] Terminated
Build step 'Execute shell' marked build as failure
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3455/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@brminich @evgeny-leksikov pls review

**Comment by shamisp** [comment]
@yosefe did you figure out the failure ?

**Pull request merged**
