### PR TITLE
UCP/WIREUP: Use generic address packing for wireup.

### LINKED ISSUE #431: Improve error message from UCP when cannot find a transport
#412 
* Detect the problem as early as possible
* Print informative error

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #431

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1678/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1066/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1067/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1679/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1680/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1069/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp can you pls review? failure is unrelated

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1080/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1686/ for details.

**Comment by shamisp** [comment]
Overall looks good. @MattBBaker can you please test it on cray ? thanks !

**Comment by MattBBaker** [comment]
Return of datagram size issues. I'm trying to track down what, precisely, is malfunctioning. It's a single byte over.

**Comment by MattBBaker** [comment]
Okay, this mechanism works fine. Just need to add the UCS_S_PACKED flag to the smsg address struct. I can probably put the udt message header on a diet too. Either way I'll do a separate PR on this bug fix.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
