### PR TITLE
GTEST: A couple of fixes in tests

### PR DESCRIPTION
**Pull request by brminich**
1)  Prevented some UD tests from being run on ethernet (those which do not expect any packet loss).
Addresses one more issue mentioned in #1182.
2) RNDV test should wait for send req before to check it, as with RNDV sender may/should finish later than receiver.

### CODE REVIEW

**Comment by yosefe** [comment]
@alex-mikheev pls take a look
Are those tests really assuming no packet loss? since loss can happen (with low prob.) on IB as well
Also it's a bit unexpected that loss happened on loopback.

**Comment by brminich** [comment]
Some failures mentioned in #1182 looks like a packet loss to me.  Some UD tests assume that the packet is delivered with the first attempt by checking various counters (acks, ack_req, tx and rx)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3021/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/562/ for details.

**Comment by shamisp** [comment]
it is unexpected on loopback, unless your credit system is broken

**Comment by brminich** [comment]
I thought it's more likely to happen with valgrind, as all errors happened with valgrind and on ROCE.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2501/ for details (Mellanox internal link).

**Comment by brminich** [comment]
Updated UD test fixes. Instead of  relatively short timeouts, wait for a particular event with bigger timeout

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/570/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3029/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/572/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2513/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@yosefe, @alex-mikheev, @shamisp, please check the update in UD tests

**Comment by yosefe** [comment]
looks good to me

**Pull request merged**
