### PR TITLE
UCS/ARCH: Read from `cpu MHz` for CPU speed on x86

### LINKED ISSUE #2792: Frequency read by UCS on x86 doesn't match actual CPU frequency
`ucs_arch_get_clocks_per_sec()` in `src/ucs/arch/x86_64/cpu.c` reads the frequency using the CPU model instead of information from cpuinfo. This is incorrect when the user changes the frequency of the CPU to something other than the base frequency of the CPU. The correct CPU frequency will be read only from `ucs_get_cpuinfo_clock_freq` when the CPU frequency is different from the base frequency.

### PR DESCRIPTION
**Pull request by rzambre**
Fixes #2792.

### CODE REVIEW

**Comment by hoopoepg** [comment]
ok to test

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7448/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
as discussed on conf call, suggested approach is to have "slow and accurate" and "fast and inaccurate" version of get_time

**Comment by shamisp** [comment]
@rzambre what is the paper that you mentioned the other day ?

**Comment by rzambre** [comment]
This is the paper that I was referring to: https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/ia-32-ia-64-benchmark-code-execution-paper.pdf The paper talks how to measure for architectures that do and do not support `rdtscp`

The paper's methodology also seems to be used in courses at universities: http://cseweb.ucsd.edu/classes/wi16/cse221-a/timing.html The infrastructure is basically the code snippet under the `Examine the Assembly Code` section 

The overhead of this infrastructure is 16ns (similar to the current infrastructure), according to my measurements.

Since UCS has different types for start (SCOPE_START) and end (SCOPE_END) of timers, I think we can forward the `ucs_profile_type_t` to `ucs_get_time` to call the right sequence of assembly instructions. For SAMPLE, a `rdtscp` followed by `cpuid` would be the right thing (so the end-timer portion of the infrastructure), according to the explanation in the white paper.

**Comment by yosefe** [comment]
@rzambre closing this one, replaced by #3070

**Pull request closed without merging**
