### PR TITLE
TEST/UCP: Run un-aligned test only if ENABLE_PARAM_CHECK is on.

### LINKED ISSUE #683: gtest fails on shm/test_ucp_atomic64.unaligned_atomic_add/0 if build with --disable-params-check
Running the test suite fails if build with /contrib/configure-release.

```
[ RUN      ] shm/test_ucp_atomic64.unaligned_atomic_add/0
/var/lib/jenkins/jobs/ornl_pod9/workspace/contrib/../test/gtest/ucp/test_ucp_atomic.cc:43: Failure
Value of: status
  Actual: 0
Expected: UCS_ERR_INVALID_PARAM
Which is: -5
<... output removed ...>
/var/lib/jenkins/jobs/ornl_pod9/workspace/contrib/../test/gtest/ucp/test_ucp_atomic.cc:43: Failure
Value of: status
  Actual: 0
Expected: UCS_ERR_INVALID_PARAM
Which is: -5
[  FAILED  ] shm/test_ucp_atomic64.unaligned_atomic_add/0, where GetParam() = mm,knem,cma,xpmem (31 ms)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #683

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1681/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1072/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review - should fix the reported bug

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
