### PR TITLE
CUDA/JENKINS: update cuda module version

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by yosefe** [comment]
```
/scrap/azure/agent-04/AZP_WORKSPACE/2/s/install/bin/ucx_perftest: symbol lookup error: /scrap/azure/agent-04/AZP_WORKSPACE/2/s/install/lib/ucx/libuct_cuda_gdrcopy.so.0: undefined symbol: gdr_copy_from_mapping
```

**Comment by bureddy** [comment]
#5446

**Comment by bureddy** [comment]
@yosefe  Need to synchronize gdrcopy module update on GPU nodes with this PR.

**Comment by yosefe** [comment]
This PR fails testing, and will pass once Cuda drives will be updated on test nodes

**Comment by yosefe** [comment]
replaced by #5497

**Pull request closed without merging**
