### PR TITLE
UCT/MM: Use smaller memory pool chunks to optimize memory usage.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
Can we go even smaller ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4732/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp now it would be 2x of the FIFO size
@alinask pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4770/ for details (Mellanox internal link).

**Pull request merged**
