### PR TITLE
UCT/self: atomics,put,get added. UCT/base and UCT/sm/mm changed

### PR DESCRIPTION
**Pull request by shssf**
- ep_atomic, ep_put_* and ep_get_ moved from uct/sm/mm to upper uct/base layer (no changes in these functions).
- moved functions are located in new uct_ep.* files
- UCT/self reuse these functions
- name of the functions changed from, for example, uct**\_mm\_**ep_put_short to uct**\_base\_**ep_put_short

@alinask please take a look

Ignored for this PR
- spell typos in mm_ep.c and mm_iface.c
- A few functions in uct/base/uct_iface.h are logically belongs to **\_ep\_** and have to be moved into new uct/base/uct_ep.* files

related issue [#824](https://github.com/openucx/ucx/issues/824)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1480/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2127/ for details.

**Comment by shamisp** [comment]
@yosefe - how do you feel about this ? Is "base" a right place to share communication directives across components ?

**Comment by yosefe** [comment]
@shamisp  yes

**Comment by alinask** [comment]
:+1:

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
