### PR TITLE
UCT/UGNI fixes for flags and locking

### PR DESCRIPTION
**Pull request by MattBBaker**
In working on OpenSHMEM some bugs happened where deadlocks were had and flags weren't updated correctly. This should fix those.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1495/ for details.

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/886/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Rebased for the new flags, everything should be in order. At least with this patch set.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/896/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1507/ for details.

**Comment by shamisp** [comment]
@yosefe - is this real failure ?

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1509/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/898/ for details (Mellanox internal link).

**Pull request merged**
