### PR TITLE
UCM/BUILD: Fix malloc hook compilation on icc.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox this should fix rh7.2

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1465/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/860/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
