### PR TITLE
BUILD/UGNI: Avoid pkg.m4 dependency

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11676/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/c13f4162802f2d9b54e1466b5d202a35b2fa55ca/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/db2ce91f36387f04fe83377b98ccd85afe5c2634/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/9eb648e1b51e795a0c0e72191f269be9f8c4b2f1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/3e2b19814c8e797994757039a8445d6d781ad9f5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/891c1d36014b690324e13bf47bf4027ae88ca5d9/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/77a1d7a36b41ab2746a133e8383b070714d8ad6f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/2217ecfec8a3b404ea302425f80f2f048d66aeca/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/f236edfdfcde3796ad764d76f5e9d1ad0c8e353c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/c65b8f63d832dda7ed64bcc34316268793f2a87a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/fa022a52a6d22f059d32ec7707807b7569fca4ae/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/972c5a5099ad23006480debcd9a7510062788f88/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/332986aa4e7341d21f1d0ccfe38317d122c060a7/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/f740924d6a0da284485187b934fd31a44fe38dd2/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/1cf7573d4a8963470630c8fe9ef78ad23aa0b213/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/3dccf54da15ad761d81c76bcacf5a5e1b3128985/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/2c3986eacc9ba27c0462cbd68a3fd8fc17cabf3f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/154ce2bae3a2a34cc358eef6242499de70909781/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/85ada0b5f7424dccae34669411ab1e5a0f9218be/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/30684dd283296f1ea5a30d875b40ed76233981f3/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/d084a955647dcda180ac5c5a88f950db2a82747d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/6289d6ab996d41b0532342e11e4686d7239fcb85/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/d285c9e112416b22abc0b44b908f7faea4c7dbd8/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/301c8bba41ecda12d7f4195124af017a1c8a39d5/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/503fb7e4dbc6134a66b7b13aa72c11c1fe6afdc6/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/2fb3607789f2b129823011a521855862414c5425/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/f530c1d31b3ca3b70b5b58494c7083af35d7c33c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/5e32203fa27707665b9d3551ebd632456b1e7dfb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/80fb00cde023a74cecc0571bbed0d6d859663931/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/20552c03444eb2222a00946d86af4caa/raw/7a3f06eb0762c646cc0857d5c1ddfe834b64cd18/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
@MattBBaker @hppritcha Can you please try and see if the check is okay,

**Comment by MattBBaker** [comment]
Build test passes.

**Comment by shamisp** [comment]
👍

**Pull request merged**
