### PR TITLE
DOC/ucp: Would -> will changes

### PR DESCRIPTION
**Pull request by tonycurtis**
## What
Changes "would" to "will" in comments

## Why ?
English fix

## How ?
N/A

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9218/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Looks good to me, squash ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9257/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@tonycurtis still has to be squashed such that we see single commit with the changes.
@bbenton if you have cycles please approve.

**Comment by bbenton** [comment]
👍

**Comment by tonycurtis** [comment]
Not sure how to do the squashing...

**Comment by shamisp** [comment]
https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/
Just to make sure that you don't wipe off your changes, play with this in a side branch.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9264/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
I still see bunch of "Merge remote-tracking branch 'upstream/master'" in the commits

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9269/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
yeah, need to squash and rebase

**Comment by tonycurtis** [comment]
Doing a new PR, there are some other changes

**Pull request closed without merging**
