### PR TITLE
UGNI: Fix compilation following uct_iface_open() change.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4490/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4492/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@MattBBaker pls take a look 
there also seems to be a problem with ORNL bot

**Comment by MattBBaker** [comment]
Looks good. I'll build it on titan in a bit. I'm also working on getting Jenkins unstuck.

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@MattBBaker thanks, waiting for your approval on this.

**Comment by MattBBaker** [comment]
Builds and runs on titan. 👍

**Pull request merged**
