### PR TITLE
UCP: Print worker address length in ucx_info.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1008/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1620/ for details.

**Comment by yosefe** [comment]
@shamisp  pls review

**Comment by shamisp** [comment]
+1

**Pull request merged**
