### PR TITLE
UCT/CUDA_IPC: Backport CUDA IPC fixes to v1.7.x

### PR DESCRIPTION
**Pull request by pentschev**
## What
Backport CUDA IPC fixes to v1.7.x

## Why ?
The fixes contained here are critical for UCT/CUDA_IPC in 1.7.0, discussed and previously agreed upon in https://github.com/openucx/ucx/pull/4431#issuecomment-553119372 and https://github.com/openucx/ucx/pull/4431#issuecomment-553146033.

### CODE REVIEW

**Comment by pentschev** [comment]
I'm not sure if we should also backport https://github.com/openucx/ucx/pull/4488, should we @bureddy @yosefe ? 

cc @quasiben @jakirkham

**Comment by yosefe** [comment]
ok to test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/c10039de4e923dfc4f2358175fdd948a7e7849f4/_main) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/b2912e77025e89b34be2489b1495cb7e922cf2e1/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/d88a4122cfc4677abd98cbb81955a654b4cbcfdf/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/a8cd23496b8f16a9b929d0696aba02fb086fd8f0/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/6e126c5fde8d9ff02e695c4deb5f3701aaf46de2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/cb4b96ca3b2300fc8808a5941267d31e0f1cbf9d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/a612d26ce05f9eead62e3c75b2b7f0cf839fd67c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/38568d2e261edb90385a7365799742b409f5504a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/858bf93d29bed55e4108c2acaa8aa4eb0e8871f6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/2da6a3de1ce22b03e98c5f9fe3ce2ca42e423eb9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/c27d22bb5425b8acf922a8c83381e6f7172fcc1c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/8b8589e5de68d283e05335a6695cf0a626a31e6f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/ab82d72f5e5a4d005acf7e3123b2d1aae4dbf43d/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/b74a538893bdf5697544bf5c9fccea8d8b68cb24/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/f414225389690fad32c46fc3984ecc2510835b9a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/fc930e7e350d47c0ddae910ae8e0338addc2ae98/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/6710c2dd59ed01b1cd15b6f02e8b6475fad505b5/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/9ac2d66b768da86f7a73cb9fbab54749ab13286b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/cd64b46496d47ec2234ccae6092b75ac14d502fc/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/da97c9421e01b6cca008ffbcbb046c26c3a9167a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/149bd0b793c7df2d6cd8fc0437cfc3d934dc8de3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/f357dae379097b55bf15badce457def9cf45bd72/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/35b20385b6c1aba6f7efcfc382a0aea91964ee46/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/822fb5f91711bfe363790bd028ac2619540dd6c7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/eba374e444a87cb0278840e0089d59b8/raw/86614737526431a6229060220010bb23f75f0fa3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@bureddy can you pls cherry pick all your test_jenkins.sh cuda-related fixes to v1.7.x branch?
currently tests are failing ..

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/ec45198161522dbd0f5694633991a572d864166b/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/0cefd9aa72378706c96f03a4173bfe2fb6015fee/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/d6dfaae72a0bf7baba9d15d1eddaa7eb1c8f6139/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/9415acf4fd264e70ea3b8467e60d896700615349/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/97da2ca17548414d08f286bec07ad4b900903e2f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/15db20c107ad6a1b3fddeb8f311d010942a88fc5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/357cff7ef0e1b8d7f4b58184698ba1c68a264f2e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/13ce6009107cbed92361b562c1aaea0afabbae5d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/8f8947e09de7477b106a4ac6911d3d1f80ebeff5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/8a6ca0b86f6df92ac63d8f1dc2f3367ac8c1327e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/71ac60464428592cdf2d7dd4a06dc2e2f9d6f8e2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/c0a0fda0c91ca53ab235b3b244c7831ed131acc7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/e92edd125d5c6123f3ead67e549c4880a6e5bafe/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/87bd2b4d2b16caa0b0a08080e0a20c92544b4eac/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/7f5badae743b45e8348eaec14a09ad65c885a029/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/655661f6ba9370f3635f2a87e43aa72fbed61782/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/029766b406f8a02a2cbef9797bfa4f28c69b44b2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/ee159276e6ec1eb4058623215b25a5fa0f595ea0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/bd4f1b1257ca2269bf5fee01ad920f61c863245e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/9c93ed09abbcf5e70cf4d61118f7a0480ada45be/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/69e29480c46a62de73c8f4a102218a7fba16176a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/ba0a3213701189574ba7a5fcda7fe040be307c70/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/3cec2e8051472953808b0d8c79ba2797ce55013b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/47e3217128f2883dc056513227fdf7405a1e1b03/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0b1f603dcb2159a879ab47cc94ea817d/raw/a0b4bf7b82cfacbc1d158ddb7698b2a917255136/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
driver umad hang
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/7936eb1501f3b248d3ef81bb32269f4e7616ae4a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/27012e2abe9fa1827c2c0de1ca02e0d1ce9c88c1/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/ecca32f6db60d4b96d2af2795968425564756302/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/3ec535fc0fcd9e8fe8ce4adbc8adb9e24241ac53/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/d3067c27173a567333843361e037af91617e826b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/a1d24d849831504393df1dae9f82d9c1ba4d76e3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/fbf244474801e5fa650e56f619182a9b82ed9e39/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/8e9d2158f3eb324d261228d6686e8e3412321b8f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/bd43bf168c04c602b59f7d2b3f2e1a9d0237686e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/e33129efedce54b0ca1ed5f16489a1ef4305b4e6/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/49a0d7b5fce4999032382bcd4cc0ee6d5566d337/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/0fca22cf8a3ef6d044eb4a1b56c1e678b51dd60a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/e9f6766d1e2648d0f5a2a5e74900b6dc8440b3f8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/5b6e2a0b88c217be12941cc5e3379c9aec61f635/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/d6818b07ee58cea776f0fa68b7b6fbc030c9a968/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/8b167a263d928141e6a7bddba2202826aa5baa6b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/26268dd6ab83fa0a070a33c5b58f62ad849f364e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/f14c1b282d20e54fc735b9ceeddeac9a2af5d344/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/09188178544421538dcb31aeda1d259dacaac734/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/421450682ee1d0856c7cdc8831fa89ec95ac30ec/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/1b172aad7fb60033b169da12e2e661609876f1bc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/eb1cb13efda99f5df9ec484a3e8134886a4f2df4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/3831c75768f8fff48c944999312afb043143505f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/2547336b595ea5c5ceac7dd155aa84dddcf6a426/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/45ef1f7e2708d2a5094345bdebdba6fe/raw/649fb520f50f39168f3d9d3b0660b7aa93295c30/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by pentschev** [comment]
Thanks @yosefe for merging this. @shamisp mentioned this was the only PR we were waiting to tag RC2, so maybe that could be done now?

**Pull request merged**
