### PR TITLE
UCS: fixed typo in macro UCS_INIT_ONCE_INITIALIZER

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by hoopoepg** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11812/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/cb558d23f61822fc3a46a6da33235cb9762eb4f6/_main) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/f7115acb0f4dbe7d589c3f41a6a9b9830e531189/hpc-test-node-new_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/3addf51e824d585dc861aaa27857e16868c107e8/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/05c52267658819ed67d4ff2874f4980f3cb12c6e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/82ee37f7ef0942235d4a9b204d2e042f7715168d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/3b23d5250e3a4f9d466fbb40225d171c36115a4d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/a843a727dd4a07490b6a299137eb3272e606e44d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/0acf6a07e955d1eb49c7dc363b041addb5c54364/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/9bd71e2eb6f764d488a936e49f56ee5752a1d960/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/4081aec8846a24cf35788ccde48872f1d010cd4a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/c81b17045269aae13debee85ddef8667388d226a/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/9603a16d8c3eaff13d9aba42dbfb3d6ecaeda6af/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/41de603511a6aeb2a0c0e70d5737591f9cc04f58/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/0249797677f6f79c86355e3105b9be148f8cb842/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/9972b4545294549266e3e9196eabfedb7d260291/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/9209328c2c4f9d009c3105c880138b2f77324d14/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/64123f4610c97b60733b294f9135d5d6df192819/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/36f24117f58f370d2a9b469361b7f336a347d43a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/81bfbb28d11c4ec37bbb1420dc5ff95594485b3f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/4ddd5bc6d6a91341fdae4ba0b8657483c92ebac5/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/c52691837532f3563dff64d99098a949f4cee0fc/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/0ff8433cdd80f012d83670a2d6826674a6d16473/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/b7b0223e32ccd48fc4d6d739b2978812a2bdf114/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/b036231e8e7eb79a9cd3542e536fe79d27ffd578/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/4fd29f9cf12fa73cdf027e6d31be1a03cb7782b8/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/5002d607230f195a0e3699419faa206b21ce3a2e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/92da16de45fdd5f9a16c4342f9c062983f12a655/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/6e614d43fd779d746c87ee5e942c4c7d81ae15dc/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a50e602c4d1e135177186cceb65e2c80/raw/0f9c60abf1a1a78f7fc8a01ae6c617e59c8faa57/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
DCI stuck
bot:mlx:retest

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11816/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/487e8291d1291ab16afd011b0344ff2418cbf809/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/b83eda91b85ebc6382e30416225f25531390db33/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/8bf04a0e05c44b7b5de34b209f4587f557c111cd/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/5912ab65468d93d3c3f8c17781423429eb612f7c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/4a40518cf152fe969fe4b501f556e5d5837b5fc9/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/6a474490ddf2c5e605bd9d41eba1c2225c4aac6d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/38ded0c601fa4bd4570322cb791efc33d9de0a1d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/2c237d15cf7e1374d202d80cb463b489670c7dfa/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/1874654d43cbd477a0d90ba8de43ade7265f8473/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/c28cea396e1e240f7d400938e748dbb6c5c0fad8/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/ca66fc801c0b46e127a8fe38e0abd0d0daf756e9/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/bb308563808065b92ea6d5a163207cfad09a7cb6/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/056cbc5187a0127c53999b32da52b814cf1f3162/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/a8164fdbd3b2c13cf4ac014eb2b7188fb3850645/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/482c9922d77eabe63a550886be9b44b408f88401/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/9929b57833d4fb81e7bf13c42061b4bbf56296b7/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/4feb8903fb6b1a70e24aa54ef203985675b770db/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/499e0f9386e6b70316b0cc6adfd9c51f4fcbee79/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/4f9bc05c66b1f9e4861d7d2abcbe82a7e3861794/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/d29c17826a221a07eefe295b802d4cd5931981f9/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/f6a0f5a0968bd19db52bf6f021533a7b73716335/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/2153667769d85082c1da98568d61d5bae3975b0b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/767567d9562cde5b6fa61508bf52259677b7c359/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/4f347158cda721408683ee3bc32e5287549ba641/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/7ca014577fbf55e6affaffca7257c7a20f58cabc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/135c90d45e772e6b2188a2272f5ada15da986a77/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/9d8286e8c917edc0e45f333801369ba98900bc2b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/8d8823193da0b9b3fff8a8fa21edcfcb909be9c6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a785a4844cbdebcfdb2e85c83e0a028/raw/22dd01980fa69387006297f73032509eec0096e1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
