### PR TITLE
contrib: Improve local usage of jenkins script

### PR DESCRIPTION
**Pull request by igor-ivanov**
Fix issue in case launching jenkins script manually as
env WORKSPACE=<path to project soutces> <path to script location>/test_jenkins.sh

@yosefe @miked-mellanox could you look at one

Signed-off-by: Igor Ivanov <Igor.Ivanov@itseez.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by yosefe** [comment]
ok to test

**Comment by yosefe** [comment]
:+1:

**Comment by yosefe** [comment]
@igor-ivanov please start the commit message like this:
`CONTRIB: Improve local usage of jenkins script`

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1295/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1296/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/702/ for details (Mellanox internal link).

**Pull request merged**
