### PR TITLE
UCS/SYS: Add functions to allocate/release memory directly from OS

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1812/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3752/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@bbenton please take a look as well

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by bbenton** [comment]
:+1: from Doc/API

**Pull request merged**
