### PR TITLE
UGNI: Fixing broken disable logic in config

### LINKED ISSUE #5731: UCX 1.9.0: configure script insists on cray-ugni support
### Describe the bug
configure script insists on cray-ugni support even when --without-ugni is given on the configure command line.

### Steps to Reproduce
- ./configure --without-ugni
- UCX 1.9.0

### Setup and versions
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Linux login4.ufhpc 3.10.0-1062.18.1.el7.x86_64 #1 SMP Wed Feb 12 14:08:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-ugni=no --enable-cma --without-cuda --without-gdrcopy --with-verbs --without-cm --without-knem --with-rdmacm --without-rocm --without-xpmem --enable-stats --enable-mt --with-avx --with-verbs --with-rc --with-ud --with-dc --with-rdmacm --with-mlx5-dv --with-ib-hw-tm --with-dm --without-cm --without-ugni
....
checking for CRAY_UGNI... no
configure: WARNING: UGNI support was requested but cray-ugni and cray-pmi packages can't be found
configure: error: Cannot continue

### PR DESCRIPTION
**Pull request by shamisp**
Removing "guess" mode that does not do anything. Fixes #5731.

### CODE REVIEW

**Comment by shamisp** [comment]
@ca-taylor can you please give it a try

**Comment by shamisp** [comment]
Ok to test

**Comment by shamisp** [comment]
@yosefe  @tonycurtis  @matt - please review through gitlab.

**Comment by tonycurtis** [comment]
> On Sep 30, 2020, at 6:06 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> 
> @yosefe <https://github.com/yosefe> @tonycurtis <https://github.com/tonycurtis> @matt <https://github.com/matt> - please review through gitlab.
> 

Gitlab?

t

**Comment by shamisp** [comment]
@tonycurtis typo 👍

**Comment by tonycurtis** [comment]
> On Sep 30, 2020, at 6:10 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> 
> @tonycurtis <https://github.com/tonycurtis> typo 👍
> 

Like butbicket? :)

**Review by tonycurtis — CHANGES_REQUESTED** [review]
l. 4 should have a period at the end to be consistent

**Comment by shamisp** [comment]
> l. 4 should have a period at the end to be consistent

Do you mean `ALL RIGHTS RESERVED` -> `ALL RIGHTS RESERVED.` ?

**Comment by shamisp** [comment]
@tonycurtis fixed and squashed.

**Comment by shamisp** [comment]
@tonycurtis ping

**Review by tonycurtis — APPROVED** [review]

**Pull request merged**
