### PR TITLE
UCT/RC/UD: Remove sl and path bits from ep

### PR DESCRIPTION
**Pull request by brminich**
## What
Remove path bits field from ud and rc endpoints
Remove sl field from rc endpoint

## Why ?
They are not used (just duplicating iface value), but rc ep address decreased from 72 to 62 bytes

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11435/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 16 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/0f90138129b75d07248f0a849e4e0b024ab56691/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/9e99f6fe266073e2080f4bf71ad243b2323bf273/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/746ffff205ed716ea6aaa491140d4d3c2e938936/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/a4c81e478881833255b80c9aac1003b93721a8f5/hpc-test-node-new_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/f815238446a86c4518861bc23bad9a626fa08ca3/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/f18e98f1441131b35079c84af5d727942da8d0da/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/407c3712b0302ddc20a76df0865c93b7ce8505e3/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/cfd8e96d2b3204af813dedea099e448e4874964b/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/c6311c192aef3c26916ef35153be883e9f4a83ed/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/47e88fb6b7ba95ac58aed5a300324ca43331e14e/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/cff0daa6e613534f8c392a41b16dbcc360176c12/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/cbf31d6c4e0bf12f11f15b986b22c05305426a58/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/deb34dd27fa8e31f38ce6eb5307a4fdb44c6e047/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/5ed6b1d377acdfb684d3316ad034b6e307003df5/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/a2a00e5a67dbe2e5786ae77fc8c1a4da2acc5af7/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/3e2fd9f9ec739d2868a1f05cb9381eb7a18edde3/hpc-test-node-upstream_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/d433e511c6d585cda5f5087e45b075b5976fbbea/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/ec123b667c494effa8064a72f7d3bb59041d604a/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/59b76657f3c4bf2c7cc677a3049bdee1afa35c12/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/e4a650d5eef11b40cba56465df1d3bd13481d2e4/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/a17733f17ef66528db0c1d719b9484c05f57d5df/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/fcae0a61d5248d5eb6b994e94a147654e4b25a57/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/f6313a0ccfffa72ed774ad2552c11d783ff2935f/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/8a80671fb71b5baed28725d20a68237f02c87ce0/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/cee70296373e78ee2583698b01009640787770bd/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/c5eaa14f624f5b1e13aa51301ddee8be0006cd0c/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/1584fb447b7ebe0b5cae9941a35a6e59c1ff2bf8/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/ec51327c78dc67066477dbd8fbb8eb9fe9185e04/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/98a1a9e89b118b456bdf3fec775289995ff9c9f9/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/1997d1e3cd16375ffb74979e5b6d1a8d0cba5cb7/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/c376826c2ce5136dcb9dc009c962c0a13226ec84/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/63e26849bbc2ad130e82734bbbbf11762fa12e95/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/91102e97b1045680465008c8e95019b3/raw/9311c56373013afc710dfc2a7b90e2bca2504ec1/hpc-test-node-new_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11447/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/a83d478bac8a16ed65ee134fd6f476b28e11559f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/07a9a508b5420f4cfc20d422530f702e7acf7d82/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/deccba55b8b62688dcc24ee0c575b24a8a88e8de/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/68877aadfb71e6219b4365cc6335052678cf5b6d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/555e1e50a47abbbc6262d162e81019072312c2b5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/83dc581c40022c478e1e679a027446c28b123fa6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/d74800bbe46ae73168dd6d431c8af253066d1981/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/41107e4fb9210ab50c26d9e0e97987d473dad275/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/51ca9d6e5b55640cb2cc4fc60a53ac431d975e3e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/21c65010ad5d4e3369ab0b337eed84fff9e13613/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/805734178add1e46c39325d015478b0e9293ec45/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/720f4319bc5241c49d9739ca2811effe503ba63b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/533006aa5d08b3bebd4d518a6797c46fa90775a5/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/3a16213ff07e397554f6393743284876678a6307/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/bf2192f9eca2e43f009f5495754a0991af6020db/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/fc0d0e4dab85ed2e4f6962d0e4844bd3db64b87a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/fd2ee458ac1566f3bdb20590000c86d8a38e66a8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/506fe38db9287cfa91baeb9cdb78dd66b5ccf9ff/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/f58108fcb0318a5e422c249284cada98fb77662b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/06e4e10a03ae7dac85699a2caba9bf235ed28780/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/03b245741c3370e4c6ca749b72af5fcf2666ff6b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/4af8bdaebe335f776aad44619e1d3e5ac1396d6e/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/134ef53650bbf61b03a9041f5df25fec03a1f352/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/491e1e187237f38757d1145483e083ba0cd76342/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/3cf177e57eeb9fc47d3a6210c713591881c652f3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/0e9085e1214bed18b77c15bf89c755d1c25448a1/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/19e88619463edbab065c8089c4be6aeab3f0c462/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/43134e0e2dd48d9dba7f633b4edb5bd2b18eaa02/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/dd2b6796017a35d9f0f0f50806be8b1e535c3711/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/ec1902fe6984f2d63a219d5935f2cc771f6196f3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/e734463b7f15a14ba60a9ca10d5262e593acef2c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/d827d0018b3c942113b6b9fb6edd38735c7e4e97/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4390eed811a0f8081264fb489320b4cd/raw/592e61f4fae6f59e761c26246a1072c060235de3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
bot:bgate:retest

**Comment by brminich** [comment]
@yosefe, ok to merge?

**Pull request merged**
