### PR TITLE
JENKINS: improved rpm-based systems detection

### PR DESCRIPTION
**Pull request by hoopoepg**
- try to detect rpm-based distributive by filesystem first, and
  try to use rpm in case if well-known files are missing

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7194/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe ok to merge?
this issue prevents all PRs

**Comment by shamisp** [comment]
What it prevents ?

**Comment by hoopoepg** [comment]
on one of ubuntu systems command ```rpm -q``` hangs permanently, it is used to detect deb-based systems to build package. this fix allows to detect rpm/deb based systems using more "natural" way

**Comment by hoopoepg** [comment]
here is hang log:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7184/label=r-vmb-ubuntu14-u4-x86-64,worker=0/console

**Comment by shamisp** [comment]
Okay so this is a workaround for some ubuntu rpm mess. Please include justification in your PRs and commit messages. It will make life easier for everybody.

**Comment by hoopoepg** [comment]
@shamisp done, commit message & PR are updated

**Comment by shamisp** [comment]
thanks ! 👍

**Pull request merged**
