### PR TITLE
UCT/RDMACM_CM: return correct err status

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
Fix error status

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12482/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/fd11d096e8d9455f221e88127d4e3a142119bc6a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/30a823b67dd5dc114b0430c0888de996e3bfc612/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/04acad1cb75e2a22648b8865ff172f662d2de119/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/2a44c30f197fd872004c7291ebc9ebdda232ab4f/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/fd33bd457acc296fdde846a64aaf14f210a169d8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/3e4197b938139b1ebb3462177c419126985a1cb1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/b4d2a27d01eeb347091782f1965873c03a5428f6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/c99ac5caa72b2cb5a105a41e7e3436a971bd1c74/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/23328c8fff0a0106f5c32a4684d3188775f770e4/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/70b8bc693209addedeb5159a0ca05fcff8c5fd5e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/ec2deac1d202d95063ad028c618b8c66ac778dd3/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/12575713961ab109a55cee19b52a10bbbb4460d1/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/913b6592d6c3ad93c3c61b9c69b1f7005cd2bc18/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/136088da67b7ce52eb7838d8167b19fda11d2f27/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/1d3ad538fd676c92e3456af3a91e2ff3662b3964/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/b4927566e460bec728bb894479cb7a8d724432dc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/8819c3e921d4d678b033e9d535fffe58cce7e809/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/ac5324c300e18cf8a768c54814743db047f68123/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/fd481025c8e02767abb55333e41b20ff760e1d35/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/188f9bee32eee97e1174fae044531daaf0c35873/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/e482df5240c4c799f83b714898d1a31d93518326/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/d22fc088a3b8db54110f2fe2a4acad609ff13ae7/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/6c4ac066c3c65790efab5c1d28d7134ce40eea1f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/469e3585c3d8b6f3d4e304ba073afebf9c5dfc9e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/baf7b283d03b5a89e32f029202613a80d6a4604b/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/0554a33c6113c4305f9f1dbdd92f5ada3bcfd567/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/f8989914727c473ac0d9e842b80671add13962d9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/061c88180049e90fa24c71cda28e3ca1fb346fc4/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc264f82e0cf886290202f4433d56bed/raw/5f2cfbb30635d8ce6d6e30f980b518dafe90ca6b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by alinask** [comment]
bot:pipe:retest

**Comment by alinask** [comment]
@evgeny-leksikov did you see this failing somewhere?

**Comment by evgeny-leksikov** [comment]
no, I just sow common IO error code instead of actual one during debugging new UCP code.

**Pull request merged**
