### PR TITLE
UCM/UTIL: Add error prints to mmap() failures

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12805/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 13 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/b61293a05a03a895fbc175f222bb230290e74190/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/16082ec51d0dad5be9a2f2a46e0bd3bd0e07b31e/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/bacf4c6b89b419566945327fb9502e0c0ce86634/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/9e685707274057effa257bf3c760b644563680c3/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/083cf9d3092a8b0aea7deb21b8ed44fee2ab3e83/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/34c609f7b010583fdf8a3488b9127698ef1774e4/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/4c5355e51d81d41aa1b1bde71c2f8ce2cf3ddfea/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/6066a2ba26e154adb931764ae255997c2354f477/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/290048f2316609ca9d28f6b0358d403fda23f117/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/1cec741ba5e0730feb148833ca4c3c64ea6b2b16/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/fc86061315c0561cf86b3d58509780dbb9b7f287/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/1a9ffb95847d4588e6cf3bf483461ac2a775ab0c/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/1d22ebc83df0d5952b86ebee6cdb5c7e53bb87e8/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/069f1ec096362217f1b30687286887f6b6776a72/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/04f68cc850620f4dbe457105ec94463a9067127d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/179c21b640bd208b9b6e3ec78011bba5e2acd470/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/0844937a81b36584ca6ebe249875a70e747f246c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/6e3d864347a67934a4dd94e3620232868077a465/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/21294c8b30eac69f34d924b7dd7648a3444b2140/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/440634a49d3d44f709dce35122e87f8596238633/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/71bde5d06768feda851e15de6190b71e38f07e9f/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/c63605b1db3163e31963090342f50fbd571ffd64/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/5eb948ce9632832e84e20d7997fd1c9b9839d61f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/e123e92792527646be2a0b3d6632a8c81b3cc848/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/c3c4a251119236637067300ce1526922972fab1e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/927e85c1a199a1c1308ac3c8046044954797f86f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/746d427f534deb7fb6fa44dbf2438c5ea5a536c4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/4751438b574683a8d91cb41bcaff565c03f3573c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1b41dbf4085d259d1cc1fef1967f5c55/raw/8e34763e4ea92af557c9cb52cd3af705e83fb6b1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12825/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/89acdfe494cc8d4fdae406735f091ca043162f8c/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/eacb669e0d99bde014ed059daf95537d502c4127/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/a8a1d84ddad494a64f0b3cebfc110a43cc208ff2/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/585b2d387c28537c2bf7c699a8786951fe257925/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/0f3b05787ad3be8ad3cdac5b3ae156e75ff6dc74/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/39fafe785f0b13ea0b4f9818b766226a11ebdff2/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/69ef9d46aebf7ca80b5244bc9598ee8606be413c/hpc-test-node-new_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/2c4417a7896b1cd12f3dab8032c8c16c11e6e96f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/f7b1056aa2cb3de705ed737c5251bd97335d1555/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/22c61f654cf053dff462f5633473fa5759f68802/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/6f7812c7b571898d6d94ecde307944a527ca8d2c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/89c624b22bf670e44fbf5cc915c55cdd96ceb069/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/2b0e828770557a31c49fb2df49f5e840439f67ff/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/115b0fe139653e8cf9c37f4c800f3f77c2b72a0e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/a9cdcc58d3bdc5348daaa9694ea535964aa8551f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/f8c55d2f827a857d9ae3a9869ceee25ce574a8db/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/39fb7ac4a38e91233f7ef4fc433c055e2659c48a/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/6762d37b14e9a870fbb8db041d55b8ef1e63fb3e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/06cd004fb7a6299f857bef4f147108862d3a7261/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/ed2b138911a0fa84c6a054dcca7ba703df582963/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/e879c1593a925b3535b4d41427aea9f99caccce0/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/65599ee77f5a79b2794766d37b13ff35adfc234c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/a3d2cbb76ef994c2d463d8a006a6f937a766cdfc/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/b24ca1f2fb7228a3b9ab6b79bdedcd57c7441138/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/b42602aad427581f598edbaf674d6c1901c00df1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/b6c87b1ab9251a9483dbfb9cdce2bf6ad2a6e1e5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/3ccb9a73f8a5be822600efe18a826eb3f1ba64a4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/0ff7c1344e56a21acc1c1943f7b3598ccca72035/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f85d29451e24acb6ce6769d15d85c79/raw/84f00bbd08694b43a27b9e3ee31b0074dab9b52a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12833/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/48ae0cdb81887beaa670c85f88d9761627e259d2/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/a55be68a21c076c3e2129795d4f8484d88d8ee6f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/7351bcb921a38a00b96748f5ea9ca10187d45a2d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/e2331faebe19f8e401e149b204753f18c5c180a7/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/14646c4e905d70b3dc5ff04a9da6e0a6007f1a49/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/ea39565cf482a4ed2935e8d12bda8c8dac177b4f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/81f61b8e0a0700614d0561475fd1afdc0680d6fb/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/e46517442584fc863f1d3741ae6ebf6ed3c63356/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/c1b831648270a0e0e5731a3540637b90338321c6/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/70d735ed5c5a460c051cf67f0903fc5f073c94c7/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/da38b9ff4ba1750eeba13fe337b0648cbbe057d0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/2baca7d28633ec926335937fa290e82c69850154/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/615817ec2fe77732713a129680b29a69a6974fb1/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/05756954a54937a7d262c15e9ad23081629b8892/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/7e007311f00042ad542c6f0b69e5b87601656b5e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/4fb6664d7f5ebc1709866a717936e6b34faf0d00/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/1bdc7a34d2b55f6bd4456c6569f650b522217216/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/96fd7e1ea77dcdd897486f0be5eecb81a202438e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/1e688198e920fafddae7e80d71a4196610974cf4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/8c1f7559cbc6314db8e781e05b3a331089cf2630/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/8e1f9925db012a8ef60344a5689bf2bab1e04264/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/b8c67add68308cb2c88b744550e60d4113a5eebb/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/901e83f54c08cb649897218c28caee0e004ddd17/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/8fbe1cc3e802e72f0a97268379c4c5f17ef33d4c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/eb036bca493d04480a2b5b991cbda336081f177d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/1b4a14b4b8d0c0db1a86222ddce89e54d334759b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/23c5d96920772014de16ae957cb84bab5d55e181/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/5372f9fb2af580d6faecefb78cc0281d69e52160/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d5770f6889bbe962d2218d4fddb04c0/raw/d1b553b23b266b4d686a142a7a38a6a85061f4fc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
