### PR TITLE
UCP: Fix for maybe-uninitialazed warnings

### PR DESCRIPTION
**Pull request by brminich**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1115/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1719/ for details.

**Comment by yosefe** [comment]
:+1:

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
