### PR TITLE
BUIILD: add exclude list for coverity

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-sharp-pr/1/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/544/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@miked-mellanox - seems like mellanox build failed

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/547/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/548/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1131/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/549/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
@alex-mikheev - jenkins failed on valgrin w/ ud
unrelated to this PR

@yosefe - please review

**Comment by yosefe** [comment]
ud test fails:
```
14:16:07 [ RUN      ] ud_mlx5/test_ud.ack_req_window/0
14:16:08 /scrap/jenkins/jenkins/jobs/gh-ucx-pr/workspace-2/contrib/../test/gtest/uct/test_ud.cc:173: Failure
14:16:08 Value of: ack_req_tx_cnt
14:16:08   Actual: 2
14:16:08 Expected: 1
```

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1132/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1133/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/550/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/551/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
