### PR TITLE
UCP/WIREUP: Fix wireup hang - switch to next_ep after pending are sent.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1014/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/438/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
