### PR TITLE
RPM Spec: bump version to 1.3.0

### PR DESCRIPTION
**Pull request by amaslenn**
This commit should be merged once we are ready with v1.3.0.

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg can you pls port the recent ARM compilation fix to v1.3.x?

**Comment by hoopoepg** [comment]
@yosefe https://github.com/openucx/ucx/pull/2379

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6476/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6490/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6498/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
Let's wait for a formal release to merge this in

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6502/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:bgate:retest

**Pull request merged**
