### PR TITLE
UCT/IB/UD: memory reduction for ud/ud_x

### PR DESCRIPTION
**Pull request by eladpe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3828/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1860/ for details.

**Comment by shamisp** [comment]
Can you please use a bit more descriptive names for PR subject.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3829/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1861/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3877/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
The latest failure was a bit more interesting than usual.
```
[----------] 4 tests from ud/uct_p2p_am_misc
[ RUN      ] ud/uct_p2p_am_misc.no_rx_buffs/1
[pod9:11278:0]    ud_verbs.c:540  Fatal: ibv_post_recv() returned 12: Cannot allocate memory
[pod9:11278:0] Process frozen...
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3879/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3881/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3883/ for details (Mellanox internal link).

**Pull request closed without merging**
