### PR TITLE
Fix build with --enable-stats (broken on some platforms)

### PR DESCRIPTION
**Pull request by alex--m**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10269/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10754/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/1f297e3aa781ffa4f4802757c7994f3132128331/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/9ea34bd596f5ad2d852af35e63a997831de7cc18/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/17bb9095a528302c1bc41c24f4fa5914369eb90c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/fcd34a50c319105d0e445733d9def1c8b8cc8bfb/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/29864511fab7e8861f9d17ac5a58a8220e5dd63e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/4781e87480df7ecea72d01b5bffc332b41574728/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/8c1b5c354babda93f92e025c847720ca416789ff/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/7eb51bb00d82bbdfebf3544be6ba1e53fbcf65a3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/b4e954fe88493baac10f7ec761a8d982f521d067/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/e1c7d2137cb792fa0e5b9a5a80aad82e7b7ff175/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/c172ce477cac2cf5352246c68718df1a0d429059/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/861c0e2ceb8d31199f17e05ffa0250ecbd0536c2/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/be48159db9dfd5bf092cb8ddd53ee7b841d12385/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/270b3b2981764c2df9ba484d41fa74c54e8c2f5d/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/d246a1c86f9312caf9a451bd493ff0620aa16786/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/bd4f84ab9da005473586c2c21d2b90dcb731cc39/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/9c30928ed523956c9a5de0ec605913703c4e8a1c/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/c51f3ba79c8972afb0a4eda97795ee4cd8c37647/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/f74a88376cfd0ed9f4a235c9c975fb36d337c6a4/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/c0b8eba26c0b8d7a4a50610422b0315489434cdb/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/d11d766fa915aa2dd0908a41f9a02262d5598536/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/323a48b1e0ad78b6e8b7881b69a8a82b725e5e09/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/e97ddd997d4740e1e61edc6e87c3c507020cc7e6/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/b064fb7402e4f8f71f4f6af5f96a2ff6beddc6db/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/691faa1af5d4a8f31d8ffde990a55bea0d4d92ca/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/382d5d6af0fbd49b188d9874b09a881b8c70d1e2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/0509ce8681196cc30c98fa35438ce3111560cb9b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/e73a6cc859f865f15899169ce37bf1ddfc59aa3b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/1c784a8d1676260051f265533f90bd263738266e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/8bd37b0f86dc488f3682ee35cabddc004875c6c2/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/c3ad546f9825a18c6fb165e44bf4ae74fca5dda3/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/60786c9b85a191bdf805d6533d348d9e09a5de58/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a1663a3a70a7829e534efcf56e2db0e0/raw/da91be3d3afc40582f23f5b202c2cfc6f57b9747/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
looks like mostly a duplicate of #3768?

**Comment by yosefe** [comment]
@alex--m , the fixes in this PR were merged in #3768 and #3838
can we close this one?

**Comment by alex--m** [comment]
yes. ( @yosefe )

**Pull request closed without merging**
