### PR TITLE
SPEC: Remove comments from subpackages

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10154/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@amaslenn can u pls look?

**Comment by amaslenn** [comment]
The change looks good.

But I found out that `libibcm` is not available on Fedora 30 and newer, looks like it is a part of `rdma-core` [now](https://bugzilla.redhat.com/show_bug.cgi?id=1404043). From Fedora [build log](https://kojipkgs.fedoraproject.org//work/tasks/7869/34807869/root.log):
```sh
DEBUG util.py:585:  Last metadata expiration check: 0:00:01 ago on Sun May 12 10:35:14 2019.
DEBUG util.py:583:  BUILDSTDERR: No matching package to install: 'libibcm-devel'
```

To address it in the spec file, we can simply do:
```diff
diff --git a/ucx.spec.in b/ucx.spec.in
index f81380e..61bf731 100644
--- a/ucx.spec.in
+++ b/ucx.spec.in
@@ -36,8 +36,12 @@ BuildRequires: gdrcopy
 BuildRequires: libibverbs-devel
 %endif
 %if %{with ib_cm}
+%if 0%{?fedora} >= 30
+BuildRequires: rdma-core-devel
+%else
 BuildRequires: libibcm-devel
 %endif
+%endif
 %if %{with knem}
 BuildRequires: knem
 %endif
```

But we also need addressing it in code, since configure should check for a new lib name and probably need to update function names too.

**Comment by yosefe** [comment]
@amaslenn regarding ibcm -
1. can you pls submit the rpm fix as PR?
2. function names should not be changed AFAIK, we will fix if find issues on the new Fedora30 Jenkins builder we are adding now

**Pull request merged**
