### PR TITLE
UCT/API/TEST: Add "flags" parameter for uct_ep_am_bcopy().

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1864/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3834/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
SIGNALED -  remote completion or event 
What is ASYN and URGENT ?

**Comment by yosefe** [comment]
@shamisp  ASYNC could mean to allow running the callback on async thread, URGENT - give priority compared to other operations, it could be useful to give priority for control over data (consider the case of bidirectional rendezvous). 
Anyway, these are just ideas of which flags we can add in the future, to justify adding the flags parameter.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1883/ for details.

**Comment by shamisp** [comment]
And what is SIGNALED ?
(IMHO naming is not good and we would have to work on this)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3853/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp this PR does not add any specific flags and the commit message only suggests possible names

**Comment by shamisp** [comment]
Would it make sense to convert the flag to a signed value  so we can use it potentially for some internal reserved values ?

**Comment by yosefe** [comment]
what do you mean exactly? currently all our flags variables are unsigned

**Comment by shamisp** [comment]
i see. Okay let's keep it unsigned

**Comment by shamisp** [comment]
Adding @bbenton

**Comment by bbenton** [comment]
:+1: for Doc/API

**Pull request merged**
