### PR TITLE
PERFTEST: fix command line parameters parsing.

### PR DESCRIPTION
**Pull request by alinask**
discovered on a ppc host.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/760/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/197/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@mellanox-github @alinask - I think something changed Mellanox jenkins default behavior. It reports valgrin errors all over the place, not just PR. I would suggest switch it back the original mode, so it will give us a time to cleanup some of the errors that a not directly related to the change

**Comment by miked-mellanox** [comment]
yep, valgrind is fine, but jenkins is sick.

**Comment by shamisp** [comment]
What do we do with pending patches...

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/762/ for details.

**Comment by miked-mellanox** [comment]
we fix it :)

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/764/ for details.

**Pull request merged**
