### PR TITLE
UCT/IB/MLX5: Don't include mlx5dv.h unless supported

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**

### CODE REVIEW

**Comment by yosefe** [comment]
@Artemy-Mellanox is it fixing any open issue?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7854/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7862/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@Artemy-Mellanox does it fix #2842 ?

**Comment by Artemy-Mellanox** [comment]
I failed to reproduce the bug, though according to logs it should.

**Comment by yosefe** [comment]
@Artemy-Mellanox pls port to v1.4.x

**Pull request merged**
