### PR TITLE
UCT/UCP: Documentation fixes

### PR DESCRIPTION
**Pull request by brminich**
Fixed a bunch of typos in the documentation

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/308/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2856/ for details.

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/310/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2255/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2257/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍  

This change requires approval from Bred before merge.

**Comment by bbenton** [comment]
+1

**Pull request merged**
