### PR TITLE
Add some files to .gitignore

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
## What

Add some files to `.gitignore` file

## Why ?

To show fewer files when running `git status`

## How ?

Add to `.gitignore` the following files:

* gnu global default filename - GTAGS etc
* ignore `modules` directory
* ignore vim temporary file.

### CODE REVIEW

**Comment by dmitrygladkov** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10913/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/d603a6d0e23ea7f57609ab91e6ec9e4a0044d6e8/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/3d7205892453e465457af3402e4beca6964c84c8/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/cf3cee2ab3c7c66690ce03045c94f1c9fafb4164/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/d7587ef1b8188e7a405a9cb190b2996c93fd86ba/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/62a5dddc8e41a5c66d7184823fb6a6e53296a655/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/f94451a6e3a1ef1cbb14eef91ae318a368d70baf/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/549e64b03e66f023cea802e2d8994d582331cd2a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/a0e12aafb0578b3bb2cfcbbc3484dc9b0ed23d47/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/766fc6b74b62d8964c197cf2a32315aa3e9a0fc5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/4dd2a8b8c3194d1860df50df93d60e805277f3d0/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/440ff20a941a67d56caed4a22e97b09c59d24623/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/ce7fbbaf6b7130271e8b663ccf4cf12f536c6add/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/f04b1e4c42a0e2099ee20c005d9771a300ce193a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/db7d5190be17a52f098f07dc4acc48049387fa8f/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/d89a84bae8c76c8b1eaeeca31f715a704c92b179/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/84df4c91e0af9dfe7ed632701d7690684c917757/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/24f0a751df0464ff403134f5e29e0ef148d1ffcf/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/fe70241bcad5f84372d0f9147de6ed370e9636b9/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/920ba4c8a014510946b60322389c170e1c819b17/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/b38442ff57fabad319d61d5039be6f04e96542e4/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/4a276c30b3d8b0e122231fe64d8aeaedd95b30d5/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/8ff54a2456fd47fc361d96782aecaf19ffb1cd26/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/5621f79539b1911cb47d8860a72e22755de478b3/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/ffaa6b6cc700afdbff1c901c71a3a9dd1682585a/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/a28c275fd67c248742bb98a0780dc16d7b6ee071/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/2848b14e6f36206d020af44d4afcdcbbadc5b5da/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/506c78b9656cb26a522aa5b8e4f023a9c4ee2f16/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/11d79f2bd6f00322c78bc9082cb96ee0c1a4da12/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/f6eb0ca1beabade4dfdd31667eaffc5b8e44ca85/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/1fc5e4b62cac76142578328e8039fdc7630131c2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/4601ab11b8ca8f55e37b24ec61f78a311f76d8c0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/7845fb04d3356a265fb86a62711d6f41b58f64c2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/07581dfbc058cce91a2d775accc2c646dbcb609c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/e6877a51f29862533c2ec4dbdc6a9c059f93e5c1/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/8271bb91e5f60f56f803408e473f59eaac9aa0db/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/f51f7469d082bf95f224895a184719243e246cff/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d603e3edcf37cb08b59134d58733466b/raw/02c74dbeb2963bfafef74847026e428d8ad58203/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
