### PR TITLE
UCT/API/MM: Remove unused uct_md_is_hugetlb()

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe why we had this in a first place ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11666/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/ea09c87eed86529df80855f4e802736d75239ef8/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/9bc6b1cec740b5dac50c7ebde70d5f2b4c162407/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/68e7464b212f117c16b534c3610d2e8e099ad568/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/330d01d01c55495ebe1d2ca7a3200fd1901d69a1/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/26b7fefd6aa49e548dcbe70a58d1c1e290f69670/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/e46638745565b7bdbcb962bc6f3fad9becdd298b/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/1cd2b364a5ae91f2572dd69a713802dc50a6c88e/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/c710e581cfd6d9387e61c0ffc154cbe20e56b216/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/61158ae1a3caa070dbb41c0d1c3b451c588ce90b/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/0a1feab70996b9ce5b26982a046b8f31fe8e19a8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/e87c1a9618a76cd422fb98bb8b9d4e79e46c40b4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/64f0a0a4276e0e5df8eba6b55ff2865e5c74e8ab/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/f8cb3e7e243131640b777ebe5f9e95c604decc83/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/93667143b1d80bc4b8614d35a5fa1d9403d29721/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/9144362561cfdeb17aef9d8a01e3c1ac654738f6/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/036a00300875b08cd8bb8c1e60d8c8054059c379/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/718e1136db2fc5c7898bb84aa979220430123a14/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/30551ec7fd3ca90f8dc2950c612eebe99dc9b584/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/f7bfff088ccf00654c398ff02e7722953209be45/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/d47ba22ade6184987f23b0d09e69bb1cab4fc907/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/2d24ec443cf0d56cfaaadc151a208d78351f6b2e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/f6587bec5299f90e01673a101f40278e725d3430/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/52a20726bf286a10dd5822389729783734a65e94/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/4516b8d2869aaa293a09a19f0c22cc0a5cdc4abe/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/533321b1846b7b9edb5ddb5951ff790be25173ea/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/391732056566ba49f2ae2d9499e093f6a1b86e73/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/b420c12dbd5c53ba9d0480a2ab33fee26b229939/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/bb034eec68c509bac00141338fe8fb44ed6d1739/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ddb859311833f0d88cee9089266e47f6/raw/12a05bd4b7bd2b17caa978527a7e741b7fd16e34/hpc-test-node-legacy_W3) | :question: UNKNOWN

**Comment by yosefe** [comment]
@shamisp it was added to check if UCT allocated mem is hugetlb, but then replaced by UCS function to determine memory buffer page size

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11669/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/fbdc5d4c0a31851942d9db0187810dd0c720c12b/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/ec0bac1366551cf473fd1eb9a5e3e43164a56f03/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/9a1703920e344d66224a9373add3f9ccd953fce9/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/5f7cb2f18a08f37e913007eee73767ee30ab4e42/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/d9d6f287028b6e0052704254a8e0f83e65dc3508/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/1f8a6bfeb87ceaf7b5855b35f13b149c0970dbbb/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/727bcf719f89a28641b7a6f9b6a249030ebd98f9/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/59b3925b8e82d4671a8897637fe5bb5ccbe4c43b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/632783e352dae2b7c2ad7ef055098604af27d86d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/d48c52869cecd8dcd15501b01387ada5da9f0e90/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/a3d7888500e7006daeba1d9b137272978e52051b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/a520abda97aca8e73797355f1c500a75c0aecf07/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/a6d11c58192a12412bf0f236cbc58848ce94e6eb/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/0b68d506a2499b34dcdfd3803e907fb91f8a770b/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/76862a39c1d2090abd2199afe3bd3aa2180a46fe/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/9f1dca23b2d419ab692f7db2444cebd169ddc744/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/5cf4372fc7ac12b356c9415653bc827083d7490c/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/f06aa849c5a6a86d57b5aaa09e0a5d2148be1623/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/944d5213e5f94ba7d1ed87dd284a247177851e93/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/6da6e9ebe9ef33954228e1ce81a16a3220771376/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/66444106f1ab40cd766db0d1a3e7190e1a2ee643/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/4d08802418ba7b7d10e53d92367c38eae5264b6d/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/446e027d70ea3c0ea14fdc5f0b97a8f1e5928f22/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/6451c53c8771e3825647de86792001d119011480/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/acb14d33951791362caba95c4eca8e9909170846/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/89df15151d4aad6abe44e03e2145d261a82da5ec/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/3f6ab979e3a73848b78cc1070054d49eb956cb23/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/d2ad3074e41f515e7e92e1c439cbf3001dd61eef/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0d859dbd1c36a42cfc7686127220162b/raw/05de87f00fdfe99c0a8e03ad9ac3a4a4127c3dfe/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11674/ for details (Mellanox internal link).

**Comment by brminich** [comment]
RNAT
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11684/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/5edf7bf5458f331a885661f7aa8b1a79b325ab33/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/1cba17c0a23f2b97e909ae8580f114143d56ddb0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/54e0e08fa768ac266343debd4fb21922ed558b02/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/abac1378a63482396ecd91a2c62c4e8e484856e9/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/3e2846428217e28dfa4324eef3bbd3de298c1865/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/6eeaa1b1f36ccd0f8d9d6f004817491515d52972/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/a66d308b62a829629f12cdc2b0031aaa8b9eee1e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/2ce8eff4ab5bc2fed8caae2aab7e6f9c2f9d8239/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/7415c67163b3fe4f9861e5f06eac2b1991cf1358/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/518c5a83c7dbc64b1364f5b9242760b5bcca1965/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/b72d6a6ec1556aa82765beaee3cf421745700f65/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/555eb75c3c718dab3c548657c3531e401f789d3c/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/d817e61500984bdbc82bd4cadaa83fd7cd28359e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/54897fedd2691e445df7b11fef7c9b7b38b10799/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/3b5e5e3ebe658763be8133180e78d4b7abdf4b40/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/9011ba911dc75d3f2b14ed8a62156b15cf98f902/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/f11090cdcc6a1aea6a83c2929ba533edba31fded/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/c66315c1e64107dc4c98d654dcfb0d55c942e68c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/fc3436e01e2a2ce0cd1ba886bda6971ef77d9d9b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/29b0dd26e46c151e5c7e4c731185ca2ab7ff8009/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/fc603e72dcb99d6e0645594990a209ab559aa1f3/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/1f66e6faf54f332cb9566ee4444e64368bb7ba38/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/fd9eaf40fed4e0b5bc03a65ed12532f32252cf99/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/7c8dcc14ae1786d0ebbb448c44f137f0e6446900/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/f2a02e2fc01494cd797b4b2073697b9755a1c5fa/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/cbad6ee754d1af9b77073c999f538695455e3c82/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/e4c5924767a6066038848aedff5fbe205416a9bb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/508b93862a3e70ba010918fc03374de9f8c05c31/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9f3eceaa427fa1c294ae35448d2dab2/raw/c4e5a0b118f78a55d674af8f3bfe2d20eafbb549/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
👍

**Pull request merged**
