### PR TITLE
JAVA: Backport JUCX fixes to v1.7.x

### PR DESCRIPTION
**Pull request by dmitrygx**
Backport JUCX fixes to v1.7.x in order to fix JUCX build on GPU node

### CODE REVIEW

**Comment by dmitrygx** [comment]
@petro-rudenko could you review pls?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/242b7490571fd6292da3ff87919dcf3620bec1c6/_main) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/b3898450620e396c1a1c8c3f605c8a0fb63a45cd/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/6da078c2af5327bcbec64e21b7a2cc921182f23b/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/9d68e69d7a413057c1086dd04221e419493a47eb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/5a5be33ee8b5ebd5d4ac47be2f653f12b243d065/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/5f0201d78720bb949a07837cefd6237a7aaffd87/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/18e077a3867cf1150d92273ef897d1db731c400a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/c118b5a93862c4301581914e7f35d751b776c094/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/be14a3953bcbcff9bd4dd6d826930a03ae420c95/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/c3df954c3114244a70ad8b85028060967bececcb/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/f1979da7ee479940e2ecc7a0043b1b2302c3b38b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/892e0a5fd82525bcdc8851a5c96860f92ed5922b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/b8096e1c27b924085d2fb277b31ed2d9f64eeebf/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/6394fdeac67b0388f7a0b53584475dd7279bc2a5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/d60a719d41c2f4d246a1356fb2bc8c5fc806b32e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/fef9767cd2c00718c54ac408c8004207184d4cdd/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/7fb674f16576befa999cc4951dfac4e6c3f9ad1e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/a43bdaf2e1642608aa1fe077094687aa4b4977e9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/7c3d02a5f6da9a33e2406156ecfe0ef032774a8f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/8107ade144bfbc46e3b62b7a481802f6ac29531c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/abfcbf846ec2307c267e573923869daf8c44eaf6/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/c49d4e0b730d8e38c5dc2762ab4f9fd13f2294ae/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/d2988c48e5d2cb27c4620f8e5c507b884a8f68a7/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/a31e94b1d59a3f8ce92a714dd7c1f7f37078232a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9197dfc87519fc8f5472956b25bd7095/raw/ef5505d1c238816dbc96e0a63191209cb7f436b2/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:pipe:retest
bot:mlx:retest

**Comment by shamisp** [comment]
@dmitrygx - is this must to have to 1.7.0 release ?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/1fd06f5da455158d5cb61f9b9b738cb899b1884b/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/6a9f8de7d4489fa3764106df2b5bf5aa08325994/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/e8a4d4afa6a652e9e17e89318bcf2da70dff402b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/1c329d46aac7fd11bfae9958114535d1b4be9953/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/04d756c1c94243050e7c54dd0aae03f5bf7ce30a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/cd6f865e66501ba10bd7ca6c86508b1fc5e90cd5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/efa04b45acf11dcde045b3d44c8ecb70038d382a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/3649f0187f784c141b2bd01e274606c1202ad435/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/2e649a12a4bec6ab7361a2fabb0a4818cfa61285/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/ae535689acb19174a52f2f1cdc03c6b4fb762383/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/0e0e1c10e2c1dbc6f75fab535558ecb0d7d9a609/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/d04cc411afe77ea541dd13e8dd7b3ec1a707a5ea/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/ade000f215b4343d9988b172f599ce479b378c8c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/2261c6ad28394a984128f1ce39773ed72cca20b7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/8f62099b9d66db9380aaf468472c85e0113fc264/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/2c644e8f393aa205821f3ac3600f4439d77e9df6/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/ba5aa58b6965925af1595ff1d3c1fcdec6c544b8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/bc0391b478f8d846ec31fc0c42ee7644fe20baef/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/6422f0347c8d954272c2bae10a8eb2d381ff2be0/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/226a5708ecce37181c95d4b4d3a5fc24dec1a2f0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/4fbf374d65a8818b9f79c67a979f226ff0364680/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/3c41cd307ce053674cd0f686328b08b8234ee54f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/20775297c94e30fb2785d36c1811f18a15f371e4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/24f8c8b01042b95f1448c31601fe518a153a4f13/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4b5c28ec2e1a5f8cc441e99debb5dc17/raw/fc3fdbd135b41e402424c283ce16bb270ff2270a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> @dmitrygx - is this must to have to 1.7.0 release ?

@shamisp yes, the CI testing fails w/o this

**Comment by dmitrygx** [comment]
NFS issue
bot:pipe:retest

**Comment by shamisp** [comment]
Okay. My plan is to merge all pending 1.7.x tonight. I prefer not to wait any longer.

**Comment by dmitrygx** [comment]
> Okay. My plan is to merge all pending 1.7.x tonight. I prefer not to wait any longer.

@shamisp ok, this is trivial cherry-picking of the JUCX related commits from master to v1.7.x and @petro-rudenko has approved this PR
Also, after merging this PR, we should restart the testing for #4659 PR that depends on this PR

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/fdc0494a538c04cba070d836c27eccd0a8553935/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/e9c9676fe70c574ce39bddcf47cf9ee45408214e/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/2d8fd876c456cff1b943cdcce3f6df01ed41cfb1/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/a21269cb63695052a501b4c824f42684927b3138/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/e216e516fc48a009b01bf2f4d7babea8eb45f664/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/76a6395f20e6df4af972d57331da422f54354cd9/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/5cf6c10138f3284e71abedaa84dad7b6533b8cdc/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/e4f1863b71cb2e89727507fbc492ddedce7c2029/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/8ecf6c8381a26e8ee09bbdbe6d2a601da2b6f07a/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/45924be3ff2cbba74fd036ce59fc7c13b162f100/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/7d94bd4e5e64bfcd0863fa8a7cb845a7e578d24e/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/e36c2c108ca86aee77f3ceeb590703fb2fdce3dc/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/af32bc4f3c4d02892f9119f2a0e83837898edc77/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/e477a5749eebfa4e09516f5e3c221a960eba38a7/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/198da7e1fb4fdb049c40cd2eaf4cf8b017eded55/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/bb0b906d5b376023cb2c4b823a53914c1a80c249/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/baf33f4d0ca6b0dd17ca69105b75915355325d36/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/b29b810f5959c39ef5925c16888b1e9dba889421/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/792a888e16efa86c71e2e227f0940b4f18afd4d5/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/318af4516dcf4e51682d9055bab7bae29bd8e9c0/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/232a488d93f32378261aef41e1657ff4fb815c1b/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/a95089260c01a7d404e4c0888328ac8c71429254/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/961f6c1d79d2b1b8ccc4c52cf4efc093f7d093db/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/5afb294825f8313d447d0d98d6566eaeb4cec9fe/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d47673c2d44438b458ccb9403da0be3/raw/94a2cf155d711ceeb7e063cfb32496f0e40afa50/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/1748d30726e3fcb67006b4e8774a65efd9351f84/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/01ed23186b17e540092341ab55bbdb8dd21d983d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/b8a376e0b1903c94092dd134cb7dcfa02a096e7a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/c6f2d5191f3610207890d4fd74dd6fa389c1fad3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/43ea9b38364429a8bebd71ecfc4c7779d7b09ba1/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/db06cab30d071b2f4e5814428bdea014f84a9b7e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/a118d85387fc6baa34f39c29152ae4674da31c0f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/ff83217d00fa03740d1478ff8b9d0b6276288c13/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/317c0ab755834f12ce5eace74e7a7d354ee44e33/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/5dc4c3618c11b1afd8e2577ee155714805abb28c/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/d0d323f07565b970c9390f4c5232e4819fd86312/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/f5ec2c6e086ac9641795e3adb861c00c976d471a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/904c88f5f789ba930e717c3b3cd145a6285ffe2d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/156fe14427458a504403ceca75505301ecc2434f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/b50fc95aa71ab916740ecef68a70de4c2507133b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/76ea54d69be47bd781793877ba10d767716b8d74/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/3f611b4ef3a1c12fa4afb820d44aef5a24437782/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/ea40cf77993c3281a3cc684564a4545861fcce9b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/515b91b4f38ef475d962dc3351d322e77e84350d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/7e6d29044ec5b04ec74a8099e8509064cd1c57f5/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/5ed1dd5c3fd4a957855ef83aa64040cc3e266851/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/6d650da4f72662b052ade3b149a6a75640caff31/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/b4ab5e70d2dc71ed40ad8b5207d27d1b3404e6d3/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/7bf836f2470a0d439115a9b8d513eeadcc3d70ba/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3366d9adeeac19d4c1bb4905fa52f6cb/raw/75d30e049e947c016c45bf59012e130bb71c7fb9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@shamisp ok to merge?

**Comment by shamisp** [comment]
@dmitrygx please restart #4695

**Comment by dmitrygx** [comment]
> @dmitrygx please restart #4695
@shamisp done

**Pull request merged**
