### PR TITLE
UCM/SYS: Don't use inline assembly for brk syscall

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Potential fix for https://github.com/openucx/ucx/issues/8415

cc @omor1

### CODE REVIEW

**Review by hoopoepg — APPROVED** [review]

**Comment by shamisp** [comment]
was this tested ?

**Comment by hoopoepg** [comment]
it should be covered by CI - we have set of tests for Bistro infra

**Comment by shamisp** [comment]
Well clearly it does not cover @omor1 case ...

**Comment by yosefe** [comment]
@omor1 can you pls check if this PR fixes your issue? IMO it should because it eliminates the inline asm, so also the register clobbering issue.

**Comment by omor1** [comment]
I'll double-check soon, but it should fix the issue—the glibc syscall wrapper should be correct.

**Comment by omor1** [comment]
I can confirm that this fixes the segfault. Instead of calling the `syscall` instruction directly there are calls (and, in some leaf function cases, direct jumps) to the `syscall` function via the PLT. There still needs to be a fix for the `HAVE_MALLOC_HOOK` test, since that still fails. Your suggestion to print `ptr` works to fix that.

**Comment by yosefe** [comment]
> I can confirm that this fixes the segfault. Instead of calling the `syscall` instruction directly there are calls (and, in some leaf function cases, direct jumps) to the `syscall` function via the PLT. There still needs to be a fix for the `HAVE_MALLOC_HOOK` test, since that still fails. Your suggestion to print `ptr` works to fix that.

I don't think we need to change it. If LTO is really eliminating calls to malloc, it means malloc hooks really do not work.
Anyway, bistro mode (patching mmap etc) is enough; malloc hooks are needed today only when running with valgrind

**Comment by omor1** [comment]
> I don't think we need to change it. If LTO is really eliminating calls to malloc, it means malloc hooks really do not work. Anyway, bistro mode (patching mmap etc) is enough; malloc hooks are needed today only when running with valgrind

The call to `malloc` is eliminated because `ptr` itself is eliminated; the compiler is able to prove—in the simple test used for malloc hooks—that `ptr` isn't used by anything and, since it's local to the executable, that it can't be accessed by an external caller. In an actual application—and particularly in a shared library—these are both not true. I think it's still worthwhile to fix the test so that using LTO doesn't silently disable a capability that otherwise works correctly. Someday you may get a compiler that even without LTO is able to make similar optimizations...

**Comment by omor1** [comment]
I'll also note that this is—potentially—a bug in both LLVM and GCC where specifically calls to `malloc` can be optimized away; similarly-declared functions do not get that luxury. Linking to a miniature shared library with a function `void *mymalloc(size_t size) __attribute__((nothrow, warn_unused_result, malloc))` that simply calls `malloc` prevents the allocation from being eliminated—it seems that LLVM and GCC both assume that `malloc` does not have observable side-effects when compiled with LTO.

**Pull request merged**
