### PR TITLE
Topic/jenkins test 4

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/151/ for detail (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/706/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/152/ for detail (Mellanox internal link)

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/154/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
ok to test

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/155/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/711/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/713/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/714/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/715/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/718/ for details.

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/720/ for details.

**Pull request closed without merging**
