### PR TITLE
UCP/WIREUP: Fix race condition when allocating request from memory pool.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by brminich** [comment]
:+1:   Just caught this bug in my experiments

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2734/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/143/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2111/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/144/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2735/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2113/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2119/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2124/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2127/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
hmm. Maybe instead we have to add thread safe variant of the function ?

**Comment by yosefe** [comment]
@shamisp we would have to make another memory pool in this case (don't want to lock from main thread), so for slow path messages would be better to just use malloc() and avoid the extra memory consumption of an additional memory pool

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by shamisp** [comment]
IMHO looks hacky

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/159/ for details.

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/161/ for details.

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/162/ for details.

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/163/ for details.

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/164/ for details.

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by yosefe** [comment]
@shamisp what would you suggest?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/165/ for details.

**Comment by shamisp** [comment]
Crate a list with a single element that we allocate / deallocate (with
locks) using already existing API ?

**Comment by miked-mellanox** [comment]
IMO - unnecessary complexity, lets add locking flows where it is absolutely needed.

**Comment by shamisp** [comment]
Such special "request" allocation method will lead to potential bugs,
memory leaks, alignment problems, etc.  It is almost guaranteed that we
will forget to update this special code exception in a future.

**Comment by yosefe** [comment]
@shamisp even today not all requests are allocated from the memory pool, for example sometimes receive requests are allocated externally on the stack of MPI_Recv() function.

**Pull request merged**
