### PR TITLE
UCT/UCP/API: align TM cb with new AM cb interface

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe please take a look

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1337/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3285/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @bbenton pls review as well

**Comment by shamisp** [comment]
adding @MattBBaker - will require change in ugni

**Comment by shamisp** [comment]
@MattBBaker - I guess ugni does not use the APIs. 
@yosefe - looks good to me
@bbenton - please take a look

**Comment by bbenton** [comment]
:+1: for Doc/API

**Comment by MattBBaker** [comment]
@shamisp It does, but the flag in UDT was updated in this PR already. The previous PR on this subject had SMSG remove the flag from its am callback so that I didn't have the descriptor passed to UCP anymore.

**Comment by shamisp** [comment]
got it.

**Comment by shamisp** [comment]
👍

**Pull request merged**
