### PR TITLE
UCP/WORKER: Fix rndv pipeline fragment pool alignment

### PR DESCRIPTION
**Pull request by bureddy**
## What
Fix data alignment 

## Why ?
detected poor performance for GPU transfers on power arch because of fragmented RDAMA WRITE in memtype pipelining put protocol

### CODE REVIEW

**Comment by bureddy** [comment]
@Akshay-Venkatesh can you please recheck perf on Summit?

**Comment by Akshay-Venkatesh** [comment]
@bureddy Performance meets expectation. Just confirmed on Summit.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7552/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
backport for v1.4 ?

**Pull request merged**
