### PR TITLE
GTEST: ignore warnings on stats filter test

### PR DESCRIPTION
**Pull request by hoopoepg**
- this caused failure on SRIOV (virtual) systems

fixes https://github.com/openucx/ucx/issues/2773

### CODE REVIEW

**Comment by yosefe** [comment]
can we somehow not show this warning at all on polar?
or disable this warning at all when running gtest?
it can happen in any test  - which calls ucs_get_time()  the first time

**Comment by hoopoepg** [comment]
there is no way to detect virtual system, and adding special case for gtest will require hack in UCS to get environment variable

@amaslenn are there more such failures where CPU info warning fails the test?

**Comment by amaslenn** [comment]
@hoopoepg yep, there are other fails. This one is an example. Please run `gtest` without filtering to see all of them.

**Comment by hoopoepg** [comment]
yes, looking at this way too

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7386/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7389/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by hoopoepg** [comment]
@yosefe ok to approve?

**Pull request merged**
