### PR TITLE
TEST/MM: Don't test without procfs link

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
docker login timeout
/azp run

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/af7a0b98b8a08d4f58aa588a94342378300d383b/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/19a1695499a61d510beefdb53e21bfc2f9943a9a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/ea7f9b26b4e0417d1e39e90aeaa6e594f87abc34/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/470f1a3202307d5996bd919bdea7bccc502b04f1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/7c4ec496862ffaed9e3d8191fcfa81ed464c6ded/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/2712321b6916253927e2d0d252e468693b39abb3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/74370b31ade817245d7536a028e29f772ec1e096/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/040a841ab110bf359196a2f68f3dcb9f372f20d3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/1ff48be7b3f8705c050f360f8d21b0626982f931/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/56dd8ddc9cc7de7678c15b252c7d9a5942459f44/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/d36d44ac9f477c686a3654aefeabeff14941ba3b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/67956fbceb5d8b86b42181c18e80c4baea5aad29/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/7689dd58fa82d83405f66cf470356d7a717054f3/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/5ef59893e104a7bad29e6cdb191b0bf44a0ceb95/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/3f5cc37ef55f8a5f371423c28bd26449165c71bd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/515798d9a3858aa1a2e43a3def093fd2484cf471/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/8654565738834f014216f6482fa910a2f10dd3d4/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/aa714344218da772df531d38c534054b05877c15/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/65d6b7a03ac2b885a20fdae653ddfb8fbd524e40/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/1b3f84ec09b40b9a631d0bffccd46e3f22e6e981/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/46364af070d64912689537de4791f525b847de6f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/fd53266e7b57182bb6a1f7b15cc704c4ceacb829/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/fc92c7ba154d3e0461c0a5cb7d339ac988281b47/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/559386d89f7e6b1e0c62073d254b6f34a2071081/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/48b7a429844ba64cdec75b9f93037557/raw/bde740e0e7efed8d38a9441353ecd9b1926099ab/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
hpc-test-node-upstream-01/02 fw failure
bot:pipe:retest

**Comment by brminich** [comment]
OOM

bot:pipe:retest

**Pull request merged**
