### PR TITLE
TEST/COMMON: Add mem_buffer class to allocate memory of different types

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11578/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 15 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/9aa61a7d8c2a43998d615a71c3450d866cf79619/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/97a5916f45c40fd085a473435bcc5d4cc871431f/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/f132f6419e4db200f939dc4531f46c59285eebe1/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/ae5d488faefffd4fc10d7703b52135464a21d55e/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/0c8becba24f62188bade88274a6b230dd804a3f5/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/24ef537db3a2364891be73ce2f8e50ed7398a35f/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/e12ae29316baa453eb27777c9f431d7f04c249ad/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/0578afa940e006d43c1962dd3d0748a74817511b/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/4ed5dc9e692ddb77ade998700d6aae7e45331239/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/f38ffddd229d72c68841f162d8979b156e431621/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/822465eb6c1a37d730c87330074de1b5dd653264/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/d7cf03e49d46a2c81e2453b521c200adc04f5b03/hpc-test-node-gpu_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/f58423d786eb0a21d1f9ddaa83712e5be0157460/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/96ecb440c2ef2bb49387d4791e3001b30030ffbe/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/7b0cd37ddfee8e3365ca728d29eda1aa4c495d36/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/73029c3f258989c9bcbea08907c1dddc50c84a76/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/48f9b40beedaec02ed9cd227e4ae1b498e7f7f45/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/8e1a0720689466331fe0c6c13c46cc45f5e23fe1/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/e8151d15b5242e72583988784a1fce9f45591243/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/2dd9921b289dcecce15fd8ceef7050527b65dfa5/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/0e01458f056ec502fb12478da8c313f9a1f3ce31/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/da7e723fc95fdb1c3d5bde54cbf83ba2028323f0/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/dc7a885cfc5532bb1d44d9130440a828a3eb8efa/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/4eab15c8e80dd1511a8470c1cf9678443b1456ad/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/010bb57efedba937fc54a796a9c6e6acb382080b/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/49d09e3d001efd065e4ae479943f2ef9cfec51ea/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/10d2d6c575daf287e1d8d0e2f96749e17bd5c38a/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/b70ff02f445f145402f1f59144c7e85dec6fd7e5/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d848572892fac48435e168837304a935/raw/1ec87ee00b51fa120526fb9e2c425a62439b5c80/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11587/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/3a2c182a2bacba04b19f9a59e05300338e264420/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/8bd0e47c5b3038e92f897afee9d72ef402df07ac/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/54f0dedcc5f526d79f6c522a53e8f5359705758c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/fbc7b510fd34fcd335118df8602b7bd6d3790c73/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/756e44e57d64b2c39a93b90588c1cd2fc6523fec/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/cb29187f1bc8a3588b2dfd5ceeecd6cc889cd316/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/3f851259f4a454d75ca14213a1a3cdc601401945/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/a9f881ce255ebbd28c51a9b13d967455b0967074/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/3b56199e9aac9962ee4ee2601d1c5d12ed9da573/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/3063389b5895470da2364831f738c6e29dbe1747/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/40e57d3ee0866b46bd368b4bfde8fbf2c8ab6941/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/94585d3b6fa9d7a72471fdfd0de35ff48afbbdf8/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/bb84a737ed18982b01be514f5e0de0402bd5e239/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/a7818f828090057f230cf34619b8c0f90957b313/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/c0c93f75d2390974e06419ea8d2117a67f84417b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/61b32126ecbb0d1fad2a7f6713962e43182c30ad/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/cb7032ee6edd416490db7ebc1cbace58854bfbdb/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/869d8af1a3543bd55e526d15b01d8b17e47732c6/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/2b62d9b93b87b1be73b1ec719cab7ffb4d02c01c/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/41d24c6983910179fc5ffe840e31e8925a73b7ad/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/d4a9c5a8e8febcccb691105483a679a16baed65e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/5ac4ccc21b298802739b0bb336017ac8b211ed67/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/4a9ab4874fd5ecf5f618fb70705f602fa16836d7/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/13aa870aaf3f1f0c2f3d545a44fe5ec16ca8ce7d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/6f2458da672425b71bfa85c0e0fcb475aa271809/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/7bf74e02c3a2d0267ae16bba97d593c4214d1f0f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/3b33d20b68190eddfba066b8b296c7951c4a9dc2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/37031f2d72ec19b8d29d60bf14c2f438d8883379/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fbf01bcf3defaf745e58205f24666ab0/raw/04b5172aabfc53aedf4c2d8013d4e6271a7db805/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:bgate:retest

**Pull request merged**
