### PR TITLE
UCS: fix corner-case in ptr_array

### PR DESCRIPTION
**Pull request by alex--m**

### CODE REVIEW

**Comment by shamisp** [comment]
Ok to test

**Review by yosefe — APPROVED** [review]
maybe add gtest?

**Comment by yosefe** [comment]
@alex--m is it possible to add gtest to repro this issue?

**Comment by alex--m** [comment]
Looks like test fail is unrelated...

**Review by brminich — APPROVED** [review]

**Review by yosefe — APPROVED** [review]

**Pull request merged**
