### PR TITLE
AZP: run new bunch of tests - legacy

### PR DESCRIPTION
**Pull request by amaslenn**
## What
Run "legacy" testing in AZP

## Why ?
Migrate from Jenkins to Azure.

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 18 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/5e87ff445ac6e16c14fb54737a4354fdcf47500a/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/b89ffb24bd956c1227c364673d3ae660078cd74a/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/d295cd14c3925cc59a93f9e09779466927e975a9/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/dc1f26bff339526a34e73ff83f3a01bf1a8a2139/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/53fc9b0be873c1d794b273f35c4b9a6402ce9e2c/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/6797b91a5402009d8482f4d228bb7a1d3e0b91fd/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/1d94c955d6275085c56691f046061689f1c54d33/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/aa8043e87cb26237d59965c47b4be5d80e29785e/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/e8d6a265f0a33621f2f4a5fb2c1c7b0fd48fd511/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/c67685e34d11834d92c846772efea5b2f9472e59/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/e4a4f644ff85f040f70c9e78b161eae8a401d714/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/dba56e5ad89629968f7049bf26d704b175e91b42/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/b9d71de9870b0a790b10e67deb45a078d59b7245/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/5139fddaa3e785129841ba71e0385159103f4a47/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/e32dca54399724dd787086faed0f0427e359472a/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/90f4f23e0cb5cd36383142b298137354b3dfe6be/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/d9bfd7a928d76258d37ba5695d5a4a3c61ef053a/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/32c0ad8d5ce44ad92b3b8da00ee2efeb/raw/1524e91c9230bce214064d21aeea6f61e26da6cc/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3ca9df2e4422c1a307976dbcf5b090e6/raw/b3aec5ac61820256eadf80fe3287f6bf357c2a16/_main) | :question: ABORTED

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/099df6232b3beaf4991781324a49a24a092b5f5a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/6a58a213f04b878985b28b077655d0e32ca91fff/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/e29b1ed7f6c3e0d90e2134938d9d05e44a210faa/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/1ce95c0121d8e00b16842614599ac5e1d455f686/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/a6a891f2c5a5f648d9d08645f0c95ca1c944da75/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/23d3f58664202d2e33797f2cd69d2ab1910e78d6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/0b233a4897a25f9124eab2d7335282afc5731d0b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/fff7d77bf06a9d6e93d0f1519cbcc3dedf38d9af/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/505b481a7e11a313526ab327c57fd54ea2448aa2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/9acb34710576413c0e2e2a61441e41b224906254/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/24639ef73dd5579df8be76005fa2597be485c30c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/f806d7e29f12c24c5125485ef2d61c5b4ae057cc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/e1c2d02e8d69429a5d24937b32018f97b32b14a7/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/6697be52eff8a83b318e5291be8591c97f8ec6d5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/c78d8b0109d9e0a43faeddde63ccfcc5cb43eac8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/bd368d51a30a57b0f4b64361a5158bd4f8c2dd9a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/8fb0eb577b7d09a5b8225709945b9adb176eb68b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/7c4bc08725f4ad8f8c6c9f2463a17fa399de63fe/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/ca5c47aea077e501de30d67462aaa7d8fbcf9cd9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/661a71d570064fa486a93411dff4f9e02f14ab47/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/8dcd31ea313e866b6c898a1797ef8cd538b9ae2a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/6406206e7aa70a159f445e1392d982004333e2bd/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/c6395dbe9d67d93e717a8dab328fd2aa04c0b11d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/23be61a39555c21c747c52134ab92163f4a8b95c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/310c1216619e3c117b6d757506a65865/raw/db31c9dc05e4982eb0bad28afd8e1f3b92e7d7f2/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by amaslenn** [comment]
@yosefe do we need it in branches? Once all hosts moved to Azure, Jenkins's coverage will be reduced.

**Pull request merged**
