### PR TITLE
GTEST: fix mm/test_uct_mm.open_for_posix test to work well with valgrind

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2857/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/311/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2256/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/312/ for details.

**Comment by alinask** [comment]
@brminich @yosefe please review

**Comment by brminich** [comment]
:+1: 
Looks good to me. As an alternative, I'd consider an approach to wait for some boolean variable to be true (which should be set in AM handler). Then relatively big timeout (waiting for AM to arrive) could be used, as it will be relevant only for the failed cases.

**Comment by yosefe** [comment]
agree with @brminich  - need to wait for a flag. no need for timeout, worst case the test will hang, which is also a failure

**Comment by brminich** [comment]
Would not it be better to set a timeout for X sec to avoid wasting time if AM is not received? By X I mean some big value (like 10) which should be definitely enough for message transfer

**Comment by yosefe** [comment]
@brminich @alinask right, let's have timeout

**Comment by shamisp** [comment]
What is "50" ? I would suggest to document what are we waiting for.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/319/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2862/ for details.

**Comment by yosefe** [comment]
looks good

**Comment by brminich** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2263/ for details (Mellanox internal link).

**Pull request merged**
