### PR TITLE
TEST/UCT/MD: Add timeout to registration performance test.

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1453/ for details.

**Comment by shamisp** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1454/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3378/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1458/ for details.

**Comment by shamisp** [comment]
@yosefe it failed on timeout. Can you please fix ? I think the setup that I run on my machine is a bit more generic that the one that you have. I run xpmem,cma,knem + all ib.

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1465/ for details.

**Comment by shamisp** [comment]
@yosefe - ARM build looking good. Can you please set JENKINS_RUN_TESTS=1

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
@shamisp test on the new node took longer to complete (44m instead of 30m) can you please check? looks like it's related to xpmem

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3396/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - I think it just tests more. I have CMA, KNEM, and XPMEM enabled in addition to all the flavors of ARM. XPMEM registration is pretty slow.

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3399/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1476/ for details.

**Comment by yosefe** [comment]
@shamisp any idea why xpmem registration is so slow? cant it be a bug?

**Comment by shamisp** [comment]
@yosefe I have no idea. I don't think this is bug. It has to go and touch every page, etc. It is not most optimized kernel module. Typically it is used for pgas where the registration occurs only during initialization. Anyways , please bump up the timer, we have to proceed with full testing.

**Comment by yosefe** [comment]
@shamisp 21sec for 4mb is very slow. for comparison, knem has to do the same, and it's much faster. in any case, the timeout is already large enough for the test to pass.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1482/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3404/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe it is looking good

**Comment by yosefe** [comment]
@shamisp yes, so we need to merge the test fix to master and enable tests on cavium
do we want to merge this PR as is (i'me fine with it)?

**Comment by shamisp** [comment]
@yosefe do you want me reverse the first patch hacking the value ?

**Comment by yosefe** [comment]
@shamisp yes

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1491/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3413/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe please +1 this

**Pull request merged**
