### PR TITLE
JENKINS: Add cray-ugni build test

### PR DESCRIPTION
**Pull request by yosefe**
Adds mock UGNI headers to test UCT UGNI compilation in Jenkins

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9168/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9190/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @MattBBaker can you pls review?

**Comment by MattBBaker** [comment]
The code looks good. I was looking through the Jenkins output though I couldn't find it trying to run this. Where can I look that up?

**Comment by yosefe** [comment]
@MattBBaker http://bgate.mellanox.com/jenkins/job/hpc-ucx-pr__published_from_mellanox_lab/9190/label=hpc-test-node,worker=1/consoleFull, grep for 'cray-ugni'

**Comment by MattBBaker** [comment]
Okay, I was just in the wrong node. Output looks like what I expect from ugni. 👍

**Pull request merged**
