### PR TITLE
CM: Call pending callback from main thread only.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1174/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1784/ for details.

**Comment by yosefe** [comment]
@alex-mikheev can you pls review?

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
