### PR TITLE
NEWS: added support of omnipath - v1.5

### PR DESCRIPTION
**Pull request by hoopoepg**
This PR should be merged after https://github.com/openucx/ucx/pull/3677/

### CODE REVIEW

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10565/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10576/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
closed via https://github.com/openucx/ucx/pull/3677

**Pull request closed without merging**
