### PR TITLE
Fixes for perftest and Jenkins with CUDA

### PR DESCRIPTION
**Pull request by yosefe**
CUDA tests were not running in Jenkins, and this error was silently ignored. Also, memset() for cuda buffers was missing, and cuda-managed was not tested.

### CODE REVIEW

**Comment by bureddy** [comment]
@yosefe  am I missing something? i see cuda tests ran in recent jenkins runs.

```
10:57:10 + echo '==== Running ucx_perf with cuda memory===='
10:57:10 ==== Running ucx_perf with cuda memory====
10:57:10 + mpirun -x UCX_ERROR_SIGNALS -x UCX_HANDLE_ERRORS -mca pml ob1 -mca btl tcp,self -mca btl_tcp_if_include lo -mca coll '^hcoll,ml' -np 2 -x UCX_TLS=rc,cuda_copy,gdr_copy -x UCX_MEMTYPE_CACHE=y taskset -c 28,29 /scrap/jenkins/workspace/hpc-ucx-pr-6/label/vulcan-jenkins/worker/0/install/bin/ucx_perftest -b /scrap/jenkins/workspace/hpc-ucx-pr-6/label/vulcan-jenkins/worker/0/install/share/ucx/perftest/test_types_short_ucp -b /scrap/jenkins/workspace/hpc-ucx-pr-6/label/vulcan-jenkins/worker/0/install/share/ucx/perftest/msg_pow2_short -w 1
10:57:10 +--------------+-----------------------------+---------------------+-----------------------+
10:57:10 |              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
10:57:10 +--------------+---------+---------+---------+----------+----------+-----------+-----------+
10:57:10 | # iterations | typical | average | overall |  average |  overall |   average |   overall |
10:57:10 +--------------+---------+---------+---------+----------+----------+-----------+-----------+
10:57:10 +ucp_contig_contig_cuda_tag_lat/8192---------+----------+----------+-----------+-----------+
10:57:11           1000     0.000    11.207    11.207     697.11     697.11       89230       89230
10:57:11 +ucp_contig_contig_cuda_tag_lat/1024---------+----------+----------+-----------+-----------+
10:57:11           1000     0.000     3.886     3.886     251.27     251.27      257303      257303
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8933/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy it works in another test on same executor loaded cuda module beforehand
this is when it doesn't work:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8928/label=vulcan-jenkins,worker=2/consoleFull
```
13:44:04 + echo '==== Running ucx_perf with cuda memory===='
13:44:04 ==== Running ucx_perf with cuda memory====
13:44:04 + mpirun -x UCX_ERROR_SIGNALS -x UCX_HANDLE_ERRORS -mca pml ob1 -mca btl tcp,self -mca btl_tcp_if_include lo -mca coll '^hcoll,ml' -np 2 -x UCX_TLS=rc,cuda_copy,gdr_copy -x UCX_MEMTYPE_CACHE=y taskset -c 30,31 /scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/2/install/bin/ucx_perftest -b /scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/2/install/share/ucx/perftest/test_types_short_ucp -b /scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/2/install/share/ucx/perftest/msg_pow2_short -w 1
13:44:04 [1551095044.896932] [vulcan-jenkins:18446:0]       perftest.c:710  UCX  ERROR in batch file '/scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/2/install/share/ucx/perftest/test_types_short_ucp' line 1: -m cuda: Invalid parameter
13:44:04 +--------------+-----------------------------+---------------------+-----------------------+
13:44:04 |              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
13:44:04 +--------------+---------+---------+---------+----------+----------+-----------+-----------+
13:44:04 | # iterations | typical | average | overall |  average |  overall |   average |   overall |
13:44:04 +--------------+---------+---------+---------+----------+----------+-----------+-----------+
13:44:04 [1551095044.897288] [vulcan-jenkins:18447:0]       perftest.c:710  UCX  ERROR in batch file '/scrap/jenkins/workspace/hpc-ucx-pr-5/label/vulcan-jenkins/worker/2/install/share/ucx/perftest/test_types_short_ucp' line 1: -m cuda: Invalid parameter
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8971/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8988/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9014/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9062/ for details (Mellanox internal link).

**Pull request merged**
