### PR TITLE
UCP: clean zcopy_multi code

### PR DESCRIPTION
**Pull request by hoopoepg**
- removed deprecated ID_LAST argument

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7096/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7097/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bgate failed due to server issue

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7103/ for details (Mellanox internal link).

**Pull request merged**
