### PR TITLE
UGNI/IOV: Fix bcopy_multy algo

### PR DESCRIPTION
**Pull request by shssf**
Fix the bug in offset handling in case of error in bcopy algorithm in PR #1072 
Related Issue #951 
@MattBBaker please review (changes are based on your proposal. Thank you for this.)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/217/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2191/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
I just tested this on Titan. With the PR I posted and this Titan passes 100% of all ucp tests. :+1: for merging.

**Comment by shamisp** [comment]
👍

**Pull request merged**
