### PR TITLE
UCM: Handle corner cases when replacing dlopen().

### LINKED ISSUE #564: ucm reloc enhancements
* install ucm_dlopen only if a relocation is being changed
* check in orig_dlopen is != NULL

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #564

### CODE REVIEW

**Comment by MattBBaker** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1352/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/742/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
