### PR TITLE
UCS/STRING: Add ucs_snprintf_safe()

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12804/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/40a25bf1b06957095701a54766cc3de9524b1da3/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/a547690d8ebcb09862f524489aa721be0514a326/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/a2690454326a2c55236c683d0537f665496121e5/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/ac35b759564bd72159eee9a1f97ad81ca2abf1f3/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/7577549578d44801857fba7ee81ef0ff1af64af7/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/e4ae694ed12449bf955769d0cd5ca655462ffbd5/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/0c62d2b090374b0cf23b72ca3ff9c6489c2bb5ed/hpc-test-node-new_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/c6ade9b897bcdb3c82868711a1e9102b8c943c97/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/354d40c5da2876be77a1d7106457e1e732a39b51/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/d3c1caaf9729f53cb78c3f68f4fabe2eac08d428/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/0098fe864a0c79c7f0d560a4eaefcb850bd0b3cd/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/9317a13466d8883b98668718a2379e309b0e0e6d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/eda3a6663ee8aecc099a3483dccd1f6191ebca6a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/aec63362d8082219608b5fb6be261f075ae3b143/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/7f8e93b5e3c1bd0d3561aa7e2342c774e6cb46c0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/76527f755863b944f1fbc34985248ce82231681d/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/93edb7440ed4ec02693ba399ae68de8d1e92ed5f/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/f24666a6851aaf2ef10f017ec2c8e7c4b7ea40f3/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/8c693ac5c88a5b659d37d611ae11eb37deb54b94/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/a69aaa2622ecc137ace0c56c3aa18325cfdfab54/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/f65bce8ff7c292289c13f8fb88914092b87a72e9/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/8333af8135600a56de21c79e2337963b8f805e17/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/91fad073c38e57c8f782ed7cbd7fd76f99b0f4fd/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/e6b2e7ce167b95d4609d5973c8d690cbf40cc3d0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/0e4b444a0be4227146ea7f48f9adac1cd66be6b7/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/45a1854a88a8e91860384dc96fc1173dbef8c992/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/7aba824fff9280039e10c18397a0bbdaebfb7a4a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/10b7723a030ed8b148aadbd8d132b734e3b7ff40/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/2b719e049f59ba4069be60c364ca959f/raw/a538656bd4fdddbe28ee460b6d301ef0459a23d6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12829/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/31fc34a6415b65aab0d183d4dcb8031adde8728e/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/eae6d1f8eb2486c4fbdac718d7e069c6df885d80/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/db60a7237a1e3071438971ec270c840179a524b7/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/72b19fc8df9ebeee791a0534965ea714ead912f6/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/57e12f0d7a50c84fa21a8e768095985377b94638/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/6b7e462e318e7e45b1a09145d6e39d77cd4fdeec/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/4b0e9418611e940dc50de4e6f4af71ef8cf057db/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/7fbc5cc9196956776f3a96d50da9fb82b1dfbe89/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/613c0b6dc5721388255671a2e642146a605436ae/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/0d877e33356836299e51a5358941ff728c5d837f/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/fb389edec246524541d8186e4ee25554fc65eb4b/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/f79c13f088190f649ab6e5a9c475dbe0de156ab2/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/bcbc50364b103c51ec284060b5bfe6c8aa82c1c5/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/0816a9d21359e0acf9b89c1a310d644f48aafdda/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/b34b75f6d9dc3513f2cefdf69e8f511867cba675/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/cc5ff864cf46a620b2ce65542599825dc02c74df/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/a5c79742d94645227ffefb9abc98816b5f54f510/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/287ed493e75d3386bd739c0e79d99eb2684d8052/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/d49bcceac11d6e3cea07dcbd78bd3a4de84e48ca/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/0c2423c5a977e1949f7c8ea87c7dedaaef2f6648/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/9941fcb5e24f5428faf8b6d8c83fbceb343f1d6c/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/f0521192cac0466713d3d300113ad89295572c6a/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/2640e798512a518ef12834240a3c9bbe05b1843f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/0a0450e957aa72f5602525ad94db5af0e9069cb5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/19cae2aa58ca79b3923d441c24be0eac9d491b4d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/b9e9bcbbc09db609680abb9d55c183f5f5f053d0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/6fe6e96daf578293dc4b4d7e3a18a5c454d04537/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/c174c9420bf0e686cd4332b236a461ec9983d816/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6d87ae1f8740dac09002b038e8228ec9/raw/8650730c776c9a47a64cf7a62d2aefec25cbe5e7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12866/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/cc40258023c685bec1e0db9b4fd9ef42ee5daa56/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/797a13123a74dd56307ef0f6b2f27424adfdf8f2/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/315a4122cb1f56191eba62875b2c7456ba0cf9d8/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/31d2abc5bc21763b1459dcb6b7e5d16d2c1a0976/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/a924ff4932508217658fa7cd10fbf1123ebc77e2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/185ebdb183ed652d01d700dc4cc3d99e7b027c49/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/1948daadc60852aab6ee373e4d5b96af5a531fa6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/a60df89f822baed511ef87047856d24de195fed4/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/d1984bddaf086a093f75f5901cadc4c879a533c0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/13e8b9f33bea7e1f4753866c8ed0d4604cd4a611/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/762925ce694fd37e0cfd3acc2c5c4b96f11fc093/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/dbbf9adeabfb2edf86116ba46f0845170d1cba5f/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/cd4a1e7efdabc5fbf7a812ace620a9a3b858f8c7/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/d2ad70d04f4660a1eb89b21eeeada7b4836e75f5/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/a11998625d37b2559387aa85d8121c848126cb5e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/2b307dd8d64132d7c0d168c9982bf03191d4d798/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/56105bd839c8910f692fe1e568862351350c8a5c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/a800a2d3cd54c20d2d9fd2b7c9e563879d5b4400/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/8088b889b5b7d24cfed1b2e589d0339445b4fbb0/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/2cdf870d33899007ec5af0492370982dcca01266/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/867365827b9b2a2fc5770f46e05c4240fec5b112/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/3a74012f1370eb693e971bc6cdee4274b2009b81/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/4176ffbe428906914df190ba22ce2a397246c0ea/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/32ce41ec472488df5beaced7a6e59a14db9eca7b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/f67c3f30fc008f8c37c213c436f8287149efb7dc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/3259337c27995721e2c9a1ba40c9344d51b61daf/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/d0fb5caccdabd35779d4534a8d39be397048d6fb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/ce8f2e0a526d64a22704433188425d1cfa70392b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9e4603f1c8824ad3947b34007477b73d/raw/0ba4563545ed0115f122c74f37d6c0c70fea1348/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12873/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/380380cc1bd98f1cf8d7125165773027ba26c671/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/86a5ee2a79c1ccc3468108c8363569ba4cc52b66/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/013d10d20311d4a41c7040b2f14f28b0970f79c5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/b7a3e9a5869935fef7e9c865e8efb80d5cfad498/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/75c6a115ea4c902a03e0aa07e8bcb82b2793092c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/3dc1ec0f75e6ed8ae21ff8754348d5d66dc604bb/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/ed1876a8b78735879edc12dfbc58de30efd63611/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/e575bcd0e71a8660ee50dd99af6373af04657fc5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/ad27747fc7e5d93b5adb7599bb5e1c01499e5d74/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/b860c645cd518aa8349197b5fa8621a2a5897203/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/3279f0b3884f4dd960edc10c9d8bcaf8d13e1ec8/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/71343363b9457e4d62f2e901508d880ff5260712/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/18c40715956bd15daba922805d89367f7b018ec9/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/805d058ffe091937741a4196d40ba422329d3a0a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/b442dcc1219d82175d1daa7567cda142fa1189c8/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/6d1b85da79d5d43b6d1b1916fb4c5b2917d9ca00/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/e209a5a4ed3a176cbe0add4f17d62ce814c0da7b/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/a619f0a94472a36182c4ed2d528b3552d3061a72/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/6afeece7edf6285786b4e3c0ef0179f2063e6145/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/cabd70bdb14a13b6c3ab7c5de23b2731d4760065/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/0d53dc741688fa45d972ae7c88a379c83f9911af/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/b4cbc81d2ba9e219cd103418c7b085499687b06f/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/0c365148f298cc5d24a34ea09561645b1fdbb007/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/0c627a52440e7308abc679e56ea28fa78352b9be/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/f283d6b1e12de1046cffb1774a6bee2a60b219ee/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/e6ffdadfa56217678fc464cb859747508fe32714/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/cb53c82bbd61159f755b81abb6a4049b59577c4c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/3390f6f1aaadd5a696cab3b60f9223ff5a4fc80b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b734f7f7b6447d4e250321837c2252d3/raw/c52795509f01b19f8b4e6cba1704fdafb575daff/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
