### PR TITLE
UCT/UGNI properly account for SMSG AM sends that fail.

### PR DESCRIPTION
**Pull request by MattBBaker**
UGNI SMSG did not properly discard AM stats for messages that failed. Fixed that.

### CODE REVIEW

**Comment by MattBBaker** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1421/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/808/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
:+1:

**Comment by MattBBaker** [comment]
@yosefe can you please merge?

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1435/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/823/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Failure on jenkins was unrelated to this patch.
15:20:19 [ RUN      ] ud_mlx5/test_ud.connect_iface_seq/0
15:20:20 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/uct/test_ud.cc:299: Failure
15:20:20 Value of: ep(m_e1)->dest_ep_id
15:20:20   Actual: 16777215
15:20:20 Expected: 0U
15:20:20 Which is: 0
15:20:20 [  FAILED  ] ud_mlx5/test_ud.connect_iface_seq/0, where GetParam() = ud_mlx5/mlx5_0:1 (1192 ms)

**Pull request merged**
