### PR TITLE
UCP/UCT: CUDA Managed memory support

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
## What
Adds Cuda-managed memory support to 1.4.x

@shamisp @yosefe

### CODE REVIEW

**Comment by bureddy** [comment]
@Akshay-Venkatesh any reason for not porting pertest and gtest changes?

**Comment by Akshay-Venkatesh** [comment]
@bureddy
Perftest isn't on par with master. I can follow up with a separate PR for that later.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7939/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7940/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7941/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7946/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7952/ for details (Mellanox internal link).

**Pull request merged**
