### PR TITLE
UCP/STREAM: add session ID

### PR DESCRIPTION
**Pull request by evgeny-leksikov**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5964/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5968/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@evgeny-leksikov after this PR, can stream API be used for loopback connections?

**Comment by evgeny-leksikov** [comment]
@yosefe sure, just new tests are playing with eps from 2 sides, this is not actual for connection to self

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5982/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
@alex-mikheev pls review

**Pull request closed without merging**
