### PR TITLE
Update flags for ugni uct layer.

### PR DESCRIPTION
**Pull request by MattBBaker**
Update flags in uct TL so that it can be used by ucp wire up.

### CODE REVIEW

**Comment by MattBBaker** [comment]
@shamisp Please have a look.

**Comment by MattBBaker** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1331/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/727/ for details (Mellanox internal link).

**Pull request merged**
