### PR TITLE
UCP: Add header file for experimental APIs

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8461/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8463/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8469/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Please add NEWS entry

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8470/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8471/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp fixed

**Comment by yosefe** [comment]
@shamisp ok to merge?

**Comment by shamisp** [comment]
👍  @bbenton  FYI

**Comment by bbenton** [comment]
:+1:

**Pull request merged**
