### PR TITLE
Topic/doxygen

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/865/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/292/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe , can you please take a look

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
