### PR TITLE
UCT/CUDA: remove cuda uct skeleton 

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4798/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy 
- need to remove from configure.ac as well
- pls form commit message according to ode style

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4835/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4846/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4858/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls take a look as well

**Comment by shamisp** [comment]
👍

**Pull request merged**
