### PR TITLE
UCP/TEST: Fix bug in generic datatype finish, and add test for it.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1074/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/504/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
