### PR TITLE
DOC: Update CodeStyle

### LINKED ISSUE #601: update code style document
- Macro argument names to start with _
- Unit tests requirement
- No leading __ in function names

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #601

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1468/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/863/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
:+1:

**Comment by yosefe** [comment]
failure is unrelated

**Pull request merged**
