### PR TITLE
TEST: Progress all entities while disconnecting.

### LINKED ISSUE #1002: Hang in shm/test_ucp_tag_xfer.generic_unexp/0
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2455/console
```
15:04:31 [       OK ] shm/test_ucp_tag_xfer.generic_unexp/0 (2211 ms)
15:04:31 [ RUN      ] shm/test_ucp_tag_xfer.contig_exp_sync/0
15:04:31 [     INFO ] 0 79x10^1 25x10^2 7x10^3 3x10^4 3x10^5 3x10^6 3x10^7 
16:17:15 make: *** [test_valgrind] Killed
16:17:15 Build step 'Execute shell' marked build as failure
16:17:15 TAP Reports Processing: START
16:17:15 Looking for TAP results report in workspace using pattern: **/*.tap
16:17:15 Saving reports...
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1002

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2468/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1809/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2472/ for details.

**Comment by yosefe** [comment]
@brminich pls take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1812/ for details (Mellanox internal link).

**Comment by brminich** [comment]
:+1:

**Pull request merged**
