### PR TITLE
CMA: Cleaning valgrind errors

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
The pod7 error is unrelated, but interesting. Do we want to open a separate bug ?
```
[ RUN      ] test_ucp_atomic.atomic_add
[pod7:9340 :0] Caught signal 11 (Segmentation fault)
==== backtrace ====
    0  /ccs/home/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/src/ucs/.libs/libucs.so.2 [0x2b664a582f75]
    1  /lib64/libc.so.6 [0x3074c30030]
    2  /ccs/home/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/test/gtest/gtest [0x459308]
    3  /ccs/home/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/test/gtest/gtest [0x45c785]
    4  /ccs/home/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/src/ucs/.libs/libucstest.so.2(_ZN3ucs9test_base13TestBodyProxyEv+0x2c) [0x2b664abd3b4c]
    5  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x8b) [0x2b664ae2f0fb]
    6  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing4Test3RunEv+0xe9) [0x2b664ae20669]
    7  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8TestInfo3RunEv+0x135) [0x2b664ae207a5]
    8  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8TestCase3RunEv+0xad) [0x2b664ae2085d]
    9  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x28d) [0x2b664ae23cad]
   10  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x35) [0x2b664ae29155]
   11  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x8e) [0x2b664ae2ecfe]
   12  /autofs/nccs-svm1_proj/csc040/software/rhel5-x86_64/ucx-build/gtest-1.7.0/lib/.libs/libgtest.so.0(_ZN7testing8UnitTest3RunEv+0x60) [0x2b664ae1cfc0]
   13  /ccs/home/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/src/ucs/.libs/libucstest.so.2(main+0xb2) [0x2b664abd2942]
   14  /lib64/libc.so.6(__libc_start_main+0xf4) [0x3074c1d9f4]
   15  /ccs/home/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/test/gtest/gtest(main+0x59) [0x40c209]
===================
make: Leaving directory `/autofs/nccs-svm1_home1/buildbot/buildbot/pod7/ucx-rhel5-x86_64/build/test/gtest'
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/763/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/199/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/766/ for details.

**Comment by shamisp** [comment]
@miked-mellanox  - I need a review

**Comment by shamisp** [comment]
Why GitHUB made the close button where merge supposed to be !!!!

**Pull request merged**
