### PR TITLE
TEST/UCP: Show error message when skipping ucp test.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1929/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1305/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @alinask pls review

**Comment by shamisp** [comment]
👍

**Pull request merged**
