### PR TITLE
UCT/IB: More of clang5 compile time fixes.

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5886/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe what is the failure ?

**Comment by hoopoepg** [comment]
@shamisp it seems one of the hosts is failed

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5898/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
on ppc64le
```
10:45:23 [==========] Running 2141 tests from 530 test cases.
10:45:23 [----------] Global test environment set-up.
10:45:23 [----------] 1 test from ud/test_ucp_stream_many2one
10:45:23 [ RUN      ] ud/test_ucp_stream_many2one.send_worker_poll/0
10:45:23 [clx-ppc-04:101779:0:101779]    ud_verbs.c:110  Assertion `ret == 0' failed: ibv_post_send() returned 12 (Cannot allocate memory)
10:45:23 
10:45:23 /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/ucs/debug/assert.c: [ ucs_fatal_error() ]
10:45:23       ...
10:45:23        33     short_file = strrchr(file, '/');
10:45:23        34     short_file = (short_file == NULL) ? file : short_file + 1;
10:45:23        35     ucs_handle_error(error_type, "%13s:%-4u %s", short_file, line, buffer);
10:45:23 ==>    36 
10:45:23        37     abort();
10:45:23        38 }
10:45:23        39 
10:45:23 
10:45:24 ==== backtrace ====
```

**Comment by shamisp** [comment]
Not sure how it is related ? I don't have ppc.

**Comment by hoopoepg** [comment]
UD may be used in wireup to establish connection
I bit played with your changes - it works fine up to 64 bytes of alignment (128 byes on PPC failed). what about set alignment to 16 bytes - it is enough for most of cases (not sure how clang5 will process it)

**Comment by shamisp** [comment]
Ah.... cacheline alignment. I'm surprised it worked on thunderx1 ....

**Comment by shamisp** [comment]
Thinking more about this - why 128B would fail on PPC ?  if this is memory consumption issue, most likely we have some descriptor leak.... or really small mem on this system. thanks for the feedback.

**Comment by yosefe** [comment]
replaced by #2286 and #2287

**Pull request closed without merging**
