### PR TITLE
UCS/DEBUG: Remove ucx error handlers from backtrace print.

### PR DESCRIPTION
**Pull request by yosefe**
The goal is that if there is an error from non-ucx code, and ucx merely catches the error, "ucx" would not appear in the backtrace.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1039/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/469/ for details (Mellanox internal link).

**Pull request merged**
