### PR TITLE
UCT/MD/IB: Fix indirect key creation for MT registered memory - v1.16.x

### PR DESCRIPTION
**Pull request by ivankochin**
## What
Backport of https://github.com/openucx/ucx/pull/9424

### CODE REVIEW

**Comment by roiedanino** [comment]
> do we need MEMIC fixes here? cc @roiedanino

Yes, memic won't work without the fixes here: https://github.com/openucx/ucx/pull/9743

**Comment by ivankochin** [comment]
> > do we need MEMIC fixes here? cc @roiedanino
> 
> Yes, memic won't work without the fixes here: #9743

@yosefe should the memic fix #9743 be added to this PR or backported later as a separate one?

**Comment by yosefe** [comment]
after fixing MEMIC in master, need to add it to this PR

**Comment by yosefe** [comment]
per offline discussion to minimize risk on v1.16.x release branch, will disable MT registration as a workaround

**Pull request closed without merging**
