### PR TITLE
GTEST/UCM: Fix compiler error with gcc 4.4.7

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

This PR fixes compiler error with gcc 4.4.7

## Why ?

Fixing compiler error with gcc 4.4.7 on boo31:
```
ucm/malloc_hook.cc: In member function ‘virtual void malloc_hook_bistro_patch_Test::test_body()’:
ucm/malloc_hook.cc:928: error: insufficient contextual information to determine type
ucm/malloc_hook.cc: In member function ‘virtual void malloc_hook_test_event_failed_Test::test_body()’:
ucm/malloc_hook.cc:990: error: insufficient contextual information to determine type
ucm/malloc_hook.cc: In member function ‘virtual void malloc_hook_test_event_unmap_Test::test_body()’:
ucm/malloc_hook.cc:1016: error: insufficient contextual information to determine type
```

## How ?

Use a static variable to determine whether we should call `vm_unmap` or not in a bistro munmap callback instead of be parameterized through a template.

### CODE REVIEW

**Comment by dmitrygladkov** [comment]
@hoopoepg can you review pls? wdyt about this approach?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10611/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
> What was wrong with gcc 4.4.7?

I see the following compiler errors w/ gcc 4.4.7:
```
ucm/malloc_hook.cc: In member function ‘virtual void malloc_hook_bistro_patch_Test::test_body()’:
ucm/malloc_hook.cc:928: error: insufficient contextual information to determine type
ucm/malloc_hook.cc: In member function ‘virtual void malloc_hook_test_event_failed_Test::test_body()’:
ucm/malloc_hook.cc:990: error: insufficient contextual information to determine type
ucm/malloc_hook.cc: In member function ‘virtual void malloc_hook_test_event_unmap_Test::test_body()’:
ucm/malloc_hook.cc:1016: error: insufficient contextual information to determine type
``` 

> BTW, is it supported by UCX?

It seems that gcc 4.4.7 is default on CentOS 6.7

**Comment by dmitrygladkov** [comment]
replaced by #3690

**Pull request closed without merging**
