### PR TITLE
 UCP/DOC: Multiple fixes in UCP iov doc

### PR DESCRIPTION
**Pull request by brminich**
## What
Fixes in UCP IOV docs

### CODE REVIEW

**Comment by shamisp** [comment]
@tonycurtis - can please take a look

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/ddd243875868d844080020b9645e6c9a9f3891cc/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/04f02cc37c4f8f5a8a12a2288fa4b25ddaadbb67/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/2889fada8d307da1b79aab58adb775da87ebbb5f/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/30b697564b02954e697e8e18d7c2e26640a99ee8/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/c11c9204dbad2c2a73040f077687dfdcb345a4fe/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/0516d7ec6166bcbbc594faf839af4f604d63fab9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/689d55378383c631f2e4ede681645db131371033/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/f3bd870e4db30fc24135cb61ff03fe8e6c98ece8/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/7c4d4c73c199fdef41f3f56fa60f57c6194dcfad/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/fc6f566e820d1c6cdbed03246e942f665fb024a8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/84911f2d28ba8e686dcbcaab9adb7c17332864b9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/ccd88675cb29ed331e51e5e0422f7f3987f9874d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/5a2d398efbfd82b4f120dd90515468c8efad5642/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/c1d75ce64ac78aa54f9e00e2b16e4362b0bfd8d4/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/0efa1d22a732f911634bf5d46d59155f6743c2e7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/a9a0ce930565667bc4d5a4d0e7913c1f7646253d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/7a48fa5c37098ed68374be7e5ae2e856c1bd9eab/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/0edc2f777a0a30a3f07aea094fc02e58c5b346f0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/a9fb30e77c31298740b507562fcc8fd8cf269ae2/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/465e9934e5a5c16796a0ffca3e71f4218f58ee46/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/7c6b07069bcb06eb452f756501b9a76dd0e3b798/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/3ebb304aa67756f2456edb9facf271e49b704cab/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/b2c6f2075bf79fea3f393fc747e68809bbb0b585/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/1bece3c146fe7fd7011b838272d31c981b03521e/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0a80b443654ff5833ec048782a40efa1/raw/c450dbd5693370cf35f6649fe514812e7d2a1461/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/6eeb0843e83089023c6480fe8109a59b0b5fe959/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/e8b859e7f6e83ec9c608133082444b6871a9479f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/5e2b7124fdb13f2149b96919832be973f6a258cd/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/6fdb1215773232d4a2a79c0d1bb413b9d3cf9b12/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/920bd03ae16c8a956f2ad104b9a9445bf36250c8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/cf5dddb031d359c16d58be3047f0a5fa301a392a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/8ba2ac4428176c27277ce0ee9cc578015e2d30d6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/682cd1c3c4177d7d700f1b9cac019f5b917a4754/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/ec8212d03f148fa089975ffea13622a849b61d6d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/6ab54e91b2504de19721edf907826f741b8f5a81/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/8ca236745cf1110f8494bfff2fe704e7902a677e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/7ba3878a7fc34a7f31531ac91a48b43ea4b46fb8/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/192a125d389698b5ec875e16ab60a0d5e0664ab4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/8e051f507e88c3ad34410f56248b7dcc625f6afa/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/a083dac66cda634243c86456fd1a8112aa0206a2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/847ed7ab178ba0c07db05fae886613476118156a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/549f236b74c0ef6dba2c1248a8d58a8fde9813d2/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/b13ae9d43045cb4f8c8254d3a9ee2fa5d228d2fa/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/053ac4bb3ab8ef5ab5196734de17413b0c1a8b62/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/8fec09e9e7eddb80cd1aea342c8e7d7fe9aa308d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/15c4a434424db4f77e891b362104564625fc77a0/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/0849f7847aabf431bcc6f19f1f0eedf2169da071/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/a08678941f661475fc72b30eecb5e74fbd413a50/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/60e86cdb4aec841282f5027b385724aa33f84073/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/69057a272b0df2c741a6bcd029d9d0a9/raw/3e81fc2c1e1a07a801dd8d739e66dab869466dd3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
👍

**Pull request merged**
