### PR TITLE
API/UCT: remove the unused uct_event_types enum.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4172/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bbenton @shamisp pls take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4174/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by bbenton** [comment]
:+1:

**Pull request merged**
