### PR TITLE
TIMER/UD: Pass current time to ucs_twheel_init().

### PR DESCRIPTION
**Pull request by yosefe**
Fix for #518.

### CODE REVIEW

**Comment by alex-mikheev** [comment]
looks good to mw  :+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1200/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/620/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
fixes #480

**Pull request merged**
