### PR TITLE
UCP/API: Remove ucp_rmem_ptr() since it's not implemented.

### LINKED ISSUE #1582: Document that ucp_rmem_ptr isn't implemented
I've just spent an hour puzzling why I can't use it...

If the intention is to eventually support the function `ucp_rmem_ptr`, then, perhaps:-

- implement it and return the `ucs_status_t` equivalent of `ENOSYS` for now;
- remove it from the documentation for now
- mark it in big, bold bright letters in the documentation that it isn't implemented

If it should be deprecated, then perhaps implement it to always fail and annotate it as deprecated.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1582

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1830/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1836/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3772/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3782/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlnx:retest

**Comment by shamisp** [comment]
bot:mlnx:retest

**Comment by bbenton** [comment]
:+1:  for Doc/API

**Pull request merged**
