### PR TITLE
UCT/DC: initial implementation

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe please take a look

dc_verbs skeleton, query functions, ep_create_connected, am_short and
flush

TODO:
- dci selection policies
- tx moderation
- pending
- am_bcopy/zcopy
- write/read
- atomics
- accel dc

### CODE REVIEW

**Comment by MattBBaker** [comment]
So this one was actually a build failure.
```
Making all in src/uct
make[2]: Entering directory `<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/build-tests/src/uct'>
  CC     base/libuct_la-uct_pd.lo
  CC     base/libuct_la-uct_mem.lo
  CC     base/libuct_la-uct_iface.lo
  CC     ib/base/libuct_la-ib_device.lo
  CC     ib/base/libuct_la-ib_iface.lo
  CC     ib/base/libuct_la-ib_log.lo
  CC     ib/base/libuct_la-ib_pd.lo
  CC     ib/rc/base/libuct_la-rc_ep.lo
  CC     ib/rc/base/libuct_la-rc_iface.lo
<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/contrib/../src/uct/ib/rc/base/rc_iface.c>: In function ‘uct_rc_iface_qp_create’:
<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/contrib/../src/uct/ib/rc/base/rc_iface.c>:304: error: ‘IBV_EXP_QPT_DC_INI’ undeclared (first use in this function)
<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/contrib/../src/uct/ib/rc/base/rc_iface.c>:304: error: (Each undeclared identifier is reported only once
<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/contrib/../src/uct/ib/rc/base/rc_iface.c>:304: error: for each function it appears in.)
make[2]: *** [ib/rc/base/libuct_la-rc_iface.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/build-tests/src/uct'>
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `<https://pod9.ccs.ornl.gov/job/ornl_pod9/ws/build-tests'>
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1214/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1821/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1216/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1823/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1217/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1824/ for details.

**Comment by MattBBaker** [comment]
So now the ORNL failure is just the get_time failure

**Comment by alex-mikheev** [comment]
@yosefe pls take a look at the last commit

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1221/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1829/ for details.

**Comment by MattBBaker** [comment]
The ORNL failure looks the same as the Mellanox failure. 
```
make[2]: Entering directory `/var/lib/jenkins/jobs/ornl_pod9/workspace/build-tests/src/uct'
  CC     base/libuct_la-uct_pd.lo
  CC     base/libuct_la-uct_mem.lo
  CC     base/libuct_la-uct_iface.lo
  CC     ib/base/libuct_la-ib_device.lo
  CC     ib/base/libuct_la-ib_iface.lo
  CC     ib/base/libuct_la-ib_log.lo
  CC     ib/base/libuct_la-ib_pd.lo
  CC     ib/rc/base/libuct_la-rc_ep.lo
  CC     ib/rc/base/libuct_la-rc_iface.lo
/var/lib/jenkins/jobs/ornl_pod9/workspace/contrib/../src/uct/ib/rc/base/rc_ep.c: In function ‘uct_rc_ep_reset_qp’:
/var/lib/jenkins/jobs/ornl_pod9/workspace/contrib/../src/uct/ib/rc/base/rc_ep.c:203: error: ‘uct_rc_ep_t’ has no member named ‘qp’
/var/lib/jenkins/jobs/ornl_pod9/workspace/contrib/../src/uct/ib/rc/base/rc_ep.c:205: error: ‘uct_rc_ep_t’ has no member named ‘qp’
make[2]: *** [ib/rc/base/libuct_la-rc_ep.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/var/lib/jenkins/jobs/ornl_pod9/workspace/build-tests/src/uct'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/jenkins/jobs/ornl_pod9/workspace/build-tests'
make: *** [all] Error 2
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1832/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1244/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1858/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1246/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1860/ for details.

**Comment by MattBBaker** [comment]
Failure from ORNL build
```
[----------] 14 tests from rc/uct_p2p_am_test
[ RUN      ] rc/uct_p2p_am_test.am_bcopy_keep_data/0
[     INFO ] 8 8.0k 255x{8..8.0k} nocomp 271
[       OK ] rc/uct_p2p_am_test.am_bcopy_keep_data/0 (364 ms)
[ RUN      ] rc/uct_p2p_am_test.am_bcopy/0
[     INFO ] 0 8.0k 256x{0..8.0k} nocomp 90
[       OK ] rc/uct_p2p_am_test.am_bcopy/0 (365 ms)
[ RUN      ] rc/uct_p2p_am_test.am_short/1
[     INFO ] 8 87 3000x{8..87} nocomp 27
[       OK ] rc/uct_p2p_am_test.am_short/1 (3392 ms)
[ RUN      ] rc/uct_p2p_am_test.am_short/0
[     INFO ] 8 87 3000x{8..87} nocomp 27
[       OK ] rc/uct_p2p_am_test.am_short/0 (3431 ms)
[ RUN      ] rc/uct_p2p_am_test.am_short_keep_data/1
[     INFO ] 8 87 3000x{8..87} nocomp 27
[       OK ] rc/uct_p2p_am_test.am_short_keep_data/1 (3390 ms)
[ RUN      ] rc/uct_p2p_am_test.am_sync/1
[       OK ] rc/uct_p2p_am_test.am_sync/1 (1545 ms)
[ RUN      ] rc/uct_p2p_am_test.am_async/0
[     SKIP ] (unsupported)
[       OK ] rc/uct_p2p_am_test.am_async/0 (66 ms)
[ RUN      ] rc/uct_p2p_am_test.am_bcopy_keep_data/1
[     INFO ] 8 8.0k 255x{8..8.0k} nocomp 271
[       OK ] rc/uct_p2p_am_test.am_bcopy_keep_data/1 (331 ms)
[ RUN      ] rc/uct_p2p_am_test.am_short_keep_data/0
[     INFO ] 8 87 3000x{8..87} nocomp 27
[       OK ] rc/uct_p2p_am_test.am_short_keep_data/0 (3436 ms)
[ RUN      ] rc/uct_p2p_am_test.am_zcopy/0
[     INFO ] 0 [pod9:32265:0] rc_verbs_iface.c:63   Fatal: iface=0x122a220: send completion 0 with error: local length error wqe: 0x7ffd60cf4ab0 wr_id: 0
[pod9:32265:0] Process frozen...
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1863/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1251/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1887/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1925/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1301/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1931/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1307/ for details (Mellanox internal link).

**Pull request closed without merging**
