### PR TITLE
GTEST: update the sockaddr to connect to if the listener's port changed

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11984/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/e6667302609cac2e280bc18b6d9a9424cfd50078/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/d30a9b0a2493ed2318a7a7fe61c92bcc1da75ac6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/4b6379f0d864e1c2df495c2e74cf1afca721f01f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/bcf40e94de2dfa68f6a016537175dbf18dd79a8d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/b51b79322ed73550366df58c3dcfbc5026ca775c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/1d84d0e50aabc6eedc97113e641ced8602005d89/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/aa427b41f3e21f35a76cc144d56a27cff4f50f18/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/642b9fdcd94f705d9b5093c2733bbeb5f510bae9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/bae6a5e08aae3e4c65dc629d8d550f718ec583be/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/57f9d5f7cb2030b2fcfacac603a595cbedd9549f/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/006e0ca12abca290f155fe79d38aa86864a6de38/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/bee42b35eed6fdd4057e6e58d6bc537f1dd003b7/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/8a037107f3db638fb4f59a52f68d3d9414b990c2/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/9664628a763316484e0eaf1edcd9e4d64892fced/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/e5d640019b53fb1530286c33273af8b41218a09f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/8241f905238894c3aef361b7cacc87b1e69a544d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/8b2d4753ed9a8080714f4e509cd4cf7e7f3694a1/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/1c1ec6b8e085cd93c589a2fdf5928431445c204e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/8e13508665aeff96f64fb55fede45217ba8a057a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/fdd63ad11a07f5736558edfcdc2a17f4dfae729b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/d05686236ba50a258828706ec409ed26578e5c79/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/1a6e205d7b68a0cb0de051914a25d8e9c212bf44/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/3df45a4123a95fc0711621c6aec6ea3a52cb0553/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/b8825c00919fa90b811397fb39508653fdcea5f1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/2ce5c008d374907c8f41ece3a9a169e69db0dde8/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/05fa5bf644489575e203f20f91746fe75b9e31e0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/b9e89ed7b9d1a65c976874b6a666b7802968a8e9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/365875c1f7a86592576ed942d189cf6c583c4a61/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6b8b7028b552a4dc8bd39d5b4a297f88/raw/44c5dc6e4442615ec39a9be3e7fceb4e5b62dada/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by alinask** [comment]
> should we do the same for UCT iface case?
> https://github.com/openucx/ucx/blob/d4af39078fa1c511a44b8fa8771bfbb898f4323a/test/gtest/uct/uct_test.cc#L601

no, the connect_addr is updated here - https://github.com/openucx/ucx/blob/master/test/gtest/uct/ib/test_sockaddr.cc#L85 after the listener's port was set (and reset if needed) in create_entity here https://github.com/openucx/ucx/blob/master/test/gtest/uct/ib/test_sockaddr.cc#L76

**Comment by alinask** [comment]
@yosefe Can you take a look please?

**Pull request merged**
