### PR TITLE
AZP: enable csclng checks — v1.6

### PR DESCRIPTION
**Pull request by amaslenn**
Picked from #4112

### CODE REVIEW

**Comment by amaslenn** [comment]
@dmitrygx could you please take a look?

**Comment by yosefe** [comment]
rnat
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12222/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 8 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/a80e929bbc299710d32ea764fab0476dcf0af5d2/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/b56f80be34d6c7e6663677590dfb7e1fb65f0f46/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/9269d99763a63acf57b0e26c95cb710751035931/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/78e0ffd4dbe8af85ee49ec63e492a9e93d4094c6/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/8947359ab6b6b339531abb968c6d7ad86358f351/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/e737ba0f5912a62b28c2abf575be69b39fbcbe9b/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/c296bd16a63be0bcee67d59a0e70e936d3981995/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/1be762f01b70a34c83a82c8461cb6c182b4ac9db/hpc-test-node-new_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/7cf6c6dcc794ff459c620f4b135558a62a0c24f7/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/f4695dbe7cfcfe49d2ee10c25be676ba69877d9c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/7c68f95cc4c21625ea32816fe3d58ce675e41049/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/538197dfbff8253ca92a8fb0eb23ac050e7afd7f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/77da569ee20b5b576f69767208e383d8f262a269/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/ae7dfa84ef27fa96ff52521478cc789fd944b624/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/2aca03bfdc33da800e6fa2c8836642bb36f324de/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/e5de98927e8be78eabf81454ed081fb9d0eda444/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/b49c508b57529c0e13ad8c8192c475302ab20098/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/35c973a0f539af7160294497555da2abfeeb106c/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/94518b9cb55ccf04f28e71619c3a2f9d1c6a9cca/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/a3a86579b93e7429b5d88c35d5015c19bfd34234/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/91571b5af5ee633714e4a02d7a2d1df40011e12f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/296fe968b58162c042e4e03fd882eb5a9881953f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/cafb05a814b558cedb2f8a539a225985e30c790c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/16122fa1426b926df7d236e068335da2f186c027/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/6580bbd567eb33cb69afbd5bac0680bde8f4abbe/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/f0033057f2a5bb58a5d969aa478fa2ab1ab10a74/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/65b3de730587e89fd2f15c441f8f5b73e21ecca2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/bc6eec83c39a206eef8ff4b282ca8387c4cac617/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/beb6ed1553dad1b97533d2a063ef2ef8/raw/b510fa76339a9618e52e0eb2c118fe3e213e52e5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
rnat
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12245/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/8ae6429167c07195299fcdc1df88c479671e9ea1/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/938d5c0494064bcf39b065340e29eef62f109641/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/caa509f64ed1d7269076a47a6deaad4c42062a9e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/0868c1b916870d7c2a1920b6ea3cab2e85eb5e69/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/a7a4b61de34f03736c41cab044cd8755092b7375/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/44e7c84090cb593129955d13c2995aeaf1b6f558/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/7ed74f158cf264c1fa8e722c666d1c77b9b30762/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/eaf8f5f533117d664d066be7154899a861fc98f5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/5d321060e5d43d801a45e3b2353fa5f8df8adedb/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/b4670543956d4851530a16c64402f59e3ccc3483/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/034f0eaa8feec045be62853269fca8bb9278e9c5/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/f58c7d12a57a94ff61e59ce06962b5a789a96eed/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/8e1ca039476ef56d6f1dc47c584d3fba2ce56f59/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/7f35f5d2b4d02f92e3954ab80353527a9108a7ca/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/dc47947de41f1f0a9c5364dcf39253b2f8d9308a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/0aa811238af0b82ed4967ec999bccfbc8bd9fc73/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/06dda163cb07c83aba8951d094af84c66ed98582/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/519011d409293c04ddf95a0a66e5e6a8c48ce819/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/605d035f607fde675442544a2d622b82f7bbc06f/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/66f8ea4613d6d8ea0ef945358ee24c7564315c8f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/2b94a825b6e47976db3d534326fbe64c9ce8160f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/904acf75e8b4544b873e97cc7e07815c514b5492/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/693c81615c61a614869f661e865eb69d49fce51a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/d9da4f3a7c0314dabfc97ddb48c45b4eba2ec17f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/c4331fe10e9e544a9d76f40a4452c160b54817d5/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/1069f9f05f9bae89f95e5aa1db89b7765875b08e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/d81e33e7a06d8aeb17eac22245f771b4730db41f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/80d42719840bc270ca4c7ca0073f0b4d43d49d8b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ecba4ebfdb2fdc86bc2fae571f7344e3/raw/23ea8def065f39c1b208329302ad64c671ea345c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
