### PR TITLE
UCT/SELF: Fix overhead estimation to be non-zero.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe the new value you set is the same as mm's on purpose? 
so that iface_attr->latency.overhead would be the deal breaker between mm and self?

**Comment by yosefe** [comment]
@alinask yes

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4002/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4007/ for details (Mellanox internal link).

**Pull request merged**
