### PR TITLE
Reverted UCT/CUDA/CUDA_COPY: Set device context within mem alloc.

### PR DESCRIPTION
**Pull request by rakhmets**
## What
Reverted https://github.com/openucx/ucx/pull/9346

## Why ?
Please find reasons here https://github.com/openucx/ucx/pull/9346#issuecomment-1714347976

### CODE REVIEW

**Review by yosefe — COMMENTED** [review]
can't it lead to memory leak ?

**Comment by rakhmets** [comment]
> can't it lead to memory leak ?

It shouldn't. The primary context is not created by the UCX. It is only retained. cuDevicePrimaryCtxRelease is a safe way to reset the primary context (cuDevicePrimaryCtxReset). But we do not need to do this inside UCX.

Even calling for cudaDeviceReset is not mandatory by the way.
( cudaDeviceReset behaves as cuDevicePrimaryCtxReset, if the primary context is a current context for the calling thread. )

**Comment by yosefe** [comment]
@rakhmets According to Cuda doc, we should release the primary context:
["A retained context should always be released once the user is done using it."](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__PRIMARY__CTX.html#group__CUDA__PRIMARY__CTX_1gf2a8bc16f8df0c88031f6a1ba3d6e8ad)
Maybe it would help if cuda_ctx_retained flag would be per thread?

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
@roiedanino pls note that now we need to set cuda context from perftest

**Pull request merged**
