### PR TITLE
UCT/XPMEM: Fix build on ppc64le

### PR DESCRIPTION
**Pull request by yosefe**
## What
Fix XPMEM compilation on ppc64le platform by converting segid/apid to unsigned long for printf()

## Why ?
Make pmem module compile on ppc

@amaslenn

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe No CI for this platform ?

**Comment by yosefe** [comment]
> @yosefe No CI for this platform ?

CI didnt have xpmem libs

**Comment by hoopoepg** [comment]
build on ppc+xpmem - built fine

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/a8f47b73149a8ee439f58db51db95d1d05f66ff3/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/737fb9a1fc1c75d1dcefa444fca91ac3d04ceac2/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/ceb43e02c5bc880668dc60d9b1091593a6fd7882/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/870f0bd2c861122ae8faa63a58c1715264f057f6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/31124f0de361b9c24fc0dd14a4ef4e7dca46feba/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/292358a0e44b041f3da847fec6ef0750e3588c0d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/fc4283af7648ee005694469744814efe924e9b7c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/85473f0a6b72b52b0995fd3fad77f8b4e509de68/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/fac567adc25c7313468777181ae419564794784b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/f15335c64d895c08e82155d0c955ff6c1b066865/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/279b9cf12d278f54ff53136aa6bef084bfeec998/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/a2a20b1fd9d28fdf6e008837fce73882a54f4a5e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/f6ce4f834838b5c0a39ec9491a28766232e058b0/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/d90ed1810bf7b9001a6d6e88754529d37eb77304/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/648d982963a03019b8b6bea218bef9456b24b941/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/491dad03c91021a1ff2faca1c037ac7aff4d7a51/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/9a37017929cd6e6046befc8485e370c395cca6cd/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/5b597b1905b484c84f2503c37a3d3fe904101ff5/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/17a31a2f9dfa116bfc7c6e5470cece1f275316c8/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/926ca4066b447cfdffecaf86745e75b8e530953b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/a37db918ee608ef04952bcaf014b3dc69d69bf1c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/978d0add395a405315ec8d0d83b1bf3b85ffcdfe/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/e396eb9db48c1eb6e0fb1ee4284c6313bd2e9ce0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/a08551cb4c7fb9831b922355c3e0305076893110/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/13e4fab651f4d1c84473b07ee1abc198/raw/f9e7bfc71be101ca99c5ade7fc5f53222673e1f3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
- coverity license not found
- zombie processes on hpc-test-node-gpu01 caused timeout
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/e29954e93d648d505eb06e4ab490aa6e41e7bf3c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/44f346b16d8f611a54308eb10be9cb83d9d44841/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/0fa8557a2e6afcb7f109709006c1f9192693601a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/032ff53df91446b0962cc4dadb9aade0fb317bf4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/395e0c86bcc7b3ab521190d44e0795f3bec7d7ab/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/0c16d1cae1041cb097d1ad7592944326d55237f0/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/cbad0e3643d0f62791f0f88d30081f88f135704c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/574a21d40b314f7db41f1d4cb40923b1f546c6ee/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/a6f7388d4108748a85b762edfd9a57e25422477a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/8f7e8c1ec6c8806cecaa70f0f3ab848bf9f7df78/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/ac139080b9fa0948c2acb5b38f589927cd60ad3a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/9f8f8d13ba881cf4bb55a750bb74a6997c730dde/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/d8523e228cd2e8da892e4f3a71de84e81dfac82f/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/297cf1c5493753bf7ac30a1f55cde3a1b0e19eb0/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/1b1c98e2ec0ff51dc1c33b9f639f68711869d697/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/575afab17f7ea7504fba8ab7cdeaa6fac0858d9a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/874049f5f4fd143d60551111f4a1437951ac551e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/4434e775238e4e23d17df197d88abf74f7a1f6f7/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/da79e7b55b9310a84c376bfbbacd14fc0fadb4e1/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/a332fa786d017b555363765564ffd3643a7b7d02/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/81c0a6b4040326b16d27e2c83bdeb7735d0e3f47/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/24767ff2e0633cff42be86bced09be817154ba7c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/d87ff59ee59d3aa0651cc612d940d55dde90f5e8/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/693a7fc27fc2ed60f3362c6d59f6a5ad2f15a056/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a7b12c16ffed614b096dbbf2fceb21d/raw/ae8250407f53641138cb406097498960abf80886/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
