### PR TITLE
README: build from git or from tarball

### PR DESCRIPTION
**Pull request by bkmgit**
## What
Update installation instructions in the README 

## Why ?
There is no autogen script, use autoconf -fi instead.

## How ?
Update Readme

### CODE REVIEW

**Comment by bkmgit** [comment]
autogen.sh is available when cloning from git, but not in the release tarballs. The README is also distributed with the release tarballs.

**Comment by yosefe** [comment]
> autogen.sh is available when cloning from git, but not in the release tarballs. The README is also distributed with the release tarballs.

Need to update the instructions that autogen should be run only when cloning from git. Otherwise could just use `./configure`, no need to re-run autoconf.

**Comment by yosefe** [comment]
@bkmgit Thank you for your contribution, in order to merge code to UCX can you please sign the contributor agreement - see https://github.com/openucx/ucx/blob/master/.github/CONTRIBUTING.md

**Comment by bkmgit** [comment]
Thanks. Related issue on CLA signing https://github.com/openucx/ucx/issues/8892

**Comment by yosefe** [comment]
> > autogen.sh is available when cloning from git, but not in the release tarballs. The README is also distributed with the release tarballs.
> 
> Need to update the instructions that autogen should be run only when cloning from git. Otherwise could just use `./configure`, no need to re-run autoconf.

@bkmgit to clarify, we don't need to advise running autoconf directly in the README. Should advise not running it at all with source release tarball.

**Review by yosefe — APPROVED** [review]
pls squash to a single commit and force-push

**Comment by bkmgit** [comment]
Done

**Review by yosefe — APPROVED** [review]

**Pull request merged**
