### PR TITLE
API/UCP: Added clarifications to the ucp_worker_arm() documentation.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6528/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe @shamisp @bbenton @gmegan Can you please review?

**Comment by yosefe** [comment]
@shamisp @gmegan @bbenton pls take a look

**Comment by shamisp** [comment]
👍

**Comment by gmegan** [comment]
+1

**Pull request merged**
