### PR TITLE
UCS/MPOOL: Add option for FIFO behaviour in debug mode, instead of LIFO.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/913/ for details.

**Comment by shamisp** [comment]
autobot build

**Comment by yosefe** [comment]
@shamisp @miked-mellanox pls review

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
@yosefe - what is the motivation behind this ?

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
