### PR TITLE
TCP/KEEPALIVE: enabled ep_check feature for TCP

### PR DESCRIPTION
**Pull request by hoopoepg**
- added support of keepalive feature for TCP transport

### CODE REVIEW

**Review by dmitrygx — APPROVED** [review]

**Review by brminich — APPROVED** [review]

**Review by dmitrygx — APPROVED** [review]

**Review by dmitrygx — APPROVED** [review]

**Comment by hoopoepg** [comment]
rebased to master

**Comment by brminich** [comment]
@yosefe, can you please review?

**Review by yosefe — APPROVED** [review]

**Pull request merged**
