### PR TITLE
UCP/EAGER: fixed failures on MPI test suite

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed mtt failure
fixes https://github.com/openucx/ucx/issues/2224

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6031/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6033/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe could you look please

**Pull request merged**
