### PR TITLE
UCT/UD: Fix reordering with pending queue for sends from am callback

### PR DESCRIPTION
**Pull request by yosefe**
+ Add assertion check that sends are not reordered to make sure we are
  not sending something directly while there are pending operations on
  the ud endpoint.
+ Before invoking AM callback, block sends if the arbiter group is not
  empty - by raising the async event flag.
+ Extend flags and rearrange fields in ud_ep to reduce memory usage.

without the fix for ud receive flow, udx/test_ucp_perf.envelope/0 fails on the new assertion

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6637/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6644/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6645/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls take a look

**Pull request merged**
