### PR TITLE
donot put request on matchq when the key is deleted

### PR DESCRIPTION
**Pull request by shengyang-3390**
## Why ?
when the key is deleted, there is no need to continue to deal with the request

### CODE REVIEW

**Comment by brminich** [comment]
ok to test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/434da577a862bbb9649cc314284df5334b2dffa0/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/5f9b5446ebd46bdda54db43cbd96f0e6124887e3/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/39e46e4dcc734056aeca1a43e1cd7fa31919f15d/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/2a996769c0cbccd7a1be0e6582930c01aa75fc4f/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/c164db63be50fcd7829a4341b0dd1028492303fa/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/627c3fbf0ad1bf768900aea56e7e9467a2c81c25/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/6ad4a445f5c6ec3e756568b1afdcc347cd3f55d2/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/0aec98b49f051f8fd35a0a8a35873592b19d509a/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/624000cf8f1851eb617f02ed947cf981266e1b82/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/77b7d37db2f30176cdf28e51892c32e2887ec202/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/91590f810dda02e933db406d2e909e839bb000f0/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/3c9f6aa22909c887f9b4df90fe2f58fbfbddbc2a/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/e772c81d6b9e6cb76e162d41575e289f64c5632c/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/b18ebdd14bf8ffaf3a8cd7ffeb82cb7953df31c0/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/f9cf379d9372a8a68d14f758f92ff69ccc9da805/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/3cc009943580189b47f9da470a971b1be8facea2/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/013020a3250e93442aa96ce91a646297d781c190/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/10461eccc9812f0590ffccf72d231d5355ef3fd8/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/28a356ce6b914642836e546d0fb0829ce326e763/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/fec159570bd454b1fde4da3e46b48627132eaa13/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/2b4f014353ecc7978b479b6ae5277dd4dcdb5e97/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/8eed175cf208cb1b1d942faeea3a0389e9359ea8/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/e04715a5366c3999c763808466ea3375eca02cad/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/cbb79f91e094257ace278733b0e40f97d674af5a/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5c25f475eea62a9da345758e73c1db70/raw/52f568d1d06428519c71898f984f286c680a141a/r-vmb-ppc-jenkins_W3) | :question: ABORTED

**Comment by shamisp** [comment]
@shengyang-3390 Can you please let us know what organization do you represent ? I have to check CLA. Thanks for the patch !

**Comment by shamisp** [comment]
@shengyang-3390 just in case adding link to corporate/individual CLA https://www.openucx.org/license/

Also, please squash the changes.

**Comment by yosefe** [comment]
bot:retest
/azp:run

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 13 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/9c8f6e1045f3cbd158d94d8315711d4807fcfbf3/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/ddb41f417199475ba695fd4894926d4356981c0b/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/cc1dec53a3182e5fda5ca4d81ee4e6101790ba08/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/da9a9f283bb5404e011c4766bbcdc7fba139ebd9/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/92c3f5dd834ddff6273dfb74910e3f8b2de0cf9c/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/b43163f9507742081802742712faba1b3e852221/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/dc266871c83c1e9f497b48fa9ca5a8dcde485760/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/d6ce7dffb412dbaee39c8722b47b0c59143c45e1/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/081f524faaac106026d0712c5b2e3fef919eaef4/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/4e8ae606cb261db10e27fb79348aa8b5b67a54df/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/b2e382591eefeb3c68262a06790587121f855730/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/219bb8563ae7ec8c4ef6fad4f49adf68304965d6/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/d895183fb500b20698ab1df458b7b4f8703bcf03/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/0e7752cc1c6758804f4ad25abef4cc3c1b8055fc/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/172a494109ca710fcb0d02a64b4d1158476fd055/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/6dbf50653055b03d63d86569fdd84d55db43b9ca/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/d459c31adfaee00d95869513d3681624a176674a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/2fbd15e7401f6240aece4f01976c8f74990d75f6/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/de629f036946725bc956dca0d65e451f6946f419/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/fea1c48ab4642eb875ededcd6320d80ad3cb12d3/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/091b7a4410e0d43e72ca02434dd618b8b66e8640/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/8fd8ddbc4bb1beb5c4ca26d0205b66c683529702/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/d9f24bbb2ae32d813aacc21cdd1c509ec403627d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/b84ad8f810709f9d022cd1acf888927241e21b9a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6abe6c391c933702c028761b70c67703/raw/6825144df2cd2ebc96881e0a0da7dfe164218c9c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/787d1be1460682c060b292b05ba6d59b/raw/c69b201b7ffc33e297acc587fcfb29a4abcffd64/_main) | :x: FAILURE

**Comment by shengyang-3390** [comment]
I submitted the code again #4444

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 7 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/9290a830de3a1167849aa023fbb625352ec54a00/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/daefe5c051fb5825e3c285273ac8b15d8849af2c/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/13ee5ce26662cbaee738bafb53a732010ff63191/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/14957d5a3b42e0a448dda4cd4d586e0fcee5b817/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/849de8ec1b5c337b0c4266e05f4338166ec11ec2/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/325e9802a5cc90c9eede4a597e8e49dc7f063be7/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9d5eb034015e27d9caf19faeb612315f/raw/80fb8ee9f0bd50a746db909605bdb8e3b9b6bd98/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN

**Comment by dmitrygx** [comment]
@shengyang-3390 can this PR be closed?

**Comment by shengyang-3390** [comment]
ok

**Pull request closed without merging**
