### PR TITLE
IB: Implement getting device address.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1022/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1636/ for details.

**Comment by shamisp** [comment]
@yosefe - who / when will do it for ugni and sm ?

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
:-1: 

 I wanna see what is the plan for other transports :)

**Comment by yosefe** [comment]
will add an implementation for other transports later, for now it is stub implementation, and unused.

**Comment by yosefe** [comment]
@shamisp would you prefer that i added those as part of this PR? because the code is already in place but i wanted to split it to smaller PRs

**Comment by shamisp** [comment]
@yosefe - agree - small PR is better.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
