### PR TITLE
BUILD: Fix autoconf for disable-assertions.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4822/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest
failure due to #1913

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4824/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4825/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Pull request merged**
