### PR TITLE
UCS/CONFIGURE: aarch64 default is to have HW_TIMER set, change config.h comment text to reflect that

### PR DESCRIPTION
**Pull request by tonycurtis**
## What

Update AC_DEFINE text to indicate h/w timer enabled

## Why ?
Wrong text in comment

## How ?
N/A

### CODE REVIEW

**Comment by shamisp** [comment]
ok to test

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
ok to test

**Review by shamisp — APPROVED** [review]

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
