### PR TITLE
JENKINS: Reduce cuda ucx perf tests iterations

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/b748f0ab35a406b1f6850d28b1b046be04829508/_main) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/f6f412024643fe6ef4f303b04b4d1eaf1984cde0/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/99423febc82d086898680d7ff8886eccb247ea0e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/64aeadb22ab62e6c62d7fcb50ea881bd7c2d81cc/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/5c7b630784afcb074321271ffc357b784575c08b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/d3389f53fca6cec49d8c50442f8f9ed9278c2fb8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/21a705c52e0a88071e115957cc8dfb61b9b27ef7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/5558bc2dec292f924f07bc7e4b6958bd038f6c1c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/eb2de1d786cd1e99e35aac49bc3bbfaba19b5ad3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/177c84b2897f438981c42b444aa7248496b57ae0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/fca9f53edd8d2412173fc3b0b430897a1e249b56/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/ae9c5738edb186625a3eb2795b8371c76a4cfbce/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/d303144e01e02ae8951b6d8d9e8b9fb071f900c5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/c69b9c9ae6aa08612ffaa3ce160a65e1a6812fb3/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/b1db6532276aefc041bf5141953be67733bf012f/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/60e46dfc4787b000929c40086d14e6e92235ab9a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/476659a8b08555bc10cbab85043934d7ef105edd/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/0cb48f06fb6ad85900afa05b4072ea3bc67ec115/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/9b743d6a674ead161a8a04bfa8696474d781fcf9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/dfb02fd0a2cf19f03676ca6d4ae336613c7d4857/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/c5edbb1311ec21da2c5ffd7f023eb6fb09d130b0/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/889453bcf02a8dac6635215d643a8d427bc4a95a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/2a4a9db91d103db6e4fb393358c4460a32074eb1/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/b3ee478b832a8728e56f0fa3cdc7e2d20d443fb3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aaa54505d95faf6e20afeb22f0d93a87/raw/d8a213ee6e607974fcd8e2a9cb0d593d3b9bb1dc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by bureddy** [comment]
```
19:39:44 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node-gpu/worker/3/contrib/../test/gtest/ucs/test_profile.cc:393: Failure
19:39:44 Expected: (overhead_nsec) < (EXP_OVERHEAD_NSEC), actual: 54.2412 vs 50
19:39:44 Profiling overhead is too high
```

**Comment by bureddy** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
issue #4458 
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/396fee54518abd8b0f0508f2ef29504f5f7b6b7f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/6b07a0315ffe451e9a765f97bb7348039a5c2fa4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/52a0f5e999e24c44a79d5163c91464c1a2892f97/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/fb850593a83cab4bbf670ce8c868309ed8c407b3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/a6e6d86e8c1ecfe4bbf5b998759588a1b353f55b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/318ad1283d484449e56af7da0c307e973d39ecea/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/1f33ef61e5814823d8a632d71fd6ac6cc385aa5f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/5f33351c6da009f372b56f7a7b3ce232f7115e6f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/57860f820046fdb44fe23a1936cf8880e27e9127/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/2b758d40a1c1ace2fafebed0ce9c8f7d47494906/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/6c1a5f4490b35d86bc8bda61b0e2bd528c7ed6e9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/1c0e0e5ff88a91c26298853d52a75b8632959cb5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/79fbce2d7b47ef26164d328f33e396f2d3274571/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/ce3d18a917be29255b17d78a1fd6087dbf09d859/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/74c095fccb767b712d6bd1a26d5deb0b4b35a46c/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/9a5b8127b1a4a568f1e1559dca572d5705aa6787/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/60d5ce9749a7cad73ebfa4487a4f11e865ee0388/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/3f3616e30a74e5707d3eac0eb2a24e56dc7e5a6b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/cb861ceaae670f0ff40076f00222867489baaa04/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/10ff0c188fc2846e6af04a0e3edb99c0822b697c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/3a108a4c979b527f9f5f4ccdeb968e6b1269fe91/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/f755cd31f69524df403c583b19809bb8e7b8680c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/2b611b452068dea82ee69b553d7a39c94ca16175/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/f3bd82460d538477dfdfe4c4ad24caa7bf72d2b0/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/55fb35bda1ae4f1057a8c143270b9348/raw/57847533e3b228516025713543591f3ecf3aab72/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
