### PR TITLE
UCT/API: Add API for adding progress callback to a worker.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp @miked-mellanox pls review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/915/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/918/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@yosefe , please check your email for the failure.

**Comment by yosefe** [comment]
@shamisp this is probably unrelated failure

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
