### PR TITLE
UCM: Avoid releasing environment strings in library destructor

### LINKED ISSUE #3429: Regression in v1.6.x and master branch
When test OSU with latest v1.6.x and master branch, it crashes when start:
```
[dc-p47-0x:61176:0:61176] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace ====
    0  /home/lsha/yuq/install/ucx/lib/libucs.so.0(+0x1decc) [0x7f711a457ecc]
    1  /home/lsha/yuq/install/ucx/lib/libucs.so.0(+0x1e134) [0x7f711a458134]
    2  /home/lsha/yuq/install/ucx/lib/libucs.so.0(ucs_config_parser_warn_unused_env_vars+0x70) [0x7f711a4506f0]
    3  /home/lsha/yuq/install/ucx/lib/libucp.so.0(ucp_worker_create+0x851) [0x7f711a8a8851]
    4  /home/lsha/yuq/install/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_init+0x7b) [0x7f711aceaebb]
    5  /home/lsha/yuq/install/ompi/lib/openmpi/mca_pml_ucx.so(+0x7b99) [0x7f711acecb99]
    6  /home/lsha/yuq/install/ompi/lib/libmpi.so.0(mca_pml_base_select+0x1f4) [0x7f7547f33f94]
    7  /home/lsha/yuq/install/ompi/lib/libmpi.so.0(ompi_mpi_init+0x6ee) [0x7f7547eaaf0e]
    8  /home/lsha/yuq/install/ompi/lib/libmpi.so.0(MPI_Init+0x5e) [0x7f7547edbade]
    9  mpi/pt2pt/osu_bw() [0x401259]
   10  /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f7545745445]
   11  mpi/pt2pt/osu_bw() [0x40173f]
```

The regression point is commit:
```
fb9bed2005462e2bc04b62c7a08f3b4b3c2ef900
Author: Yossi Itigin <yosefe@mellanox.com>
Date:   Sat Mar 23 14:04:33 2019 +0200

    UCM: Set NODELETE flag at runtime instead of link time
    
    In case another lib depends on libucm.so fails to load, libucm.so
    remains corrupted in the process link map. So we set NODELETE only at
    runtime, when trying to install some memory hooks.
```

When OK commit, I can see some warning:
```
[1553843016.554913] [dc-p47-0x:75976:0]    ucp_context.c:601  UCX  WARN  transport 'rc' is not available
[1553843016.566280] [dc-p47-0x:75976:0]         parser.c:1486 UCX  WARN  unused env variable: UCX_DIR (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
[dc-p47-0x:75976] ../../../../../opal/mca/common/ucx/common_ucx.c:149  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #3429 
@yuq

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9620/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Does it mean we just leak it ?

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
@shamisp no, pls see the commit message for details

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9630/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe I was referring to ```Since we are not clearing the environment now, we also cannot release
the allocated strings.``` Seems like do leak memory but Valgrined simply does not complain about this.

**Comment by yosefe** [comment]
@shamisp we keep the environment variables allocated until the end of the program. i don't think this is problematic because this is same as glibc is doing.

**Comment by yuq** [comment]
@yosefe  Verified to fix https://github.com/openucx/ucx/issues/3429, thanks.

**Pull request merged**
