### PR TITLE
NEWS: Update to v1.6.0-rc5

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11223/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/94cfed0f571104252865834ff6f5d40a28537fe7/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/6d39ccadcaf8cf0be49f8be907721f9890e0a32a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/de7b8e5a99733346b7c60e78a8fc553a2bb13929/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/2d92022f9cde517d6a512d9adf5883f30aa6a223/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/07b989b563bb66ea506f0f489b8b087dab47ac88/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/57a46bc78093324b18d6d6e85b9f17b2f6b8b861/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/1aa23342a2795b42cedd4497a729b06f7fee122f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/b3672662d7d01f1ecabd3c070429d852c9519595/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/604d04ebee5937d6bdda23b3053fa3ac8c3cb664/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/108aafe07d131120244b721ebee0b1c71b4ece15/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/344a711f3d613f1b60d664e2f55b836b8be49dfa/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/8b04f3b836ab565145a122eba5ca79cfcefaa036/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/dc6dd87aec9d5b0e39aa824978ef381ff9b6c3dd/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/77a01dc6f465ddfef9bd85b5883b9fc6ccb13438/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/3fdc91e090f130ec957c14c306683e128e1b1fd5/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/fc96327cbd0c1fdce30f65b91a565fa3bfb1ad25/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/5a2681232dddbbd78eb451fcca17696c5f4d0498/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/77337fcadb3f6c6387a05c4994ccbfe614dd4c96/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/3e40b73cc6a65f18c82207ce753d0080c5c0726b/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/8b47fad1051d1bd321b75412f9cea57ac0f0701f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/78ef135af5da74797480bf4a7253ea7e5a86530a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/76b0d99751376a42a8fce3bbb1d563884b2c9f69/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/ffec9074bb11fce0a12dfbc16605d90178c514ec/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/969ad2f46c437f290eef812ede091d278e89e6f6/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/4d847132fc1cd357cd8a653fc60c0c5ee19f6fc2/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/62cc1052378682f79b41cec12f90252e77440552/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/711681a36db8f14ab83d32b72abb60cb88f635da/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/6c3ded639091b97c6ca26d73b1245334bb012ac2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fc797a399434cf0a7eda7e679c588e77/raw/6627bb00a051e507e5f71023ffd0da8906966212/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by shamisp** [comment]
@yosefe do you tag it today ?

**Pull request merged**
