### PR TITLE
UGNI: Reordering progress initialization

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@MattBBaker please review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/809/ for details.

**Comment by shamisp** [comment]
Ignore pod7 failure

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/236/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe please take a look if you have cycles (this is short)

**Comment by shamisp** [comment]
@MattBBaker please review

**Comment by MattBBaker** [comment]
Looks good. +1

**Pull request merged**
