### PR TITLE
UCT: fix hang when using polling fd #1492

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
Fixes https://github.com/openucx/ucx/issues/1492

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1787/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1788/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3724/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3725/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
@yosefe @brminich pls review

**Comment by yosefe** [comment]
@evgeny-leksikov why need to rearm inside progress, if the user has to explicitly call arm after progress anyway?
e.g use flow is:
1. progress
1. arm
1. epoll_wait/...

so how is adding "arm" to (1) helps, given that we already have arm in (2)?

**Comment by evgeny-leksikov** [comment]
@yosefe because arm did not re-arm if there are any events. Pls, take a look now.

**Comment by yosefe** [comment]
@evgeny-leksikov user should call arm again when getting BUSY, until he gets UCS_OK, which would mean the cq is really re-armed.

**Comment by yosefe** [comment]
@MattBBaker can you please post ORNL failure?

**Comment by evgeny-leksikov** [comment]
@yosefe yes, but some events can be missed between BUSY and next re-arm but not polled from the CQ by progress. So, we have to have re-armed transport all the time.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1794/ for details.

**Comment by yosefe** [comment]
@evgeny-leksikov so you mean that if there are unpolled CQEs, and then arm is done, no event is generated?

**Comment by evgeny-leksikov** [comment]
yes

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3733/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
@evgeny-leksikov what if the event arrives just before arming is done, and the cq is not armed yet? for example, on the first time?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3735/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3738/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
@yosefe Looks like a build environment failure.

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by shamisp** [comment]
probably should go to v1.2 as well

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3788/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
the reported issue is not a bug

**Pull request closed without merging**
