### PR TITLE
DOCS/INSTALL: Fix typo in install instructions

### PR DESCRIPTION
**Pull request by esoha-nvidia**
Simple typo fix

### CODE REVIEW

**Comment by hoopoepg** [comment]
ok to test

**Review by hoopoepg — APPROVED** [review]

**Comment by dmitrygx** [comment]
pls, change the commit title to "DOCS/INSTALL: Fix typo in install instructions" and force-push the change to pass a UCX CI that checks commit titles

**Comment by yosefe** [comment]
@esoha-nvidia FYI, need to change the commit title (and force push), not (only) the PR title

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by shamisp** [comment]
@tonycurtis , how did you miss this ;-)

**Review by yosefe — APPROVED** [review]

**Pull request merged**
