### PR TITLE
UCP/RMA: Complete send request in case of error

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7005/ for details (Mellanox internal link).

**Comment by brminich** [comment]
should not we also use `status` instead of `UCS_OK` in `ucp_rma_request_advance` ?

**Comment by yosefe** [comment]
@brminich ucp_rma_request_advance() already checks the status for error in the beginning of the function

**Comment by brminich** [comment]
somehow missed it

**Pull request merged**
