### PR TITLE
DOC: fix typo - patch should be path?

### PR DESCRIPTION
**Pull request by ofirfarjun7**
## What
Fix a potential typo in the optimizations style document

## Why ?
Training assignment - check I'm able to commit and create pull requests.

## How ?
_It is optional but for complex PRs please provide information about the design,
architecture, approach, etc._

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
@yosefe @ofirfarjun7 - is this contribution by Nvidia ?

**Comment by shamisp** [comment]
Adding @tonycurtis for documentation review

**Comment by yosefe** [comment]
@ofirfarjun7 is with NVIDIA.
@ofirfarjun7  can you pls fix the email in the git commit?

**Review by tonycurtis — APPROVED** [review]

**Comment by ofirfarjun7** [comment]
@yosefe 
Oops... Yes Sure.

**Review by brminich — APPROVED** [review]

**Comment by brminich** [comment]
@shamisp, can you plz approve?

**Review by yosefe — CHANGES_REQUESTED** [review]
need to fix commit email , amend the commit, and force push
pls see the email in https://patch-diff.githubusercontent.com/raw/openucx/ucx/pull/7883.patch

**Review by shamisp — APPROVED** [review]

**Pull request merged**
