### PR TITLE
Topic/doxygen3

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
This PR depends on #408

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/924/ for details.

**Comment by shamisp** [comment]
@manjugv , please take a look.

**Comment by shamisp** [comment]
this ticket was replaced by #419

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/948/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/365/ for details (Mellanox internal link).

**Pull request closed without merging**
