### PR TITLE
UCT/UGNI: Downgrade log level when selecting UGNI device.

### PR DESCRIPTION
**Pull request by MattBBaker**

### CODE REVIEW

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3968/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3976/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - what is the story with Mellanox failure ?

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3986/ for details (Mellanox internal link).

**Pull request merged**
