### PR TITLE
DOXYGEN/BUILD

### PR DESCRIPTION
**Pull request by MattBBaker**
Fix up the Makefile so that the .dot to .pdf is a generic rule and remove the file specific rule that used to be in the Makefile for the dot file.

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1024/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/450/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@miked-mellanox - can you please check what failed ?

**Comment by yosefe** [comment]
```
00:27:00 + rm -rf /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp1-x86-64/build-test/ucx-1.0.988
00:27:00 + test x/scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp1-x86-64/build-test/_rpm '!=' x
00:27:00 + rm -rf /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp1-x86-64/build-test/_rpm
00:27:00 + rm -rf filelists
00:27:00 + echo 'Build docs'
00:27:00 Build docs
00:27:00 + make -j1 docs
00:27:00 dot -T pdf -o doc/uml/uct.pdf /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp1-x86-64/contrib/../doc/uml/uct.dot
00:27:00 doc/uml/uct.pdf: No such file or directory
```

**Comment by shamisp** [comment]
@MattBBaker - please check the rule. I think you got it wrong.

**Comment by yosefe** [comment]
@MattBBaker please not the build directory is not the source directory

**Comment by MattBBaker** [comment]
The rule itself was not the problem. The special targets do the dirs correctly. However, the makefile was not correctly generating the subdirs for doc/uml. I have incorporated the same solution used by doxygen to fix the same problem.

**Comment by shamisp** [comment]
@MattBBaker you can blame me :smile:

**Comment by MattBBaker** [comment]
I blame autotools for not having an elegant way to say, "This subdir needs to exist, though it might not, so make it anyways."

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1032/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/459/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe can you please check the lab ?

**Comment by yosefe** [comment]
unrelated problem in jenkins

**Pull request merged**
