### PR TITLE
TEST/TIME: Allow up to 1% time calculation discrepancy for nanoseconds

### LINKED ISSUE #3141: gtest test_time.time_calc fails on Bluefiled smart nic
```
[ RUN      ] test_time.time_calc
ucs/test_time.cc:23: Failure
The difference between value * 1000 and ucs_time_to_nsec(ucs_time_from_usec(value)) is 1.6000000238418579, which exceeds 1.0, where
value * 1000 evaluates to 384577000,
ucs_time_to_nsec(ucs_time_from_usec(value)) evaluates to 384576998.39999998, and
1.0 evaluates to 1.
[  FAILED  ] test_time.time_calc, where TypeParam =  and GetParam() =  (1 ms)
[----------] 1 test from test_time (1 ms total)
```

```
./configure --enable-gtest
```

@yosefe - busted test ?

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #3141

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp

**Comment by shamisp** [comment]
so, the time of the day is a bit off ?

**Comment by yosefe** [comment]
it's floating point accuracy issue

**Comment by shamisp** [comment]
Ah. Any idea why we step on this only now ?

**Comment by yosefe** [comment]
i guess because of timer freq on BW nodes or accuracy of "double" calculations on BW.

**Comment by shamisp** [comment]
Accuracy is IEEE compliant. I guess it has something to do with the freq of
the node itself. Probably the slow timer take extra time.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8706/ for details (Mellanox internal link).

**Pull request merged**
