### PR TITLE
GTEST: Fix test_tag tests  - v.1.4.x

### LINKED ISSUE #2855: dc/test_tag.tag_rndv_zcopy_tag_mask/0 failed on hpc-arm-hwi-jenkins
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7645/label=hpc-arm-hwi-jenkins,worker=0/consoleFull
no valgrind
```
18:43:02 [       OK ] dc/test_tag.tag_eager_bcopy_unexpected/0 (460 ms)
18:43:02 [ RUN      ] dc/test_tag.tag_rndv_zcopy_tag_mask/0
18:43:03 [1536853383.103086] [hpc-arm-hwi-jenkins:30243:0]      ptr_array.c:110  UCX  WARN  releasing ptr_array with 1 used items
18:43:03 /scrap/jenkins/workspace/hpc-ucx-pr-3/label/hpc-arm-hwi-jenkins/worker/0/contrib/../test/gtest/common/test.cc:264: Failure
18:43:03 Failed
18:43:03 Got 1 warnings during the test
18:43:03 
[  FAILED  ] dc/test_tag.tag_rndv_zcopy_tag_mask/0, where GetParam() = dc/mlx5_0:1 (559 ms)
18:43:03 [ RUN      ] dc/test_tag.tag_cancel_noforce/0
```

### PR DESCRIPTION
**Pull request by brminich**
## What
Bug fix

## Why ?
Fixes #2855 

## How ?
Need to wait send completion when message is sent with RNDV protocol

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7652/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7653/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@brminich is this cherry pick from master?

**Comment by brminich** [comment]
@yosefe, yes

**Pull request merged**
