### PR TITLE
UCT/UGNI/SMSG Drain entire smsg queue

### PR DESCRIPTION
**Pull request by MattBBaker**
Last bit of SMSG for now. Each invocation of progress will totally drain the completion queues before moving on.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1098/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1701/ for details.

**Comment by shamisp** [comment]
:+1:  @hppritcha please take a look

**Comment by hppritcha** [comment]
looks good :+1:

**Pull request merged**
