### PR TITLE
GTEST: extended allowed tag sync mr range

### PR DESCRIPTION
**Pull request by hoopoepg**
- extended range to make tests happy

### CODE REVIEW

**Comment by hoopoepg** [comment]
failed log: http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7898/label=hpc-test-node3,worker=2/consoleFull

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7900/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
failed due to infra issues

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7905/ for details (Mellanox internal link).

**Pull request merged**
