### PR TITLE
UGNI: Fix flush function definition.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1314/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1941/ for details.

**Comment by yosefe** [comment]
@MattBBaker

**Comment by MattBBaker** [comment]
Yep, the last merge broke it and this fixed it. :+1:

**Pull request merged**
