### PR TITLE
UCT/RC: Add statitiscs and enable/disable config for RC flow control.

### LINKED ISSUE #821: Add statistics to RC/DC flow control

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #821

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1374/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1999/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1375/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
