### PR TITLE
DOC: Adding annual release schedule diagram

### PR DESCRIPTION
**Pull request by shamisp**
This diagram will be references in README, wiki, etc.

### CODE REVIEW

**Comment by tonycurtis** [comment]
+1

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8976/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
seems weird to add this to doxygen. It's not going to be part of UCX specification, right?
Why not just add it to the Wiki?

**Comment by shamisp** [comment]
I want to reference it in readme, which means it is better to have it in repo. We can create new directory under doc for diagrams,

**Comment by yosefe** [comment]
i don't think README is a right place for this. README should describe the up-to-date content on the project, not future plans and such metadata.

**Comment by miked-mellanox** [comment]
i think best to reference from README the documentation wiki page.
This wiki page should have a reference to diagrams and all related docs and howtos.

**Comment by shamisp** [comment]
How do I attach image to wiki ? It has to be somewhere in repo.

**Comment by yosefe** [comment]
@shamisp you can push it to the wiki repo (ucx.wiki)

**Comment by shamisp** [comment]
I will take a look

**Comment by shamisp** [comment]
I moved the diagram to WIKI git: https://github.com/openucx/ucx/wiki

**Pull request closed without merging**
