### PR TITLE
UCP/EP: Refactor endpoint creation

### PR DESCRIPTION
**Pull request by yosefe**
preparation for dest_ep_ptr-based protocols (instead of dest_uuid)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6743/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6746/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask @evgeny-leksikov pls take a look

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by alinask** [comment]
@yosefe since this is a change in the basis of connection establishment, could you please verify that it's tested at scale?

**Comment by yosefe** [comment]
@alinask this PR does not change connection establishment, just moves the address unpack to other places. the connection scheme change is in next PR

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6755/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe yes but the ep creation and addr_unpacking are basic in the connection establishment flow. IMHO it would be good to make sure that the refactoring didnt change anything.

**Comment by yosefe** [comment]
@alinask tested with mpi_test_suite on 16 nodes, 28 ppn (jazz)

**Comment by alinask** [comment]
:+1:

**Pull request merged**
