### PR TITLE
Adding UH and SBU to license.

### PR DESCRIPTION
**Pull request by tonycurtis**
... as former UH employee and current SBU.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1823/ for details.

**Comment by shamisp** [comment]
Tony, can you please squash the two patches into one. For a single line change we would prefer to avoid having multiple commits. Thanks

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1824/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3762/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1826/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3763/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3765/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by shamisp** [comment]
@tonycurtis can you please squash before we approve ? If you have trouble with this, just open new PR

**Comment by shamisp** [comment]
replaced by #1597

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1834/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1832/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3774/ for details (Mellanox internal link).

**Pull request closed without merging**
