### PR TITLE
LEGAL: fixed file header for ucp_am.c

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11424/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/e3e22615f1c9228b6e7176727e9ad3ba32f5dabe/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/d7d29bb21dfae49eeadcb5bee1777b0e6525179a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/c8cf807d0f1492bed39c55589bc0d76547c20212/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/e67718e7f19c100af664cfe8e176fb487f2b2371/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/2e99c3cf0dfcf6206939569ced51acdb42e065fc/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/2d895e30442589039f0e631e026b215335a1c391/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/d7390ef95f9d46545f984f52c6db3b3d41f57508/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/2bad1113963f2724fbe4230fb234ce8c242662f7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/66a7490da12e2c8e584f49ae6d3eca7650a0db68/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/7748ba2e6314f0eecba76bddc6db2119b7ef0dcb/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/6992aa27073831d74b21d683cfbb053815130e2a/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/392d8ecef4a28875726e20528e8b93e42411cbf6/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/73f2815bb06446c30c66ca2052c8cb1f0f0a2016/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/b4ada1ca9a38e4db1bbbec5a206f282afd4e2914/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/7ab2305ae902a4a9bf2544759ff62de1a1e4c647/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/67c32a1a1545373c24088e0e018c904f08aa6d03/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/b839d3e07d5d0c32e0d817b96a2b84added43743/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/8793e43c68c5d3935c0d30549b54fef293b19a0a/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/fb4a6ea3d0ad152aa3aba399fbf690f0ed03157a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/9ce9904c01d8f5c8d3becac6eca838f988e12ff3/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/31618f90f7794543b563824f2fb9f4992ee53178/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/d97326e8630afc06cc65e4e989ee3733cb0eea47/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/48215aeec59618ced7dd029e847ffcd003f172bb/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/b4d1da25d721c1e03a8eb719e49032de149a00b7/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/9e5fff0ecd3e2ee7359f5b15f4769c7bbda1d2ed/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/e245d91e1727b380a2f3773c04e0f37c0eaf089d/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/aab22b5df76e6fc7c32829187f339c9d3fcf9145/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/a8651e4394b1dba8aa1456b3a3e33625742fcb91/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/eef65ea50193ba568f3d57a7f8ae92b455ae4a9a/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/1f761f1ab7d1b7b1f330b6faf7383668b12b46cc/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/5d86a0894339d12eebbae75b2f56739e04ff3bc5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/2ec1a2c4683df2d8715a784a3b7f372f910a8ecc/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/32b63ebb13cd802dd0167a6991502e30/raw/fa32e3ecabc5a9765eddf97150897ab2516990bc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Comment by shamisp** [comment]
👍

**Pull request merged**
