### PR TITLE
UCT/RCX/IFACE: fixed typo in macro

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by hoopoepg** [comment]
@yosefe approve please

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6626/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6628/ for details (Mellanox internal link).

**Pull request merged**
