### PR TITLE
TCP enhancements

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5301/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5304/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev @brminich pls take a look

**Comment by shamisp** [comment]
👍

**Pull request merged**
