### PR TITLE
Integrate Tcmalloc

### PR DESCRIPTION
**Pull request by MattBBaker**
Initial round of integrating tcmalloc for use in ucx.

This version will not build tcmalloc by default, but has to be explicitly enabled with --enable-tcmalloc. How to properly integrate with the testing suite is an open question.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/975/ for details.

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/399/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/977/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/400/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@miked-mellanox @yosefe - please comment

**Comment by shamisp** [comment]
autobot build

**Comment by miked-mellanox** [comment]
could you please rebase PR to eliminate "merge" commit?

**Comment by miked-mellanox** [comment]
is it only integration PR, no use-case on top of it?
is there plan to have ucx_malloc on top of it?
Could you please add gtest for it?

**Comment by shamisp** [comment]
@miked-mellanox , the top case will be registration cache. We will add it later on with gtest infrastructure.
We don't plan to have ucx_malloc.

**Comment by shamisp** [comment]
I agree with the comment about rebase. It will look a bit cleaner.

**Comment by miked-mellanox** [comment]
btw, will tcmalloc support access to __end symbol for heap allocation w/ it?

**Comment by miked-mellanox** [comment]
i mean we may want to use ucx alloc framework for memheam in SHMEM

**Comment by shamisp** [comment]
@miked-mellanox for symmetric allocations you can use ucp_mmap in shmem with a similar effect.

**Comment by shamisp** [comment]
@MattBBaker - is there a way to check if the library was loaded ? From UCX we need a way to identify that tcmalloc was pre-loaded

**Comment by MattBBaker** [comment]
The only way I can think of to check if the library was loaded would be to parse LD_PRELOAD. Not the end of the world but I will investigate if there is anything that is more elegant in code.

The reason for modifying the gperftools package is mostly for the build infrastructure. The default build of gperftools includes the profiling tools and those tools have external dependencies that aren't on the clusters. However, with the AC_CONFIG_SUBDIRS macro at the top level you can't alter the flags, so either the default configure script has to be altered or you have to rewrite the AC_CONFIG_SUBDIRS to pass different configure parameters. However, in make distcheck it will look for windows headers and solaris libraries and then fail, so the jenkins tests will report failure. So there is no way around some amount of editing gperftools conifgure scripts. I can take the rewrite AC_CONFIG_SUBDIRS route to eliminate some of that, but the distcheck looking for non-existent files I'm not sure about.

And fair enough on the merge commit. I'll rebase.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/981/ for details.

**Comment by miked-mellanox** [comment]
@shamisp - why need to check if it is already loaded?

you can open /proc/self/maps and find it

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/982/ for details.

**Comment by shamisp** [comment]
@miked-mellanox - based on this we will disable/enable registration cache. As well, if we enable mmap  by default it will allow us to enable some other optimizations. As for the detection mechanism, I was thinking to use a simple getenv/setenv

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/405/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/403/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/404/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/406/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/983/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/984/ for details.

**Comment by yosefe** [comment]
I think this is too much useless files. We should either put only the bare minimum files (2-5 files - like they did in ompi), put the package in another directory ("ucx/external", possibly as a tarball), or consider using another malloc library which is easier to strip.
As for other stuff -  
* instead of LD_PRELOAD, we can check during startup nothing is allocated yet (mallinfo) - because our real concern is that nothing was allocated with glibc before we install the hooks.
* I think we should enable the build by default, since it does not hurt performance, and we surely want to use it if possible, and also detect regressions in tests.

**Comment by shamisp** [comment]
I think we can clean it up a bit. Remove all the doc/deb/rpm etc and see what it leave to us.

**Comment by MattBBaker** [comment]
Alright, I'll make one that is stripped and put into ucx/external.

What should be done if the user malloced something before ucx has a chance to catch the hooks?

My concern with enabling by default was that I wasn't sure how to test it in the automated system, because I don't know how to make jenkins set LD_PRELOAD for the tests. I'll make it enabled by default anyways.

**Comment by MattBBaker** [comment]
Update now strips out a lot more files, moves the build into ucx/external/gperftools as a source dir, and is enabled by default.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/988/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/409/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@miked-mellanox - seems like the failure is unrelated to this change 
@yosefe - I think it is much more compact now.

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
@shamisp - it failed on coverity

``` shell
01:02:43 Analysis summary report:
01:02:43 ------------------------
01:02:43 Files analyzed                 : 355
01:02:43 Total LoC input to cov-analyze : 161242
01:02:43 Functions analyzed             : 9454
01:02:43 Classes/structs analyzed       : 1932
01:02:43 Paths analyzed                 : 124843
01:02:43 Time taken by analysis         : 00:00:23
01:02:43 Defect occurrences found       : 25 Total
01:02:43                                   1 ASSERT_SIDE_EFFECT
01:02:43                                   2 CHECKED_RETURN
01:02:43                                   1 DEADCODE
01:02:43                                   3 FORWARD_NULL
01:02:43                                   3 INFINITE_LOOP
01:02:43                                   3 RESOURCE_LEAK
01:02:43                                   1 SIZEOF_MISMATCH
01:02:43                                   1 STREAM_FORMAT_STATE
01:02:43                                   2 UNINIT
01:02:43                                   4 UNINIT_CTOR
01:02:43                                   1 UNREACHABLE
01:02:43                                   3 USE_AFTER_FREE
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/411/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@miked-mellanox - do you know if all these are related to tcmalloc ? I don't think that we will want to do a cleanup for external packages.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/990/ for details.

**Comment by MattBBaker** [comment]
All the coverity failures were tcmalloc related.

**Comment by shamisp** [comment]
@miked-mellanox - IMHO we should not fix these ...

**Comment by tonycurtis** [comment]
> On Oct 14, 2015, at 10:42 AM, shamisp <notifications@github.com> wrote:
> 
> @miked-mellanox <https://github.com/miked-mellanox> - IMHO we should not fix these …
> 

You can add tcmalloc as an ignored component in the Coverity analysis settings.

the other tc

**Comment by MattBBaker** [comment]
Probably add the whole external directory. If more packages are added there I can't envision wanting to scan any of those either.

**Comment by yosefe** [comment]
can't we just add few files? Don't think we need to add so much unused files to the project just for malloc().

**Comment by shamisp** [comment]
We decide to put the PR on hold until next conf-call.

**Comment by shamisp** [comment]
We decided to use jemalloc over tcmalloc

**Pull request closed without merging**
