### PR TITLE
GITHUB: Move CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md to .github

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 25-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/f5cb4b7ca23d7fd21abbaae39a2d0d8f54004441/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/f66a2fbb0a6b22cfa75638b7e2db941bfc6a8e61/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/0a86aa5a36c417cb984b5cd9841bb3df90f829e7/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/a2c510b3526354db1ab4b777b44ebfb9b99e2789/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/4a7448017e79a61b7edea78f54b0c673f2555f96/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/f6e090622ff1b331d1ff4bb84920d445245c79a7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/a7faa109167e4c8741b406092eddc3e520236f73/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/496a6610d3d80c6705121e35960daa9210fbe47f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/e914437cf31ce7e09a585360c62db16db16e520b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/9374856f1a2c854a2c995c4a0dd800579751a210/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/9d1cfc488d86f9777dacfb5b10fdb9b8b9b034d4/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/0f7559612ca8f5a6ca65d7b59a2e86722a747fa2/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/65d85c780926ecb6bf341e67c7418b8508ed22dc/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/360a5a22bef642608fc19d3290b3877effbd00d8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/552c5f04873bc3d407ba7d8b89e4a85fdf664bf3/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/66cd50d9dbac03454bb196440188cc818234adaf/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/37553c0e0aab87dca2cc0956a83e20eb22e0d3f6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/54600cf312468f718b4650bc50672b25f792f407/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/f378fa8c34a8a3ed7b98914c74ca85bc8644c024/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/89bf95b7ded93f22473d035702f2d88acd31d62b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/f5addc354dcada2d1aa1e409566067eebedeca89/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/72547403056c53f17d473c30b4e7c5b799b67b13/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/eb91572b1a809da49dff0969792ac33570c048ce/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/63f801c6d58658278b24dcd8eb256187568efedb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8f2f08a56f93aa7b6dbd292274de7fb4/raw/19c77736d6d3cbf23c32297cb146b20dfba4c35f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
issue is #4458 
bot:pipe:retest

**Comment by yosefe** [comment]
@alinask can you pls take a look?

**Comment by alinask** [comment]
why is this done?

**Comment by yosefe** [comment]
> why is this done?

To place all github related files in a separate directory like they did in OMPI

**Pull request merged**
