### PR TITLE
BUILD/NVC: set of fixes for new HPC SDK

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed compilation by HPC SDK version 20.9

### CODE REVIEW

**Review by brminich — APPROVED** [review]

**Comment by shamisp** [comment]
@hoopoepg is purely PGI compiler issue

**Comment by hoopoepg** [comment]
hi @shamisp 
as I can see there is improved checks for C standards

**Comment by shamisp** [comment]
@hoopoepg can we add NVC (I think it is renamed PGI?) to CI ? It is kinda pity that the issue was caught post 1.9.0.

**Comment by hoopoepg** [comment]
actually it is already there? but used older version (where nvc is called pgcc).
will update scripts/test systems

**Comment by hoopoepg** [comment]
@yosefe any comments?

**Review by yosefe — APPROVED** [review]

**Pull request merged**
