### PR TITLE
UCP/WIREUP: Fix pending requests purge

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7497/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
How it is detected only now ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7500/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
it's found by emulation layer code (which is not pushed yet)

**Comment by yosefe** [comment]
@evgeny-leksikov @brminich pls take a look

**Comment by evgeny-leksikov** [comment]
👍

**Pull request merged**
