### PR TITLE
jenkins: run ucx_perftest with mm as well.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1233/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1843/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
