### PR TITLE
DOC: Updating the diagram describing the architecture

### PR DESCRIPTION
**Pull request by shamisp**
Updating project diagram based on offline discussions

### CODE REVIEW

**Comment by shamisp** [comment]
For convenience attaching PNG of the diagram.

architecture

@yosefe @bbenton @tonycurtis please let me know what do you think

**Comment by bbenton** [comment]
This looks good to me.  Just one minor correction: for the task-based support, it should be Legion rather than Legions.

**Comment by tonycurtis** [comment]
> On Feb 18, 2019, at 2:37 PM, bbenton <notifications@github.com> wrote:
> 
> This looks good to me. Just one minor correction: for the task-based support, it should be Legion rather than Legions.
> 

The word “for” is missing in the intra-node memory section.  In task-based domain & UCT, should be “Active Messages” rather than “Active Message” (or I assume that is the intent).  Capitalization inconsistent in “tag-matching” vs. other domains.

Might also consider moving the ends of the top-most arrows slightly further away (higher) from the text otherwise it looks like they’re pointing at parts of the text itself

tony

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8838/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8839/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Thank you for comments. I will work to update the diagram.

**Comment by manjugv** [comment]
@shamisp It might be useful to capture TCP and ROCE support as well.

**Comment by shamisp** [comment]
architecture

**Comment by shamisp** [comment]
Updated. Please take a look.

**Comment by tonycurtis** [comment]
+1

**Comment by shamisp** [comment]
@yosefe ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8857/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
- do we want to add TensorFlow app as potential UCP user?
- remove XRC from IB
- lets separate CUDA and ROCm?
- somehow reduce the size of "intra-node" box since it appears more significant than what it really is

**Comment by shamisp** [comment]
Which part of API tensorflow is expect to use ?

**Comment by shamisp** [comment]
@yosefe I addressed some of the comments that I considered relevant. Resizing shared memory box is royal pain. The size of boxes does not represents complexity or anything like this.

architecture

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8896/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe are we good ?

**Comment by shamisp** [comment]
Okay, we can resolve any concerns later on.

**Pull request merged**
