### PR TITLE
BUILD: Disable CPU-specific optimizations by default.

### LINKED ISSUE #1548: No way to disable AVX
./configure provides no way to disable AVX. It would appear that if the compiler supports `-mavx`, openucx always activates -mavx, even if the machine itself cannot possibly run such code.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1548

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1802/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3742/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1805/ for details.

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1804/ for details.

**Comment by shamisp** [comment]
👍

**Pull request merged**
