### PR TITLE
Topic/async

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
Fixing #1477

**Comment by shamisp** [comment]
@yosefe please take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1566/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3484/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:ornl:retest

**Pull request merged**
