### PR TITLE
UCT/TCP/GTEST: Protect against connection from non-UCX sock-based app

### LINKED ISSUE #4525: 1.7.0-rc1 showing tcp_ep.c:739  Assertion hdr->length <= (iface->config.rx_seg_size - sizeof(uct_tcp_am_hdr_t))
### Describe the bug
Got a sporadic
tcp_ep.c:739  Assertion `hdr->length <= (iface->config.rx_seg_size - sizeof(uct_tcp_am_hdr_t))' failed
when chasing issue #4406 

Could this be caused by outside connection attempts by port sniffers?

```
[b-cn0131:542585:0:542585]      tcp_ep.c:739  Assertion `hdr->length <= (iface->config.
rx_seg_size - sizeof(uct_tcp_am_hdr_t))' failed
==== backtrace (tid: 542585) ====
 0 0x000000000001f130 ucs_fatal_error_message()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-
7.3.0/ucx-1.7.0-rc1/src/ucs/debug/assert.c:33
 1 0x000000000001f2ce ucs_fatal_error_format()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/debug/assert.c:49
 2 0x0000000000019388 uct_tcp_ep_progress_rx()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/tcp/tcp_ep.c:738
 3 0x000000000001b2d9 uct_tcp_iface_handle_events()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/tcp/tcp_iface.c:180
 4 0x0000000000027575 ucs_event_set_wait()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/sys/event_set.c:213
 5 0x000000000001b39f uct_tcp_iface_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/tcp/tcp_iface.c:197
 6 0x0000000000022392 uct_iface_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/api/uct.h:2984
 7 0x0000000000022664 ucp_worker_iface_check_events_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucp/core/ucp_worker.c:746
 8 0x000000000001a16a ucs_callbackq_slow_proxy()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/datastruct/callbackq.c:397
 9 0x0000000000024d0a ucs_callbackq_dispatch()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/datastruct/callbackq.h:211
10 0x0000000000024d0a uct_worker_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/api/uct.h:2203
11 0x0000000000024d0a ucp_worker_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucp/core/ucp_worker.c:1897
12 0x0000000000003aa7 mca_pml_ucx_progress()  ???:0
13 0x000000000002c61c opal_progress()  ???:0
14 0x0000000000003c7d mca_pml_ucx_recv()  ???:0
15 0x00000000000a398d ompi_coll_base_allreduce_intra_recursivedoubling()  ???:0
16 0x000000000006275f MPI_Allreduce()  ???:0
17 0x0000000001cf5706 lj_vm_ffi_call()  crtstuff.c:0
18 0x0000000001d15baa lj_ccall_func()  crtstuff.c:0
19 0x0000000001cf1663 lj_cf_ffi_meta___call()  lib_ffi.c:0
20 0x0000000001cf3767 lj_BC_FUNCC()  crtstuff.c:0
21 0x0000000001ce26ac lua_pcall()  ???:0
22 0x000000000045477f main()  ???:0
23 0x0000000000020830 __libc_start_main()  /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291
24 0x0000000000454d09 _start()  ???:0
=================================
```

### Steps to Reproduce
- Command line
- UCX version used 1.7.0-rc1
- **Any UCX environment variables used**

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
  Ubuntu 16.04.6, HWE kernel 4.15.0-70-generic

### Additional information (depending on the issue)
- OpenMPI 3.1.1
- MOFED 4.4

### PR DESCRIPTION
**Pull request by dmitrygx**
backport of #4612 to v1.7.x

Fixes #4525

### CODE REVIEW

**Comment by dmitrygx** [comment]
@brminich @shamisp @akesandgren this is for v1.7.x branch

**Comment by shamisp** [comment]
@akesandgren - can you please test this with 1.7.x branch and confirm that it works for you.

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/be3febe4a2e930fa07f6c89b79a6ace1e6707e66/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/d6c76c6c981fd67c49cb7ae168bc52b4c04bca5b/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/39d5f56684504e90787acc0141332a7946c38bd4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/0a3cb02a22b928ccfabbde04259a0b46041cb4ae/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/587512d969f79e4d578ce2391fbd57e86cda0154/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/6dbc5dafd7bfac8b80ecedbd5e7e33992df9db46/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/67e3ff244a7d5f989eabd329fd098a12eeaec916/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/967d993e1c4675e87555da75fb1047db2262ed0f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/ae0ac7e9723599a5743fdbe6e418784a3bb9f932/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/0f622356c7c1fa5faa393fd2cc4ac3ceadfe2a15/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/ae457fabf29d7c2352056b7e081ec2e322ea00cc/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/3d76b74e69dd17fac4df82fefe55195380c232f8/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/7d0de1ce08ec48a30ea82daeb9d6f8d1f616e05f/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/605c830b8bbc412e18367b11ffb3af4eaf63b041/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/91bf156b3fbab602ff516e0f76026a1dc1e48027/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/6175aab3971d5df5e7add802d8391c2461fbb0c4/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/b4ad51481f57e109437fd8a98bc308c12a121209/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/5c7179fb699eb992ff4ac88362711d552576e0f4/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/8d9c444917491598760046b293adff2a4645bff0/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/97150054a5358a22949a2eb5fbfb491ea19e2074/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/ab9ae3a4d1d7a027a46b60b6f7a267a43d38a2fd/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/8488ee34b883e942da709902c36c41df87cdf2bc/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/996d966321a93d86f44916265c0a6681298845b7/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/1a1c3841e30d9043e731799a626f2e5b31c27d97/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7cbf4be72c34c0702a88fe471244692f/raw/3fe33fb93c395c6ed9800e8b0638962fc3eb8775/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:mlx:retest
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/74aac62e88e4296419cc9904dca9bfbf43c9ea2a/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/88d9ffac559bcba6133b80be5b259ffc738809aa/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/a8f759868c0bfc6d22f7d64b500dcb1ae9ae8918/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/b8e3318993452cf894cdb5261fb863f85c6f4e35/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/5d863f6e0f5cf00beea2a67b65f2600688efe251/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/c1074ffbef3ce98ad323160ebb7708449d36c3be/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/3ead32ae58ab9ecdf6bce689fb4967a291b350e1/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/d1bd60804fa518f1b43c383be9055f8e5d2eb245/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/d2e573d34135b2777ff62f8fc8eb73395c676994/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/a020f7c3edf53e77e64b8aeb235319447165e59d/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/4b4f23edab89f8685654508dacca3ffd1d750c38/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/2394f0b712cc72ae30f960467a2186c6da798a43/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/e6b8971efd7fe11a3c653121b63e1e3e32040d7c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/30b4b6ee34ff2f19f4283424544fbad386e7cba5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/30a0f6a23bff5052ff8b56fceba68605d38b4230/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/29265bb011d2a0c0c320b99698a5c3c87166344f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/b575b425bee6fef04c5c4d25fc26f165e8392a00/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/9cbd40bde4691c90f121ced80721ab546513e847/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/baf2d49ebbafd766694105bedfc3cedbfc28762d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/f8865e5073c2db688c37f9b4c9c00666aeaf2dc8/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/0ecec4843a11c8537768c3d219361b6b153f85b2/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/0ef726ef1fe28be7b2b41a1cb6147d08d3b9e1a3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/d7d252da7d4fc93592ce33e1622c7340843287ef/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/c01748743b3ce7cc96788bb2879ed49281ba49fe/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ccaedd02d4f48c795c7a24159cf2007f/raw/87da8694f473219419ac45a6cb25b7b36d6efdb9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> Mellanox CI: ABORTED on 25 workers (click for details)

waiting for #4661 gets merged to fix gpu node issue

**Comment by akesandgren** [comment]
@shamisp Test run started, however, it takes a long time to make certain that it works, at least 3-4 days.

**Comment by shamisp** [comment]
Okay. We may end up merging now. Since it worked on master I'm under
assumption we will have no surprises. If we will have surprises, next fix
will go to 1.7.1 or 1.8.0.

**Comment by dmitrygx** [comment]
bot:pipe:retest
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/4a329e4e34d3f61017482a7fdd22f6d388b2439c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/af9b0a9a959b6e88ac77b6add8637999b7ca6190/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/7493ddae88c6a6dfb7b2063fde25978d9b0dd362/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/7c708e8813021912c47d93c73b4dc5df0e60c135/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/aa486d2371440b88a78c5a67146974ca5c40886b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/e2c0851cc258d962a1734ab5c45b757bb6a8f557/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/bd8623f48e3cf82cfc7d81c625f737363f5a8e2c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/6e45d31a04b7264c2a2f82711403189c9debea37/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/eb92d71cdb10b64a9b021b5f5cf3f4f64c737800/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/e365bb5974b8b67d37ae5f3d7c8f330de07053e9/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/3b64a79bc02d22cd2e18bda6366b95863771799c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/0d4a0bec88d4f128946c4d7d9efe0d8f07cf58b9/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/2b6c06355ea59546e95d4501cfea959522d64867/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/fdf4e87ee95fddee0bdebfe18610a4dcc55df842/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/8edf13af17f74f3f5b6a8a04614b8053881616b7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/c0899e3e0b200a0f8bb60367f44d73a1107aa153/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/a804d963202d354e5a5ff6dbaa10b595440bf8d4/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/f53d4bb0454fc5cbf11e3865c058f1e1b1d380b4/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/470185359d994441ba8382c28475a87f6eb19f86/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/bac23506db21872ea814cc5702ab2fe4fb53bc82/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/fb4f7a3fe7866f33c04f7e2e61df9d4fd64259f7/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/1f51c22cc452ebc8927fd708e1a4489683560845/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/0c727978ae229cba74211a88b8ac0ce9d6c26368/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/a2186ada02831d22a18c79ee6c68d3c62e6ba795/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4ae32b40773b389637060c839a9d5ff0/raw/45028ce3e573a848298762cc3f96e495ec3845ff/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@shamisp could you review pls?

**Comment by akesandgren** [comment]
My test run for this seem to have gotten hung without any errors. Is suspect that to be cause by this change. But i'll redo it again...

**Comment by dmitrygx** [comment]
@akesandgren do you this hung with patch on top of the master or v1.7.x?

**Comment by akesandgren** [comment]
Actually neither, I was using your branch for the PR, i.e. https://github.com/dmitrygx/ucx commit d286f8d6804b98c97b5a16a81ea28813e0826d91

Second (current) test is however openucx  v1.7.x commit ee2252bf0d3b5736d4b459a42291351cf53b1df0

**Comment by dmitrygx** [comment]
> Actually neither, I was using your branch for the PR, i.e. https://github.com/dmitrygx/ucx commit [d286f8d](https://github.com/openucx/ucx/commit/d286f8d6804b98c97b5a16a81ea28813e0826d91)
> 
> Second (current) test is however openucx v1.7.x commit [ee2252b](https://github.com/openucx/ucx/commit/ee2252bf0d3b5736d4b459a42291351cf53b1df0)

@akesandgren was it ok with the first patch before refactoring? have you ever seen that your application was passed w/o any error and hangs?

**Comment by akesandgren** [comment]
I have one test run which ran to completion using dmitrygx commit 23f0ece7d8
Then a couple which ran out of time, but did not hang, using dmitrygx commit c3c5f1b79c

I only ran one test using dmitrygx commit d286f8d, and that one got hung.

openucx v1.7.x commit ee2252b test still running.

**Comment by dmitrygx** [comment]
> I only ran one test using dmitrygx commit [d286f8d](https://github.com/openucx/ucx/commit/d286f8d6804b98c97b5a16a81ea28813e0826d91), and that one got hung.

@akesandgren this is the new version of the fix on top of the v1.7.x. Is it possible to check whether it works w/o hang on the master branch (i.e. just take the master branch and run your test)? If it wokrs on the master, then it means that there is a lack of some fix on v1.7.x branch.

**Comment by akesandgren** [comment]
openucx v1.7.x commit ee2252b test hung after 12 days of running. If this is a UCX problem or not is not going to be easy to figure out... I say ignore it until we can find an easier way to trigger it.

**Comment by dmitrygx** [comment]
> openucx v1.7.x commit [ee2252b](https://github.com/openucx/ucx/commit/ee2252bf0d3b5736d4b459a42291351cf53b1df0) test hung after 12 days of running. If this is a UCX problem or not is not going to be easy to figure out... I say ignore it until we can find an easier way to trigger it.

@akesandgren thank you for letting us know.
but is it possible to try the UCX master branch? It contains the fix for the problem reported by you, but it can probably work fine, we need to check it. If it still doesn't work, could open an issue for the hang that you can see?

**Comment by akesandgren** [comment]
Yeah, I can try that too...

**Comment by akesandgren** [comment]
No hang seen with the master branch. Only ran it once though since it takes so long to be somewhat sure that it works.

**Comment by dmitrygx** [comment]
> No hang seen with the master branch.

@akesandgren thank you!
if it's so, it looks like we have some TCP bug on v1.7.x preventing us to help you.
BTW, the fix for sporadic assert was included into v1.8.x - so, next release (v1.8.0) can be used by you

>  Only ran it once though since it takes so long to be somewhat sure that it works.

are you going to make more runs? it would be helpful to make sure that it really helps you.

**Comment by akesandgren** [comment]
I could, but each run takes around 12-14 days to be somewhat sure...

**Comment by akesandgren** [comment]
Test with master ran to completion. So 1.7.0 does potentially have a problem...

I'll run a test with that version again.

**Comment by dmitrygx** [comment]
> Test with master ran to completion. So 1.7.0 does potentially have a problem...
> 
> I'll run a test with that version again.

@akesandgren thank you! v1.8.0 is coming soon, it has almost the same content for TCP as the master branch. Maybe it's worth waiting for v1.8.0 and use it for your app instead of v1.7.0?

**Comment by akesandgren** [comment]
That's my intention yes. I was just going to verify if it was a fluke that caused it to hang last time with the 1.7.x branch or if it is repeatable.

**Comment by dmitrygx** [comment]
> That's my intention yes. I was just going to verify if it was a fluke that caused it to hang last time with the 1.7.x branch or if it is repeatable.

@akesandgren good idea, thank you! we appreciate your help!

**Comment by akesandgren** [comment]
reg 1.8.0 how soon is soon? approximately...

**Comment by shamisp** [comment]
we will have rc1 out by end of the week.

**Comment by akesandgren** [comment]
The test with 1.7.0 didn't hang the first 7 days at least. I forgot to up the timelimit of the job after it started so it got killed.

I think we can consider 1.7.0 fairly good at least. But should keep an eye out for anyone else reporting hangs...

On towards 1.8.0 then...

**Comment by dmitrygx** [comment]
> The test with 1.7.0 didn't hang the first 7 days at least. I forgot to up the timelimit of the job after it started so it got killed.
> 
> I think we can consider 1.7.0 fairly good at least. But should keep an eye out for anyone else reporting hangs...
> 
> On towards 1.8.0 then...

@akesandgren thank you for testing it!

**Pull request merged**
