### PR TITLE
UCT/IB/RC: Add parameter to control the level of reporting peer failure.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by brminich** [comment]
Should it be extended for regular RC as well (uct_rc_verbs_handle_failure)?

**Comment by yosefe** [comment]
@brminich added

**Comment by brminich** [comment]
Another thought which is also related to comments to PR #884 . Typically runtimes (MPI) are silent by default, so if silence is needed from UCX, then fatal log level should be used (we have other errors and warnings unrelated to peer failure). Peer failure is an important message (on fault tolerant systems as well), so error (or warning) message seems to be appropriate to me. Otherwise what error/warning levels are intended for? Why do we provide a separate interface for hiding peer failures from logs, while we have the general one (log levels). 
What if someone wants to get rid of some other warnings?  Also how should we decide what trace message is related to peer failure?  For instance we may print warnings when freeing resources when ep goes to failed state, so we have to use the configuration log level parameter as well. 
But in many cases we have the common code for regular destroy and peer failure handling.

**Comment by yosefe** [comment]
currently the goal is to allow fatal failure when peer failure happens so we could debug the problem if needed. Also it could allow silencing peer failures in case the application wants to. As a more generic solution, we probably would like to have some error callback to the runtime.
Also, we should be able to free resources without warnings when ep goes to failed state.

**Comment by brminich** [comment]
I see. So it is needed for UD/DC as well then?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1560/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2224/ for details.

**Comment by shamisp** [comment]
👍

**Comment by yosefe** [comment]
yes. will need to add it to them as well.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1562/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2227/ for details.

**Comment by brminich** [comment]
:+1:

**Pull request merged**
