### PR TITLE
TEST: Reduce maximal number of p2p test transfers.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2542/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1895/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
👍

**Pull request merged**
