### PR TITLE
UCP/RMA: Add safe memory copy for aarch64

### LINKED ISSUE #2923: shmem_verifier fail on arm
```
module load hpcx-gcc
oshrun -np 42 -mca btl self --bind-to core -mca oshmem_proc_group_cache_size 10000 \
-report-bindings -mca btl_openib_if_include mlx5_0:1 -x UCX_NET_DEVICES=mlx5_0:1 \
-mca sshmem ucx -mca coll '^hcoll' -mca spml ucx -mca pml ucx --map-by node \
-x SHMEM_SYMMETRIC_HEAP_SIZE=1164M \
/hpc/mtr_scrap/users/mtt/scratch/shmem/20181002_232037_61903_7871_hpc-arm-*/installs/4BYz/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=data:put_blocking
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2923

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7874/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7876/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7877/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe I'm not sure if I understand the problem. Let's chat about this

**Comment by yosefe** [comment]
closing this , the test is invalid

**Pull request closed without merging**
