### PR TITLE
UCT: Add progress callbacks using thread-safe method.

### LINKED ISSUE #1637: segv on cmrcx test
```
14:39:17 [ RUN      ] cmrcx/test_ucp_tag_xfer.send_generic_recv_generic_exp/1
14:39:17 [jenkins03:4970 :0] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
14:39:19 
14:39:19 /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/uct/ib/rc/accel/rc_mlx5_common.h: [ uct_rc_mlx5_iface_common_poll_rx() ]
14:39:19       ...
14:39:19       125     unsigned flags;
14:39:19       126 
14:39:19       127     ucs_assert(uct_ib_mlx5_srq_get_wqe(&mlx5_common_iface->rx.srq,
14:39:19 ==>   128                                        mlx5_common_iface->rx.srq.mask)->srq.next_wqe_index == 0);
14:39:19       129 
14:39:19       130     cqe = uct_ib_mlx5_poll_cq(&rc_iface->super, &mlx5_common_iface->rx.cq);
14:39:19       131     if (cqe == NULL) {
14:39:19 
14:39:20 ==== backtrace ====
14:39:20  0 0x000000000003c689 uct_rc_mlx5_iface_common_poll_rx()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/uct/ib/rc/accel/rc_mlx5_common.h:128
14:39:20  1 0x000000000003c689 uct_rc_mlx5_iface_progress()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/uct/ib/rc/accel/rc_mlx5_iface.c:75
14:39:20  2 0x000000000001d74a ucs_callbackq_dispatch()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/ucs/datastruct/callbackq.h:150
14:39:20  3 0x000000000001d74a uct_worker_progress()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/uct/base/uct_worker.c:37
14:39:20  4 0x000000000001c098 ucp_worker_progress()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/ucp/core/ucp_worker.c:850
14:39:20  5 0x000000000001c098 ucs_async_check_miss()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/ucs/async/async.h:75
14:39:20  6 0x000000000001c098 ucp_worker_progress()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../src/ucp/core/ucp_worker.c:851
14:39:20  7 0x00000000005f078f ucp_test::progress()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/ucp/ucp_test.cc:101
14:39:20  8 0x00000000005c438a test_ucp_tag::wait()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/ucp/test_ucp_tag.cc:122
14:39:20  9 0x00000000005b0484 test_ucp_tag_xfer::do_xfer()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:432
14:39:20 10 0x00000000005b0a4e test_ucp_tag_xfer::test_run_xfer()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:203
14:39:20 11 0x0000000000469fde ucs::test_base::run()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/test.cc:204
14:39:20 12 0x000000000046a24d ucs::test_base::TestBodyProxy()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/test.cc:230
14:39:20 13 0x0000000000462c63 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3562
14:39:20 14 0x00000000004556ed testing::Test::Run()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3635
14:39:20 15 0x0000000000455784 testing::TestInfo::Run()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3812
14:39:20 16 0x0000000000455885 testing::TestCase::Run()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3930
14:39:20 17 0x0000000000455885 testing::TestCase::total_test_count()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3864
14:39:20 18 0x0000000000455885 testing::TestCase::Run()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3929
14:39:20 19 0x0000000000455afd testing::internal::UnitTestImpl::RunAllTests()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:5802
14:39:20 20 0x0000000000455dde HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest-all.cc:3562
14:39:20 21 0x000000000040d572 RUN_ALL_TESTS()  /var/lib/jenkins/jobs/gh-ucx-pr/workspace-3/label/master/worker/0/contrib/../test/gtest/common/gtest.h:20059
14:39:20 22 0x0000000000021b15 __libc_start_main()  ???:0
14:39:20 23 0x0000000000442cfd _start()  ???:0
14:39:20 ===================
```

http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1960/label=master,worker=0/consoleFull

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1637 and should also fix ORNL failure

### CODE REVIEW

**Comment by yosefe** [comment]
@brminich pls take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3955/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@MattBBaker how is ornl jenkins doing?

**Comment by MattBBaker** [comment]
@yosefe Running fine so far.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3956/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
There is implicit assumption there that the callback is thread safe. Did you document it anywhere ?

**Comment by yosefe** [comment]
@shamisp it's documented in ucs_callbackq API

**Pull request merged**
