### PR TITLE
Fixes in gtest for GPU memory with peer-direct

### PR DESCRIPTION
**Pull request by yosefe**
Test started to failed after loading nv_peer_mem kernel module on GPU test nodes

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/9c9c4c70433766d3acde04aedc10b055580d6af9/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/fac8f680afc04fd7a5626d48875d8b8beacb248b/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/07a8f4b31e16ea12b33b00baaa3d61de8f89d6b8/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/fd5efdc5b25e1ec4a961815681a3465d86e58df1/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/a68d554af94c1a95ec2aded05a7e28b1921e374d/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/2424d4dee274ed612e8b936d190a4646e34ede18/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/5f21933e7bea804208ec82eb1cb6e69afc2d897b/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/4ed63d45fd08c04137ec6b77ff692c7aa6e867cc/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/4e7d7dcb19697e92799f361e50c7f4545e420eb0/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/658daf629d8d0d9d41dbe11f8242d9e3c5f1a0bc/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/c0dabd1768dec98700af207c1a4884b0914c56c5/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/8d95f9c495b323d07f30ff2630828619d328357b/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/e12119da1dab0af0d94467b9e9aaaf52a2a5b3c3/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/ba3459414b364a0ac3038adc48fe64931f02d6ee/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/2e4c05e0f5b8da9b7762ef9f44e2e55da454b6a8/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/40befac9d7f95b02a3104bbb199f10d15f16f94c/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/9052a4dbadae1b9083ac3cc6545fd5138f2d211f/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/5e976a3ce7a41bbe056c09ac31e986b9f3b30ed9/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/58b110d4309598914fd5254f0edf170386dc4323/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/6ad162017c8bee0308ec824d5b5456378d33b4aa/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/56e858b04f09b807ba76892b2934692aba54694b/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/3c1f011a1246ce9bda3742a2663334dca657600b/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/805476eb5a3176f30d5194210ba8738113c08e30/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/15a36cfb38cb544e5039c4d4ae8ad1db9f01e2aa/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bfbb6b670dcff0964d261456ad8d82e5/raw/a6d22a5288959769ef2b9d4762e26b05572ea088/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/d72ae90f09cbd40371135e863ad9778de1b27981/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/9ef1854431450a3d06095be9f4a5c5441fc506dd/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/7a6c8768ebc78adc07f8023d7db66a4328799d1d/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/6b395608b93142a085f3abfcc01bccdbb86a85d3/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/59f399c3cca48e3895a8a98bff374bbb000a19c0/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/f7309dee864e50f0339a258a57bd9f0068bd37a9/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/0ff5e36162aeaef35c89f50127239071f06ac9d3/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/db820b13a90b58508e4efc35f300be2c1adda2aa/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/130b582ceafac1582684d29807ae7cacf09754e7/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/e36673648fbc84cd28500787e58d9e11871b97b6/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/9c96f4f3499524c0f341192452a1050242ea2b1f/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/e431d14d32e45deff450ecc34477058ac1e2b009/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/4e464e20d03ee115371cce0c7a10e2535fcc8302/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/f46a68d81d30d7c04a8c7405bfbadf63763b7415/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/f415eca359bbcb8920203bbd7a57ab3566c7733a/hpc-test-node-new_W3) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/5e90afd8a368fda58455bad489a7373ec7a9fdd5/hpc-test-node-new_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/c1a044f9cd4f2071d72ac064cdbdb915ae804b5e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/1c07be9efa056a8a58603376eb8fb720d65fd8a3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/23e4b79aeaf2ce285bfda218db94110469b22d9f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/58b83bb77796f44cc02a7267834fbd4489ced667/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/92a62d3fcb58f6f86ea2a63738260f39bd156f30/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/187373542cf7c5af9a18e7ae23b3fbb4c1e6ece5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/e98d833c2988c8e9b6e79a8b3723ee779d6ef2a1/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/8de884d99cde7942e8562e4d5390e05be92945ea/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e6524da51aa7d85d6841dae0c0c6ffb/raw/8ad48feb276d1341c7331077a53de6312a0b70ed/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/5c2df95e3462955bcc41666473528ccaf1ccd76f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/721011f755ce313b10830c572a0323195ab7f7c6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/ecef7c690d6e47775237c3bf5368b3d62f58c274/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/bb08f3d59a5205e35a492e0b759bcce36556ef90/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/c1d43b22f89feaa60df6443dd2037bc3bac3e7b9/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/29edb736ac81c06d122674065a059afab885b654/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/2cc3ff7a62573f4b563b5d5b463afdc8aa70993c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/a44b9140e5f3415a0be0f785c1eb560a3b81d599/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/a5d822871800b5f50030f40e0971b24a537780f8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/3df856188953a7b707ded26d57a9da1229f7d4e9/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/26457e4340b9a77a5cf8ae8a29367b2915681143/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/e3273989f885671e7948083bd423112235e4167c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/8ec44e3d09cdb93d5dee642bfd2c52a23e9f4238/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/e4b6f42633ae149d2207492f246426ad5d790c13/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/475b0d103f564cd2d46de9e709eb9ae83cc42668/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/a44d28324a4ee4a42bfce3540dcb188404d39846/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/46a59937575a0c0a26d4f08dd1ce80fc5b0b52b4/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/adf5b530c873b1edc5041aecb98004b612e0a871/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/3df7d748e34c03daa5235384527d0e85a20c7562/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/017fbdd3cfc00db2e59b111f4ab32d1aaefe3df6/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/9f02cf82a676bd3d2387f6bf3d49802db00b05ba/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/566b8c8db1623abd0b3c55cb7589f8b838a69171/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/1e2ec963625bd58c7c73f944d9870d6c660bcd79/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/b87a80dba4cf3dc380e2ed153222b3f05cc2c428/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8b25ac4cd2236c0700662138d01901a8/raw/0a0840adb4a6928f4817f95aaa8c330617428b50/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
"MellanoxLab New" would be fixed by #4413

**Pull request merged**
