### PR TITLE
DOCS/PUT-GET-NBX: fixed params specs

### LINKED ISSUE #5453: DOC/UCP: ucp_{pu,ge}t_nbx reference non-existent callback
### Describe the bug

The documentation for ucp_{pu,ge}t_nbx describes a callback parameter, but the routines don't have one.

### Steps to Reproduce

- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)

https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed params specs for ucp_put_nbx and ucp_get_nbx calls

Fixes #5453

(to be ported to v1.9.x)

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
@tonycurtis can you pls take a look?

**Comment by brminich** [comment]
issue is #4616 

bot:pipe:retest

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Pull request merged**
