### PR TITLE
BUILD/TEST: Test and fix compilation on ARM server.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/934/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2900/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
xpmem was restarted. Let's see if it fixes the issue

**Comment by shamisp** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2906/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
replaced by #1325

**Pull request closed without merging**
