### PR TITLE
JUCX: catch exception on ep close.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Catch ep timeout exception in JUCX tests. 

## Why ?
Fixes errors in CI: http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/8270/pipeline/1015/

https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=11330&view=logs&jobId=da813497-1cca-54a8-f0a9-cb3fd519bc00&j=da813497-1cca-54a8-f0a9-cb3fd519bc00&t=7dd3ffab-efd6-51e7-77f1-40598eb2014b

### CODE REVIEW

**Comment by petro-rudenko** [comment]
```
Received connection. Will read 1000000 bytes from remote address 139638287417344
Iteration 0, bandwidth: 24.7621 GB/s
Iteration 1, bandwidth: 42.8240 GB/s
Iteration 2, bandwidth: 45.0430 GB/s
Iteration 3, bandwidth: 41.6997 GB/s
Iteration 4, bandwidth: 45.9348 GB/s
```

@yosefe works now, and reports correct results.

**Comment by yosefe** [comment]
merging with https://github.com/openucx/ucx/pull/5961

**Comment by yosefe** [comment]
bot:pipe:retest

**Review by yosefe — APPROVED** [review]

**Pull request merged**
