### PR TITLE
UCT/UGNI/RDMA: Fix flag for cswap32

### PR DESCRIPTION
**Pull request by MattBBaker**
Subtle bug caused by using the wrong version of a flag to GNI_FmaPost.

### CODE REVIEW

**Comment by MattBBaker** [comment]
@shamisp Can you have a look at this one?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3086/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1156/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1157/ for details.

**Pull request merged**
