### PR TITLE
UCM/RELOC: Fix reading /proc/self/auxv when forking with valgrind.

### LINKED ISSUE #943: failure in malloc_hook.fork with valgrind
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2320/consoleFull
```
23:39:00 Note: Randomizing tests' orders with a seed of 63552 .
23:39:00 [==========] Running 989 tests from 158 test cases.
23:39:00 [----------] Global test environment set-up.
23:39:00 [----------] 3 tests from malloc_hook, where TypeParam = 
23:39:00 [ RUN      ] malloc_hook.fork
23:39:00 [     INFO ] Reduced heap free space to minimum: 3605595 after allocating 5590000 bytes
23:39:01 [1472675941.507000] [jenkins03:23563]            reloc.c:172  UCX  ERROR failed to read phent size
23:39:02 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucm/malloc_hook.cc:203: Failure
23:39:02 Expected: (m_unmap_size) >= (large_alloc_size), actual: 0 vs 41943040
23:39:02 process 0/4
23:39:02 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucm/malloc_hook.cc:205: Failure
23:39:02 Value of: is_ptr_in_range(ptr, large_alloc_size, m_unmap_ranges)
23:39:02   Actual: false
23:39:02 Expected: true
23:39:02 process 0/4
23:39:03 [     INFO ] process 3/4: small mapped: 503808, total mapped: 126357504, total unmapped: 125853696
23:39:04 [     INFO ] process 1/4: small mapped: 503808, total mapped: 126357504, total unmapped: 125853696
23:39:04 [     INFO ] process 2/4: small mapped: 503808, total mapped: 126357504, total unmapped: 125853696
23:39:04 [     INFO ] process 0/4: small mapped: 503808, total mapped: 126365696, total unmapped: 41955328
23:39:04 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucm/malloc_hook.cc:336: Failure
23:39:04 Value of: ((((*(int *) &(status))) & 0xff00) >> 8)
23:39:04   Actual: 1
23:39:04 Expected: 0
23:39:04 Process 0 failed
23:39:04 [  FAILED  ] malloc_hook.fork, where TypeParam =  and GetParam() =  (3540 ms)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #943

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2519/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1870/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
👍

**Pull request merged**
