### PR TITLE
INFO: Print memcpy bandwidth.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1438/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/825/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
autobot build

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/829/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1442/ for details.

**Comment by MattBBaker** [comment]
Buildbot failures are unrelated. I'm working on getting this fixed, but until then I suggest ignoring buildbot.

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
