### PR TITLE
POWER: improve store mem barrier

### PR DESCRIPTION
**Pull request by artpol84**
arch/power: Use faster "lwsync" to ensure store ordering
Reduces ib/mlx5 latency by 9 ns when changing memory barrier between WQE and DB record writes.

### CODE REVIEW

**Comment by artpol84** [comment]
@yosefe

**Comment by yosefe** [comment]
need someone from IBM to approve, @sssharka what do you think ?

**Comment by yosefe** [comment]
@artpol84 seems you are right, what bothers me is that rdma-core is using "sync" : https://github.com/linux-rdma/rdma-core/blob/master/util/udma_barrier.h#L88

**Comment by artpol84** [comment]
I see. As you know I talked to IBM guys and they confirmed that "lwsync" looks ok there. 
But I totally agree that we should triple-check before merging. So if we can get additional comments from rdma-core developers it would be great. 

And just to emphasize, I'm only replacing mem barrier between WQE post and DB record write.
The barrier between DB record write and BF/DB remains "sync" and this is what was also confirmed by our IBM partners.

**Comment by yosefe** [comment]
let's no merge yet

**Comment by artpol84** [comment]
@yosefe it seems to be OK to merge.
Should we drop WIP-DNM flag?

**Pull request merged**
