### PR TITLE
Expose emulation

### PR DESCRIPTION
**Pull request by tonycurtis**
## What
Adds ability to test whether external progress is required, e.g. when UCX has enabled its emulation mode. 

## Why ?
OpenSHMEM (and other consumers of UCX) may need to set up their own progress for AMs when engaging in passive 1-sided non-blocking operations.  This gives us the ability to ask UCX whether external progress is likely needed.

## How ?
Add a worker attribute field to expose use of AM (call it external progress for generality) that can be tested by ucp_worker_query()

### CODE REVIEW

**Comment by shamisp** [comment]
Adding @gmegan @yosefe  - this is API change.

**Comment by shamisp** [comment]
Adding @bbenton

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7834/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7838/ for details (Mellanox internal link).

**Pull request closed without merging**
