### PR TITLE
Typo fixes in license

### PR DESCRIPTION
**Pull request by bkmgit**
## What
Fixes typos

## Why ?
Make license section easier to read.

### CODE REVIEW

**Comment by yosefe** [comment]
@bkmgit please change to commit title to "LICENSE: Fix typo" and force-push
otherwise looks good

**Comment by bkmgit** [comment]
@yosefe Thanks done.

**Comment by bkmgit** [comment]
Signed on my part.

**Comment by shamisp** [comment]
@yosefe confirmed

**Review by yosefe — APPROVED** [review]

**Pull request merged**
