### PR TITLE
UCT/IB/MLX5: Accel requires CQ ignore overrun

### LINKED ISSUE #2940: Ubuntu 18.04 inbox driver failure: ‘struct mlx5dv_cq’ has no member named ‘uar’
```
4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:22:18 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

```
  CC       ib/rc/base/libuct_la-rc_ep.lo
../../../src/uct/ib/mlx5/ib_mlx5.c: In function ‘uct_ib_mlx5_get_cq’:
../../../src/uct/ib/mlx5/ib_mlx5.c:43:53: error: ‘struct mlx5dv_cq’ has no member named ‘uar’
     mlx5_cq->uar       = uct_dv_get_info_uar0(dcq.dv.uar);
                                                     ^
```

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**
Fixes #2940

### CODE REVIEW

**Comment by shamisp** [comment]
Ouch ! Why we didn't catch this in regression ? Looks like rdma-core upstream related issue ?

**Comment by shamisp** [comment]
I don't think ubuntu is any difference from rdma-core...

**Comment by yosefe** [comment]
it has a specific rdma-core version, which exposes the issue

**Comment by shamisp** [comment]
We should talk with Jason about this ...

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7918/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7927/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe do we have the backport ?

**Pull request merged**
