### PR TITLE
UCT/RCX: Add iface addr handling

### PR DESCRIPTION
**Pull request by brminich**
Forbid connections on rc_x if peers have different HW TM support status

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6140/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@hoopoepg, plz review

**Comment by yosefe** [comment]
@brminich for v1.3.x?

**Comment by brminich** [comment]
better add to v1.3 as well. will submit shortly

**Pull request merged**
