### PR TITLE
IB: Adding restricted to uct_ib_mlx5_inline_copy

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2578/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1934/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp what is the motivation for this?

**Comment by shamisp** [comment]
path the notion of non-overlap buffers. Compiler actually does smart stuff. We have to use it more.

**Comment by shssf** [comment]
@shamisp I would propose to use `restrict` as a macro similar to UCS_INLINE_ALWAYS and allow `configure` to control this because:
- compilers might use different syntax for this modifier
- if memory regions really crosses we will have memory corruption silently (no extra memory load generated), without any notice because compiler doesn't generate runtime checks for this. In this case, it is better to have ability to switch off `strict` modifier at compile time by `configure`.

**Comment by yosefe** [comment]
@shssf I think this is what AC_C_RESTRICT in configure.ac:72 does, right?

**Comment by shssf** [comment]
@yosefe Yes, it looks like it is.

**Comment by shamisp** [comment]
@shssf - ac_c_restrict takes care of variance between compilers. Probably we can add runtime asserts that verify that this is not overlapping memory.

**Comment by shssf** [comment]
@shamisp I agree with you but I think this is overinvestment to add runtime asserts at every code place.
I just think about something like:
```
AC_ARG_ENABLE([restrict-option],
    AS_HELP_STRING([--disable-restrict-option], [Disable restrict modifier for pointers, default: NO]),
    [],
    [enable_restrict-option=yes])

```
and use value of the `AC_C_RESTRICT` if the option is `yes`.

**Comment by shamisp** [comment]
@shssf - sure, sounds good.

**Pull request merged**
