### PR TITLE
BUILD: Check for mlx5dv.h w/o default includes

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**

### CODE REVIEW

**Comment by yosefe** [comment]
seems like it doesnt help:
```
configure: Checking for legacy bare-metal support
checking infiniband/mlx5_hw.h usability... yes
checking infiniband/mlx5_hw.h presence... yes
```
can you pls dpuble check on l-csi-0603s?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7626/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7631/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7634/ for details (Mellanox internal link).

**Pull request merged**
