### PR TITLE
UCT/TESTS: Wakeup tests fix for ugni

### PR DESCRIPTION
**Pull request by shssf**
This fix related to build procedure failed. Addressed comments in #1044 
@MattBBaker Could you please take a look?

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/113/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2705/ for details.

**Comment by MattBBaker** [comment]
Works 100% 👍

**Comment by MrBr-github** [comment]
bot:bgateNEW:retest

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2067/ for details (Mellanox internal link).

**Pull request merged**
