### PR TITLE
rpm/version: Fedora spec port from master to v1.2.x

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4259/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
@shamisp @yosefe @alinask please review

**Comment by shamisp** [comment]
Is this cherry pick from master ?

**Comment by amaslenn** [comment]
@shamisp yes, all of them. Two had conflicts, others were applied successfully.

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
Did it pass fedora review ? Can we do 1.2.1 ?

**Comment by amaslenn** [comment]
We should bump version to 1.2.1 and create a release with this version first. After that, I'll go to the second round of the review process. It is required to make `Source` tag in spec file real.

**Comment by shamisp** [comment]
Can you poke them BEFORE we actually tag release ? You can share with the
reviewers the specfile and get some initial feedback...

**Pull request merged**
