### PR TITLE
UCP: Instrumentation added

### PR DESCRIPTION
**Pull request by alex--m**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2246/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1578/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
