### PR TITLE
JENKINS:  CUDA Jenkin fixes - 1.7.x

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/13bf329949cee6d5bb0a61942a4d288fd9ecb8e0/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/ef4b076b186f4b6501180fed1fd399108d60b65d/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/c21458deb799a9206f1fdfc4f3609be4ddb60f91/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/444e09910a3dd5fd71c8d46ccccaad6eb78ed793/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/51f9e7d6f92e9b9c9c156c0610cbfe83c6e391db/hpc-test-node-new_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/99b8f205ce74500d893bf13d2cbb8f72f6ec1d0c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/2e74d401bef68fe6044149a7d4ac099f313ed20f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/b70a05ca4e5a1bcfd69328277443dc23606b0b3d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/ccb71e7ab2da5ba0be4192fe043fdfae71d2bd87/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/252d2d3f4fa1bca4c4e049280477420990661554/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/9374e3e67909f2043f3c844b680e9eba1cced1c9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/cb93e640b93f20e2ffcc9d261ca092414b8dc5e6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/5879d5c15d0db5ae82c35d6d94285e2b047dcb3c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/c146fe5a11224d9470b4ce92a364215eb76ed062/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/63ac7b51f2cc9a5c264e4eebffa00f942fa41261/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/543aecc93f42c76af1196a4eb581c350d6dfd3ba/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/a2724d535ed36c5d78ba03e6ab029d35294b1991/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/a63c13225c2e32845a34ec7f895e2acf08324804/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/9718bf23ea1305f1ac7a7dfc6749f8383575796b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/d4126f7498141fc00b6b16aa4a1b0b1cd2273985/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/081bffbcaa47721c48d94660e24e177fd533d54d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/b8bda5730a5b8f4fed505e8b1a952b863d993282/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/60600a1db2a3de0077049eb4ecead15c05bdce20/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/9183e6bfa0dc6bb16bd26f9fe0054226bcafd759/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/eedff2bb51fdd142e217cc04edc3e340/raw/ed951911a5280797a459aa038182e4efa9ba1adc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
ib_mad deadlock
bot:mlx:retest
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/ce2a578454e01003f5041c157dbf044f34a9ebdb/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/c866c82f4d11358c89ce9f0bca3d82abcb67134c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/695e0eb17dc06a19ae9edd153781b14c412d5308/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/2f66328a3032932685f8e45dcc88776c38aaff2d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/45d41ab7dc2c4305ae665a10f12203194a4f3fcd/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/9b8767c7e196eab49c8948b26d36fa300de381fc/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/88f5a5dbb1eea471e67e7c5e1a232aea8a6d0344/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/cbd204c79335dd6283d966167abd10e922ad391e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/7dcb6d01bb439fcb97ae3eb737f12ac09b9c946a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/f29c839778f633aa7b3445e36aae53fb26da3980/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/cefc5456afdef0bb9c7743d33340f8a9c4b90548/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/b16e08167cdcbd1a7162599303f0f8d38d37cafd/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/6360448bbde180ca5dadb932d8f81ad6dd69849d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/dcb148ab0775e5a7e366d5b44b31523396af998d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/928a4f6c56681ccb8d238bf08dfdf2e72e83a5b1/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/a58c766060ed24990c08bc6ee45dc80477daba88/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/911a10663be874d408e68162a276063881f7615b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/8defb78fb509c571081cd90f598df3b67b147aab/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/e4631cc8a8f11ddafd5be07b1cd4b2bf18b219e6/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/fcc5f10f151843962020074be17ef00f3bab4e20/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/fb619318a327c6d067dcb03346564dac1c7fc29a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/20f0071e506f29d76e5983a20156334db157ba90/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/b90a20d4a661b27e85096779c1ff5c4470c8f94f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/9c66bf666ee714fa486b5394c10818bd0c2e949a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/dabe1ee4c34f9d43ab1735da35b33d50/raw/92fd55ab292c3d075e3a3db3aed0ded3bf9f7a18/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
