### PR TITLE
CONFIG/BUILD: Enhance build configuration output

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/e24657bf50348ea181a725d5f6cab51581b5be83/_main) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/134c78c5e4995bb7e90a30bab5088a92053de3b7/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/fbb3626c45e77ab0d0d45e653b1113252b21ea04/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/99fe9c2d870e5bb638ca42bc99d53cccc90dde07/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/71e428eac6ac9414d90bf8461cb4fab2ac9c45d4/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/e995adeeff22991f234c852f57df4d82ecfcb90f/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/5c788b3c3e50ac75140e08eda3526647bcbcb33d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/a699def881e82b63f964d36674b0a40028b0f1b4/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/aaf4c084fe1cdce5e207ee6e2ac92f4877d6ffa1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/917a78b6babdae70544499d0319d95dc1c90324f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/c21a925c1be26e853bf8edb1199f762041a2165e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/881cb9021154ae140c72d15dad4358d110942e84/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/a542c97bf9e2aa6cf7f3f110b0a52e87cabd4aa2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/437619fc4b62c56c6967aae9bd1da2f801381e2f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/9efd4f485f44b6d15abd2c20e9f27ec1e1bb0f77/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/8687b31e40656d4ffac3499ad05a55e48eca6fd4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/21dda848b083559a716703b0c1c2f60851c3e7d2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/c82cac3f1417257ddc9345fcc0b20354b04602f5/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/f44ae8f11e5999d5ed6537ac9bb11d73e6c22fac/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/3711ade73348ceae7c5d548dc8b0c2d2bfab9d5e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/5a1f72f39422117707994d8e6eeab6fc674aa404/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/c64878d1330fd7c351f39fe3fdc9396f5cfb63d1/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/a357f366167c6711d423ace93eabbf90c9f5d267/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/1caebb20763b19b35ec86c4120a68a5f33bcd3fe/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9c102ebfbb38aaebfc5da01dba23c8c6/raw/9e1a0cf6a23527d7e296e012b79171fbd206a6cf/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/8478d7db2825db076560224a5315bb775a21cb52/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/b49acf524d52e8e78f4ecb82e34647f38a4d5af3/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/2462b8e9c670d2f309e01407b7717c6e64cdbabd/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/b37559ea0920e4932dde4b5ca59718fba7e866c5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/5ae34d151cb3d50488308206b952a66630f65e51/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/12816a715df4f9bcb261f96c02da5c930d8c2276/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/a3a53c371eb6be91caccbf8f1dc0a5288189be20/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/7dbb197eaafacd7a50f965fca5c9f8f175c4189e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/6ededdbf21a9a4fae8e3057a273bd4987539e5b7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/5e53ef62326ecb2f031ee017a5129dd56f811ba1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/db11c672b6afece1dcb1a8cba928c152f69e0f5f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/9c6f7e235dec7eebb92e90dbdbb9b5724ca97f16/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/98dd627ce5fc326f5be37c65cc565e8d00e6d4f0/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/71b2b1cb8b45ce17f109a543582b4bb793b0834b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/2fee8704507395fcd3fec74e6d2b941442bcf763/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/b64f6528a0be40b8c71a5f41151a65db9063f6fb/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/aa5c14990f8ccfe2d0c18538f44034117747e58c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/c1c44ca9b52dad7f4e15ff63e36c3f9963a98da9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/206ba88020ce26632fbd13bd73e890c624d08d57/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/3af64d0e2b20c9eb2952271b8c94de5dd058d8c9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/24eb6cc699fc639a9adf0f4fdb0ac46a7f5c5544/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/304e1e410a9d27d6cd68837b4cb4bb89edcd83f7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/ee6af2872c6a438d26566105c32389ca2277df6d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/ef6724cef9093d6a743168a850407a8df4fee6d0/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5f5bd92aa7d6424ae6d78e2011f86f4d/raw/de6073d0cdcc79f23639b0263909aa82780819f6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/544c3b9dd5dbf72de57854cf825dc3ef5371e5f8/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/e863feb15bf53aca69efd2d4d78f48ea9f08043f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/38b4a5862452022863b9d659846e6a7dcc85721b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/8d7b3ebcb1df4ea89d9fa73d9428d16ab6e0d425/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/2e85393b096cee92c1a173643622c1cc900a1772/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/8a4b1857fbdb9b82b1661adc76a6a799e0389325/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/30d391571b997b9c38f68b1b98cfd14e4c14da51/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/bef62bb11670f542d0617e8448bbb85e5feda539/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/7b692a2be1f90882966f5793d4171b827d8853d7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/911da66429c477fd93aeac77170b525f83c736d6/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/1d88e499e9b5221e5fbfbbee8f8f0e11ce17bccd/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/8ab5d1765730575b6c752b2435a0a50cf4b43a4c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/909a46fc63cde29ffd107663af86d7883e7502cc/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/8776c1b0a7784186457a42b2b870e5f6f3b7d1e8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/07957fe7b89b02712557f91b7def9b44ccf027fe/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/e486cb4880f89422e9b8f9be7b79b3c3cf82f7f0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/514ce2bf17e2801ee1c2857325567c86e853bcb7/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/34a739c3d5dac4ce2fcd11b43c13ac3dc4453dad/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/9f34cb6d8cb9d6b11520262f79018ab5dfa31697/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/8ead07f0e8c0ad7c5424a78f91106b37b9704483/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/fc672a47c6ae6a609cb26da112aca220e42a7041/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/9429c7e0ecefe5d260422d4a27e8073880498a01/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/f58429ab861b2e19ad67b4e2ef3bd41422c0faad/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/2290e43ef8d836f9daa627c54f7e2329f878f6be/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/00b75dcc46869ab2dae5bdc4a33dcec5/raw/1bc683fa4152215f52a9d1f88a1a5c2af5641fa9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
