### PR TITLE
UCG: Updated spinlock-related API

### PR DESCRIPTION
**Pull request by alex--m**
After changing UCX's spinlock with #4779 - this fixes UCG's references to the new spinlock API.

### CODE REVIEW

**Comment by yosefe** [comment]
I don't understand why we need pull request to UCX when UCG repo is updated?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 22 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/5f5a8a4ace2922fd5aca463ce85454274b7599cc/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/505e28177602660bdbc6254c80f535f9f0d4b7e3/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/bb459fccf73c4d473e833c84c2346a91b2ac99e0/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/a1d58077e0b64197463e87218c8edbf7325c3c83/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/c9be0a7fff51e94c2316e09ad6d284af99f86b90/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/e1af6ae3b2c6dfe1f5068dbc2e52dd5149036c73/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/51f5f750c1f506deba33f848e140d6f2f4b4bcb1/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/bc91d29941053e88df952e1a37ab6fd24c69e9da/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/c2fe6de2d50f42b075f48be5f190e71c1d5c0938/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/851843f4d08989f3155ee4629525743186b7c2a6/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/78ccd38b160955099a6d37abd29a6e72819e0c42/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/437c5d0e6577db1d982165aed1084ed5d6060410/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/c07fab5525a9c04f97a155a10e5823629951203c/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/2e9379f37139dd15155c80fbe9597dda037d5184/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/46c6a39f9db097642f53c69f5c38ee9cb4d0c153/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/9c55921c2fb427921dfd5f48942ffb25cd9a229e/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/8fb7d1c0ba94e21a30b65eb2391d9c3da88d9adf/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/997bb84af02388ed96f063c5d90b464ab7762a10/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/0a5e768080037690a4caea330ce348b64a5e189c/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/0d2f3fd2aa8975f52a93dd2c382913200cb39ab6/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/18494907d13b3cabf3e7acb96435a0abc3e72bfa/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/de37fdc6057047caff82940156df935d/raw/6abdf502978ff20835ed008c2df169a4699990ab/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by shamisp** [comment]
second this ...

**Comment by alex--m** [comment]
Closed in favor of #4875 .

**Pull request closed without merging**
