### PR TITLE
UCP/EP: Fix handling of disconnect event on failed endpoint

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by evgeny-leksikov** [comment]
this is covered by https://github.com/openucx/ucx/pull/5075 which fixes more cases

**Comment by yosefe** [comment]
> this is covered by #5075 which fixes more cases

@evgeny-leksikov can you pls point to exact commit/line in your PR which replaces this PR?

**Comment by evgeny-leksikov** [comment]
> > this is covered by #5075 which fixes more cases
> 
> @evgeny-leksikov can you pls point to exact commit/line in your PR which replaces this PR?

commit 542ce6ae55aefcc4b293083d5af7c200c2e918af line 528
condition `if (ucp_ep->flags & UCP_EP_FLAG_FAILED) {` goes first and covers more cases, this way `else` brach covers only `ucs_assert(ucp_ep->flags & UCP_EP_FLAG_CLOSED);` case as before.

**Comment by yosefe** [comment]
covered by #5075

**Pull request closed without merging**
