### PR TITLE
DOCS: fix doxygen warnings about broken links

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
Fix doxygen warnings about broken links

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8180/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp can u pls take a look?
@evgeny-leksikov can you make test_jenkins fail if there are any doxygen warnings (for regression testing)? could be in separate PR

**Comment by shamisp** [comment]
👍 thanks for fixing this.

FYI, http://doxygen.10944.n7.nabble.com/Doxygen-exit-code-td3736.html

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8185/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8195/ for details (Mellanox internal link).

**Pull request merged**
