### PR TITLE
UCT/RC/DC: Fix multiple inheritance of DC configuration.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@MattBBaker can you please post ORNL failure?

**Comment by MattBBaker** [comment]
@yosefe More /dev/shm out of memory failures.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2533/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1887/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@alex-mikheev pls take a look

**Pull request merged**
