### PR TITLE
UCT: fix #1502, #1513 (backport to v1.2)

### LINKED ISSUE #1502: Hang in MPI_Finalize with UCX_TLS=rc[_x],sm on the probe-unexp test
Command to reproduce:

> mpirun -x -np 2496 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1 -mca btl_openib_if_include mlx5_0:1 -mca coll_hcoll_enable 0 -x UCX_TLS=rc,sm -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20170510_132009_18827_734706_clx-hercules-113/installs/50e4/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/probe-unexp

Reproducibility ~50% with rc and rc_x, ud works fine.

Most of processes (~2461) are in MPIx_Fence, others (~35) are in mca_pml_ucx_waitall.

@alinask

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
- Fix hang in MPI_Finalize with UCX_TLS=rc[_x],sm

Fixes  https://github.com/openucx/ucx/issues/1539

@yosefe @shamisp

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1727/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3667/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1733/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3675/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3680/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3682/ for details (Mellanox internal link).

**Pull request merged**
