### PR TITLE
PARSER: added bandwidth auto value

### PR DESCRIPTION
**Pull request by hoopoepg**
- also added UCS_VALUE_AUTO_STR preprocessor string to use in strcmp

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11705/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4118201caac136468222fee6dc91288d/raw/6d34f85003b821b15fb5acaec654d3f7a5f40f9f/_main) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11707/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11706/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 24 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/a86b4a72e960e6c15fd0c116ae3deb9730413017/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/698d873ce65878b8d7988955b2b06411398d0b69/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/de2e061a141d73d4a9d5886de869f8b891f4ea47/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/bcc4479c61d4907256f8e4de4d4cc6054764fe7a/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/a2a18fda00cff4fd55f25e593cf454818edbe1e0/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/42a6b3814848921a00e5698bb6f7f9cf899431c8/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/e0c9477492169608b06fb4bc6442e12b2fb67d9d/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/633842a3827740f3ffb122f14039b47552da7a89/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/2aea763a1bd146e7eea03ee180874e3ea1b62f9c/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/e464123c70466f5626b4b68801bc005e232d88db/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/29daba082cf953feee33f8997a821cfe1735accb/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/f3968f823c37a57c1e38f44dba6880ab5fa06d5e/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/ba19d0f9914c057d62f34a65b1a0e9ff54afb7ba/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/f6e14881d608b1c6d243b8eadc0deb4edf4d9ec8/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/fd1bef7f26ee338691e0ee4f94455922399e5551/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/e3ba51863199ad1cebb42817e2c9434dff824323/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/0b34af8f5fe5caa59ad15cbd8b419e1fa821ec77/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/e06976d6f55ad8bbc65f6c03d4958b045de8bcaf/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/3096adb6bfc99c3df87c2688497ffde2bb8dd1e3/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/b4fb6b17a5398fffa1d57342171aa700ab33d222/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/b688b736c4df79b41d516669cc7476d71462d221/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/b3cd3fc7f339d691fe0b0aec2fce9e273ebb2cf3/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/2c6099cf0a62784f10d9317e18e5d0a2322000b6/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/fc2998adb2da7c871d23926adbdd152b7c05c015/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/15e515570925ac1638cff64285ff07c68cefc365/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/7efe55c95f5d611439431ff9d8a7a35b52d2e30e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/d7fd388af2cffaa028eefe43ca2d594b03ee3517/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/ba8f0e1772814e373c1f35a5a7c293d8b4edf088/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5d8be6808a97327e2a0c4fd0306324b0/raw/b5348c8050244a9df0544821f90fa0aec11bccad/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 15 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/d6483f875ce18ac1ddf3098845e39170e9b48cdd/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/b21bd89a13a9ff89e4a2baa696b60367bed863e5/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/c54c1359e18b84a4da09f612de4ec2b2943a2f62/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/6d932b0c13413a01efd1a2557ef47808d5d0cfa4/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/966618e58ae653e8b4e00149ceb6f58aa57e15f2/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/6f9a35b27a16c5dc4429bfc9b928e8e9d955ce63/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/b7599701a03150c7c1626411877d3a447f6c56e5/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/a04c5ac05953f27450ba48749789d0c115816d68/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/a228ba91e23cbf1622f79e27b2a63e7ac4039dc0/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/0ced23427888f9be0bbc1e2eaa3460ac43043184/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/457ffd39975364ef1a2fbbe99db3a295301f2567/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/5006e6cb9fb32bd0a85d3cb9f03623ac536c8cbf/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/fa9eb85cb7dec1a63bd141ee98dead577dabad80/hpc-test-node-new_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/87ae0778fd405594f11efd63bca985249531985f/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/1979d70817a5df2f25efd0a83b1e49fc482480e3/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/29cd9035a2743f62632dbe0f061e59b9c4cb73e4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/a305fde9aee376440cfa918a319e5566b6c395e7/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/0aed0b2ec32e69425f9f6937c603a3e538c3e8ae/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/3665cae9b7aa7c2052eb12b6ea92532f1ce056bd/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/4247320e8eb333f569267ca234f7b3a11c8bfec1/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/0a67d9a5b71f7dc123a6139a19a138ba23de2eb8/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/af493e08bbf2ab382d30fb3ba6aa6099cd072268/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/95847f4e48290e6b97979562ba9710c53a08d601/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/40442ed2df1fd084b6dc69669f8bae41e8d8d22e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/e3e7efcb7005e3bfd500f3f6c96eefe3e30ce6c7/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/3103b1ec7fb7c77323860399f28739829b700ef3/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/b3af38d0f31dd3bc401370b288b6b858993a3fd2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/09a63fa044687fdc11ac19c3101d0c134d36ca50/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f3b1b980aa15d44fedecd2f03fb727ea/raw/3ca2b03517af1a0805da129ea17291cfb1823ca7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11708/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/6d2e2ee3840b7198ddec0087a4f3d8dbe676fe23/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/08f850efa3491f999244f5a5e231b0b0e5dbfad7/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/ef5e246fbf9efd09b0aa8b5ec8971b339c33f3d4/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/47562270d0e810b79f78c20504e259aed97e2530/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/9e4abe3a21ac244b9738760d73cbd967e727d897/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/f019ea63bb4ed859964508cfe5ae87cd86b80613/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/b943bba97f844d0476535af81f91be330a527337/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/25cb935944b34df5dbfc1c13bca3029237dedc9d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/34e05f48f3a9ad0181273f965ba6d18944510fdb/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/c3bd4ccc8918351804addb8b24cd1e60247eea75/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/c4084b249d01c17b46c36ccb723d92e53906df30/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/99794b42d147d4c42b984f16b1901ba23a5d12aa/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/1582a807699338285d98acdc4b321ec690509439/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/640ba60dd91b93e21dba160e264687c0b9ec6e7c/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/d87cdfa06cd7ac07a3f78b573a08392e46879111/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/da4034e00f562143ccadb3032582522b6562b6ce/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/499ec05716bf1cbd127aa143d3f0b989f4436ea6/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/cb486e8fe1bbe32078cecc3b70a5f75504e9bf1a/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/53a0bd251936775f38745d960978b09573a4b12a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/71b7cb22d82f44829db464b751fb698e3fcc4198/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/a7326f37b729449ebcb899c5a3d39a3e265de4e4/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/ea4ab161aafbe6aecd82b6cd3e947aca09b1a311/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/fb3af2a9066c32045ebc42e1b5715c5f185b9bd7/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/050d2053db0bdf76bb365a18a49baa72e0fa07b6/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/8781811c3c03923aeafb47582a32682597a34d9e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/d33855451b73be4b042da5896dd1fa615aaff544/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/d03ece8f53f3f1faf96d1aa143861b6b935bbb5d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/5001cf9d61c88d7173446214bb5cba8bd4c7d81a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c48586b6701affc0ea175eeed20a5659/raw/c0c2ecd58bc329bbe5dbc6d96f1cb8911dcf0252/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
bot:pipe:retest

**Pull request merged**
