### PR TITLE
TOOLS/PERF: Fix releasing uninitialized pointer.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@MattBBaker this should fix the bug from #711

**Comment by MattBBaker** [comment]
@yosefe Test passes now, bug fixed. :+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1140/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1745/ for details.

**Pull request merged**
