### PR TITLE
UCT/UGNI: Update UGNI to new UCT api.

### PR DESCRIPTION
**Pull request by MattBBaker**
## What
Refactoring UGNI portion to conform to new UCT api.

## Why ?
the UGNI uct layer currently doesn't compile.

## How ?
Data structures have been reworked to conform to the new API, some bad behavior the layer got away with in the past has also been tightened up.

### CODE REVIEW

**Comment by shamisp** [comment]
@MattBBaker does the patch address the issue of smsg not fitting in udt packet ?

**Comment by MattBBaker** [comment]
@shamisp Unfortunately not. This just makes the build work with the new API.

**Comment by shamisp** [comment]
@MattBBaker okay. So this is just the compilation issue. 
Any plans on fixing the header side ? Can we make the same assumption as @yosefe made for homogeneous IB setup and just pack less information ? All Cray setups with ugni are completely homogenous.

**Comment by MattBBaker** [comment]
@shamisp That would be enormously helpful, since then we would just have to pack the CDM id and the compated smsg struct. Do you have a PR handy on that change set?

**Comment by shamisp** [comment]
@MattBBaker #3056 defines env for this.

**Comment by shamisp** [comment]
For Cray unified_mode is alway true. You just have to add a bit extra logic in UCT to compress the data.

**Comment by MattBBaker** [comment]
Looking through these changes I wonder if that will even be needed. That change set might just do the trick by itself.

**Comment by shamisp** [comment]
Crossing the finders. Maybe you can narrow this down by specifying TLs that you have to use.

**Comment by MattBBaker** [comment]
Seeing a lot of love from that. Now, there is a problem that someone seems to keep adding tests to gtest that causes ugni to fail in interesting ways. In particular pending queue problems.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9150/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9154/ for details (Mellanox internal link).

**Pull request merged**
