### PR TITLE
UGNI/SMSG: Fix compilation in debug mode.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1723/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1119/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @MattBBaker

**Comment by MattBBaker** [comment]
Oops. Though it looks like --enable-debug does not imply --enable-stats? I'll have to add that in my titan configure line.

:+1:

**Pull request merged**
