### PR TITLE
UCT/IB/MLX5: fix zcopy_post flags

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
fix zcopy_post flags in MLX5 TL

### CODE REVIEW

**Review by yosefe — APPROVED** [review]
I guess fence was missing?

**Comment by yosefe** [comment]
Any chance we could find this in some gtest?

**Comment by evgeny-leksikov** [comment]
> I guess fence was missing?

yes

**Comment by evgeny-leksikov** [comment]
> Any chance we could find this in some gtest?

gga_mlx5/test_uct_perf.envelope on BF (in CI #9993 ) hangs with 30-40% probablility without correct fence.

**Pull request merged**
