### PR TITLE
Completely disable unused makefiles

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12447/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/11289359ef53003343d630ba6da6498faf9a7ae5/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/dd9ccd9fc1e7db7ac5be4666f76d4554d8a30e9d/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/08999f8d9ee56857f7f84063103a11baf072d675/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/017c0692c0784414340bfe93fa92e14dddbfbea2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/28d980d075f8d1a2c3cafe3413a28313ab157752/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/45d90de9cd10a37734c8f23510e0490c6fe10468/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/569ab8fb128703db41d61eb4a30e9989ca5e2ee1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/9840248b3fbe70254d3a8dcd3278a659ada4e46e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/f0558db8cc186b3857180af267e4be6b33ca3008/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/1b4794c7f1a509795b4a84e5f813c7188d01d83e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/347daa0b7c911e4653f36ab55c4e8334bad619f4/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/ed69168ddeb63f24055e88ef1a49b214ee942424/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/7a22e11dae3f38f843dbe657b5eb5db0db01254e/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/5d78ca6473fbbe3445450e7390ee9e7999d74b99/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/ceeeb392daac979306adc09a98ad5d0ce1b1e717/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/d9e00ba13f2051db60a485fb4ca98f038f6bf830/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/f5098887ade2690e735a11f01c72a87824e2d399/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/6ec0bc41c14cc6e55adec4126b757d26c547a59c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/0126da8fb76bc5083d518d13575a0e5d7f9af969/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/79363e4cd06dc2936988a5c632412002a3ebf8d1/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/a05142a06fc5af0b8ed3c986226bf0da31b03f83/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/7ad9ac6149665f92f1bc777c8f14b49f4a1aec9d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/0452b43e4517ae601d39c3738455ccf8cc0a463c/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/1f849e826911623b516133eca59fe2e1d27d46ed/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/5c6c0fc4f76c545015583044ed341f48febb7e1f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/81b543bdc472b469706a4abd63e87b307eeee836/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/fef7e98e1ef8738ffb48b7656b0988674d4b3846/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/763b21befa29653e1d5ac7e8fe838485c4a7c3cb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ace91e41da3c10b5cdeaaeaba178a43d/raw/2f05cb4a183e09e7e112b78390da8b1425d75755/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
#4207 

bot:mlx:retest
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12456/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/43c6e73af5e511326b94afc1fe3edcb61500261e/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/94953cf22a8386f077bc260fa66022cc65e31949/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/3aee926f91a8b795bec1345f0abe6008205f726f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/89cb59662c2fd2f4b28eba92d56216f73c67f4ad/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/5da48737957aa41c04ecbb7646c659845bc56fb6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/f3df9a2dfbd723c2cf73e46aa4417cf1702b6708/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/b816264be4b8e8acd9ff80a3b82352f49e6948e2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/a6668918e67b49d247555a47c44b3f5dce54d79a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/2f635698fc81f096221f04345ec6cf6731e98b43/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/b839296cb0ddcfc522196134ada80481060845ee/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/6eee293743d95683d7ac6678a900c269e47ae141/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/9d74a3980aa78c5f7bd1dcbfa83ef8d05bc06cdf/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/66582781c2a40b7bf6a2e6a2f253b5e5f8fadc97/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/2ca727aabba057db827cf5f01adc6f211258e438/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/166ca3c212600f4e777c485e2f5c0bc0245edcc9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/9862e60695b5de1eb397e60541745c4e6e65bad6/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/8ee787e10f67069e40848a9f0fba496cd56f1907/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/c64030e6293564dc7033d9bd99aed95fda9aadb5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/f8187d86faa489e41a9e7c22ba86d4792787f843/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/83dbaa2c78d57844ea4750af50d52c06bffa94b0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/c40555ee7655311ab6368169e5113904e0b60825/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/f27c29a8fae7e7737b86ea545a52d4b7ce85faad/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/6c3630d5289d8983a7cb68b7166b135e4361591f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/93d81469d60c2a8317bcb9cc7ee944395c623b83/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/e458054bbb43c65c31900c1bf72863a0ef1fd512/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/86e8f62195f8701845a9313d32eb996a44f801c3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/4cded80040ada4b5867e2ecc399ffa3647f6c413/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/8dc791f00566532ca7e855387c25f806d5877fa2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e1f23dfcdc837d59754f95db441408d4/raw/4c0f0ba8f345fd2f6cbce7585235ed2bbf845ef1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
👍

**Pull request merged**
