### PR TITLE
UCX/API: external API is wrapped into -=extern "C"=-

### PR DESCRIPTION
**Pull request by hoopoepg**
- added 'extern "C"' wrapper around public functions definitions

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp pls take a look

**Comment by hoopoepg** [comment]
@yosefe I updated gtests - removed deprecated extern "C" references (and wrapped some internal headers into extern "C")

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5004/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5005/ for details (Mellanox internal link).

**Pull request merged**
