### PR TITLE
UCT/IB/MLX5: Remove the c99 'restrict' keyword.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2567/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1921/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls take a look

**Comment by shamisp** [comment]
@yosefe - what is your concern here ? I added macro that checks for restrict.

**Comment by yosefe** [comment]
@shamisp where is it?

**Comment by shamisp** [comment]
https://github.com/openucx/ucx/blob/master/configure.ac#L72

**Pull request closed without merging**
