### PR TITLE
UGNI: fix the device type.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by shamisp** [comment]
@MattBBaker please take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1397/ for details.

**Comment by MattBBaker** [comment]
@shamisp already on it.

That first mellanox failure is ib related perf failures, not relevant here. 

Still in the middle of running the test on titan, but given the change I would say that it's good.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/785/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Everything is in order. :+1: please merge.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
