### PR TITLE
UCT/UGNI: Build as loadable module

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
@hppritcha FYI. Can you please take a look

**Comment by shamisp** [comment]
Adding @MattBBaker

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8972/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
The autoconf stuff looks fine, but it looks like I missed a recent UCT API change. It doesn't look too bad though, I'll see if I can fix it up quickly.

**Pull request merged**
