### PR TITLE
AZP: run new bunch of tests - GPU

### PR DESCRIPTION
**Pull request by amaslenn**
## What
Run "GPU" testing in AZP

## Why ?
Migrate from Jenkins to Azure.

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/df1a83da4ffb23276b270b4f12e22bbedf3b63a4/_main) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/d62463c8031a312e900a305bd5fcbba28619e8b3/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/8487d0c89e9a6eda51abae9b6eb44cd5c536045c/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/900f4d1c8a1ef1d5f7a2c5404ea3f50a5501d454/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/a0cdbfb125d0754b1caa21e80434a199f3eabee4/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/2bdc190fb4d1cfa38110d8a07f026be704fcdf1d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/f4b5b1f7f70b8673af38ef4e514e670e515fd16a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/6e941e5745a830a41b4dfc368321b84a2f48de42/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/6843f18a097e5d8a0bf4e3d926c661c8da9715eb/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/409219266a95646adb4e1a707a80b6d49a9d3914/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/9ae5d2b8cd866a2a3a4cb346770e243fa5adc567/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/73c8f68345f0fb8ba415e3f872f8b080844bfc69/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/90e8c9c45eb3f5c519300e3dc6f56773b33c9692/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/70dec93090cb031cfd7aa8a19c3528b3c2dbd7ab/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/c6327223250c80a472672f5f95309d075ef80668/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/934f2b6c86fd942577117193b9d67f85e8a0c289/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/a96395c9a6198db5cb1f0649dc01bb6a7e5f93df/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/2ccbce1e615cec74981107873942693d97f27dfb/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/0c88237d8616456b41447b8c17b0c34aea55da8d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/62675b9c2989c51a86dd80cc047600da6dde05b6/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/dc92023ec9f880631879b07a8790d883cb8b9cd4/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/c831ad22e8a311f331e44c07a71d1e4a063b4b00/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/ca7d287acf1ca95e801a7482c55b5bd52ec0ecbf/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/f756f28ff0463bd2eb3f1abb0d613d6dc6c4de66/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a43d06ec9ec22c9402d3ec80689d2b4b/raw/83f74df567761d5017ced071aa5a6089ca0b2a31/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by amaslenn** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/a194c24558d6eb889f0a7cbdd7e6b1791b0ef28b/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/a495d3d6959ea218bb103aefbea06c3752380ceb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/f5ed6502105cdb2b6fb399db359ee046eba1a73f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/e1537ec65bbccc6034d1d16331bd76a5967d2d31/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/b9568f72bcbeecede5b34ebd077d5f94c281df25/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/f7a50f330eaa99e694b3a4b2157bd0e9842515cf/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/2d48e7a68e02e1e4e2a84cd79214ba4733dedef8/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/5bae1d5822f4a46a8a9db0cc256a991db0e6640b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/02eed299d1fe3363ed135f5507658a5685a56fb3/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/f590677936f304593a07669b157e2434b4df719f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/7b4ee4c3041a317bdba298a7f6fbe0f9a87b7a3c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/84dff145903edb4b42f5e7a700ee71f4c3c34906/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/54721dc72a0f8232a15015ae72f54d16ec22d9d8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/6938ab2d04e26e903d0033f71f9933f0ac6d61d9/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/fcefa7f7401539e856b8b565fb5d14ec8cee2e65/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/4e876112970f20879fdf4dc1e62e76abf78b1ada/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/fa8df6b0dbe674b02cd11c26308ee3eae57a8e4a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/ae22c208a06c6b79c1aff8dc06f666b808248c81/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/7004a3c404f29a755e623c815b2ce28b5714d536/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/ccc5d77fe7974e7c24a5692a095db2ca8c2e545f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/ebcabd41aeb9dabaf2652b28fb46e4927ed04f29/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/a050a1b3a8b62d8f849c53886f55da0eda26c8db/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/01ed2f0ac762f7ba0a9fca15aa27cd938fcfc93b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/4873173b44c98349ee5e194c19b43333e50cca72/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/dce82997074f670def08ff0a1cf99f0d/raw/d613af73f41b5dac3c63494bfb463b65f125a87c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by amaslenn** [comment]
OK to merge?

**Pull request merged**
