### PR TITLE
UCP: Fix recursive call to ucp_worker_progress().

### LINKED ISSUE #607: assertion failure in ucp (Assertion `worker->inprogress++ == 0' failed)
There is a an assertion failure in ucp detected in mtt.

It is:
```
ucp_worker.c:302  Assertion `worker->inprogress++ == 0' failed
```

Command line to reproduce (2 hosts) :
```
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/installs/IxSk/install/bin/mpirun -np 48 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_1:1 -x UCX_ACC_DEVICES=all -x UCX_TLS=rc_x,mm --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/installs/IxSk/tests/mpich_tests/mpich-mellanox.git/test/mpi/basic/simple
```

Backtrace:
```
Tue Feb  9 04:03:26 2016[1,5]<stderr>:/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/base/ud_ep.c: [ uct_ud_ep_rx_creq() ]
Tue Feb  9 04:03:26 2016[1,5]<stderr>:      ...Tue Feb  9 04:03:26 2016[1,5]<stderr>:      334     ucs_assert_always(ctl->conn_req.ib_addr.id == ep->dest_ep_id);
Tue Feb  9 04:03:26 2016[1,5]<stderr>:      335     /* creq must always have same psn */
Tue Feb  9 04:03:26 2016[1,5]<stderr>:      336     ucs_assert_always(ep->rx.ooo_pkts.head_sn == neth->psn);
Tue Feb  9 04:03:26 2016[1,5]<stderr>:==>   337     /* scedule connection reply op */
Tue Feb  9 04:03:26 2016[1,5]<stderr>:      338     UCT_UD_EP_HOOK_CALL_RX(ep, neth, sizeof(*neth) + sizeof(*ctl));
Tue Feb  9 04:03:26 2016[1,5]<stderr>:      339     uct_ud_ep_ctl_op_add(iface, ep, UCT_UD_EP_OP_CREP);
Tue Feb  9 04:03:26 2016[1,5]<stderr>:      340 }
Tue Feb  9 04:03:26 2016[1,5]<stderr>:Tue Feb  9 04:03:26 2016[1,22]<stderr>:
Tue Feb  9 04:03:26 2016[1,22]<stderr>:/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/ucp/core/ucp_worker.c: [ ucp_worker_progress() ]Tue Feb  9 04:03:26 2016[1,22]<stderr>:      ...
Tue Feb  9 04:03:26 2016[1,22]<stderr>:      299      * coverity[assert_side_effect]
Tue Feb  9 04:03:26 2016[1,22]<stderr>:      300      */
Tue Feb  9 04:03:26 2016[1,22]<stderr>:      301     ucs_assert(worker->inprogress++ == 0);
Tue Feb  9 04:03:26 2016[1,22]<stderr>:==>   302     uct_worker_progress(worker->uct);
Tue Feb  9 04:03:26 2016[1,22]<stderr>:      303     ucs_async_check_miss(&worker->async);
Tue Feb  9 04:03:26 2016[1,22]<stderr>:      304 
Tue Feb  9 04:03:26 2016[1,22]<stderr>:      305     /* coverity[assert_side_effect] */
Tue Feb  9 04:03:26 2016[1,22]<stderr>:Tue Feb  9 04:03:26 2016[1,7]<stderr>:==== backtrace ====
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 0 0x0000000000028be6 uct_ud_ep_rx_creq()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/base/ud_ep.c:337Tue Feb  9 04:03:26 2016[1,7]<stderr>: 1 0x0000000000028be6 uct_ud_ep_process_rx()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/base/ud_ep.c:410
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 2 0x000000000002a16d uct_ud_verbs_iface_poll_rx()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/verbs/ud_verbs.c:289
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 3 0x000000000002a16d uct_ud_verbs_iface_async_progress()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/verbs/ud_verbs.c:306
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 4 0x0000000000025fbf uct_ud_iface_timer()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/base/ud_iface.c:564
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 5 0x0000000000025fbf uct_ud_iface_timer()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/uct/ib/ud/base/ud_iface.c:565
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 6 0x000000000002b26a ucs_async_dispatch_handler_cb()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/ucs/async/async.c:94
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 7 0x000000000002b869 ucs_hashed_ucs_async_handler_t_find()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/ucs/async/async.c:23
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 8 0x000000000002b8dd ucs_async_dispatch_handler()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/ucs/async/async.c:126
Tue Feb  9 04:03:26 2016[1,7]<stderr>: 9 0x000000000002f27f ucs_async_thread_func()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160208_223553_36686_92103_r-hp01/ucx_src/src/ucs/async/thread.c:97
Tue Feb  9 04:03:26 2016[1,7]<stderr>:10 0x000000395dc079d1 start_thread()  pthread_create.c:0
Tue Feb  9 04:03:26 2016[1,7]<stderr>:11 0x000000395d8e8b6d __clone()  ??:0
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #607

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1476/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1477/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1478/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1479/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/872/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/873/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1480/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/874/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
failure is unrelated

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/875/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
