### PR TITLE
UCP/WIREUP: fix for UD TL processing

### PR DESCRIPTION
**Pull request by hoopoepg**
- fixed regression for UD detection function

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6066/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6074/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe ok to go?

**Pull request merged**
