### PR TITLE
AZP: enable for all release branch (and related PRs)

### PR DESCRIPTION
**Pull request by amaslenn**
## What
Enable AZP checks for all release branches and related PRs.

## Why ?
To have all release PRs tested before merge.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11834/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/641513d24fb9d042c1f296370024e42520652eb6/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/937759f6103938351011c8c55e5afc24d42aa687/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/57f850ced6b7a9700b2e0017e2e865d98969dcc3/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/d6dc0faf9c0b4a7aa9597e1d2c6a9cb9a08958f8/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/f6d08012d9a38b22f0dca7920132c9b1d95651ad/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/0d57e706fdd74034bfd897a84b3e0f707443fc6a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/42078e0500004a4e5943193df7483582c8f0cdf3/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/bd34cc43119365e99c7d6bf07db804900cb29317/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/4711307a55f1956c3e219ef2938f1ae6cd290737/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/673550c60ef1765b1285367632119474f0665244/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/2e2bacca953ccee49f0f6e992a2582d114e328c5/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/c5dd4b188b2c201802aa5d0c3604af1890b2fa58/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/5b37ba6d71e3b5a6e36c1a27352acdd0dbeac3bc/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/69e9ac1d36f90111a5c937756d54904635b0b898/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/9b413a25981d707d46ecef2db257bef030385046/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/33acb983007730124dc823af6971b80e6aae53e4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/d55208d498746d1eee7e3d7c67cbec1e30eaece2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/273b973889ade2eb75c1a82e1ab9f3422dfcdbbc/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/f49c10de8b93ae669d85c0de12c29dc8f6fca95d/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/99561b1053925baad4060cedafec080397df66d0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/61d2817416a607e16dedbf1e8ef4566eff02020f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/a2005259953bb7a8c32b1e19ff22ab915478a3c4/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/3e99ac8d3ab142886471dd91912b4c6ea01f9508/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/639ad95b98aab41bf450f59ee34350b4fe3cd7c0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/5bfb74b297be3c07af97ecd4445003a57d43967d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/3af7ec9446b8c945f8af77c1620e4a1f3a2910f3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/d656c100606646415cf6fb584558f228c7443df9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/725815fb8a22e189c857256b0af9219eebc499c4/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e9470d6941bd7a3deee32b7cdbe214c/raw/49a2162ccd193334eab2d9144206c906a68be03b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by amaslenn** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
