### PR TITLE
GTEST/MALLOC_HOOKS: added barrier to test exit

### PR DESCRIPTION
**Pull request by hoopoepg**
- added barrier to test exit to prevent race on event fire

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg did you see it fixes the error on juno003?

**Comment by hoopoepg** [comment]
yes, reproduced on juno003 (one shot from 500), with this fix is not reproduced anymore

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7898/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7902/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7909/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
failed due to infra issues

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7914/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Pull request merged**
