### PR TITLE
UCP/API/INFO: Add API to define endpoint scope name for debug info

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Show which kind of endpoint are we printing the information for - "intra-node", "inter-node", "self".
The scope name will be set from the upper layer, for example - an MPI library.

### CODE REVIEW

**Comment by yosefe** [comment]
@brminich can you pls take a look?

**Comment by brminich** [comment]
general comment is that it looks like a duplication of EP name. Regarding the scope, can we try to identify that internally and use for the debugging info? Because user already may customize the ep name, and he may not be able to recognize the scope himself (for instance if he just uses some ip address)

**Comment by yosefe** [comment]
> general comment is that it looks like a duplication of EP name. Regarding the scope, can we try to identify that internally and use for the debugging info? Because user already may customize the ep name, and he may not be able to recognize the scope himself (for instance if he just uses some ip address)

The problem with name is that it has to be unique, but on the other hand - scope has to "group" several endpoints of the same type so we can aggregate their configuration info.
We can try to detect internally - but it can be incomplete (for example what if self or shared memory transports are disabled)?
Also users can provide custom "ep_scope" such as "server" / "client"..

**Comment by brminich** [comment]
ok, then is it supposed to be matched with ep configs? What is the main difference with the name? Seems that in our API we do not require name to be unique (we only mention that t will be unique by default i)
I think it will also be difficult for the user to understand the topology and define the scope.

**Comment by yosefe** [comment]
> ok, then is it supposed to be matched with ep configs? What is the main difference with the name? Seems that in our API we do not require name to be unique (we only mention that it will be unique by default)
> I think it will also be difficult for the user to understand the topology and define the scope.

Yes, the scope is matched with ep_config, so it's part of the ep config key (if scope is different, config is also different index)
name - it has to be unique since used as a directory name in VFS

**Comment by brminich** [comment]
> Yes, the scope is matched with ep_config, so it's part of the ep config key (if scope is different, config is also different index) name - it has to be unique since used as a directory name in VFS
So, if we have the same configs except the user defined scope we will have to create different config entries? Can it lead to some scalability problems (e.g. large number of ep configs), when user sets quite unique scopes?

**Pull request closed without merging**
