### PR TITLE
TEST/ucp_hello_world: ucx_init() parameters initialization

### LINKED ISSUE #1286: Reverted functionality in hello example
I think that in https://github.com/openucx/ucx/blob/master/test/examples/ucp_hello_world.c#L467 it should be negation.
Example works anyway, but it looks confusing (at least to me).

### PR DESCRIPTION
**Pull request by shssf**
This PR fixes #1286

### CODE REVIEW

**Comment by evgeny-leksikov** [comment]
@shssf please note this PR has conflicts with #1233

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2840/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2843/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3348/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/880/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2844/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3353/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/884/ for details.

**Comment by shssf** [comment]
@yosefe merge conflicts resolved. Please review.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2848/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3373/ for details.

**Pull request merged**
