### PR TITLE
UCT/RELOC: Fix patching dlopen() dependencies

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg does it help with knem issue?

**Comment by hoopoepg** [comment]
@yosefe will check later (now there is no available configurations for testing)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11003/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/012d2fb261c71d79e620a282e43e610cfea6e9e4/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/c21ee6a942d1ff6e52e7882fbe199ab8599a5316/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/f8ab28233d653aa3bf62fac063801c75b8225b6d/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/09adea7addd2c30db3a997fcb6a3e13e7d13140e/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/20fd3db5ce601e74251c267df7074913de8bd5ca/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/c8565b52863dfa68ed0e624e8e8f82b26ccb6b37/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/caccedbcb2a04cf2c0f36419d3565a12514febca/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/e9539ff0e8324850765574cdc9ef204f0a51eefd/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/ddd1258ddd4fba1ea5ae40b84e9ef0e02f792d82/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/306ca70984c9429a13795e53726a272e6a2a0e58/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/b92651d8e8cb28523e2b19c20c5ef9c4801bdf10/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/a4bab02243ee43bdb15575070f0f04284410ac70/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/634e50ddab6dd08b41a04021b5bbd3f96de647cc/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/bb94b31fa9e839bd8e52b93344dc85344a7cc1e8/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/a96af31f1519837efeb4c8990fc2fec402bca8ca/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/db0c14015fe2d15d53b69f12efdd5b1367f30c51/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/d317b33b1e9d352ed27cfe286b63475d95e60c2d/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/9faf718e56cac7e0fd712d5672f0aedb034ecb7b/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/3469b985b9f25cba338509334b413cfb57be9f69/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/8930115a1302b7520432024751877d5ae5789e3b/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/35f2d1c4d3c0833721a14f6ddaad40104e214c90/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/74aa18d84761ac7e2e7dba9f437e627253bd0dca/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/9293166147527fab4be007c492791b13db7d3c65/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/afa208befbd7c6eeaacfa15c5e8c075de63daa77/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/8fc3474f4fe7de54f6fa5d77d2d734f83b1befcb/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/d1a04621f5b7c675fb755ef662849ea06b67886e/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/8228219565f101bbccfd1ce97e9470cfd4275e2c/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/ac4501311e41afdfe99b50277a0e8f0a67920af2/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/2cbc6cd52e1f7839b18dc1d2ef83f2349abd5d12/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/060d6cfe482017f260b188dc8c1c55448d6ea35c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/a0a13a407b2494a0053a411c5e269042d503c8db/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/cc1062665cd1916c4e5bf579ee94804d998c4065/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/8fb61f7a3fa9a30a03e79efc619e00387d377a5e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/e6154dc75690a48dc6e5977fb8d0321ba5689209/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/a324765a97f02e9e30b37c0a1bca8913461ed357/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/191065635b45a0a116688914434027b94793cc50/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b706fd15d688e675bfaf4eded592a047/raw/08c16fb7fb540571267c42215ecf1c3719c8b4fe/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
