### PR TITLE
AZP: Fix snapshot v1 10

### PR DESCRIPTION
**Pull request by avildema**
we need to use lowest version for build

### CODE REVIEW

**Review by yosefe — APPROVED** [review]
@petro-rudenko can u pls confirm it works now?

**Comment by petro-rudenko** [comment]
Do we need to port this as well: https://github.com/openucx/ucx/pull/6516/ ?
@yosefe it's not a snapshot publishing. For 1.10 we need a release publishing. So we can check it works - when merging this and create 1.10.1-rc2

**Comment by yosefe** [comment]
@avildema do we need to add something in the title to trigger release pipeline and check it works?

**Comment by yosefe** [comment]
bot:pipe:retest

**Review by petro-rudenko — APPROVED** [review]

**Pull request merged**
