### PR TITLE
BUILD: Bump version to 1.5

### PR DESCRIPTION
**Pull request by yosefe**
v1.5 for now
When we start breaking API/ABI will be bumped to v2.0

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7175/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
failure is #2670 
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7176/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7177/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Pull request merged**
