### PR TITLE
UCX: bump version to 1.2.2

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4581/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
We have never tagged 1.2.1, how did we get to 1.2.2 without official release of 1.2.1

**Comment by shamisp** [comment]
-1

**Comment by yosefe** [comment]
@shamisp https://github.com/openucx/ucx/releases/tag/v1.2.1

**Comment by shamisp** [comment]
didn't notice. We have to check that ucx doc version get's update. Can you please check the pdf ?

**Comment by shamisp** [comment]
BTW, I overlooked it but each release has to have description similar to 1.2.0 in the github release version.

**Comment by shamisp** [comment]
News file has to be update 
https://github.com/openucx/ucx/blob/master/NEWS

(for both, 1.2.1 and 1.2.2)

**Comment by amaslenn** [comment]
Doxygen is up to date:
https://github.com/openucx/ucx/blob/2411231810a4337d8f12b6817bbb0f4d051751a6/doc/doxygen/header.tex#L131

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4612/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
It should be 1.2.x.

Also, I want to stop this random releases without proper change log and release notes.

**Comment by yosefe** [comment]
@shamisp we have to provide link with release tarball for Fedora review process. Do you have other suggestion how this can be done?

**Comment by yosefe** [comment]
@amaslenn we discussed it with @shamisp , and let's try to provide tarballs for Fedora which are built from your local fork. Once the process is complete, we will merge it to 1.2.2 and create the final tarball for Fedora.

**Comment by amaslenn** [comment]
@yosefe got it. I think you can close this PR for a while.

**Pull request closed without merging**
