### PR TITLE
TEST/WAKEUP: Handle UCS_ERR_BUSY returned from ucp_worker_arm().

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4027/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @evgeny-leksikov pls take a look

**Comment by evgeny-leksikov** [comment]
👍 @yosefe did we have these tests failed or you just noticed wrong usage?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4028/ for details (Mellanox internal link).

**Pull request merged**
