### PR TITLE
AZP: edit existing release if exist — v1.6

### PR DESCRIPTION
**Pull request by amaslenn**
(cherry picked from commit ab86fb41a12a359489c02f5b89bf4707b68e6594)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12978/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/dc74799503adc51975b81493b632502642bd3c9d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/be7c02446b3980ddc8d850bdf90ba3819314e886/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/ecc3da183a4f7c3189806543aa4f402d265b2035/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/0cd16d934a834c76750387690a594d46bfaee61a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/5a2fad00ca1d7cf48c5b1f39e76def12478f6ef1/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/1189a36d273a1a526f357d8db0ad858d700ae77a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/cd255aa0cf35df4b479c8a3a45a0cd2fdffc81d2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/cb80d6f7d4dbb969bf4a081407e53a93973f501f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/8ecd8fb6b74d0a60ff8764dc1e5b0924d8fb256b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/96eef61b36a7880817dba59bb9ddf552bc542bc1/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/02743a719541119fdf8cdec05bcaefaddcbe2ebd/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/efadfdd248d25a99c11cd18f0ed01cac0f4b88fd/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/f8a6186694825464e0ece214747ef2753125e52e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/793e191ffaf9608a1011751d826ef05fc02117e4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/ed7bf74a415e1fb33017eb4b40c5459c3356554e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/705bb0943f7259e13c9c2a44063febcc78eb2620/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/b3bbd073d5fad3f7416e858e0a298ea54ea57860/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/6032ebe03a84f99986c4d70e63f5f8c543962ed0/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/ab862fa2392cfbb0bc2b2934517b38f007e1e12d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/d93af40ee07515b61b72f5ec13e22fe606ce6930/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/750c5b51a529a627e64b84ba98882b49f6eb33c9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/def9ea49493cf27e838e0359ddc4f3b8468d4fe7/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/e80b094119732c7859d28a9ccf014a0c41613c72/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/821f35d1095a05fa3558dae9c46daa65711249bc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/602494c686add6a9519f8a8ca84cb513b02157fb/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/38a5f88f74fc32682e05b4cc08aa8e5c6c8d9615/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/6063fcbfcdd13c15d95895d4af1dfca584d9f86b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/74619a114b47ed2eb535d9dbf3afb4d7f7226b79/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/46d4e9fa960f53b5af81282ca01c0788/raw/c54f3d0ba70df05d6fe5874d5a4043da0b9f9226/hpc-test-node-legacy_W0) | :question: UNKNOWN

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
out-of-memory on boo31
bot:pipe:retest

**Pull request merged**
