### PR TITLE
NEWS: adding KNEM and XPMEM to the list of supported transports

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@yosefe - review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/847/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/273/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
shouldn't we document other features except shared memory transports?
also, what about CMA?

**Comment by shamisp** [comment]
cma mentioned in 1.0.0

**Comment by shamisp** [comment]
other feature - I'm not aware of other features

**Comment by shamisp** [comment]
later on we add UCP interface enchantments

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
