### PR TITLE
UCT/IB/MLX5: Add method to add information to UCT worker, and fix mlx5 BF.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1034/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/463/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
is this the optimization that we discussed at f2f ?

**Comment by yosefe** [comment]
this is mainly a bug fix, and also a preparation for this optimization.

**Comment by shamisp** [comment]
feynman6 is mlx5

**Comment by yosefe** [comment]
i'm splitting this PR into 2 separate PRs:
1. share mlx5 BF
2. create QP on IB resource domain

**Comment by yosefe** [comment]
#465

**Pull request closed without merging**
