### PR TITLE
UCM: Fixes in malloc hooks.

### LINKED ISSUE #548: malloc_hook.threads test hangs on power
```
gtest/gtest --gtest_filter=* 
[     INFO ] Using random seed of 11893
[==========] Running 307 tests from 68 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from malloc_hook, where TypeParam = 
[ RUN      ] malloc_hook.threads
```

….

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #548

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1326/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/723/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/724/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1328/ for details.

**Comment by shamisp** [comment]
```
[----------] 2 tests from rc/test_uct_pending
[ RUN      ] rc/test_uct_pending.pending_op/0
[pod7:2512 :0] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2b7025fa2000)
[pod7:2512 :0] Process frozen…
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1332/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1333/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/728/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@MattBBaker can you post pod7 and pod11 failures?

**Comment by miked-mellanox** [comment]
@yosefe - what was a root cause for ppc failure?

**Comment by yosefe** [comment]
deadlock: malloc/realloc() -> lock(malloc_hook_lock) -> dlrealloc()
fix: replace internal dlrealloc with mremap()

**Comment by miked-mellanox** [comment]
:+1:

**Comment by MattBBaker** [comment]
The pod7 failure:
[ RUN      ] ud/test_ud_pending.connect/0
uct/test_ud_pending.cc:134: Failure
Value of: req_count
  Actual: 0
Expected: N
Which is: 13
[  FAILED  ] ud/test_ud_pending.connect/0, where GetParam() = ud/mlx4_0:1 (4089 ms)

pod11 2 failures:

[ RUN      ] rc/test_uct_perf.envelope/0
[     INFO ] mlx4_0:1                am latency : 6.723 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 6.72334 vs 2.5
[     INFO ] mlx4_0:1                   am rate : 0.536 Mpps
base/test_perf.cc:289: Failure
Expected: (value) >= (min), actual: 0.536355 vs 1.1
[     INFO ] mlx4_0:1                 am rate64 : 0.654 Mpps
base/test_perf.cc:289: Failure
Expected: (value) >= (min), actual: 0.653671 vs 1.1
[     INFO ] mlx4_0:1               am bcopy bw : 739.363 MB/sec
[     INFO ] mlx4_0:1               am zcopy bw : 478.077 MB/sec
base/test_perf.cc:289: Failure
Expected: (value) >= (min), actual: 478.077 vs 620
[     INFO ] mlx4_0:1               put latency : 1.939 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 1.9394 vs 1.5
[     INFO ] mlx4_0:1                  put rate : 1.713 Mpps
[     INFO ] mlx4_0:1              put bcopy bw : 893.023 MB/sec
[     INFO ] mlx4_0:1              put zcopy bw : 708.908 MB/sec
[     INFO ] mlx4_0:1               get latency : 3.687 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 3.68682 vs 2.5
[     INFO ] mlx4_0:1        atomic add latency : 6.778 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 6.77795 vs 3.5
[     INFO ] mlx4_0:1           atomic add rate : 0.570 Mpps
[     INFO ] mlx4_0:1       atomic fadd latency : 3.581 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 3.58111 vs 3.5
[     INFO ] mlx4_0:1      atomic cswap latency : 4.816 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 4.81632 vs 3.5
[  FAILED  ] rc/test_uct_perf.envelope/0, where GetParam() = rc/mlx4_0:1 (23538 ms)

-----

[ RUN      ] ud/test_uct_perf.envelope/0
[     INFO ] mlx4_0:1                am latency : 6.068 usec
base/test_perf.cc:290: Failure
Expected: (value) < (max), actual: 6.06832 vs 2.5
[     INFO ] mlx4_0:1                   am rate : 0.560 Mpps
base/test_perf.cc:289: Failure
Expected: (value) >= (min), actual: 0.560494 vs 1.1
[     INFO ] mlx4_0:1                 am rate64 : 0.525 Mpps
base/test_perf.cc:289: Failure
Expected: (value) >= (min), actual: 0.525336 vs 1.1
[     INFO ] mlx4_0:1               am bcopy bw : 478.304 MB/sec
base/test_perf.cc:289: Failure
Expected: (value) >= (min), actual: 478.304 vs 620
[  FAILED  ] ud/test_uct_perf.envelope/0, where GetParam() = ud/mlx4_0:1 (20231 ms)

**Comment by shamisp** [comment]
seems like perf failure that can be ignored

**Comment by yosefe** [comment]
the ud failure is unrelated

**Comment by alex-mikheev** [comment]
@yosefe 
It looks like the packets were not sent during the short_progress_loop() for some reason.

@MattBBaker can you manually reproduce the failure in ud/test_ud_pending.connect/0 on pod7 ?
(To reproduce run: env UCX_LOG_LEVEL=data gtest --gtest_filter=ud/test_ud_pending.connect/0)
If so can you post the output ?

**Comment by MattBBaker** [comment]
@alex-mikheev Been trying to reproduce it, but it looks like it is fixed.

**Pull request merged**
