### PR TITLE
UCT/IB/RC: Fix atomic endianness for ConenctX-4 devices.

### LINKED ISSUE #823: MLX5 ConnectX4 support
AMOs 64bit appear to be broken. The issue was discussed with @yosefe off-line. I have implemented prove-of-concept bugfix and @yosefe will introduce a prober solution.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #823

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1991/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1366/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1367/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1369/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1994/ for details.

**Comment by yosefe** [comment]
@alex-mikheev can you please review?

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
