### PR TITLE
JUCX: rename organization to openucx.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Rename java package to be in organization openucx.

## Why ?
In order to submit to maven central java package should correspond to the organization site domain:
https://central.sonatype.org/pages/choosing-your-coordinates.html

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11495/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 17 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/10f2afbf30b834c480a9645af5c80a54ff53b88d/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/bfd1f3c8ad15ce22dde38b323289c87c9932a8a0/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/a6cf5dcbe32bec71c3cafa5e43ea7174b27058ab/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/7bc8724fbf3af411b680639b27b7770d520969b0/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/912a1410a72e21e9d293ef16e90cd24b49ac04f8/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/ce10b94d0a1a1d8f3e75c199e470268485cd6046/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/29fa6e38a5892148891b66876e681803f2ad9d53/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/741205c0c58742473eede8037921515a54414cf9/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/6e7b54eec7465171fb4bd4a1c31f399035b20604/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/ee03d3c8074731bf8d72b8f4e9ecc362dae0ca73/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/162d46163270f5574e7d455a5910783826c46f29/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/de6563821f01202549c674e0329177f12632d85a/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/00b391940b870a5ef3b5516f43f2cecb925e66e8/hpc-test-node-new_W3) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/858e4afed7fb8644174ac1dc6408a8d9cd81e79c/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/ff39cafe5c37bb1baae93530062c820c19abcb9d/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/8fcc4dafb12c9815b084e6aa748f5439634df2ad/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/b7ced0baeb631fe7332efa3be682524a569175d7/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/39b2f92513d944f5d1c49cbee3a4faeeeddb6ac2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/3dcb1c8afdcbb8e82459b474c5c29b61cc7b5450/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/38fd05008adfcd6889cd924b9362384337ef107a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/fb32b5bd0b2e0e9f77ee8ef34c7278f6afcb6367/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/5e3d2b30d32694accb0b84ff8f25ce36b5b9f389/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/2969fd59f8670182dd70b888ef7c5de3301e3185/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/ea14f279ff6e64ca219ee3c0b4b809e18265ba06/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/0b9a0cf6fa0cd5c73756fa07fb4e7e51e41c999d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/fe4eb7544cf6a47023298c0c0c06fdd8665f1658/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/d56c327e6f556ce59cbafe0c742e6d0d7ccbf90c/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/8b09e4cd3b8e5a0fe6c1dc784f167229a197c03e/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/6f95fb62fe4e761c6c635e2213745599812a1cf3/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/832eb020407493cac5beecf8b4a2adf2a4b86af9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/400d87278d3779f5cfbc3e3bc822df99aa3ca80c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/73b3da9b8b7204ca4147983f75eb725b44871f8f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/639cbc3a2ae977d6db00cb980649505d/raw/59a292960303dab3f2b03aaddf8e64999971a17c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11496/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/262dc223515aed4237fe93a28d88992bce9b47d1/_main) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/49ff374e40e6c5e18c1ffbd25724a067f4c14fdb/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/1284baec414873732d8f90f2029db138d60be9a6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/502b7e45e2e4f8d6cfe30003d85bce9555b5bc1e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/d8a66242bca40537546c2d0ce77d4b19ce22c4b9/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/72448842d3d0acdb9bae45bba381753c1d4b27fc/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/5a3cd7da57bea862c36edccd7a50809d66e6039e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/982443218185224f12afae0297d08d04e366a501/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/7d9c704e2d88d229198820dcaa194d2643a2cfca/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/edfac139f76af629b7ec8eadcbfbf4c94c249f79/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/483f4586dd1d3bb42a9104021fee51af4bd0673e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/d63234ffc77ea9d4682f0863500607a60740e296/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/b3754f39e97ca8d5a6a22aceb4b473ef5a48af53/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/b7dc8587700074b8a5a33408e3fec223b37650fa/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/ae0721f8f7890931257b7f527610d97f2faae4ad/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/27034cf1f531bdb2e5d0ea18d8b46429feb0ce7d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/f52b9aeb16e524823e07555cc462f8fa3758c699/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/981af5e98cd2336ef4a9deadb2bf85475f8ea997/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/bc2560839d82a053a04fd90d13ee8b2748025c36/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/7ebb37b675e36dcd9ea9de276c558c89972fcf99/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/22ad54afdf8ef40f7ad8a769b0b255775a9e4e7c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/4c1fccbcd70bce50d92039cec057a061648e70c6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/709b21372489b0122f39fc4d040d5bdd7d7263d9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/6deef896807a168808c8b44f395c061e593256ad/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/57ccd03678dd58481d9c01bc5e21ac464508e323/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/d9784b35d495f5309df208e650749e4b43f9c4c6/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/2c78c554b1e6acb0909d146f86bffdbfd5e07c0c/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/68a14e39756531b41b99f2c59555a185b9c38a6b/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/cfbd0504e30bc527504f93623dbaa09078d1f2a7/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/65a18daa528a7f12920a6960585174033f5a8df0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/b29e1085193239d7c4ad720b7cfddce4ce6bbec6/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/ca931f00985882ac21a1e044b4ee294b6505c2fb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c018c90ea8d9697b30d1c5bbba963fbc/raw/5132331c93b9cda00a51844f65708a0c65d41996/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by petro-rudenko** [comment]
bot:mlx:retest

**Comment by shamisp** [comment]
@petro-rudenko may I ask what is the reason ?

**Comment by petro-rudenko** [comment]
@shamisp 
1. In java there's a [name conversion](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). E.g. if companyA  and companyB may want to have their own JUCX library. They can deploy with namespace like `com.companyA.ucx` and  `com.companyB.ucx`
2. Maven central is a de-facto standard way to deploy open source libraries for java - you don't have to to download or install anything - you just have to specify dependency for you project and build tool (like maven) would bring everything needed to build your project.
3. In order to publish to maven central `groupId` of your project has to match the project's website.
4. Project website in **openucx.org**, not **ucx.org** so we can't use that name.

**Comment by shamisp** [comment]
> 4. Project website in **openucx.org**, not **ucx.org** so we can't use that name.

Okay, I didn't realize that package name is linked to domain name. Sounds good.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11500/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/e2ebb72e7e6ae4f559e5425d3efa9c40c5792b8d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/cc1396679bd5b0cf0f3f3743f586a9076186877b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/331bd72fc806b1b800c41a23039b95724098fef6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/cfb1593da173b4aa55791f0e51242ca85fb7b5e4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/37e83d4377cc5cb69918bb1b26845612618bb0ba/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/6fa149a2db63a8b15e0e2849096576cc4892ed0d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/8f63f307a9e8f1634d15d146b4317c83c0bf43bc/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/f747b7ec03593c79d277ea7678ef721c0155038f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/7dd2079c3998809cb899dc365a6ee2bf0a4a2fe1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/63e973cf35ae928f202fe724196a88b9636b5e16/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/7383cc029a55f7771ef24d1403c4d7dbee6252dc/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/0cf838a248f58a60d09fba17aaa826fd2b6ac113/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/21283893244bbff2b3cd0a4462c1f693b1c9e22d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/54a0170059f0be3c37295358da48fdedbc418000/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/c4a0b90a6f69e52ed848c4c7ebed29ae4fe66b4b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/53a0aa72f97abdb6cc3ca357f109060422174c2b/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/95472f8f54774c8b43aea2f92493746ff5434fcd/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/16249327839e5f22ee117e27caa43be7d5d80c56/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/c0b5ab58d707cfee8d93daea24a81017f050a795/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/78edca01a58ee70cf2883ccb51224520edb7997f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/d80183d400c19d1fdcfbced537bae8ee9e6f2d6e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/3ef933e0659c2495697f05d5abe812cf1db23186/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/ff264815e3dad772b423159e7b51559b5c089663/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/69241ff4ce4bf232ecdf20208496121a56ad41c1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/03004d8c736910cc54e06c79df8ed3975e5a5cb4/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/b2d78df6519f850ad2b0cd41ee737ee05c275fa5/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/e6ca00d8d77f02b4ebabe036e11553591ab0d53a/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/fbc6d99d8aef67217ae63d829e8a6ec630d743fa/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/46bfbab26435c0355728b72cc5807c3b8429975f/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/6310e5c283205aaf4fb62414fff7c33c49cbb09f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/cf557383cc87825dab6a06fc2f204fbd035cfb67/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/96e367fd4d7dcb076559b6045cde7963f5a653b7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5afd2559a4f878714164b6777e934bb1/raw/b2a7b0a92422e3d9391461023ea3b058a943277e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
