### PR TITLE
DOCS/RTD: Add download and FAQ pages

### PR DESCRIPTION
**Pull request by yosefe**
Add Download and FAQ from gh-pages.
Rendered HTML: https://openucx.readthedocs.io/en/topic-docs-rtd-add-download-and-faq-pages

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/4e1270048c62b78e455e109b7973a4d855ef866e/_main) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/7a99e46e71713a92e01d65dacc07bb23eb2f6eab/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/0e959a4b9584ea2b79295106498c85e3499b415c/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/69ba8613f9ac259343fb4577362ad35bf9545c0d/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/9dc39b0dfb4c3cbe5782be02e7fcdb9a254a6357/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/622c7cedb01dd5cd25ae716f8324c5ec24d9f4da/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/97076223b617f7cac2be4960908b1a7c29c3155d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/a2b98a34c989216a74c479ba50dc3d3273cccb6a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/76dad29d980444a8274fbebe3429e0f039f4e435/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/087864a5b3490d5eb0fc3b648d788cc4f50319d5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/bde671b8cf1d16161af44e493fabf2ffccfc1ae6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/135d0784d133e716c7bb71675cbb6555b3d3c560/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/7f1689ea02b529e8c8161b38b03c28e4cb9e15ae/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/b19649cbb44c720c0a592eea5430c36662d8533a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/b3708a5045377d992244a7840375c6456bea9c4a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/df6bb4e4a4669120b7c235962e4118d46b97cdef/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/6021290ddbe9dd86bf51fd7d75ab84ff5666af0e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/3fc2a6638fdbb0011cef7e2e57162066eec8989d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/7cc39bfef4eca39de4aac3332a2dcaa18d54f123/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/71ba67bb224344e6f10cbd3c63b8a1966ecc4ada/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/8869847be52755d591b4d79046337b2c30792a68/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/3e9aec44d9aec8e61935b1a647cc7dbc61700484/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/7482c1ac39c1641667213762edd27927c52a2d18/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/5d69bfc7248caa56c0fd7896aac50fc4b701bdcd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/22490f731cdb8161605d82c642af862f/raw/80af6545d3aca07fe1b999c479d6ed5f7fe556de/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/6b76d4552a45e54f009f0b34a5f4d0111e687e35/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/f44ff9c11f68e7184f95cf3aafcbcb67b9bb0622/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/7e0accaef1dee69356b71440fa08dadba21f58f5/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/7068c5053a4030dc49e9e22ed9cd30082afa7b50/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/4664e9bf891b4c04464e52e2ff9958884969f9a8/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/71cc8d8e7bd820cd48261113ca0ab423c58b4b78/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/c441c220c9e9a294de229cbc16d585ac43589599/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/ef5237039824f09ebb07443ef49f6103918c7c4a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/8bf823d2abde1910ec6f6a8b4a9218454d7e890a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/7c45b1160808ec4cfed0772a429a851fa349b9d2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/8a3ad574f9abb872572685a9370b7d0c1665d66b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/50af332b927c9be3498c1fe86ede768455b54323/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/a9e4ade12b62ed43bb006a40f0f139a528d1c072/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/5206dbcf53a38752d33b103d2abb39468a9c9e85/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/2d36a178a1f9d466b563e249e6b6f201e20f9acf/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/b85a5b4e5c102cab8ba5c60953c194defe606bcb/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/c52bceb51ec8db0edbd0fe18fa0f14f2c9c48b38/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/93bc1d06cbdfee4da88ba4185a1469cfd433df62/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/edd71628b780212e71f1af0784d8ee18e9719f4f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/5b0b0fe52ada4a85743d3670f086802b6d39fc42/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/247203a72bd45a2bc56820f4036c146d7d75b937/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/64ce228e62d27c3f0155746c599ae25fec3dc4d8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/f359ddf5cdf104256673b952a8cf0a7dcdf1919f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/9f899f05e804cb23580510b07706438b2491d09d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/00ddedeb02982115722ad2d9545e712e/raw/df3bcfb095495cd187d30a9775e34f2384cda93f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/57633515494a64a4ac13b4b137397345b47ec910/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/d12bb2281b7f62eba7c58960863d8b7192ad84bc/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/86968604611e9006eb34cb26825ff33bd1349c96/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/09dee6d61703bbcadcfa90a9406a9bd923ec54d5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/e7220601442b7a25c191e2310afcd6e767ab82ca/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/e72ad29d88cecebec87900969b67ac264f68df86/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/e52f88a943632ebc7f772b418054039ac994a40f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/c08dcc62b997c3c8c013c58ac017e3c1beeec419/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/7d77fa95b482a7fd059625fa39951d86960fc7b2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/d8376080afea3728742b49b35fa0accec7ab9b07/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/cd021d12c94a499a4a6805282f59710714f77619/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/09a81abba87a05eed1f49bdb3f217c32dcb200c3/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/d17625499e11fb94f57600735a10ebaea64268aa/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/2c322c95563cdbc4dcc5cf9719b1d9c7e1958a14/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/ddc1fc48542b95a7096c765a7c20c44980f3fa11/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/5fb2ca8b537579afc7378acb5402583a0eb1cf08/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/c472e843a54acfacbcc04dd65e396f512549c6fe/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/f5acff65c7045d9c4f1ae7f964c5d94b91e577fe/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/f0f3f1fa959c90df169c48a916f79431c4771ddd/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/3ed5b0943561ed8c608fa0de03d33ea7af3bb578/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/e077eb0a9eb224ad09b1e9d95ca94b79e9fe410c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/68cab9f7ba73f36aec96f2389e746d48d03b9104/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/b0285482643f0fa1d4dfbfd8af90152ad2271bdb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/0dd63ca2afb030402a1bf92f287107d430c62089/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7d0a611e0810f2bc184f27860bcfb731/raw/553a37f6b4412d1fe6eff538ebbe6176b9a369dc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@shamisp @tonycurtis can you pls take a look?

**Comment by shamisp** [comment]
Looks good to me.

**Pull request merged**
