### PR TITLE
UCP/API/TEST: Fix ucs_status_ptr_t checks

### LINKED ISSUE #4128: incorrect UCS_PTR_STATUS(request) behavior
`(UCS_PTR_STATUS(request) == UCS_OK)` check is ~failing~ false positive if last byte of the inprogress request object address bits are 0. 

```
(gdb) n
84              if (UCS_PTR_STATUS(self->reply) == UCS_OK) {
(gdb) p self->reply
$1 = (void *) 0x1689a00
(gdb) p ((ucs_status_t)(intptr_t)(self->reply))
$2 = UCS_OK
(gdb) p ((ucs_status_t)(intptr_t)(0x1689a00))
$3 = UCS_OK
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #4128

### CODE REVIEW

**Comment by yosefe** [comment]
@bureddy can you pls check if it works for you?
@shamisp @tonycurtis pls take a look on API doc fix

**Comment by shamisp** [comment]
what will happen to the codes using old semantics

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12229/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/31d0427aeb32097ac94a7144eee3dabbda6bcb55/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/7591b008f205a6ba8f36cb6089747c7c7e12aeab/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/d5b422e1d867af108d0264a99fd34ad8f0ea1c1e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/836b912e78e94df440327f395b3bde42ef005627/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/162b897db7d4aeb2c6f9296ba34aceef54387298/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/0d4fa5f52febb4d774a372b5648ca00a9ce5828d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/daabf9660c63cbc7bae0885024815f7a41d75a96/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/d37582489df5e18d3bac9e97e82522e0758f757c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/fdba666b6f14287a4ea505017f0169b055499263/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/425fe1003bace77ee8fb0717faf84bab75cfc05f/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/05fec40aa885ce9a2acee5919dfb10653c30f414/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/97c0e919872b78dd3a52a9ecfa3ea24f95aae26b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/0e7a3901d36c0dc5d0b514c2c88b0d4d42d7a7c8/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/5befcb87ca6b8b582225fb5bb46111d07122ff73/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/b9a0eaaa3286cab66d4dfc3b5a550c0e64ceb77b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/d8cc0170fb112b1e89c40f36c6a5dac6c8cdbb15/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/ca7afa3f32303ada07f2f070303a66970e95b58e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/bbcaeee371a14aeefb2e4cb4af64196dc1ac6b86/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/eae4f35f3c9a6d14312a46e59c03584f98568f3b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/7d4bff1f120faf4e54ff2cbf5cf9067477072f5b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/54895599d7de008e6ff7af8bfae9e02f960b4897/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/f8fe9da095b520ee85946a443213cfda184b4c16/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/a549f071a82a2073d19d8dc24f2fba55b59576cc/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/eaad5a82c3cda81a0491ba50b78b70278e069859/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/7c5633bc42840fd3c294eaf53b49a260e588d3c7/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/fcab30a44b68b70a99bef2ab522e6623f2187b8a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/221a3d990001ba06d32f4bd930f67c4830a8afd4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/9ecf6e42e9f9bef6d5e7dd1e8e10fe6631bb0284/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c3853f4fad5c946c1a31b6588338f323/raw/1cf935d160593bc4e611d4c082534b3c2e8a6cb7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by bureddy** [comment]
@yosefe  I fixed ucp_request_t size in PR https://github.com/openucx/ucx/pull/4123 . It is not changing the size. So, it hard to reproduce issue in that PR. 
But, other repro of crash in ucp_hello_world by simply  adding the padding bytes in request object is fixed by this PR

**Comment by tonycurtis** [comment]
Looks ok.

**Comment by yosefe** [comment]
@shamisp the codes using the old semantics were never correct.

**Comment by shamisp** [comment]
@yosefe but we don't really fix existing codes. According to @bureddy some of the recent changes introduced the alignment changes which breaks this check. So, we still going to have bunch of existing codes using the same macro and doing the wrong thing. Can we change ucs_status_t to 64 bit value ?

**Comment by yosefe** [comment]
@shamisp we are eventually not changing the alignment so it should not break
this PR only fixes documentation, examples, and gtests

**Comment by yosefe** [comment]
also, we can't break ABI

**Comment by shamisp** [comment]
Do we have unit test for request alignment, to make sure that we don't break it in a future ?

**Comment by yosefe** [comment]
we have a unit test that request size does not change

**Comment by shamisp** [comment]
> we have a unit test that request size does not change

not part of this PR , I guess ? If we have one, how did we manage to break it earlier ?

**Comment by bureddy** [comment]
@shamisp Issue was detected in my WIP PR.  But, i reworked it to make request size not change.
I think it might also possible that with current alignment and some user defined request size,  there might be a request object with 256B in the mpool.

@yosefe how about changing UCS_PTR_STATUS() definition also to check for NULL and return UCX_OK if it is null. this should make current codes compatible, right?

**Comment by yosefe** [comment]
@bureddy we can add a check in UCS_PTR_STATUS() to return INPROGRESS (for example) if this is an actual pointer. it would add extra branch, but for correct codes this would be slowpath anyway (since checking the status should be done after checking UCS_PTR_IS_ERR)

**Comment by shamisp** [comment]
I don't think branch in this case is a such big deal. Set likely() to help branch predictor.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12288/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/b20f3195f90a4c8bb395c4ecf84fbe2510f02e4e/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/78168d04745770523ae66dde5844a41da3d7f246/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/0a35e3d94e227c9b9692e3976c751ab6921f4667/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/d8252610a7af1857e3cbc52f4c094892b1ddd4f3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/bec47d859bc3517e6e4884a79d845e1437510b37/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/07115aa7267a915219c6b8b50175ffa461646ddd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/4213275807c447acf137e38a5d5a27ceece8eebb/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/c50f3e7c5784c85f87de95e7efc615f2a277f6f9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/0e27727ddfddf92fe438eb80028c21de480500fc/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/a2c53661e45f380f158edcd7b7efd8194ae011ea/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/d1b18d3e918c8097f4cac6d0e4b6c11c485e17e2/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/3b426370be7acc759d9e5708177984c268400926/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/20fdb7395a3499c42871d4735b6e148d8fed6489/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/8affa993d1adbdb7f2f6ee8a4394db71df226e3e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/789d7a8c9db7b393ec0e02010cd1d6b6a3a4bc31/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/de32e1495eb6d7fe811fc6811dca92007b60f304/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/d4f0581a630e6ca4423cf5bfe888230436caef73/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/5f896209c0005a79087de42ea3d5316f16e0ad8b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/c52d0301a6add284e84f9f43327627f2de9c4707/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/d5f2b6036d9c0ff1c328d1708e8e5d6abd7fd1c2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/26d0fb4087807efa66289db7e83f32c4f45aaaea/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/c73c7e290ebae3b3d9e0a395ec7565edfe1c824f/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/a87f7ef0d192c1afb214bc85621e293daa717d2f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/ef41b39fca33c8e59f91a5c4c4928b9db791aab2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/f439afcdb70bc048c6e8b3f7df3e1f1ff820a2c3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/9aeea22d7897f90a1fc6b9ee93b1e61562ec8e68/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/35ede95eb688b75a54e6444df74d7ded6fee4f42/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/43fc463fefd9aa725978fbb9884b3ce0e90966c7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d53adf6f81cea34e4c61069d669a18ed/raw/2075e9f7f1d82e99d9256bd357ce56da94aae17b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@shamisp @bureddy i've added check to UCS_PTR_STATUS and a unit test for it, are we good now?

**Comment by shamisp** [comment]
👍 Shell we issue an email on the list asking user to review/update their codes ?

**Comment by yosefe** [comment]
@shamisp with this PR the codes do not have to be updated

**Pull request merged**
