### PR TITLE
Fix hang in dc flush

### LINKED ISSUE #1338: hang in dcx/test_ucp_tag_xfer.iov_exp_truncated/0
when dc endpoint is waiting for pure grant, it cannot be flushed because goes into infinite loop of flush/pending_add. if checking the waiting-for-grant flag in pending_add, still does not work because rx progress does not process pending queue if the ep cwnd>0 (to avoid reordering).
looks the the solution would be to destroy the ep which is waiting for grant, but not release its memory, and keep it in "ghost buster" mode. if the iface is destroyed, all ghost-busters could be destroyed because the grants to the iface would be dropped anyway.

another fix which has to got to UCP layer is:
```
diff --git a/src/ucp/core/ucp_ep.c b/src/ucp/core/ucp_ep.c
index 215ff0c..a716e10 100644
--- a/src/ucp/core/ucp_ep.c
+++ b/src/ucp/core/ucp_ep.c
@@ -276,11 +276,11 @@ static void ucp_ep_flush_progress(ucp_request_t *req)
                 break;
             }
 
-            req->send.lane = lane;
             status = uct_ep_pending_add(uct_ep, &req->send.uct);
             ucs_trace("adding pending flush on ep %p lane[%d]: %s", ep, lane,
                       ucs_status_string(status));
             if (status == UCS_OK) {
+                req->send.lane         = lane;
                 req->send.flush.lanes &= ~UCS_BIT(lane);
             } else if (status != UCS_ERR_BUSY) {
                 ucp_ep_flush_error(req, status);
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1338

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1010/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2973/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1012/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2976/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1013/ for details.

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2980/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@brminich pls take a look

**Comment by brminich** [comment]
:+1:

**Pull request merged**
