### PR TITLE
RC/MLX5: Fix counting available TX WQEs.

### PR DESCRIPTION
**Pull request by yosefe**
Same issue as in #387, but for RC.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/937/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/352/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls review

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
:+1:

**Comment by shamisp** [comment]
autobot build

**Pull request merged**
