### PR TITLE
NEWS: Backport v1.12.0 news to master

### PR DESCRIPTION
**Pull request by brminich**
## What
Port UCX v1.12.0 news to the master  branch

### CODE REVIEW

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
Any Author list changes ?

**Comment by shamisp** [comment]
> > Any Author list changes ?
> 
> not sure. How does one check it typically?

Documented here under N4 https://github.com/openucx/ucx/wiki/Release-process

**Comment by brminich** [comment]
> > > Any Author list changes ?
> > 
> > 
> > not sure. How does one check it typically?
> 
> Documented here under N4 https://github.com/openucx/ucx/wiki/Release-process

i think we will have to update  instruction N4, as currently it produces not really useful output. 
btw, do you think we need to update authors here? It is just a port of latest release news to master. I'd suggest to update author list for the next release

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
> > > > Any Author list changes ?
> > > 
> > > 
> > > not sure. How does one check it typically?
> > 
> > 
> > Documented here under N4 https://github.com/openucx/ucx/wiki/Release-process
> 
> i think we will have to update instruction N4, as currently it produces not really useful output. btw, do you think we need to update authors here? It is just a port of latest release news to master. I'd suggest to update author list for the next release

I checked and for me it works as expected. It does not produce exact output as authors but it is close enough to do the comparison

**Comment by brminich** [comment]
> > > > > Any Author list changes ?
> > > > 
> > > > 
> > > > not sure. How does one check it typically?
> > > 
> > > 
> > > Documented here under N4 https://github.com/openucx/ucx/wiki/Release-process
> > 
> > 
> > i think we will have to update instruction N4, as currently it produces not really useful output. btw, do you think we need to update authors here? It is just a port of latest release news to master. I'd suggest to update author list for the next release
> 
> I checked and for me it works as expected. It does not produce exact output as authors but it is close enough to do the comparison

hm, it shows many lines for every author - (different emails, names, sshs), which makes it hard to compare with the original file

**Comment by shamisp** [comment]
@brminich - yep. This is because people have been using multiple name signatures, emails, etc. As a result those appear as a different authors. This is why I ended up using vimdiff and manual review of the authors file. It is not as bad as it looks.

**Pull request merged**
