### PR TITLE
UCP: Fixing typo

### PR DESCRIPTION
**Pull request by shamisp**
access_mem_type -> access_mem_types

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
Fixing #5801

**Comment by shamisp** [comment]
ok to test

**Comment by bureddy** [comment]
duplicate to https://github.com/openucx/ucx/pull/5797

**Comment by shamisp** [comment]
Thanks @bureddy

**Pull request closed without merging**
