### PR TITLE
UCT/MM: Fix error message for UCT_MM_MAX_SHORT

### PR DESCRIPTION
**Pull request by evgeny-leksikov**

### CODE REVIEW

**Comment by shamisp** [comment]
This is a bug. Should be ported to v1.2 once merged

**Comment by yosefe** [comment]
it's a bugfix, but doesn't seem critical as it only fixes the error message

**Comment by shamisp** [comment]
ok

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3748/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1807/ for details.

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1817/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3757/ for details (Mellanox internal link).

**Pull request merged**
