### PR TITLE
DOXYGEN: Updates for documentation

### PR DESCRIPTION
**Pull request by shamisp**
* Updating documentation for UCP API
* Improving HTML layout (pdf is still broken)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1033/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/460/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/461/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yosefe - can u check the failure pls.

**Comment by yosefe** [comment]
reason is #434

**Comment by shamisp** [comment]
then I will merge in, ok ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/462/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
It is passing now !

**Pull request merged**
