### PR TITLE
UCS/RCACHE/TEST: Fix 'status' variable override in rcache error flow

### LINKED ISSUE #4016: UCX  WARN  : destroying inuse region, and heap corruption
I am porting an application to use UCP active messages, and I am getting 3 messages from UCX when the application terminates. Each rank in the application gets these messages.
```
[1,17]<stdout>:[1565098290.648134] [c712f6n01:94404:0]          async.c:634  UCX  WARN  async handler table is not empty during exit (contains 27 elems)
[1,17]<stdout>:[1565098290.648163] [c712f6n01:94404:0]         thread.c:408  UCX  WARN  async thread still running (use count 27)
[1,17]<stdout>:[1565098290.648168] [c712f6n01:94404:0]         thread.c:408  UCX  WARN  async thread still running (use count 27)
```
I am terminating the application with a call to ucp_cleanup. This issue looks similar to https://github.com/openucx/ucx/issues/1098 , but that issue has been resolved.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #4016
Issue introduced by #3939

This PR also adds event checks to UCM, so the rcache unit test will fail to create the rcache.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11766/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/4ea9a8f333639b0d611f3c7da91ab6c99d155bb9/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/293e57f0f2ba9e4f94cdfa8c751f036c078da7d5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/ca6c4704d39c37f46770435fd1d24d6b7aa4dfa4/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/681bb40b51316cf7b7a716acc7194b4045f55d2e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/7af339f92bb86ad3a8da443d18355102a8991930/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/dd222a748f0906e57bbe0467662bff653b66e43b/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/4cc5d5053fae2dc56d716387ea0531488e364764/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/2af9b14ca088796d94e867e592557fd43cf38318/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/76521d39900bf853f666128419a5834790fad91c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/fc8c48c65beda1ecfd4c138182c01b486ed07265/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/3fafcfd19fec7647c3bd954d0566d28d6925eaca/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/f0258c71e48dd1cb6873c98446e403c3c0e4e7c9/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/62dc67594c01731d68e300809a5c99354e9f7c02/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/4abe79a3b0891014d60843781595f53f9376314a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/a5f82d6446f310199391ade4b095111ead6c712b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/b79908a5d65b35778ce2eccea3da6c9e6f67afe9/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/a168ad0507b78d423139dcd448cfa11c2986db63/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/8459559291f547005262967170eb393211b8a46b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/96268e794dd4fcd69eb2e189e002a131d01fc0af/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/5cb08704270f08e0c52ba505ecd63685c8fa9d3b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/d09e20b11d25620915af06c6a28f3aabb1e2c1c4/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/a3b4ecf4ad6ac4a3e0f0c864585a01987f29f015/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/0be151ddd7f2386bc0285c7d62f5bcb9b0b7ce40/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/ae8f12047692945e36b275ada033e5fc57e20083/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/08fdfb0d87feebec66d07fe34af1a0dc75d6e516/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/bbded939227252ea45e7293a62922840cf470ff6/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/92f22ebe54551978998fdfbe435c53468eccbe1f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/229e08f7defb02d0809335af0cde3a1e7386ed0b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0f44b95f7759ee318f238df1569a8a73/raw/b471fd07d78ec3967b5e343a866b7f35a3769214/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@hoopoepg @hiroyuki-sato can you pls take a look?

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
