### PR TITLE
NEWS: News file update for RC2

### PR DESCRIPTION
**Pull request by shamisp**
News update before RC2

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe We don't have to wait for full CI cycle. If you are ok, let's merge and do RC today.

**Comment by shamisp** [comment]
ok to test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 9 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Apr-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/433664082471fd29d7e7c7e6408d59bbb79bb8d2/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/29b1e42ffd7e71a9a82b8fa51307485462d60f93/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/3e22a41524ef2f29cfda794428b015ca4fb87aa0/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/3d7cacce3264951cfc67fc3b3e67baf3dc82df69/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/c1bf5cd42906e35edf34deb4233cf9dcec5ae22d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/d7147f9f98033e8111ffa4ca7664e0ee406dafa0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/cbca38891ef990830e56cd2e3f7ab4b091f0d352/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/5fc08099365df4ad4fae69e196c9e092d965bb0b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ea892764f5d7a624a0422bc7bc80c876/raw/51d5a5d243e276852c38a9a0aa6305531b956c64/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 9 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Apr-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/84c87198590529d8a917f1ba7a9ba35e66ded3fd/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/3a857e0d473ad651c9728884566952e8edf06cae/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/151731bfe03d1f523fe76ddb7fa831f945a8a63e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/ff0339147bcc5b72b764f70ca8883b6c4ee55ff9/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/b2f88ed06babd56b99210e32fca9ecdbe28903ed/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/3f488c1b45945623351f50891c592a3ec697e81c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/8aaefe46254fe5361a5eeaaa753c476077e6100c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/02ab122f5207abc801a1fc498a68762d5c41aef6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70ff621abfbe923f97c7afb878741e04/raw/41bf267e6f31044dc62460f49648f1270c693bf2/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by shamisp** [comment]
@yosefe good to go with RC2

**Pull request merged**
