### PR TITLE
UCT/RDMACM: Set iface_is_reachable to ucs_empty_function_return_zero

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10082/ for details (Mellanox internal link).

**Comment by alinask** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10085/ for details (Mellanox internal link).

**Comment by alinask** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10086/ for details (Mellanox internal link).

**Comment by alinask** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10120/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe let's merge?

**Pull request merged**
