### PR TITLE
DOC/FAQ: Use HTML markup for static build table

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Fix static build section not rendered correctly in the read-the-docs site

### CODE REVIEW

**Comment by shamisp** [comment]
It does not very aligned either https://openucx--8224.org.readthedocs.build/en/8224/faq.html

**Comment by yosefe** [comment]
> It does not very aligned either https://openucx--8224.org.readthedocs.build/en/8224/faq.html

I want to convert the whole file to RST which is a more robust format. But first would like to fix the table for static build users, currently it's totally unreadable.

**Comment by shamisp** [comment]
Maybe just render it as an PNG 🤷

**Comment by yosefe** [comment]
> Maybe just render it as an PNG 🤷
> […](#)

Would like to support copy/paste

**Comment by shamisp** [comment]
Good point. Also it is good for search.

**Comment by yosefe** [comment]
@shamisp added space after the table

**Review by shamisp — APPROVED** [review]

**Pull request merged**
