### PR TITLE
GTEST: fix test_ucp_stream_many2one.drop_data

### LINKED ISSUE #2746: failure on tcp/test_ucp_stream_many2one.drop_data/0
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7351/label=hpc-arm-cavium-jenkins,worker=0/consoleFull#-111310395944550c5d-247a-4f9d-bad5-5b93d2b6e2ac

```
10:22:47 [----------] 2 tests from tcp/test_ucp_stream_many2one
10:22:47 [ RUN      ] tcp/test_ucp_stream_many2one.send_recv_nb_iov/0
10:22:47 [       OK ] tcp/test_ucp_stream_many2one.send_recv_nb_iov/0 (159 ms)
10:22:47 [ RUN      ] tcp/test_ucp_stream_many2one.drop_data/0
10:22:47 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-cavium-jenkins/worker/0/contrib/../test/gtest/ucp/test_ucp_stream.cc:712: Failure
10:22:47 Value of: others.size()
10:22:47   Actual: 0
10:22:47 Expected: m_nsenders - 1
10:22:47 Which is: 2
10:22:47 
[  FAILED  ] tcp/test_ucp_stream_many2one.drop_data/0, where GetParam() = tcp (96 ms)
10:22:47 [----------] 2 tests from tcp/test_ucp_stream_many2one (255 ms total)
```

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
Fixes #2746

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7989/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7994/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7997/ for details (Mellanox internal link).

**Pull request merged**
