### PR TITLE
AZP: align buildlib/ with master - v1.8.x

### PR DESCRIPTION
**Pull request by amaslenn**
## What
Sync AZP configs with the master branch.

Related PRs: https://github.com/openucx/ucx/pull/4997 and https://github.com/openucx/ucx/pull/4989

### CODE REVIEW

**Comment by yosefe** [comment]
@Artemy-Mellanox can you pls pick both valgrind suppression fixes to v1.8.x?

**Comment by amaslenn** [comment]
@yosefe looks like Valgrind PRs should be ported to v1.8.x.

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
