### PR TITLE
UCS/DEBUG: Demangle C++ symbols.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1145/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1752/ for details.

**Comment by shamisp** [comment]
:+1:

**Comment by MattBBaker** [comment]
:+1:

**Comment by yosefe** [comment]
got a link issue on ubuntu12 - checking

**Comment by yosefe** [comment]
Looks like i've hit this: https://bugs.launchpad.net/ubuntu/+source/binutils/+bug/50512
Will remove binutils-dev on the build machine

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1152/ for details (Mellanox internal link).

**Pull request merged**
