### PR TITLE
TOOLS/PERFTEST: Fix bug when using socket rte

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Removes changes introduced in #3799

## Why ?

They are unneeded and can be removed

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11162/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 8 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/d7210980fd82f32b4180f33f825951e8bdf32707/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/54d1ccd325d5c89a47bd39977f73c7b1ef42aacd/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/3bfcfaecba8c2abf38d0d8b404db1db250228ecf/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/1fe0bd3883b125e359a7952238d7e327053afc8e/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/19318dbf03701acf7a4391fc5a276d62c59e2c5e/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/ecfa778d759b6d9a969429df29c01b66ab45a301/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/5ec3977dc85a42b74206e2f9cb76987e3e5b4764/hpc-test-node-new_W3) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/f1ec91667c4ffb032283fb18a6829aa6fdd52fe8/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/28808839928c63178f886e5b28b7060ebbd50cb0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/e413583e6caafb5f2e7c42e6b3e156b770beb12c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/b0302bf252f8c9b3b5a7dab7247599d6ee702667/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/dd28635cb4340c7be90bcd3e4130fb4d48de507f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/1b78f9029ec211a41dbc740b7af12828af9d0898/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/89e94b70341d4dc1e79205f185b803a55e5b19db/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/c26d5035001bb4063623e7f21af3f56c2f736f88/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/c79d60dc1fc6a966e082133c368f05a8371042cd/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/fe9563cf87f41584a6672c4fe8ef2b15d5fcf11c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/1c1d821920fc94c9869d28bcbc2f6af3602776ab/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/7536552848501f58153c751904ce0c538b7b8752/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/3a32cf72b035a0100110f97482550a4194c142ee/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/4f09ba9a456dcf0f6d0ae1480f573a0cfa2f5ac6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/4e7f1371633f4d05e90c06b941b1df23babd1619/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/7a3d33f1547c5a26a87b471937c30b1eaaecde00/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/f499c9ce9b917c6e3bca21146e9c4e7f9b5df63b/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/e991742a20294f6067aa28d2bc57dc99f1a396ee/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/4d83bd9f365a006b736afd5afca7507b737faaae/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/e4ca953e7198b684b7b148cffd52e342d126bd7e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/a20ba558ec223cde2878c057e151f7380ea6f2d7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/68ae3dd19efaea4c2fde65ab837166b3/raw/9a14236f0d040871504e09d8158bba93efa4e27d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by dmitrygladkov** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11165/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/ecbf9b9d5827f46f8483077bf147d6c8ea1c8d8c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/215ebed6aaa3f5b06802dbb12b97b3ce80acf706/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/0a3732604a9559cdcec2bdd2e9efe884620b655e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/b94bad09954201268fb7f57314c94bee56e4c940/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/6a2c04dc345770024d13e9124e5b708c9e0ab573/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/df98042f2376dee2c397ee4c5e8ba1702a027f44/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/515a740a0fcd20e18dc5495c8bc4de3df1c4736f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/2c74f44521e2649cf187085c034bf23fdeb1e30e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/f5131be230731297801cbcc995ec35a818126be8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/dfe62f4b9138c77dbb6f094a41cbbc180365bd4f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/0ece60920dddee08e6627c1ce325eefad8557138/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/62e2c3fd6372ae7c57b6603a92f39af290e06cec/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/432acafee5df0067b8faca97e8f4b0d86f33e1e3/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/cd3b92d9672cfbca9252a729cda19ea0e0c35aa8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/38049a5f42ef98010a6e4627b2eb9c996db90e9b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/f98d36f6c6314263f01d31aabe3c3a31deeb2626/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/add41d4667aaf4270a2aff36fa1c44d5493abe42/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/34c24e427098be0f80fa58c7f99d7ca2eccf3be9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/6012a6af0ad7ff3e525711d0872ef78d00b132ba/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/bed2c0e0e449a7f006831c7d52864b066938e60b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/c026a36f6f4666d3aa55d4ec0843b3a96735739f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/af5b698e5ea00ee828e607afde80912915ddf831/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/50170c79ceaeed6dcdf28b265ec619c52900ebac/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/f96ab8fd73b96e739912c43ed6de4ff4d58f952c/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/411d9b8e9f3981078cb545ad15995147120abc97/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/67c07d83eafc87797c885c313b071e8d30f55980/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/b836715b4a7518ea767223f86c42054d08579378/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/987fa7b7f2342dedb201cf44e8ef35478fe976b1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/82a854c159770f14d2e496b70a34c377/raw/7a854c393a9381a814b75b3e23a17d55b0d92511/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe ok to merge?

**Pull request merged**
