### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by zasdfgbnm**
These files are generated files when building.

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
@yosefe - seems like @zasdfgbnm part of Nvidia org. @zasdfgbnm can you please confirm ?

**Comment by yosefe** [comment]
@zasdfgbnm can you please use NVIDIA email address for the commit (instead of gmail)?

**Comment by zasdfgbnm** [comment]
Yes, I work for NVIDIA. I will create a new account with my nv email.

**Comment by zasdfgbnm** [comment]
See https://github.com/openucx/ucx/pull/7017

**Pull request closed without merging**
