### PR TITLE
CONFIG: Removing zlib dependency

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1264/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3211/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
on sles11-sp2:
```
00:55:45 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/ucs/.libs/libucs.so: undefined reference to `inflateReset'
00:55:45 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/ucs/.libs/libucs.so: undefined reference to `inflateEnd'
00:55:45 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/ucs/.libs/libucs.so: undefined reference to `compress'
00:55:45 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/ucs/.libs/libucs.so: undefined reference to `inflate'
00:55:45 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/ucs/.libs/libucs.so: undefined reference to `compressBound'
00:55:45 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/ucs/.libs/libucs.so: undefined reference to `inflateInit_'
00:55:45 collect2: ld returned 1 exit status
00:55:45 make[3]: *** [ucx_info] Error 1
00:55:45 make[3]: Leaving directory `/scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/tools/info'
00:55:45 make[2]: *** [all] Error 2
00:55:45 make[2]: Leaving directory `/scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test/src/tools/info'
00:55:45 make[1]: *** [all-recursive] Error 1
00:55:45 make[1]: Leaving directory `/scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp2-x86-64/worker/0/build-test'
00:55:45 
make: *** [all] Error 2
```

Looks like linking with zlib is needed when binutils installs static libraries (e.g libbfd.a)

**Comment by shamisp** [comment]
Add test for linking libbfd.a and check if it broken. Something like AC_FUNC_*

**Comment by shamisp** [comment]
@yosefe - follow up on the discussion.
We actually have this check:
https://github.com/openucx/ucx/blob/master/config/m4/ucs.m4#L45

Can you please check how exactly your SuSE system (with only static version of the library) pass the test ?

**Comment by yosefe** [comment]
maybe checking bfd_init is not enough because it's not calling zlib. need to check a function in bfd which actually uses zlib.

**Comment by shamisp** [comment]
Yeah...most likely

**Comment by yosefe** [comment]
@shamisp looks good now

**Comment by shamisp** [comment]
Awesome, let's wait it to complete

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1378/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3316/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp does it fix #1382 ?

**Comment by shamisp** [comment]
This is was the goal. Fixing 1382.

**Pull request merged**
