### PR TITLE
TOOLS/INFO: Fix CPU model info for aarch64

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
Thanks @paklui for catching this

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8063/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8068/ for details (Mellanox internal link).

**Comment by brminich** [comment]
timeout

bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8071/ for details (Mellanox internal link).

**Pull request merged**
