### PR TITLE
UCT/API: Remove deprecated API for querying UCT memory domains

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
We have to remove this or just move to deprivation mode but still support ?
Can you please remind the alternative that we have provided

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10299/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp it's replaced by uct_query_components()+uct_component_query()
since UCT API is not backward compatible yet (and new API is future-compatible because it has field_mask), and btl/uct is going to require a specific UCX API version now, i think it's better to remove it now.

**Comment by shamisp** [comment]
Will it break OMPI UCT BTL ? Shell we bounce by @hjelmn ?

**Comment by hjelmn** [comment]
Yes it will. I plan to update the BTL next week for this change. Is this targeted for v1.7?

**Comment by yosefe** [comment]
@hjelmn yes, it's targeted for v1.7

**Comment by hjelmn** [comment]
@yosefe Ok, will make the changes to btl/uct later this week.

**Comment by shamisp** [comment]
👍

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10358/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10374/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10383/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10389/ for details (Mellanox internal link).

**Pull request merged**
