### PR TITLE
CONFIGURE: bump the ucx version to v1.3.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1668/ for details.

**Comment by alinask** [comment]
@yosefe please review.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3587/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by shamisp** [comment]
Do we need to update doxygen ? I don't remember where from it is getting the version.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3591/ for details (Mellanox internal link).

**Comment by alinask** [comment]
Looks like it is already updated after this change.
I attached a screenshot from the doxygen page, with the commit in this PR.
ucx-doxygen-version-bump

**Comment by yosefe** [comment]
@alinask need to also PR updating to v1.2 on v1.2 branch

**Comment by alinask** [comment]
@shamisp Can we merge?

**Comment by shamisp** [comment]
👍

**Pull request merged**
