### PR TITLE
UCS/SYS: Add uid header file

### PR DESCRIPTION
**Pull request by lappazos**
## What
Create new header uid.h , add it to installed list, and move ucs_iface_get_system_id from sys.h to uid.h 

## Why ?
Expose ucs_iface_get_system_id to UCS public API

## How ?
Move method between headers

### CODE REVIEW

**Comment by lappazos** [comment]
If possible, this change will be pushed to v1.11.1 soon

**Comment by lappazos** [comment]
@yosefe please add reviewers

**Review by yosefe — APPROVED** [review]
pls squash without rebase

**Comment by lappazos** [comment]
> pls squash without rebase

@yosefe I think that because you asked not to rebase, the PR include 2 other commits that aren't mine

**Review by yosefe — APPROVED** [review]

**Pull request merged**
