### PR TITLE
UCP/UCT/IB: Fix thread mode in UCT - v1.4.x

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7934/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7943/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:mlx:retest

**Comment by shamisp** [comment]
```14:20:23 [----------] 2 tests from dc/test_ucp_tag_offload_stats
14:20:23 [ RUN      ] dc/test_ucp_tag_offload_stats.sw_rndv/0
14:20:40 [1539343240.049747] [hpc-test-node3:64125:0]       dc_verbs.c:610  UCX  ERROR Send completion with error on qp 0x3868a: transport retry counter exceeded syndrome 0x81
16:53:49 
```

@yosefe - this does not look right ...

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7948/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7951/ for details (Mellanox internal link).

**Pull request merged**
