### PR TITLE
CONFIG: Huawei Hi1620 CPU detection

### PR DESCRIPTION
**Pull request by alex--m**
Note: pending signature of a contibutor agreement... :(

### CODE REVIEW

**Comment by yosefe** [comment]
bot:bgate:retest

**Comment by shamisp** [comment]
From technical perspective it looks fine.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9780/ for details (Mellanox internal link).

**Comment by alex--m** [comment]
As discussed in the mailing-list, I'm closing this and re-submitting as a "draft PR".

**Pull request closed without merging**
