### PR TITLE
EXAMPLE: fixed missing initialization of EP

### PR DESCRIPTION
**Pull request by hoopoepg**
fixes https://github.com/openucx/ucx/issues/2861

### CODE REVIEW

**Comment by yosefe** [comment]
@hoopoepg can you pls add uct_hellow_world tcp testing to jenkins?

**Comment by hoopoepg** [comment]
@yosefe it will require changes in build infrastructure (for now there is hack for examples build), will create additional PR

**Comment by yosefe** [comment]
today we run uct_hello_world over ib, can't we run it same way over tcp?

**Comment by hoopoepg** [comment]
@yosefe right, there is a hack to build examples... ok, updated jenkins to run uct hello world over tcp
I would like to add build of examples into regular build, but later...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7666/ for details (Mellanox internal link).

**Pull request merged**
