### PR TITLE
API/UCT: fix doc - uct_iface_config_read to uct_md_iface_config_read.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4671/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe @shamisp @bbenton Please review.

**Comment by bbenton** [comment]
:+1: for this doc/API fix.

However, there is a problem in a related function. uct_md_config_read() is assigned to a non-existent group, RESOURCE, rather than UCT_RESOURCE.  The result is that uct_md_config_read() is not documented in the API.

**Comment by shamisp** [comment]
@bbenton - good catch.

**Comment by shamisp** [comment]
👍

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4682/ for details (Mellanox internal link).

**Comment by bbenton** [comment]
:+1: for uct_md_config_read doc fix

**Comment by alinask** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4689/ for details (Mellanox internal link).

**Pull request merged**
