### PR TITLE
UCS: Using "stronger" barrier

### PR DESCRIPTION
**Pull request by shamisp**
Fix for #780.  The issue was discovered using test_callbackq.threads unit test

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe - please take a look.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1296/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1918/ for details.

**Comment by shamisp** [comment]
I'm fairly positive that the failure is unrelated.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1919/ for details.

**Comment by yosefe** [comment]
Looks good - but i'm not familiar enough with ARM architecture to verify. You can merge at your own risk :)

**Pull request merged**
