### PR TITLE
MM: Adding an assert and using an existing function.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe @bureddy Please take a look.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7061/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7065/ for details (Mellanox internal link).

**Comment by alinask** [comment]
@yosefe cherry-pick this to v1.3?
the failure in jenkins here is due to bad VMs.

**Comment by yosefe** [comment]
@alinask yes pls cherry pick

**Pull request merged**
