### PR TITLE
AZP: edit existing release if exist - v1.7.x

### PR DESCRIPTION
**Pull request by amaslenn**
(cherry picked from commit ab86fb41a12a359489c02f5b89bf4707b68e6594)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12977/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 08-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/c47779d6d7313334ad2b5a79c8fe5bf372213963/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/e57c3e53b77b5bcdfbebf3d1368e11b274ea0aed/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/44e45db692c1b91b30600a4dae97a98acfe02463/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/3a15d10f9b6e05c605d9f36ea024469604ee9a03/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/440dec53e5d69169db297e4ca31b57d67ead2b51/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/51529b7ce08fff97a7cb92bd75fdc8ffb0145d45/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/c7f14ac4796a0a779571ebeab4ba89d611bf0628/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/cbb10245199e0abca6327c9e4216619c9cfe41a3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/bbfac5054ff356be76757f84f71f4480a5625ffa/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/eefb36fdfeb8abf778ceeeed724f8d923edac5cf/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/dc23fdcb6035b8e6e26d351b2718ce5fa83c2eab/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/99e84143e3e98cb8e9291f471e0b9bf2b72f4f7a/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/44155025ccac925ec454067f374aef4603eed91a/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/0ad77ec85401886c5b76b09d69549dc9be45cd2e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/b423e4249608abcbc7df9c78a990aa5fdcc9ff24/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/b7bd2b1cf036ed8598c36ecae5834813f3bc4a7f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/30875cd2b102fff3abe15445b5c5b0a2aef44e6e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/8d77f8374cf3e7f33e185c1c4a1ce75face54c1d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/3d4370246b249fbdb8002e46c9cb9fd61b449abe/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/933add735a299c6b70f97ba8a9b2fa06e24f90d7/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/afc9825d1563cfda4b239b1123ad3315033f0769/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/eaefc7abf0f786be24044c68c9fb71f201da9eb7/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/3e12d64818c27eba03964a3b863e6a78657e81ca/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/77060b02d96eda22bad0d1c4df77b84180ea2830/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/dac04618d1ea4089ed480528abc0081ba19204ea/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/2eeb3bacd9a5cf723b6bb6e97eeb236c9e031eea/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/422c0115ed84aae37049edfc280e83f0c3f598d6/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/19a4f2aa07086b9dc0f70cd6c4b996de454e51e4/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d8f0d93c54bb15525b9a5a52577e109/raw/b1382e7157bec2389d3d22c1b89d3b4921dec3cc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
git fetch error
bot:pipe:retest

**Pull request merged**
