### PR TITLE
UCT/API: Expose device address

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
@MattBBaker @hppritcha  please take a look / test.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/980/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1587/ for details.

**Comment by MattBBaker** [comment]
Compiles fine and runs as expected on titan.

**Comment by hppritcha** [comment]
This looks okay.  builds on a cle 5.2up04 system.

**Comment by shamisp** [comment]
@hppritcha - it would be nice to hook it up to your jenkins 
thanks for testing

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/983/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1590/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
