### PR TITLE
TEST: Minor fixes in tests for RoCE fabric.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2651/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/52/ for details.

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2007/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev pls take a look

**Comment by yosefe** [comment]
@alinask pls take a look

**Comment by alinask** [comment]
:+1:

**Pull request merged**
