### PR TITLE
FIX: fix license in several files

### PR DESCRIPTION
**Pull request by amaslenn**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4891/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
adding @bbenton .

**Comment by bbenton** [comment]
:+1:

**Comment by shamisp** [comment]
can you please create a PR for master ?

**Comment by amaslenn** [comment]
Sure: https://github.com/openucx/ucx/pull/1939

**Pull request merged**
