### PR TITLE
KNEM: Addressing Coverity CID 128530

### PR DESCRIPTION
**Pull request by shamisp**
See https://scan8.coverity.com/reports.htm#v27370/p11529/fileInstanceId =7867043&defectInstanceId=2805442&mergedDefectId=128530

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe please review

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/846/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/272/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
@yosefe seems like mellanox jenkins does not feel good.

**Comment by yosefe** [comment]
:+1: testing failed because of #349

**Pull request merged**
