### PR TITLE
UCT: Fix HW TM unexpected counting

### PR DESCRIPTION
**Pull request by alex-mikheev**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3602/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
v1.2 ?

**Comment by yosefe** [comment]
this flow is not active on v1.2

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3603/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3611/ for details (Mellanox internal link).

**Pull request merged**
