### PR TITLE
UCT/CUDA_IPC: make cuda-ipc cache global - v1.10.x

### PR DESCRIPTION
**Pull request by Akshay-Venkatesh**
## What

Backport of #5815 and #6360

### CODE REVIEW

**Comment by Akshay-Venkatesh** [comment]
cc @yosefe @pentschev

**Comment by yosefe** [comment]
ok to test

**Comment by yosefe** [comment]
@Akshay-Venkatesh was this clean cherry pick?

**Comment by Akshay-Venkatesh** [comment]
> 
> 
> @Akshay-Venkatesh was this clean cherry pick?

@yosefe I took https://github.com/openucx/ucx/pull/5815.diff and https://github.com/openucx/ucx/pull/6360.diff and patched in that order as all changes were in uct/cuda/cuda_ipc. I didn't see any issues in build/tests.

**Review by pentschev — APPROVED** [review]
LGTM, I just tested this and didn't experience any regressions as well. Thanks @Akshay-Venkatesh !

**Review by yosefe — APPROVED** [review]

**Pull request merged**
