### PR TITLE
UCT/TCP: Don't allow connecting loopback with other devices [v1.11.x]

### PR DESCRIPTION
**Pull request by dmitrygx**
ported #7600 to v1.11.x branch

### CODE REVIEW

**Comment by yosefe** [comment]
fails because need to port #7359 to v1.11.x

**Comment by dmitrygx** [comment]
> fails because need to port #7359 to v1.11.x

let's port them together in a single PR?

**Comment by yosefe** [comment]
> let's port them together in a single PR?

can you pls cherry pick it as a separate PR?

**Comment by dmitrygx** [comment]
> > let's port them together in a single PR?
> 
> can you pls cherry pick it as a separate PR?

done - #7602

**Pull request closed without merging**
