### PR TITLE
UCT/IB: Add configuration for Hop Limit / RoCEv2 TTL

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7467/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7480/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7493/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@evgeny-leksikov can you pls take a look?

**Comment by evgeny-leksikov** [comment]
👍

**Pull request merged**
