### PR TITLE
UCS/DEBUG: Check that signal hash is initialized before using it

### LINKED ISSUE #3676: UCX programs hang when compiled with -fsanitize=address
git master @ 462e0240e544678a9d28bf48a59230a513767da4

When compiled with `-fsanitize=address`, programs linked with UCX hang on start, even a vanilla `main() { return 0; }` that doesn't even call UCX

Works with 1.x releases

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #3676
@tonycurtis

### CODE REVIEW

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10623/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10626/ for details (Mellanox internal link).

**Pull request merged**
