### PR TITLE
UCP: Fix configuration which disabled am_short path.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
I guess this is for hw that does not support inline ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1764/ for details.

**Comment by yosefe** [comment]
Nope, just a bug introduced by multi transport change.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1157/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
+1

**Pull request merged**
