### PR TITLE
UCS/UCM/UCT/GTEST: Coverity errors fix

### PR DESCRIPTION
**Pull request by brminich**
Fix coverity errors appeared after migrating to version 8.5

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2301/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1621/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
failure is #922

**Comment by yosefe** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1622/ for details (Mellanox internal link).

**Pull request merged**
