### PR TITLE
IB/RC: Register progress function only if ep exists.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by alinask** [comment]
Shouldn't all the ucts register the progress function only if ep exists?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1134/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask this can be done only on p2p transports for now (see commit message). In order to do it on all transports, need to use events. This will be done in next commits.

**Comment by shamisp** [comment]
:+1:

**Comment by shamisp** [comment]
Probably we have to do the same for ugni. Adding @MattBBaker

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1135/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1738/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1739/ for details.

**Pull request merged**
