### PR TITLE
UCP/TYPO: fixed typos in UCP_STREAM_RECV_FLAG_WAITALL description

### PR DESCRIPTION
**Pull request by hoopoepg**
## What
- fixed typos

## Why ?
- wrong words are used

## How ?
- fixed comments

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/9b92b15a54e347df2e103b06b39b7140b9f34687/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/0759763ed019369f3e30ca6df287752b8500ad76/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/f04b18051cf5f34109cdac791777b2d97e1d4978/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/48ed77e94eb73e49fa8aaf39ea933baa0ec3ff67/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/d216649b439ccd8a302df53d316b0f5bb9529f7d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/9a6ca1cce503875bfa90a7c55cf2fc4c91b44c4e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/105aadcbad03a0a63cfe3ed917286f91ee746a82/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/7e3059e4356870112636ab18c08f71df85b39928/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/8fa9c8c0354096ffaf7644c10220971b1329230d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/dc37a3f7bcc48ce2edf0a12c803430429a3f9679/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/35790aef639a9107cba57cc428fdcd5fffd5db39/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/17dc2eb8386a5d641040980b8489c56cbba923cc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/42805ff14fd35b85086a061805423a0abc30fce8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/5f01f60200f9cf2f2594808782c1e31c17406eb1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/2d1cc97688c02caa8fb768b6596d030810b35aee/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/6264be784b5d9cc9d2b838c8ca3ddecb1e30b956/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/ad37205fa3d5774d766101185d7b90ab35b6173a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/fffaf2ea9a80937a2d6c8120b0a76a6aa9433a3c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/fbdece29474bc717c3186d6c8ed39344592b3366/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/ecc75364f36afdfbf870c1c0b5f04565877a85a2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/d990f95228bda31cf58dacb3ebfba7ef119732ac/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/239ad74a8a5fab486023b65cf2d5a3c117e24177/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/7c565c82d9533bf5096a7d7ffa4fa2231d91c8ae/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/f369b39b62e608eca8d614d59527fdf603a72e22/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/36b480441d0f70810ac1bd9ec5594efa/raw/9ae1688ccf4661a4bbe359b58e3fbd5ee448f5e5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@tonycurtis can you pls take a look?

**Comment by hoopoepg** [comment]
updated

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/6d5767480c6f5e2b651be028ccb205fcaabfb63b/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/70776ac6803583b120aa229bbb87ce703bda5aff/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/b12c5dc77aacad330dba28f2b390ebc9b51dc5e3/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/088a827c83c5bbd8e25f463a83f7e937a327dfe1/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/7f33d40db5952b1df4c2c97779620aa35b905372/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/fe892402b7c5e88feae66de82fcce7f1bb689005/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/efae5df13f5f0161e40ee29b03b78063eae385a4/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/630e68eb48973b6f259d0f767758c9c81ec9d8c0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/986c0fba4f08271ae66529810d5e40597a88d6fa/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/d268bab3ec40313814b9b9f84b21e1f652cc52f7/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/4c064fcfe03db99cda4ac1141acaef4059c97e03/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/8d233ce988f660c5b35930e5ab03addd62ae9fe4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/9be5dc050f7a6a413a271d7384ad6563afc36283/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/f6339b9d16693fd9e2390c88ea4844f5d360017d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/9dd5cf6b162019438ece3cb7092e3c1818bb31fd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/9631ab90647109be306be5ab7075591e5ff6be8b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/80f99c39b24c256a0987e9804a3dc0cfc45e1073/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/fb0b2e98076c487ae7ef52c65c00bae9a67d6335/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/f60b268e5746d5ffbf98805aa469b08a860b56a4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/0fd7f7afeab2f017261b255615c9e4cadd8bdc5e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/1f398a6df6fa9e6a170c2d0744b86c9fe8f586de/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/dea69585d4b18b95bf8561cfb0f93eed15a204bf/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/7f55a6c035ad45b935ea7540273c9ef44fa65ed3/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/30cdd245f87fa708216b6df9ac6903aa3caf4a4e/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/31eb17a2cfc879e3af333282b2a7bdef/raw/a9f42a2aeebe67398aa772b13a17b0ddf9232469/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by hoopoepg** [comment]
bot:mlx:retest
source not in tree

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/656e8705bd372df9cc4bd23fd6fa9c5e36bc2730/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/073e7295cc162116e35b245b73380f5341728f02/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/67e8e6f636a95355817fbe4bfac0f877f0bc3e56/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/35e29819d7f011777d295613606ee3d257b603aa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/2a0054496d7ff1654bbe8ebd969d4173bdfd655e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/1cdf6c35b4e1d23a3894543af595e7c3634c2ce1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/84ef9856efe6ecbee759891e0f6bf38d130bc4b2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/4fdde42b841e8e3451cbe11210d82f684ec8c65b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/9162ddb78f369fa3a8f682ca5ddc127b58a2d597/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/c28fe6e95d2cce55c0300eee0e2bd4f8c51fe811/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/df42a976ad4c2336305db694b4bc6749eb4afcb0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/53714f9c5414225c6f142037d1e0cf0f13543a7f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/25940013bd5569ee4d3b7926409480eeafd3f429/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/c25167fbeba2cee0730635381913f8c333b1029a/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/66253864cb1920a7e1914254cb99ac48ce9b1fec/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/685832c6ab9b6f3a710cdf682abb6af9555dff6a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/c2eeac6e3888b3ae413c46016f16343e83fd1793/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/a2837c6f4111475562ee27ba887417dfee735f35/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/0c3e08dd648b2e6ea05e523b2d8b847e2ea94d64/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/dcf260a83e7ec8b1113ece067cba27e3ed470755/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/1dc553d53f7047929a04a262f71728a8111d7a00/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/cb81f845e7f51526b7ab0ba1251369cfb6885828/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/b89026eb9dbbd74e68731394288d73c5dce990c1/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/739c7cc74e62d82b6ebcedab5120e79eb9c4e5be/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f55e1f74a6deac5a78b78c454fdf64cd/raw/21497fc1c66c54d334871ca0e2feecd1528b86ab/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
