### PR TITLE
UCP: Change pending request logic and use correct lane.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1324/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1325/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1953/ for details.

**Comment by yosefe** [comment]
@shamisp can you please review?

**Comment by shamisp** [comment]
Looks good to me but I would like ask @MattBBaker to give a try on Cray, it is a big change.

**Comment by MattBBaker** [comment]
So, I can't try this out because #794 made the wireup message one byte too big, so now wireup fails on Titan.

**Comment by shamisp** [comment]
Maybe we should define some "MAX" + assert so we don't step on the same
issue again and again..

**Comment by yosefe** [comment]
@MattBBaker @shamisp , I would suggest following changes in UGNI to reduce address size:
1. remove `UCT_SOCKADDR_COMMON (sgni_)` from uct_sockaddr_ugni_t - this should immediately solve the issue
2. move uct_sockaddr_ugni_t->nic_addr to be "device address" so it could be common to all ugni transports (assuming it's the same for all ifaces). domain_id can move to ep_addr in case of smsg.
3. why uct_sockaddr_smsg_ugni_t->ep_hash is 64bit where in other places it's uint32_t?

You can use `ucx_info -d` to see the address lengths of all transport to test the impact of these changes.

**Comment by MattBBaker** [comment]
@yosefe @shamisp Did some of the suggestions above and got it down so that the testing works on master. This PR also works
:+1:

**Pull request merged**
