### PR TITLE
CONTRIB/MTT: use UCX_NET_DEVICES instead of UCX_DEVICES.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@miked-mellanox please review.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by alinask** [comment]
can merge this?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1395/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/783/ for details (Mellanox internal link).

**Pull request merged**
