### PR TITLE
GTEST/UCT: Fix FC tests

### LINKED ISSUE #1884: gtest test_rc_flow_control_stats.soft_request
```
13:32:39 [ RUN      ] rc/test_rc_flow_control_stats.soft_request/0
13:32:39 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/worker/3/contrib/../test/gtest/uct/ib/test_rc.cc:253: Failure
13:32:39 Value of: v
13:32:39   Actual: 0
13:32:39 Expected: 1ul
13:32:39 Which is: 1
13:32:39 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/worker/3/contrib/../test/gtest/uct/ib/test_rc.cc:258: Failure
13:32:39 Value of: v
13:32:39   Actual: 0
13:32:39 Expected: 1ul
13:32:39 Which is: 1
13:32:39 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/worker/3/contrib/../test/gtest/uct/ib/test_rc.cc:260: Failure
13:32:39 Value of: v
13:32:39   Actual: 0
13:32:39 Expected: 1ul
13:32:39 Which is: 1
13:32:39 
[  FAILED  ] rc/test_rc_flow_control_stats.soft_request/0, where GetParam() = rc/mlx5_0:1 (467 ms)
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node2,worker=3/4728/consoleFull#1664427763b7949d9e-3f09-4d9b-9be7-3ff694c6afcd

### PR DESCRIPTION
**Pull request by brminich**
fixes #1884

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5601/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5605/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@hoopoepg, plz  review

**Comment by brminich** [comment]
@yosefe, please check

**Pull request merged**
