### PR TITLE
UCT/ATOMIC: renamed atomic_fetch_nb to atomic_fetch

### PR DESCRIPTION
**Pull request by hoopoepg**
here is renaming only, no functional changes

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6768/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Comment by yosefe** [comment]
@shamisp pls review the API change - renaming atomic_fetch_nb to atomic_fetch because _nb is UCP suffix

**Comment by shamisp** [comment]
@hjelmn - is this going to be trouble for you ?

**Comment by yosefe** [comment]
@shamisp pls note the new atomics API was never part of a release, it was just added recently

**Comment by shamisp** [comment]
I want to bounce this by Nathan. I will poke him today.

**Comment by miked-mellanox** [comment]
additional comments (if any) will be addressed in the following PRs. merging to catch more mtt testing.

**Comment by hjelmn** [comment]
Shouldn't be a problem for me. I will make adjustments in btl/uct as necessary.

**Comment by shamisp** [comment]
awesome thanks !

**Pull request merged**
