### PR TITLE
TOOLS/PERF: Use portable format string like PRIu64

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
## What

This PR uses a portable printf format like `PRIu64` instead of `%ld.`

```
perftest.c:421:71: error: format specifies type 'long' but the argument has type
      'ucx_perf_counter_t' (aka 'unsigned long long') [-Werror,-Wformat]
  ...number of iterations to run (%ld)\n", ctx->params.super.max_iter);
                                  ~~~      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                  %llu
perftest.c:423:33: error: format specifies type 'size_t' (aka 'unsigned long')
      but the argument has type 'ucx_perf_counter_t' (aka 'unsigned long long')
      [-Werror,-Wformat]
                                ctx->params.super.warmup_iter);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

uct_tests.cc:506:61: error: format specifies type 'long' but the argument has
      type 'ucx_perf_counter_t' (aka 'unsigned long long') [-Werror,-Wformat]
  ..."recv_sn=%d iters=%ld", sn, m_perf.current.iters);
                       ~~~       ^~~~~~~~~~~~~~~~~~~~
                       %llu
```

## Why ?

Same as #5547, #5548, #5549 and #5552 reason. (for porting macOS)
For fixing https://github.com/hiroyuki-sato/ucx/issues/38

## How ?

`%ld` -> PRIu64

It seems that all of the parameters use `ucx_perf_counter_t` datatype. It uses `uint64_t`.

```C
typedef struct ucx_perf_params {
    //...
    ucx_perf_counter_t     warmup_iter;     /* Number of warm-up iterations */
    ucx_perf_counter_t     max_iter;        /* Iterations limit, 0 - unlimited */
    //...
}

typedef uint64_t ucx_perf_counter_t;
```

### CODE REVIEW

**Comment by hoopoepg** [comment]
ok to test

**Comment by yosefe** [comment]
```
[2020-08-13T09:33:35.951Z] make[4]: Nothing to be done for `all'.
[2020-08-13T09:33:35.951Z] make[4]: Leaving directory `/scrap/jenkins/workspace/ucx/build-test/ucx-1.10.0/_build/sub/src/tools/perf/rocm'
[2020-08-13T09:33:35.951Z] Making all in lib
[2020-08-13T09:33:35.951Z] make[4]: Entering directory `/scrap/jenkins/workspace/ucx/build-test/ucx-1.10.0/_build/sub/src/tools/perf/lib'
[2020-08-13T09:33:35.951Z]   CC       libucxperf_la-libperf.lo
[2020-08-13T09:33:35.951Z]   CXX      libucxperf_la-uct_tests.lo
[2020-08-13T09:33:36.208Z] ../../../../../../src/tools/perf/lib/uct_tests.cc: In member function ‘ucs_status_t uct_perf_test_runner<CMD, TYPE, DATA, ONESIDED>::run_stream_req_uni(bool, bool, bool)’:
[2020-08-13T09:33:36.208Z] ../../../../../../src/tools/perf/lib/uct_tests.cc:505: error: expected ‘)’ before ‘PRIu64’
[2020-08-13T09:33:36.466Z] cc1plus: warnings being treated as errors
[2020-08-13T09:33:36.466Z] ../../../../../../src/tools/perf/lib/uct_tests.cc: In member function ‘ucs_status_t uct_perf_test_runner<CMD, TYPE, DATA, ONESIDED>::run_stream_req_uni(bool, bool, bool) [with ucx_perf_cmd_t CMD = (ucx_perf_cmd_t)0u, ucx_perf_test_type_t TYPE = (ucx_perf_test_type_t)0u, uct_perf_data_layout_t DATA = (uct_perf_data_layout_t)0u, bool ONESIDED = true]’:
[2020-08-13T09:33:36.466Z] ../../../../../../src/tools/perf/lib/uct_tests.cc:628:   instantiated from ‘ucs_status_t uct_perf_test_runner<CMD, TYPE, DATA, ONESIDED>::run() [with ucx_perf_cmd_t CMD = (ucx_perf_cmd_t)0u, ucx_perf_test_type_t TYPE = (ucx_perf_test_type_t)0u, uct_perf_data_layout_t DATA = (uct_perf_data_layout_t)0u, bool ONESIDED = true]’
```

**Comment by hiroyuki-sato** [comment]
@yosefe Thank you for your comment. I had forgotten about the PPC.

**Comment by hiroyuki-sato** [comment]
Sorry, I modified the wrong file.

`ucs/sys/sys.h` include `inttypes.h` files as the below.
That's why I need to write `__STDC_FORMAT_MACROS` at the top.

Should I remove `#include <inttypes.h>` in `tools/perf/lib/uct_tests.cc`?
https://github.com/openucx/ucx/blob/87cfa718399250e5ad9cb046ac71ce5af78388d4/src/ucs/sys/sys.h#L42

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
