### PR TITLE
UCT/API/TEST: Introduce a minimal length for uct_ep_get_zcopy() (reopened)

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
reopened #1136

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2917/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/416/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2357/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bbarett pls take a look

**Pull request merged**
