### PR TITLE
ucx/wakeup: pipe handles are replaced by event FD

### PR DESCRIPTION
**Pull request by hoopoepg**
- pipe handles are replaced by event FD in wakeup
  infrastructure (in fact used kind of counters to
  notify waiters)
- this is fix for https://github.com/openucx/ucx/issues/1762

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4396/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:bgate:retest

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4409/ for details (Mellanox internal link).

**Pull request merged**
