### PR TITLE
AZP/RELEASE: Remove strict libibverbs dependency

### LINKED ISSUE #6662: RPM packages for mofed 5.x depend on specific versions of mofed
I am trying to install the UCX 1.10 RPM packages in centos 7.9 with MLNX_OFED:
```
$ ofed_info -n
5.3-1.0.0.1
```

But I see:
```
--> Finished Dependency Resolution
Error: Package: ucx-1.10.0-1.el7.x86_64 (/ucx-1.10.0-1.el7.x86_64)
           Requires: libibverbs = 50mlnx1-1.50100.0
           Installed: libibverbs-52mlnx1-1.53100.x86_64 (installed)
               libibverbs = 52mlnx1-1.53100
           Available: libibverbs-22.4-5.el7.i686 (base)
               libibverbs = 22.4-5.el7
 You could try using --skip-broken to work around the problem
```

Not entirely sure why the `ucx` package requires libibverbs in the first place (I'd assume that to be the `ucx-ib` and `ucx-rdmacm` packages), so that's part of it. We want to be able to install `ucx`, even if MLNX_OFED is not installed.

`ucx-cuda` requires the CUDA runtime installed. This makes sense, but not all installations are via `rpm`, so that may be another issue. Perhaps we should relax this requirement, like https://github.com/openucx/ucx/pull/5776.

```
Error: Package: ucx-cuda-1.10.0-1.el7.x86_64 (/ucx-cuda-1.10.0-1.el7.x86_64)
           Requires: ucx(x86-64) = 1.10.0-1.el7
           Available: ucx-1.5.2-1.el7.x86_64 (base)
               ucx(x86-64) = 1.5.2-1.el7
Error: Package: ucx-cuda-1.10.0-1.el7.x86_64 (/ucx-cuda-1.10.0-1.el7.x86_64)
           Requires: libcudart.so.11.0()(64bit)
Error: Package: ucx-cuda-1.10.0-1.el7.x86_64 (/ucx-cuda-1.10.0-1.el7.x86_64)
           Requires: libcuda.so.1()(64bit)
Error: Package: ucx-cuda-1.10.0-1.el7.x86_64 (/ucx-cuda-1.10.0-1.el7.x86_64)
           Requires: libcudart.so.11.0(libcudart.so.11.0)(64bit)
Error: Package: ucx-cuda-1.10.0-1.el7.x86_64 (/ucx-cuda-1.10.0-1.el7.x86_64)
           Requires: ucx(x86-64) = 1.10.0-1.el7
           Installing: ucx-1.5.2-1.el7.x86_64 (base)
               ucx(x86-64) = 1.5.2-1.el7
```

### PR DESCRIPTION
**Pull request by yosefe**
# Why
Fix #6662

@abellina FYI

### CODE REVIEW

**Review by abellina — APPROVED** [review]

**Comment by abellina** [comment]
Thank you @yosefe

**Comment by shamisp** [comment]
@yosefe 1.10.1 ?

**Comment by yosefe** [comment]
> @yosefe 1.10.1 ?

yes, after more review & testing

**Comment by yosefe** [comment]
> With this change the IB dependency is _completely_ gone from the UCX packages right? I.e. as long as you stay within MLNX_OFED 5.x, you'll get it if you have it installed (which is all good), but if you don't have MLNX_OFED, everything installs, and the IB dependency isn't a prerequisite for any of the UCX rpms.

After this change, only the ucx-ib package would depend on libibverbs. The dependency will be auto-computed by rpmbuild and will work with any MOFED>=5.0 version.

**Comment by yosefe** [comment]
@avildema can you pls take a look?

**Review by avildema — APPROVED** [review]

**Pull request merged**
