### PR TITLE
UCS/ASYNC: Pass event id to async callback.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3004/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3007/ for details.

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/543/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2479/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2483/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
why ?

**Comment by yosefe** [comment]
in order to install one handler for for multiple sockets, and in the callback can tell which got the event. to avoid allocating additional context for each.

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by shamisp** [comment]
makes sense. the same can be useful for verbs.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2489/ for details (Mellanox internal link).

**Pull request merged**
