### PR TITLE
API/UCT: enhance doc for uct_iface_params_t.mode, typo and spaces fixes

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe @shamisp @bbenton Please review.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4631/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
looks good to me. @bbenton

**Comment by bbenton** [comment]
:+1: for doc/API

**Comment by shamisp** [comment]
@yosefe ? what is the failure

**Comment by yosefe** [comment]
bot:bgate:retest

**Pull request merged**
