### PR TITLE
UCP/CORE/RMA: Refactor RMA config to avoid duplication

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Refactor RMA configuration in `ucp_ep_config_init` and RKEY resolving

## Why ?

1. Decrease duplication
2. Allow using different RMA Zcopy thresholds for different memory types
3. Preparation for future RMA/AMO error reporting when using it for unsupported memory types

## How ?

1. Define `ucp_ep_rma_proto_t` structure for RMA protocols
2. Define the auxiliary `ucp_ep_config_set_memtype_zcopy_thresh` for setting AM and RMA Zcopy thresholds
3. Define the auxillary `ucp_ep_config_set_rma` for setting PUT and GET limits in `ucp_ep_config_init`

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/bd125f6be8a51fa5e8faa9a1d3b26c90e06acb90/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/e1340c10494246227f2d34be29f79812b2911086/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/bd0507e48726716eba54eabb7b0138c4e42db4e4/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/5eccbadbd5642cf7b0896ca1c8070557d4edb94e/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/9fba251ca6ed7d6b84c833cbb3a2c9a500b9a176/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/ec2c0f6b71926b547507da0da41d633e670dbff7/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/82e26b4f90764a8b70f2945be8f4b42f52d58268/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/5f12816ced55a3b3519decee147e6bcc25a6e6c7/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/292b53bab39bd5fd00200f1835b12c79559a502c/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/a902e3b87fb542e1a14b37b6e54f09c6d5aa7663/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/958cf7afd4617a803ef999a5025901a45328f315/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/a8f6783fa848e08b08b1e058823c03f54413dff6/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/41fe6064a81bbf7616e4c708a54313afe5ce3cfe/hpc-test-node-legacy_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/1004a3515274ea918861521eed6115dfbc55b5ce/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/dbebf28def15e67a9b0a5e7c13869c37a34f3470/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/a3987f3844d73c45d830d5ee23184f9784c4dee6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/33f0fcd2906293b32b3a7fad5a9d4e1efc292772/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/52b4effea133c3b7d86462b3a1455a8176cf2fc3/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/f93288266a97fba43d5fec92988203a881bfba2d/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/070b5f0fb60b46df9bd4da6890e246591aa29b2d/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/b4f7dd4b2e8a16a90f33020721979761e1b420b5/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/afdca2c2fc4cb04cacde1476fddcb48870b931b0/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/7819b1d4c836c262f6ab05170dd731cf57ce1364/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/0c098771188c28a13820b05ca5a96fe3da158d03/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f98020e9acf3c789f8c420cb35e95f63/raw/6237de6d688dadf6f60e91570e32e4483abb6443/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/4a9a2df815730ee7d8f668998d1ae642edd2236b/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/3048670a89e28438eff19fe46dfdd173c38d7d7b/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/a4bd2e92db011d9a968494d28351f98fd42a9b39/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/de2551e7d57f0d12711f095d8bd25bee784d1a4a/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/2732e4cbe597ec3e1a296cf9e645098804e8375f/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/73eeaa2933a69ead1005b28a9c405fd1af0dcfc3/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/fa9ade219efa42375e55b9fdc96637b6d1bfa536/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/276ac0f3600e0665ec611f8ffc76d07597ac6441/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/70f08e4c746e520385e14d7ee704b3b2f235b70f/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/58c9e7ac42bc582be7daf6c9c94279628e834431/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/7517c85fecb409592aed22f41da3e5fbf0c4ea8e/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/d13ac0dcdb5dfd2a131f8d1980dfc39f988d3d9c/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/d7e35cd8de60d7c420e576f126fcb0766a537691/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/165939b2386229db69ded365aed42005cdc050d3/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/5d804fa29eb39467063da90ab3e3263c21781508/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/996800c5130b5bb2614137a0fd37f66ae3b9d957/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/1e605cb8e22a7989ccaf889b22d8fa9aa659d628/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/59ba1664bfe6a6b422c2280354e31014df3bd048/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/856d25f8904621929046333110df54db8def0017/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/e072eca795049521c0f06f8097be536bfd50504b/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/5098f54a0290f3a61bef80190cba2930fb60af15/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/095d89a25c4369adb67b7e0a12a3496b0277860f/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/959fb6edfcb8446a1aafcb8892771465350f6a46/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/83d918d619ca2ac43b392fc0dc5fd89f132422d2/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d96b72d40018eeddf7595619650dbcd7/raw/b2b0d62faa717e02da029d3b9dd397bbac115729/r-vmb-ppc-jenkins_W3) | :question: ABORTED

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/e09fce8787d455d0b425e7e0d2f55d49825258e8/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/ace84a5258d33471d9c37eccb0c81095ee4a516d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/158bbe600f1cc01e03f25fe54973a10aad7d6925/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/cf50d8de1faa6b86c2a4212795413ea4f2c8dc21/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/a4d07c434b693c6ed408aa10782384fc22c18adb/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/90da64249c8e50865e7ca623cc2cf2b3ad156d7f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/38c78f934ee30c97c4d7632a4918f65ea7816efa/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/d0e353ed0444f27659ad920b5366003a34af9c03/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/d4136d2e814192aa8aadd2da37b36f453c789a01/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/c22d4cfba99b7fa302364d229c146364268c69e5/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/ec71391b0b9bdad86b6e3cb422bbd6f0bba40885/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/e1febaf0bf0ba3887d519f59ff1f1dba8cf0e858/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/c60d407c0ee2b15f8a75af78fd9be1215cf345f4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/292d9ac5cfb15cbfd2124572525d4c19e2b7f6a9/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/09c69f190e9b34383c4acdf7371dd7157d9877e2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/b6bdc39753f31b602f0839dbe9a98443e4b0f690/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/63e07d566636227be0f9db4f0e071a07f933ab88/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/5a0f73c8748d1175aef32db0fc44d0b76f2078cb/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/ef8b373fc9ebceb2c40e1030acb24f0abe2da531/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/d63987fdd3bf13c3ea64c1d5ce43433ab240fa2b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/b10ba0e3f0a8405068ebb41b8cb2f1311ba0d534/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/c5a556893bb4fd8b8982bb160a99e8ff2a570d6b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/f59e4770ebfac7841da8a5c390652e4a65360d79/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/f42f1ca4250e339b89306ffca006c6315e7cd9b1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/150d1bba0ad9dd9f362bd8f1ecae109a/raw/a4c1d1df7b935f4b5a4a6030074532321edad978/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request closed without merging**
