### PR TITLE
CONFIG/M4: Separated library flags for CUDA, CUDA RT, and NVML.

### PR DESCRIPTION
**Pull request by rakhmets**
## What
Separated library flags for CUDA, CUDA RT, and NVML.

## Why ?
To use only required libraries during building modules.
The changes facilitate switching to CUDA Driver API in UCT.

### CODE REVIEW

**Review by yosefe — APPROVED** [review]
pls squash

**Review by brminich — APPROVED** [review]

**Comment by rakhmets** [comment]
> is it expected that UCX can be built on the system without `nvidia-ml` and have unresolved dependencies?
> 
> ```
> ldd <ucx_install>/lib/ucx/libuct_cuda.so
> ...
> libcuda.so.1 => not found
> ...
> libnvidia-ml.so.1 => not found
> ...
> ```

If  `nvidia-ml` is absent on the system:
1. If UCX is configured with default option `--with-cuda=guess`, then CUDA support is disabled.
2. If CUDA support is explicitly requested, then configure will fail with error `libnvidia-ml not found. Install appropriate nvidia-driver package`.

**Comment by evgeny-leksikov** [comment]
> 2. is not true

It seems like environment magic related to container and/or platform.
all missed dependencies are found in 
```
/etc/alternatives/cuda/lib64/stubs/
```

**Comment by yosefe** [comment]
> > 2. is not true
> 
> It seems like environment magic related to container and/or platform. all missed dependencies are found in
> 
> ```
> /etc/alternatives/cuda/lib64/stubs/
> ```

@evgeny-leksikov so are we good with this PR?

**Review by evgeny-leksikov — APPROVED** [review]

**Pull request merged**
