### PR TITLE
UCM: Link with --no-as-needed, to find all symbols at runtime

### LINKED ISSUE #3480: CUDA/UCM: couldn't find original cudaMalloc() address error
Hi,

I'm running into this issue with UCX-py. I'm not able to repro the issue with just ucx_perftest. It may be similar to issues that we had seen in https://github.com/openucx/ucx/issues/3319
- The repo is here: https://github.com/Akshay-Venkatesh/ucx-py
- Installation procedure is the same as what was captured here : https://github.com/openucx/ucx/issues/3319#issuecomment-470256054 and https://github.com/openucx/ucx/issues/3319#issuecomment-470514334 
but in short you would need 
```
conda create -n ucx-py python=3.7 cython pytest 'pytest-asyncio>=0.10.0' -c defaults -c conda-forge
conda activate ucx-py

cd ucx-py # after clone of https://github.com/Akshay-Venkatesh/ucx-py
make -j install
python3 -m pip install --pre cupy-cuda92==6.0.0b2
```

```
# server located at  server-ipoib.A.B.C.D

$ UCX_MEMTYPE_CACHE=n UCX_RNDV_SCHEME=put_zcopy python3 tests/send-recv-py-obj.py -o cupy
[1555109977.665256] [prm-dgx-34:42140:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_HOME, UCX_PATH, UCX_PY_CUDA_PATH,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
about to send
[1555109989.481495] [prm-dgx-34:42140]            reloc.h:67   UCX  FATAL could not find address of original cudaMalloc(): Unknown error
Aborted

#client 

$ UCX_MEMTYPE_CACHE=n UCX_RNDV_SCHEME=put_zcopy python3 tests/send-recv-py-obj.py -o cupy -s server-ipoib.A.B.C.D -p 13337
[1555109986.709119] [prm-dgx-35:13619:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_HOME, UCX_PATH, UCX_PY_CUDA_PATH,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
```

Was able to narrow down the commit that causes this issue. Basically master before this commit works. 
```
commit 9d619b6e0f261c4297344297a85c6ed0ff498909
Merge: 3b0698d 437b422
Author: Yossi Itigin <yosefe@mellanox.com>
Date:   Thu Apr 4 16:03:34 2019 +0300

    Merge pull request #3436 from alinask/topic/ucm-inline-ucm-reloc-get-orig
    
    UCM: Make ucm_reloc_get_orig() a static function.

```
@yosefe @bureddy Lmk if you guys need more help with setting up the repro.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #3480

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9875/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9881/ for details (Mellanox internal link).

**Pull request merged**
