### PR TITLE
UCP/WIREUP: Use slowpath_progress to progress stub_ep.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/986/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2949/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2956/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev @brminich pls take a look

**Comment by brminich** [comment]
:+1:

**Comment by alex-mikheev** [comment]
👍

**Pull request merged**
