### PR TITLE
AZP: Run distributed io_demo from install directory

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by hoopoepg** [comment]
seems relevant:
```
2020-12-13T21:16:14.3456679Z make[2]: Entering directory '/auto/rdmzsysgwork/swx-azure-svc/workspace/azure/io_demo/1/s/src/ucm'
2020-12-13T21:16:14.3827495Z make[3]: Entering directory '/auto/rdmzsysgwork/swx-azure-svc/workspace/azure/io_demo/1/s/src/ucm'
2020-12-13T21:16:14.3844363Z  /usr/bin/mkdir -p '/install/lib'
2020-12-13T21:16:14.3855417Z /usr/bin/mkdir: cannot create directory '/install': Permission denied
2020-12-13T21:16:14.3859690Z make[3]: *** [Makefile:616: install-libLTLIBRARIES] Error 1
2020-12-13T21:16:14.3860625Z make[3]: Leaving directory '/auto/rdmzsysgwork/swx-azure-svc/workspace/azure/io_demo/1/s/src/ucm'
2020-12-13T21:16:14.3862310Z make[2]: *** [Makefile:1064: install-am] Error 2
2020-12-13T21:16:14.3863076Z make[2]: Leaving directory '/auto/rdmzsysgwork/swx-azure-svc/workspace/azure/io_demo/1/s/src/ucm'
2020-12-13T21:16:14.3868872Z make[1]: *** [Makefile:900: install-recursive] Error 1
2020-12-13T21:16:14.3872246Z make[1]: Leaving directory '/auto/rdmzsysgwork/swx-azure-svc/workspace/azure/io_demo/1/s/src/ucm'
2020-12-13T21:16:14.3924134Z make: *** [Makefile:732: install-recursive] Error 1
2020-12-13T21:16:14.3972685Z ##[error]Bash exited with code '2'.
```

**Comment by avildema** [comment]
@yosefe  in my PR #5958 I move io-demo to separate file / stage

**Comment by yosefe** [comment]
> @yosefe in my PR #5958 I move io-demo to separate file / stage

@avildema can you make it run from install/bin?

**Comment by avildema** [comment]
> > @yosefe in my PR #5958 I move io-demo to separate file / stage
> 
> @avildema can you make it run from install/bin?

Yes, Will add it

**Comment by yosefe** [comment]
replaced by #5958

**Pull request closed without merging**
