### PR TITLE
TEST/UD: Wait for a packet up to 10 sec.

### LINKED ISSUE #1576: Failure in ud/test_ud_slow_timer.retransmit1/0 with valgrind
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node2,worker=2/3747/consoleFull#571846247b7949d9e-3f09-4d9b-9be7-3ff694c6afcd

> 14:58:59 [ RUN      ] ud/test_ud_slow_timer.retransmit1/0
> 14:59:00 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/worker/2/contrib/../test/gtest/uct/test_ud_slow_timer.cc:110: Failure
> 14:59:00 Value of: ucs_frag_list_sn(&ep(m_e2)->rx.ooo_pkts)
> 14:59:00   Actual: 0
> 14:59:00 Expected: 1
> 14:59:00 
> [  FAILED  ] ud/test_ud_slow_timer.retransmit1/0, where GetParam() = ud/mlx5_1:1 (1291 ms)

May be related with changes in retransmit logic (See https://github.com/openucx/ucx/pull/1532)

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1576 and #1604

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3935/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3940/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@MattBBaker is ORN jenkins running?

**Comment by MattBBaker** [comment]
It is, and there is a big back log for it. This will take a little while.

**Comment by MattBBaker** [comment]
Segfault
```
[----------] 148 tests from ud/test_ucp_tag_xfer
[ RUN      ] ud/test_ucp_tag_xfer.send_contig_recv_contig_exp/0
[       OK ] ud/test_ucp_tag_xfer.send_contig_recv_contig_exp/0 (106 ms)
((Lots of successes filtered))
[ RUN      ] ud/test_ucp_tag_xfer.send_generic_recv_contig_exp_rndv_probe/0
[       OK ] ud/test_ucp_tag_xfer.send_generic_recv_contig_exp_rndv_probe/0 (10118 ms)
[ RUN      ] ud/test_ucp_tag_xfer.send_generic_recv_generic_exp/0
[pod9:4023 :0] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[pod9:4023 :0] Process frozen...
``

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by shamisp** [comment]
why 10 and not 20 ? just curious ...

**Comment by yosefe** [comment]
just some reasonably large timeout for loopack

**Comment by shamisp** [comment]
okay

**Comment by yosefe** [comment]
bot:ornl:retest

**Pull request merged**
