### PR TITLE
SYS: fix ucs_generate_uuid() - use the thread's id. not the process's.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/892/ for details.

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/893/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/894/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/895/ for details.

**Comment by shamisp** [comment]
@alinask , is it related to #392 ?

**Comment by alinask** [comment]
yes. I made a reference to it from the commit message.

**Comment by alinask** [comment]
@yosefe please review

**Comment by shamisp** [comment]
:+1:

**Comment by yosefe** [comment]
:+1:

**Pull request merged**
