### PR TITLE
UCS/ARCH: Fix gettting CPU clock speed.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/912/ for details.

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/914/ for details.

**Comment by shamisp** [comment]
autobot build

**Comment by yosefe** [comment]
@shamisp @miked-mellanox pls review

**Pull request merged**
