### PR TITLE
UCT/GDR_COPY: set rcache alignment to 64k (GPU Page size)

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6096/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
@bureddy we can close this since #2214 is merged, right?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6098/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
yes. we can close this.

**Pull request closed without merging**
