### PR TITLE
UCP: Cleanup API header file, remove ucs/queue include.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/458/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1031/ for details.

**Comment by shamisp** [comment]
I'm ok with the change (since I triggered this), but please check the failure in mellanox lab

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
