### PR TITLE
TEST/IB: Re-enable ODP tests, and flush sender iface to fix err syndrome

### LINKED ISSUE #2915: dc_mlx5/uct_p2p_mix_test_alloc_methods.mix1000_odp/0 fails on arm
```
18:01:26 [----------] 1 test from dc_mlx5/uct_p2p_mix_test_alloc_methods
18:01:26 [ RUN      ] dc_mlx5/uct_p2p_mix_test_alloc_methods.mix1000_odp/0
18:01:26 [hpc-arm-hwi-jenkins:30708:0:30708] ib_mlx5_log.c:113  FATAL: Error on QP 0x6d45 wqe[1828]: Remote access (synd 0x13 vend 0x88) opcode RDMA_WRITE
18:01:27 
18:01:27 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../src/uct/ib/mlx5/ib_mlx5_log.c: [ uct_ib_mlx5_completion_with_err() ]
18:01:27       ...
18:01:27       108     }
18:01:27       109 
18:01:27       110     ucs_log(log_level, "Error on QP 0x%x wqe[%03d]: %s (synd 0x%x vend 0x%x) opcode %s",
18:01:27 ==>   111             qp_num, wqe_counter, info, ecqe->syndrome, ecqe->vendor_err_synd,
18:01:27       112             uct_ib_mlx5_cqe_err_opcode(ecqe));
18:01:27       113     return status;
18:01:27       114 }
18:01:27 
18:01:27 ==== backtrace ====
18:01:27  0 0x00000000000311f4 uct_ib_mlx5_completion_with_err()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../src/uct/ib/mlx5/ib_mlx5_log.c:111
18:01:27  1 0x00000000000320bc uct_ib_mlx5_check_completion()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../src/uct/ib/mlx5/ib_mlx5.c:107
18:01:27  2 0x000000000007a100 uct_ib_mlx5_poll_cq()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../src/uct/ib/mlx5/ib_mlx5.inl:32
18:01:27  3 0x000000000054d4b4 ucs_callbackq_dispatch()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../src/ucs/datastruct/callbackq.h:208
18:01:27  4 0x00000000005499a0 uct_p2p_test::cleanup()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/uct/uct_p2p_test.cc:94
18:01:27  5 0x000000000047f648 ucs::test_base::TearDownProxy()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/test.cc:248
18:01:27  6 0x000000000047388c HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest-all.cc:3562
18:01:27  7 0x000000000046800c testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest-all.cc:3643
18:01:27  8 0x0000000000468114 testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest-all.cc:3812
18:01:27  9 0x0000000000468284 testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest-all.cc:3930
18:01:27 10 0x000000000046c694 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest-all.cc:5802
18:01:27 11 0x000000000046c9b0 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest-all.cc:5719
18:01:27 12 0x0000000000415f64 RUN_ALL_TESTS()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/2/contrib/../test/gtest/common/gtest.h:20059
18:01:27 13 0x0000000000020d64 __libc_start_main()  :0
18:01:27 14 0x00000000004529bc _start()  :0
18:01:27 ===================
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-arm-hwi-jenkins,worker=2/7845/consoleFull#98030106524dff065-0424-4e55-b698-eb134734d522

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2915

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8090/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8097/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8110/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8119/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8212/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8213/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8214/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@Artemy-Mellanox can you pls take a look?

**Pull request merged**
