### PR TITLE
MM/KNEM: Enhance logging.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by MattBBaker** [comment]
This failure was /dev/shm ran out of memory.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1234/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1844/ for details.

**Comment by shamisp** [comment]
👍

**Pull request merged**
