### PR TITLE
JENKINS: Adding armclang to the list tested compilers

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
Let's kick the tires ...

**Comment by shamisp** [comment]
bot:retest

**Comment by shamisp** [comment]
@yosefe - please take a look at the logs. The clang5 issue was successfully reproduced.

**Comment by shamisp** [comment]
```
01:11:30 /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/0/contrib/../src/uct/ib/dc/verbs/dc_verbs.c:674:56: error: taking address of packed member 'gid' of class or structure 'uct_dc_fc_sender_data::(anonymous)' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
01:11:30                     dc_req->sender.global.is_global ? &dc_req->sender.global.gid : NULL,
01:11:30                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
01:11:30 1 error generated.
01:11:30 make[2]: *** [ib/dc/verbs/libuct_la-dc_verbs.lo] Error 1
01:11:30 make[2]: *** Waiting for unfinished jobs....
01:11:30 /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/0/contrib/../src/uct/ib/dc/accel/dc_mlx5.c:831:53: error: taking address of packed member 'gid' of class or structure 'uct_dc_fc_sender_data::(anonymous)' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
01:11:30                                                    &dc_req->sender.global.gid,
01:11:30                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
01:11:30 1 error generated.
01:11:30 make[2]: *** [ib/dc/accel/libuct_la-dc_mlx5.lo] Error 1
01:11:32 In file included from /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/0/contrib/../src/uct/ib/ud/base/ud_iface.c:7:
01:11:32 /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/0/contrib/../src/uct/ib/ud/base/ud_iface.h:216:17: error: taking address of packed member 'super' of class or structure 'uct_ud_send_skb_inl' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
01:11:32     if (skb != &iface->tx.skb_inl.super) {
01:11:32                 ^~~~~~~~~~~~~~~~~~~~~~~
01:11:32 1 error generated.
01:11:32 make[2]: *** [ib/ud/base/libuct_la-ud_iface.lo] Error 1
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6180/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6182/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
replaced by #2286 and #2287

**Pull request closed without merging**
