### PR TITLE
UCS/CALLBACKQ/TEST: Add ONESHOT flag for callback

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3928/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3937/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3945/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by shamisp** [comment]
what is the use case for this ?

**Comment by yosefe** [comment]
@shamisp in UCP dynamic progress code (not submitted yet) and ucp_ep disconnect, it's needed to run something on the main thread only once, because it can't run from the callback/event context directly.

**Comment by shamisp** [comment]
got it

**Comment by shamisp** [comment]
the patch looks good, but the failures have to be addressed

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3959/ for details (Mellanox internal link).

**Pull request merged**
