### PR TITLE
UCS/DEBUG: If possible, print the source code of program error.

### PR DESCRIPTION
**Pull request by yosefe**
After the commit, the error message would print something like this:
```
[hpchead:5187 :0] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x12)

/labhome/yosefe/workspace/ucx/src/ucs/sys/rcache.h: [ ucs_rcache_get() ]
      ...
      146     pgt_region = ucs_pgtable_lookup(&rcache->pgtable, start);
      147     if (ucs_unlikely(pgt_region == NULL)) {
      148         region = ucs_derived_of(pgt_region, ucs_rcache_region_t);
==>   149         if ((region->flags & UCS_RCACHE_REGION_FLAG_VALID) &&
      150             ((start + length) < region->super.end))
      151         {
      152             ucs_rcache_region_hold(region);

[hpchead:5187 :0] Process frozen, press Enter to attach a debugger...
```

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1234/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/647/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1235/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/648/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@miked-mellanox pls review

**Comment by miked-mellanox** [comment]
cool! :+1:

**Pull request merged**
