### PR TITLE
NEWS: Update with v1.6.1-rc1

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@shamisp @tonycurtis can you pls take a look? i'd like to start rolling out v1.6.1 RCs

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11839/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Aug-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/53716aeaaea0dc612575262832be56a8f67edd7f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/8eeeb5ad49566d4e226fd807864bf2271fdace75/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/b7067a01373c782159606ec700bbc25d1b5b36ac/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/3cb3dbadfc10439437bc63562b799128113fed4f/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/30e64b76b2288949dfdbdf39212a496749905821/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/e923122bb8c30550ceef07503bed33656dadfc6f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/6b82bc3f8444ff2435c9eb34e81dec451a32451c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/1e565f0f73a41341278aed5aabf5c40e5d9b0b30/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/bd6069636786fe2f19b74e7a6f4cbf343d0f645d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/f8de9a3ca57a2bfe9423912b8b56ca11ee93a069/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/a99cadd35f55c74409cf7957e5247c9d97f7c758/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/564194d0aea64722e97cb5ee0e715837e00989e4/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/e7cf0b518c8bc474803c477670c05c8c415088a7/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/08ac731b895224549e694004e3493d1c8cc23313/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/e6bb74f7e5604ae27c012d52b7896bc63590b6c0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/ec03e60337d116c3638d311fab97f36491d74954/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/df8119e51fed0dfe1db8f4dfe7ea89af4a3a5766/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/b8ab2ba5ff17fcf2a4c6f0ac8dc31c4a56af3827/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/5936d4534d14586670503d93b04a5a1b1377b722/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/f523bdbb48090eea50916786d4deb5618b547c09/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/18267e38fc1f782c0b6d0383196037ea232e5e86/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/b1240c6a45be5941b6b82168e85d2f62182df194/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/f4bd87fcf5a47e7f5791000f34a2a3f924b37d00/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/f982d8193e49c5707b8c8632208a5f69af53230e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/14ccf58908b7dfe9fa8ca914fd791109d351b0fc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/9179d55db981d44effe9f01f60a94ef9b92cde9d/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/6643a49ed924b283ef9270deb5365e2bcace5d92/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/f8c109e3915399d0ada71957c3f7eae1ea1c1e86/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5b5fdd6fd90d8f2c03bd1deacd941fa8/raw/dbe4b9fdef1281e6db4d291a28d3b2610750b562/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by tonycurtis** [comment]
> On Aug 11, 2019, at 12:22 PM, Yossi Itigin <notifications@github.com> wrote:
> 
> @shamisp <https://github.com/shamisp> @tonycurtis <https://github.com/tonycurtis> can you pls take a look? i'd like to start rolling out v1.6.1 RCs
> 

Looks ok to me.

**Pull request merged**
