### PR TITLE
CONFIG: Fix MPI support printout in the end of configure

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10844/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/55e2f9a7258be9a03a1138375e37aea33379432b/_main) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/f2f68a5a8daaa7293cd705eb958c8e755926fe9e/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/f30b2677e881c9fb34f3691315c4a9d25b7dba58/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/c44e4e9dad65ecda53f8aee6d341d44f89bc3edb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/f60dcf1f847856600f342986a52bc971c9a342f9/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/bdd0907618920ad79b47bca27a3afa1704a5dfc9/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/a02e73c046bfa32da17b7f0124b7e12bde45e039/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/1857426547ff70801f0221880411abd300871344/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/6c6869905ec3038b284455714bc65fdbcaddecce/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/ce374df260320bc1ecccdb8e04ee261fbb54ba66/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/0dadb2e1ba79f625d84efb96ef8909d794aa20d3/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/5a6eb154ae94dbbf2a71303eddc4d5b0b8808177/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/30b28e7c6d0277fc4aa46515ed66cb9a7f0868ea/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/00727cec1c216b28fc25ba0ec237a6cb2213d7fc/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/e7fbfc5c643f5a6eff3255df95abf0fe3b04aa3f/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/74442dbd602c8a7f1f9f8f4ff082a0bd6c84016e/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/52cc573f6379edc7ce56998f9e5caed5e6fce2df/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/f7e85c273844216cb77cd786246ce12e234e5884/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/3185467f3c01a00995179353d984165a84a447a0/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/eb6e354e83d10bd94c891d78cef9942f7a3347c6/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/267c2a7752326bb3f6141aa44cd054388b44a7dd/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/b3161aa90daee0dc45a225a14e74373e211df40e/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/f1627476d3871c8b674ac00fdf3356226c81ab90/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/3e167d570a4648389cea7e202992926cf802d76b/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/c4fa18d3e380a3efbf74a99268de058a97be9658/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/0c7194fbdb8c044958664c051a2c061391a9ea41/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/39f5a3f9ea9b593a0679b178110599013cfe7a58/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/7b9ff911f8d2b2ae56fc7a9c96f8b7846da6bfa7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/768c61d3886fe44488db8c4af7dd097ac9693744/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/3ad14265c54fc477fb3ed9a9f7b784787f411b6b/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/ae07c4e76cd54d9d7b3f66009e7e12d4b1a09c5d/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/70f8d2d1253eff25ab3fc2ebfeeb808cdc6528af/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18e01607e0f94e4a9806ee93841fefda/raw/d46c75b3b1bd8166ebdcb90c0507a600cfa79e0b/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10879/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/b3f7d325ed4b44bdd321c0571f60f8c00c78571d/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/fb7ab5938f67157ba89017e677aaedb954c3eba0/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/8aed89b25a46da8ff89b19a0c8af509305e4240a/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/6766f31a5680f57d7dae20cccfb5b4ca448e5431/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/b64eb8bdcf7cb505030365d8c9702dbf7cd48a09/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/f084bcc8bf547cafb3e24ac56b1b69149e7a48d2/hpc-test-node-upstream_W3) | :x: FAILURE
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/dfb4af2a392da5d2549c3c2efa61bd21ecb85b24/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/82c709491174affd7d0cf519d31240fd712ad0f6/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/97ca4370a2f6b9598e164f1cd6d927db826bf86f/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/af6c5104672d72e83bc376b4bcd6dcb5aa557f9d/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/de7e8cc401e15033fbb47219069244afd8778189/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/aae0d8178d45ab0309a3f127a9eb8bc82ae6382c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/14c162d6d0b9ff8a55b8ff6029dea682c731baaa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/e997bb10d464542fefa687c3b3f3ace82ee2f4c0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/3efefac38d2aa7b43371380658ca30693ff91fe6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/c79dcb1e5abf46b254d2a853c906114592b72fb5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/3521e8456a61c05e1454f8ad9e923e7805aa1670/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/0f8f452c29db85ae700e776656b9d2c689131dc9/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/03c89035ad13db5bdfccb8b3c05c624d5fab7384/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/ac0aa9549e4d07decbe2745ddff6aa8efcd46f6f/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/02f8487068a147da19a5552e5159deec12b07ecc/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/968d0f6b08a0c07163ad11c339365e898b3f9f5e/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/61a622397ff1bd05aed1329e88928891570fc357/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/64f21da8341e0985a09c66edc363805d2856ae85/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/ffb5a6e3c466001d28f677c3be0e72c76a90c87e/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/fe6d2b63345938af96f4f1c4eb925ab467fca515/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/a8d1e261d75f9a1cc1312288c7b4a7bbeb2df7ab/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/27f7323e38fc7a0dacaae4216d4ee19183a6b259/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/ab947a6b98a137a64b697e5a1355f2fb2b073e4f/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/d515d17de78af3b8865284fee59991dcaf48afa9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/287924929393ceb197d3a2f1c6a9e04703f4d20d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/cba5c2613b9d1737183238685150adc492e1c3ca/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/1895bf1d1abda6cc46e020ea1b4180184716bd95/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/da243772027238e3481291199c2f5f9d3147274c/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/c5e57cd2dd20496f4c24a3fd9f90b58ed48a81f4/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/f0e3a13ae2a37f6871df15dce71df01b79aca019/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/52d45ea24ce4bffe6c83b5b9c4c9b4e9/raw/df6a5b94cae3c6a1440508e3b27d7dd25c2e24f3/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10910/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/54165047d4aa13f11681b1aa987f5ab974b088b5/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/7e00ae317d141a22f08d50604cd68d6c15f563fe/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/813aae23e6118bfe1e4d1691fcca0bf55f6310ab/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/24798edc1ccd35875d78e0494880af6ae0c8179a/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/10d6d6348e83d10ae80f3438613c0978c3d8d04a/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/3a1c5d6a9e61b1053012450c9bfda380e3ae8e4c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/5a02e90174318651ef6b1a3308844c276a5f5f53/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/fb2410fd8b9c0ad18d482ead742f37ec48e51075/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/0996eba8448c552d31c2e350aeff8da21996113d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/da4da5e7aa8422932cb5fecf7a1663953e96d216/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/81dd68b4507c8649f662fddc448d1a7c8584a48e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/f1934fb21e2784970be1c2567338fa71252dca54/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/9bf3277307cac904367ed839fc77567029c05eb8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/2a187f0bd2c9d01b12956f0c0c8096e4eb1236d1/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/1c657185f8320c654249adbf1377acf2c0b4b5a6/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/ff3b9a95fb2f184c4574a8c684e211bf6c3384b7/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/ff33729cc71fa4d46fc5ca0bc79d0470b2945f43/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/577ea7b68619c433bc6faca89a25a8835f9fb5d8/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/0cc92d7cbcd6c5fc01119a9f52cdbaeaf89c404b/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/6470ae46b1cbf5734dd5a63971b79928b7a61b66/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/b5dbcd637f0149c5f60cc53ac6ea3027720fec82/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/d3c0a1d8f211b2d7a1c7d7d682e9c8aa248d132b/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/95b3b2851974e23ff1d47283340f2bf33bc9c3e4/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/03601fc16e8ed7aa8d8d5d5bdedbd967531ed9b0/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/5abd77e2e7f1f70f6431d109126fa3a43eec7cbe/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/51a03cd0e28caa73a24220318c3410141679e23d/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/2ba8f8e5cbe2a1fd62c153d6c5fb7d9e8b1c6118/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/89f81f3728af06a43cbdfd01acbf070baf6a75fc/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/5a4508a8090e83cb92999a0c9f27732fd3ff2a46/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/f0d1f3a1c5b22d65b8b26c41a4408c5e0a966ce6/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/a5d8262ff57beb5f563e2243efb65b9bedeaf9df/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/b51a9dbfad23bae8fff03d0865fbc07ccb26978b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/d0f95a56bb18eda974e70dbc76fbb2514f7f9803/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/c392bfabc5db1c04e4b33991d84232cf12bd5054/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/6e5fa781babc2ca22be57c2c475b0fb1bfd51014/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/22b3324c9246deffd68f8e35e3f529cc894f056b/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b47096c3281556f3b47e89f6c279b184/raw/6ecb617fe1994106b95ae0298df90b0e193b35f4/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
