### PR TITLE
BUILD/ICC: fixed ICC diag suppression

### PR DESCRIPTION
**Pull request by hoopoepg**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9431/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9442/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Comment by yosefe** [comment]
@hoopoepg what is this diag and why need to suppress it?

**Comment by hoopoepg** [comment]
@yosefe actually I didn't add this suppression, I just fixed CFLAG initialization.
I can just suppose that this is indentation warnings prompted by ICC

**Comment by yosefe** [comment]
@hoopoepg right. i see other places have this bug as well.
How about adding generic macro like AC_C_COMPILER_FLAG([PROGRAM], [FLAG]) which updates BASE_CFLAGS if CC can compile PROGRAM with FLAG?

**Pull request closed without merging**
