### PR TITLE
Allow the java bindings to compile in a VPATH/out-of-source-tree build

### PR DESCRIPTION
**Pull request by tonycurtis**
## What
Allow the java bindings to compile in a VPATH/out-of-source-tree build

## Why ?
Couldn't compile out of tree

## How ?
* Point configure's maven test to the source directory.
* Tell maven where the POM file is in the source tree.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9032/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9035/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9092/ for details (Mellanox internal link).

**Pull request merged**
