### PR TITLE
UCP/UCT/API/TEST: Allow pending callback to return UCS_INPROGRESS.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/832/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1445/ for details.

**Comment by yosefe** [comment]
Need to use RESCHED_GROUP instead of NEXT_GROUP

**Comment by shamisp** [comment]
@MattBBaker please take a look as well

**Comment by yosefe** [comment]
@alex-mikheev @shamisp Please note, that this commit will not provide fairness between transports, because most transports today have to exhaust the new available resources with pending sends, before returning from progress, to avoid reordering between pending sends and new sends. 

The only fairness would be for now between multiple peers. 

So we return NEXT_GROUP - since RESCHED_GROUP can create out-of-order.  
If at some point a transport would like to be more fair, it could solve this problem internally, possibly by using the arbiter in a different way and possibly returning RESCHED_GROUP. But we can start with this PR to at least start implementing protocols the correct way.

**Comment by alex-mikheev** [comment]
@yosefe 
returning RESCHED_GROUP it is ok for ud tl. Ud already has to deal with the possibility that tx resources may be freed asynchronously.  See 0c9e8c303136577e11b1f141ecfc2256484a9272

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1461/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/852/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/855/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1464/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/859/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
reverted ud because apparently it does not really support RESCHED_GROUP.

@shamisp pls review

**Comment by shamisp** [comment]
Let's talk about this. I want to see consistent behavior across transports. "Disables for UD" a bit concerns me.

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
