### PR TITLE
UCT/IB/DC: Align attributes and attributes mask passed to modify QP

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Align attributes and attributes mask passed to modify QP (experimental and normal) for DCI

## Why ?

They need to be aligned

## How ?

- Remove/add flag from/to attributes mask
- Remove attribute field filling

### CODE REVIEW

**Comment by yosefe** [comment]
@dmitrygladkov did you see any failing tests or mtt, related to these fixes?

**Comment by dmitrygladkov** [comment]
> did you see any failing tests or mtt, related to these fixes?

No, I didn't see. This is just an expecting code and aligning with what we have for the code that relies on experimental API

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9792/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
tests are failing for now, need driver upgrade in one of the internal test machines

**Comment by Artemy-Mellanox** [comment]
Actually tests are failing because ib_core expects valid ah_attr.port_num when IBV_QP_AV is set. In DCI case it is meaningless, but ib_core knows nothing of DC.

**Comment by yosefe** [comment]
ok @dmitrygladkov , pls fix this PR accordingly

**Comment by dmitrygladkov** [comment]
> Actually tests are failing because ib_core expects valid ah_attr.port_num when IBV_QP_AV is set. In DCI case it is meaningless, but ib_core knows nothing of DC.

@Artemy-Mellanox Thank you!

> ok @dmitrygladkov , pls fix this PR accordingly

@yosefe done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9819/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
> Test FAILed.
> See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9819/ for details (Mellanox internal link).

```
20:11:37 [     INFO ] Using random seed of 30025
...
20:35:37 [----------] 2 tests from dc_mlx5/uct_p2p_mix_test_alloc_methods
20:35:37 [ RUN      ] dc_mlx5/uct_p2p_mix_test_alloc_methods.mix1000_odp/2
20:50:37 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/test_helpers.cc:42: Failure
20:50:37 Failed
20:50:37 Connection timed out - abort testing
20:50:37 [hpc-test-node3:61109:0:61109] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
20:50:38 
20:50:38 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../src/uct/ib/mlx5/ib_mlx5.inl: [ uct_ib_mlx5_get_cqe() ]
20:50:38       ...
20:50:38        10 uct_ib_mlx5_get_cqe(uct_ib_mlx5_cq_t *cq,  unsigned index)
20:50:38        11 {
20:50:38        12     return cq->cq_buf + ((index & (cq->cq_length - 1)) << cq->cqe_size_log);
20:50:38 ==>    13 }
20:50:38        14 
20:50:38        15 static UCS_F_ALWAYS_INLINE int
20:50:38        16 uct_ib_mlx5_cqe_is_hw_owned(uint8_t op_own, unsigned index, unsigned mask)
20:50:38 
20:50:38 ==== backtrace (tid:  61109) ====
20:50:38  0 0x0000000000060178 uct_ib_mlx5_get_cqe()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../src/uct/ib/mlx5/ib_mlx5.inl:13
20:50:38  1 0x0000000000624b5a uct_test::progress()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../src/ucs/datastruct/callbackq.h:211
20:50:38  2 0x00000000005f1448 uct_p2p_mix_test::random_op()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/uct/test_p2p_mix.cc:132
20:50:38  3 0x00000000005f2a00 uct_p2p_mix_test::run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/uct/test_p2p_mix.cc:156
20:50:38  4 0x0000000000557f3e ucs::test_base::run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/test.cc:273
20:50:38  5 0x00000000005472d3 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest-all.cc:3562
20:50:38  6 0x000000000053b74d testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest-all.cc:3635
20:50:38  7 0x000000000053b81c testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest-all.cc:3812
20:50:38  8 0x000000000053b97f testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest-all.cc:3930
20:50:38  9 0x0000000000540317 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest-all.cc:5802
20:50:38 10 0x000000000054061b testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest-all.cc:5719
20:50:38 11 0x00000000004e7f43 main()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/2/contrib/../test/gtest/common/gtest.h:20059
20:50:38 12 0x0000000000021c05 __libc_start_main()  ???:0
20:50:38 13 0x0000000000525ede _start()  ???:0
20:50:38 =================================
20:50:38 Sending notification to dmitrygla@mellanox.com
20:50:40 [hpc-test-node3:61109:0:61109] Process frozen...
```

Related to #3453

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9833/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9838/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9840/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
@yosefe ok to merge?

**Pull request merged**
