### PR TITLE
GO/TESTS: Use serialized thread mode

### PR DESCRIPTION
**Pull request by tvegas1**
## What
Seems goroutines can end up being scheduled on different OS threads.

## Why ?
When used in single thread mode, UCX must be always running on the same thread.

### CODE REVIEW

**Review by brminich — APPROVED** [review]

**Comment by rakhmets** [comment]
what issue is being solved by these changes?
I guess `runtime.LockOSThread()` is the only way to force Go to use the same thread.
Please take a look at https://github.com/openucx/ucx/pull/9581.

**Comment by tvegas1** [comment]
> What issue is being solved by these changes?

The goroutine is being run on different OS threads, which ends up operating UCX worker on different OS threads.

Doing so can cause corruption. For instance, in single thread mode for IB, we use `bf_post` instead of `bf_post_mt` which skips using a store fence when sending data. I am not aware of any other difference apart this added barrier.

We then added #9918 to enforce single thread usage, which is now triggering issue in go tests.

> I guess you need `runtime.LockOSThread()`. Because this is the only way to force Go to use the same thread. Please take a look at #9581.

Agree there is similarity, but here we don't even need to be as stringent. Having the worker being freely non-concurrently operated from multiple OS threads is fine (the goroutine), as long as we create it in serialized mode.

**Review by rakhmets — APPROVED** [review]

**Comment by brminich** [comment]
wire-compat failure is a known issue related to a specific server config

**Comment by brminich** [comment]
merging this PR to unblock CI

**Pull request merged**
