### PR TITLE
UCM/MMAP: Fix race condition updating fired_events from multiple threads

### LINKED ISSUE #3756: malloc_hook_cplusplus.remap_override_multi_thread fails on arm
may be related to recent changes in testing for mmap event support by @yosefe and @hoopoepg 
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10760/label=hpc-arm-cavium-jenkins,worker=2/consoleFull
```
17:47:38 [ RUN      ] malloc_hook_cplusplus.remap_override_multi_threads
17:47:38 /scrap/jenkins/workspace/hpc-ucx-pr-5/label/hpc-arm-cavium-jenkins/worker/2/contrib/../test/gtest/ucm/malloc_hook.cc:86: Failure
17:47:38 Error: Unsupported operation
17:47:38 terminate called after throwing an instance of 'ucs::test_abort_exception'
17:47:38   what():  std::exception
17:47:38 [hpc-arm-cavium-jenkins:96946:1:39511] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
17:47:38 ==== backtrace ====
17:47:38     0  /scrap/jenkins/workspace/hpc-ucx-pr-5/label/hpc-arm-cavium-jenkins/worker/2/build-test/src/ucs/.libs/libucs.so.0(+0x2129c) [0xffffb7f3129c]
17
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #3756

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10778/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/26bbe64f62fb49f48d7b05cb9c195ceff05e9425/_main) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/513d9d168ca0355ef04595afec37c42f5f99d929/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/6800af12b0218dcaa55005d2bc35483b78513dc9/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/fef72eba06b6ce845d200a590aa75249b55cd219/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/1044830996c824fccf850781169d99e692b16e75/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/d3cecca4eb8955f1d7de8c697849ea27d40ecb6b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/9311f3c400308f639a19ba05b5e8be8230e56948/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/b6cc42a6ca0b6dcdf71f027cf5c447888fae4791/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/4b3f93dbb402964bd0ab40f3f44f51b655bcd783/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/d4f4e7a7fbdb3b23ef563669fc96d90c66ba55d9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/1016d62a3141d2436f874e01c74620e3e01b32b4/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/c9c9376bb106f03f4e582a0ba4701fe53c66d4f6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/ea43a2e98b5468fa6f185d06010a26d42cf93bf0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/1dd91286c2c2fc0f719cd862ad477bb81d485e1a/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/333f1e4586a3434ee03d555bcb138dc4b4eeb987/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/4ea45127b6b34e91d152321684b6aeeb92bda3d4/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/6205ed395509f9b1b50e717b85027397152a6a61/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/068f655c67285c199cd88412a5b968d308c652ea/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/07f1ce3f2b0e3d8e4707b0fc1d4a91019785eab9/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/423665ee3ccfd56e35c7d6ae6ca6250de4683db7/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/dac7073db8c19c395d660c9dd86fe42cee700f1f/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/a9da9f588efc831ab367dda045eeff619348dfc4/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/3c405a0f553ac41ea8fa84fc4a6f5c1b7b2386a6/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/e929b8637160b7e150cedb7e9003e2edb6572afe/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/d0496af2f059f426527e25ff846cfb90c8d607e2/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/a98b93f19a2e5e1bc92f941815b3e7dcd29c4a33/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/dde4fb54e0f97c7c05d152f87ead57a9bee43b4e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/e6c50ad4815d2993a729450b2dfd3adca81b1516/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/638b7db815a205307c5c1803ddb37c23fdd05fa2/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/01baa9e2a5db3dd8fae3884d7c140ac19124215f/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/0c8f2ff46050cb615cf4880898b09b98527d307c/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/51c56cc96fc6e0c34a0e47ecd0a9cb53dec4383a/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4398e4e7f3a00856921d1aac37860dd1/raw/12819e2542508d03abc8c764fc7596721857c19d/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10801/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/31985700c74fe82bb17f59d3c05f60fb0320462e/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/d1cea229fe050b97529293a3a79c71750ecaeabc/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/f88947de481c8627990cc7830dbf6380ed078bbb/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/31428aabba75d097e08d0160037e4be50a8f5480/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/65f72538c285c43bf377c95ea3711953b501ebf0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/546ed376a98d4660d9e0a96900677a644793e1d4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/fbce8a71b307e76e024320b1845369538b5d605d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/98a50bab02801ea275118552677e3483cccc5d11/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/3550434140208227c1b2d64475795b2d83b4e6ba/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/f16e889445c7854da2899415dc1070f6fde93991/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/384fd444c5453c5d3d4c574d21a6515dc450a907/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/02ba91111e11821889cb2771a8854af711670222/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/88f7f2d20d14d7e0b70141b1cc7c160024df3678/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/e9c4f617651fa02a853e6c9a3bb4df64e2cf4fa9/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/c778ee795946480835583f863d64560efc88f070/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/b80a201124d65182b514c57cf193862d0049b8a0/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/8a9466df1b87c922a99e2003c47e56238ecae826/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/c9fca78819598ae617a58945168beb115f2c7263/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/619fb1536d46d61eff5c240f21bd21ae09590da8/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/7a9cd7b0fd7353b9994b9f26f538c60d744a400b/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/a9a334825740d5b3f210ed9fa33f8bddb13cb329/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/ef2490b16e9a85bb01f14f90827e4b7461480d17/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/63cd3b193d240fb768b0199b6e8d1ca43926ab9f/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/17c35e0ff69e8db223adc0adaaa283f5dcee4d4c/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/7d933f03e2dda9147c1f56c31af2b42223230980/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/25d5391a6e80ebf7d4e0c203d8691e3950c9d684/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/c56ba16abc53e806eff435da3082a8e8cb01aefb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/610fbc700bcd489b58f3b3dc4e4ac607b707afef/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/d32c70273dfcd096855abe6ab4eae4d629f919bb/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/f6dfe044727e1431706f7ebf0da4c693fe27aa0f/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/726598a9d56ea53a1b92459ca89f342e141f5f4f/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/cb492376a7d63186f137046e113ccd3028bf56e5/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6689ee9ac8c2901988bb395b5d394447/raw/767f7ab3555eaaa700454c387cc78441472c6759/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@hoopoepg can you pls review?

**Pull request merged**
