### PR TITLE
NEWS: Add v1.5.0 release, and add placeholder for v1.6 release

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
@tonycurtis @bbenton

**Comment by shamisp** [comment]
👍

**Comment by tonycurtis** [comment]
"that" on line 14 looks correct to me

**Comment by tonycurtis** [comment]
"that" on line 14 looks correct to me

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8853/ for details (Mellanox internal link).

**Comment by bbenton** [comment]
I agree with Tony, old line 14/new line 23 should use **that** rather than **which**.

**Comment by bbenton** [comment]
👍

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8871/ for details (Mellanox internal link).

**Pull request merged**
