### PR TITLE
UCS/STATS: missing lock (v1.2)

### PR DESCRIPTION
**Pull request by eladpe**
add lock for filter node add

### CODE REVIEW

**Comment by eladpe** [comment]
@yosefe PR from master

**Comment by yosefe** [comment]
@eladpe this is not same code as master - pls check

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1656/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1657/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3574/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3575/ for details (Mellanox internal link).

**Pull request closed without merging**
