### PR TITLE
Bug fixes for Jenkins on ARM

### PR DESCRIPTION
**Pull request by shamisp**
Bug fixes for bugs discovered with Jenkins. 

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/23/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2624/ for details.

**Comment by shamisp** [comment]
bot:bgateNEW:rebuild

**Comment by shamisp** [comment]
bot:bgateNEW:rebuild

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2625/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/24/ for details.

**Comment by shamisp** [comment]
bot:bgateNEW:rebuild

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1977/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1978/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:bgateNEW:rebuild

**Comment by shamisp** [comment]
bot:bgateNEW:rebuild

**Comment by shamisp** [comment]
bot:retest

**Comment by shamisp** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2630/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/28/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/30/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2632/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2633/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/31/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1982/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1984/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1985/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1987/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2635/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/33/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2636/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1988/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/34/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2637/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/35/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1989/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@yossefe what is the MellanoxLab error ?

**Comment by miked-mellanox** [comment]
``` 
02:50:29 [  PASSED  ] 3590 tests.
02:50:29 [  FAILED  ] 1 test, listed below:
02:50:29 [  FAILED  ] cmrcx/test_ucp_wireup.stress_connect/1, where GetParam() = \cm,\rc_mlx5
02:50:29 
```

and

```
02:44:20 [1476920660.441184] [hpc-test-node:18842:4]          mpool.c:37   UCX  WARN  object 0x357ef00 was not returned to mpool ucp_requests
02:44:20 [1476920660.441185] [hpc-test-node:18842:4]          mpool.c:37   UCX  WARN  object 0x357efc0 was not returned to mpool ucp_requests
02:44:20 [1476920660.441187] [hpc-test-node:18842:4]          mpool.c:37   UCX  WARN  object 0x357f080 was not returned to mpool ucp_requests
02:44:20 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/common/test.cc:133: Failure
02:44:20 Failed
02:44:20 Got 120 warnings during the test
02:44:20 
[  FAILED  ] cmrcx/test_ucp_wireup.stress_connect/1, where GetParam() = \cm,\rc_mlx5 (1874 ms)
02
```

**Comment by shamisp** [comment]
Seems like unrelevant for this pr

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1995/ for details (Mellanox internal link).

**Pull request merged**
