### PR TITLE
UCT/ROCM/IPC: Use correct agent for IPC copies

### PR DESCRIPTION
**Pull request by souravzzz**
## What
 Use local GPU agent as the source and destination for ROCM-IPC copies

## Why
* Fix incorrect agent selection when all HSA agents are not visible to all ranks
* Fix failure when unequal number of GPUs are assigned to different ranks

### CODE REVIEW

**Comment by shamisp** [comment]
You probably want to add OSU copyright to the file

**Comment by souravzzz** [comment]
Hi @shamisp I am working at AMD now.

**Comment by shamisp** [comment]
@souravzzz - congratulations !!! :)

**Comment by yosefe** [comment]
ok to test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/112e6e42811791a96f3f286dec4818d155f8e882/_main) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/d523408c709ce3a8ccedc608a62ad7f8a6244991/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/51ff3ec6a6446c4bf08365eefd947a2cbd27ec17/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/2e48cd89e517458bd950c9a891cba64d63e37b56/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/9b708e2c78fcd98b993c7f07d5ea1314548907b1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/0f3d749f1d0c3a0a3569ae43099359f767580c3c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/f82cb0d0b5373880e61c86ad648c23e6e39f14ab/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/624717a28b534552f4b1bb7d17529ce0d568aebb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/6e163091ccd5549c71243ff45e21105071142453/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/83e98bb7e9462de87af0190d6fec7886e7b7f52d/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/149b554b9e18bb61c13a45e0da6a6562d32e5de1/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/700283ed212888a4d68332a7e3b34776615999d2/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/c531a36b4bb4f1796cec4a484fa2b2d97ad19704/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/16466e2d97afe96501b772bb1bc211c9dcbafd26/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/b5742e91cb70a6f2cace29113678764eecceb15e/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/f88779f0a95f77acd9877f2d86b34056032bf06e/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/dc2ecbf251dc27ff61ca31e368db8a6ecf3cd264/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/ca1b99577f6863004f48d13bd54a2043591c5842/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/e62bffdab00685123baba1bf0ad172362daed616/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/c1f6b036dc1a3e61c140c2e54bedecf8cb94c7ef/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/4e58fc959eaec92bddd063b141dace5eda73daac/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/8080c3d45bb2805389b010e0c048ecab73cefa26/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/50b209f43e7e45be7a60c8fabb3e0f96d495ac6c/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/6e8518ee0cfcd806ae02efed917e9ba20e585b85/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1e4bf56c59a7ca7701fc078f6191618b/raw/6f41d627d3b80ce2c17f2d374fa8511da4a1ff20/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/d72a105ed871a6bb74b8dda1fa77bf3c95873b30/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/268d704244ecb871184ad5fec30a0e5d35176bde/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/dabd5eecb3851f48b11bcda77bd69d7f32f119b8/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/591a267a2f455cdbc3a9a898f456e405be55eaca/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/66dcf2458852cac791a4e91c78ec4e26e317fa22/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/477044919ecb92b3f73fa90d1c58a6269aa75ad4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/76b16684f9456209ca94e90604bd7ba712cd8ead/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/ca5676b54e40f3f9d20fefe0bcdc9b514e1b4a4a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/568bc8451251b333a068f8e10e086eee4e31dd0e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/bfae7112bbd60afdf008de0c462caa704e45891f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/29c4833e012cbb8cf278846736c8b8eca0efcc56/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/110e7c44437b3fa4aec631cd3a18b30b8731a141/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/6e81a888ecca47bac840a6607e614ea72a38ccdd/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/d8ff38960241e1a847d3b2128cd772912321a542/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/3f05a65cffe2e781c0678cdf7620a486ccebe430/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/1093040218c326bf2676be01fb664e1923825716/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/b0a0e7d77ea600b266e80e291f658a3975439bc3/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/8d0fe23cfd7f0dd381d45768df4eafe847f29ce9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/b6f05c8aae16011b820a174c37bfaa6d1a1d10c2/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/a8cd7ead5a2c65fcb4a236e22366fddbd194d383/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/ce5d3222b0242e117194cc7d695bb3ac6f53b117/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/33ed1568e144a0e5f6fe0dfa0508d10e075a9a06/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/fd7d1ccdc017be5d5d6371355cf9f51269468c68/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/8678d10cdd47fe112bd450fc9d3b18ee2439c5b8/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b561fdb234353d2c4f08e823d61f6f31/raw/6a4bbf7af90d4cfd0646fb44dc8f2f99d7ba3b56/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by souravzzz** [comment]
@yosefe @shamisp Is anything else required to merge this PR?

**Comment by shamisp** [comment]
@yosefe ?

**Pull request merged**
