### PR TITLE
DEBIAN: Replacing copyright file with the LICENSE

### PR DESCRIPTION
**Pull request by shamisp**
The copyright is in sync LICENSE.

### CODE REVIEW

**Comment by shamisp** [comment]
@miked-mellanox and @jengelh please review

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/896/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/897/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/898/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/899/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/900/ for details.

**Comment by shamisp** [comment]
@miked-mellanox can you please take a look at the failure.

**Comment by yosefe** [comment]
:+1: 
test failure is unrelated

**Pull request merged**
