### PR TITLE
UCT/MM: Extract guid calculation to a function.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by miked-mellanox** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1011/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/434/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls review

**Comment by alinask** [comment]
:+1:

**Pull request merged**
