### PR TITLE
UD/VERBS: Avoid passing empty SGE entry.

### LINKED ISSUE #1022: zcopy test error
The zcopy test is failing on Mustang at LANL.

```
[     INFO ] checking dc: no
[     INFO ] checking dcx: no
[     INFO ] checking ud: yes
[     INFO ] checking udx: no
[     INFO ] checking udrc: yes
[     INFO ] checking cmrcx: yes
[     INFO ] checking shm: yes
[     INFO ] checking udrcx: no
[     INFO ] checking ugni: no
[     INFO ] checking self: no
[     INFO ] checking rc: yes
[     INFO ] checking rc_x: no
[     INFO ] checking ud_mlx5: no
[     INFO ] checking all: yes
[     INFO ] Using random seed of 5586
Note: Google Test filter = ud/uct_p2p_am_test.am_zcopy/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ud/uct_p2p_am_test
[ RUN      ] ud/uct_p2p_am_test.am_zcopy/0
[mu1581:28734:0]    ud_verbs.c:301  Fatal: Send completion (wr_id=0xFAAFFAAF with error: local length error 
 
/users/ngraham/myprojects/ucx/src/uct/ib/ud/verbs/ud_verbs.c: [ uct_ud_verbs_iface_poll_tx() ]
      ...
      297 
      298     if (ucs_unlikely(wc.status != IBV_WC_SUCCESS)) {
      299         ucs_fatal("Send completion (wr_id=0x%0X with error: %s ",
==>   300                   (unsigned)wc.wr_id, ibv_wc_status_str(wc.status));
      301         return;
      302     }
      303 
```

Hardware: Mustang - Xtreme-X 1320H-LANL, Opteron 12 Core 2.30 GHz, Infiniband QDR

driver version: libibverbs-1.1.8-4.el6.x86_64
FW version:    2.9.1000

ibstat output:
```
CA 'mlx4_0'
    CA type: MT26428
    Number of ports: 1
    Firmware version: 2.9.1000
    Hardware version: b0
    Node GUID: 0x002590ffff1668c8
    System image GUID: 0x002590ffff1668cb
    Port 1:
        State: Active
        Physical state: LinkUp
        Rate: 40
        Base lid: 1246
        LMC: 0
        SM lid: 250
        Capability mask: 0x02510868
        Port GUID: 0x002590ffff1668c9
        ​Link layer: InfiniBand
```

The log file can be seen at: https://gist.github.com/nrgraham23/208fdff27d71b6f1d6c6bb227a7dadb4

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1022

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1868/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2518/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1869/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1873/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shssf pls take a look

**Comment by shssf** [comment]
:+1:

**Comment by yosefe** [comment]
@shssf it would be fixed by #1030 anyway right?

**Comment by shssf** [comment]
@yosefe Yes, you rigth, it will be reimplemented in 1030. I would propose to merge this PR anyway because we will have a lot more changes in 1030 and it is better to stabilize the mainline ASAP.

**Pull request merged**
