### PR TITLE
BUILD: include cudamem.h in source tarball

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6830/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6832/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy how did we miss it in jenkins?

**Comment by amaslenn** [comment]
@yosefe will you create v1.3.1?

**Comment by yosefe** [comment]
yes :(

**Comment by bureddy** [comment]
@yosefe we missed it because jenkin's build_release_pkg() checking is without cuda environment

**Comment by shamisp** [comment]
@bureddy Do you want to say that we do not run any testing with cuda env ?

**Comment by shamisp** [comment]
Maybe we should wait a bit before we do 1.3.1 just to see if there are any other issues that will come up. But please go ahead and open back port PR for v1.3 branch

**Comment by miked-mellanox** [comment]
@shamisp - we run tests on cuda env as part of jenkins CI.
We did not run package (make distcheck, rpm/deb buildup test) in cuda setup, now Deva added it as well.

**Comment by shamisp** [comment]
@miked-mellanox maybe this is something that we have to run with each CI cycle, unless it is time killer.

**Comment by bureddy** [comment]
@shamisp  we did testing with cuda env for cuda functionality.  but didn't test tarball distcheck build in cuda env.
It is backported to 1.3.x in https://github.com/openucx/ucx/pull/2528

**Pull request merged**
