### PR TITLE
UCP/MM: memory type for ucp memory map

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by bureddy** [comment]
@yosefe  please review.  
may be we need to expose  mem type in ucp_mem_map() API  to indicate memory type of passed address.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5783/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy do we need this for users like MPI or TF?

**Comment by bureddy** [comment]
@yosefe I don't have a use case to expose this n the ucp_mem_map() api now.  I have to check with Arch team(Yaniv) for this.  will revisit on this.

**Pull request merged**
