### PR TITLE
TEST/ASYNC: Reduce threshold for number of events.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1445/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3371/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls review

**Comment by alinask** [comment]
@yosefe why do want to reduce this value?

**Comment by yosefe** [comment]
@alinask when the system is under load, there is higher probability some events will be coalesced so the number of delivered events will be lower than 50% of the number of original events

**Pull request merged**
