### PR TITLE
TEST/FLUSH: Fix counting active messages - pending should be counted too

### LINKED ISSUE #965: hang in cm/test_uct_stats.flush_wait_iface/2
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2367/console
w/o valgrind

```
13:59:39 [ RUN      ] cm/test_uct_stats.flush_wait_iface/2
13:59:46 [1473677986.628758] [jenkins03:2529 :3]       cm_iface.c:210  UCX  ERROR SIDR request error, status: response timeout error
13:59:46 [1473677986.628793] [jenkins03:2529 :3]       cm_iface.c:210  UCX  ERROR SIDR request error, status: response timeout error
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #965

### CODE REVIEW

**Comment by yosefe** [comment]
@shssf pls take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2744/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/153/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2126/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2130/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:bgateNEW:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2131/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/158/ for details.

**Pull request merged**
