### PR TITLE
DOC: Rename 'doc' folder to 'docs'

### PR DESCRIPTION
**Pull request by yosefe**
## Why
In order to support read-the-docs, move all documentation under "docs" subfolder

## How
preview of RTD site: https://openucx.readthedocs.io/en/topic-read-the-docs/index.html

### CODE REVIEW

**Comment by shamisp** [comment]
Overall looks good to me. Are there any other external dependencies (srpm) that we will break ?

**Comment by shamisp** [comment]
@tonycurtis @bbenton please take a look

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 22-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/5996623f12f929924710d4aeb925b255c6ea0614/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/a267d0e306f012798d96af75333b213c16b4a211/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/a6c8e0860d4d7f11b56df8237b8cd1aa72f7230a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/fd79ac4808eb40b0299a8f269e53a2293b1a454f/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/b44e8774434170caf2528a60ef6ab3dcc02716ec/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/e165129d64c5b1d6394223e077a859c6f08fedb8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/43f1d69de02585e756bf96477e74d9bd38877030/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/919298b4e4a7d50ff960ee7745df752af9a76185/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/02b50396bf778d3e5323672599dabc1f78fbd81b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/a8ecd0c703a5a1cfdd69d2fa7ae18345db5ed315/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/287ac9b324bc0bb4c63d5e35a599424cb2eea929/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/a5a9ffa2b36b8bc1d4f6877cba77ddc982d55a47/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/fcd698c0fc991387d03c1a9d2baef1d60d014a96/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/85e85833c0a76390f5452dff9752216a20ae7bdd/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/16104fcf1c57e157d39b54d3719759d279c28738/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/4e0b9e2d3f23d4ee7ca176e177e3b3ac2d44bb87/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/29fbe9f9ad66b0480097cd3d9a5cbb1c19f1c749/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/6e140eba3f2a81880ffdf9ef82fb803af917c28d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/0462f1a354c04eb2f6a55c6bd434e1042b356e6f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/c5914e43665d1677b96f63485e8b700b8ffa0e09/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/1b63a4362ca75760d7e49915d19a14b43f5af924/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/3b5d204c5c11878928f471091a5c91a3a34be04d/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/687ca086ef04d41d3afd5cf4277db03c00846b01/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/73a40f62006fae7e9318170d79e683be5d451a5d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70cbbabd38c0d8084cfb8fe169497225/raw/d667f5cf87c7b1ad09d61d0c82cb2dac2c4b3ec5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
> Overall looks good to me. Are there any other external dependencies (srpm) that we will break ?

Should not break since doc install path has not changed

**Comment by shamisp** [comment]
Ping - @tonycurtis @bbenton - this is mostly technical change. I want to make sure that we don't break anything in your workflow.

**Comment by tonycurtis** [comment]
> On Dec 17, 2019, at 10:43 AM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> Ping - @tonycurtis <https://github.com/tonycurtis> @bbenton <https://github.com/bbenton> - this is mostly technical change. I want to make sure that we don't break anything in your workflow.
> 

Wait, there’s a documentation directory? ;)

Applied the patch, can’t see any difference in use.

Tony

**Pull request merged**
