### PR TITLE
UCP/TAG: Expected match latency optimization.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1540/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3461/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
it reduces latency for expected messages (i guess compiler can generate more efficient code this way)

**Comment by brminich** [comment]
Have you measured this somehow? Can you please add a comment ? (otherwise someone can change it back later, as it is not obvious)

**Comment by yosefe** [comment]
@brminich updated the comment.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1544/ for details.

**Comment by brminich** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3463/ for details (Mellanox internal link).

**Pull request merged**
