### PR TITLE
JUCX: set memory address of registered memory.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
 Set memory address of start of registered memory.

## Why ?
Need to do RDMA operations (ucp_get_nb/ucp_put_np, etc).

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9925/ for details (Mellanox internal link).

**Comment by petro-rudenko** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9932/ for details (Mellanox internal link).

**Comment by petro-rudenko** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9939/ for details (Mellanox internal link).

**Pull request merged**
