### PR TITLE
TEST/UCP: Disconnect all endpoints during test cleanup.

### LINKED ISSUE #2050: Bus error in shm XPMEM ucp_ep_destroy
There is a possible ordering of events that causes a bus error on disconnect using a UCP ep that is connected with XPMEM. `Caught signal 7 (Bus error: nonexistent physical address)`

Investigation show that this is reliably reproducible in the test `shm/test_ucp_stream_many2one.drop_data`

A more detailed GDB backtrace is pasted below, but the highlight is that it looks like xpmem regions are deregistered and then there is an attempt to access them. 

Tail end of log level data:
```
[1512659430.586462] [nid00762:14204:0]       mm_xpmem.c:71   UCX  TRACE xpmem removed segment 0x40000377c
[1512659430.586508] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.586519] [nid00762:14204:0]       mm_xpmem.c:71   UCX  TRACE xpmem removed segment 0x20000377c
[1512659430.586529] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x30f7af0 [id=13] ucp_worker_iface_event() from hash
[1512659430.586534] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x30f7af0 [id=13] ucp_worker_iface_event()
[1512659430.586539] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x30f7af0 [id=13] ucp_worker_iface_event()
[1512659430.586688] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.586704] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x30f7bd0 [id=15] ucp_worker_iface_event() from hash
[1512659430.586709] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x30f7bd0 [id=15] ucp_worker_iface_event()
[1512659430.586715] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x30f7bd0 [id=15] ucp_worker_iface_event()
[1512659430.587137] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.587423] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_requests destroyed
[1512659430.587441] [nid00762:14204:0]     ucp_worker.c:164  UCX  DEBUG worker 0x31036d0: remove active message handlers
[1512659430.587446] [nid00762:14204:0]     ucp_worker.c:1173 UCX  DEBUG worker 0x31036d0: destroy all endpoints
[1512659430.587451] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_am_bufs destroyed
[1512659430.587455] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_reg_bufs destroyed
[1512659430.587457] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_rndv_get destroyed
[1512659430.587462] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x30f8410 [id=16] ucp_worker_iface_event() from hash
[1512659430.587473] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x30f8410 [id=16] ucp_worker_iface_event()
[1512659430.587478] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x30f8410 [id=16] ucp_worker_iface_event()
[1512659430.587488] [nid00762:14204:0]       mm_xpmem.c:71   UCX  TRACE xpmem removed segment 0x80000377c
[1512659430.587530] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.587539] [nid00762:14204:0]       mm_xpmem.c:71   UCX  TRACE xpmem removed segment 0x60000377c
[1512659430.587549] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x30ff4d0 [id=18] ucp_worker_iface_event() from hash
[1512659430.587553] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x30ff4d0 [id=18] ucp_worker_iface_event()
[1512659430.587558] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x30ff4d0 [id=18] ucp_worker_iface_event()
[1512659430.587696] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.587712] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x30ff270 [id=20] ucp_worker_iface_event() from hash
[1512659430.587717] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x30ff270 [id=20] ucp_worker_iface_event()
[1512659430.587723] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x30ff270 [id=20] ucp_worker_iface_event()
[1512659430.588051] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.588308] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_requests destroyed
[1512659430.588320] [nid00762:14204:0]     ucp_worker.c:164  UCX  DEBUG worker 0x311d870: remove active message handlers
[1512659430.588326] [nid00762:14204:0]     ucp_worker.c:1173 UCX  DEBUG worker 0x311d870: destroy all endpoints
[1512659430.588330] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_am_bufs destroyed
[1512659430.588334] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_reg_bufs destroyed
[1512659430.588338] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_rndv_get destroyed
[1512659430.588343] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x3113c60 [id=21] ucp_worker_iface_event() from hash
[1512659430.588357] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x3113c60 [id=21] ucp_worker_iface_event()
[1512659430.588360] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x3113c60 [id=21] ucp_worker_iface_event()
[1512659430.588371] [nid00762:14204:0]       mm_xpmem.c:71   UCX  TRACE xpmem removed segment 0xc0000377c
[1512659430.588412] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.588421] [nid00762:14204:0]       mm_xpmem.c:71   UCX  TRACE xpmem removed segment 0xa0000377c
[1512659430.588430] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x31194b0 [id=23] ucp_worker_iface_event() from hash
[1512659430.588435] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x31194b0 [id=23] ucp_worker_iface_event()
[1512659430.588440] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x31194b0 [id=23] ucp_worker_iface_event()
[1512659430.588574] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.588588] [nid00762:14204:0]          async.c:130  UCX  DEBUG removed async handler 0x3119510 [id=25] ucp_worker_iface_event() from hash
[1512659430.588593] [nid00762:14204:0]          async.c:482  UCX  DEBUG removing async handler 0x3119510 [id=25] ucp_worker_iface_event()
[1512659430.588598] [nid00762:14204:0]          async.c:145  UCX  DEBUG release async handler 0x3119510 [id=25] ucp_worker_iface_event()
[1512659430.588923] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool mm_recv_desc destroyed
[1512659430.589172] [nid00762:14204:0]          mpool.c:126  UCX  DEBUG mpool ucp_requests destroyed
[nid00762:14204:0] Caught signal 7 (Bus error: nonexistent physical address)
[1512659430.589186] [nid00762:14204:0]          flush.c:179  UCX  DEBUG disconnect ep 0x3147b60
[1512659430.589190] [nid00762:14204:0]          flush.c:30   UCX  TRACE ep 0x3147b60: progress flush req 0x3169300, lanes 0x1 count 1
```
Head of the GDB back trace (cut out the gtest portions)
```
(gdb) bt
#0  0x00002aaaacbc93bf in waitpid () from /lib64/libpthread.so.0
#1  0x00002aaaaacf06f5 in ucs_debugger_attach () at debug/debug.c:702
#2  0x00002aaaaacf0b81 in ucs_handle_error (
    error_type=0x377e <Address 0x377e out of bounds>, 
    message=0x2aaaaaaefd40 "\020") at debug/debug.c:985
#3  0x00002aaaaacf154b in ucs_debug_handle_error_signal (signo=14206, 
    cause=0x2aaaaaaefd40 "\020", fmt=0x0) at debug/debug.c:932
---Type <return> to continue, or q <return> to quit---
#4  0x00002aaaaacf1217 in ucs_error_signal_handler (signo=14206, 
    info=0x2aaaaaaefd40, context=0x0) at debug/debug.c:949
#5  <signal handler called>
#6  uct_mm_ep_update_cached_tail (ep=<optimized out>) at sm/mm/mm_ep.c:202
#7  uct_mm_ep_flush (tl_ep=0x31482b0, flags=0, comp=0x3169388)
    at sm/mm/mm_ep.c:420
#8  0x00002aaaab3afbec in uct_ep_flush (ep=<optimized out>, 
    flags=<optimized out>, comp=<optimized out>)
    at /lustre/atlas/scratch/bzf/csc040/ucx-work/721904/ucx/src/uct/api/uct.h:2042
#9  ucp_ep_flush_progress (req=0x31482b0) at rma/flush.c:48
#10 0x00002aaaab3b0b13 in ucp_ep_flush_internal (ep=0x31482b0, uct_flags=0, 
    req_cb=0x3169388, req_flags=2868159200, flushed_cb=0x3145ee0)
    at rma/flush.c:212
#11 0x00002aaaab39aa6b in ucp_ep_close_nb (ep=0x31482b0, mode=0)
    at core/ucp_ep.c:459
#12 0x00002aaaab39a845 in ucp_ep_destroy (ep=0x31482b0) at core/ucp_ep.c:488
#13 0x000000000094274c in release (this=<optimized out>)
    at ./common/test_helpers.h:380
```
Going to the `uct_mm_ep_flush` function (because I can't see ep in uct_mm_ep_update_cached_tail) I can get the following out of tl_ep...
```
(gdb) p ((uct_mm_ep_t*)tl_ep)->fifo_ctl
$6 = (uct_mm_fifo_ctl_t *) 0x2aaab01b4000
(gdb) p ((uct_mm_ep_t*)tl_ep)->fifo_ctl->tail
Cannot access memory at address 0x2aaab01b4080
```
So it looks like it's deregistered, then in flush in the disconnect it tries to update the cached tail by accessing the freshly deregistered memory region and failing.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2050

### CODE REVIEW

**Comment by yosefe** [comment]
@evgeny-leksikov pls take a look

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5667/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5675/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5687/ for details (Mellanox internal link).

**Pull request merged**
