### PR TITLE
RPM: follow Fedora guidelines in rpm spec

### PR DESCRIPTION
**Pull request by amaslenn**
Changes were approved on the review: https://bugzilla.redhat.com/show_bug.cgi?id=1474033

### CODE REVIEW

**Comment by amaslenn** [comment]
I expect some failures, a review can be postponed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4916/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4918/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4932/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4950/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4951/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@amaslenn 
```
12:38:14 Requires(rpmlib): rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
12:38:14 Checking for unpackaged file(s): /usr/lib/rpm/check-files /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp0-x86-64/worker/0/build-test/_rpm
12:38:14 Checking for unpackaged file(s): /usr/lib/rpm/check-files /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp0-x86-64/worker/0/build-test/_rpm
12:38:14 
12:38:14 
12:38:14 RPM build errors:
12:38:14     File listed twice: /usr/share/doc/packages/ucx
12:38:14     File not found: /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-sles11-sp0-x86-64/worker/0/build-test/_rpm/usr/share/doc/packages/ucx/examples
12:38:14 
Build step 'Execute shell' marked build as failure
```

**Comment by amaslenn** [comment]
@yosefe I'm working on it, please postpone review.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4979/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
Ready for review now.

**Comment by yosefe** [comment]
@shamisp do you want to take a look?

**Comment by shamisp** [comment]
is this the spec that was accepted to fedora ?

**Comment by shamisp** [comment]
Here is my concern. The spec states that it is for version 1.2.1, which already was released and we pushing this 1.2.1 change after this tag. This is odd..

**Comment by amaslenn** [comment]
@shamisp yes, it is the spec approved by Fedora.
Spec should contain version == product version. Once it is merged we can bump version to 1.2.2.

**Comment by shamisp** [comment]
What about the spec file in master ? What version we will put there ?

**Comment by amaslenn** [comment]
It will be 1.3.0, like we state in configure.

**Comment by shamisp** [comment]
Since it is coming after official 1.2.1 release we should use version 1.2.2 for the 1.2.x branch.

**Comment by amaslenn** [comment]
Do you want to include version change into this PR?

**Comment by yosefe** [comment]
@amaslenn yes

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5022/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5027/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Please squash the changes.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5079/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
bot:mlx:retest

**Comment by alinask** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5103/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5119/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
fails because the PR which disabled jenkins on ppc was not merged to v1.2

**Comment by shamisp** [comment]
Then let’s bring it to 1.2...

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5126/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
I also tried to run it manually on `hpc-test-node2`, and see some fails:
```
[ RUN      ] shm/test_ucp_atomic64.atomic_add/1
/labhome/andreyma/workspace/ucx/contrib/../test/gtest/common/test.cc:135: Failure
Failed
Got 2 valgrind errors during the test
[  FAILED  ] shm/test_ucp_atomic64.atomic_add/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib (3141 ms)
[ RUN      ] shm/test_ucp_atomic64.atomic_fadd_nb/2
/labhome/andreyma/workspace/ucx/contrib/../test/gtest/common/test.cc:135: Failure
Failed
Got 2 valgrind errors during the test
[  FAILED  ] shm/test_ucp_atomic64.atomic_fadd_nb/2, where GetParam() = \mm,\knem,\cma,\xpmem,ib (3045 ms)
[ RUN      ] shm/test_ucp_atomic64.unaligned_atomic_add/2
/labhome/andreyma/workspace/ucx/contrib/../test/gtest/common/test.cc:135: Failure
Failed
Got 2 valgrind errors during the test
[  FAILED  ] shm/test_ucp_atomic64.unaligned_atomic_add/2, where GetParam() = \mm,\knem,\cma,\xpmem,ib (3072 ms)
[ RUN      ] shm/test_ucp_atomic64.atomic_fadd/1
/labhome/andreyma/workspace/ucx/contrib/../test/gtest/common/test.cc:135: Failure
Failed
Got 2 valgrind errors during the test
[  FAILED  ] shm/test_ucp_atomic64.atomic_fadd/1, where GetParam() = \mm,\knem,\cma,\xpmem,ib (3216 ms)
[ RUN      ] shm/test_ucp_atomic64.atomic_fadd_nb/0
^Cmake: *** [test_valgrind] Killed
```

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5149/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5169/ for details (Mellanox internal link).

**Comment by alinask** [comment]
Can this be merged?

**Pull request merged**
