### PR TITLE
CI: update azure pipelines readme file

### PR DESCRIPTION
**Pull request by changchengx**
## What
1. update ```azure-pipelines.md``` to align with document usage.
2. exclude ```azure-pipelines.md``` file in ```azure-pipelines-pr.yml```

### CODE REVIEW

**Comment by yosefe** [comment]
pls add this file to the exclude list in azure-pipelines-pr.yml

**Comment by changchengx** [comment]
excluded ```azure-pipelines.md``` file in ```azure-pipelines-pr.yml```

**Comment by Al3xR01** [comment]
The readme file is outdated and does not accurately reflect the current state of the project.
While a complete rewrite would be ideal, it may not be a priority task at this time.

**Comment by changchengx** [comment]
@Al3xR01 I agree with you. As you have more expertise knowledge about the pipeline, if it's needed, I could close this RP, then you or others could give a full refresh of this document.
As a CI user, I think it's better to upload/duplicate some docker container to be docker hub, especially ```stack checker``` and ```code format checker```, then I could run these test cases locally.

**Pull request closed without merging**
