### PR TITLE
UCT/RC/TEST: Fix configuration for maximal number of WRs.

### LINKED ISSUE #850: hang on Allreduce with rc_x
There is a hang on Allreduce with np=96 with rc_x at a message size of 16384. (rc and ud are ok). Reproduces on every run.

Probably caused by one of the rc commits from last week because when tested with ucx from the following commit it worked fine:

No hang:
```
commit 6cb0d7189bd53534575a992a2bdb27dd1cb66e22
Merge: 2ab9962 b1688ae
Author: Yossi <yosefe@mellanox.com>
Date:   Thu Jun 16 12:40:09 2016 +0300

    Merge pull request #833 from yosefe/topic/rc-move-txqp-stats

    UCT/RC: Attach txqp stats to ep instead of iface.
```

$mpirun -np 96 --bind-to core --map-by node  --display-map -mca pml ucx -x UCX_TLS=rc_x,mm  ./IMB-MPI1 Allreduce -npmin 96

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #850

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2043/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1408/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2044/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2048/ for details.

**Comment by yosefe** [comment]
@alex-mikheev can you pls review?

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
