### PR TITLE
UCT/API: Fix reference in documentation.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3960/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bbenton pls take a look

**Comment by shamisp** [comment]
good catch. 👍

**Comment by bbenton** [comment]
:+1:

**Pull request merged**
