### PR TITLE
Fixes for compatibility with MLNX_OFED 4.2

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4905/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4906/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4907/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4909/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4910/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4911/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@MattBBaker can you pls post ORNL failure?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4912/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
Test failure in rcache.
```
[----------] 10 tests from test_rcache, where TypeParam = 
[ RUN      ] test_rcache.get_unmapped/mt_6
[       OK ] test_rcache.get_unmapped/mt_6 (14 ms)
[ RUN      ] test_rcache.merge_with_unwritable/mt_6
[       OK ] test_rcache.merge_with_unwritable/mt_6 (6 ms)
[ RUN      ] test_rcache.merge_invalid_prot/mt_6
[       OK ] test_rcache.merge_invalid_prot/mt_6 (34 ms)
[ RUN      ] test_rcache.merge_expand_prot/mt_6
/var/lib/jenkins/jobs/UCX/workspace/contrib/../test/gtest/ucs/test_rcache.cc:55: Failure
Error: Input/output error
terminate called after throwing an instance of 'ucs::test_abort_exception'
  what():  std::exception
make: *** [test] Aborted
make: Leaving directory `/var/lib/jenkins/jobs/UCX/workspace/build-tests/1508878806/test/gtest'
Build step 'Execute shell' marked build as failure
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4920/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4921/ for details (Mellanox internal link).

**Pull request merged**
