### PR TITLE
rpm: apply changes to comply Fedora guidelines

### PR DESCRIPTION
**Pull request by amaslenn**
Spec file now compliant with Fedora guidelines.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4315/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4316/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4322/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
bot:bgate:retest

**Comment by amaslenn** [comment]
MellanoxLab build failed because of issue #1770.
@MattBBaker could you please post ORNL log?

**Comment by amaslenn** [comment]
@alinask @shamisp @yosefe please review.

**Comment by MattBBaker** [comment]
It's a local error. Retesting.

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by shamisp** [comment]
This should be must commit before we bump up new version

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4332/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4333/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4337/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4341/ for details (Mellanox internal link).

**Pull request merged**
