### PR TITLE
IB: do not limit amount of the send tx buffers

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe 
This is a workaround for https://github.com/openucx/ucx/issues/1288
until adaptive cq tx moderation is implemented

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3347/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/879/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2842/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
The new test fails:
```
15:12:38 [----------] 2 tests from dc_mlx5/uct_p2p_am_tx_bufs
15:12:38 [ RUN      ] dc_mlx5/uct_p2p_am_tx_bufs.am_tx_max_bufs/1
15:12:39 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node/contrib/../test/gtest/uct/test_p2p_am.cc:580: Failure
15:12:39 Value of: status
15:12:39   Actual: -2
15:12:39 Expected: UCS_OK
15:12:39 Which is: 0
15:12:39 
[  FAILED  ] dc_mlx5/uct_p2p_am_tx_bufs.am_tx_max_bufs/1, where GetParam() = dc_mlx5/mlx5_0:1/loopback (153 ms)
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/886/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3355/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/895/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3362/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2858/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2862/ for details (Mellanox internal link).

**Pull request merged**
