### PR TITLE
TEST/jenkins: fix port number

### LINKED ISSUE #1308: Jenkins/Hello_world: test port selection
In the Jenkins script we have several client/server tests that are required system port to establish connection.
The port has calculated as 
```
UCP_TEST_HELLO_WORLD_PORT=$(( 10000 + ${BASHPID} ))
```
If the `${BASHPID}` bigger than 51000 the tests are failed due `sockaddr_in::sin_port` has been overflowed

The system has following limitations on port ranges:
```
$cat /proc/sys/net/ipv4/ip_local_port_range
32768   61000
```
Need to implement an automatic procedure to find valid free port for communication.

### PR DESCRIPTION
**Pull request by shssf**
This fixes #1308 
Perhaps, it is better to add:
1. Check number of the function input parameters. Not clear what to do if check failed. `exit 1`?
2. Implement a conditional to avoid `while` loop hangs

### CODE REVIEW

**Comment by shssf** [comment]
One more performance improvement might be using an array for `netstat` to `grep` it in the loop.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/920/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2890/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
AFAIU this solution will not work when multiple processes on the same host - they might discover same free port and try to use it.

**Comment by shssf** [comment]
@yosefe It shouldn't. This procedure dosn't use `/` operation. It uses `+` and `-` operations only. The initial value for this linear algorithm is the shell PID. So, if PIDs of two process are different, this procedure must provide different ports.

**Comment by yosefe** [comment]
@shssf suppose following case:
pid1=100
pid2=101
first free port is 1024.
will they both try to use 1024?

**Comment by shssf** [comment]
pid1 will be incremented by 100 and goes to 1100 as the first port above 1024.
pid2 do the same and will try to use port 1101

**Comment by yosefe** [comment]
and if pid1=100 and pid2=200?

**Comment by yosefe** [comment]
i would suggest to use 12345+$EXECUTOR_NUMBER

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2891/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/929/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2896/ for details (Mellanox internal link).

**Pull request closed without merging**
