### PR TITLE
ASYNC/TEST: Fix handling missed fd for the second time.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
The code does not compile on our systems. I will post the log on Monday.

**Comment by yosefe** [comment]
retest this please

**Comment by mellanox-github** [comment]
bot:retest

**Comment by mellanox-github** [comment]
bot:retest

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/707/ for details.

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
bot:retest

**Comment by yosefe** [comment]
bot:retest

**Comment by yosefe** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/156/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/709/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/712/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/710/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/716/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/717/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/719/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/157/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/722/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/160/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/723/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/726/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/162/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/163/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/727/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/164/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
