### PR TITLE
TOOLS/PERF: Fix perftest compilation with CFLAGS.

### LINKED ISSUE #1456: Compile error redefining UCS_BIT and some types
At commit 551d453caaac62b66769cbaba6b797b5d3b49338, master branch

Problem seen on CentOS 6.6 (gcc 4.4.7) and Fedora 25 (gcc 6.3.1)

(RHEL7.1 was ok, gcc 4.8.5)

```
make[2]: Entering directory `/gpfs/home/arcurtis/src/ucx/master/build/src/tools/perf'
libtool: compile:  gcc -DHAVE_CONFIG_H -I../../.. -O3 -g -Wall -Werror -I/gpfs/home/arcurtis/opt/ucx/include -mavx -I/opt/knem-1.1.1.90mlnx/include "-DCPU_FLAGS=|avx" -I/opt/knem-1.1.1.90mlnx/include -I/gpfs/home/arcurtis/src/ucx/master/build/../source/src -I/gpfs/home/arcurtis/src/ucx/master/build/src -fopenmp ../../../../source/src/tools/perf/perftest.c -c  -fPIC -DPIC -o .libs/perftest.o
In file included from ../../../../source/src/tools/perf/libperf.h:19,
                 from ../../../../source/src/tools/perf/perftest.c:15:
/gpfs/home/arcurtis/opt/ucx/include/ucs/sys/math.h:79:1: error: "UCS_BIT" redefined
In file included from /gpfs/home/arcurtis/opt/ucx/include/ucs/type/status.h:12,
                 from /gpfs/home/arcurtis/opt/ucx/include/uct/api/uct_def.h:10,
                 from /gpfs/home/arcurtis/opt/ucx/include/uct/api/uct.h:12,
                 from ../../../../source/src/tools/perf/libperf.h:17,
                 from ../../../../source/src/tools/perf/perftest.c:15:
/gpfs/home/arcurtis/opt/ucx/include/ucs/sys/compiler_def.h:32:1: error: this is the location of the previous definition
In file included from ../../../../source/src/tools/perf/libperf_int.h:16,
                 from ../../../../source/src/tools/perf/perftest.c:16:
/gpfs/home/arcurtis/opt/ucx/include/ucs/time/time.h:20: error: conflicting types for ‘ucs_time_t’
/gpfs/home/arcurtis/opt/ucx/include/ucs/time/time_def.h:18: note: previous declaration of ‘ucs_time_t’ was here
In file included from /gpfs/home/arcurtis/opt/ucx/include/ucs/async/signal.h:11,
                 from /gpfs/home/arcurtis/opt/ucx/include/ucs/async/async.h:11,
                 from ../../../../source/src/tools/perf/libperf_int.h:17,
                 from ../../../../source/src/tools/perf/perftest.c:16:
/gpfs/home/arcurtis/opt/ucx/include/ucs/datastruct/list.h:16: error: redefinition of ‘struct ucs_list_link’
/gpfs/home/arcurtis/opt/ucx/include/ucs/datastruct/list.h:19: error: conflicting types for ‘ucs_list_link_t’
/gpfs/home/arcurtis/opt/ucx/include/ucs/datastruct/list_types.h:17: note: previous declaration of ‘ucs_list_link_t’ was here
In file included from ../../../../source/src/tools/perf/libperf_int.h:17,
                 from ../../../../source/src/tools/perf/perftest.c:16:
/gpfs/home/arcurtis/opt/ucx/include/ucs/async/async.h:43: error: redefinition of typedef ‘ucs_async_event_cb_t’
/gpfs/home/arcurtis/opt/ucx/include/ucs/async/async_fwd.h:25: note: previous declaration of ‘ucs_async_event_cb_t’ was here
/gpfs/home/arcurtis/opt/ucx/include/ucs/async/async.h:81: error: conflicting types for ‘ucs_async_add_timer’
/gpfs/home/arcurtis/opt/ucx/include/ucs/async/async_fwd.h:64: note: previous declaration of ‘ucs_async_add_timer’ was here
make[2]: *** [perftest.lo] Error 1
make[2]: Leaving directory `/gpfs/home/arcurtis/src/ucx/master/build/src/tools/perf'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/gpfs/home/arcurtis/src/ucx/master/build'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1456

### CODE REVIEW

**Comment by yosefe** [comment]
@tonycurtis can you please check if this patch resolves the compilation issue?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1567/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3485/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3488/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
looking good

**Pull request merged**
