### PR TITLE
TOOLS/UCM/UCT: Build CUDA as a separate loadable module

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8753/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
@yosefe I see following on vulcan-jenkins's ucx_perftest with cuda. is it failed to load uct gdr copy module? I see that vulcan-jenkins have gdrcopy module loaded. 

```
15:00:22 [1549890022.953612] [vulcan-jenkins:12855:0]    ucp_context.c:599  UCX  WARN  transport 'gdr_copy' is not available
15:00:22 [1549890022.956082] [vulcan-jenkins:12865:0]    ucp_context.c:599  UCX  WARN  transport 'gdr_copy' is not available
```

**Comment by yosefe** [comment]
@bureddy is this with this PR or with master?
What is the command line?

**Comment by bureddy** [comment]
In this PR Jenkins : http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8753/label=vulcan-jenkins,worker=0/consoleFull

**Comment by yosefe** [comment]
@bureddy it seems gdrcopy currently depends on cuda code to detect MDs, so must load gdrcopy module after cuda module is fully loaded. 
for long run, i think we need to remove this dependency, and make gdr_copy MD "host" instead of "cuda" memory

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8784/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8785/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8788/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@bureddy can you pls review the gdrcopy fix?

**Pull request merged**
