### PR TITLE
UCP/RNDV-PUT: fixed crash on rndv-put mode

### PR DESCRIPTION
**Pull request by hoopoepg**
- crash affected on knem tl (combination of MEMH/RKEY)

### CODE REVIEW

**Comment by yosefe** [comment]
looks like copy paste bug @xinzhao3

**Comment by xinzhao3** [comment]
@yosefe @hoopoepg yes it should be compute_rndv_put instead of get. Thanks for fixing this.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5500/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5506/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe good to go?

**Pull request merged**
