### PR TITLE
UCS/UCT/IB: Ignore PFs without RDMA cap on BF2 according to its gid_t…  - v1.9.x

### PR DESCRIPTION
**Pull request by bureddy**
porting https://github.com/openucx/ucx/pull/5965 to v1.9.x

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

**Comment by bureddy** [comment]
```
ucx_info -e -u t -n 2
[1611200685.760698] [swx-rdmz-ucx-arm-hwi:50874:0]        ib_mlx5.c:410  UCX  ERROR mlx5dv_devx_alloc_uar() failed: Operation not supported
<Failed to create UCP endpoint>

```

**Comment by bureddy** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
bot:pipe:retest

**Pull request merged**
