### PR TITLE
1.6.0 version updates in the main tree 

### PR DESCRIPTION
**Pull request by shamisp**
1.6.0 version updates in the main tree

### CODE REVIEW

**Comment by tonycurtis** [comment]
> On Jul 19, 2019, at 4:02 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> @shamisp <https://github.com/shamisp> requested your review on: #3907 <https://github.com/openucx/ucx/pull/3907> 1.6.0 version updates in the main tree .
> 

Looks good

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11366/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/0fb53123411920f7468af09e60c1c8b9e9963312/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/1c88ff7eae3da7d9e4443ff7661c18269b95b8d9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/d850b2938773cd2ef48df8bc3b55328e90fe3a81/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/b35041cf75479fcce87583f1d9cfdbbbc718213c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/08e2f815517b3f50104d54fc2c527f828a4875f1/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/2dbc2176d995b3fc1a40bc62466ed4b77ebba6d6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/1181b4458f4a7c90bf97ed9dd943f3f28e8483ae/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/799384e69945b2f1369f379685a46287b2799c60/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/fabb79b403a0796742d7705241cb69e4b7dead8a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/a7bb751b8c72d95b9a99d42b952342e278a9a106/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/b17eb6f18604348452e424e2c06df7d2e674a6c8/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/b6be9c0be5c8f3d45b2ecaf30b0d86a34d549c4a/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/2bf55b86c86c4407837f37080a55bc003eeb3068/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/c563d89fe54374489ef5467c64e9e088bf409611/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/cfa5597f6509576edfa68c4bca13d64983c687fd/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/8fc583773cf0eefd98d2a52081f20cd2a8ca35e5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/489ed8a623c9cea5540c520d3e05ffa97da0943e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/f047139b14f5025efcbb79bab7ffcd39e3d78776/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/cc569d0e6d8fb4b304966cf45d94412a02a3e98a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/7009b6da01811f1c6cba1fbbc1d77b373af01f61/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/a00650c4f8b39c4d2138027dc5746954c3321ffc/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/9e50b3a9cbdc94b4668ace284c3a5b767f5288f1/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/d71cee9841ed952d2a697386641846b06711b6d4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/cd078ff85b17bf05d42788801fa6c31d1eb1ef9c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/33cb25153154f79c7890ff9bd40df96ca2c953a5/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/be51798fe1533f841fabe015622cd11691403839/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/8c8fd7f08a3158a0411bea757ae60c010cf22311/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/76a402673057dddc3cdc16c9e197b420c1f3f9c9/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/35385bac584729db846dbcc7db5d41f0d5337748/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/6562e23d7e467a06d6b76c754616bac996b19a60/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/d888a4ab4d580b87f5682be7aeb40a3fd30c38fc/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/102322ed50802a958a46bd207624986ebebc66ce/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5bf74a59af18173b608958245eadf3f4/raw/8e534843031fd7e0b735a5852e474437df3b8832/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@shamisp 

NEWS:27
`- Multiple stability fixed in Verbs and MLX5 transports`
->
`- Multiple stability fixes in Verbs and MLX5 transports`

This is not related to your changes, but would do you think about including this fix into your PR?

**Comment by shamisp** [comment]
> @shamisp
> 
> NEWS:27
> `- Multiple stability fixed in Verbs and MLX5 transports`
> ->
> `- Multiple stability fixes in Verbs and MLX5 transports`
> 
> This is not related to your changes, but would do you think about including this fix into your PR?

I will fix in a separate PR. Good catch.

**Comment by dmitrygx** [comment]
> I will fix in a separate PR. Good catch.

@shamisp Thansk
I've prepared #3911 and #3912 (backport to v1.6.x branch)

**Pull request merged**
