### PR TITLE
UCT/RC/MLX5: Move noninline function to C file

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@Artemy-Mellanox

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8542/ for details (Mellanox internal link).

**Comment by Artemy-Mellanox** [comment]
BTW. why is it noninline?

**Comment by yosefe** [comment]
@Artemy-Mellanox it's noninline to avoid overheads of register save/restore for fast path

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8544/ for details (Mellanox internal link).

**Pull request merged**
