### PR TITLE
UCP: Add ucp_context_find_tl_md() to a devel header

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10396/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp can you pls take a look?

**Comment by shamisp** [comment]
@yosefe would not be it easier to limit "dev" extensions to TLs only? As for not it is purely syntax sugar that can reside inside of SHMEM.

**Comment by yosefe** [comment]
@shamisp we need a way to access from UCP to the underlying UCT objects
we can also expose it as official API

**Comment by shamisp** [comment]
@yosefe official exposure UCT object in UCP - meh. Unless we can express this in UCP terms, it does not make much sense.  So you problem is opaque structure of ```ucp_context_h``` ?

**Comment by yosefe** [comment]
> @yosefe official exposure UCT object in UCP - meh. Unless we can express this in UCP terms, it does not make much sense. So you problem is opaque structure of `ucp_context_h` ?

yes

**Comment by shamisp** [comment]
@hat is your idea for 'official' API for something like this ? Define UCP memory domains ?

**Comment by yosefe** [comment]
@shamisp no, just obtain UCT memory domains from UCP context

**Comment by shamisp** [comment]
@yosefe extracting UCT object from UCP is not a clean solution. Let's go with this one as for now.

**Pull request merged**
