### PR TITLE
UCP/CUDA-IPC: enable protocols using cuda-ipc for inter-node GPU transfers- v1.4.x

### PR DESCRIPTION
**Pull request by bureddy**
picked from master pr #2692

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7334/ for details (Mellanox internal link).

**Comment by bureddy** [comment]
bot:mlnx:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7335/ for details (Mellanox internal link).

**Pull request merged**
