### PR TITLE
Small fixes in tests

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2386/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1722/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1723/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev can you please take a look?

**Comment by shamisp** [comment]
👍

**Comment by alex-mikheev** [comment]
:+1:

**Pull request merged**
