### PR TITLE
IB/BUILD: Disable accel verbs if cannot use a shared BF.

### PR DESCRIPTION
**Pull request by yosefe**
See #420

### CODE REVIEW

**Comment by shamisp** [comment]
I think it is a good idea to do the both. Print the message and disable.

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/393/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/967/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/968/ for details.

**Comment by yosefe** [comment]
@miked-mellanox pls review

**Comment by miked-mellanox** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/970/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/395/ for details (Mellanox internal link).

**Pull request merged**
