### PR TITLE
UCP/API/DOC: Add clarification for ucp_ep_rkey_unpack()

### PR DESCRIPTION
**Pull request by yosefe**
@petro-rudenko @shamisp @tonycurtis

### CODE REVIEW

**Comment by shamisp** [comment]
👍 @tonycurtis ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10535/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@tonycurtis - are we good now ?

**Comment by tonycurtis** [comment]
+1

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10618/ for details (Mellanox internal link).

**Pull request merged**
