### PR TITLE
EXAMPLES/UCT: Rename PD to MD as PD is deprecated name

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What
_Describe what this PR is doing._ 

This PR applies the following changes:
- renames PD to MD in UCT "hello world" example
- minor fixes for misprints in the doc/doyxgen

## Why ?

Protection Domain is the deprecated name. Memory Domain is the new one.

## How ?
_It is optional but for complex PRs please provide information about the design,
architecture, approach, etc.

Studying source code of examples/uct

### CODE REVIEW

**Comment by hoopoepg** [comment]
ok to test

**Comment by shamisp** [comment]
@yosefe - do we need CLA for this ?

**Comment by yosefe** [comment]
@shamisp - @dmitrygladkov is with Mellanox org.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8678/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
@bbenton @tonycurtis please take a looks since the PR includes some spec changes

**Comment by dmitrygladkov** [comment]
@tonycurtis  Thank you!

> uct_hello_world.c:289
> 
> > ```
> > unsigned                num_md_resources; /* Number of memory domain */
> > ```
> 
> domains

Done

> > the collective operations include Barrier, All-to-one, All-to-all, and reduction operations.
> 
> Suggest being consistent with capitalization, would go with all lower case myself

Done


Please, find the commits updated

**Comment by dmitrygladkov** [comment]
ok to test

**Comment by dmitrygladkov** [comment]
@yosefe Looks like "ok to test" doesn't work for me. Should I be added in the some white list to successfully execute the command?

**Comment by shamisp** [comment]
👍  @tonycurtis can you please take a look

**Comment by yosefe** [comment]
@tonycurtis your comments were applied :)

**Comment by shamisp** [comment]
Okay, then we are all good.

**Pull request merged**
