### PR TITLE
Port fixes to v1.6.x: UCM events test, client/server example

### LINKED ISSUE #3686: (title changed) OpenMPI bogus warnings "UCX is unable to handle VM_UNMAP"
I am running:

```bash
$> ucx_info -v
# UCT version=1.5.1 revision 7e67a4b
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-rc --with-ud --with-dc --with-cm --with-mlx5-dv --with-ib-hw-tm --with-dm --with-mcpu --with-march --prefix=/opt/gnu/9.1.0/ucx/1.5.1
```
and OpenMPI 4.0.1 and GCC 9.1.0.

I am running on a local machine, which of course does not make sense with all the options, but configure just disables the extended features.

However, when running the simplest MPI program (only `MPI_init` and `MPI_finalize`) I get the following error:

```bash
[1560244589.726560] [nicpa-dtu:6527 :0]            sys.c:619  UCX  ERROR shmget(size=2097152 flags=0xfb0) for mm_recv_desc failed: Operation not permitted, please check shared memory limits by 'ipcs -l'
[1560244589.726561] [nicpa-dtu:6528 :0]            sys.c:619  UCX  ERROR shmget(size=2097152 flags=0xfb0) for mm_recv_desc failed: Operation not permitted, please check shared memory limits by 'ipcs -l'
```

```bash
$> ipcs -l

------ Messages Limits --------
max queues system wide = 32000
max size of message (bytes) = 8192
default max size of queue (bytes) = 16384

------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014398442373116
min seg size (bytes) = 1

------ Semaphore Limits --------
max number of arrays = 32000
max semaphores per array = 32000
max semaphores system wide = 1024000000
max ops per semop call = 500
semaphore max value = 32767
```

It seems unrelated to #3023 and #3668 since this is a local machine.

### PR DESCRIPTION
**Pull request by yosefe**
Picked from #3716
Fixes #3686

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10693/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 10 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/0b7a48a918b53bf8778ba732e0b24de8f1715d55/_main) | :x: FAILURE
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/d86135137cfe8d3084d73dbeca746ed0f32f11ba/hpc-test-node2_W3) | :x: FAILURE
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/1a0f5e1c680f1d221fb30e67677a9b066fe719af/hpc-test-node3_W2) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/0de7a47590b3152d623bd928e87c081d7e485d79/hpc-test-node3_W3) | :x: FAILURE
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/3bfe1496661a2257f0499c4b0390fc560e7ff845/hpc-test-node_W1) | :x: FAILURE
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/8cecc3e692569855a984b8e7226b36b3ad2cf544/hpc-test-node_W2) | :x: FAILURE
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/3de75ed5a8406e5afdcf42e852488783786a110c/hpc-test-node_W3) | :x: FAILURE
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/f4977d11c7172ff3ed06694902d74859f4975de9/vulcan-jenkins_W0) | :x: FAILURE
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/fff0813c43d328dc6e841d186335ab90154a9e05/vulcan-jenkins_W1) | :x: FAILURE
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/7ecbb2e1a045704cbf7d712db94d923f5b1cc8a9/vulcan-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/aecedc3fdee8581a43ef6f32cf2a0b3c472a7533/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/456a1805a84ecd4b52a0155182ba75eca345509d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/de23a75e8a71d7c9e7ae491f311f1f1c64fddc91/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/81d81abafa462d461e1ce82d394a679ef1141778/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/3e9fd9f861d8545177c9b53c0cee90cdd1a4545f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/a6389867d5827e1f599bcf88cf9d4f2c18a33303/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/207c39d2d0ce0af4f44a586f3c8d3ca3892cb86b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/1d6a0870c5484b3febff7a9e9c2ce4b974d1b5a1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/46ffe711fbc2f9f026454387c96ae7e6a94301f9/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/a34002a0b1619e73acd842516f4d0f09f7d1bb1f/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/2a5ffbe88aa4536e15ac24db846040c552bb1a7d/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/350bdbe5b6016977b3f9b8a337bb97ae4cae89ad/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/852ce267f73fd1560cc0c719876f0b36cc411950/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/dd5335026e40133531df1ca2ce64972647fcce8d/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/54e0269a8ca5559b38a28b6a87e84f3bae7c9652/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/064e3882e7fa82ca25739d6d707796af34cc7dc2/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/25ca3c6fffde31d71002c30ed69563188770a42c/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/f3ec8e111aae5986d2489abd1d490cb520bfc3f4/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/643a31e1908f55c375632749e027aa5fd88e6aa4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/6ea5cdc7d75839520b12a1691de3d72612987fc2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/589ae53931d2184bc2a348de4f8dd4c637e55299/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/691a7ab8f538f23b7aed9fafac2a5c709431b148/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/162d7bad816399bab39059ec98ad07e2/raw/6342cf18c16b8611313ae941692c890e45e4fd6a/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10699/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/51cf7a6bc0c0911b47ce40880509d176bb194ef8/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/fd99789ec81998c362cf77b7be0693d09b7fe597/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/6fc7dfb876bc37eacb550a547e6d1dadbd3a09d6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/a200526a2667dfd9b644dbec0e974a5b4b733813/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/331a335e1eabaa638afd3eadd5df5df42ebac51c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/762eb0bf9b48d91f05144205e78b8a328a21db0c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/29dc5f183998ece5e5544b46c0bcbdd409c05f45/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/d310412b7c81ee42e4190e7602c1bdd00dcfbf02/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/98736ebfe98cfc91dd5bfd60835420ad0e9bb752/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/6b01942d6f7739a276df064648fd65be62ae2e12/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/fa15f62ce2c1440ec15e53994d7bfd6fc993725c/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/2bdf52419c6119eeff8d9f5ecad484d8ec632bbd/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/ed6da00727b6a3fb2a417af0c90644565f5d9e53/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/a0201e5a081952cbd9520c1c63fb83ec1ffc1aeb/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/9ef5186df91e4f6ccccf8ed1281c14b328d5074b/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/658cd5287dd0acc8c48cb89319d375574ffb2bb6/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/5ae8d534251a6ac53945edc6e213c69500e9d9c8/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/2f1f0beaa277b1dc5d42fba417902d068d6c0b94/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/7b11df8ee9e1484bdfe2b5d118117edc1fcb06d1/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/9a3ae326f90b37fa83a98def7e1e9b7f15288520/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/441f8e1a6dbc4c364882b252145fe69f70766a20/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/51ff6d7e2fe8bb1c18b0a338541bee0a1500466b/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/461eea524f29b08bad6952573628c3545b59d880/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/51a987a8a26b808d179c095775bc7f6917bde0f7/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/f5a3324d59f72d9d2fe0b41df71bfa7b1292fac7/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/853f4bee0bbbb7e79950e8398f1fd0f3c6adf2b0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/97e3035b87f7a770fb33a0351461827ee134f7c0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/7bb40d8fd3e081468db794cbaa5028ddb00da089/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/b6916b0eaf8bc17e828c0edc931348d52b36899c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/4eae6a53428f8a2a6e33bcaa182d49b74ff927d0/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/505a6176f9f6512f5919ad9c5936ca801b9a47a3/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/927a50974d273dda4a1430ec14de53d602e4b2d9/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ea63679ce633fb6b7dd438cd9d853393/raw/b421c6acc31ace65459d798c7ed422b7a971e16c/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
@hoopoepg can you pls review?

**Comment by yosefe** [comment]
yep - i also added fixes for client_server which cause tests to fail

**Pull request merged**
