### PR TITLE
NEWS: News update for v1.10.0 rc5

### PR DESCRIPTION
**Pull request by shamisp**
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe FYI

**Comment by shamisp** [comment]
Ok to test

**Comment by shamisp** [comment]
@yosefe can you please take a look ? Seems like some CI clients stuck

**Comment by yosefe** [comment]
@shamisp i restarted the test earlier, should be done in ~1.5hrs

**Review by yosefe — APPROVED** [review]

**Pull request merged**
