### PR TITLE
UCM: add ROCM hooks

### PR DESCRIPTION
**Pull request by yuq**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9094/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@yuq 
[rocm-build-log.txt](https://github.com/openucx/ucx/files/2925748/rocm-build-log.txt)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9113/ for details (Mellanox internal link).

**Comment by yuq** [comment]
Hi, could anybody tell me what's wrong now?

**Comment by bureddy** [comment]
bot:retest

**Comment by bureddy** [comment]
build timeout (200 mins) on one server. not sure if related to load, triggered rebuild

```
16:43:32 [ RUN      ] udx/test_ucp_wireup_1sided.stress_connect/0
16:46:06 Build timed out (after 200 minutes). Marking the build as failed.
16:46:06 Build was aborted
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9132/ for details (Mellanox internal link).

**Pull request merged**
