### PR TITLE
UCP: Extract common code in tag matching.

### PR DESCRIPTION
**Pull request by yosefe**
related to #1147

### CODE REVIEW

**Comment by yosefe** [comment]
@evgeny-leksikov @brminich pls take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1367/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3308/ for details (Mellanox internal link).

**Comment by brminich** [comment]
:+1:

**Pull request merged**
