### PR TITLE
Some cosmetic changes in comment

### PR DESCRIPTION
**Pull request by Honggang-LI**
Fixed some typos and deleted some outdated comments.

### CODE REVIEW

**Review by yosefe — COMMENTED** [review]
Thanks for the contiribution! The fixes are good, but pls fix commit titles perf guidelines (the words before ':' should be in capital letters), see the check failure : https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=25551&view=results
In addition, in order to contribute code to UCX need to sign a CLA, pls see more details in https://github.com/openucx/ucx/blob/master/.github/CONTRIBUTING.md

**Comment by Honggang-LI** [comment]
> Thanks for the contiribution! The fixes are good, but pls fix commit titles perf guidelines (the words before ':' should be in capital letters), see the check failure : https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=25551&view=results

I fixed the commit titles. All commits pass code style CI check.

> In addition, in order to contribute code to UCX need to sign a CLA, pls see more details in https://github.com/openucx/ucx/blob/master/.github/CONTRIBUTING.md

All commits have 'Signed-off-by' tag. Is it not enough?

https://live-openucx.pantheonsite.io/wp-content/uploads/2019/05/ucx-individual-contributor-agrement.pdf

I don't know how to sign it. Print it, sign it and then send a photo of it to you? Or just leave a message say "OK, I agree the CLA" in the comment?

Thanks

**Comment by yosefe** [comment]
> All commits have 'Signed-off-by' tag. Is it not enough?
> 
> https://live-openucx.pantheonsite.io/wp-content/uploads/2019/05/ucx-individual-contributor-agrement.pdf
> 
> I don't know how to sign it. Print it, sign it and then send a photo of it to you? Or just leave a message say "OK, I agree the CLA" in the comment?
> 
> Thanks

Unfortunately, signed-off-by tag is not enough
@shamisp can you pls help with the CLA? Honggang is with Redhat.

**Comment by shamisp** [comment]
@Honggang-LI can you please email the copy of sign CLA to UCF Administration <admin at ucfconsortium.org>. Just to clarify - do you sing the corporate version or individual contributor ? Once it is emailed, please let us know in the ticket. thanks !

**Comment by Honggang-LI** [comment]
> @Honggang-LI can you please email the copy of sign CLA to UCF Administration . 

What is the email address of UCF Administration?

> Just to clarify - do you sing the corporate version or individual contributor ? Once it is emailed, please let us know in the ticket. 

I will sing the version of individual contributor.

thanks

**Comment by shamisp** [comment]
> > @Honggang-LI can you please email the copy of sign CLA to UCF Administration .
> 
> What is the email address of UCF Administration?

UCF Administration: admin@ucfconsortium.org

> 
> > Just to clarify - do you sing the corporate version or individual contributor ? Once it is emailed, please let us know in the ticket.
> 
> I will sing the version of individual contributor

No problem

**Comment by shamisp** [comment]
@yosefe I received copy of CLA.

**Comment by shamisp** [comment]
Fixes look fine as well.

**Review by yosefe — APPROVED** [review]

**Pull request merged**
