### PR TITLE
CLEANUP: remove unused ptmalloc283

### PR DESCRIPTION
**Pull request by amaslenn**
We have ptmalloc286.

(cherry picked from commit a03a496daaf89bad67553edb10f758f4bfa285d3)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4889/ for details (Mellanox internal link).

**Comment by amaslenn** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4892/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
what is the failure ?

**Comment by amaslenn** [comment]
```
16:42:18 Build timed out (after 150 minutes). Marking the build as failed.
16:42:18 Build was aborted
```

**Comment by yosefe** [comment]
failure due to #1641

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4895/ for details (Mellanox internal link).

**Pull request merged**
