### PR TITLE
JUCX: Use our own checkstyle rules.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Remove Apache license and use our own rules. A small subset for now.

## Why ?
As discussed

### CODE REVIEW

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8938/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8939/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@petro-rudenko @shamisp is this OK to remove Apache license? since the file we use is not fully deleted, just partially edited..

**Comment by petro-rudenko** [comment]
@yosefe i've added rules from scratch there.

**Comment by petro-rudenko** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8984/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8987/ for details (Mellanox internal link).

**Pull request merged**
