### PR TITLE
UCP: adds dc_x alias

### PR DESCRIPTION
**Pull request by alex-mikheev**
@yosefe please approve

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2413/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1752/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
:+1: MellanoxLab failure is unrelated

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by alinask** [comment]
don't need to add regular dc to the UCX_TLS list?

**Comment by yosefe** [comment]
@alinask it's already there as the name of the transport - no need to have alias for it

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1757/ for details (Mellanox internal link).

**Comment by boehms** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1766/ for details (Mellanox internal link).

**Pull request merged**
