### PR TITLE
UCP/UCT/GTEST: Minor fixes

### PR DESCRIPTION
**Pull request by brminich**
- UCP/TAG: Do not use separate request union for AM rndv, because ucp_do_am_z/bcopy_multi use ucp_send_request_get_next_am_bw_lane which use req->send.tag union.

- GTEST/UCP/TAG: Use all tls for offload_multi test

- UCT/RC: Use macro instead of magic number

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6109/ for details (Mellanox internal link).

**Comment by brminich** [comment]
the failure is #2237

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6111/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@hoopoepg, plz review

**Comment by yosefe** [comment]
@brminich do we need to for v1.3.x branch too?

**Comment by brminich** [comment]
I'd say no. Union related bug does not provoke any errors, because `rndv_data.rreq` overwrites `tag.tag`, which is not used for AM rndv.

**Pull request merged**
