### PR TITLE
GTEST: Adding a hint that DIR can be specified as an input

### PR DESCRIPTION
**Pull request by shamisp**

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe , please take a look

**Comment by shamisp** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/934/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/349/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/350/ for details (Mellanox internal link).

**Pull request merged**
