### PR TITLE
RELEASE: Updated NEWS for 1.17

### PR DESCRIPTION
**Pull request by shasson5**
## What
Updated NEWS for 1.17

## Why ?
Release 1.17

### CODE REVIEW

**Review by brminich — APPROVED** [review]

**Review by tvegas1 — APPROVED** [review]
compared content with #9956

**Review by yosefe — APPROVED** [review]

**Comment by shamisp** [comment]
LGTM

**Comment by shamisp** [comment]
What about AUTHORS update ?

**Comment by shasson5** [comment]
> What about AUTHORS update ?

will be done in separate PR

**Pull request merged**
