### PR TITLE
UCS/QUEUE: Fix queue_del_iter / ucs_queue_for_each_safe()

### LINKED ISSUE #504: infinite loop in ucs_queue_for_each_safe
commit c78d39814bb89f360b7a169a46081c2f6cef7709 introduced a bug that the queue does not stop when reaching the end, if the last item is deleted and its "next" is pointing to itself.

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #504

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1140/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/557/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
just noticed i have comment-leftover. need to fix.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1142/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/560/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1148/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1163/ for details.

**Pull request merged**
