### PR TITLE
UCS/DEBUG: Print extended signal information.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1185/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/605/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp @miked-mellanox pls review

**Comment by miked-mellanox** [comment]
:+1:

**Comment by shamisp** [comment]
This will bite us when we will work on portability...

**Pull request merged**
