### PR TITLE
UCM/TEST: Malloc hook and rcache fixes.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by MattBBaker** [comment]
autobot build

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1364/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/754/ for details (Mellanox internal link).

**Comment by MattBBaker** [comment]
All failures were the same. 

Feynman6: 
[ RUN      ] malloc_hook.fork
[     INFO ] Reduced heap free space to minimum: 13360 after allocating 10000 bytes
ucm/malloc_hook.cc:179: Failure
Expected: (m_map_size) > (0lu), actual: 0 vs 0
process 0/4
ucm/malloc_hook.cc:194: Failure
Expected: (total_ptrs_in_range) > (0u), actual: 0 vs 0
[     INFO ] process 0/4: small mapped: 0, total mapped: 83894272, total unmapped: 83894272
ucm/malloc_hook.cc:179: Failure
Expected: (m_map_size) > (0lu), actual: 0 vs 0
process 1/4
ucm/malloc_hook.cc:194: Failure
Expected: (total_ptrs_in_range) > (0u), actual: 0 vs 0
[     INFO ] process 1/4: small mapped: 0, total mapped: 83894272, total unmapped: 83894272
ucm/malloc_hook.cc:179: Failure
Expected: (m_map_size) > (0lu), actual: 0 vs 0
process 2/4
ucm/malloc_hook.cc:194: Failure
Expected: (total_ptrs_in_range) > (0u), actual: 0 vs 0
[     INFO ] process 2/4: small mapped: 0, total mapped: 83894272, total unmapped: 83894272
ucm/malloc_hook.cc:179: Failure
Expected: (m_map_size) > (0lu), actual: 0 vs 0
process 3/4
ucm/malloc_hook.cc:194: Failure
Expected: (total_ptrs_in_range) > (0u), actual: 0 vs 0
[     INFO ] process 3/4: small mapped: 0, total mapped: 83894272, total unmapped: 83894272
ucm/malloc_hook.cc:309: Failure
Value of: ((((*(int *) &(status))) & 0xff00) >> 8)
  Actual: 1
Expected: 0
Process 0 failed
ucm/malloc_hook.cc:309: Failure
Value of: ((((*(int *) &(status))) & 0xff00) >> 8)
  Actual: 1
Expected: 0
Process 1 failed
ucm/malloc_hook.cc:309: Failure
Value of: ((((*(int *) &(status))) & 0xff00) >> 8)
  Actual: 1
Expected: 0
Process 2 failed
ucm/malloc_hook.cc:309: Failure
Value of: ((((*(int *) &(status))) & 0xff00) >> 8)
  Actual: 1
Expected: 0
Process 3 failed
[  FAILED  ] malloc_hook.fork, where TypeParam =  and GetParam() =  (14 ms)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1366/ for details.

**Comment by miked-mellanox** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/756/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1369/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/759/ for details (Mellanox internal link).

**Pull request merged**
