### PR TITLE
UCT/IB/UD: Remove unneeded ECN flag

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Remove unneeded ECN flag.

## Why ?

It is not used.

## How ?

1. Remove `UCT_UD_PACKET_FLAG_ECN` flag.
2. Remove all mentions of ECN in UD code.

### CODE REVIEW

**Review by yosefe — COMMENTED** [review]
IMO for compatibility, better keep this flag in the wire protocol, even if currently unused

**Comment by dmitrygx** [comment]
> IMO for compatibility, better keep this flag in the wire protocol, even if currently unused

do you mean for future usage?
I saw this wasn't used even in UCX 1.2

**Comment by yosefe** [comment]
> do you mean for future usage?

yes, for future usage

**Comment by dmitrygx** [comment]
> > do you mean for future usage?
> 
> yes, for future usage

btw, we don't have a special handling for it. we will ignore if smth unknown was received.
but we print `E` bit - so, it worse keeping it as is

**Comment by yosefe** [comment]
if we just remove, it could get reused it for smth else. IMO the cleanup benefit is not worth it, in case of something that affects wore format.

**Pull request closed without merging**
