### PR TITLE
UCP/UCT/API: Change UCT pending queue interface.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/840/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/265/ for details. (Mellanox internal link)

**Comment by yosefe** [comment]
@shamisp pls review

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
@sssharka @sameerkm can you please review as well. It was discussed during f2f.

**Comment by shamisp** [comment]
@yosefe - the patch implement pending only for CM and no other transports. Will it go as a separate commit ? What about pending infrastructure for tl/base ?

**Comment by yosefe** [comment]
currently only pending for CM is required to make tests pass. Other transports will come later.
The relevant infrastructure is in tl_base.h

**Comment by sameerkm** [comment]
How do I see the changes?

**Comment by shamisp** [comment]
@sameerkm - On the top of the website you have "Files changed". It will open up a page with a diff. On the page you can leave comments. More info here: https://help.github.com/articles/using-pull-requests/

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ucx-pr/863/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/290/ for details. (Mellanox internal link)

**Comment by shamisp** [comment]
:+1:

**Pull request merged**
