### PR TITLE
UCP/CONFIG: Support aliases when selecting transports.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by shamisp** [comment]
autobot build

**Comment by shamisp** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1029/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/456/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
`:` or `-` ? IMHO `-` looks better

**Comment by yosefe** [comment]
bot:retest

**Comment by shamisp** [comment]
did we agree on the format ?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/465/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1036/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/468/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
yep, we can go with tl-x for now and expand it later

**Pull request merged**
