### PR TITLE
UCP/PROTOV2: Don't depend on NO_IMM_CMPL for DATATYPE checks

### PR DESCRIPTION
**Pull request by tvegas1**
## What
Check datatype field independently from no immediate completion flag.

## Why ?
Reported by #9626.

### CODE REVIEW

**Comment by tvegas1** [comment]
> seems that `UCP_OP_ATTR_FLAG_NO_IMM_CMPL` is not really supported for `put_nbx` can you pls fix it in this pr then?

it is supported inside `ucp_put_send_short()` so we should be good i think.

**Comment by brminich** [comment]
> > seems that `UCP_OP_ATTR_FLAG_NO_IMM_CMPL` is not really supported for `put_nbx` can you pls fix it in this pr then?
> 
> it is supported inside `ucp_put_send_short()` so we should be good i think.

indeed, then can we move `attr_mask` initialization to protov1 section to avoid unneeded overhead for protov2?

**Comment by tvegas1** [comment]
> indeed, then can we move `attr_mask` initialization to protov1 section to avoid unneeded overhead for protov2?

makes sense, removed it altogether.

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
@tvegas1 can you pls squash?

**Pull request merged**
