### PR TITLE
JENKINS: Increase UD timeout to make ucp_hello_world stable

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Increase UD timeout for `ucp_hello_world -e` test

## Why ?

Make `ucp_hello_world -e` test more stable
i.e. this fixing the following errors happened from time to time (e.g. on `boo31` jenkins node):
```
19:12:48 + ./ucp_hello_world -e -n boo31 -p 10002
19:12:48 INFO: UCP_HELLO_WORLD mode = 0 server = boo31 port = 10002
19:13:50 UCX_NET_DEVICES=all
19:13:50 UCX_SHM_DEVICES=all
19:13:50 UCX_ACC_DEVICES=all
19:13:50 UCX_SELF_DEVICES=all
19:13:50 UCX_TLS=all
19:13:50 UCX_ALLOC_PRIO=md:sysv,md:posix,huge,thp,md:*,mmap,heap
19:13:50 UCX_SOCKADDR_TLS_PRIORITY=rdmacm,*
19:13:50 UCX_SOCKADDR_AUX_TLS=ud,ud_x
19:13:50 UCX_WARN_INVALID_CONFIG=y
19:13:50 UCX_BCOPY_THRESH=0
19:13:50 UCX_RNDV_THRESH=auto
19:13:50 UCX_RNDV_SEND_NBR_THRESH=256K
19:13:50 UCX_RNDV_THRESH_FALLBACK=inf
19:13:50 UCX_RNDV_PERF_DIFF=1.000
19:13:50 UCX_MAX_EAGER_RAILS=1
19:13:50 UCX_MAX_RNDV_RAILS=2
19:13:50 UCX_RNDV_SCHEME=auto
19:13:50 UCX_ZCOPY_THRESH=auto
19:13:50 UCX_BCOPY_BW=5800M
19:13:50 UCX_ATOMIC_MODE=guess
19:13:50 UCX_MAX_WORKER_NAME=32
19:13:50 UCX_USE_MT_MUTEX=n
19:13:50 UCX_ADAPTIVE_PROGRESS=y
19:13:50 UCX_SEG_SIZE=8K
19:13:50 UCX_TM_THRESH=1K
19:13:50 UCX_TM_MAX_BB_SIZE=1K
19:13:50 UCX_TM_FORCE_THRESH=8K
19:13:50 UCX_NUM_EPS=auto
19:13:50 UCX_RNDV_FRAG_SIZE=256K
19:13:50 UCX_MEMTYPE_CACHE=y
19:13:50 UCX_FLUSH_WORKER_EPS=y
19:13:50 UCX_UNIFIED_MODE=n
19:13:50 [0x583ae700] local address length: 274
19:13:50 [1560874430.442560] [boo31:19131:0]     ucp_worker.c:506  UCX  ERROR error 'Endpoint timeout' will not be handled for ep 0x7fb255ffb000 - rc/mlx4_0:2 since no error callback is installed
19:13:50 [boo31:19131:0:19131]    ud_iface.c:755  Fatal: transport error: Endpoint timeout
19:13:50 
19:13:50 /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
19:13:50       ...
19:13:50        33     }
19:13:50        34 
19:13:50        35     ucs_handle_error(message_buf);
19:13:50 ==>    36     abort();
19:13:50        37 }
19:13:50        38 
19:13:50        39 void ucs_fatal_error_format(const char *file, unsigned line,
19:13:50 
19:13:50 ==== backtrace (tid:  19131) ====
19:13:50  0 0x000000000003c088 ucs_fatal_error_message()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/ucs/debug/assert.c:36
19:13:50  1 0x000000000003c18f ucs_fatal_error_format()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/ucs/debug/assert.c:52
19:13:50  2 0x000000000001ed42 uct_ud_ep_dispatch_err_comp()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/uct/ib/ud/base/ud_iface.c:755
19:13:50  3 0x000000000001ee42 uct_ud_iface_dispatch_async_comps_do()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/uct/ib/ud/base/ud_iface.c:777
19:13:50  4 0x0000000000028d7e uct_ud_iface_dispatch_zcopy_comps()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/uct/ib/ud/base/ud_iface.h:446
19:13:50  5 0x0000000000028d7e uct_ud_verbs_iface_progress()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/uct/ib/ud/verbs/ud_verbs.c:381
19:13:50  6 0x0000000000021632 ucs_callbackq_dispatch()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/ucs/datastruct/callbackq.h:211
19:13:50  7 0x0000000000022e71 uct_worker_progress()  /scrap/jenkins/workspace/ucx-temp/label/boo31/worker/1/contrib/../src/uct/api/uct.h:1917
19:13:50  8 0x0000000000401d75 wait()  ucp_hello_world.c:0
19:13:50  9 0x0000000000402092 run_ucx_client()  ucp_hello_world.c:0
19:13:50 10 0x00000000004027e1 run_test()  ucp_hello_world.c:0
19:13:50 11 0x0000000000402cf9 main()  ???:0
19:13:50 12 0x000000347981ed1d __libc_start_main()  ???:0
19:13:50 13 0x00000000004016d9 _start()  ???:0
19:13:50 =================================
19:13:50 [boo31:19131:0:19131] Process frozen...
```

## How ?

`export UCX_UD_TIMEOUT=1s` -> `export UCX_UD_TIMEOUT=15s`

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10702/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:pipe:retest

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/9f0e7a7d6be9655f88eb75b237a0eb35b98c890b/_main) | :question: ABORTED
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/cc39bac6f0b17be83b705ad739d6a88bf6e60db5/hpc-test-node2_W1) | :question: ABORTED
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/e57d47cf8004ebd5f942c8324fd820ba5514d086/hpc-test-node3_W0) | :question: ABORTED
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/b9474434e3d091247e21a5fb214c984f56e3155a/hpc-test-node3_W1) | :question: ABORTED
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/d9a59d27d60e75474cc0342ba49d63be012c4c39/hpc-test-node3_W2) | :question: ABORTED
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/102a678c864200c26b4f0eaa684a1a79a39348d1/hpc-test-node3_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/6546d6987187fe235da42eb43a7b8e4ddd9daea9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/73c60e9abbbf6844f9b37f1d8ba1218f1b135e25/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/a7e5e3544108f511594aeaadf7e56af0ea33af3b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/fd9e3c40aee1b64e31c315d3ef0ad13b57a11fd3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/77d29bd28fda1e253c0b5f6e0a4c0c734b5fceb0/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/558101dd42978c3f3740fad73124abd3999bdbe5/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/a8efd24a59877e85b56af8de365580e1c6388a48/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/51ae044d0011d7f973c5c44bcc5dab90d4406655/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/e699bdbc9e4cb637711bec3d1c21def0c661c15f/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/f9f7f10d7a2d92dd8bb245b2f231c2b4f6987ef6/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/293d64368468c81e972121f0e63846bd7e70636a/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/6cd61a9bd3ec8e8092a62cea391ad7e13455d3e3/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/9644a7dd10188bca135a4b770f3a5643509d65fb/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/19bfa24401b0549f7c0c058520dd2189c951d59d/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/0b69c64f38815b29d31943c2586414088d6161e7/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/56a10ec3151ee0a60032ec141d59bb58ae64e5df/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/e89d4f9e49c6595546df437f79b448eaa4ffe59d/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/f82c86d6f2737980a2f5b9b1f4b8483a48e125ea/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/1f84df0d1c10abf2cfe9c70084b52f864604cc76/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/108a4c297d728492536dca267f2ad5b5a4168845/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/b751d7bf96a8b9bb8b7f4f8334b2a36c67f2c2c3/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/ff066d8716e2047d15ae0951185b1588154c6d4a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/28693790a9fa7f226097e182842b5383e1389b4d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/4138cb75b078b49e1d25e9f8e4a11a529d2b6ff6/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/74792f823739774b096fac7bc302c8c7b2ea90ac/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/30d2f34c44962dd3c1626d7a89ad1d47c4ac449b/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4834d89f675a0d57f52e7c129e466dde/raw/0bf8f41c56e88c95ec8841b4e994ef17aec392c0/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
> Test FAILed.
> See [http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10702](http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10702/) for details (Mellanox internal link).

there was an unrelated failure:
```
[2019-06-19T10:25:35.958Z] checking that generated files are newer than configure... done

[2019-06-19T10:25:35.958Z] configure: creating ./config.status

[2019-06-19T10:25:37.787Z] config.status: error: cannot find input file: `src/ucm/cuda/Makefile.in'

script returned exit code 1
```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10708/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/b6e071e4dabd07a41ce439805c74166324927c97/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/d9b46c6bed87a6282b8f34d1e91c0ac50d7cb82f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/132658d8e87111a3da5592b395e6114375413dcc/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/b0eaddec70cbdbe2864cc0218ada322b52ded355/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/64f0a87d76e510a58cdd3ea01f29c718de13bba2/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/c5578bb7406e93e6505f2a6b668a1037f7541e31/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/1f12b846020b910a85a00e641850d890aff8af7f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/54c26975aaff6d7037682ba468fb457a20c054de/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/9452a6813838bf7a99b01ab079e2333e7537e6f5/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/a57ae44399421480582ff9bd0745b72e26bbd744/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/1ba2e91b9484f0951cc12c3615309cabfe3874ec/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/a95f4439cdd2db0b15c90c616a15edb141e69969/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/889c951102040cae32d7b373d01cd1364f778b26/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/d3532ba5656d313f619088ebcab51c3360b0c036/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/544480ba69e94519f28050fb18034530f5431d7e/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/9ea456f25a1ef1dce5b332f0430eb8e672ae3853/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/d5d95e99cdd0aa507296eebf731178caaf29f817/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/1d29d3a6748eb0f1f2a06a54e838eb7175681870/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/2bdf9fd00a5f929d23b8e361380453524601b7cb/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/61affe7d490ea3520de0220d7bb903a88946dec8/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/1b9d052e3370ed9266a4ee4afed55653c1824e8d/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/3e4b99dc62d2231dfe5561f8d66dd81f0fa06787/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/a454e85b521e2e96bbc6f19182a2d36ebe5337de/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/62ea24d6203d7fcad556fb0cda8ed7a47291a047/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/7ac11ba2f6adcf2083d09b7c02973c214c9a0666/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/94b5309d7f0d8c7703b33bb3681857d2735d806d/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/584eff336ab739218e9b2510517019988ed64d58/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/4b9cfead441a6bfe09624adbd74bc594ba261b66/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/afca5e9c5567b9477cb359146d3c99e6e7f8cb87/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/b98de67f11293d88718d35a4d1e4e5885b134a4e/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/6f063b39aa50a4a0c230d4bfbf04fe6066760fe2/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/a7b4cf0fd531af97cfd553b409428a07d3c928c4/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8680177b33df7ed5c5b3de6ef0fad3ac/raw/156120e5f8f89e9a4286f10609267f1bc5a2c1ff/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe ok to merge?

**Pull request merged**
