### PR TITLE
IB/MLX5: Fixing #1470

### PR DESCRIPTION
**Pull request by shamisp**
Adding missing barrier in order to enforce the order of loads

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1695/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3625/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
it is bus fence since you read a register from device.

**Comment by yosefe** [comment]
bus fence is needed only for weakly ordered architecture

**Comment by shamisp** [comment]
then you would have to introduce additional macro at arch, read_barrier_from_dma (similar to verbs) and map it per architecture. FYI, in verbs it is bus barrier as well.  On ARM this is for sure DSB. I'm not positive that on x86 it is just CPU barrier. Most likely not portable.

**Comment by yosefe** [comment]
this macro is currently called "ucs_memory_cpu_load_fence()" , for x86 it covers both loads from DMA and loads from other processor. Do we need to distinguish between the 2 cases for ARM?
in verbs it's rmb() which maps to compiler barrier on x86 and "dsb ld" on ARM

**Comment by shamisp** [comment]
On ARM, if you interact with I/O device, you have to go with bus_load/store (dsb) operations. If you interact with load/stores in respect to other cores (not peripheral devices) you should use cpu_load/store fence (dmb on arm). This is why I would expect that like on the post send flow you use bus_store_fence on the access to CQ you also have to use bus_load_fence

**Comment by yosefe** [comment]
there is a difference when the interaction is done by read/write to MMIO and when it's done over RAM (DMA). What type of barrier is required on ARM in each of those cases?

**Comment by shamisp** [comment]
skype me

**Comment by shamisp** [comment]
I can change it to CPU fence. I will provide the patch.

**Comment by shamisp** [comment]
@yosefe please take a look

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1772/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3710/ for details (Mellanox internal link).

**Pull request merged**
