### PR TITLE
UD: Fix handling a dropped CREQ issue #972

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2387/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1725/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alex-mikheev can you please take a look?

**Comment by alex-mikheev** [comment]
:+1:

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@MattBBaker is the ORNL failure real?

**Comment by MattBBaker** [comment]
@yosefe No, when it came online all the tests ran at once and the usual suspects ran out of memory. Though can you try a ornl specific bot retest? Maybe it just doesn't work for me.

**Comment by yosefe** [comment]
bot:ornl:retest

**Pull request merged**
