### PR TITLE
UCT/CQ-MODERATION: fixed test

### PR DESCRIPTION
**Pull request by hoopoepg**
- fix for https://github.com/openucx/ucx/issues/2033
- increased event moderation limit

### CODE REVIEW

**Comment by hoopoepg** [comment]
bot:ornl:retest

**Comment by yosefe** [comment]
@MattBBaker can you pls post ornl failure?

**Comment by MattBBaker** [comment]
Internal server error.

**Comment by MattBBaker** [comment]
bot:ornl:retest

**Comment by hoopoepg** [comment]
bot:ornl:retest

**Comment by hoopoepg** [comment]
bot:ornl:retest

**Comment by hoopoepg** [comment]
bot:mlx:retest

**Comment by hoopoepg** [comment]
bot:ornl:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/5401/ for details (Mellanox internal link).

**Comment by hoopoepg** [comment]
@yosefe good to go?

**Pull request merged**
