### PR TITLE
GTEST/UCP/SOCKADDR: fix log handlers leak

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
Should fix rdmacm related failures reported in #2872

### CODE REVIEW

**Comment by evgeny-leksikov** [comment]
@shamisp could you check this patch on your system?

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7711/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
hangs in:
```
[       OK ] tcp/test_ucp_wireup_1sided.stress_connect/1 (5339 ms)
[ RUN      ] tcp/test_ucp_wireup_1sided.stress_connect2/0
```

**Comment by shamisp** [comment]
The hang issue might be not directly related to the patch. It occasionally hang even without the patch...

**Pull request merged**
