### PR TITLE
UCT/IB: Add DC and compact AV flags to IB_DEVICE_SPECS

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/9013f438324a6ddaba9c42c5a1ccc0f0aec9f22a/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/03e8518913c8012001786176635df40a42a47877/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/e18ef04b3338c07249aeb133a4e297ce99d5813b/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/bc0be5bd98e79c50e82b3f9e8b349b57ba48fa0d/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/af3984aaad6261900b9c04198c7452ccc2a0d3bc/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/5dabe040c83f66eeeb33b8e410554683a2c1b031/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/1a38dbfb0510666b7e394c3f56cc0f206b3f47ac/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/87cc10165be0e135a9ca89ee67d7a593d40f35ab/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/997900492a169148bce6e8e4b92bc3c8ed8fb682/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/4e38f3de366732e8143f74450733c05981a010c2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/319f3d60a0d43e869a8677a7a9e352c0e86405f1/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/a9742672e0cc69fc17290719f2e7a9332e59caa2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/bd852eaa4d50736c7e70f957c6221b68f711ac24/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/dda42f92bea51300d99df7a737759d3b67936691/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/6d33032701437151a04ed31ae76f121e5ab985c0/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/a1bae14c7449ac41b239821c79939b736e8abe46/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/4c0f012b8d8fd546546291bc6b83abe4ba3a6f5a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/a502b6ccba3b34a4254beddaa4a81d6d69240818/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/f45cb2f4e8cfc54938879872c32cca6887c47f07/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/228dd1aea509b97564b78ee21a51258f225357a1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/53d18432bd9ddeb05ca23abf0267b447b4296b01/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/eec99153e85db019dc542fb719ca449c0e915094/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/1da8feac1f4c0a7ea0af4ec80973555143f4b044/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/9715a809338faf7c7fd7a64f135f51deaeb9da29/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7dcfc9265fe06e8936d06f69a641abb5/raw/0b6423ac7c9740101f83fa45258bab6368595dac/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 20 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/16f5c2bbdaca37aa3e66f5a2cd1e1fa6f13f2a87/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/ba64b2936c22cf1777d20f4a4170019499169506/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/aaa184840f128fa9adaef035c1417a98e185973c/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/878e742fbb0e60f38a1023eafb60e47aae6d2413/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/790ac956ab607104027723be4a3d1d954bc93300/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/d9f7e523e64172aba46c87d375d6caf8ffe8acec/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/5ece765a5f94a5ed06fb1e628bb474fc77ae9006/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/26a481b0cccb431cde0bfef367b0e6d8c8fda9cf/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/cd0070ced8b66ad188e81d63ab6d144dff643e70/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/229fb3b64d32d1aeb1b1fbefc2984f27099cbb11/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/22a9bf7c7126a1849099699a52f27a80ddee8690/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/c111d0acd98a921cc71d54091f9aa5e50e4de241/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/f8c834bc2947119a594956d242a7925e0508a547/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/3b1a1524a976222463876a56a95fcdb55c764e9a/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/f565c37ca807002817ae4ed7b9105aa856a4ed8b/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/83995a2093df542151c01702a29676c7c90617ad/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/14a7e962447bf3e9aa3774f4b71e376ee8945b0e/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/82d7e6640db56526c3e86e0e867c94443c89a7e4/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/cf67dac41b00b6d700d2499a006a405733fe4ddf/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/445b369e1ba6506810d9b44ebcfd55d1/raw/09fd35924e638530936a165362faa320c2f22fee/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/c54abd20bc2f482da1edd7c2e3f350accd63f779/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/6c14e9726b796d84f45ddf549c968598c214e098/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/d07acfa990345de1994c70d9996ef2ec5e233ecb/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/07d8a8306fccd9b8f14263aff42cfbb09aa42af9/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/75cee6e0334cea30b6f9ddda478e4ea4c718a3af/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/6f0cd846bd9b29f99cd13d30f3579710726606fd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/6a4481fdadc5849649e416f29702b3047c52288e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/8699700618d432425ae4c6a27728d57c3aead0b2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/f6e396c974daa5fe4a4141741f51892de32c2bd7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/f9c37902e48b0d910f271ccdbb5cb0ecc5c1523a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/534dd4267cfda0ab3a8b6f291f84ccbdc1ce5c3c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/3375ce90bc00c53ac9d00cfd8c89a9e16bd24ba4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/5d1befb523f425479c0f730cc60e6e56f6afbda2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/e86f5ecbcd6192be66b4cb5a965d0f1cf618e02f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/aa5bbf9d7f793daaabcd5a621caa53bdb42d5f1d/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/e314774ab9a7eae2dac788afec8ba16d0c823144/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/b25b26654fc65acb0d71f416b1c3d97b59cf0da8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/5e98f1596687c16bf82013c3f54fc33e4a1e3056/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/435d3c45b4e28ff745f59fb0b1b3a77286dac503/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/184ed9c3b56eb2bc3a7bff62b82c519eb28c5ff9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/c8493fd3d81a16b7a26d2ba8dcb92aad1c771df2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/1f70ff0265b8da3b3bf4b21b0ecde6392d8e9c05/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/03fe02eecc4bbd763ec7d56e2ab5253511e53b6a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/6f38ab620e194a63ce8c7404aa9af2ff0fd201dc/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/03dfc21742e495e4cbc6087ddae9e427/raw/cd73c23672fbffa9df6a42ce5583162443394499/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Pull request merged**
