### PR TITLE
 UCP/AM: fix zcopy_multi protocol for iov datatype

### LINKED ISSUE #2822: ud/test_ucp_stream.send_iov_recv_data/0 fails
```
20:54:56 [----------] 5 tests from ud/test_ucp_stream
20:54:56 [ RUN      ] ud/test_ucp_stream.send_exp_recv_iov/0
20:54:58 [       OK ] ud/test_ucp_stream.send_exp_recv_iov/0 (2038 ms)
20:54:58 [ RUN      ] ud/test_ucp_stream.send_iov_recv_data/0
20:54:59 [hpc-test-node-upstream:4004 :0:4004] stream_recv.c:365  UCX Assertion `rdesc_tmp.length > 0' failed
20:55:37 
20:55:37 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../src/ucp/stream/stream_recv.c: [ ucp_stream_am_data_process() ]
20:55:37       ...
20:55:37       362     }
20:55:37       363 
20:55:37       364     ucs_assert(rdesc_tmp.length > 0);
20:55:37 ==>   365 
20:55:37       366     /* Now, enqueue the rest of data */
20:55:37       367     if (ucs_likely(!(am_flags & UCT_CB_PARAM_FLAG_DESC))) {
20:55:37       368         rdesc = (ucp_recv_desc_t*)ucs_mpool_get_inline(&worker->am_mp);
20:55:37 
20:56:15 ==== backtrace ====
20:56:15  0 0x00000000000633f1 ucp_stream_am_data_process()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../src/ucp/stream/stream_recv.c:365
20:56:15  1 0x000000000004397f uct_iface_invoke_am()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../src/uct/base/uct_iface.h:523
20:56:15  2 0x000000000004718d uct_ud_verbs_iface_poll_rx()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../src/uct/ib/ud/verbs/ud_verbs.c:336
20:56:15  3 0x000000000001f72a ucs_callbackq_dispatch()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../src/ucs/datastruct/callbackq.h:208
20:56:15  4 0x0000000000687e6d ucp_test_base::entity::progress()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/ucp/ucp_test.cc:521
20:56:15  5 0x000000000057cc6b test_ucp_stream::do_send_recv_data_test()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/ucp/test_ucp_stream.cc:161
20:56:15  6 0x00000000004784f6 ucs::test_base::run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/test.cc:271
20:56:15  7 0x000000000046cb53 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest-all.cc:3562
20:56:15  8 0x0000000000460fcd testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest-all.cc:3635
20:56:15  9 0x000000000046109c testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest-all.cc:3812
20:56:15 10 0x00000000004611ff testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest-all.cc:3930
20:56:15 11 0x0000000000465b97 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest-all.cc:5802
20:56:15 12 0x0000000000465e9b testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest-all.cc:5719
20:56:15 13 0x000000000040f64e main()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-upstream/worker/0/contrib/../test/gtest/common/gtest.h:20059
20:56:15 14 0x0000000000021c05 __libc_start_main()  ???:0
20:56:15 15 0x000000000044b75f _start()  ???:0
```

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
 - Fix zcopy_multi protocol for iov datatype, do not send the empty tail. 
 - New gtest for this.
 - Fixed ucp::data_type_desc_t usage in stream tests

## Why ?
https://github.com/openucx/ucx/commit/8e5225022a0b3d432486a5e1973ce3d2353b5495 fixes #2822

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7944/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
```
20:29:35 Error: WRAPPER_ESCAPE:
20:29:35 path:/scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node2/worker/3/test/gtest/ucp/test_ucp_stream.cc:532:
20:29:35 cond_true: Condition "size < 65536UL /* max_size */", taking true branch.
20:29:35 path:/scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node2/worker/3/test/gtest/ucp/test_ucp_stream.cc:537:
20:29:35 cond_true: Condition "j < 8UL /* iov_num */", taking true branch.
20:29:35 path:/scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node2/worker/3/test/gtest/ucp/test_ucp_stream.cc:538:
20:29:35 cond_true: Condition "j % 2 == 0", taking true branch.
20:29:35 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node2/worker/3/test/gtest/ucp/test_ucp_stream.cc:539:
20:29:35 escape: The internal representation of local "buf" escapes into "v[j].buffer", but is destroyed when it exits scope.
20:29:35 + echo 'not ok 1 Coverity Detected 1 failures # http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node2,worker=3/7944//artifact/cov_build_7944/output/errors/index.html'
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7958/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7961/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7965/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
Not related failures should be fixed by #2958
bot:mlx:retest

**Comment by evgeny-leksikov** [comment]
timed out and #2958 
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7978/ for details (Mellanox internal link).

**Pull request merged**
