### PR TITLE
UCT: allow to destroy EP from error handling callback

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
@brminich @yosefe pls review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1488/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1489/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3410/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3411/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
Looks for for me.

**Pull request merged**
