### PR TITLE
Add some files to .gitignore

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Add some files to `.gitignore` file

## Why ?

To show fewer files when running `git status`

## How ?

Add to `.gitignore` the following files:
1. etags default filename - `TAGS`
2. autogenerated xml, tex and script files
3. binary files

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10851/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/06995c21c63c6ab5e431515a3d2bb94639ff06c2/_main) | :question: ABORTED
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/0110561f24c0cfc9c475b8e6b6114248a9769d12/boo31_W1) | :x: FAILURE
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/8c349197989f3d5c377d85d93c0ce3b18e99857e/boo31_W3) | :x: FAILURE
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/65018f959a819c16455eaaed77fe75abaa842e85/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/f8343efc10fb17b7b3a2d5446fefce47491696ab/boo31_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/f469e769d0f7d6904fa6622f116e63df5d171056/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/f8afb71863c248cb38da2f08b2894271e66e67ad/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/d40c621665845abde788bfd53b8641dfca61b754/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/89320a1678536b553bf10c33be55fd37dc1fb933/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/dd0b2d3b051d515c08db19ceed47f93ac8ad7552/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/5d240456540cc80ec13e75f09eb0068c3dc3da6f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/601f240085ba84d43dec0bf18c3bf04d7fe85ad6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/c90f9b2c8a4dbc543a31c553726b85fe36a27457/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/d9d76323b52db1ec45cacedffbdb967d1c7a0eb9/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/f473cfcc3c767e4399ca81d10f7bd9d124c857dd/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/3109f3897f97da2c93bcdc8118eac11dbe62e358/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/042aeaf814b5a819e8957499c575bb121b9de26c/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/a9c691b33c7dac2c41d66a5284e075560675d65c/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/24828c9d087226001f4ed9c68965f6346936b629/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/7ef564b64a616c7fc1ffeb520a25aa29bb9a8ab3/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/9c80b15713fd2236d1eab2c900474996b3513894/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/ade84349f55085bae3d232f0f14daa118be5f422/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/35b8218823cd6191e024a90a296f456d306d9d1b/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/d828d15ae38d0735b2cd2a12b9670090e076aeb2/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/d96546d3870787f2696097eaead2d75d9264d31b/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/06a046faf819ee55917af7fa300db5043983e711/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/fa93dfc66dea03ec7e90dfb9af6bbfe3152421be/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/a2ec5d9e6a17977fbd862aa1af4f1ceba5afc5c7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/77342463febcb26638b5973c6428eaa03459dbd8/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/3b9e85eaf53b58f51606aaa69f84453fc2353140/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/b61643812a9fd519185b2019829b821c8e2896c4/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/b4b6466770d21fd400d471c2ffb343a538b0acc5/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b1a0653f13273ecb2833aa333580cac5/raw/870dca158e62674ef84d4afc1d47e328325a8ab3/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10872/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/593e5c83efaf67db2b0e128d446fb95bddf7c8b7/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/263a9951be330e107e1a8726eaa6414c774c20f3/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/cefa7d7c5de4ae60808260ecf804536521fae011/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/3ee547b215de19e5d464c31087a5201d8d72e9d9/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/09b3c8ae6005d6990362cc5b6230e5781918cedf/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/ae496e00824a959db56cde8fa6331b85eb5e52a0/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/4cf65ee098f51a0083385c422b0f41c4e4c5f1b4/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/39e8359cacd377adac12fd6dc8956d4902ba62bd/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/b58814306e07eb9a09fee29c1d312894ba8b1a6a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/724bf3a5bad86398249a413928cc36fb311ac8ee/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/c1441679ca6faff8a37af2654abb778e0a19ded2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/61dc005e89dae7eec7ca8de69570f2cb96c7c398/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/7a5e4b6cf81ebc1e9d3a99b03a50db59dab46dc2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/e63d4c656c21e43ee6a396c66e224424b9c71dfc/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/ac028d3179add9b85ccbdcad864884ed67db775e/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/c1ecb8e18983b82e7333326cfed217cef1e51ee8/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/5140a1e77b22d3315df45bb21251e2706b48e238/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/eddf0be1bc6811b76d4a1ea5f04b752de6b01b10/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/406c0976c2f8eed898c059fe75732b7501ae230f/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/390b4e80a1ab92c5ef5a4a655782ea080b35ab13/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/f21b88f24adec0fcf8ff2e6ccc9ac10685d15cef/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/537b2d4c4f2c31983009183bc06ba5563bb9a29b/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/102facd93ef2318225801890b7c291c26e0c9e4d/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/31f1c66c26c03993de792526ab6ba17cd0d35183/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/501ba3e7ce08a5a640588d3e94a532226b28fb2b/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/c0da7edfde3af1a5b829f77708a3b390665807ec/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/9ba65db4a55841da22b605ba00b25373d755fe87/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/ee96b992b9435e19f6bc3baa79b93c6569054e1a/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/77a5cd8ac2cb2d0b7760b3b6dc456b4c4cd32adb/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/6c374cedf98a24b8041be24d818b6b42062417fd/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/1e457ef249667e17f042cb275c9933db52c71bfb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/3d489aa2a238c365d55efb95e1e3a38c1b83ad4c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/4f60d98771ce50e3aaa7f497ae5c2cfe58f38b71/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/d3bfcb070461b29ddebf549f9375fc90e006a214/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/c271b4fda368e322c7fc9763492a23db64ab0037/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/65936a9ed48bea96aff06cbbe7d1cbf2f6b4fac4/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/235b9e123d6584627a05b27ce25f3def/raw/c1ff1fbdc5dea560973e045a05e4b495ae09e40d/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe ok to merge?

**Comment by hiroyuki-sato** [comment]
Hello, @dmitrygladkov 

What do you think to add `modules`?
I tested your branch. 

```
autogen.sh
contrib/configure --disable-numa
make -j 4
```

```
git status
```

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

  modules/
```

I'll appreciate if you add the following entries.
(I'm using GNU global and vim)

```
GPATH
GRTAGS
GTAGS
*.swp
```

Best regards.

**Comment by yosefe** [comment]
@hiroyuki-sato merging this for now, you are welcome to submit PR with any other files you'd like to add to .gitignore :)

**Pull request merged**
