### PR TITLE
AUTHORS: Add Hiroyuki Sato

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
## What

Add my name as a developer.

### CODE REVIEW

**Comment by dmitrygladkov** [comment]
ok to test

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10340/ for details (Mellanox internal link).

**Comment by shamisp** [comment]
@hiroyuki-sato thanks for you contributions.

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
